### ISSUE TITLE
[🐛 Bug]: driver.execute_script and execute_async_script return prematurely with use of window.confirm or prompt

### ISSUE THREAD

**Issue by gilesjohn** [SeleniumHQ/selenium#10026]
### What happened?

When a script, run by driver.execute_script or driver.execute_async_script, uses either window.confirm() or window.prompt() both execute_script and execute_async_script return instantly with no value.

I have tested with both ChromeDriver and GeckoDriver using Python.

### How can we reproduce the issue?

```shell
# Python script to reproduce
from selenium import webdriver
driver = webdriver.Firefox()
result = driver.execute_script("window.confirm('something'); return 'result';")
# result == None
result = driver.execute_script("console.log('something'); return 'result';")
# result == "result"
```

### Relevant log output

```shell
Unsure what to include here
```

### Operating System

Windows 10

### Selenium version

Python 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 94.0.1, Chrome 95.0.4638.69

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.30.0, ChromeDriver 95.0.4638.54

### Are you using Selenium Grid?

None

**Comment by AutomatedTester** [comment]
This is going to need to be raised with the chromedriver and geckodriver teams but I expect they will say that is how it needs to be due to the fact that  modal dialogs can block the main thread in the browser. They won't want it to be blocking the main thread. I hear there be dragons there.

Feel free to comment the issues that you raise back in this issue.
