### ISSUE TITLE
Click command not working

### ISSUE THREAD

**Issue by annasuc** [SeleniumHQ/selenium#1005]
I am using selenium webdriver and testng for data driven testing along with java. One method is parameterized to be invoked mutliple times using dataprovider annotation. During the test execution on firefox and after 50 iterations, a selenium command (for example a click on a button) is called but didn't work correctly to fire the click event in the application, and no error is generated. Any idea on what can be the cause behind it.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
