### ISSUE TITLE
[🐛 Bug]: TimeoutException while working with alert with ChromeDriver v96

### ISSUE THREAD

**Issue by AvallaSD** [SeleniumHQ/selenium#10074]
### What happened?

Hi! 
I updated Chrome Browser and ChromeDriver to v96 and code worked before throwed the TimeoutException. 
Would you kindly solve this problem, or explain how to do it myself?

### How can we reproduce the issue?

```shell
alert = ExpectedConditions.AlertIsPresent().Invoke(driver);
alert.Accept();
```

### Relevant log output

```shell
Message: 
    OpenQA.Selenium.WebDriverTimeoutException : timeout: Timed out receiving message from renderer: 60.000
      (Session info: chrome=96.0.4664.45)
```

### Operating System

Windows 10

### Selenium version

C# 3.141.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 96.0.4664.45

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 96.0.4664.4500

**Comment by titusfortner** [comment]
We are no longer maintaining Selenium 3, so there is nothing we can change in the code to make this work for you, even if it were a Selenium issue (I don't actually know what the cause of your issue is).

The recommendation for .NET bindings is to create your own anonymous functions for waits with Selenium 4. You can find a number of posts for how to do this, here's one of them: https://www.ontestautomation.com/on-no-longer-wanting-to-depend-on-expectedconditions-in-my-c-selenium-webdriver-tests/
