### ISSUE TITLE
[🐛 Bug]: FirefoxDriverService.cs one line change breaks geckodriver ConnectToRunningBrowser

### ISSUE THREAD

**Issue by deadmike** [SeleniumHQ/selenium#10096]
### What happened?

[dotnet] Add --websocket-port command line argument for geckodriver
**argsBuilder.Append(string.Format(CultureInfo.InvariantCulture, " --websocket-port {0}", PortUtilities.FindFreePort()));**

This breaks the firefoxdriver ability to connect to an already open browser when using --connect-existing.

geckodriver: The argument '--connect-existing' cannot be used with '--websocket-port

The websocket-port should not be blindly added when all the other parms are conditional...

### How can we reproduce the issue?

```shell
FirefoxDriverService firefoxDriverService = FirefoxDriverService.CreateDefaultService(browserSettings.DriverLocation);
                    firefoxDriverService.HideCommandPromptWindow = false;
                    firefoxDriverService.Port = 0;
                    firefoxDriverService.BrowserCommunicationPort = 2828;
                    firefoxDriverService.Host = "127.0.0.1";
                    firefoxDriverService.ConnectToRunningBrowser = true;
                    var tmpDriver = new FirefoxDriver(firefoxDriverService, ffOptions);
```

### Relevant log output

```shell
geckodriver: The argument '--connect-existing' cannot be used with '--websocket-port
```

### Operating System

win 10

### Selenium version

latest

### What are the browser(s) and version(s) where you see this issue?

firefox

### What are the browser driver(s) and version(s) where you see this issue?

most recent geckodriver

**Comment by diemol** [comment]
This was added as part of #9817, please report this to https://github.com/mozilla/geckodriver as it would need to be sorted out by the GeckoDriver team, at least as a first step.

**Comment by jgraham** [comment]
If you're trying to connect to an existing firefox instance you can't pass in options that only make sense at Firefox startup time e.g. the websocket server address. So this looks like a problem with the Selenium implementation. I don't see what we could do on the geckodriver side apart from just ignore the argument in this case, but it seems bad to just silently ignore unsupported combinations of arguments.

**Comment by whimboo** [comment]
@diemol based on @jgraham's comment can we please get this issue reopened?

Let me add some more details here. geckodriver is only used to start Firefox and to let it enable the BiDi protocol by passing the `--remote-debugging-port` option as Firefox argument. Then Firefox itself acts as the remote endpoint, and there is no interaction with geckodriver anymore. Clients that want to communicate with Firefox have to directly use the WebSocket connection.

As such using `--websocket-port %random%` doesn't make sense at all because the port as specified here will not be used. It's still the one from when Firefox has been started. Also if Firefox got started without the BiDi protocol enabled, there is no way to do that by connecting to a running instance of it. 

So maybe do not add the argument if a connection to a running Firefox instance is requested.

**Comment by deadmike** [comment]
the problem is that selenium is UNCONDITIONALLY adding that argument. there is NO user control over adding that argument. EVERY single time selenium starts geckodriver it adds **--websocket-port**, forcing breakage, unconditionally, if any other parameter is USER SPECIFIED.

yes, the selenium code has user conditions to control every other parameter, but this one is ALWAYS added, thus when i specify a user parameter I want to use, it breaks. I pinpointed the line and mentioned this here but perhaps you didn't understand: add a user controlled parameter to control whether SELENIUM adds --websocket-port

both sides here seem to be ok with an intentional breaking change that us consumers cannot control. --websocket-port is ALWAY PRESENT, 100% of the time. thereby disallowing every other commandline option you 'support'.

give us a way to control whether that parameter is added, like every other parameter in that source file.

otherwise, this is an intentional breaking fix that everyone talks past each other about and leaves things intentionally broken.

**Comment by jimevans** [comment]
Okay, yes, I see that it’s a bug. Contrary to @deadmike‘s assertion, this break was not intentional; it was done inadvertently with a misunderstanding of how the bidi port should be applied. Without it, none of the new Selenium 4 bidi-based features (network interception, JavaScript console monitoring, etc.) will work for Firefox. I’m sure you’re willing to live with the trade off, so I’ll reopen the issue. I get the frustration, but the assertion of malice and intent, and the accompanying tone, is entirely unwarranted.

**Comment by deadmike** [comment]
@jimevans I didn't state any malice. Intentional is exactly what the change was, however the implementation was flawed.

i've developed code since 1986, it's why I know about this bug. every single bug i've ever written and will write is all intentional, never any malice implied, but honestly speaking, every bug is intended for some purpose that it misses to fulfill. the code is intentionally written, albeit without me realizing it was buggy.

**Comment by whimboo** [comment]
> Okay, yes, I see that it’s a bug. Contrary to @deadmike‘s assertion, this break was not intentional; it was done inadvertently with a misunderstanding of how the bidi port should be applied. Without it, none of the new Selenium 4 bidi-based features (network interception, JavaScript console monitoring, etc.) will work for Firefox.

Note that the argument is only needed when Firefox has to get started by Selenium but not when it's already running. In the latter case it will be up to the user to have started Firefox correctly before with the BiDi protocol enabled. 

From what I can see the `--websocket-port` flag for the service arguments should only be set if there is no `--connect-existing` flag set.

**Comment by titusfortner** [comment]
a4dc6ea54b0b804296db11e524171572d470bd8c
