### ISSUE TITLE
[🐛 Bug]: Selenium 4.0 and 4.1 Relative locators are not working properly starting from December 6 2021, but the same worked fine till November end 2021

### ISSUE THREAD

**Issue by YasodhaNithi** [SeleniumHQ/selenium#10122]
### What happened?

We are using web based application and working in Chrome browser 96.0.4664.93 version. We implemented Selenium relative locators for the project and the same was working fine till November end 2021 and starting from December 6th 2021, it is not working.

below direction is not working so far, it is not inputting value in the immediate next below input box, instead it is inputting value in the 2nd input box.

Note: tried in both Selenium 4.0 and 4.1

### How can we reproduce the issue?

```shell
.
```

### Relevant log output

```shell
.
```

### Operating System

Windows 10

### Selenium version

Selenium 4.0.0 and Selenium 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 96.0.4664.93

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 96.0.4664.93

### Are you using Selenium Grid?

no

**Comment by YasodhaNithi** [comment]
Hi,

As we are using the secured application and can not be shared, however, i will give you the required screenshot

![image](https://user-images.githubusercontent.com/46740517/145363982-9bcc0891-8d20-4a2f-ab63-852e9a05230d.png)

Code:
element=driver.findElement(RelativeLocator.with(By.tagName("input")).below(By.xpath("//label[text()='" + locatorValue + "']")));

in locatorValue, we are passing field name as Name
DOM Structure:
![image](https://user-images.githubusercontent.com/46740517/145365037-a014b3af-c5f6-4718-9341-632124467e79.png)

**Comment by diemol** [comment]
It does not need to be the exact same code and site you are using, we really need a complete script to reproduce the issue, otherwise we cannot troubleshoot this.

**Comment by titusfortner** [comment]
There's no bug here to troubleshoot. Relative locators are inherently a little vague. They work by traversing the DOM node near an element and evaluating each element's `rect` (coordinates and dimensions). It can be easy for one element to slightly overlap another in a way that the "wrong" element will be selected. Relative locators are a nice shortcut when the specific DOM you are working with makes them easy to use, and will be more trouble than they are worth for most others.

In this instance you might try "near" instead of "below." Since the input is going to be the closest one to that label
