### ISSUE TITLE
[🐛 Bug]: Relative Locator in Selenium 4. 'Below' direction seems to be working incorrectly

### ISSUE THREAD

**Issue by saranmani** [SeleniumHQ/selenium#10121]
### What happened?

I am using Selenium 4.0.0 and using relative loctors to locate my elements in web app.
But when using 'below' direction, it seems to be inputting the value in wrong textbox.
This issue happens only for few controls.
Kindly help

### How can we reproduce the issue?

```shell
couldnt share the steps
```

### Relevant log output

```shell
Couldnt share the project.
```

### Operating System

windows 10

### Selenium version

selenium 4.0.0

### What are the browser(s) and version(s) where you see this issue?

chrome 96 +

### What are the browser driver(s) and version(s) where you see this issue?

chrome 96+

### Are you using Selenium Grid?

no

**Comment by saranmani** [comment]
Hi ,
I couldn't share the url and credentials as it is secured.
I will provide the screenshot.
**Xpath used:**
element=driver.findElement(RelativeLocator.with(By.tagName("input")).below(By.xpath("//label[text()='Legal Entity']")));

Dom of the Legal Entity
![MicrosoftTeams-image](https://user-images.githubusercontent.com/12432584/145362751-6c1b858a-708a-4e74-9477-46490027c24b.png)

UI of the Legal Entity
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/12432584/145362979-70a73e91-29fd-40ac-b67e-43a96fb1122b.png)

I wanted to enter value in legal entity textbox. the xpath which i m using is correct. but when i use 'below' keyword it is entering the values in 'Site' textbox instead of 'Legal Entity'.
I tried with 'near' keyword. It types the values in 'Location' textbox.

please help.
I want to pass only the lable name as xpath and direction as below. 
When i tried with multiple direction (below legal entity and above site) it worked.
But i dont want to use multiple direction.
Why it enters input in wrong textbox.

**Comment by diemol** [comment]
If you cannot share your code and URL/HTML, any complete code snippet and URL/HTML that reproduces the issue is good enough.

**Comment by titusfortner** [comment]
There's no bug to fix here. Relative locators are inherently a little vague. They work by traversing the DOM node near an element and evaluating each element's rect (coordinates and dimensions). It can be easy for one element to slightly overlap another in a way that the "wrong" element will be selected. Relative locators are a nice shortcut when the specific DOM you are working with makes them easy to use, and will be more trouble than they are worth for most others.

You might try "near" instead of below, because the legal entity textbox is going to be the closest to the label, even if by some quirk of the DOM dimensions, the "site" text box is more "below" the entity label than the entity text box.
