### ISSUE TITLE
[🐛 Bug]: Selenium cannot interact with some visible elements with fragment tags

### ISSUE THREAD

**Issue by GgStormer** [SeleniumHQ/selenium#10157]
### What happened?

Selenium cannot interact with some visible elements which contain "fragment" keyword.
Run the code from snippet.

Element "//main[contains(@class, 'App---main')]" is visible on page.

So expected behavior is that this block of code works fine:
`wait.until(ExpectedConditions.visibilityOf(fragment));`

### How can we reproduce the issue?

```shell
        WebDriver driver = new ChromeDriver();
        driver.manage().window().maximize();
        driver.get("https://anker.dev-bs-ecom.com/products/2-LO-0PA-10");
        WebDriverWait wait = new WebDriverWait(driver, 10);
        // Even some creepy wait
        Thread.sleep(10000);
        WebElement fragment = driver.findElement(By.xpath("//main[contains(@class, 'App---main')]"));
        wait.until(ExpectedConditions.visibilityOf(fragment));
```

### Relevant log output

```shell
Exception in thread "main" org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of [[ChromeDriver: chrome on XP (1e85e298f2e143a984b6ff5a0edab033)] -> xpath: //main[contains(@class, 'App---main')]] (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'GG-OK', ip: '192.168.0.98', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.37.544315 (730aa6a5fdba15..., userDataDir: C:\Users\Gg\AppData\Local\T...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 96.0.4664.110, webStorageEnabled: true}
Session ID: 1e85e298f2e143a984b6ff5a0edab033
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:138)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
	at Test.main(Test.java:21)
```

### Operating System

win 7, win 10, linux

### Selenium version

4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 96.0.4664.110

### What are the browser driver(s) and version(s) where you see this issue?

chromedriverVersion: 2.37.544315

**Comment by titusfortner** [comment]
Ok, I can reproduce this one. Also, looks like it's the same issue as #9668.

Reading up on Vue Fragments, I see them described as:
> virtual elements that won't be rendered in the DOM tree

Presumably it creates valid DOM elements and adds these fragment attributes to them, so I don't see anything obviously wrong during inspection.

Selenium determines whether an element is interactable  by executing the `isDisplayed.js` atom, which traverses the DOM looking for things that would cause an element to be hidden. I'm not sure how to determine which part of the JS investigation is causing the issue.

In Chrome, attempting to get the text of the element returns an empty string (which is what is expected if the element is not displayed, because it is supposed to represent text content which is visible). Attempting to click an element throws an interactable error.

In Firefox, though, it will return text in spite of it being reported as not displayed and will allow the element to be clicked without an error.

I'll bring this issue up to the team and see if we can figure out something more.

**Comment by titusfortner** [comment]
actually, let's track this in #9668
