### ISSUE TITLE
[🐛 Bug]: PrintOptions don't work (simply do nothing)

### ISSUE THREAD

**Issue by elasadel** [SeleniumHQ/selenium#10189]
### What happened?

I've been testing printing page in headless mode in Chrome browser. No matter what printing options I set up, the outcome is always the same. The priinting options do nothing.

For example when I set up PrintOptions.Orientation.LANDSCAPE the file still has portait orientation. I have removed the file before another run to make sure it's a new file.

### How can we reproduce the issue?

```shell
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.Pdf;
import org.openqa.selenium.PrintsPage;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.print.PrintOptions;

import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Base64;

public class PrintPageExample {

    @Test
    public void printPageExampleTest() throws IOException {
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless");
        WebDriverManager.chromedriver().setup();
        WebDriver driver = new ChromeDriver(options);
        driver.get("<some_test_page>");

        PrintsPage printer = (PrintsPage) driver;
        PrintOptions printOptions = new PrintOptions();
        printOptions.setOrientation(PrintOptions.Orientation.LANDSCAPE);
        Pdf pdf = printer.print(printOptions);
        String content = pdf.getContent();
        byte[] decoded = Base64.getDecoder().decode(content);
        FileOutputStream fos = new FileOutputStream("D:\\test.pdf");
        fos.write(decoded);
        fos.flush();
        fos.close();

        driver.quit();
    }
}
```

### Relevant log output

```shell
There is no log
```

### Operating System

Windows 11 Pro

### Selenium version

Java 4.1.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 96

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 96.0.4664.45

**Comment by titusfortner** [comment]
Selenium is sending the correct commands to the driver, but the driver is not working as expected.

Right now the best way for the drivers to fix things is to show failing tests in WPT. You can see here that there are print command tests that are failing for Chrome/Edge: https://wpt.fyi/results/webdriver/tests/print/printcmd.py?label=experimental&label=master&aligned

So you can expect that Chrome is working on it.
If you would like to add more scenarios to ensure that Chrome fixes the part that most interests you, you can add them here: https://github.com/web-platform-tests/wpt/blob/master/webdriver/tests/print/printcmd.py

In the meantime I'm going to close this issue since there is nothing that can be changed in this code base to fix this problem.
