### ISSUE TITLE
Bug: IEDriverServer does not run on Windows XP

### ISSUE THREAD

**Issue by Elmue** [SeleniumHQ/selenium#1023]
The documentation says that the Internet Explorer Driver should run on Windows XP and even on Internet Explorer 6. But this is not true.

I downloaded IEDriverServer_Win32_2.47.0.zip
and when I start it on XP it tells me that 
the entry point "CreateUri" was not found in urlmon.dll.

**Comment by jimevans** [comment]
This is not a symptom of running on Windows XP, but rather attempting to run against IE6. The IE driver has not actively supported IE6 since 15 April 2014, following Microsoft's end of support for that browser version. While nothing was explicitly done to prevent execution against IE6, the refactoring of cookie handling in 2.47 included use of the CreateUri API, which requires IE7. The wiki page for the IE driver does not list support for IE6; if other documentation pages indicate support for it, those are bugs in documentation, but support for IE6 will not be returning to the driver.
