### ISSUE TITLE
[🐛 Bug]: wait.Until(ExpectedConditions.ElementToBeClickable ... does not exist in latest nuget

### ISSUE THREAD

**Issue by fasteddys** [SeleniumHQ/selenium#10253]
### What happened?

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'ExpectedConditions' does not exist in the current context	
```

### Hello, this is not working with latest nuget `C# .net Core 6` update
but the docs / help show this, while browsing the code does not., please advise

```
WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(25));
            wait.Until(ExpectedConditions.ElementToBeClickable(By.XPath("/html/body
```

### How can we reproduce the issue?

```shell
Update to latest ASP core 6 and use the code above
```

### Relevant log output

```shell
Update to latest ASP core 6 and use the code above
```

### Operating System

win 11

### Selenium version

.NET ASP C# core 6 latest nuget

### What are the browser(s) and version(s) where you see this issue?

chromium  latest nuget

### What are the browser driver(s) and version(s) where you see this issue?

chromerdriver latest nuget

**Comment by titusfortner** [comment]
Yes, this is intentional: http://jimevansmusic.blogspot.com/2018/03/deprecating-parts-of-seleniums-net.html

We recommend that you create your own anonymous functions to manage your wait conditions. 

If you need to continue to use expected conditions classes, you can find it in a separate NuGet package:
DotNetSeleniumExtras.WaitHelpers
