### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by cyberfuhrer** [SeleniumHQ/selenium#10272]
### What happened?

When i use TouchActions in python, the Error is Message: unknown command: Cannot call non W3C standard command while in W3C mode With this, ActionChains class works well. This is my python code:

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
#from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.touch_actions import TouchActions

mobile_emulation = { "deviceName": "Nexus 5" }
options = Options()
options.add_argument('--headless')
options.add_experimental_option('mobileEmulation', mobile_emulation)
driver = webdriver.Chrome(options=options)
driver.get("http://example.com/")
element = driver.find_element(By.TAG_NAME, 'body')
actions = TouchActions(driver)
actions.tap(element)
#actions.double_tap(element)
#actions.flick(10, 10)
actions.perform()
driver.quit()
```

### Relevant log output

```shell
Cannot call non W3C standard command while in W3C mode With this
```

### Operating System

Linux

### Selenium version

4.1.0

### What are the browser(s) and version(s) where you see this issue?

97.0.4692.71

### What are the browser driver(s) and version(s) where you see this issue?

97.0.4692.71

**Comment by titusfortner** [comment]
Selenium `TouchActions` is deprecated and has been removed for the next release because it is not w3c compatible.
The replacement is to use pointers, but we don't have useful helper methods for them at this point, and I'm not sure how painful building up the necessary code is for that.
We're discussing how we should create a better interface for helper functionality going forward.
In the meantime, you probably need to check out Appium library for this functionality.
