### ISSUE TITLE
[🚀 Feature]: Make ExpectedConditions library work with Android, Mobile, Ios elements without type casting

### ISSUE THREAD

**Issue by jevgenijsklimovs** [SeleniumHQ/selenium#10288]
### Feature and motivation

Greetings, as I'm doing mobile app automation testing I've faced problem that ExpectedConditions library doesn't work with mentioned element types without type cast, in Java type casting is an anti pattern, but still this library is best solution for explicit wait. It would be great if library will work with all element types.

### Usage example

```
public MobileElement getElement(By id) {
        return (MobileElement) wait.until(ExpectedConditions.visibilityOfElementLocated(id));
    }
```

**Comment by titusfortner** [comment]
How are you defining your `wait` variable? What interface does MobileElement implement that should be getting returned instead? You can initialize Wait with the interface you want returned.

**Comment by jevgenijsklimovs** [comment]
```
public void init(AndroidDriver<MobileElement> driver) {
        this.driver = driver;
        touchActions = new TouchActions(driver);

        driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);

        WebDriver wait = new WebDriverWait(driver, 2);
    }
```

This is how `wait` is defined. You mean to create interface for my `DriverBaseClass` and define `wait` inside it?

**Comment by titusfortner** [comment]
I was thinking you could implement your own `Wait` class, but I see that isn't your issue.

For the reason you mentioned it is recommended that you use lambdas instead of `ExpectedConditions` classes, which we don't want to create more of. Lambdas will return anything you want them to, Especially if you are crating your own wrapper, you can do this instead:

```java
public MobileElement getElement(MobileBy by) {
        MobileElement element = wait.until(driver -> driver.findElement(by));
        wait.until(driver -> element.isDisplayed());
        return element;
}
```

Also of interest, `MobileElement` has been deprecated in the version of Appium that supports Selenium4, which removes some of this concern as well: 
https://github.com/appium/java-client/blob/665c7f5a4bcaaff5442a1c1fd41f460063c1a836/docs/v7-to-v8-migration-guide.md

**Comment by jevgenijsklimovs** [comment]
Thank you for the article. I will start migrating my project.
