### ISSUE TITLE
[🐛 Bug]: Actions.moveToElement is not working for FireFox driver, while it works fine with Chrome.

### ISSUE THREAD

**Issue by MaheshkumarPalled** [SeleniumHQ/selenium#10327]
### What happened?

I'm trying to perform mouse hover on a webElement, so that it expands the list and then I continue by choosing the displayed option.

Below code is working fine with Chrome browser.

### How can we reproduce the issue?

```shell
public void mouseOverOnElement(WebElement targetElement) {
Actions builder = new Actions(webDriver);
builder.moveToElement(targetElement).perform(); // This didn't work in FireFox
builder.moveToElement(targetElement).build().perform(); // This didn't work in FireFox

//Also tried to achieve it with Java script executor. 

JavaScriptExecutor js = (JavascriptExecutor) webDriver;
js.executeScript("arguments[0].onmouseover", targetElement); // Didn't work,
js.executeScript("arguments[0].scrollIntoView(true);", targetElement); // Didn't work.
}
```

### Relevant log output

```shell
NA
```

### Operating System

macOSMonterey, version 12.2

### Selenium version

Java 3.14.0, 4.1.1, 4.1.2

### What are the browser(s) and version(s) where you see this issue?

FireFox 91.5.0esr (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

GeckDriver 0.30.0

### Are you using Selenium Grid?

NA

**Comment by titusfortner** [comment]
First, hover is working for me in Firefox 91.

Few things:
1.  What "doesn't work?" Are you getting an error, or is the pointer just not moving?
2. Does the page need to be scrolled in order to see the element? Chrome is incorrectly scrolling elements instead of throwing an out of bounds error. You might need to scroll the page first if so.
3. It should be moving the pointer to the middle of the element, but you can try a small offset `builder.moveToElement(targetElement, 1, 1)` to see if that helps.

**Comment by MaheshkumarPalled** [comment]
Thanks for the reply. 

"targetElement" is part of shadow DOM -> iFrame -> targeted element.

I access shadow DOM and then switch to correct iFrame. It's happening only with FireFox. Same approach or code works fine in Chrome.

Just to add here. 
.Click() method works correctly (FireFox) and clicks on the element. But I do not need click action here, as it opens the another link.

Please find the details below. 

1. What "doesn't work?" Are you getting an error, or is the pointer just not moving? -> _It's hovering on an element which is just above the expected one._ 
2. Does the page need to be scrolled in order to see the element? Chrome is incorrectly scrolling elements instead of throwing an out of bounds error. You might need to scroll the page first if so. -> _Element is visible,  Scrolling is not required._
3. It should be moving the pointer to the middle of the element, but you can try a small offset builder.moveToElement(targetElement, 1, 1) to see if that helps. -> _I tried this, still hovers on an element, which is above the expected element._

**Comment by titusfortner** [comment]
Oh, inside a shadow DOM. How interesting. I wonder if something about it being in the shadow DOM is throwing off the rect. 

So, Selenium is doing the right thing, but geckodriver is not. So we need to follow up with mozilla. In the meantime, you might be able to do a workaround with `builder.moveToElement(targetElement, xOffset, yOffset)`, where the offsets correspond the pixels to move the pointer to the element you want.

If there's a flakiness concern where the window might change dimensions or there is otherwise a variable component to this, you can use the clever approach JLipps created here with getRect (it's for Appium, but the same principle applies):
https://appiumpro.com/editions/22-making-your-appium-tests-fast-and-reliable-part-4-dealing-with-unfindable-elements

**Comment by MaheshkumarPalled** [comment]
It's still not working with the above suggestions. Seeing that it's hovering on different element than expected in Shadow DOM. Created a ticket to geckoDriver team.
