### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by taksan** [SeleniumHQ/selenium#10361]
### What happened?

When I run selenium with firefox driver, firefox opens with an error dialog and then quits.

```
Profile Missing

Your Firefox profile cannot be loaded. It may be missing or inaccessible
```

### How can we reproduce the issue?

```shell
Even a very minimal program raises the issue with web. The following code running with Selenium version 4.1.2


import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;

public class Selenium {
    public static void main(String[] args) {
        System.setProperty("webdriver.gecko.driver", "/tmp/drivers/linux/marionette/64bit/geckodriver");

        FirefoxOptions options = new FirefoxOptions();
        options.setBinary("/snap/bin/firefox");
        FirefoxDriver driver = new FirefoxDriver(options);
    }
}
```
```


### Relevant log output

```shell
No logs.
```

### Operating System

Ubuntu Linux 22.04

### Selenium version

4.1.2

### What are the browser(s) and version(s) where you see this issue?

Firefox 97.0

### What are the browser driver(s) and version(s) where you see this issue?

Firefox Driver 0.30.0

**Comment by titusfortner** [comment]
Is this a new implementation, or code that used to work, but no longer does?
The most likely cause is an issue with Firefox install itself. Are you able to open this Firefox instance properly without Selenium? Can you debug with a Profile Manager?

**Comment by taksan** [comment]
Firefox is working flawlessly. How can I debug with a profile manager?

**Comment by titusfortner** [comment]
We know our users can run Firefox with Selenium right now, so there is something specific to your environment that is having an issue. 

Is this your machine running Selenium as you, or is this executed by a process for a user that might not have full permissions?
Is there more than one instance of Firefox on the machine?

Profile manager:
https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles

I'm going to close this because there is nothing for Selenium to fix, but I'll respond to replies, or you can reach out to us on chat
