### ISSUE TITLE
[🚀 Feature]: A method to listen to page title change

### ISSUE THREAD

**Issue by YueMiyuki** [SeleniumHQ/selenium#10382]
### Feature and motivation

Listening to change of the title of the page instead using wait

### Usage example

To include unexpected page change
For example: 
The page was expected to change to succes.xxx.com but it changed to fail.xxx.com

thats where event listening jackes in, the new featrue would help making better handling of page changes with the driver

**Comment by diemol** [comment]
Listening to page changes are useful methods. Since you can use the https://www.selenium.dev/documentation/webdriver/bidirectional/ methods to implement these things, and there are a bunch of different ways it can be implemented and used, though, we do not add this functionality directly to Selenium and highly encourage our users to implement this kind of thing in their own test frameworks/libraries/code.
