### ISSUE TITLE
Click doesn' t work after hovering in version later than 2.44

### ISSUE THREAD

**Issue by ygruninBGGK** [SeleniumHQ/selenium#1043]
Hi, next code worked and stopped on new version of selenium :

Actions builder = new Actions(driver);
		WebElement tagElement = driver.findElement(By.cssSelector(".deleteDomain"));
		builder.moveToElement(tagElement).build().perform();
		System.out.println("The x for delete appeared and should be presented for a long time");
		Thread.sleep(3000);
		driver.findElement(By.cssSelector(".deleteDomain .icon.moreLink")).click();//at last Menu Item Click

It cannot find the element after hovering
I installed  the 2.42 - works again

Selenium version: 2.44
OS: Windows
Browser: Firefox
Browser version: 28.0

**Comment by ddavison** [comment]
have you tried version `2.47`?

**Comment by ygruninBGGK** [comment]
Yes, but still...
Works for me on 2.42 only :(
But this version doesn't work with latest firefox version

**Comment by lukeis** [comment]
This is due to the project's inability to build the 'native events' components with our FirefoxDriver. Unless someone provides a patch to fix them, we are unable to support them. You might be able to try Marionette, but it is still not feature complete. 

You should be able to use FF 31 ESR with the latest selenium version and have it work.
