### ISSUE TITLE
[🐛 Bug]: IE11(Win11) ,use selenium to click upload_file_button, but after clicking the open file dialog, the whole system is unresponsive

### ISSUE THREAD

**Issue by susan20150801** [SeleniumHQ/selenium#10464]
### What happened?

the whole system is unresponsive.The following code doesn't work

### How can we reproduce the issue?

```shell
win11 IE11,upload_file
```

### Relevant log output

```shell
No
```

### Operating System

windows 11

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

IE 11

### What are the browser driver(s) and version(s) where you see this issue?

IE 4.0.0 64bit

**Comment by titusfortner** [comment]
You can not use the File Explorer dialog with Selenium since it is part of the Operating System not the browser. To upload files with Selenium you need to use the send keys method with the path to the file you want to upload on the input element that has a type of file. We don't have an example in our documentation right now, but there are plenty of other tutorials online.
