### ISSUE TITLE
[🐛 Bug]: StackOverflowException from a listener after upgrading to Selenium 4

### ISSUE THREAD

**Issue by baflQA** [SeleniumHQ/selenium#10477]
### What happened?

Hello folks. 
Recently, I've upgraded my project to Se4. 
In my project, I have a WebDriverListener implemented, that tries to find an element in any of the iframes. It helps me to make my tests handle iframes smoothly.

After upgrading to Se4, it started to fail inside this listener with StackOverflowException.
I've prepared a sample project with Se3 and Se4 implementation of the same test.

https://github.com/baflQA/selenium_debug/tree/main/se3 - Selenium 3 implementation
https://github.com/baflQA/selenium_debug/tree/main/se4 - Selenium 4 implementation

As You can see, I create a decorated instance of WebDriver. 
Then, from found WebElement, I extract the wrapped driver and create a new decorated driver instance. 
It's an abbreviation of what I do in my framework, but it points to the problem directly. 
The listener's beforeFindElement method will be called infinitely in Se4 implementation after decorating the wrapped driver, causing StackOverflowException.
This is not the case in Se3.

### How can we reproduce the issue?

```shell
https://github.com/baflQA/selenium_debug/tree/main/se3 - Selenium 3 implementation
https://github.com/baflQA/selenium_debug/tree/main/se4 - Selenium 4 implementation
```

### Relevant log output

```shell
StackOverflowException will be thrown
```

### Operating System

macOS

### Selenium version

4.1.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 99

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 99

**Comment by pujagani** [comment]
Thank you for the details and the project to help reproduce the issue. I was able to reproduce the issue. 

#### Reason for the bug
After sufficient triaging, the issue seems to happen due to a combination passing a DecoratedWebDriver https://github.com/baflQA/selenium_debug/blob/4c9c1ae144b13b8c1b431351886031ed3859d960/se4/src/test/java/selenium/debug/ListenerTest.java#L25 and the recursive nature of https://github.com/baflQA/selenium_debug/blob/4c9c1ae144b13b8c1b431351886031ed3859d960/se4/src/main/java/selenium/debug/WebDriverListenerImpl.java#L49. What is happening is that at every call, https://github.com/baflQA/selenium_debug/blob/4c9c1ae144b13b8c1b431351886031ed3859d960/se4/src/main/java/selenium/debug/WebDriverListenerImpl.java#L23 method is being called which in turn calls the recursive function and this keeps happening. This is because a decorated webdriver is passed and true to its implementation it calls the decorated method. This goes on and leads to a StackOverflow exception. 

#### Potential fix
Listing down 2 ways to fix this in your code : 
1. Replace https://github.com/baflQA/selenium_debug/blob/4c9c1ae144b13b8c1b431351886031ed3859d960/se4/src/test/java/selenium/debug/ListenerTest.java#L25 with:
 `var wrappedDriver = ((WrapsDriver)((WrapsElement) until).getWrappedElement()).getWrappedDriver();`
2. Adding a check to https://github.com/baflQA/selenium_debug/blob/main/se4/src/main/java/selenium/debug/WebDriverListenerImpl.java#L23  

  ```
  @Override
    public void beforeFindElement(WebDriver driver, By locator) {
        if (driver instanceof WrapsDriver) { 
            handleIframes(locator, null, ((WrapsDriver)driver).getWrappedDriver());
        } else {
            handleIframes(locator, null, driver);
        }
    }
```

Either of the options work. 

#### Additional details: 

On the face of it, it looks like an error in the Selenium 4's implementation of WebDriverDecorator. That is not the case. To eliminate that, I have double-checked and compared the implementation of the EventFiringDecorator and EventFiringWebDriver. The `getWrappedDriver()` function in both cases is returning the correct value i.e the driver that wraps the element which is the decorated webdriver in this case. When the decorated webdriver is used, it is expected to call the decorated method. 
However, the reason the code works in Selenium 3 is that there is a bug in EventFiringWebDriver. Though it returns the decorated webdriver, the implementation does not call the decorated method instead it calls the original method (https://github.com/SeleniumHQ/selenium/blob/7217bb389dc38d5f19a75eb0da8a958e81013a06/java/src/org/openqa/selenium/support/events/EventFiringWebDriver.java#L115) if the value returned by "getWrappedDriver()" is used. Fixing it is not a small change because of the way it is designed. Since it is deprecated using WebDriverDecorator is recommended.

**Comment by baflQA** [comment]
Hey! 
Thanks a lot for this great explanation and for providing a solution to my problem. 
So, it was working previously by luck ;) 
I can confirm that it works with the example that I provided, gonna have a try in my production project. 
Once again, thanks for Your effort.
