### ISSUE TITLE
[🐛 Bug]: Cannot Get DevToolSession

### ISSUE THREAD

**Issue by rinnn31** [SeleniumHQ/selenium#10486]
### What happened?

I want to get the devtoolsession from idevtool object, but when I write the code to get it, my program freezes.
Here is my code (the program freezes after executing line 2):

### How can we reproduce the issue?

```shell
IDevTools devTool = driver as IDevTools;
            var session = devTool.GetDevToolsSession();
            var domains = session.GetVersionSpecificDomains<DevToolsSessionDomains>();
            domains.Page.Enable(new EnableCommandSettings());
            domains.Page.AddScriptToEvaluateOnNewDocument(new AddScriptToEvaluateOnNewDocumentCommandSettings()
            {
                Source = "Object.defineProperty(navigator, 'webdriver', { get: () => undefined });" +
                @"Object.defineProperty(navigator, 'platform', { get: () => 'MacOS'}); " +
                ""
            });
```

### Relevant log output

```shell
nothing
```

### Operating System

Window 10

### Selenium version

C# 4.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 99

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver

**Comment by diemol** [comment]
I cannot reproduce this, I tried this code but it never froze https://github.com/diemol/selenium-issues/tree/master/selenium/issue-10486.

However, please note that `Object.defineProperty(navigator, 'webdriver', { get: () => undefined });` will lead to unexpected behavior because it is meant to be there to prevent attacks from bots or similar. See #9986
