### ISSUE TITLE
[🚀 Feature]: Need Videos Dashboard For Selenium Grid 4 

### ISSUE THREAD

**Issue by IronMan0404** [SeleniumHQ/selenium#10523]
### Feature and motivation

Hi Team,
           I need access to the dashboard, videos and logs access from any remote machine. Do we have any selenium configuration or environment variable to access the selenium dashboard from any machine? So that all team members of my team can have access to review test case status.

Feature Like this:
![image](https://user-images.githubusercontent.com/42374890/162170820-2490a951-81a8-4480-baff-ef97d817ea39.png)

### Usage example

Please refer the  [Zalenium - Dashboard ]https://opensource.zalando.com/zalenium/

**Comment by shivakalva** [comment]
+1 for the above feature

**Comment by diemol** [comment]
The dashboard in Zalenium was a good idea, yes. But over time it became unmaintainable and the code was very complex, basically because every user wants something different. A dashboard won't be part of the Grid itself, but it can be perfectly a community project that can be hosted on https://github.com/seleniumhq-community. 

If someone wants to work on this, please feel to reach out to us and we can collaborate. We are available at the channels shown in https://www.selenium.dev/support/.
