### ISSUE TITLE
Query - around "Screenshot: available via screen"

### ISSUE THREAD

**Issue by menonprasad1** [SeleniumHQ/selenium#1054]
I know this is not the right location for this query , Apologies.

On an exception i see that a message is returned Screenshot: available via screen".
Also in the debug mode I see a screen : with a very verbose id.

How can I use this id?
Does this mean that the grid has already captured a screenshot and I could may somehow access it?

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
