### ISSUE TITLE
Screenshot partially black with the IE Driver

### ISSUE THREAD

**Issue by florentbr** [SeleniumHQ/selenium#1056]
The returned image only contains the part that is visible on the screen.
The size seems to match the full content, but the remaining content is black.
![screenshot](https://cloud.githubusercontent.com/assets/918557/9986058/28fa17a4-602f-11e5-94b7-63c64e8de9ea.png)

Environment :
Windows 8.1 64bit, IE11, IE Driver 2.47.0 32bit

To reproduce:

    var driver = new InternetExplorerDriver();
    driver.Navigate().GoToUrl("https://en.wikipedia.org/wiki/Yelcho_Lake");
    driver.GetScreenshot().SaveAsFile(@"screenshot.png", ImageFormat.Png);
    driver.Quit();

**Comment by jimevans** [comment]
Thanks for the issue report. As it happens, this is a long-standing known issue with the IE driver. It was introduced when IE 10 was released, and we will not be fixing it. There are two reasons for this decision.

First, fixing the root cause of the issue would require a complete rearchitecture of the driver. For a complete technical discussion of why this would be so, and what rearchitecture would be required, please see http://jimevansmusic.blogspot.com/2014/09/screenshots-sendkeys-and-sixty-four.html.

Second, the [W3C WebDriver specification](https://w3c.github.io/webdriver/webdriver-spec.html) defines screenshots as being of the visible view port only. This means that when the driver is updated to implement the specification, the driver will no longer attempt to take full-DOM screenshots, and this will no longer happen.

**Comment by florentbr** [comment]
I had a look at your analyse and found it quite impressive.
Though, there is no need to use code injection to capture the full page with IE.
The trick is to call SetWindowPos with the SWP_NOSENDCHANGING flag on the "Shell DocObject View" window intead of the "IEFrame" window. This way, the message loop doesn't send the WM_GETMINMAXINFO message.

I successfully tested it on WindowsXP/IE8, Windows7 64bit/IE11 and Windows8.1 64bit/IE11
Let me know if you are interested in a pool request to fix this bug.

**Comment by jimevans** [comment]
Incidentally, I've made a change to this method in 005c5c9. You can try the version of the IE driver containing the fix (`2.47.0.3`) by downloading it [from here](https://github.com/SeleniumHQ/selenium/blob/master/cpp/prebuilt/Win32/Release/IEDriverServer.exe?raw=true)

**Comment by florentbr** [comment]
I've just tested it (2.47.0.3) on Windows 10-64bit/IE11, Windows 7-64bit/IE11, Windows XP/IE8.
With this fix, the screenshot is no longer partial in a cross-bitness context.

BTW, it's also possible to resize the document outside the limits of the screen with the SetRect method from the IOleDocumentView interface:

    dynamic docEle = doc.documentElement;
    IOleDocumentView view = (IOleDocumentView)doc;
    view.SetRect(scrollRect);
