### ISSUE TITLE
[🚀 Feature]: Allow user defined metadata in Sessions list in Selenium 4 Grid 

### ISSUE THREAD

**Issue by ApexK** [SeleniumHQ/selenium#10578]
### Feature and motivation

The Selenium4 grid ui has this new "Sessions" section containing a list with the columns "Session, Capabilities, Start Time, Duration etc". 

It would be really helpful if it allowed a user-defined metadata field which could be displayed as column here. 

For example, the user can set the testcase name programmatically as metadata which can then be showed in a separate column along with the sessionid.

Please see screenshot for example highlighted in red
<img width="1648" alt="Screenshot 2022-04-26 at 3 27 12 PM" src="https://user-images.githubusercontent.com/45968860/165323111-5e045786-48db-4603-a038-2c61d0e3fec9.png">

### Usage example

Feature can be used by sending important metadata like testcase name or some other test case related information programmatically. This will be helpful in mapping which session is for which test case and quickly select and click on the session and view the live VNC recording which is currently possible.

**Comment by therealdjryan** [comment]
If you need the test name displayed you can add se:name as an option: ```options.setCapability("se:name", "myTest")```  I understand that my suggestion doesn't satisfy your general request for including arbitrary metadata, but maybe it will help you out.

**Comment by ApexK** [comment]
Thanks but that still requires an extra click to see the information. 

The sessions view right now is very barebones and if we have more than 1 session running simultaneously, then it gets difficult to identify which session is for which test case. 

Adding a "name" column would be so helpful to quickly identify and debug things.

**Comment by diemol** [comment]
Not at all, if you add a capability with `se:name` per test, that will be used instead of the session id and it will be shown right away. For any other metadata, you can click on the session info icon and you will see them in the UI, but you can also obtain that data through [GraphQL](https://www.selenium.dev/documentation/grid/advanced_features/graphql_support/).

I just added a section in the docs describing a bit more https://www.selenium.dev/documentation/grid/getting_started/#tests-metadata.

Regarding the UI, it is meant to be very simple to accommodate to most use cases. If any customization is wanted, and it makes sense for the community, we welcome pull requests to add them. However, if major changes are wanted, we recommend implementing an own UI by using the GraphQL endpoints.
