### ISSUE TITLE
Disable http TRACE method in selenium (grid)

### ISSUE THREAD

**Issue by julianhaslinger** [SeleniumHQ/selenium#1058]
Hi! 

Is there a way to disable the http TRACE method for selenium (grid) instances? 

Best Regards!

**Comment by ddavison** [comment]
Hi @julianhaslinger ,

We reserve these GitHub issues for concrete issues found in Selenium rather than a question/answer forum.. For that, you should check out the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

If you find an issue with Selenium, feel free to log it here but please be sure to abide by the [Contribution Guidelines](https://github.com/seleniumhq/selenium/tree/master/CONTRIBUTING.md).
