### ISSUE TITLE
Problem with 'click' on IE11

### ISSUE THREAD

**Issue by HiperNova** [SeleniumHQ/selenium#1061]
I use webdriverIO to write tests for my javascript application. But when I simulate clicking the 'login' button it doesn't work but selenium thinks that there's no problem. Same test on chrome works correctly. How to fix this problem? 

```javascript
browser.login = (src, name='Demo') ->
    this
        .url(SERVER_PATH + src)
        .pause(2000)
        .setValue('#username-id', name)
        .click('#controlBox > table > tbody > tr:nth-child(5) > td:nth-child(3) > input:nth-child(1)')
```

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
