### ISSUE TITLE
Selenium Web Driver : Start Up Log : instance identification

### ISSUE THREAD

**Issue by BugFinderBugFixer** [SeleniumHQ/selenium#10642]
### Feature and motivation

When I start Selenium Chrome Driver "Version 101.0.4951.67 ( 12/05/2022 7:52 AM ) : 2.50 MB" 
a log file is opened in a window and messages written to it.
The messages do not include the "Process Identifier" allocated by Windows 10, 
nor does it display the date/time when the Driver instance was started.

I run many instances of Selenium Chrome Driver concurrently. They may , or may not be spawned
by the same parent process. For various reasons the parent process may no longer able to
shut down a specific instance. So Windows 10 Process Monitor must be used to manually remove
the Driver instance. However identifying the orphaned instance is guess work.

If the Driver log displayed PID and Start/Time this ambiguity could be eliminated.
It would also be useful if the parent process had identified itself at Browser Start.
This could be easily done by allowing a start up preference like this . . .

    Driver.setPreference "browser.startup.invokedby", "ShippingScheduleDownloader.exe"

Killing the wrong Driver instance can be extremely inconvenient
![Selenium Chrome Driver ~ Log file](https://user-images.githubusercontent.com/105487255/168253721-62cad11a-bcd8-494a-b1a9-7e62e01617d3.png)
.

### Usage example

Use Case : A Process, that initiated Selenium Chrome Driver, crashes.
The Selenium Chrome Driver continues to run. Its Chrome Browser has its Profile Directory locked.
By killing the Selenium Chrome Driver all resources and points of potential contention are released.
I should be able to look at each of the Selenium Chrome Driver log windows and see
which one was started at the requisite time, and invocation context ("invokedby").
The Selenium Chrome Driver log window will also show the Process Identifier of Selenium Chrome Driver.
Using the Process Identifier I would then 
use Windows 10 Process Monitor to kill the orphaned process only.

**Comment by titusfortner** [comment]
First, it is highly recommended that you ensure that quit is always called on the driver so that it can exit everything properly. If you are using a test runner, put it in an after hook; if it is in an after hook but after another command that might fail, put it in a try/catch/finally to ensure it is executed.

Second, I don't really understand the value. The processes are very low resources. If you need things clean, can you not wait until the active sessions have completed and remove them all? Additionally, the executable does log the port, so if you really need to identify the process, you can search for the process that owns the port in the log and close that one.

Finally, the message you are referring to is written by the driver and not by Selenium code, so any action would need to be done by Google.
