### ISSUE TITLE
RemoreWebdriver Issue

### ISSUE THREAD

**Issue by Diplomat2015** [SeleniumHQ/selenium#1072]
Hi,

I have Selenium Server installed in Remte machine.When I tried to run a Selenium program it is giving error "No SUch Element" and terminating.I am using Chrome and C#.

The same code is running if I am using my local system.What I observed that no chrome browser is opening in the remote machine when I am running the code.I am using VS2015 to run the code.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
