### ISSUE TITLE
WebDriver doesn't take screenshot of complete browser, it captures only visible area

### ISSUE THREAD

**Issue by NehaDua** [SeleniumHQ/selenium#1075]
Hi Team,

Actual :WebDriver doesn't take screenshot of complete browser, it captures only visible area
Expected - To capture complete browser

Code- if((this.objWebDriver != null) && (!(strBrowser.equals("CHROME")))&& (!(strBrowser.equals("IOSNATIVEDRIVER")))&& (!(this.objWebDriver.getClass().toString().contains("RemoteWebDriver")))) {
	    		File screenshotFile = ((TakesScreenshot)this.objWebDriver).getScreenshotAs(OutputType.FILE);     
	    		FileUtils.copyFile(screenshotFile, new File(screenshotPath));

Please help

**Comment by lukeis** [comment]
According to the WebDriver spec:
https://w3c.github.io/webdriver/webdriver-spec.html#take-screenshot

"The Take Screenshot command takes a screenshot of the top-level browsing context’s viewport."

meaning, the specification is stating drivers should only create an image of the visible area.

If you disagree with that, you can try to bring it up with the specification itself, but know that has already been discussed:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27646

**Comment by adiherzog** [comment]
@lukeis I think that the WebDriver spec should support both variants (taking a screenshot of only the viewport and taking a screenshot of the entire page). This could be realized by a flag in the screenshot function or by adding a second function. What's the procedure to bring this into the specification?

In the open source tool Scenarioo (https://github.com/scenarioo/scenarioo) we need the screenshots of the entire page (not only the viewport) to document the entire UI flow that is covered by a test. Currently we use Firefox as a workaround because Chrome only gives us the viewport (at least on Ubuntu).
