### ISSUE TITLE
[🐛 Bug]: Zombie ChromeDriver with data:, involving session request queue (Python PoC)

### ISSUE THREAD

**Issue by AcidCaos** [SeleniumHQ/selenium#10831]
### What happened?

**DESCRIPTION**

There is a (reproducible) situation where a zombie ChromeDriver page with `data:,` is created.

This happens when a driver quits (due to session-request-timeout) and yet a Chrome session is created for that script, which has just quit. Since the script is no more, the Chrome session is left orphan with a `data:,`.

This can be reproduced easily by playing with a timer in a script.

**SETUP**

Using a hub and a single node with one single available chrome session:

Command to start the hub:

`java -jar selenium-server-4.3.0.jar hub --config hub.toml`

Content of hub.toml:

```
[server]
host = "localhost"
port = 4444
[sessionqueue]
session-request-timeout = 10
```

Command to start the node:

`java -jar selenium-server-4.3.0.jar node --config node.toml`

Content of node.toml:

```
[node]
detect-drivers = true
driver-implementation = ["chrome"]
max-sessions = 1
grid-url = "http://localhost:4444"
session-timeout = 5
```

**HOW TO REPRODUCE**

The simplest way I've found to reproduce this issue is by executing 2 scripts simultaneously:

The first one (occupy.py) blocks the unique session for arround 'session-request-timeout' seconds.
The second one (dummy.py), waits in the session request queue for 'session-request-timeout' seconds, and quits the driver without getting a session (apparently, since it actually "gets" one).

The second one will be given a session (although the script has already quitted the driver), and a zombie `data:,` chrome is left open.

_Check the Code section for both scripts._

Running those simultaneously (occupy.py and dummy.py) with

```
start python "occupy.py"
start python "dummy.py"
```

(in that order) will:

1. (occupy.py) Open _about:blank_
2. (occupy.py) quit and close Chrome window
3. (dummy.py) quit driver
3. A zombie `data:,` chrome is left open

The _about:blank_ for the second script (dummy.py) is never opened, since the script has quitted, but the session persists.

This has to do with timings (see `time.wait(7.5)` at occupy.py), which might need to be adjusted by adding or substracting at most one unit (seconds). Tested in several versions (check below).

### How can we reproduce the issue?

```shell
[occupy.py]

from selenium import webdriver
driver = webdriver.Remote(command_executor = "http://localhost:4444", desired_capabilities = {"browserName": "chrome"})
driver.get("about:blank")
import time
time.sleep(7.5) # session-request-timeout = 10 (substract aprox 2.5 sec, may vary +- 1 sec.)
driver.quit()


[dummy.py]

from selenium import webdriver
driver = webdriver.Remote(command_executor = "http://localhost:4444", desired_capabilities = {"browserName": "chrome"})
driver.get("about:blank")
driver.quit()
```

### Relevant log output

```shell
.
```

### Operating System

Windows 10

### Selenium version

Java 4.3.0, Java 4.1.3

### What are the browser(s) and version(s) where you see this issue?

Chrome 103.0.5060.66 64-bit, Chrome v.101.0.4951.67

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 103.0.5060.53, ChromeDriver 100.0.4896.60

### Are you using Selenium Grid?

4.3.0, 4.1.3

**Comment by diemol** [comment]
There are a mix of things here. 

`session-request-timeout` serves to timeout requests sitting on the queue, however the check happens in intervals (every `session-retry-interval` seconds). However, I had this hard coded to be a minimum of 15s. This means that every 15 seconds, the check to see if any session had timed out was executed, therefore a session request sitting on the queue was timed out during the interval `session-request-timeout` and `session-request-timeout` + 15s. 

I've set the default to 15s, which can be configured to a lower value, through this [commit](https://github.com/SeleniumHQ/selenium/commit/5294269c1dee029934a9b3ccd44c47cfc4af8653).

Now, in reality, configuring a low `session-request-timeout` is not useful, because one wants to have the Grid help hold the sessions while a slot gets free. So, if you use the default of 5 minutes, doing the check can happen in spread intervals without affecting much the final outcome.

In any case, with the linked commit, you will be able to configure the session queue as you please, and avoid the situation you are running into with the provided script. This will be available in 4.4, which should be released during the first week of August.
