### ISSUE TITLE
[🐛 Bug]: "socket hang up" error occurring on Firefox driver.createCDPConnection call

### ISSUE THREAD

**Issue by dryu99** [SeleniumHQ/selenium#10851]
### What happened?

I'm currently trying to capture JS exceptions on Selenium via the [Bidi API](https://www.selenium.dev/documentation/webdriver/bidirectional/bidi_api/#listen-to-js-exceptions) on Chrome and Firefox.

```
const driver = await new Builder()
  .forBrowser(name)
  .usingServer(server)
  .build();

try {
  const cdpConnection = await driver.createCDPConnection('page')
  await driver.onLogException(cdpConnection, function (event) {
    console.log('print JS exception', event['exceptionDetails']);
  })  
} catch (error) {
  console.error(error)
}
```

Chrome works as expected, however when I specify a Firefox browser, I get the following error: 
```
Error: socket hang up
    at connResetException (node:internal/errors:692:14)
    at Socket.socketOnEnd (node:_http_client:478:23)
    at Socket.emit (node:events:539:35)
    at Socket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ECONNRESET'
}
```

I am running a Selenium Grid server on Docker based on the following images:
- selenium/node-chrome:4.2.2-20220609
- selenium/node-firefox:4.2.2-20220609
- selenium/hub:4.2.2-20220609

I have also manually set the `SELENIUM_REMOTE_URL` env variable (based on the check in [`createCDPConnection`](https://github.com/SeleniumHQ/selenium/blob/8487998201cbd9f552a2ca4dbb385494813436af/javascript/node/selenium-webdriver/lib/webdriver.js#L1209-L1214)), originally I had not done this and was receiving the following error for both Chrome and Firefox (with different IP addresses): 
```
Error: connect ECONNREFUSED 172.18.0.3:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '172.18.0.3',
  port: 4444
}
```

### How can we reproduce the issue?

```shell
import { Builder, By, Browser } from 'selenium-webdriver';

const run = async () => {
  const driver = await new Builder()
    .forBrowser(Browser.FIREFOX)
    .usingServer("grid server address")
    .build();

  try {
    const cdpConnection = await driver.createCDPConnection('page')
    await driver.onLogException(cdpConnection, function (event) {
      console.log('print JS exception', event['exceptionDetails']);
    })  
  } catch (error) {
    console.error(error)
  }
}

run();
```

### Relevant log output

```shell
Error: socket hang up
    at connResetException (node:internal/errors:692:14)
    at Socket.socketOnEnd (node:_http_client:478:23)
    at Socket.emit (node:events:539:35)
    at Socket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ECONNRESET'
}
```

### Operating System

Ubuntu 22.04 LTS

### Selenium version

JavaScript ^4.2.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 101.0

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.30.0

### Are you using Selenium Grid?

4.2.2

**Comment by titusfortner** [comment]
It's unlikely your issue, but your geckodriver version is not compatible with that version of Firefox — https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html

Firefox implements a subset of the Chrome DevTools Protocol, and some of that can be used by Selenium for features like this, and this feature might be one that isn't implemented by Firefox (domains implemented: https://gist.github.com/barancev/65c7a6eff884d209f3bf86b8d4ce55fb). If it is working in Chrome, but not in Firefox, it is likely one of these limitations. Further, we aren't officially supporting any of this yet.

The good news is that Firefox v103 has added support for WebDriver BiDi, including console logging options, and the Selenium team is working to implement that functionality directly so that this is handled in a cross-browser manner. Hopefully we'll have something useful for you soon.

**Comment by dryu99** [comment]
@titusfortner Thank you for the response!
