### ISSUE TITLE
[🚀 Feature]: Get download percentage 

### ISSUE THREAD

**Issue by canklot** [SeleniumHQ/selenium#10884]
### Feature and motivation

When downloading files from a website sometimes we need to check if the download have ended and the file is ready. A native way to check this would be very useful. As you can see in this link with more than 80k views its relatively popular request. https://stackoverflow.com/questions/34338897/python-selenium-find-out-when-a-download-has-completed

There are some work around but they are not perfect. Checking the download folders manually can cause problems when there are other programs that are also downloading in the same folder.  Checking .crdownload files can be a problem when you are downloading multiple files. Checking a file name can be a problem because sometimes filenames are send random from the server.

The code below is a good attempt and works ok for big files but I had problems with small ones and sometimes fails for some reason.
```
downloadPercentage = driver.execute_script(
                "return document.querySelector('downloads-manager').shadowRoot.querySelector('#downloadsList downloads-item').shadowRoot.querySelector('#progress').value")
```

A native way to check if download finished or not, what is the percentage, did the download finished successfully or failed, would be very usefull.

### Usage example

I want to use this feature when downloading many files from a website that requires login and only allow some number of concurrent downloads at the same time. So that I can download one file, wait for it to finish and download next one. Also I can start processing the files as soon as they finish downloading.

**Comment by diemol** [comment]
This seems to be a corner case in browser automation, and probably a combination of WebDriver to get the link and a HTTP client that allows you to track the download progress is more suitable. In short, alternatives with more reliable tools to download files are available.

More than that, Selenium offers what is specified in the W3C WebDriver spec, so this type of case would need to be supported and implemented by all browsers. Which is why you can suggest it for consideration here https://github.com/w3c/webdriver.
