### ISSUE TITLE
[🚀 Feature]: isClickable function allowing to check if a DOM element can be clicked

### ISSUE THREAD

**Issue by doberkofler** [SeleniumHQ/selenium#10901]
### Feature and motivation

It would be most helpful to have a function that determines, if a DOM element isClickable similar to the functionality offered by [WebDriverIO](https://webdriver.io/docs/api/element/isClickable).

Return true if the selected DOM-element:

- exists
- is visible
- is within viewport (if not try scroll to it)
- its center is not overlapped with another element
- is not disabled
otherwise return false.

### Usage example

```javascript
const {Builder, By, Key, until} = require('selenium-webdriver');

(async function example() {
  let driver = await new Builder().forBrowser('firefox').build();
  try {
    await driver.get('http://www.google.com/ncr');
    const el = await driver.findElement(By.name('q'));
    const clickable = await el.isClickable();
    console.log(clickable);
  } finally {
    await driver.quit();
  }
})();
```

**Comment by titusfortner** [comment]
Big picture, Selenium tries to be unopinionated and allow users to create their own helper methods that make sense in their specific context. So this isn't something we plan to add in our code directly.

A few interesting details here, though...

If you click or send keys to an element that is not in the viewport, Selenium will automatically scroll the element into the viewport first. Unless you are using the Actions class, or there are static headers/footers/etc of some kind, you shouldn't have to scroll anything for it to work.

Right now we don't have an easy way to evaluate ahead of time whether an element is overlapped with another element. At on point I suggested it at a w3c meeting, and it didn't go anywhere, and it also made me rethink how I do these things. My recent approach is to have a click method that locates & clicks and if it isn't there, isn't visible, or is overlapped, rescue the error and either retry or take another remediating action. Clicking a disabled element is an outlier, because Selenium will not error (you should be able to click anything you want), so you would still need to check this.

**Comment by doberkofler** [comment]
Thank you for the feedback. When I need to click on something , I also use a custom condition that catches the error as long as the element cannot be clicked. In other use cases I must must wait for one element to clickable before I can continue interacting with other elements and this is why I would have hoped for an API like `isClickable` in WebDriverIO.

**Comment by titusfortner** [comment]
@doberkofler in wdio it just means that the element is displayed and enabled, you can actually still get an element click intercepted error when that wdio method returns true.
