### ISSUE TITLE
[🐛 Bug]: dotnet - FindElement By Id Exception says that it is using the CssSelector and it might cause confusion when debugging.

### ISSUE THREAD

**Issue by AlexWFreitas** [SeleniumHQ/selenium#10906]
### What happened?

If you execute a WebDriver FindElement "By Id" and pass an incorrect value on Chrome using ChromeDriver on Selenium 4.3.0 for dotnet, Selenium will throw an exception that reads like the text below.

`Unable to locate element: {"method":"css selector","selector":"#PassedValue"}`

This seems to be caused by the way that the By class is used, for example when you search by Id, it seems to use a CssSelectorMechanism and add a # to the argument. 

I can provide code to reproduce this issue if needed.

I think this also happens when using FindElement by Name and ClassName.

### How can we reproduce the issue?

```shell
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using WebDriverManager;
using WebDriverManager.DriverConfigs.Impl;

var url = "https://www.google.com/";

new DriverManager().SetUpDriver(new ChromeConfig());

var Browser = new ChromeDriver();

Browser.Navigate().GoToUrl(url);
Browser.FindElement(By.Id("feafefewaf"));
```

### Relevant log output

```shell
OpenQA.Selenium.NoSuchElementException: 'no such element: Unable to locate element: {"method":"css selector","selector":"#Frame_5"}
  (Session info: chrome=103.0.5060.134)'
```

### Operating System

Windows 11

### Selenium version

.NET - Selenium 4.3.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 103.0.5060.134

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 103.0.5060.53

**Comment by titusfortner** [comment]
Thanks for this report. 

The issue is that ID is no longer a supported locator by a w3c compliant driver. Selenium maintains backwards compatibility by converting id, name and class locators to equivalent CSS selector values. The error message is coming from the driver and represents what was actually sent to it. Selenium is not going to edit error messages from the driver. The only alternative is to deprecate the locator types that are no longer directly supported, and we prefer the slightly confusing error message to removing the locator entirely.
