### ISSUE TITLE
[🚀 Feature]: default locator type in find_element()

### ISSUE THREAD

**Issue by neurocker** [SeleniumHQ/selenium#10940]
### Feature and motivation

I'm always working with css locators only, and I'm tired of inserting this parameter all the time in latest versions of Selenium. Maybe it will be good to add some default option?

### Usage example

So instead of using by=By.CSS_SELECTOR every time:
```
driver.find_elements(By.CSS_SELECTOR, 'div.maschineListItemInner > a')
driver.find_elements(By.CSS_SELECTOR, 'li.usedSingleItem')
ad_element.find_element(By.CSS_SELECTOR, 'a')
ad_element.find_element(By.CSS_SELECTOR, 'a > div.usedSingleContent > div.usedPrice')
```

make it something like this:

```
options.default_locator = By.CSS_LOCATOR
...
driver.find_elements('div.maschineListItemInner > a')
driver.find_elements('li.usedSingleItem')
ad_element.find_element('a')
ad_element.find_element('a > div.usedSingleContent > div.usedPrice')
```

**Comment by titusfortner** [comment]
Selenium tries very hard to be unopinionated about the choices made by the end user, which means requiring explicit arguments instead of providing defaults in many cases.

We encourage users to create wrapper objects for elements, or at least wrapper methods for these locators that will allow making custom code within a specific project easier to read/write/use.
