### ISSUE TITLE
[🐛 Bug]:Selenium grid 4 console is in loading state intermittently 

### ISSUE THREAD

**Issue by remyanekkuth** [SeleniumHQ/selenium#10986]
### What happened?

Have migrated to selenium grid 4 (4.1.3) and working fine. 
But sometimes when open the console, cannot see nodes, rather seeing " loading "  message on the screen.
Attached screenshot.

Whenever we see this issue, have to go to hub and restart the task for this environment and it works. But would like to get this issue fixed.
<img width="960" alt="selenium4 console error" src="https://user-images.githubusercontent.com/16626518/187320123-b9442441-4294-473b-9c8a-daaf5aa39d33.PNG">

### How can we reproduce the issue?

```shell
set up selenium nodes for selenium grid 4 . 
Intermittently get the loading page. 
port used to set up is 5955.
```

### Relevant log output

```shell
Getting "loading " message in console
```

### Operating System

windows10

### Selenium version

java 8

### What are the browser(s) and version(s) where you see this issue?

chrome 104, edge 104

### What are the browser driver(s) and version(s) where you see this issue?

chrome driver 104. 

### Are you using Selenium Grid?

4.1.3

**Comment by diemol** [comment]
Can you please share the Grid logs after upgrading to 4.4.0?

**Comment by remyanekkuth** [comment]
@diemol 

How to get the grid log? 
we have tasks configured in task scheduler and just click run to execute windows command batch script . 
when “loading” message comes up , not seeing anything in console. 

Please help on checking the grid log

**Comment by diemol** [comment]
@remyanekkuth by the logs I mean all the output from the execution. You can also send it to a file https://www.selenium.dev/documentation/grid/configuration/cli_options/#logging

**Comment by remyanekkuth** [comment]
@diemol attaching the logs that I got. Hope this is what you asked for.
https://github.com/SeleniumHQ/docker-selenium/issues/1640 looks similar to mine. 

[output.log](https://github.com/SeleniumHQ/selenium/files/9499631/output.log)
[output-preprod-sel4 - Copy.log](https://github.com/SeleniumHQ/selenium/files/9499632/output-preprod-sel4.-.Copy.log)

**Comment by remyanekkuth** [comment]
any update on this issue ? Please suggest what can be done to avoid nodes going to loading state .

> @diemol attaching the logs that I got. Hope this is what you asked for. [SeleniumHQ/docker-selenium#1640](https://github.com/SeleniumHQ/docker-selenium/issues/1640) looks similar to mine.
> 
> [output.log](https://github.com/SeleniumHQ/selenium/files/9499631/output.log) [output-preprod-sel4 - Copy.log](https://github.com/SeleniumHQ/selenium/files/9499632/output-preprod-sel4.-.Copy.log)

**Comment by pujagani** [comment]
@remyanekkuth Thank you for sharing the logs. I have had a look at the logs and I am not seeing anything odd. The status endpoint seems to return Http status code 200 each time. Maybe the /graphql end point is not responding.
When you see the loading state of Grid, are you able to run a new session? or it just gets stuck?
Also, as based on https://github.com/SeleniumHQ/docker-selenium/issues/1640#issuecomment-1241884103
Is your machine using any security scan mechanism that might be causing this? It might be good to rule out that possibility for the root cause.

**Comment by remyanekkuth** [comment]
@pujagani No. We are getting driver exception when try to run.  
There is a vulnerability check once in a month I guess. but this is happening every week. Once I reboot , nodes will get connected. 

As a work around , I scheduled a weekly reboot for the server for now, which we shouldn’t do . 

Not sure if it is related, but I see the nodes getting graying out and getting removed from console for couple of minutes and registering again.

**Comment by pujagani** [comment]
Thank you for the quick response. Can you share that exception trace? But after the restart does it work as expected? I think the vulnerability check might be potentially causing the need for restart. It sounds awfully similar to https://github.com/SeleniumHQ/docker-selenium/issues/1646. Is it possible to disable the scan and see if it works fine (I understand this might not be easily possible)? Just trying to narrow down the root cause.
Any pointers on how can we reproduce the issue? It is only possible to fix this if we are able to reproduce the issue.

**Comment by diemol** [comment]
Since this is caused by a vulnerability check, I will close this as a duplicate of https://github.com/SeleniumHQ/docker-selenium/issues/1646
