### ISSUE TITLE
How Selenium is better as compared to NightWatch framework?

### ISSUE THREAD

**Issue by sayom88** [SeleniumHQ/selenium#10989]
### Feature and motivation

How is Selenium better than Nightwatch?

### Usage example

Hello Team,

I would like to know from a feature point of view how Selenium is better than NightWatch.

**Comment by diemol** [comment]
Comparing Selenium and Nightwatch is not correct because both tools have different scopes.

Selenium is a tool that focuses on browser automation, and has no opinions in it. By this I mean that it has no automatic waits, or extra features to enable easy debugging. See it as a low level library.

Nightwatch is built on top of Selenium, and has lots of good features that make it a full testing framework. 

So, if you are looking for a framework in JavaScript with many included features to write tests, you should use Nightwatch directly and avoid getting involved with the internals of Selenium. An alternative is WebdriverIO, another JS testing framework that implements the WebDriver specification.

If you have more questions, please reach out to us through the links shown in the comment above.

**Comment by sayom88** [comment]
Hello @diemol  thanks...our client has actually asked to showcase the pros and cons of Selenium vs Nightwatch. Hence the ask
