### ISSUE TITLE
How to print text from child node using xpath?

### ISSUE THREAD

**Issue by rajpradeep32** [SeleniumHQ/selenium#1099]
Trying to print the text ' caught Hughes' alone.Using the below xpath am able to point to the text 'caught Hughes' in the HTML code but am unable to print it. Using Java in selenium webdriver

XPATH:
++++++
//*[@id='full-scorecard']/div[2]/div/table[1]/tbody/tr[3]/td[2]/child::text()

HTML:
+++++
<td colspan="8">
<b>12.6</b>
 caught Hughes 
<b>73/4</b>
<br/>
</td>

Selenium code which isn't working:
+++++++++++++++++++++++++++
WebElement txt= driver.findElement(By.xpath(
   "//*[@id='full-scorecard']/div[2]/div/table[1]/tbody/tr[3]/td[2]/child::text()"));

System.out.println(txt);

**Comment by twalpole** [comment]
findElement finds elements -  text nodes aren't elements.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
