### ISSUE TITLE
Can't start chrome with quic disabled

### ISSUE THREAD

**Issue by arsenik** [SeleniumHQ/selenium#1112]
I need to start chrome with webdriver with quic disabled as follow:
--flag-switches-begin --disable-quic --flag-switches-end

    from selenium import webdriver
    from selenium.webdriver.chrome.options import Options as ChromeOptions

    options = webdriver.ChromeOptions() 
    options.add_argument("--disable-quic")
    _browser = webdriver.Chrome(chrome_options=options)

Doing that does not put --disable-quic in between --flags-switches-begin and end.

If I start manually chrome with "chrome.exe" --disable-quic , and go to chrome://version, I see --disable-quic added in flag-switches.

selenium 2.47.3
chrome 45

**Comment by lukeis** [comment]
you should raise the bug with chromedriver:
https://code.google.com/p/chromedriver/issues/list

since the selenium webdriver bindings are just passing the 'args' over to it to launch chrome appropriately and nothing more can be done here (unless chromedriver adds a new 'chromeOptions' capability to pass)
