### ISSUE TITLE
getAttribute() is not working for size

### ISSUE THREAD

**Issue by yadavgabhi** [SeleniumHQ/selenium#1113]
```java
element.getAttribute("size");
```
is not working for me. It throwing UnsupportedCommandException. Please help me on same.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
