### ISSUE TITLE
[🐛 Bug]: Do not store Selenium Manager binary files with in the source code repository

### ISSUE THREAD

**Issue by aaltat** [SeleniumHQ/selenium#11243]
### What happened?

Storing binary files in the source code repository is not recomended: https://github.com/SeleniumHQ/selenium/tree/trunk/common/manager/windows Instead it would be better to store them in the GitHub releases page. or somewhere else.

Storing binary files in the repository makes repository size big and surprisingly fast, which makes the cloning and updating the repository slow.  

### How can we reproduce the issue?

```shell
Stop commiting binary files to source code repository.
```

### Relevant log output

```shell
https://github.com/SeleniumHQ/selenium/commit/c927d4b34a6142c536269c6d262d6624c9d0dba7
```

### Operating System

N/A

### Selenium version

4.6.0

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Thanks for the feedback!

The project sometimes follows this approach in for different reasons, in this case, because we want to iterate quickly and we wanted to have the files available for the release. In future releases, Selenium Manager will have its own release and binaries will be uploaded to their own release.
