### ISSUE TITLE
[🐛 Bug]: Failure to send '/' using sendkeys in rich text boxes in Linux

### ISSUE THREAD

**Issue by fandazhou123** [SeleniumHQ/selenium#11344]
### What happened?

I tried to automatically submit the form in linux, and when I sent something with a '/' to the rich text box, the content got scrambled. For example, when I send "path:/root/a", the result turned out "apath:root".

### How can we reproduce the issue?

```shell
driver.get(url)
driver.switch_to.frame(driver.find_element(By.CLASS_NAME, 'ke-edit-iframe'))
content = 'desc: \n ftp://1.1.1.1/A/B'
driver.find_element(By.XPATH, '/html/body').send_keys(content)
```

### Relevant log output

```shell
-
```

### Operating System

centsos7

### Selenium version

"4.3.0"

### What are the browser(s) and version(s) where you see this issue?

107.0.5304.62

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 107.0.5304.62

**Comment by titusfortner** [comment]
You need to show us an example that explains why your situation is different from everyone else's, because no one else has reported this problem. 

You need to provide the url or an otherwise reproducible case where I can copy/paste/run and see the problem. Though, that you are using send_keys on a `body` element might be part of the problem, as it isn't typically `content-editable`.

**Comment by fandazhou123** [comment]
For some reason, I can't give my URL, and also I can't find a open website which has the same condition. The texarea is achieved by Kindeditor, maybe the problem happened when the content was sending to the Kindeditor. 
Anyway, thanks for your patience.
