### ISSUE TITLE
[🚀 Feature]: Display information about Selenium Manager activity

### ISSUE THREAD

**Issue by diemol** [SeleniumHQ/selenium#11385]
### Feature and motivation

I was releasing Java 4.7.1, and as part of the release I was doing a quick manual test on Selenium Grid. While starting Grid, the log output halted for 40-50 seconds and I panicked a bit. When the log output continued, I realized Selenium Manager was downloading the drivers for the updated browsers I have on my laptop. Should we show the user what is happening behind the scenes to avoid user confusion?

### Usage example

Would it make sense to display to the user information such as:
>Chrome 108 detected, downloading ChromeDriver 108...

**Comment by titusfortner** [comment]
Right now the bindings are swallowing that information to hide implementation details from users. For now I think we should just display that Grid is obtaining latest drivers in grid code before the relevant step.

**Comment by diemol** [comment]
The "problem" is that the code Grid uses is the same one the Java bindings use. A change would reflect on both sides.

**Comment by bonigarcia** [comment]
If I am not wrong, this feature should be implemented on the bindings side but not on the Rust side. Is that right? If so, can I update the labels accordingly?

**Comment by titusfortner** [comment]
Yes, you're right. At this point, once we support proxies and #11599 I think we're ok to throw the Selenium Manager error & link to our docs instead of current error.

**Comment by diemol** [comment]
Got it. So we can use this issue to track the logs Selenium Manager returns.

**Comment by titusfortner** [comment]
So, because Selenium Manager is the one managing everything, I don't think we can log things before hand in the detail suggested above.

If there's a problem we need to log that with `WARN` or `ERROR`

I think all we want at INFO level is:
```
INFO: Compatible browser driver not found; using Selenium Manager (Beta) to obtain a driver; Read more about using Selenium Manager:  https://selenium.dev/documentation/webdriver/selenium-manager/
```

I think everything else should be at `DEBUG` level. That documentation page should show how to turn on debugging for that info so they can see everything if they want to.

**Comment by titusfortner** [comment]
I think logging that it is starting with INFO is already happening in all the bindings. WARN & DEBUG messages are there depending on logging level. I think we still want to add a link to that INFO message to the new Install Drivers page- https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1385

**Comment by titusfortner** [comment]
This is different from the Error message. I think we want to create a "new" error for driver installation failure and link to it in https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/
And from there we'll want to link to logging to suggest that people turn on the logging for it in order to get more info about what went wrong.

**Comment by diemol** [comment]
What is exactly needed here? I got a bit lost. I now see that all bindings (except .NET) are logging that Selenium Manager will try to load the correct driver (`Applicable driver not found; attempting to install with Selenium Manager (Beta)`). Warnings and debugging should be also possible now, right?

**Comment by titusfortner** [comment]
What I've tried to do before now was to make it so that any driver-related error message users get has information they can do something about (i.e., "add the driver to PATH") instead of one they can't (e.g., "Selenium Manager doesn't support Proxies"). 

* Merge https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1390
* Create a "NoSuchDriver" exception in the bindings
* Add all relevant info into one error message with that exception and link to documentation

Here's a specific example in in Ruby — https://github.com/titusfortner/selenium/commit/35bb8b93c85abff56a49de5dcbfd359aa77dccee

**Comment by diemol** [comment]
OK, then I guess we move this to 4.11 and we need to break all those tasks into their own issues

**Comment by titusfortner** [comment]
When we do this, we should also remove the info logging that we are using Selenium Manager; another step in making Selenium Manager something users don't need to explicitly know about...

* Create a "NoSuchDriver" exception in the bindings
* Add all relevant info into one error message with that exception and link to documentation
* Remove all default INFO logging about Selenium Manager.

**Comment by titusfortner** [comment]
Just JS is left as an issue here.

- [x] 1. When Selenium Manager class gets the Binary: log location as debug if found
- [x] 2. Selenium Manager class Running: log results at appropriate level (not just WARN) and before raising exception for non-zero code
- [x] 3. Need to create custom Error for Driver not found, with link to documentation

**Comment by titusfortner** [comment]
I guess technically #12269 is what handles the non-JS differences

**Comment by diemol** [comment]
Implemented in JS, closing issue.
