### ISSUE TITLE
[🚀 Feature]: Support for chromedriver canary in Selenium Manager

### ISSUE THREAD

**Issue by bonigarcia** [SeleniumHQ/selenium#11384]
### Feature and motivation

Continuation of [#11334](https://github.com/SeleniumHQ/selenium/pull/11334). Currently, Selenium Manager downloads chromedriver from: https://chromedriver.chromium.org/

To support chromedriver canary, it should also be able to download artifacts from: https://chromedriver.chromium.org/chromedriver-canary

### Usage example

```
./selenium-manager --browser chrome --browser-version canary
```

... and `canary` exists on the machine, but the required driver version is unavailable in the stable chromedriver repository.

**Comment by titusfortner** [comment]
By definition, Canary driver will never be available in stable chromedriver repo.

My take is that for now it is ok to use the latest stable driver released for dev channel, but this issue is for if we want to be super special and try to get the "real" canary driver from the snapshot that would be cool.

So, I see this particular issue as super low priority, but a good thing to track.

**Comment by bonigarcia** [comment]
This already possible, thanks to the CfT endpoints support (introduced in Selenium 4.11.0).
