### ISSUE TITLE
Ability to take full page screenshot

### ISSUE THREAD

**Issue by foxx** [SeleniumHQ/selenium#1141]
As a follow up from #646, it would be nice if Selenium offered support to take full page screenshots.

Currently, the only way to do this in a consistent manner is to screenshot/pagedown in a loop until page end is reached, then stitch images together. This is a lot of user work, and would be great if Selenium exposed a method which handles this for the user, in all browsers. Although this could be provided as a separate library, it seems to me like the perfect candidate for core inclusion.

Could a maintainer/contributor give their thoughts?

**Comment by jimevans** [comment]
At the moment, the intended behavior of the screenshot API _is_ to produce a so-called full page screenshot. In point of fact, the current IE and Firefox drivers _do_ create full page screenshots. The Chrome driver does view-port-only screenshots, mostly due to a years-old bug in the browser that shows no signs of ever being fixed. Similarly, the Safari driver has architectural limitations imposed by the browser that prevent it from yielding full page screenshots. I was under the impression that PhantomJS would produce full page screenshots, but apparently I am mistaken. 

While this accurately describes the state of current drivers, the future behavior of drivers will be governed by a W3C specification. That spec states outright that screenshots are to be of the current view port only. This decision was discussed at length  Moreover, driver implementations are increasingly provided by browser vendors, not the Selenium project. This has been the case for Opera and Chrome for quite some time, recently for Microsoft Edge, and soon to be for Mozilla Firefox.

**Comment by foxx** [comment]
Thank you for the detailed response @jimevans, much appreciated

**Comment by Jorge2M** [comment]
Scroll in the page for capture screenshot is not a solution when the page implement a scroll functionality. The scroll for capture screenshot will affect the aspect page.

**Comment by shubhanjalidubey** [comment]
Full Page ScreenShot seem to be broken again for latest driver for firefox which is geckoDriver.
Has anybody experienced this?

**Comment by MelindaN** [comment]
I have the same problem with gecko driver. Firefox was actually the only driver that I could use for taking screenshot with scroll option (had to downgrade my FF version to 47.0.1). Now I want the same feature for FF 49, and I cannot use other libraries that provide scrolling and stitching screenshots together ... So please reopen and fix this issue asap.

**Comment by jigyasa-at-git** [comment]
Same here! With this latest stack:
selenium-server-standalone-3.0.0-beta4
geckodriver-v0.11.1-win64
Firefox 49.0.1

I was unable to execute even the basic code of driver.get(url), let alone take screengrab. The only thing that happened was - Firefox browser would open. I had to finally downgrade to 47 to make code work. Definitely some solution will be greatly appreciated.

Also, for the full page screenshot, it is happening only for older Firefox version. IE, Chrome and Edge take view port screengrabs only. I have provided the details on this page: http://newbieshelper.blogspot.com/p/take-screenshot.html

I have not used ‘stitching’, but will look into it and add the details on the above page.

**Comment by jamesthecat7** [comment]
Exactly the same experience as jigyasa-at-git, I too have downgraded to FireFox 47 to keep the fullpage screenshot functionality. I find scroll and stitch a nightmare due to fixed position elements but I can't see any other solution.

**Comment by MelindaN** [comment]
Maybe if we had a method for taking screenshot to an webpage element without cropping the whole page in order to capture the element with located position and crop with its height and width... maybe then we could consider the most external tag like <html> (or something like that) as an element from page and take screenshot to the page?

But even though the specification from webdriver (w3c) has a chapter called `Take element screenshot` I wasn't able to use it because I think it's not implemented yet. 

e.g. For a webElement located with driver.findElement we can use `File urlScreenshot = element.getScreenshotAs(OutputType.FILE)` ...

**Comment by jantman** [comment]
Using Firefox 49.0.2 on Linux with Ruby selenium-webdriver 3.0.0 and geckodriver 0.11.1, I can launch the browser and navigate, but screenshots are exactly like they are on modern Chrome - the visible viewport only, and nothing more...

**Comment by ababushkin** [comment]
I'm having the same issue as @jantman

**Comment by fabtho** [comment]
I do understand that the spec is screenshot = viewport size, but why not add another like get_full_screenshot_as_file or so?

**Comment by cgoldberg** [comment]
> why not add another like get_full_screenshot_as_file or so?

because the underlying browsers and browser drivers don't support this.
