### ISSUE TITLE
[🚀 Feature]: Checking if Page is Loaded

### ISSUE THREAD

**Issue by shyampatadia** [SeleniumHQ/selenium#11424]
### Feature and motivation

I have been running into issues with using selenium in complicated webflows with many page loads.  It seems there isn't a way to verify that a page that we navigated to is fully loaded or the elements inside the page that we are navigating is fully loaded. There might be some way to do it which I might not be aware of? Because whenever I try to automate a webapp I get ElementNotFound errors because the page is not loaded meaning that the element might be loaded inside the DOM but the UI is not displayed or loaded fully. 

### Usage example

A feature like this is useful to check whether an element is displayed on the UI when we try to perform some action on the specified element. Currently, I have to use hard coded thread sleeps to wait and check if the element is now visible, which slows down my runtimes

**Comment by titusfortner** [comment]
In today's web, "fully loaded" doesn't really make sense. On navigation commands, Selenium waits for the Document Readiness State to be complete, but that doesn't include all the scripts that are executing to load new things. Those scripts might not finish or might not keep you from doing the thing you need to do. I've fixed problems before by removing even the wait for Document Readiness State when unnecessary assets weren't properly loading.

You should be using a looping [explicit wait strategy](https://www.selenium.dev/documentation/webdriver/waits/#explicit-wait) instead of hard coded sleeps for checking to see if the element you want to work with is in a state that can be used. Alternately you can set up a loop that catches the exceptions and retries until it works.

There is no good way to automatically ensure the thing you need to be ready is in fact ready, and users need to provide their own synchronization strategies for that.
