### ISSUE TITLE
Can't find children of WebElement based on FindBy className locator

### ISSUE THREAD

**Issue by lesho** [SeleniumHQ/selenium#1152]
Hi, 
I have one element found with two different locators:
```java
    @FindBy(className = "error")
    private WebElement weError;
    
    @FindBy(xpath = "//ul[@class='error']")
    private WebElement weError2;
```
Now I want to get their children:

```java
        List<WebElement> elements = weError.findElements(By.xpath("child::*")); 
        System.out.println("elements.size() = " + elements.size());

        List<WebElement> elements2 = weError2.findElements(By.xpath("child::*"));
        System.out.println("elements2.size() = " + elements2.size());
```

Is it correct behavior that  elements.size()  = 0, while elements2.size() = 7? 
There is only one element with class="error" in the application

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
