### ISSUE TITLE
[🐛 Bug]: SetLoggingPreference doesn't seem to be working for RemoteWebDriver

### ISSUE THREAD

**Issue by ParanoikCZE** [SeleniumHQ/selenium#11588]
### What happened?

The use case is to obtain WebSocket application communication with the backend. It works flawlessly with ChromeDriver, but after switching to RemoteWebDriver, AvailableLogTypes is empty and same while trying to get log items.

### How can we reproduce the issue?

```shell
var options = new ChromeOptions();
options.SetLoggingPreference(LogType.Performance, LogLevel.All);
driver = new RemoteWebDriver(new Uri(configuration.SeleniumGridUrl), options.ToCapabilities());

var logEntries = _driver.Manage().Logs.GetLog(LogType.Performance);
```

### Relevant log output

```shell
N/A
```

### Operating System

W10

### Selenium version

4.8.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 109

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 109.0.5414.7400

### Are you using Selenium Grid?

4.7.2

**Comment by diemol** [comment]
This is expected because Grid is not implementing the log methods at the time given that this is a Chromium only feature. We do not want to add this to remove it later, given that different browser vendors are working with the Selenium project to have that feature in a standard way. Please follow the development at https://github.com/w3c/webdriver-bidi.

For now, if you need this, you might implement a non-supported workaround which was shown for C# in a related [issue](https://github.com/SeleniumHQ/selenium/issues/9377#issuecomment-822248803).
