### ISSUE TITLE
[🐛 Bug]: No compatible version of selenium-devtools with Chrome 110

### ISSUE THREAD

**Issue by arielj** [SeleniumHQ/selenium#11650]
### What happened?

Chrome 110 was released and applications that use selenium-devtools fail to run tests since the newest version of selenium-devtools is 109.

I'd be happy to make a pull request with the version changes, I don't know if that's what's needed.

### How can we reproduce the issue?

```shell
In an application that uses selenium-devtools (109 or older), update the version of Chrome to version 110.
```

### Relevant log output

```shell
LoadError:
  cannot load such file -- selenium/devtools/v110
```

### Operating System

Linux Mint 21 and MacOS Monterrey

### Selenium version

4,8,0

### What are the browser(s) and version(s) where you see this issue?

Chrome 110

### What are the browser driver(s) and version(s) where you see this issue?

Not sure how to check this

**Comment by titusfortner** [comment]
Selenium is behind in releasing support for Chrome v110. Unlike the other languages, Ruby releases a separate gem. Which is good because it doesn't have to wait for a Selenium release, but because of that we don't provide a fall-back option, and we're behind on even adding support to the repo.

Plan is to get it done tomorrow. Thanks for your patience.

Adding this issue for future - https://github.com/SeleniumHQ/selenium/issues/11651

**Comment by titusfortner** [comment]
We'll track the long-term fix in that issue instead of here.
