### ISSUE TITLE
[🚀 Feature]: Selenium Manager documentation

### ISSUE THREAD

**Issue by bonigarcia** [SeleniumHQ/selenium#11695]
### Feature and motivation

If #11694 is done, Selenium Manager needs its own documentation.

### Usage example

n/a

**Comment by bsquizz** [comment]
+1 I'd like to see some improvements related to how the binary is released and the documentation around that. I see several issues open here related to enhancing this and I'm not sure which ticket to place this upvote on... but let me highlight a problem we have recently run into:

As of Selenium version 4.6.0 it appears that the selenium-manager binary that is released with the python `selenium` package requires glibc 2.29. This is a problem for systems running RHEL8 which is based on glibc 2.28. If we had the opportunity to install the python package with a different selenium-manager binary that would help in this kind of situation.

It's not clear to me how/where this binary gets built and released so documenting how it appears in the python package would be helpful as well.

For the time being, I think our quick fix is to simply pin to selenium 4.5.0. It's not clear to me what the recommended approach would be to using a different 'selenium-manager' binary. I suppose I could compile it myself and then overwrite the one shipped with the python package, or update the PATH so that my custom selenium-manager is executed before the "packaged" one. I have to try some of these options out.

**Comment by titusfortner** [comment]
I'm against releasing it separately, it would only be (more) confusing to Selenium users who already don't realize they don't need to download it. It's still beta and we're still working out bugs.

@bsquizz can you update to latest 4.8, that bug should have been fixed.

**Comment by bsquizz** [comment]
Thanks, will give the latest 4.8 a try.

As far as releasing binaries within the python package goes, I can understand that releasing it as part of the package makes people's lives easier -- I am just not sure how I would "swap out" selenium-manager to use my own if it was necessary. It looks like the path is hard-coded, correct? https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/common/selenium_manager.py#L51

So at the very least I think an env var allowing users to change the binary location might be needed.

Improvements could possibly be made to the packaging/release process too -- one example that comes to mind in the python world is the `psycopg2-binary` vs `psycopg2` package. `pip install psycopg2-binary` installs a pre-compiled binary whereas `pip install psycopg` compiles the binary during the pip install. The 1st option is easy for most users to get up and running quickly, and the second does require that you have the build dependencies present on your system but offers flexibility. I am wondering if a similar approach could be useful for selenium as well (i.e., if a certain pip install option would trigger a local compile of selenium-manager and then point the `selenium` package to use that locally compiled binary)

**Comment by bsquizz** [comment]
It does look like 4.8.2 takes care of the glibc issue -- thanks.

**Comment by titusfortner** [comment]
@bsquizz there's an open issue that would essentially allow this: #11359 it would have some other advantages, and would make a good solution for advanced users in your use case.

Also, I'm not sure why you pinned to 4.5? Whatever you were doing in 4.5 to get drivers to work should have also worked in 4.6. Selenium Manager shouldn't be getting used right now unless no drivers are found on the system and it would otherwise error. That bug was found in the first release, and hopefully we won't see many more of that magnitude.

The biggest issue is we don't guarantee a stable API, yet, and some things are likely to change when we add browser download support. Ideally, once we get the release process more streamlined (we need to be able to cross compile), it'll be easier for us to update the manager with latest bug fixes and do patch releases of the bindings when/if they come up.

As for the packaging/release... it is implemented and compiled with Rust so that we do not have to do any language specific things. The binaries themselves are included in the package so that each of the bindings do not need to implement the extra downloading logic that would otherwise be required.

**Comment by bsquizz** [comment]
OK good to know.

We thought about pinning to v4.5 because once we ran into the glibc error on v4.8.0 we didn't realize we had hit a bug -- rather we assumed that the newer releases were starting to require a newer glibc. When we started to look back at prior releases to find an older binary, v4.5 appeared to be the most recent binary that worked with glibc 2.28 -- but we might have overlooked v4.6. At any rate, moving up to v4.8.2 did get us past the error.

As for what we were doing -- after we got past the glibc error we discovered we ran into this whole problem "by accident." Someone on our team was executing some code in a ubi8 container image (ubi8 is based on glibc 2.28) which had python-selenium installed. Normally for our workflows we are using a Remote webdriver when running in this container image but a code path that was trying to set up a local webdriver was unexpectedly invoked, which led to selenium-manager being invoked, and the glaring glibc error distracted us from getting to the root problem for a bit :)

**Comment by titusfortner** [comment]
@bonigarcia what documentation are you thinking of for this. Is this good enough, or are you thinking something in the repo? https://www.selenium.dev/documentation/selenium_manager/

**Comment by bsquizz** [comment]
I think the main thing I'm still curious about is:
> It's not clear to me how/where this binary gets built and released

The doc mentions it is a rust binary, but not where the code is for it. After some searching I think I found it here: https://github.com/SeleniumHQ/selenium/tree/trunk/rust -- I would suggest noting this location in the doc. If I want to take a look at the build environment/build config for this -- where are the jobs defined that the team uses to release and compile it? When you run the build for an official release, is it being run on a specific platform/VM/etc.? Being run as a github action (or something else?). In my opinion some adding some quick pointers in the doc with more info about how that binary gets built and added into the python package would be useful.

**Comment by titusfortner** [comment]
Great feedback, would you be interested in updating/making a PR for the document? https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/website_and_docs/content/documentation/selenium_manager.en.md?plain=1

We can't get it to cross compile in Rust the way we expected, so we rely on Github actions runners to build binaries in windows, linux & mac:
https://github.com/SeleniumHQ/selenium/actions/workflows/build-selenium-manager.yml
Turns our that these work in both x86 and arm architectures, so 3 binaries works for almost all use cases.

we manually check the Artifacts into the repo (for now), bazel currently grabs those pre-built binaries for testing and packaging releases.

**Comment by bonigarcia** [comment]
The doc looks nice. It can be extended in some parts, IMO. If you want, I can prepare a PR for that.

Moreover, in my opinion, Selenium Manager deserves to be released independently. I already mentioned this in the past, and I still think the same. 

During SeleniumConf, there were several questions about how to get and use custom configurations for other use cases than Selenium WebDriver and Grid. For example, when people create their own Docker containers with browsers, they need to resolve the drivers automatically. And for that, Selenium Manager (as a standalone CLI tool) can help.

**Comment by titusfortner** [comment]
Yes, please update that page with whatever you think makes sense!

I feel like I'm already fighting confusion about Selenium manager even without it being a separate download. I'm not against a separate release artifact, I just want to us to have explicit use cases to target so that we can get our messaging sorted. Like, I don't understand how the scenario you mentioned can't be accomplished by current behavior, either local, standalone or node.

**Comment by bsquizz** [comment]
Brief explanation of the build/release process that was described here will be added to the docs via https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1399

**Comment by bonigarcia** [comment]
This issue is in progress since we already have an initial [Selenium Manager documentation](https://www.selenium.dev/documentation/selenium_manager/). Nevertheless, this page should be completed/enhanced, IMO. I'll try to do it as soon as possible.
