### ISSUE TITLE
[🐛 Bug]: NavigateToUrl method

### ISSUE THREAD

**Issue by Correia87** [SeleniumHQ/selenium#11755]
### What happened?

My selenium WebDriver sometimes can't use NavigateToUrl  method, 70% of the times its possible to navigate to the webpage and 30% selenium can navigate to the webpage but NavigateToUrl freeze and give me a timeout 10min later.

### How can we reproduce the issue?

```shell
try {
                driver.navigate().to(url);
            } catch (Exception e) {
                throw new TestFailException("Error navigating to the new URL", e);
            }
```

### Relevant log output

```shell
org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.8.0', revision: '267030adea'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_341'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [63cfa7bb80422863669436c3f35ef810, get {url=url}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 110.0.5481.105, chrome: {chromedriverVersion: 109.0.5414.74 (e7c5703604da..., userDataDir: C:\Users\a\AppData\Local\Te...}, goog:chromeOptions: {debuggerAddress: localhost:58335}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:58335/devtoo..., se:cdpVersion: 110.0.5481.105, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 63cfa7bb80422863669436c3f35ef810
```

### Operating System

Windows 11

### Selenium version

4.8.0

### What are the browser(s) and version(s) where you see this issue?

111.0.5563.65

### What are the browser driver(s) and version(s) where you see this issue?

111.0.5563.64

**Comment by titusfortner** [comment]
You are not providing a way for us to troubleshoot your issue.

First, your driver version does not match your browser version, which may or may not cause a problem.
Secondly, it shouldn't take that long to timeout.

The code sends a message to the driver, which sends a message to the browser, and when the document readiness state is "complete," the browser sends a message to the driver which sends a message to the code.

Typically this error happens when the page load gets stuck and the document readiness state never changes to "complete."
When the driver doesn't hear back from the browser after the PageLoadTimeout interval (5 minutes), it will report a timeout error to the Code.

That error is also unlikely, because the Java HTTP Client only waits 3 minutes to get a response back from the driver, so you should be getting an error at most 3 minutes after sending the command.

To see if the problem is the page not loading, you can set the `PageLoadStrategy` to `"none"` and it will return without waiting for a specific document readiness status value.

The only other alternative is that there is some kind of bug in the driver, but that would need to be filed with Google
