### ISSUE TITLE
implicitly_wait and WebDriverWait.until

### ISSUE THREAD

**Issue by liyang0452** [SeleniumHQ/selenium#1176]
when I set implicitly_wait to 100, but WebDriverWait.until to 10.   the until not stop after 10.

Becase of until will wait implicitly_wait .

So I think the until impletement need to change if until < implicitly_wait ,  set implicitly_wait=0 , and at the end of until recovery implicitly_wait .

Thank you

**Comment by lukeis** [comment]
Selenium doesn't allow you to fetch the current implicit wait setting and doesn't otherwise track the current setting. It's up to the end user to implement something like this if they so desire and it's documented that one should not be mixing Implicit and Explicit waits:

http://docs.seleniumhq.org/docs/04_webdriver_advanced.jsp#explicit-and-implicit-waits

This is not a bug, rather a known side affect with mixing them. It's highly recommended to not use implicit waits at all and just use the WebDriverWait mechanism.
