### ISSUE TITLE
I am getting this error when trying to open ie browser "unexpected error launching internet explorer ielaunchurl() returned hresult 80070005"

### ISSUE THREAD

**Issue by bleeet** [SeleniumHQ/selenium#1177]
hi guys

when I try to run my script I am getting this error when it tries to open the ie browser. 

"unexpected error launching internet explorer ielaunchurl() returned hresult 80070005"

From my searches this seems to be a frequent issue that has happened to a lot of people. Is there a fix for this? I have set all the permissions to unchecked in each zone in the ie security tab but still get this error. 

I am using ie 10

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
