### ISSUE TITLE
[🐛 Bug]: Need refactor method: mergeInOptionsFromCaps in class: ChromiumOptions

### ISSUE THREAD

**Issue by brucechen-github** [SeleniumHQ/selenium#11857]
### What happened?

`List<String> arguments = (List<String>) (options.getOrDefault("args", new HashMap<>()));`

Exception:  java.lang.ClassCastException: class java.util.HashMap cannot be cast to class java.util.List

Little Suggestion: Can we change **new HashMap<>()** to **new ArrayList<>()** ?

### How can we reproduce the issue?

```shell
ChromeOptions chromeOptions = new ChromeOptions();
Map<String, Object> capMap = new HashMap<>();
capMap.put("goog:chromeOptions", ImmutableMap.of("binary", "xxx"));
DesiredCapabilities desiredCapabilities = new DesiredCapabilities(capMap);
chromeOptions.merge(desiredCapabilities);
```

### Relevant log output

```shell
Exception in thread "main" java.lang.ClassCastException: class java.util.HashMap cannot be cast to class java.util.List (java.util.HashMap and java.util.List are in module java.base of loader 'bootstrap')
	at org.openqa.selenium.chromium.ChromiumOptions.mergeInOptionsFromCaps(ChromiumOptions.java:366)
	at org.openqa.selenium.chrome.ChromeOptions.merge(ChromeOptions.java:78)
```

### Operating System

Windows10

### Selenium version

Java - 4.8.3

### What are the browser(s) and version(s) where you see this issue?

Chrome 111

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 111

**Comment by titusfortner** [comment]
Few things: `merge()` no longer mutates the capabilities, and `DesiredCapabilities` should not be used (try `MutableCapabilities` if you need something that can be set dynamically).

Your example code does not show you using the `arguments` variable, but `arguments` needs to be a `List` not a `Map` as is described in the error.

You should be doing things with the provided methods instead of setting them dynamically:

```
ChromeOptions chromeOptions = new ChromeOptions();
chromeOptions.setBinary(binaryLocation);
chromeOptions.addArguments(arg1, arg2, arg3);
```
