### ISSUE TITLE
[🐛 Bug]: Issue with Netty Package in Selenium Java Jar

### ISSUE THREAD

**Issue by mohamedoabbiit** [SeleniumHQ/selenium#11879]
### What happened?

When we run the Prisma scan its fails

### How can we reproduce the issue?

```shell
rerun the pipeline related to it
```

### Relevant log output

```shell
CVE-2022-41881 | high     | 7.50 | io.netty_netty-codec | 4.1.79  | fixed in 4.1.86 | > 3 months | < 1 hour   | -97        | Netty project is an event-driven asynchronous      | Yes               |
|                |          |      |                      |         | > 3 months ago  |            |            |            | network application framework. In versions prior   |                   |
|                |          |      |                      |         |                 |            |            |            | to 4.1.86.Final, a StackOverflowError can be       |                   |
|                |          |      |                      |         |                 |            |            |            | raised whe...
```

### Operating System

Ubuntu

### Selenium version

4.8.2

### What are the browser(s) and version(s) where you see this issue?

chrome v.111.0

### What are the browser driver(s) and version(s) where you see this issue?

v.111.0

### Are you using Selenium Grid?

4.8.2

**Comment by mohamedoabbiit** [comment]
I send email to security team with more details about this ticket.

**Comment by titusfortner** [comment]
Selenium relies on Async HTTP Client, which relies on Netty v4.1.60. Async HTTP Client has not been maintained and has not had a new release in over 2 years. This is why we recommend people to upgrade to using the Java 11 client if they are using Java 11+ — https://www.selenium.dev/blog/2022/using-java11-httpclient/

There is a new maintainer of the Async HTTP Client project, and if they make a new release that does not rely on a vulnerable version of Netty, we will upgrade to using it, but in the meantime, there is nothing we can do about this issue.

**Comment by a2m8** [comment]
If as of selenium 4.5.x recommendation is java11 client, Can the docker images be updated to not even have AHC as part of the image?
selenium is on 4.8.x now and if AHC is being deprecated in favor of java 11 client then enterprises CANNOT utilize since CVE-2022-41881 is a blocker once it hits scans as mentioned by OP.

**Comment by titusfortner** [comment]
Please file a ticket with [Docker Selenium](https://github.com/SeleniumHQ/docker-selenium/issues/new/choose)

**Comment by diemol** [comment]
The Docker images already use the Java 11 client by default. We cannot exclude in a simple way the Java 8 client because it would break things for many Selenium Server users.

The good news is that you can create an issue at https://github.com/AsyncHttpClient/async-http-client and ask them to release a new version.
