### ISSUE TITLE
[🚀 Feature]: Intercept network and get response body

### ISSUE THREAD

**Issue by Terence625** [SeleniumHQ/selenium#11872]
### Feature and motivation

Selenium already has some Network Intercept BiDi APi like `onIntercept` which is given in the example of BiDi API: https://www.selenium.dev/documentation/webdriver/bidirectional/bidi_api/. However, this API can only used for mock the API response, I want to have some BiDi API that can capture the request's real response with response body. 

I know there is a cdp method called `Network.getResponseBody` that can get the request response body, but the current `CDPConnection` does not return responseBody when running 
```
const connection = await driver.createCDPConnection('page')
connection._wsConnection.on('message', async (message) => {
      const params = JSON.parse(message)
      if (params.method === 'Network.loadingFinished') {
        const requestParams = params['params']
        //this command does not return the response body
        const body = await connection.execute('Network.getResponseBody', {requestId: requestParams.requestId})
      }
    })
```
I saw a workaround by @tenbits in https://github.com/SeleniumHQ/seleniumhq.github.io/issues/1155#issuecomment-1254236233, which is amazing and works for me. But it'll be great if some BiDi API that supports this feature comes from Selenium's end. 

### Usage example

I would like some BiDi API like `onInterceptRequest` that can intercept particular `url` or `Regex url` as below:
```
const connection = await driver.createCDPConnection('page')
await driver.onInterceptRequest(connection, url, (result) {
  console.log(result.responseBody)
  console.log(result.status)
})
```
It's just some rough idea of the some API like cypress or playwright has. But it would be good enough to just make `CDPConnection.execute('Network.getResponseBody', {requestId: requestParams.requestId})` to return response body. I also hope I can have more knowledge of the implementation of cdp so maybe I can contribute to complete the cdp implementation

**Comment by titusfortner** [comment]
Ok, yes, this is a bit confusing, let me try to unpack the various things.
Selenium 4.0 support is entirely with Chrome DevTools Protocol, which Firefox partially adopted. The goal is to create a true cross-browser implementation of this in a [WebDriver BiDi spec](https://w3c.github.io/webdriver-bidi/).

Everything that is `executeCdp()` or `createCDPConnection()` in Selenium is using Chrome specific functionality, and will eventually be removed. The new spec compliant functionality will be using `getBidi()` under the hood.
You can see how it is getting wrapped here — https://github.com/SeleniumHQ/selenium/tree/trunk/javascript/node/selenium-webdriver/bidi and how it is getting used here — https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/node/selenium-webdriver/test/bidi/bidi_test.js

As to the specific functionality you want, it needs to be supported by what's in the spec. The BiDi spec just added the network module last week (https://github.com/w3c/webdriver-bidi/commit/47f0b65df3a01e299f5758cb546ae1af0201b7e9), and Firefox has it (mostly?) implemented in Nightly right now.

When the spec supports it and a browser has implemented it, Selenium will write the code to use it. If you have an interest in helping us with this, we'd greatly appreciate it. Feel free to reach out to us in #selenium-tlc channel on [Selenium IRC / Slack](https://www.selenium.dev/support/index.html#ChatRoom)

Since this is work we are tracking elsewhere I'm going to close this specific ticket, but I'll let @TamsilAmani know about your specific concerns since he's been the person working on the JS pieces so far.
