### ISSUE TITLE
[🐛 Bug]: WebKitGTK Does Not Support Providing Host Parameter

### ISSUE THREAD

**Issue by davidjayb** [SeleniumHQ/selenium#11897]
### What happened?

When trying to run the WebKitGTK driver in an Ubuntu Docker on MacOS container the driver fails to start. The WebKitWebDriver service is trying to bind to the local IPv6 port. IPv6 is only supported on Linux hosts:
https://docs.docker.com/config/daemon/ipv6/

### How can we reproduce the issue?

```shell
Create a Dockerfile like the following:


FROM ubuntu:focal

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt-get install -y epiphany-browser webkit2gtk-driver

RUN pip install --upgrade pip wheel
RUN pip install selenium


Create a test file using something similar to this:

```python
from selenium import webdriver

options = webdriver.WebKitGTKOptions()
options.binary_location = "epiphany"
options.add_argument("--automation-mode")
options.add_argument("--host=127.0.0.1")
driver = webdriver.WebKitGTK(options=options)
```

Try running the tests.
```


### Relevant log output

```shell
Failed to start HTTP server at port 54385: Could not listen on address ::1, port 54385: Error binding to address [::1]:54385: Cannot assign requested address
```

### Operating System

MacOS Ventura 13

### Selenium version

Python 4.8.3

### What are the browser(s) and version(s) where you see this issue?

Epiphany 3.36.4

### What are the browser driver(s) and version(s) where you see this issue?

webkit2gtk-driver_2.28.1-1

### Are you using Selenium Grid?

No

**Comment by hlootens** [comment]
Same issue here, seems to me the parameters for the WebDriver are not aligned with how it is done for chromium and firefox, where the service is not created in the init, but passed as an argument. 
When the service is passed as an argument, users have full access to all parameters of WebKitWebDriver executable.

**Comment by diemol** [comment]
> Same issue here, seems to me the parameters for the WebDriver are not aligned with how it is done for chromium and firefox, where the service is not created in the init, but passed as an argument. When the service is passed as an argument, users have full access to all parameters of WebKitWebDriver executable.

I see what you mean. However, after checking the code, I do not see how that influences the situation @davidjayb is seeing. 

I was checking the [Service](https://github.com/SeleniumHQ/selenium/blob/6be659b6cf99846db616ba8ef17cf4f413692030/py/selenium/webdriver/common/service.py#L41) class in charge of instantiating the service driver by calling the binary with the required flags. I did not see any special treatments in the code depending on the browser. 

I think the issue might be in the driver, because the message:

```
Failed to start HTTP server at port 54385: Could not listen on address ::1, port 54385: Error binding to address [::1]:54385: Cannot assign requested address`
```

comes from the browser driver binary itself. 

Have you tried reaching out to them?

**Comment by hlootens** [comment]
Correct, it does not, but the exception thrown there is not thrown by the browser, but by the WebKitWebDriver binary:

```
/ # WebKitWebDriver -p 6548
Failed to start HTTP server at port 6548: Could not listen on address ::1, port 6548: Error binding to address [::1]:6548: Address not available
/ # WebKitWebDriver --help
Usage: WebKitWebDriver options
  -h,          --help             Prints this help message
  -p <port>,   --port=<port>      Port number the driver will use
               --host=<host>      Host IP the driver will use, or either 'local' or 'all' (default: 'local')
/ # WebKitWebDriver -p 6548 --host=all
```

The problem with the default host in a docker container is that it resolves to ::1, which doesn't exist in a container, when this is changed to all, the web driver application starts without issues.

Passing the arguments for the browser through the Options works fine.
I tested passing this in my container using a dirty patch to always add adding the parameters `service_args=["--host=all"]` to the service instantiation, and it resolves the problem mentioned above.

The only issues I still got after that came from the browser binary itself complaining about availability of a display or graphical drivers, but those issues are due to the environment.

**Comment by diemol** [comment]
>Correct, it does not, but the exception thrown there is not thrown by the browser, but by the WebKitWebDriver binary:

Yes, that is what I meant, by the driver binary from the browser.

What do you mean by a "dirty patch"? Is there something you see we could improve in the Python bindings?

**Comment by hlootens** [comment]
WebDriver instantiation currently does not allow to pass parameters to Service in the bindings. Service itself has bindings to pass parameters, but there's no way of using them in practice, as the Service is created within WebServer.__init__.

My dirty hack was no more than hardcoding to add the --host=all parameter at the Service instantiation on the following line: https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/webkitgtk/webdriver.py#L62 . 
Not a clean solution that can be released, but it was effective to confirm what causes the issue.

**Comment by davidjayb** [comment]
@hlootens @diemol that is what I found as well, you are unable to pass these parameters to the WebKitGTK driver. Looks like the other drivers allowed you to pass in service arguments which may have allowed you to pass in these parameters (such as the host parameter) and that functionality has since been deprecated in favour of instantiating the Service outside of the driver:
https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/firefox/webdriver.py#LL148C16-L148C16

Looks to me like the WebKitGTK driver could use some TLC.

**Comment by diemol** [comment]
But you can create a service and pass those args, isn't it? And then pass the service as a parameter to the driver.

**Comment by symonk** [comment]
Those drivers don't accept the normal args at the moment, they are somewhat neglected.  It also links to #12408 and I'll be sorting it in the release following `4.11.0`, no capacity right now

**Comment by titusfortner** [comment]
But this can easily be user subclassed? I don't think we're doing anything special under the hood for it.

**Comment by titusfortner** [comment]
There has been an update to this code, please let us know if it has addressed the issue.

**Comment by titusfortner** [comment]
Closing as we didn't get a response, we can re-open if there is still an issue
