### ISSUE TITLE
[🐛 Bug]: 'data:,' in the address bar while using chromedriver 112.0.5615.49 and selenium 3.141.0

### ISSUE THREAD

**Issue by sbasu2023** [SeleniumHQ/selenium#11924]
### What happened?

After installing the Chrome Version 112.0.5615.138 with Chrome driver Driver Version: 112.0.5615.49 I am getting 'data:,' in the address bar while running automation headless=false (non-headless mode)

### How can we reproduce the issue?

```shell
1.Install the latest Chrome version 112.0.5615.138
2. Run selenium python automation on non-headless mode
3. Getting 'data:,' in the address bar with blank page and automation failing
```

### Relevant log output

```shell
HOOK-ERROR in before_scenario: WebDriverException: Message: unknown error: Chrome failed to start: exited normally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

### Operating System

Windows 11

### Selenium version

selenium 3.141.0

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 112.0.5615.138 

### What are the browser driver(s) and version(s) where you see this issue?

Chrome driver Driver Version: 112.0.5615.49

**Comment by titusfortner** [comment]
* We do not support anything but the latest version of Selenium. 
* `data:,` is the standard start page, so that isn't actually a problem.
* The error you are seeing is part of a known Chrome issue: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4403
* I don't think `headless=false` does anything. If you do not want headless, do not add the capability at all.
