### ISSUE TITLE
Not able to get the xpath count, getting "error occuredTypeError: undefined is not a function"

### ISSUE THREAD

**Issue by chotugaru** [SeleniumHQ/selenium#1193]
I tried using the following command
var browser = require('selenium-webdriver');
var sample1 = browser.findElements(driver.By.xpath('//somenode')).getXpathCount();
console.log( sample1.intValue() );

**Comment by JustinPhlegar** [comment]
This will probably be closed soon for being a question rather than an issue. But I saw you posted the same question in [StackOverflow](http://stackoverflow.com/questions/33337868/how-can-i-get-xpath-count-in-selenium-webdriver-using-jasmine-javascript/33359231#33359231) and I have replied there. You can also try the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users) to ask questions

**Comment by jleyba** [comment]
There is no getXpathCount() method, nor has there ever been one.  The closest thing is

```
browser.findElements(By.xpath('//somenode'))
    .then((nodes) => console.log(nodes.length));
```

Refer to the [API docs](http://seleniumhq.github.io/selenium/docs/api/javascript/class_webdriver_WebDriver.html#findElement) for more info.
