### ISSUE TITLE
[🚀 Feature]: Enhance Customize Node Functionality For Session Stop & Session Timeout

### ISSUE THREAD

**Issue by asolanki-in** [SeleniumHQ/selenium#11991]
### Feature and motivation

Hi Team,

Not sure why its not working in existing functionality of customize node as given in [docs](https://www.selenium.dev/documentation/grid/advanced_features/customize_node/).

as per example given on above link a class is extended using node

```JAVA
public class DecoratedLoggingNode extends Node
```

and this class contains a overridden method called stop as follows

```JAVA
@Override
public void stop(SessionId id) throws NoSuchSessionException {
   perform(() -> node.stop(id), "stop");
}
```

whenever I am building a jar running with selenium 4 jar with browser automation, other methods are getting called properly except this stop method not sure why.

- I suggest, this stop method should get called whenever a `driver.quit()` is called by user.
- stop method should get invoke when a session is terminated with timeout also.

This is a must feature if any developer wants do some clean-up in his custom code when session is finished or some time calculation based on session start and session closed.

### Usage example

Calculating Usage(in seconds or hours may be) of a particular browser or mobile device. for example

`session created: 04/05/2023 12:00:00`
`session stop:  04/05/2023 12:30:00`
`total session time was 30 mins`

using this a developer can store data like how much time a browser or device was used.
what device or browser is most popular in terms of usage.

All this information will important when we create a device lab and browser lab for our multiple teams.

**Comment by krmahadevan** [comment]
Adding some additional context

The `stop()` method is internally called via the `executeWebDriverCommand()` from within the LocalNode and that is the reason why the decorated node never gets the call.

Here's how the call trace goes

Test calls `driver.quit()` -> `CustomizedNode.executeWebDriverCommand()` ->` LocalNode.executeWebDriverCommand()` -> `LocalNode.stop()` 

There are two ways that I can think of which can be used to have this addressed.

1. Enhance `CustomizedNode.executeWebDriverCommand()` to filter out `quit()` and then have it explicitly call `CustomizedNode.stop()`
2. Add a new no-op method inside `LocalNode` which will be called from `LocalNode.stop()` that would basically let a user do some clean up activity.

Here's the issue that @asolanki-in raised against my sample project https://github.com/krmahadevan/demo-node/issues/1

@diemol  thoughts ?

There are some additional questions as well. Today the factory method that is responsible for instantiating `LocalNode` takes in a lot of parameters and eventually builds the `LocalNode`. For an end user having to go through all that parsing is going to be very painful and without getting all those parameters, even if a user subclasses `LocalNode` they cannot instantiate it.

Maybe we should build/expose a utility method which when invoked would basically return back all the parameters that are required by `LocalNode` so that a user can just invoke this utility method within their factory method to pass in all the mandatory parameters needed by children of `LocalNode`.

**Comment by diemol** [comment]
Probably moving the `quit()` logic to its own method is what would be cleaner.
