### ISSUE TITLE
[🚀 Feature]: (python) waiting until element is loaded

### ISSUE THREAD

**Issue by grethler** [SeleniumHQ/selenium#12041]
### Feature and motivation

Instead of waiting a specific number of seconds one can wait until it is loaded. 
This can shorten running times, because if an element loads in 0.6s but i say it should
wait 1s until it is loaded, i loose 0.4s. If this happens multiple times this is gonna add up.

### Usage example

```
import time
from selenium.common.exceptions import NoSuchElementException

class MyClassName:
    def check_element(self, element, timeout=5):
        """This function checks if an element is available within a timeout period.
        """
        start_time = time.time()
        while time.time() - start_time < timeout:
            try:
                browser.find_element(element[0], element[1])
                return True
            except NoSuchElementException:
                time.sleep(1)
        return False

```

**Comment by diemol** [comment]
Where is this code present? Not following what the feature request is.

**Comment by grethler** [comment]
@diemol it is an idea for a feature.

**Comment by diemol** [comment]
I see. However, due to the HTTP nature of the WebDriver protocol, polling needs to be done to see if the element is there or not. However, https://github.com/w3c/webdriver-bidi is on the works, and WebSockets will be used, which means that the browser will tell the automation script that the element has loaded, and it should save you 0.4s. 

A good overview can be seen here https://developer.chrome.com/blog/webdriver-bidi-2023/

I will close this as it is part of BiDi.
