### ISSUE TITLE
[🐛 Bug]: Scroll only works on main scrollbar

### ISSUE THREAD

**Issue by TheCarpetMerchant** [SeleniumHQ/selenium#12081]
### What happened?

The scrolling action does not work for sidebars (using send_keys(Keys.PAGE_DOWN))

### How can we reproduce the issue?

```python
from selenium import webdriver
from selenium.webdriver.common.by import *
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
import time

chrome_options = Options()
chrome_options.add_argument("--window-size=1800,1000")
driver = webdriver.Chrome(options=chrome_options)
driver.get('https://www.youtube.com')

time.sleep(5)

# Scrolls fine
scroll = driver.find_element(by=By.CSS_SELECTOR, value='body')
scroll.send_keys(Keys.PAGE_DOWN)

# Scrolls not fine
scroll = driver.find_element(by=By.CSS_SELECTOR, value='div#guide-inner-content')
try:
  scroll.send_keys(Keys.PAGE_DOWN)
except:
  print('error')

# Scrolls fine
driver.execute_script(
  """
  document.querySelector('div#guide-inner-content').scroll(100,800)
  """
)

time.sleep(5)
```

### Relevant log output

```shell
/
```

### Operating System

Windows 10

### Selenium version

Python 4.9.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 113

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver.exe does not have a version number

**Comment by TheCarpetMerchant** [comment]
Full quick and dirty workaround :
```python
  def scrollToBottom(self, selector: str):
    last_scroll = 0
    current_scroll = -1
    while(current_scroll != last_scroll):
      last_scroll = current_scroll
      self.driver.execute_script('document.querySelector(arguments[0]).scroll(0,100000);', selector)
      time.sleep(1)
      current_scroll = self.driver.execute_script('return document.querySelector(arguments[0]).scrollTop;', selector)
``

**Comment by titusfortner** [comment]
Native scrolling functionality was added to the Actions class in Selenium 4.2 and all of the latest browser versions support it. It is much more powerful than other options because you can explicitly set the origin point of the scroll. https://www.selenium.dev/documentation/webdriver/actions_api/wheel/

Selenium dutifully passes along the javascript and the keystrokes to the drivers, so if there are any discrepancies between actions and desired behaviors for Chrome, you'll need to raise the issue with Google.
