### ISSUE TITLE
[🐛 Bug]: Java: Chrome Browser: Selenium Manager: Unsuccessful command executed: Error sending request to URL

### ISSUE THREAD

**Issue by rsenthilr** [SeleniumHQ/selenium#12093]
### What happened?

Java
Selenium Dependency Version: 4.9.0

Selenium webdriver unable to launch google chrome, but the same code launches edge browser. Please refer the screenshot for the complete error message
![SeleniumMgr1](https://github.com/SeleniumHQ/selenium/assets/128029958/4ac77ac0-3c42-4f60-97ea-c1ed96a3e703)
![SeleniumMgr2](https://github.com/SeleniumHQ/selenium/assets/128029958/c933128d-3427-4e1f-a49a-c456ac8c4f8d)

### How can we reproduce the issue?

```shell
public class DemoTest() throws InterruptedException{
WebDriver driver = new ChromeDriver();

driver.get("https://www.google.com")

Thread.sleep(3000);

driver.quit();

}
```

### Relevant log output

```shell
Please refer the attached screenshot for log
```

### Operating System

Windows10

### Selenium version

Java 8

### What are the browser(s) and version(s) where you see this issue?

Chrome - 113.0.5672.63

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver, msedgedriver

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
This seems to be a timeout, the fix has not been released yet. So if you want to try the SNAPSHOT version, please try this [workaround](https://github.com/SeleniumHQ/selenium/issues/12053#issuecomment-1551033406) **after** using 4.10.0-SNAPSHOT (you need to add the [SNAPSHOT repository](https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/examples/java/pom.xml#L21-L29) to your POM).

**Comment by rsenthilr** [comment]
@diemol  - thanks for the sharing the information, but still we could see the same error. Please find the screenshot
![image](https://github.com/SeleniumHQ/selenium/assets/128029958/47fc55b9-c7a0-450a-8d2e-ae793ea0f785)

**Comment by diemol** [comment]
Did you add the timeout configuration shown in the comment I linked?

**Comment by rsenthilr** [comment]
@diemol  - yes have added the same, screenshot for reference
![image](https://github.com/SeleniumHQ/selenium/assets/128029958/ac2f9ee4-66bb-4f45-94c7-b70e8e5ceb62)

Selenium Manager after cache clear: working for Edge but not for chrome
![image](https://github.com/SeleniumHQ/selenium/assets/128029958/d11ee8e2-b499-4072-9fce-94fb3685d7e9)

**Comment by Pandzioch** [comment]
Same thing was catched by me on ChromeDriver without using Selenium Manager with usage of C# & TeamCity Agent.
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4470
Also log looks similar for  ChromeDriver 113.0.5672.63
 OpenQA.Selenium.WebDriverException : An unknown exception was encountered sending an HTTP request to the remote WebDriver server for URL http://localhost:23342/session/593ab3ce94c28796d9805af05f12c14a/element/610B32E029BA93F56ECB70DF486F70D6_element_64/text. The exception message was: An error occurred while sending the request.
09:37:42     ----> System.Net.Http.HttpRequestException : An error occurred while sending the request.
09:37:42     ----> System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
09:37:42     ----> System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.
09:37:42   TearDown : OpenQA.Selenium.WebDriverException : An unknown exception was encountered sending an HTTP request to the remote WebDriver server for URL http://localhost:23342/session/593ab3ce94c28796d9805af05f12c14a/screenshot. The exception message was: No connection could be made because the target machine actively refused it. (localhost:23342)
[09:37:42 ](https://ci-zjk.ebre.pl/buildConfiguration/Tests_SeleniumTests_EagleAutomation_EagleTrev/311325?buildTab=log&focusLine=861&logView=flowAware&linesState=861)    ----> System.Net.Http.HttpRequestException : No connection could be made because the target machine actively refused it. (localhost:23342)
[09:37:42 ](https://ci-zjk.ebre.pl/buildConfiguration/Tests_SeleniumTests_EagleAutomation_EagleTrev/311325?buildTab=log&focusLine=862&logView=flowAware&linesState=862)    ----> System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it.

**Comment by mdiwakar** [comment]
@rsenthilr ,  with the following configuration, the test that you gave works fine. please try, if you get the same error again, then check for firewall configuration for OS Error 10054

        <selenium.java>4.9.1</selenium.java>
        <selenium.jupiter>4.3.3</selenium.jupiter>
        <cucumber-java>5.6.0</cucumber-java>
        <webdrivermanager.version>5.3.2</webdrivermanager.version>

12:00:03.377 [main] DEBUG io.github.bonigarcia.wdm.Preferences - Preference chrome=113 (valid until 2023-06-01 11:51:33)
12:00:03.377 [main] DEBUG io.github.bonigarcia.wdm.Preferences - Preference chrome113=113.0.5672.63 (valid until 2023-06-01 11:51:33)
12:00:03.377 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 113.0.5672.63 (since Google Chrome 113 is installed in your machine)
12:00:03.377 [main] DEBUG io.github.bonigarcia.wdm.WebDriverManager - Driver chromedriver 113.0.5672.63 found in cache
12:00:03.377 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users.\\.m2\repository\webdriver\chromedriver\win32\113.0.5672.63\chromedriver.exe
Starting ChromeDriver 113.0.5672.63 (0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}) on port 48268
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
May 31, 2023 12:00:04 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Title of page is Google

Process finished with exit code 0

**Comment by titusfortner** [comment]
@mdiwakar to clarify, you are using webdriver manager, not the Selenium Manager that this issue is about.

**Comment by mdiwakar** [comment]
@titusfortner  selenium manager also working without any issues.

C:\git\Binaries>selenium-manager.exe --driver chromedriver --debug
DEBUG   Using shell command to find out chrome version
DEBUG   Running command: "set PFILES=%PROGRAMFILES: (x86)=%&& wmic datafile where name='!PFILES:\\=\\\\!\\\\Google\\\\Chrome\\\\Application\\\\chrome.exe' get Version /value"
DEBUG   Output: "\r\r\n\r\r\nVersion=113.0.5672.127\r\r\n\r\r\n\r\r\n\r"
DEBUG   The version of chrome is 113.0.5672.127
DEBUG   Detected browser: chrome 113
DEBUG   Required driver: chromedriver 113.0.5672.63
DEBUG   Running command: "chromedriver --version"
DEBUG   Output: ""
DEBUG   Driver URL: https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_win32.zip
DEBUG   File extracted to C:\Users\xxxxx\.cache\selenium\chromedriver\win32\113.0.5672.63\chromedriver.exe (12789248 bytes)
INFO    C:\Users\xxxxx\.cache\selenium\chromedriver\win32\113.0.5672.63\chromedriver.exe

C:\git\Binaries>selenium-manager.exe --version
selenium-manager 1.0.0-M3

C:\git\Binaries>

**Comment by titusfortner** [comment]
@rsenthilr is it a network issue? are you behind a proxy or firewall? Can you curl the Google api url, or visit it in the browser?

**Comment by rsenthilr** [comment]
@titusfortner - yes it is behind proxy, but still msedge is working fine and chrome it is not working. Pls find the screenshot of the same
![image](https://github.com/SeleniumHQ/selenium/assets/128029958/30bd5ec9-e0a5-4661-9763-69a39144751e)
![image](https://github.com/SeleniumHQ/selenium/assets/128029958/e9cbd63b-0097-4bd2-8b3e-7528d3bd4e0a)
![image](https://github.com/SeleniumHQ/selenium/assets/128029958/10e79a8b-a0b0-47b7-8403-ba709e9652c5)

**Comment by titusfortner** [comment]
Ok, so this isn't limited to Selenium manager per se if curl is also not working. Perhaps a header issue. @bonigarcia anything you can figure out right off?

**Comment by bonigarcia** [comment]
I'm not sure. If the browser works but selenium-manager/curl does not, maybe the headers sent by Chrome does the trick.

![image](https://github.com/SeleniumHQ/selenium/assets/5413013/c620dd91-35e4-4016-afcb-ad9b7b68dd00)

**Comment by titusfortner** [comment]
yeah, that's what I was thinking. Is there a header SM might need to add?

**Comment by bonigarcia** [comment]
> yeah, that's what I was thinking. Is there a header SM might need to add?

For the general use case, I would say it is not required. But for strange cases like this (i.e., behind a proxy that seems to do something strange with the TLS handshake), perhaps We can try to discover by tuning the curl command.

@rsenthilr Can you try the following command in your shell? It contains some of the headers that Chrome sends. It is a multiline cmd command. If works, you can try to remove some of the headers until we find the one that makes some difference:

```
curl ^
--header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7" ^
--header "Sec-Fetch-Dest: document" ^
--header "Sec-Fetch-Mode: navigate" ^
--header "Sec-Fetch-Site: none" ^
--header "Sec-Fetch-User: ?1" ^
--header "Upgrade-Insecure-Requests: 1" ^
--header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" ^
--header "X-Client-Data: CKO1yQEIibbJAQiktskBCKmdygEI2+7KAQiWocsBCLqUzQEIz5rNAQienM0BCIWgzQEIkabNAQjEqs0BCO2rzQEItrLNAQjqs80BCLa0zQEIxLXNAQiduc0BGNedzQE=" ^
https://chromedriver.storage.googleapis.com/LATEST_RELEASE_113
```

**Comment by rsenthilr** [comment]
@bonigarcia - I have tried the curl with headers and still getting the same issue. please find the screenshot below
![image](https://github.com/SeleniumHQ/selenium/assets/128029958/50ce450e-755c-419e-a336-beb045007a42)

**Comment by rsenthilr** [comment]
@bonigarcia - Finally curl got worked after  providing proxy, but confusion how it is working for msedge without proxy. 
Please find the screenshot for the same
![image](https://github.com/SeleniumHQ/selenium/assets/128029958/b4f0b142-33fb-4bad-9318-821bda6c1261)

**Comment by bonigarcia** [comment]
You can also specify your proxy is selenium-manager. I think the proxy support will be shipped in the next release of Selenium.

**Comment by titusfortner** [comment]
Yes, using a proxy changes everything. Support is in next release.
Usage will look like this:

```java
    ChromeOptions options = new ChromeOptions();
    Proxy proxy = new Proxy();
    proxy.setHttpProxy("http://127.0.0.1:9000");
    options.setProxy(proxy);

    WebDriver driver = new ChromeDriver(options);
```
