### ISSUE TITLE
Bazel Build tehnical issue

### ISSUE THREAD

**Issue by nvborisenko** [SeleniumHQ/selenium#12102]
### What happened?

Why not just `dotnet build`, or `dotnet pack`, or `dotnet test`. It is easy. Solution: keep preconditions for building as artifacts (couple of js files, cdp auto-generated classes). That's all what is required to make dev experience in .net absolutely comfortable.

Keeping generated pre-requisites under git allows to:
- not install huge number of software
- not waste time to build pre-requisites again and again
- increase speed of build process
- involve more contributors
- clean up repo and removing some strange binaries like `third_party/dotnet/**` (`nuget.exe` is there, hmmm)
- be independent of unnecessary build party who is show stopper in very simple cases: https://github.com/bazelbuild/rules_dotnet/issues/343

How I see new process: all bindings (most likely) require common prerequisites. CI process tracks original source, and generate artifacts once original source has been changed - and pushes to repo, which initiates testing stage for all dependent bindings.

Final remark for everybody here: you can remove `*.csproj` files, they are not a part of building process. Ah, CI uses `dotnet test` cli command (interesting why not bazel). Hm, and `selenium-manager.exe` (pre-requisite) is under git. Philosophy is not kept up.

Continuation of https://github.com/SeleniumHQ/selenium/issues/10465

### How can we reproduce the issue?

```shell
-
```

### Relevant log output

```shell
-
```

### Operating System

any

### Selenium version

any dotnet, selenium 4.0+

### What are the browser(s) and version(s) where you see this issue?

any

### What are the browser driver(s) and version(s) where you see this issue?

any

**Comment by nvborisenko** [comment]
This is how fast tests can be executed (parallelized).

![image](https://github.com/SeleniumHQ/selenium/assets/22616990/80627ac4-0e8e-472d-b255-76cb94440024)

But it is nothing given that build process takes ~20 minutes.

**Comment by titusfortner** [comment]
Thanks for opening this as an issue Until/unless we make a post or article about it, let's use this as a place to explain and document our reasoning.

**Comment by titusfortner** [comment]
I asked Nikolay to create this issue so we can have a single place to direct people or mark as duplicates suggestions to move away from Bazel.

My primary concern with using Bazel has been the higher-than-otherwise barrier to entry for encouraging developers to work on our project. That said, there are many advantages to having everything in one system, including addressing many inefficiencies. Personally, I was much more frustrated last year when we had significant deficits (especially in Windows and .NET) and no work was being done on improving it. Very fortunately, super smart people have done a lot of really great work to improve things (thank you!). Our CI build & test times are low and getting lower because of Bazel caching, it is easier to work on all bindings at once than it would be otherwise, and we've managed to automate more things multi-platform in one go.

So, while there are legitimate concerns with using Bazel, and while there are valid alternatives, the project as a whole has decided that the benefits of Bazel outweigh the downsides, especially as we make more progress on the initiatives already underway.

Simon wrote a great explainer here:
https://www.selenium.dev/blog/2023/building-selenium/
