### ISSUE TITLE
[🚀 Feature]: Can you provide a method to judge whether the page is loaded?

### ISSUE THREAD

**Issue by hchenxu** [SeleniumHQ/selenium#12113]
### Feature and motivation

Can you provide a method to judge whether the page is loaded or not.

### Usage example

 I need to cache the entire page after the page is fully loaded, so I need such a method。

**Comment by titusfortner** [comment]
From a theoretical perspective, providing this feature first requires solving the [Halting Problem](https://en.wikipedia.org/wiki/Halting_problem) — so any product that claims to do this is not.

From a more practical perspective, what we can easily do with current specification is wait for the Document Ready State to be "Complete" on navigation commands, but not on clicks that cause navigations — except Chrome does this, but technically it shouldn't. Even this doesn't help in many cases because once the JS is loaded it is still likely doing a bunch of stuff.

What you will be able to do eventually with the new [WebDriver BiDi spec](https://w3c.github.io/webdriver-bidi/), is to check for network activity and decide for yourself how long of a period of inactivity is likely to mean that the page has loaded. Regardless, we will not be providing this method directly, and once it is feasible we will make sure to publicize the functionality.
