### ISSUE TITLE
[🐛 Bug]: selenium v4.10.0 removes executable_path from Chrome object

### ISSUE THREAD

**Issue by jbiams77** [SeleniumHQ/selenium#12176]
### What happened?

moving from version 3.9.1 to 4.10.0 broke my integration tests since I used the parameter in Chrome object to specify executable_path:

```
chrome_options.binary_location = '/usr/bin/google-chrome'
chrome_driver = `/usr/bin/chromedriver`
driver = webdriver.Chrome(executable_path=chrome_driver, chrome_options=chrome_options)
```

This non-backwards compatible change should not have been a minor version bump but a major IMO. Request a patch to ensure executable_path remains backwards compatible with 3.9.1 features.

### How can we reproduce the issue?

```shell
Use executable_path paramter in webdriver.Chrome() initializer.
```

### Relevant log output

```shell
19:35:46   bdd/fixtures/chrome_driver.py:29: in fx_chrome_driver
19:35:46       driver = webdriver.Chrome(executable_path=chrome_driver, chrome_options=chrome_options)
19:35:46   E   TypeError: __init__() got an unexpected keyword argument 'executable_path'
```

### Operating System

Ubuntu 20.04

### Selenium version

4.10.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 

### What are the browser driver(s) and version(s) where you see this issue?

101.0.4951.41

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
This has been deprecated since the Selenium 4.0.0 release (~1.5 years ago), and was removed through [this PR](https://github.com/SeleniumHQ/selenium/pull/12030/), the way to fix it has been [documented](https://www.selenium.dev/documentation/webdriver/getting_started/upgrade_to_selenium_4/#python-1) for a while, and this was also announced on the release [blog post](https://www.selenium.dev/blog/2023/selenium-4-10-0-released/). If you need help, please join the community chat where we can collaborate (see links below).

**Comment by titusfortner** [comment]
Selenium does not practice semantic versioning because we choose to keep the versions consistent across all languages.

Our policy is to deprecate the behavior; throw warnings as necessary and wait three releases before removing it. In this case it has been deprecated since before the release of 4.0, so you have had plenty of time to update your code.

Further, you should not need to manage your own drivers. Selenium should do this for you now.
