### ISSUE TITLE
[🐛 Bug]: Why is there a timeout error

### ISSUE THREAD

**Issue by wantz1018** [SeleniumHQ/selenium#12198]
### What happened?

When I run code:
```python
from selenium.webdriver import Chrome
driver = Chrome()
driver.quit()
```
it raise error
```
ValueError: Timeout value connect was <object object at 0x000001D250768F00>, but it must be an int, float or None.
```

### How can we reproduce the issue?

```shell
from selenium.webdriver import Chrome, ChromeOptions
driver = Chrome()
driver.quit()
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "D:\work\ImageScan\main.py", line 2, in <module>
    driver = Chrome()
  File "D:\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "D:\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "D:\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 269, in __init__
    self.start_session(capabilities, browser_profile)
  File "D:\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 423, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Python\Python310\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 333, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\Python\Python310\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 355, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "D:\Python\Python310\lib\site-packages\urllib3\_request_methods.py", line 118, in request
    return self.request_encode_body(
  File "D:\Python\Python310\lib\site-packages\urllib3\_request_methods.py", line 217, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "D:\Python\Python310\lib\site-packages\urllib3\poolmanager.py", line 422, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "D:\Python\Python310\lib\site-packages\urllib3\poolmanager.py", line 303, in connection_from_host
    return self.connection_from_context(request_context)
  File "D:\Python\Python310\lib\site-packages\urllib3\poolmanager.py", line 328, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "D:\Python\Python310\lib\site-packages\urllib3\poolmanager.py", line 351, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
  File "D:\Python\Python310\lib\site-packages\urllib3\poolmanager.py", line 265, in _new_pool
    return pool_cls(host, port, **request_context)
  File "D:\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 196, in __init__
    timeout = Timeout.from_float(timeout)
  File "D:\Python\Python310\lib\site-packages\urllib3\util\timeout.py", line 190, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "D:\Python\Python310\lib\site-packages\urllib3\util\timeout.py", line 119, in __init__
    self._connect = self._validate_timeout(connect, "connect")
  File "D:\Python\Python310\lib\site-packages\urllib3\util\timeout.py", line 156, in _validate_timeout
    raise ValueError(
ValueError: Timeout value connect was <object object at 0x000001D250768F00>, but it must be an int, float or None.
```
```


### Operating System

Windows 11

### Selenium version

Python 4.1.3

### What are the browser(s) and version(s) where you see this issue?

Chrome 114.0.5735.110

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver  112.0.5615.49

### Are you using Selenium Grid?

_No response_

**Comment by diemol** [comment]
Please update to the latest release and report back please.

**Comment by wantz1018** [comment]
> Please update to the latest release and report back please.

I update the selenium version by pip and now it's useful.Thank you!

**Comment by jkrauss82** [comment]
We just did an update from v4.8.0 to v4.8.3 and now we are seeing timeouts for the clients which connect through the Java firefox webdriver. Chrome seems to work, but it is using Playwright.

Error message:

`Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.`

**We haven't changed anything aside from using selenium-server-4.8.3.jar instead of selenium-server-4.8.0.jar.**

### Operating System
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

### Selenium version
4.8.3
Java
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Debian-1deb11u1, mixed mode, sharing)

### What are the browser(s) and version(s) where you see this issue?
Mozilla Firefox 102.7.0esr

### What are the browser driver(s) and version(s) where you see this issue?
4.8.3

### Are you using Selenium Grid?
yes, through standalone mode

### Startup Command
java -Xmx2048m -XX:G1PeriodicGCInterval=60000 -jar selenium-server-4.8.3.jar standalone --port 4445 --grid-url https://selenium:4445 --override-max-sessions true --max-sessions 128 --session-request-timeout 30 --session-retry-interval 1 --session-timeout 300 -I firefox -I chrome --https-private-key selenium.key.pkcs8 --https-certificate selenium2.crt.pem

### Log from selenium process
11:51:01.069 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "*****","eventTime": 1686743461069398640,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "selenium:4445","http.method": "POST","http.request_content_length": "1869","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "selenium\u002f4.8.3 (java unix)"}}

This might be related:
https://stackoverflow.com/questions/75907541/selenium-project-stops-working-after-updating-to-4-8-3

**Comment by diemol** [comment]
Latest is 4.10.0

**Comment by jkrauss82** [comment]
Sure, we just wanted to avoid running into breaking changes!

You are saying it should work in 4.10.0?

**Comment by diemol** [comment]
I am not sure what your issue is. If you upgrade to 4.10.0 and have a reproducible issue, you should create one in this issue tracker.

**Comment by jkrauss82** [comment]
We have tried with 4.10.0 and 4.9.1, problem persists.

In case it matters: we use geckodriver v0.33.0 (latest).

Chrome sessions work, Firefox sessions do not get opened by the Selenium node/grid. Unfortunately, there is no error in the logs which would tell what is going wrong, aside from the 500 status code which probably means that the Firefox process has not been created.

The logs I have checked are stdout and stderr of the Java process which runs selenium, additionally syslog and journald. The --log parameter seems not to work, at least it does not create a file when specified.

I would be eager to look at the right place if someone could point me to it. Or, if you need more debug information please let me know what I should provide, thanks.

**Comment by titusfortner** [comment]
@jkrauss82 here is how you turn on logging for Selenium — https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/
Double check your Firefox version and location; sounds like it might not be finding where it is.

If you're still having an issue, please open a new ticket instead of replying to this one, thanks.
