### ISSUE TITLE
[🐛 Bug]: Performance issue in case of performance logs enabled in chrome

### ISSUE THREAD

**Issue by sparsh00** [SeleniumHQ/selenium#12225]
### What happened?

After the changes made in https://github.com/SeleniumHQ/selenium/pull/11973 jar spawning is not adding the `--log-path=` flag to Chrome in the normal flow. Need to enable the `readableTimestamp` or `appendLog` flag to get it working   https://github.com/SeleniumHQ/selenium/pull/11973/files#diff-405c68a6b743ea8f4b340b5ea0c92c802a24109b4c38818335f6ca39511e2bc8R385.
What is has caused is that the chromedriver logs are append to file while going through jar causing performance issues.

### How can we reproduce the issue?

```shell
Run session on Chrome while adding logging params and opening heavy websites like Pinterest
"goog:loggingPrefs": {
  "driver": "ALL",
  "browser": "SEVERE",
  "performance": "ALL",
  "server": "ALL"
}
```

### Relevant log output

```shell
No direct logging of chromedriver flags in selenium logs found by looking around after facing performance issue.
```

### Operating System

Windows 10

### Selenium version

4.9.1

### What are the browser(s) and version(s) where you see this issue?

Chrome latest

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver related to the chrome version

**Comment by titusfortner** [comment]
What is happening is that the output of the entire process is being sent to the file requested. Everything going to the console is put into the log file. 
Appending to File and Readable Time Stamp do not work with console output, so if either of those features are requested, we use the driver output instead of porting the console output to the file.

I only evaluated this with parameters being sent to start the driver, not parameters being sent to the driver to start the browser, which shouldn't be affected, but I'll take a look.

**Comment by titusfortner** [comment]
Sure enough, the `goog:loggingPrefs` value requires the driver to have logging turned on, and the current behavior doesn't allow that without using `--log-path` to driver.

### Selenium 4.9.0
* `--log-path=FILE` turns on logging, respects the log levels in loggingPrefs map, sends it to that file
* `--log-level=LEVEL` without log-path turns on logging, overrides the log levels in loggingPrefs map, sends it to the console

### Selenium 4.10.0
* `--log-path=FILE` turns on logging, does not respect anything in loggingPrefs map
* `--log-level=LEVEL` without log-path still has default logging set to dev/null and does not respect anything in loggingPrefs map

### Options:
1. Selenium updates code to not go to dev/null when log level is set but log file is not. This isn't really related to the problem specified, but is a place where intent is not being respected --> Yes

2. Selenium updates code to add a default log level when a log file is specified. Whatever level chosen would override what is set in loggingPrefs and would either be more or less than desired --> Probably Not?

3. Selenium restores previous `withLogFile()` behavior and adds support to sending the whole process to a log file with a second method of `withLogOutput()` that takes a File name --> Maybe?

4. User sets `withLogFile()` and `withLogLevel()` and accepts all logging the way it comes in --> Probably good enough for this use case?

5. User obtains logs the way they are theoretically intended to be accessed using: `LogEntries logs = driver.manage().logs().get("performance")`, but we actually removed support for this in grid (#10949), so that is somewhat inconsistent as well. Really this is a mismatch of if Selenium isn't going to support it remotely, it really should be set in the driver and not the options, which is frustrating --> A pain, but can also filter out things not desired as desired.

**Comment by diemol** [comment]
I think the issue is that one can not set a log path if you do not set either the readable timestamp or the append log options. Which is a breaking change, in [4.9.0](https://github.com/SeleniumHQ/selenium/blob/selenium-4.9.0/java/src/org/openqa/selenium/chrome/ChromeDriverService.java#L361-L367) the flow was slightly different, you could set the log path and then the readable timestamp was applied when set. 

I will make that change, to leave it as 4.9.0 and you can test it tomorrow when the [nightly build](https://www.selenium.dev/downloads/#nightly) is available.

**Comment by sparsh00** [comment]
@diemol  This fixes the issue but can see it's not released with selenium 4.10 https://github.com/SeleniumHQ/selenium/blob/selenium-4.10.0/java/src/org/openqa/selenium/chrome/ChromeDriverService.java#L381
can we expect it in next release

**Comment by diemol** [comment]
You can already try it https://www.selenium.dev/downloads/#nightly

**Comment by grandEL-dsouza** [comment]
Hey @titusfortner 

I'm trying to run a test but I'm unable to get the Performance logs enabled.

I'm writing my code in Java and this is my code snippet:


` logPrefs.enable(LogType.BROWSER, Level.ALL);
        logPrefs.enable(LogType.PERFORMANCE, Level.ALL);
       // options.setCapability("goog:loggingPrefs", logPrefs);
        LoggingPreferences logPrefs = new LoggingPreferences();
        logPrefs.enable( LogType.PERFORMANCE, Level.ALL );
        //options.setCapability(LogType.loggingPrefs, logPrefs);`

Please note that I have uncommented the lines and tried different combinations but they all yielded me the following error:

`Exception in thread "main" org.openqa.selenium.InvalidArgumentException: invalid argument: log type 'performance' not found`

I also tried to print the available logs by this line of code:

` System.out.println("Available log types ====>" + driver.manage().logs().getAvailableLogTypes());`

And its only giving me these in the output:

`INFO: Detected dialect: W3C
Available log types ====>[browser, driver, client]`

So it seems that performance logs are not available altogether. 

Please let me know if I'm missing out on something or doing something incorrectly. 

Thanks.

**Comment by dineshb-qa** [comment]
Hi @grandEL-dsouza

You are able to resolve the issue? or got any solution?

This issue is already closed so I will suggest to file new one if you don't get any response.

**Comment by titusfortner** [comment]
This is working for me:

```
        ChromeOptions options = new ChromeOptions();
        LoggingPreferences logPrefs = new LoggingPreferences();
        logPrefs.enable(LogType.PERFORMANCE, Level.ALL);
        options.setCapability(ChromeOptions.LOGGING_PREFS, logPrefs);

        driver = new ChromeDriver(options);
        driver.get("https://www.selenium.dev");
        driver.manage().logs().get(LogType.PERFORMANCE).forEach(System.out::println);
```

**Comment by dineshb-qa** [comment]
Thank you @titusfortner it worked for me.
