### ISSUE TITLE
[🐛 Bug]: Wrong Version Numbering for breaking changes

### ISSUE THREAD

**Issue by principat** [SeleniumHQ/selenium#12241]
### What happened?

I updated form Selenium Version 4.0.0 to 4.10. By the Version numbering there should be no problems because there are only minor changes like new features, deprecation-Warnings and bugfixes. There are no changes in the API.

But when upgrading from 4.0.0 to 4.10.0 there are some breaking changes at selenium.webdriver.Chrome. Some of the arguments for the constructor are removed.

removing external functions, classes... or changing their signature should be marked as breaking change and lead to an increase of the major-part of the version

### How can we reproduce the issue?

* in 4.0.0 use the following code to initialize the chrome-Driver
    
```python
    selenium.webdriver.Chrome('path to the chrome-driver', options=selenium.webdriver.ChromeOptions())
``` 
    
  * upgrade to 4.10.0 and you will get an error, that options are defined twice

### Relevant log output

```shell
none
```

### Operating System

Windows

### Selenium version

Python 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chorme any version

### What are the browser driver(s) and version(s) where you see this issue?

Chrome any version

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
We do not follow semver. For breaking changes we deprecate the code and wait at least two minor releases before removing it or making the change. For example, the code you are referencing has been deprecated since 4.0.0, and was removed in 4.10.0. Users had 1.5 years to change their code.

If you have more questions, I will leave some links below where you can join our chat.
