### ISSUE TITLE
Is it possible to set webdriver.firefox.logfile in the ruby driver for firefox?

### ISSUE THREAD

**Issue by retorquere** [SeleniumHQ/selenium#1226]
I need the stdout from firefox, I saw seom docs saying setting webdriver.firefox.logfile on the profile should do the job, but I can't find how to do so for the ruby driver.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
