### ISSUE TITLE
Internet Explorer javascript executor return wrong data

### ISSUE THREAD

**Issue by NG-np6** [SeleniumHQ/selenium#1235]
Hi, I work on a site with Ext.js.
I want get Dictionary in my site with JavaScriptExecutor.
Example : 
{
        $formLinksIdentifierLabel: ['Identifiant', 'Identifier', ''],
        $formLinksLinkTypeLabel: ['Type de lien', 'Link type', ''],
        $formLinksHrefLabel: ['Href', 'Href', ''],
};
It works on main page. 
But, when I change page (this page is dynamic page with Ext.Loader), 
it returns a invalid RemoteWebElement.
The script work in console.

I use Selenium 2.47 in C#.

Helpe Me, Please.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
