### ISSUE TITLE
[🐛 Bug]: Dotnet Breaking Change in 4.11.0

### ISSUE THREAD

**Issue by tidusjar** [SeleniumHQ/selenium#12473]
### What happened?

When using the following code to create a ChromeDriver, it throws the following exception in 4.11.0

### How can we reproduce the issue?

```csharp
var pathToDriver = GetDriverPath(typeof(ChromeDriver));
return new ChromeDriver(pathToDriver, options);
```

`pathToDriver` is the full path to the driver instance e.g. `C:\something\chrome\driver.exe`

This change is related to https://github.com/SeleniumHQ/selenium/pull/12344/

### Relevant log output

```shell
System.ComponentModel.Win32Exception : The FileName property should not be a directory unless UseShellExecute is set.
TearDown : BoDi.ObjectContainerException : Interface cannot be resolved: OpenQA.Selenium.IWebDriver
StackTrace:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at OpenQA.Selenium.DriverService.Start()
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options)
```

### Operating System

Linux

### Selenium version

4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 114.0.5735.90

### Are you using Selenium Grid?

N/A

**Comment by titusfortner** [comment]
Ok, this is a fun one. 
In Selenium 4.10, the driver constructor that takes a single string argument is supposed to be a *directory* not the full path. So, it needs to be `C:\something\chrome\` not `C:\something\chrome\driver.exe`. https://github.com/SeleniumHQ/selenium/blob/selenium-4.10.0/dotnet/src/webdriver/Chrome/ChromeDriver.cs#L103

If the latter was passed in, .NET would actually look for `C:\something\chrome\driver.exe\chromedriver.exe`, and if it didn't find it, it would ignore it and use what it could find on the system.

4.11 does not ignore it any longer, but respects what a user passes in (as it should).

But since I know people sometimes pass in the full path, I added code to fix it — https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/src/webdriver/Chrome/ChromeDriverService.cs#L72

But it looks like I was assuming that the driver would be named "chromedriver.exe".
Regardless I didn't test this well enough.

But the feature you thought was working before was not actually working the way you thought, which is why it was bad and needed to be changed..

**Comment by tidusjar** [comment]
Thanks for the explanation behind that. 

Another potential fix instead of just 'making it work', could be if it's a full path, throw an exception so the developer knows exactly what is wrong and how to fix it?

**Comment by titusfortner** [comment]
Yes, I went this route to make it more closely match all the other bindings. 

Looking through the code I don't see where we make use of it being two arguments in general since we just end up combining them when they actually get used. If I had more time/energy, I'd deprecate the constructor for setting 2 parameters and require the single string to always be full path because that is what people seem to most expect.

**Comment by timandella** [comment]
I think the original description for this issue was a bit misleading, as the example for "pathToDriver" is not accurate. In this instance, path to driver is "c:\<somefolders>\chromedriver" so the command being executed is this

`return new ChromeDriver("c:\<somefolders>\chromedriver", options);`

The chrome driver exe itself is still named "chromedriver.exe"

I think it is the fact that the containing folder is also named "chromedriver" that is causing issues, Looking at the fix at https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/src/webdriver/Chrome/ChromeDriverService.cs#L72, it looks like it is checking the folder path contains "chromedriver" and assuming it is the full exe path, and adjusting the folder path accordingly. (so the driver path becomes "c:\<somefolders>")

If we pass in the full exe path "c:\<somefolders>\chromedriver\chromedriver.exe" then it works as expected, but I would really expect it to work if just the folder path is passed in, even if the folder is named "chromedriver" too

**Comment by titusfortner** [comment]
Ah, yes, it's matching anything with the driver name in it.

To be honest the best fix for all of this is to delete the driver and let Selenium manage it for you now. But thanks for the clarification, that's definitely the wrong conditional.

**Comment by titusfortner** [comment]
No, that's not true...

If my driver is here: "/Users/titusfortner/chromedriver/chromedriver"
 
This works:
```csharp
ChromeDriverService.CreateDefaultService("/Users/titusfortner/chromedriver/chromedriver");
```
and this works:
```csharp
ChromeDriverService.CreateDefaultService("/Users/titusfortner/chromedriver/");
```
This does not work, because it is not getting parsed as a directory, but as a file:
```csharp
ChromeDriverService.CreateDefaultService("/Users/titusfortner/chromedriver");
```

I've [updated the conditional](c9d0e356ea2f841ee2a3268f6b70052d6cac4fd8) to just check if it is a file. If it's a file, Selenium will just use the directory, if it isn't a file, Selenium will use what was passed in.
