### ISSUE TITLE
[🚀 Feature]: Support for Chromium

### ISSUE THREAD

**Issue by bonigarcia** [SeleniumHQ/selenium#12511]
### Feature and motivation

Modify the existing logic of the Chrome manager (`./selenium-manager --browser chrome`) to check Chromium (e.g., checking `/usr/bin/chromium` etc.) when Chrome is unavailable.

### Usage example

```
./selenium-manager --browser chrome
```

... should return `/usr/bin/chromium` as `result.browser_path` if Chrome is not available but Chromium it is.

**Comment by titusfortner** [comment]
Yeah I think this should be a higher priority because it represents a breaking change from previous behavior. 

Ideally, ideally, selenium manager should look for the browser the exact same way that the driver does (in the same order). Not doing so means there are weird non-backwards compatible issues.

**Comment by bonigarcia** [comment]
I have just sent a PR about Edge management. This one (support for Chromium) will be next.
