### ISSUE TITLE
[🐛 Bug]: Selenium sometimes returns a blank page

### ISSUE THREAD

**Issue by h928725721** [SeleniumHQ/selenium#12544]
### What happened?

I try to open an URL through Selenium, after Google Chrome opened and it showed a blank page.

But when I copied this URL to a new TAB and opened it, it could be displayed normally.

### How can we reproduce the issue?

```shell
This scene is sporadic，most of the time it doesn't happened.
```

### Relevant log output

```shell
here is my code:


server_path = '../browsermob-proxy-2.1.4/bin/browsermob-proxy.bat'
server_opetion = {'prot':8080,'use-littleproxy':False}
server = Server(path=server_path,options=server_options)
server.start()
proxy = server.create_proxy()
options = webdriver.ChromeOptions()
options.add_argument('--ignore-certificate-errors')
options.add_argument('--proxy-server={0}.format(proxy.proxy))
options.add_experimental_option('excludeSwitches',['enable-automation'])
options.add_experimental_option('excludeSwitches',['enable-logging'])

try:
    driver = webdriver.Chrome(executable_path='/chrome_driver/chromedriver.exe',options=options)
except Exception as e:
    latest_driver = ChromeDriverManager().install()
    driver = webdriver.Chrome(latest_driver,options = options)

driver.maximize_window()
wait = WebDriverWait(driver,10)
proxy.new_bar('google',options={'captureHeaders':True,'captureContent':True})
driver.get('url')
```

### Operating System

windows 10

### Selenium version

4.9.0

### What are the browser(s) and version(s) where you see this issue?

115.0.5790.171

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriverManager().install()

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
Does it happen when you use Selenium without browser mob proxy?

**Comment by SinghSuraj-04092002** [comment]
It seems like you're facing an issue where sometimes a URL opened through Selenium using ChromeDriver shows a blank page, even though the same URL opens normally when manually opened in a new tab. This sporadic behavior can be challenging to debug. Here are a few steps you can consider to troubleshoot the problem:

1. Check Network Activity: Use the BrowserMob Proxy to capture network activity for both scenarios (Selenium and manual). Compare the network requests and responses to see if there's any difference.
2. Logging and Debugging: Introduce logging statements at various points in your script to better understand the flow of execution. This could help identify any inconsistencies.
3. Update Chrome and Drivers: Ensure you're using the latest version of Chrome, ChromeDriver, and Selenium. Sometimes compatibility issues can lead to unexpected behavior.
4. Try Different WebDriver Methods: Instead of using get() method, you could try navigate.to() to see if there's any difference in behavior.
5. Check JavaScript Errors: Use the WebDriver to execute JavaScript code on the page to check for any JavaScript errors that might be causing the issue.
6. Headless Mode: Try running the browser in headless mode to see if the issue is specific to the browser window.

**Comment by h928725721** [comment]
@diemol I haven't tried it because the problem occurs only in rare cases

**Comment by titusfortner** [comment]
This sounds like a network/proxy issue, unrelated to this code base. Regardless, if we can't reproduce it, we can't investigate it as a potential bug.

**Comment by h928725721** [comment]
@titusfortner Alright ,thank you very much
