### ISSUE TITLE
[🚀 Feature]: Fill the gap between WebDriverListener and EventFiringWebDriver

### ISSUE THREAD

**Issue by harmin-parra** [SeleniumHQ/selenium#12613]
### Feature and motivation

Hi,

This ticket is rather a question that, hopefully, could lead to an improvement.

A decision was made to deprecate `EventFiringWebDriver` and replace it by `WebDriverListener`

I notice, with regret, that `WebDriverListener` lacks the `findElement` and `findElements` that were present in `EventFiringWebDriver` 

These 2 methods would allow the possibility to wrap or decorate `WebElements`.

I would like to understand what was the motivation or the reason to get rid of `findElement` and `findElements` methods in  `WebDriverListener`

It seems to me, this choice limits the possibilities of what we can do with wrappers and listener, compared of what we could do before with `EventFiringWebDriver`

### Usage example

The WebElement wrapper:

```
public class WebElementWrapper implements WebElement  {

    // Add attributes here if you want to store metadata associated to WebElements

    public WebElementWrapper(WebElement elem) {
        super()
    }

    // Add getters and setter to manage your metadata
}
```

The WebDriver listener using the WebElement wrapper (using `findElement` method missing in current listener implementation):

```
public class DriverListener implements WebDriverListener {

    public WebElement findElement(​WebDriver driver, By locator, WebElement element) {
        wrappedElem = new WebElementWrapper(element);
        // Use setters to initialize the WebElement metadata
        return wrappedElem;
    }

}
```

**Comment by diemol** [comment]
@shs96c do you know?

**Comment by dev-velo** [comment]
so you can still accomplish what you want just not through the listener, you need to go through the decorator

currently making some examples and comments for WebDriverListener and EventFiringDecorator and went down a deep rabbit hole of Decorators and Default Decorators since theyre all related so I [started making examples](https://github.com/RevealOscar/SeleniumExamplesJava/blob/main/src/main/java/examples/selenium/webdriver/decorator/webelement/WeebDriverDecorator.java). 
From my **basic** understanding , if you would like to change the underlying implementation call from the web element context then you have to override the createDecorated method for the WebElement instance of WebDriverDecorator. Then you can anonymous class and override the call method and provide your wrapper implementation. One note about this though is that this will only work for elements using find element. I provide the driver implementation at the end.
``` 
driver.findelement() // does not use wrapper
element.findelement() // uses wrapper
```


WebElement
```
public class WebElementWrapper implements WebElement {
    @Override
    public WebElement findElement(final By by)
// provide implementation here
```
```
public class WebElementDecorator extends WebDriverDecorator<WebDriver> {
    @Override
    public Decorated<WebElement> createDecorated(WebElement original) {
        return new DefaultDecorated<>(original, this) {

            @Override
            public Object call(Method method, Object[] args) throws Throwable {
                String methodName = method.getName();
                if ("findElement".equals(methodName)) {
                    logger.info("Actual Call in decorator");
                    WebElementWrapper element = new WebElementWrapper(getOriginal());
                    return element.findElement((By) args[0]);
                } else {
                    return super.call(method, args);
                }
            }
```
You can also do this for the webdriver context. 

```
driver.findelement() // uses wrapper
element.findelement() // does not use wrapper
```
WebDriver 
```
public class WebDriverWrapper implements WebDriver {
    @Override
    public WebElement findElement(final By by)
```
```
public class WeebDriverDecorator extends WebDriverDecorator<WebDriver>{
    @Override
    public Decorated<WebDriver> createDecorated(WebDriver driver) {
        return new DefaultDecorated<>(driver, this) {
            @Override
            public Object call(Method method, Object[] args) throws Throwable {
                // same as webelement implementation
            }
        };
```

Then to actually invoke the calls
```
final var decoratedDriver = new WebElementDecorator().decorate(driver);
final var searchBox = decoratedDriver.findElement(foo);
searchBox.findElement(foo);
```
Not sure if this is the approach to use for decorators but it was in the class docs. Feel free to correct me

**Comment by titusfortner** [comment]
`WebDriverListener` interface is just for before and after hooks for all the methods listed.

To change the behavior of the called method requires extending the `WebDriverDecorator` and overriding the `call()` method.

My examples are here — https://github.com/titusfortner/selenium-deep-dive/blob/seconf2023_final/src/test/java/com/titusfortner/deep_dive/decorators/DecoratorTest.java

@RevealOscar thank you for your help getting things documented for us. These aren't trivial things to explain, and I never even learned how the old way worked. 😄
