### ISSUE TITLE
[🚀 Feature]: (c#) Add support for Async operations

### ISSUE THREAD

**Issue by miroljub1995** [SeleniumHQ/selenium#12648]
### Feature and motivation

Since WebDriver is using HTTP calls under the hood, it's not a good practice to make HTTP requests synchronously. It would be good to add support for Async operations.

### Usage example

```cs
WebDriver driver = ...;

await driver.ExecuteAsyncScriptAsync("arguments[0](... some long running promise like axios.get(...))");
```

**Comment by titusfortner** [comment]
These changes are being discussed for selenium 5.
The change would require a lot of work and would not be backwards compatible, but we're investigating options.

**Comment by miroljub1995** [comment]
Why it wouldn't be backwards compatible?

**Comment by titusfortner** [comment]
> it's not a good practice to make HTTP requests synchronously

For most of the code, the calls *have to be synchronous. Either we use a synchronous pattern or we use a promise/await of some sort so that we can parse the response before continuing in the code execution. Managing the .NET code with everything requiring an await, and naming all of the methods async is not backwards compatible.
