### ISSUE TITLE
[🐛 Bug]: Building with Bazel failed during fetching of repository @rules_ruby_dist (hangs)

### ISSUE THREAD

**Issue by MatzFan** [SeleniumHQ/selenium#12757]
### What happened?

I'm attempting to build Selenium WebDriver locally so I can submit a PR on the Ruby bindings.

I've cloned the repo, installed the dependencies and am following the build instructions for Ruby here: https://github.com/SeleniumHQ/selenium#ruby

When I run `bazel build //rb:selenium-devtools` the process hangs trying to download the @rules_ruby_dist repo.

### How can we reproduce the issue?

```shell
Add the build dependencies and run `bazel build //rb:selenium-devtools`
```

### Relevant log output

```shell
me@0:~/dev/selenium$ bazel build //rb:selenium-devtools
Starting local Bazel server and connecting to it...
Analyzing: target //rb:selenium-devtools (114 packages loaded, 365 targets configured)
    Fetching repository @rules_ruby_dist; Installing Ruby 3.0.6 300s
```

### Operating System

Ubuntu 23.04

### Selenium version

Ruby 4.12.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 102.15.1esr

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.33.0

### Are you using Selenium Grid?

n/a

**Comment by titusfortner** [comment]
It's not actually hanging. It's compiling Ruby. 

That's right....

It needs to compile the whole thing from scratch because Bazel doesn't know about the local system libraries that Ruby needs. It's a pain and we'd love to find a way around this (precompiled Ruby bindings?), but for now. it's compiling Ruby. That can take a long time. Once it is in cache it's fine, but if the cache is cleared or an update is needed... it'll happen again.

Looking forward to seeing the PR, and come find us on Slack if you want to discuss - https://www.selenium.dev/support/#ChatRoom
