### ISSUE TITLE
[🐛 Bug]: WebSocket connection for vnc session is not using the --sub-path argument

### ISSUE THREAD

**Issue by atos-cosmin-gavagiuc** [SeleniumHQ/selenium#12791]
### What happened?

I'm trying to make multiple Selenium hubs accessible through a single Fully Qualified Domain Name (FQDN) using sub-paths. However, I'm encountering an issue where the VNC sessions fail to load in the browser.

I've identified that the WebSocket connection for the VNC sessions doesn't consider the "--sub-path" argument; instead, it only uses the FQDN.

![image](https://github.com/SeleniumHQ/selenium/assets/75359737/4841b723-3731-457e-ae8f-7718907216b2)

### How can we reproduce the issue?

```shell
expose the selenium hubs using an ingress controller with multiple paths.
```

### Relevant log output

```shell
Failed to load resource: net::ERR_FAILED
websock.js:231 WebSocket connection to 'wss://selenium.xxxx.net/session/6e7cc43f3ad98019f3a41bccbc6ff8a1/se/vnc' failed: value @ websock.js:231 rfb.js:686 WebSocket on-error event value @ rfb.js:686
rfb.js:941 Failed when connecting: Connection closed (code: 1006)
```

### Operating System

Docker image running in kubernetes.

### Selenium version

4.12.1

### What are the browser(s) and version(s) where you see this issue?

chrome 116.0

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 116.0

### Are you using Selenium Grid?

4.12.1

**Comment by zhangjunqiang** [comment]
I met the same problem.

**Comment by zhangjunqiang** [comment]
can any body fix this?

**Comment by dreadnaught07** [comment]
Am still experiencing this issue for selenium -hub version 4.16

**Comment by VietND96** [comment]
Hi @dreadnaught07, in the PR #13219 I put a little information for the background of how the URL is generated and how it to be tested.
In few points of view, it could be a workaround rather than a fix, since it required extra configs from user. Waiting for a better fix would come.
- If you are starting the grid via CLI, it is required to set these options for both Hub and Node
  - Hub: `java -jar selenium-server.jar hub [...] --sub-path /production`
  - Node: `java -jar selenium-server.jar node [...] --grid-url http://grid.example.com/production`
- If you are starting via docker images is built in [SeleniumHQ/docker-selenium](https://github.com/SeleniumHQ/docker-selenium), need to set ENV vars
  - Hub: `docker run [...] -e  SE_SUB_PATH=/production [...] selenium/hub:latest`
  - Node: `docker run [...] -e  SE_GRID_URL=http://grid.example.com/production [...] selenium/node-chrome:latest`
 
Here is a test in my local with above configs
![image](https://github.com/SeleniumHQ/selenium/assets/23253546/bbf15fb4-5dfe-4e45-b930-f6d8d67df481)

I am using Helm chart to bring up the Grid in K8s (started by Minikube) - chart version `0.26.1` contains an update https://github.com/SeleniumHQ/docker-selenium/pull/2053 for above config

Updated: If you already set the right config as mentioned above but NoVNC is still blank, probably it could be due to SeleniumHQ/docker-selenium#2045. Try to use a newer docker image tag, at least [4.16.1-20231212](https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.16.1-20231212)

**Comment by diemol** [comment]
I believe this is already working.
