### ISSUE TITLE
py: phantomjs service needs to really kill the spawned process

### ISSUE THREAD

**Issue by drennalls** [SeleniumHQ/selenium#1281]
I'm using selenium on Python2 with the PhantomJS driver. I noticed phantomjs processes accumulating after running my selenium script, despite having a `driver.quit()` call. Googling led me to this fix https://code.google.com/p/selenium/source/detail?r=885b62bbb7ee in the old codebase where a SIGTERM was added to the selenium.webdriver.phantomjs.Service.stop method. However that fix is not in the GitHub codebase it seems. Was that missed in the migration to GitHub ?

**Comment by lukeis** [comment]
it's was moved appropriately.
https://github.com/SeleniumHQ/selenium/commits/master/py/selenium/webdriver/phantomjs/service.py

https://github.com/SeleniumHQ/selenium/commit/885b62bbb7ee8661559148d267c1d9b5de4fdedb

The problem is this was not cross OS friendly... but it seems all attempts to do this in a cross platform way haven't been great and we should start checking which platform we're on and kill it appropriately.

**Comment by drennalls** [comment]
Ah ok, you're right, I missed that. I see now that the SIGTERM was changed back to a call to kill() with https://github.com/SeleniumHQ/selenium/commit/dbac7447d803a6efd33a031df841fa5f51e70ce5

**Comment by barancev** [comment]
Duplicate of #767
