### ISSUE TITLE
[🚀 Feature]: use one `java.net.http.HttpClient` in JdkHttpClient

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#12814]
### Feature and motivation

There were complains about the slow cleanup of the threads created by the JdkHttpClient. To fix this we registered a custom executor and shut it down, what caused other issues when there are still pending responses.

I would suggest to still call `HttpClientFactory.createDefaut` and return new JdkHttpClient instances, but they should all use the same `java.net.http.HttpClient` and not close it after use, only drop the reference.
Further calls to a closed JdkHttpClient could raise a speaking Exception rather than just using the dead HttpClient and waiting for the timeout that will be raised in this case.

### Usage example

Less threads are created, instances are faster ready to perform requests. Allready closed instances instantly fail with a speaking exception.

There might be side effects as this change will allow connection reuse between sessions of one java process to the same selenium server. I think this should not make any problems, but it might be possible.

**Comment by piotrbo** [comment]
Info for those who "complains about the slow cleanup of the threads created by the JdkHttpClient".
Try **run it with JDK 21**. It solved the issue in my case. I have a custom mulithread test framework build on Selenium 4.15 and compiled to Java 11. Running on Java 21.0.1 (backward compatibility) extensive SOAK tests (over 48 hours) on Ubuntu 20  AWS r5.2xlarge instance, showed garbage collector works perfectly. Total application threads oscillates up to ~2K (http threads 50-700). On JDK 11 or 17 it throws OutOfMemory in a few hours.

P.S. the issue is related to JDK bug https://bugs.openjdk.org/browse/JDK-8308364
so you may also try implement in Selenium a workaround descibed there.
