### ISSUE TITLE
[🐛 Bug]: c# CDP RequestPaused event issued only twice

### ISSUE THREAD

**Issue by PYasonau** [SeleniumHQ/selenium#12813]
### What happened?

I am using Chrome v 116
c# dotnet core 6.0
Selenium support lib: 4.12.4

Want to modify responses for different requests while testing

I want to have one method/one rule for each type of requests i want to mock

But i can't add more than two handlers for ResponsePaused/RequestsPaused events, beacuse the third one always would be ignored. 
You can find steps to rerpoduce below

### How can we reproduce the issue?

```shell
1. Create chromedriver session
2. Get Devtool Session and get a fetch as var fetch = (V116Network)session.Domains.Network; 
3. Enable it: fetch.EnableFetchForAllPatterns();
4. Create 3 methods like
        public void CollectNetworkRequests()
        {
            fetch.RequestPaused += (sender, e) =>
            {
               Console.WriteLine($"Log 1(here use 1-2-3 for better loggin): {e.RequestId}");
               return fetch.ContinueRequestWithoutModification(e.RequestData);
            };
            fetch.ResponsePaused += (sender, e) =>
            {
                return fetch.ContinueResponseWithoutModification(e.ResponseData);
            };
        }
5. Call these methods
6. Navigate to any website:  Driver.Navigate().GoToUrl("https://google.com");

Expected:
Each method would print to Console(and accordingly - could work with requests/responses)

Actual result:
Only first two methods would print to console(and accordingly - could work with requests/responses)
```

### Relevant log output

```shell
-
```

### Operating System

Windows 10

### Selenium version

c# dotnet,  selenium.support lib: 4.12.4

### What are the browser(s) and version(s) where you see this issue?

Chrome 116

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 116.0.5845.96 

### Are you using Selenium Grid?

Selenium server standalone 4.12.1

**Comment by nvborisenko** [comment]
@PYasonau I think your issue is in logic. You invoke `fetch.ContinueRequestWithoutModification` twice when naturally it should be continued only once. So you should improve your logic and make sure that you continue a request only one time.

Internally, selenium invokes your event handlers one by one, as soon as one fails it fails the whole invocation chain. This is why you see that the 3rd handler is not invoked. I don't remember, hopefully this behavior is already fixed in trunk, so selenium gives a chance to all handlers to be invoked.

**Comment by diemol** [comment]
Closing as we did not get more comments from the OP.
