### ISSUE TITLE
[🐛 Bug]: SSLHandshakeException for JDK Http Client

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#12869]
### What happened?

I'm not sure if this is an issue with how the test is written or a limitation of the http client. @pujagani I'm assuming if it's a test issue it's an easy-ish fix. If it's client related, can you please update this with the correct details? Thanks.

> javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.

### How can we reproduce the issue?

Run this test with jdk-http-client set as the default HTTP client

https://github.com/SeleniumHQ/selenium/blob/selenium-4.13.0/java/test/org/openqa/selenium/grid/router/ProxyWebsocketTest.java#L142

**Comment by pujagani** [comment]
Sure! This is on my todo. I will update things as I triage further.

**Comment by pujagani** [comment]
> I'm not sure if this is an issue with how the test is written or a limitation of the http client

I think it is both. 
The failing test has a HttpClient that wants to make a secure connection to a server that uses self-signed certificates. For testing purposes, the HttpClient needs to bypass SSL Certificate Verification by passing in a mock trust manager and creating an SSL context instance which needs to be passed to the HttpClient instance. 

This was not a concern while using AsyncHttpClient because of the change made in https://github.com/SeleniumHQ/selenium/blame/c64ed7d067f8314b2d3fbe3600dcc1ed47b866a4/java/src/org/openqa/selenium/remote/http/netty/NettyClient.java#L77, since we used a single instance of AsyncHttpClient throughout.

Currently, we do not have a provision to provide SSL-related information while building the client. I think we will need to add this in ClientConfig. ClientConfig can accept SSL-related information and JDK HttpClient can use it to create the SSL context instance while building the client.  

Once it is landed in the ClientConfig, the test can be updated accordingly.  The test will help verify the changes.

I am working on making those changes.
