### ISSUE TITLE
[🐛 Bug]: Selenium Manager force-browser-download only used for edge

### ISSUE THREAD

**Issue by elliottj** [SeleniumHQ/selenium#12938]
### What happened?

Selenium-manager 0.4.14 force-browser-download flag only used for edge.

Firefox reuses what is in the cache even with flag (chrome does similar):
```
C:\AFT>selenium-manager.exe --browser firefox --browser-version stable --debug --cache-path C:\AFT\sm --force-browser-download
DEBUG   geckodriver not found in PATH
DEBUG   Required browser: firefox 118.0.2
DEBUG   firefox 118.0.2 already exists
DEBUG   firefox 118.0.2 is available at C:\AFT\sm\firefox\win64\118.0.2\firefox.exe
DEBUG   Required driver: geckodriver 0.33.0
DEBUG   geckodriver 0.33.0 already in the cache
INFO    Driver path: C:\AFT\sm\geckodriver\win64\0.33.0\geckodriver.exe
INFO    Browser path: C:\AFT\sm\firefox\win64\118.0.2\firefox.exe
```

But edge honours flag:
```
C:\AFT>selenium-manager.exe --browser edge --browser-version stable --debug --cache-path C:\AFT\sm
DEBUG   msedgedriver not found in PATH
DEBUG   edge detected at C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
DEBUG   Running command: wmic datafile where name='C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe' get Version /value
DEBUG   Output: "\r\r\n\r\r\nVersion=117.0.2045.60\r\r\n\r\r\n\r\r\n\r"
DEBUG   Detected browser: edge 117.0.2045.60
DEBUG   Required driver: msedgedriver 117.0.2045.60
DEBUG   msedgedriver 117.0.2045.60 already in the cache
INFO    Driver path: C:\AFT\sm\msedgedriver\win64\117.0.2045.60\msedgedriver.exe
INFO    Browser path: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe

C:\AFT>selenium-manager.exe --browser edge --browser-version stable --debug --force-browser-download --cache-path C:\AFT\sm
DEBUG   msedgedriver not found in PATH
DEBUG   Required browser: edge 117.0.2045.60
DEBUG   Checking edge releases on https://edgeupdates.microsoft.com/api/products
DEBUG   Downloading edge 117.0.2045.60 from https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/04953c72-9e0d-420a-950c-15e0e659a225/MicrosoftEdgeEnterpriseX64.msi
DEBUG   Installing MicrosoftEdgeEnterpriseX64.msi
DEBUG   edge 117.0.2045.60 is available at C:\Program Files (x86)\Microsoft\Edge\Application\117.0.2045.60\msedge.exe
DEBUG   Required driver: msedgedriver 117.0.2045.60
DEBUG   msedgedriver 117.0.2045.60 already in the cache
INFO    Driver path: C:\AFT\sm\msedgedriver\win64\117.0.2045.60\msedgedriver.exe
INFO    Browser path: C:\Program Files (x86)\Microsoft\Edge\Application\117.0.2045.60\msedge.exe
```

Possibly a documentation issue (only applicable to Edge) or it's not working as intended.

### How can we reproduce the issue?

```shell
See above
```

### Relevant log output

```shell
See above
```

### Operating System

Windows 10

### Selenium version

Selenium-manager 0.4.14

### What are the browser(s) and version(s) where you see this issue?

Chrome, Firefox

### What are the browser driver(s) and version(s) where you see this issue?

n/a

### Are you using Selenium Grid?

n/a

**Comment by GandharviWalavekar** [comment]
Here are some steps you can take to potentially address this issue:

Browser Profile Settings:
For Firefox, create a custom Firefox profile for Selenium and set the browser preferences to disable caching. This can be done with the browser.cache.disk.enable and browser.cache.memory.enable preferences set to false.
For Chrome, create a custom Chrome profile for Selenium and set Chrome options to disable caching. This can be done using the --disk-cache-size=1 option, which effectively disables caching.

Browser Specific Configurations:
You may need to specify different configuration settings for each browser you're using (Edge, Firefox, and Chrome). 

Headers Manipulation:
Sometimes, you can send custom HTTP headers to the server to request fresh downloads instead of cached content. This can be done using the browser mob-proxy or selenium-wire libraries.

Clear Browser Cache:
Before initiating a file download, try clearing the browser's cache. This can be done using browser-specific commands. For example, in Chrome, you can use driver.execute_script("window.open('chrome://settings/clearBrowserData');").

Use Explicit Waits:
Implement explicit waits after clicking the download link to make sure the download is completed before interacting with the file. You can wait for the file to appear in the expected download directory.

Rename Downloaded Files:
After the download is complete, you can rename the downloaded file to ensure it's not cached. This can be done by moving the file to a different location or renaming it before using it in your automation.

**Comment by diemol** [comment]
@bonigarcia do you know?

**Comment by bonigarcia** [comment]
Unfortunately, Edge's automatic management in Windows by Selenium Manager is different than other browsers (Chrome, Firefox). The reason is that the Edge installer for Windows is distributed as a Microsoft Installer (MSI) file, designed to be executed with administrator rights. We tried to extract the Edge binaries from that MSI file. Still, it seems not possible (see [Stack Overflow post that summarized the problem](https://stackoverflow.com/questions/77132922/extract-parse-resources-from-portable-executable-pe-file)). All in all, the only solution we found is to install Edge in Windows using the MSI installer, and so, administrator grants are required.

This way, when Edge is attempted to be installed with Selenium Manager in Windows with a non-administrator session, a warning message will be displayed as follows:

```
selenium-manager --debug --browser edge --browser-version beta
DEBUG   msedgedriver not found in PATH
DEBUG   edge not found in PATH
DEBUG   edge beta not found in the system
WARN    There was an error managing edge (edge can only be installed in Windows with administrator permissions); using driver found in the cache
INFO    Driver path: C:\Users\boni\.cache\selenium\msedgedriver\win64\118.0.2088.17\msedgedriver.exe
```

But when Selenium Manager is executed with administrator grants in Windows, it will be able to automatically discover, download, and install Edge (stable, beta, dev, canary, and older versions):

```
selenium-manager --debug --browser edge --browser-version beta
DEBUG   msedgedriver not found in PATH
DEBUG   edge not found in PATH
DEBUG   edge beta not found in the system
DEBUG   Checking edge releases on https://edgeupdates.microsoft.com/api/products
DEBUG   Required browser: edge 118.0.2088.17
DEBUG   Downloading edge 118.0.2088.17 from https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/7adec542-f34c-4dea-8e2a-f8c6fab4d2f3/MicrosoftEdgeBetaEnterpriseX64.msi
DEBUG   Installing MicrosoftEdgeBetaEnterpriseX64.msi
DEBUG   edge 118.0.2088.17 is available at C:\Program Files (x86)\Microsoft\Edge Beta\Application\msedge.exe
DEBUG   Required driver: msedgedriver 118.0.2088.17
DEBUG   msedgedriver 118.0.2088.17 already in the cache
INFO    Driver path: C:\Users\boni\.cache\selenium\msedgedriver\win64\118.0.2088.17\msedgedriver.exe
INFO    Browser path: C:\Program Files (x86)\Microsoft\Edge Beta\Application\msedge.exe
```
@elliottj So, this is not a bug. It is how Edge can be installed in Windows by Selenium Manager. As a result, Edge is installed in `C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe` and not in the cache, like Firefox and Chrome.

**Comment by elliottj** [comment]
Understood and I had suspected that was the reason. Isn't this just a documentation issue then - to clarify how the force-browser-download flag actually works?

**Comment by bonigarcia** [comment]
Indeed, the Selenium Manager doc page needs to be updated to explain the difference between the automatic management in Edge in Windows and the rest of the browsers (even Edge in Linux and macOS).

**Comment by MarcelWilson** [comment]
> So, this is not a bug. It is how Edge can be installed in Windows by Selenium Manager. As a result, Edge is installed in C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe and not in the cache, like Firefox and Chrome.

@bonigarcia would this be similar for macOS as well? 
I'm noticing that `selenium-manager --browser edge --force-browser-download`  took much longer than expected after it was already downloaded to `.cache`.   And yet the returned browser path was indeed `.cache`.

```
Selenium Manager binary found at: /Users/me/.pyenv/versions/setup_selenium/lib/python3.11/site-packages/selenium/webdriver/common/macos/selenium-manager
Executing process: /Users/me/.pyenv/versions/setup_selenium/lib/python3.11/site-packages/selenium/webdriver/common/macos/selenium-manager --browser edge --force-browser-download --debug --output json
msedgedriver not found in PATH
Required browser: edge 118.0.2088.46
Checking edge releases on https://edgeupdates.microsoft.com/api/products
Downloading edge 118.0.2088.46 from https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/abda5cb7-da3d-4486-b0a7-e770b10f0758/MicrosoftEdge-118.0.2088.46.pkg
edge 118.0.2088.46 is available at /Users/me/.cache/selenium/edge/mac-arm64/118.0.2088.46/Microsoft Edge.app/Contents/MacOS/Microsoft Edge
Required driver: msedgedriver 118.0.2088.46
msedgedriver 118.0.2088.46 already in the cache
Driver path: /Users/me/.cache/selenium/msedgedriver/mac-arm64/118.0.2088.46/msedgedriver
Browser path: /Users/me/.cache/selenium/edge/mac-arm64/118.0.2088.46/Microsoft Edge.app/Contents/MacOS/Microsoft Edge
```
Or is this a separate bug for edge not using the cache on mac?

**Comment by bonigarcia** [comment]
> would this be similar for macOS as well?

No, Edge for macOS works in the same way that Firefox and Chrome. In other words, the Edge downloads by Selenium Manager are stored in the cache folder (`/Users/me/.cache/selenium/edge/mac-arm64/118.0.2088.46/Microsoft Edge.app/Contents/MacOS/Microsoft Edge`  in your case).

**Comment by MarcelWilson** [comment]
> No, Edge for macOS works in the same way that Firefox and Chrome.

Ok, then I might be seeing a separate bug.  Everytime I run edge on mac, it re-downloads the browser to the cache. I'll open a new issue for that.

**Comment by titusfortner** [comment]
This may have been addressed, either way, we don't explicitly support standalone usage.
