### ISSUE TITLE
[🚀 Feature]: provide fluent API for WebElement

### ISSUE THREAD

**Issue by manoelcampos** [SeleniumHQ/selenium#13074]
### Feature and motivation

`WebElement` class has void methods `click`, `submit`, `sendKeys` and `clear`.
It would be very convenient that such methods return `WebElement` instead of `void` to enable chaining method calls.

Other classes such as `Select` may benefit from this.

### Usage example

There are some situations that would be helpful, for instance:

- Sending multiple keys in sequence: `webelement.sendKeys("my email address").sendKeys('\t')`
- Performing multiple operations in sequence, such as filling in a field and clearing up after that to check how the element behaves: `webelement.sendKeys("my email address").clear()`

**Comment by manoelcampos** [comment]
I can submit a PR if you think this is interesting.

**Comment by titusfortner** [comment]
You could create an element wrapper library and have it provide this kind of functionality. 

For Selenium itself, we want to provide the most obvious return value for each element method, which is going to be based on the expectations set in the [WebDriver spec](https://w3c.github.io/webdriver/) instead of encouraging people to chain things.

**Comment by manoelcampos** [comment]
If someone is willing to have a fluent API for some classes such as WebElement, but don't want to implement a decorator pattern by scratch, you can use Lombok's `@Delegate` annotation to streamline that. Check http://www.javabyexamples.com/decorator-pattern-with-lombok
