### ISSUE TITLE
[🚀 Feature]: Replace `Newtonsoft.Json` package with `System.Text.Json`

### ISSUE THREAD

**Issue by nvborisenko** [SeleniumHQ/selenium#13097]
### Feature and motivation

We use `Newtonsoft.Json` package to serialize/deserialize json. It is great library. But seems json is becoming built-in format in BCL (.net 6). In future it allow us to be not dependent on any 3rd-party libraries.

### Usage example

It is entirely internal stuff.

We will produce multi-targeted package:
- `netstandard2.0` - depends on `System.Text.Json`
- `net6.0` - has no dependencies

### Actions:
- [ ] Migrate `WebDriver` project without CDP generation
- [ ] Change generation of CDP models
- [ ] Migrate unit tests
- [ ] Introduce new target framework `net6.0` without dependencies

**Comment by titusfortner** [comment]
But we can't do this until we drop support for everything below .NET 6?

**Comment by jimevans** [comment]
@titusfortner Not _entirely_ accurate. We could still target .NET Standard 2.0, but that target would just have to have a dependency on the System.Text.Json assembly. Same for .NET Standard 2.1 (to handle .NET Core 2 and 3). But if we target those two platforms, plus .NET 6, 7, and 8, the latter three would not require dependencies.

**Comment by NCLnclNCL** [comment]
Great

**Comment by NCLnclNCL** [comment]
need do, it will reduce size for native aot

**Comment by titusfortner** [comment]
So the idea is to add compile conditionals to use `System.Text.Json` in some places and `Newtonsoft.Json` in others? That seems like a lot more of a maintenance burden than just having a 3rd party dependency?

**Comment by NCLnclNCL** [comment]
> So the idea is to add compile conditionals to use `System.Text.Json` in some places and `Newtonsoft.Json` in others? That seems like a lot more of a maintenance burden than just having a 3rd party dependency?

No, System.Text.Json is supported in .net standard 2.0(> .net 4.6.2), it can be installed via nuget, currently selenium only supports .net standard 2.0 and above

**Comment by nvborisenko** [comment]
> need do, it will reduce size for native aot

I don't think this story is about size reduction for native AOT. I am expecting selenium package will be targeted to `net6.0` without dependencies. Size reduction via assembly trimming would be next step (if `bazel` allows).

**Comment by NCLnclNCL** [comment]
> > need do, it will reduce size for native aot
> 
> I don't think this story is about size reduction for native AOT. I am expecting selenium package will be targeted to `net6.0` without dependencies. Size reduction via assembly trimming would be next step (if `bazel` allows).

But why you dont it

**Comment by RenderMichael** [comment]
Just noting that [`OpenQA.Selenium.DevTools.DevToolsCommandData`](https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/src/webdriver/DevTools/DevToolsCommandData.cs#L36) has a public constructor which takes `JToken`, in fact only `JToken`.

This gets used by the [`SendCommand`](https://github.com/SeleniumHQ/selenium/blob/da62a402d0565dd2dda2ced71cf74965caa4391c/dotnet/src/webdriver/DevTools/DevToolsSession.cs#L242) method, Which takes a `JToken` directly (this is the way I found out about this).

The method calls `JToken.ToString()` for logging, and passes it into a `new DevToolsCommandData()` and calls the JSON serialize method onto it.

In the use cases I have handled, I have only needed to pass in the equivalent of `Dictionary<string, string>`, so I am tempted to suggest exposing an alternate method with that kind of parameter. However I do not know the full breadth of what this API handles.

I strongly suggest staying away from just passing in `object`, otherwise there will be no indication of a break, and if a `JToken` gets serialized by the `System.Text.Json` serializer... nothing good happens (trust me, I've tried... it fails in both directions. I opened an issue on Newtonsoft.Json to support STJ types, but this is almost certainly not happening https://github.com/JamesNK/Newtonsoft.Json/issues/2910).

My suggestion: this API is likely intended to handle command args from booleans to strings to lists to dictionaries. Expose a constructor which takes a `bool`, a `long`, a `double`, an `List<object>`, `IDictionary<string, object>`, and an overload with no command argument, which would have better user experience instead of dealing with `null` having multiple overloads. Although the `object` generic parameters may cause issues (if an element of the list is itself a `JToken`), this will be nothing near the basically breaking change it would be to expose an `object` overload.

Alternate suggestion: currently the command parameters are serialized [without any options set](https://github.com/SeleniumHQ/selenium/blob/da62a402d0565dd2dda2ced71cf74965caa4391c/dotnet/src/webdriver/DevTools/DevToolsSession.cs#L277). Add an options, and use a custom converter which can handle `JToken`. [Here is an example provided by the System.Text.Json authors](https://github.com/dotnet/runtime/discussions/82180#discussioncomment-4986749) of handling a `JToken` using STJ. Note that this means Newtonsoft.Json will remain a dependency for as long as this constructor remains exposed.

edit: I see that [`OpenQA.Selenium.Command`](https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/src/webdriver/Command.cs) just passes in a `string` to represent an already-serialized string. This is arguably better than my previous two suggestions. Let users figure out serialization. The only problem with that is, a lot of properties have explicit `[JsonProperty]` attributes which serializes the data with different property names. This could break things. However, this is probably not an issue as long as it is only used for internal serialization (which AFAICT is the case), such as the `SendCommand` method mentioned above. When work begins on this issue, the relevant code probably needs to be audited to ensure this.

**Comment by titusfortner** [comment]
@nvborisenko do we have more clarity on what we want to be done for this? Thanks.

**Comment by nvborisenko** [comment]
Goal is pretty simple: use another library for `json` serialization/deserialization. That's it.

Why I didn't implement it yet: it is risky to convert some code (like `Cookies` serialization).

My further thoughts: start utilization of new library in BiDi implementation, and then smoothly get rid of old library.

PS: the question is what new target framework we wanna introduce, .net6? .net8? I vote for .net8 because .net6 ends of support soon.
