### ISSUE TITLE
[🚀 Feature]: Add implicint wait, behind the scenes, when interacting with WebElements

### ISSUE THREAD

**Issue by harmin-parra** [SeleniumHQ/selenium#13139]
### Feature and motivation

Recent frameworks like **Cypress** and **Playwright**, make an implicit wait behind the scenes, when interacting with WebElements.

For this reason, **Cypress** and **Playwright** are very suitable for testing modern websites built with **AngularJs** and **ReactJs**

With **Selenium**, you need to write extra code to add the implicit wait.

### Usage example

Writing this:

`element = driver.find_element(By.ID, 'someid')`

Instead of this:

```
from selenium.webdriver.support import expected_conditions as EC
wait = WebDriverWait(driver, 10)
element = wait.until(EC.presence_of_element_located((By.ID, 'someid')))
```

**Comment by titusfortner** [comment]
Selenium does have the ability to do Implicit waiting — https://www.selenium.dev/documentation/webdriver/waits/#implicit-waits

Waiting is tricky because there is no single correct way to do it that works for every single use case (including how Playwright/Cypress does it).  Many projects that wrap or extend Selenium have taken slightly different approaches.
