### ISSUE TITLE
[🐛 Bug]:  selenium-manager.exe being blocked as malware

### ISSUE THREAD

**Issue by HernJer** [SeleniumHQ/selenium#13130]
### What happened?

After upgrading from 4.14.1 to 4.15.0, selenium-manager.exe gets blocked by software like Carbon Black. 

### How can we reproduce the issue?

```shell
.
```

### Relevant log output

```shell
![image](https://github.com/SeleniumHQ/selenium/assets/87041628/67b84785-e10f-469b-a611-29404df718ea)
```

### Operating System

Windows Server 2012 R2

### Selenium version

4.15.0

### What are the browser(s) and version(s) where you see this issue?

na

### What are the browser driver(s) and version(s) where you see this issue?

na

### Are you using Selenium Grid?

na

**Comment by bonigarcia** [comment]
Sorry for the inconvenience. I suppose this issue is caused by using the `stable-i686-pc-windows-gnu` target to build Selenium Manager for Windows in Selenium 4.15.0. But since this target is only required for the debug version of Selenium Manager in Windows, I think we can revert to `stable-i686-pc-windows-msvc` for the release version (which seems safer than the `gnu` one in the eyes of antivirus, for some reason). We can use `stable-i686-pc-windows-gnu` only for the debug version (this will include the debug symbols used for troubleshooting).

I created a PR to change how Selenium Manager is built in CI: https://github.com/SeleniumHQ/selenium/pull/13134

@HernJer Can you please have a try with the new binary?

1. Download the new binary from here: [selenium-manager_windows-x32](https://github.com/SeleniumHQ/selenium/suites/18080121136/artifacts/1041760955)
2. Uncompress it and replace it with your local Selenium Manager at `C:\agent\runner\selenium.webdriver\4.15.0\manager\selenium-manager.exe`
3. Test again and share the results here.

Thanks

**Comment by HernJer** [comment]
@bonigarcia  - that seem to have done the trick. thanks! i am also sending the file to my IT Sec team to fully vet.

will this be packaged on a new version so i can update my references?

**Comment by bonigarcia** [comment]
Great to know, thanks @HernJer. Yes, this new Selenium Manager Windows binary will be shipped with next Selenium release.

**Comment by vikramtechforall** [comment]
@bonigarcia was this change incorporated in 4.16? because i am still observing the issue with selenium-manager.exe

**Comment by titusfortner** [comment]
We're still working to get the binaries signed which should fix the issue.

**Comment by vikramtechforall** [comment]
Thanks @titusfortner! Is there an ETA on the same? is there a temporary file which we could try to make sure that's going to work fine with our firewall/proxy settings?

**Comment by titusfortner** [comment]
I'm not sure what you mean by a temporary file. What we have isn't signed and might flag security checks if they are stringent. I'm not sure the current status of it as it is our fiscal sponsor who is running down the requirements for us, and we haven't had a chance to follow up in a while.

**Comment by HernJer** [comment]
Any change this can this be reopened until it's actually resolved? Don't want this to fall down the cracks.

**Comment by titusfortner** [comment]
It's being tracked here — #12935
