### ISSUE TITLE
[🐛 Bug]: Open Chrome with an exsisting profile, when same profile is already open

### ISSUE THREAD

**Issue by Shumatic** [SeleniumHQ/selenium#13149]
### What happened?

I am using VBA and trying to open a new instance of chrome with my default profile, and with chrome open, and i get this error.
is there a workaroun for this?
I read i should use an other profile, but i need my default one, and copying it isn't a solution as it is 4Gb

### How can we reproduce the issue?

```shell
Dim driver As New Selenium.ChromeDriver
Sub test()
driver.SetProfile "C:\Users\xxx\AppData\Local\Google\Chrome\User Data"
driver.AddArgument ("user-data-dir=C:\Users\xxx\AppData\Local\Google\Chrome\User Data")
driver.start "chrome", ""
End Sub
```

### Relevant log output

```shell
Run-time error '33'
SessionNot CreatedError
Session not created: Chrome failed to start: exited normally.
```

### Operating System

Win10

### Selenium version

SeleniumBasic VBA

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 119.0.6045.124

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 119.0.60.45.105

**Comment by diemol** [comment]
We do not maintain the VBA project, you are probably looking for https://github.com/florentbr/SeleniumBasic

**Comment by Shumatic** [comment]
> We do not maintain the VBA project, you are probably looking for https://github.com/florentbr/SeleniumBasic

Sorry for ignorance :-)

**Comment by OshidaBCF** [comment]
I do not know what "VBA" is but i am having the same issue with regular selenium 4 on python

If i try to run my script i get this error
```py
SessionNotCreatedException: session not created: Chrome failed to start: exited normally.
  (chrome not reachable)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

i'm starting chrome with a profile so that i am already connected in a couple websites, but if i have chrome already running with said profile, it just open a new window, not automated, then crash with the error above.

I have this bit of code for the driver but i'm not sure if i added something i shouldn't have

```py
options = Options()
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--no-sandbox')
options.add_argument('--remote-debugging-port=9292')
options.add_argument(R"user-data-dir=C:\Users\swann\AppData\Local\Google\Chrome\User Data") #Path to your chrome profile

service = Service(executable_path=R"D:\Users\Swann\Documents\chromedriver.exe")

driver = webdriver.Chrome(options=options, service=service)
```

i already did updated chromedriver to the right version of chrome.

**Comment by Shumatic** [comment]
Even though it is for VBA, have a look at https://github.com/florentbr/SeleniumBasic/issues/275#issuecomment-1817475430

**Comment by OshidaBCF** [comment]
i tried adding ```options.add_argument("--profile-directory=Default")``` but it doesn't work, it open chrome with the profile loaded like before, but the instance isn't automated, and i get the same error "chrome is unreachable"

Putting anything than "default" start a new window, not automated, with a new clean profile

**Comment by titusfortner** [comment]
You cannot access an open instance of Chrome by passing in the directory location to the driver. Please investigate options on stack overflow.

**Comment by OshidaBCF** [comment]
I managed to make it work

if i start my regular chrome with a debugging port, then if i only have this line for option, it works
```options.add_experimental_option("debuggerAddress", "localhost:9222")```

Now i just needed to add a new "tab" line because it decided to run the script on a random tab each times

Now i just need to add the debugging port argument to my normal chrome startup.


Thanks a lot

If anyone has to do that too one day, here's the code just for that :

```py
options = Options()
options.add_experimental_option("debuggerAddress", "localhost:9222")
service = Service(executable_path=R"D:\Users\Swann\Documents\chromedriver.exe")
driver = webdriver.Chrome(options=options, service=service)
driver.switch_to.new_window('tab')
driver.get(R"https://steamcommunity.com/workshop/editcollection/?appid=107410")
```
