### ISSUE TITLE
Safari 9.0 webdriver extension certificate issue.

### ISSUE THREAD

**Issue by vveliev** [SeleniumHQ/selenium#1315]
Hey, not sure if I'm doing something wrong or not. But I'm not able to run safari due to the trust issue(have to enable extension every time safari starts).
can someone give me any alternative ?! Since buying dev subscription just to install webdriver extension does not seemed to be logical. 

Thanks

**Comment by Elisena** [comment]
I have same issue System is Yosemate 10 with Safari 9.0.1 Safari extension 2.48

**Comment by ipsi** [comment]
I suspect that it's a bug in Safari - someone else reported the same problem here: http://apple.stackexchange.com/questions/214760/force-installing-untrusted-safari-extensions, and I'm seeing the same behaviour. It works fine on Safari 9.0, but not Safari 9.0.1.

**Comment by ddavison** [comment]
The Safari extension will have to be deployed and "licensed" through apple in order to be trusted.  we unfortunately do not have a license yet to develop for Safari.. @shs96c , I think, has been working on getting a license for the Selenium team from the SFC, but i'm unsure of the status.

I'm not sure that installing the SafariDriver will work with the newer versions due to the security changes.  All new extensions must be signed, and to sign - you need that apple developer license.  There's nothing we can do at this moment.

If there is a user out there with an Apple developer license and is willing to look into this, then they are very welcome to!

**Comment by vveliev** [comment]
I found solution .... 

0. Download extension
1. Boot into the OSX using safemode.
2. install extension
3. restart.
4. Start selenium

:) and you can use it !
