### ISSUE TITLE
[🚀 Feature]: How to access all attributes and/or data attributes?

### ISSUE THREAD

**Issue by ioquatix** [SeleniumHQ/selenium#13220]
### Feature and motivation

Right now it's possible to query an attribute value using `element.attribute(name)`, `element.dom_attribute(name)` or `element.property(name)`. There is an alias of `element.[name]` -> `element.attribute`.

I would like to enumerate all attributes, and occasionally only all `data-` attributes of an element.

It would be nice to implement the following methods:

```ruby
class Element
  # Return a hash table of all attributes.
  def attributes
    # ...
  end

  # Return a hash table of all data- attributes.
  def data
    # ...
  end

  # Return true if the attribute exists
  def attribute?(name)
    attribute(name) != nil
  end

  # We already have alias [] attribute, so consider this too:
  alias key? attribute?
end
```

### Usage example

I believe this is useful for test frameworks to implement expectations, e.g.

```
expect(element).to have_keys(class: be =~ /foo/)
```

More specifically, we can make assertions about the attributes:

```
expect(element.attributes).to be == {class: "foo"}
expect(element.data).to be == {stuff: "..."}
```

**Comment by titusfortner** [comment]
Cool idea. With watir you could use #inner_html on the element and run some regex against it to see what all it contains. Would be an interesting feature in watir. 

Selenium doesn't have access to that method's functionality directly... And getting more info around all of an element's attributes would require new features get added to w3c, which isn't likely right now.

I'm closing this as out of scope, but find me on Selenium slack if you want to discuss it.

**Comment by ioquatix** [comment]
I found that the following code can return an element's attributes:

```ruby
web_driver.script("return arguments[0].attributes", element)
```

We could provide this as a method on element.

I also wondered if we should make it easier to run a script with `this` as the element, e.g.

```
element.script("return this.attributes")
```

Something like:

```ruby
class Element
  def script(source)
    web_driver.script("(function(){#{source}}).call(...arguments)")
  end
end
```

**Comment by titusfortner** [comment]
Ah, there we go. JavaScript to the rescue. 

Definitely add it to your framework; I actually encourage people to create their own wrapper class of the `Webdriver::Element` because there is a bunch of interesting additional functionality that can be added (e.g., https://github.com/watir/watir/blob/main/lib/watir/elements/element.rb)

But these convenience methods are outside the scope of Selenium itself.

**Comment by ioquatix** [comment]
Can you clarify what is in-scope and what is out-of-scope? I assume it's something to do with the W3C standard?

But then we have things like `alias []` and https://github.com/SeleniumHQ/selenium/blob/240e17b647d754b8d88b606cd1bca6345240c0b1/rb/lib/selenium/webdriver/common/element.rb#L106-L117 which seem fairly non-trivial/non-primative. Specifically, Element seems to be duck typed to behave like a hash table (similar to how the JS object interface would work) but is missing specific pieces of the interface like `include?` and `key?` etc.

I understand your idea about wrapping the element class, but it will create a lot more garbage, and I think primitive operations should be well-supported. In addition, this will create a lot of divergent frameworks which makes it harder for users to learn the core competencies of the webdriver model. Therefore, I'd encourage us to be mindful of having a well supported set of primitive operations on the Element class.

It might also be nice from a user debugging POV to make `Element#inspect` behave similarly to how it does in the browser inspector. Certainly it would make it easier to debug.

**Comment by titusfortner** [comment]
Yes, there's some magic in`Element#attribute`. It pre-dates the spec, and is kept for backwards compatibility, we recommend using `#dom_attribute` or `#property` instead.

Yes, the previous maintainer liked accessing things with `#[]` as a convenience method (used in `Capabilities` as well much to my frustration). I'm less of a fan because you see `#[]` and then you expect a `Hash` even when it isn't a `Hash`, and `Symbol`s and `String`s get all weird. Definitely not principle of least surprise. But they are there, and seems easier to leave them be than to remove them.

The major thing you can get from a wrapper class is the ability to store the locator, manage stale elements and sync/re-sync on actions. It only creates the garbage you want since Ruby makes it easy to delegate everything you don't want to the Selenium object.

>  I think primitive operations should be well-supported

Yes, and the primitive operations are the ones defined by the spec. We don't have methods that wrap JavaScript (or at least we shouldn't), and we don't have methods that include a combination of wire calls (except for uploading a file to the grid). Requests for additional features can be made here: https://github.com/w3c/webdriver/issues

What do you think `Element#inspect` should look like?

**Comment by ioquatix** [comment]
I agree aligning with the spec makes sense.

I suggest you deprecate that behaviour/methods which don't align with the spec.

We could add more documentation:

- Regarding aligning with the spec - exposed functions.
- How to do things like listing attributes, properties, etc.
