### ISSUE TITLE
Lack of documentation for JavaScript

### ISSUE THREAD

**Issue by jpierson** [SeleniumHQ/selenium#1324]
I'm just diving into using Selenium for the first time and I'm attempting to write my tests in JavaScript and Mocha as the test runner. When searching for examples out in the wild I come across plenty of Python and Java examples but not a whole lot in JavaScript. I figured I'd go to the source and ended up on the official Selenium site but even there JavaScript seems not to be given equal treatment. Just look at the [code examples](http://docs.seleniumhq.org/docs/03_webdriver.jsp).

http://docs.seleniumhq.org/docs/03_webdriver.jsp#setting-up-a-selenium-webdriver-project

Currently I'm struggling to find the supported ways of dealing with _select_ and _option_ elements. Some Java examples show wrapping the element in a _Select_ object but I can't find any similar usage in JavaScript. Is there somewhere that I can find more complete documentation? If not, are there plans to improve the JavaScript documentation?

**Comment by mekdev** [comment]
@jpierson 

San Francisco Selenium just had a tech talk on this - node.js and Selenium.
The recording and slides might be of some help to you 

Recording - https://www.youtube.com/watch?v=CqeCUyoIEo8
Slide - http://www.slideshare.net/MekSrunyuStittri/nodejs-and-selenium-webdriver-a-journey-from-the-java-side

**Comment by lukeis** [comment]
Pull requests to that page would be greatly appreciated. I spent a good amount of time trying to get examples in the initial for main supported languages.... and then we added node as another official one.

The documentation referenced is maintained in a separate repo. Pull requests gladly accepted:

https://github.com/SeleniumHQ/www.seleniumhq.org/blob/master/src/main/rst/03_webdriver.rst

If you'd like a bug to 'track' getting more javascript examples, please log one over in that repo. Closing since it's not related to the code inside this repo.

Also there's a few javascript examples here:
https://github.com/SeleniumHQ/selenium/tree/master/javascript/node/selenium-webdriver/example

**Comment by lukeis** [comment]
As far as 'select' are concerned. All the helper classes in the other languages do is find the appropriate 'option' element and perform a click on them to change the state of the select.
