### ISSUE TITLE
[🐛 Bug]: node already offline , but xxx:4444/ui 仍显示对应node

### ISSUE THREAD

**Issue by jjqi92** [SeleniumHQ/selenium#13305]
### What happened?

node 10.32.114.13:8088 already offline , but hubip:4444/ui 仍显示对应node

![image](https://github.com/SeleniumHQ/selenium/assets/30493198/a7957eda-f75c-44f2-b4f1-a7c901eec0a1)

### How can we reproduce the issue?

```shell
i'm not sure if reproduce by this operates.

online node 10.32.114.13:8088
then kill port 8088
```

### Relevant log output

```shell
no
```

### Operating System

windows10

### Selenium version

java11 selenium4.16.1

### What are the browser(s) and version(s) where you see this issue?

chrome  114.0.5735.134（正式版本） （32 位）

### What are the browser driver(s) and version(s) where you see this issue?

chromeDriver4.16.1

### Are you using Selenium Grid?

4.16.1

**Comment by diemol** [comment]
The UI will still show the Node for a while because it does not assume it is dead after the first check, however, it marks it as DOWN (which is why you see it with a different tone in the UI). This is done in case there was a network hiccup during the check, but there is no need to remove the Node yet.

After a couple of checks more, the Hub will definitely assume the Node is dead and remove it.
