### ISSUE TITLE
[🚀 Feature]:[bidi][grid]Remove se:bidi and rewrite webSocketUrl

### ISSUE THREAD

**Issue by diemol** [SeleniumHQ/selenium#13302]
### Feature and motivation

In Grid, currently, we are enhancing the `webSocketUrl` returned after a BiDi session is created. This value is sent back to the client as `se:bidi`. 

### Usage example

Thinking this through, we do not need `se:bidi`, we can rewrite `webSocketUrl` and therefore simplify the logic implementation on the client side.

**Comment by pujagani** [comment]
The approach is the above changes tries to reconstruct the websocket URL while creating websocket connection in the Node side, since it is possible to do so because it uses the session id in the URL. The only parameter that is required is the port in which the BiDi session is running, so that is added as a capability. 
The approach may not be ideal but it prevents having "se:bidi" capability to store the rewritten URL and simplifies the logic a bit..

**Comment by pujagani** [comment]
Closed via https://github.com/SeleniumHQ/selenium/pull/13528

**Comment by elgreco247** [comment]
Doesn't seem to work for Chrome 123.0.6312.86 (no webSocketUrl capability returned from grid).

**Comment by diemol** [comment]
Please create an issue and fill out the template, thanks.
