### ISSUE TITLE
Firefox 42.0 Linux selenium 2.48 Not able to change firefox user settings

### ISSUE THREAD

**Issue by kolvo** [SeleniumHQ/selenium#1330]
Hi All,
I am not able to save the file directly from Firefox during the test case is running by webdriver.
The browser is opened as a root. Normally when I manually open browser it works fine.
It does not work with Firefox 42 and 40. However, it works with v39. 
I modified ../../../../../python2.7/dist-packages/Selenium2Library/resources/firefoxprofile/prefs.js
but unfortunately the changes are not visible in GUI view directly in Firefox.
In my opinion the problem can be with access rights or some other configuration files need to be change.

Does anybody have a similar issue and can give any hint?
Thanks,
Regards,

**Comment by HelioGuilherme66** [comment]
Sorry if I am wrong, but I think you are using a RobotFramework Selenium2Library which is DSL for Selenium (Webdriver).
I think (again) that there was security changes in profile usage since Firefox 40. In the case of RobotFramework Selenium2Library the known workaround is to give the path for a user profile, like in:
```Open Browser    http://URL    ff    ff_profile_dir=/path_for_the_firefox_profile/filename.default```

(My guess is that this issue tracker manager will not consider your problem a valid defect.)

**Comment by kolvo** [comment]
Hi Helio,
Thanks for your input. You are right about my tools.
Fortunately, somehow it started to work well.
All what I did was changing entries into above mention prefs.js file which is located in Selenium2Library directory. 
I am closing the issue as resolved. Maybe someone will have similar problem then I can try to help with above configuration file.
