### ISSUE TITLE
Selenium with Python: - Not able to locate elements for Guidewire Claimcenter 7 in IE

### ISSUE THREAD

**Issue by samrat-github** [SeleniumHQ/selenium#1331]
I am automating Guidewire Claimcenter 7 which runs in IE only. I am using selenium webdriver and python script.

iedriver = "C:\Python34\IEDriverServer_Win32_2.48.0\IEDriverServer.exe"
os.environ["webdriver.ie.driver"] = iedriver
driver = webdriver.Ie(iedriver)
driver.get(<my claimcenter link>)

###after logging into...
actDropdown=driver.find_element_by_xpath("//a[@id='TabBar:ClaimTab']")
actDropdown.click()

I am getting the error while executing the script 

"selenium.common.exceptions.NoSuchElementException: Message: Unable to find eleme
nt with xpath == //a[@id='TabBar:ClaimTab']"

I also tried with class name, partial text etc etc...but no luck.

Can anybody help me?

**Comment by ddavison** [comment]
This looks like a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

We reserve these GitHub issues for concrete issues with the Selenium software.  If you've found one, please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#bug-reports)
