### ISSUE TITLE
Capability Flag in IE Ignores Control Panel Mouse Setting

### ISSUE THREAD

**Issue by DeZaelez** [SeleniumHQ/selenium#1335]
Selenium version: 2.48.2 (selenium-server-standalone-2.48.2)
Language: Java (1.8.0_66)
IE Version: 9.0.8112.16421

This issue is only visible for users that have *reversed* the mouse buttons in the control panel because they are using their mouse left handed.

In IE, when the user sets the Desired Capability flag to ".REQUIRE_WINDOW_FOCUS" and has reversed mouse buttons, Selenium ignores the control panel settings and issues the wrong click event.

 To reproduce the issue do the following:
1.  In the control panel, reverse the mouse buttons.
2.  Create and run a script with the following code:
>DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
>capabilities.setCapability(InternetExplorerDriver.REQUIRE_WINDOW_FOCUS, true);
>WebDriver webdr = new InternetExplorerDriver(capabilities);
>
>webdr.get("google.com");
>WebElement image = webdr.findElement(By.id("hplogo"));
>image.click();

You will notice that when the click event is issued, Selenium issues a right-click event rather than the normal left-click.

**Comment by jimevans** [comment]
Yes, this is a bug. The reason is that when you set the `requrireWindowFocus` capability, you're simulating events with the `SendInput` API. This API simulates input at a very low level in the OS's input queue stack. Thus, it explicitly sends a "left button" input event. If you've swapped your mouse buttons at the input stack level, the left button will trigger the secondary button event in the application (Internet Explorer).

Fixing it would involve querying the mouse configuration settings of Windows, and even then, there are likely to be corner cases for systems with non-standard input devices. Given the potential for mishandling these corner cases, I'm closing this as won't fix. If someone wants to do the leg work to submit a pull request to the IE driver (the relevant code is located in `InputManager.cpp`), I'll consider merging it.
