### ISSUE TITLE
[🐛 Bug]: Selenium Manager - Exec format error on aarch64 (with fix)

### ISSUE THREAD

**Issue by JChrysanthemum** [SeleniumHQ/selenium#13359]
### What happened?

Same with this [closed issue](https://github.com/SeleniumHQ/selenium/issues/12778)

But this answer fixes this problem [https://stackoverflow.com/a/77099069/7064406](https://stackoverflow.com/a/77099069/7064406), now I can use selenium manager on arm64 board.

[Env]
System: aarch64 debian_bullseye 
geckodriver: v0.33.0-linux-aarch64
Firefox: Mozilla Firefox 115.5.0esr

### How can we reproduce the issue?

```shell
Could you take a look into [https://stackoverflow.com/a/77099069/7064406](https://stackoverflow.com/a/77099069/7064406) ? I don't know how and why it works :(
```

### Relevant log output

```shell
no logs, works perfectly.
```

### Operating System

aarch64 debian bullseye 

### Selenium version

python 3.9

### What are the browser(s) and version(s) where you see this issue?

Firefox 115.5.0esr

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver  v0.33.0-linux-aarch64

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
That code works because it skips Selenium Manager; there is nothing for Selenium to be able to automatically manage.
You need to:
1. Manually download the desired driver
2. Specify the location of the desired driver in the appropriate Service class

We will likely revisit this if Chrome releases a driver we can automatically manage on Linux/Aarch64 —https://github.com/GoogleChromeLabs/chrome-for-testing/issues/1

**Comment by JChrysanthemum** [comment]
Thanks for your time !!! Hope to try your new feature soon.
