### ISSUE TITLE
Disable user name and password logging on Selenium Server side

### ISSUE THREAD

**Issue by carlwu66** [SeleniumHQ/selenium#1342]
Currently I am using selenium-server-standalone-2.48.2.jar, it works perfect. However, when a user name and password is passed in by client, it also logs the user name and password:
"
java -jar /opt/selenium/selenium-server-standalone-2.48.2.jar -log /var/log/selenium.log -forcedBrowserModeRestOfLine *firefox -maxSession 40 -browserTimeout 90
"
We want to run the server in the same way, just we just do not want user name and password go to selenium.log. 

Is there a method to do this or it will show up in the future release?

**Comment by barancev** [comment]
How would the server recognize what data should not be logged?

**Comment by carlwu66** [comment]
Match a configuration list, something with data fields name like "pass*",
"user*"?

Regards,
Carl Wu

Contact Info:
Email:  carlwu66@gmail.com
Phone: (510)598-8048

Email is the best way to reach me.

**Comment by pharasimiuk** [comment]
How about just an option to omit logging events such as "send keys"? Or as per Carl's suggestion: accept a list of field names for which keystrokes won't be logged.

**Comment by barancev** [comment]
Selenium uses java.util.logging, so you can create a custom selenium server launcher that disables default log handlers and registers your own "secure" handlers instead. Write your own class with the main method instead of this one: https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/selenium/GridLauncher.java#L105-L135
