### ISSUE TITLE
[🚀 Feature]: Selenium Manager combine driver-version and browser-version

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#13420]
### Feature and motivation

Kind of along the lines of #13419 
The functionality for these two should be the same now that Selenium manages both.
I don't think SM should support mixing different versions of browser & driver.

It should:
1. Full version: Use/Get the exact version of browser & driver, error if it can't find it
2. Major version:
    * If matches what is installed, use what is installed
    * If there is a later minor/patch version available than what is installed log a warning (Does this work with installed versions? Should "stable" always use the latest Stable CfT  and not what is on the desktop by default?)
    * Download the latest major version driver/browser

### Usage example

./selenium-manager --browser chrome --browser-version 120.0.6099.71

**Comment by diemol** [comment]
I am not sure this is needed. I think we will eventually have the binary released and users will just need the driver version part, for example when they want to automate browsers like Brave.

**Comment by titusfortner** [comment]
I can see that use case, but then `--driver-version` should not include a `browser_path` in the output.

**Comment by bonigarcia** [comment]
If you think in Chrome terms, the browser and driver versions are indeed related (both major values match). But Firefox and geckodriver uses different versioning schema, so that's a reason to have `--driver-version`, in my opinion. Regarding not including `browser_path`, I am not sure about that. Reporting the found browser can be helpful in creating a Selenium session, which is the final aim.

**Comment by diemol** [comment]
Implementing #13419 will implicitly implement this one. Therefore, I am closing it.
