### ISSUE TITLE
[🚀 Feature]: Selenium Manager Log Level

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#13437]
### Feature and motivation

If we stream errors from Selenium Manager (#13414), we should be able to set the logging level at whatever Selenium's logging level is set to. So I propose we get rid of `--debug` and `--trace` and replace with a generic `--log-level` that accepts `error`, `warn`, `info`, `debug`, `trace`

### Usage example

Have this output Debug info:
```
Logger.getLogger("").setLevel(Level.FINE);
Arrays.stream(logger.getHandlers()).forEach(handler -> {
    handler.setLevel(Level.FINE);
});
new DriverFinder(service, options).getDriverPath();
```

**Comment by bonigarcia** [comment]
I would include `--log-level <LEVEL>` as proposed, but I would also maintain `--debug` and `--trace`, since we already have them. For example, I used these options all the time in development. This way, `--log-level debug` would be the same as `--debug`, but both options are possible (and with the second, you write less).

**Comment by bonigarcia** [comment]
Closed via https://github.com/SeleniumHQ/selenium/pull/13566.
