### ISSUE TITLE
[🚀 Feature]:  [JAVA] Avoid null Return Value for fromString Method

### ISSUE THREAD

**Issue by manuelsblanco** [SeleniumHQ/selenium#13458]
### Feature and motivation

 I noticed that the fromString method  `public enum   UnexpectedAlertBehaviour` returns null when it can't find a matching UnexpectedAlertBehaviour. This could potentially lead to NullPointerExceptions in parts of the code that use this method and do not anticipate a null return value
 
 
<img width="623" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/30122785/28d64fd9-03c0-43b7-bbf9-8f39a10a6864">

### Usage example

Instead of returning null, we could:

Throw an IllegalArgumentException when no matching enum is found. This makes it explicit that the provided text could not be matched to an UnexpectedAlertBehaviour and forces the caller to handle this case.
Java

`public static UnexpectedAlertBehaviour fromString(String text) {
  if (text != null) {
    for (UnexpectedAlertBehaviour b : UnexpectedAlertBehaviour.values()) {
      if (text.equalsIgnoreCase(b.text)) {
        return b;
      }
    }
  }
  throw new IllegalArgumentException("No enum constant " + text);
}`
<img width="404" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/30122785/b9ebfb84-318a-4e70-9461-38958e497315">

**Comment by pujagani** [comment]
Thank you for filing the issue. The method `fromString()` is primarily for getting the enum value. However, it is not used in the Selenium project internally. 
Since it is a public method, there could be a chance that a user is using it and handling the "null" situation on their end. Throwing an error will then make it a breaking change and there is no way to avoid it.
