### ISSUE TITLE
Unable to enter text in second consecutive textbox(Sometimes) when running tests on jenkins(Centos) with FirefoxDriver

### ISSUE THREAD

**Issue by amish44** [SeleniumHQ/selenium#1345]
We are using jenkins along with xvfb plugin to run selenium tests using FirefoxDriver. When any webpage have two text boxes consecutively(e.g. userame, email etc on signup page) sometimes the text for both the textboxes entered into first textbox only(e.g. UserName: myUserNamemyEmailAddress) instead of entering myEmailAddress in Email field. The web application is designed using springboot and tapestry frameworks. For now as workaround we are using pauses between both text boxes to work. But this is not expected as we are providing element for both text boxes it should enter value to that specific text box only. I don't know exactly why it is happening may be its very fast running tests but the thing is elements are different then how it possible, please let me know the details if possible.

**Comment by p0deje** [comment]
This looks like a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

We reserve these GitHub issues for concrete issues with the Selenium software.  If you've found one, please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#bug-reports)

**Comment by amish44** [comment]
Thanks for the quick reply, I will add it to forum.
