### ISSUE TITLE
Selenium Not Running

### ISSUE THREAD

**Issue by gmur24** [SeleniumHQ/selenium#1349]
Hi I'm a neophyte in using this package. I followed this tutorial http://denvycom.com/blog/data-scraping-selenium-java/ yet for some reason the main method is not recognized. Below is a screenshot. 

BTW, I'm using Java. 

![image](https://cloud.githubusercontent.com/assets/13022982/11610101/96d2ad1a-9bd3-11e5-8f25-69c617b1d772.png)

Error: Editor does not contain a main type.

**Comment by ddavison** [comment]
that's because eclipse doesn't know what to compile.  you'd need to add `ScrapeData.java` to a source folder on your build path.  do some googling around regarding "eclipse build path source folder" and i'm sure you'll figure it out.. unfortunately though, we can't help you with this here :).  we reserve these issues for concrete issues found with Selenium.
