### ISSUE TITLE
[🚀 Feature]: add TryGetElement functionality

### ISSUE THREAD

**Issue by minnmass** [SeleniumHQ/selenium#13503]
### Feature and motivation

C# especially tends to have `TryGetX` functions alongside `GetX` functions that throw exceptions when the thing can't be gotten - which is the behavior for `GetElement`. I find that I keep having to work around the lack of a `TryGetElement` function, and neither of the available options is stellar.

Wrapping `GetElement` in a try/catch means having to swallow the exception and still makes debugging obnoxious if I have VisualStudio set to break on all `NoSuchElementException`s.

Using `GetElements` and checking for an empty list works well up until it doesn't, eg. on pages were the best selector may still return a significant number of elements (which mostly means that `By.Xpath` doesn't work for some reason).

### Usage example

```
if(driver.TryGetElement(By.ClassName("foo"), out IWebElement element)) {
  // element cannot be null here, since the element was found
  element.Click();
}
```

**Comment by titusfortner** [comment]
Thanks for the suggestion.

Selenium uses the WebDriver specification, which means that when the driver does not find an element, it returns an error - https://w3c.github.io/webdriver/#dfn-no-such-element

So either Selenium code would need to try/catch the generated error, or you would need to do it in your code.
Since there are many similar/competing things that can be done here, we leave it up to client projects to decide how to handle these things.
