### ISSUE TITLE
[🐛 Bug]: Memory leak on Chrome 121 when page is reloaded when it is run from selenium-webdriver

### ISSUE THREAD

**Issue by dbaranovsky97** [SeleniumHQ/selenium#13533]
### What happened?

We faced with memory leak on Chrome 121 when it is run from selenium-webdriver.
After page reopening there are a lot of not destroyed Window objects.

![image](https://github.com/SeleniumHQ/selenium/assets/37049940/432a8581-42af-4523-be35-16ebec1eadbe)
It's Window objects from previous page instances.

### How can we reproduce the issue?

```shell
Repo: https://github.com/dbaranovsky97/chrome-selenium-webdriver-memory-leak.git
Just run:
`npm i`
`node .`
On last the iterations you can stop driver by breakpoint, go to Chrome, open DevTools and take Memory snapshot and see how many objects are leaked.
```

### Relevant log output

```shell
-
```

### Operating System

Windows 10

### Selenium version

JavaScript 4.17.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 121

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 121

**Comment by rjamiller** [comment]
Hi @dbaranovsky97 

Getting the same issue here - did you raise a defect with chromedriver?

Thanks

**Comment by shalvardb** [comment]
We are also facing out of memory issue with chrome driver 121.0.6167.85 . 
It is a blocker for our automation framework

**Comment by diemol** [comment]
@shalvardb have you reported the issue to the Chrome folks?

**Comment by sparrowt** [comment]
Also seeing unusually high memory usage running selenium tests on chrome 121.0.6167.140 / chromedriver 121.0.6167.85
![image](https://github.com/SeleniumHQ/selenium/assets/793763/14b7b2d8-51e5-423c-a47e-3dac97108678)
and often we then find the tests eventually hang because the renderer has died and is showing: 

    Aw, Snap!

    Something went wrong while displaying this webpage.

    Error code: Out of Memory

which causes the tests to just hang as there is no timeout by default in `RemoteConnection`.
You can set one so that it no longer hangs infinitely:
```python
from selenium.webdriver.remote.remote_connection import RemoteConnection
RemoteConnection.set_timeout(60)
```
but this doesn't solve the problem that the chrome renderer has died due to OOM and is now unresponsive for subsequent tests.

The closest ticket I can find is https://bugs.chromium.org/p/chromedriver/issues/detail?id=4696 which was closed as WontFix due to no repro being provided (EDIT: I've added the repro steps from this ticket and requested reopen; EDIT2: now reopened)

**Comment by sparrowt** [comment]
See also https://issues.chromium.org/issues/41494493
