### ISSUE TITLE
[🐛 Bug]:  Breaking change to RemoteWebDriver constructor

### ISSUE THREAD

**Issue by MJB222398** [SeleniumHQ/selenium#13609]
### What happened?

Not a bug per se, but just wanted to point out the breaking change that was made since 4.16.2. The parameter name for the ICapabilities parameter in this constructor was seemingly changed from `desiredCapabilities` to `capabilities`. Is it typical to make breaking changes in minor releases without warning? This had me worried for a bit before I saw what had happened.

```
public RemoteWebDriver(Uri remoteAddress, ICapabilities capabilities, TimeSpan commandTimeout)
    : this(new HttpCommandExecutor(remoteAddress, commandTimeout), capabilities)
{
}
```

Maybe stick something in the release notes?

### How can we reproduce the issue?

```shell
N/A
```

### Relevant log output

```shell
N/A
```

### Operating System

N/A

### Selenium version

4.18

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

N/A

**Comment by diemol** [comment]
Why is it a breaking change? The parameter name changed, but the type stayed the same.

As a reference, this is the [commit](https://github.com/SeleniumHQ/selenium/commit/0ebddde50728459888c49e30e864257ae420d38c).

**Comment by MJB222398** [comment]
@diemol Its a breaking change because it meant I had to make changes to my code after updating the Selenium NuGet package. 

My code was as below. So I had to change the parameter name to get it to build. 
```
public async Task<IDriver> CreateAsync(Browser browser)
{
    var remoteDriver = new RemoteDriver(
        new RemoteWebDriver(
            remoteAddress: new Uri(_driverConfiguration.Url),
            desiredCapabilities: _driverOptionsFactory.Create(browser).ToCapabilities(),
            commandTimeout: TimeSpan.FromSeconds(_driverConfiguration.CommandTimeout)),
        browser,
        _elementFactory,
        _byFactory);

    await remoteDriver.Initialize();

    return remoteDriver;
}
```

**Comment by diemol** [comment]
Thanks for flagging this. We did not consider this use case and will consider it for future changes. Before implementing breaking changes, we deprecate the old interface and then do them. Our apologies.

**Comment by nvborisenko** [comment]
50 cents from my point of understanding:

Renaming a parameter name is a breaking change at the compilation level. It differs from a breaking change at the binary level, where all upstream dependencies must be rebuilt to be compatible with the new Selenium binaries. Therefore, it is considered a “minor” breaking change. All right? Aligning the parameter name in your code (which uses the `parameter: value` syntax) is not a big deal, especially since it is highlighted by the IDE.

Selenium project tries to deprecate old API and suggests to use new one. Particularly in this case it was impossible, the API is still the same (API at binary level).

Given that Selenium project doesn't follow to SemVer schema, it is OK to break something... as has happened many times before through deprecation notifications. New minor versions continue to be released with such changes.

In my opinion, we should continue to “break what we want with deprecation,” or alternatively, “break what we want with a notice in the changelog/release notes.” In this scenario, a “notice in the changelog” would suffice.
