### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by yogendrakan** [SeleniumHQ/selenium#13631]
### What happened?

I am using selenium 4.18.1 version in my .net 7 web api, it is working fine when I run from visual studio but I published project in IIS server, Selenium raise an error like "Cannot start the driver service on
[http://localhost:port number]"

### How can we reproduce the issue?

```shell
Just publish the web api in IIS server.
```

### Relevant log output

```shell
Cannot start the driver service on http://localhost:8009/
```

### Operating System

Windows 10

### Selenium version

4.18.1

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver

**Comment by diemol** [comment]
Do you know if this worked before? What is the use case? I want to understand better because I need to know where the browser should be launched when you are published to an IIS.

**Comment by yogendrakan** [comment]
hi diemol,
IIS server is my local host, I have create Asp.net core web api and .net framework is 7.0 , within API call and published on my system IIS server. I want to open Selenium browser in my local host, that is my system., Chrome browser is already installed my system and also when I run the web api from visual studio , Selenium browser is open but after publish on IIS server IIS server is not opening due to error  "Cannot start the driver service on
[http://localhost:port number]"

**Comment by diemol** [comment]
From your answer, I understand that this has not worked before, and you are trying to figure out how to do this. 

I assume that is not trivial to achieve since all processes run inside IIS. Somehow, you want to launch a browser inside that web server process. I'm sorry, I cannot give hints on how that can be done.

If you want to run tests on a remote server, we recommend https://www.selenium.dev/documentation/grid/.
