### ISSUE TITLE
Enabled:True/False is not working (selenium)

### ISSUE THREAD

**Issue by MeghaPrakash1992** [SeleniumHQ/selenium#1377]
I am supposed to check if a link is enabled or not for a web portal. I am using 'enabled:true' for this but it is not working. Even for the links that are disabled and made as plain texts, enabled:true is returning true and the test is 'passed' which should have been the opposite.

How to fix this?

**Comment by stupidnetizen** [comment]
I think Selenium would verify with the value of disabled attribute. However, I am not sure whether disabled:true stands valid for anchors. May be you need to choose another attribute to verify disabled anchors. Did you try disabled: disabled ??

**Comment by ddavison** [comment]
according to the [W3C](http://www.w3.org/TR/html5/disabled-elements.html), links are excluded from elements that can be disabled.  Buttons are able to be disabled, but not links.

In order to test that links are disabled, you cannot use `isEnabled()` as this, by requirement, only checks the `disabled` attribute on input elements, buttons, textareas and the like.

If you need to validate that the link is enabled, then you need to find another way.. it most likely is defined by a class, so you should check that the element exists with a class `disabled`.  It's your responsibility to see which class enables that behavior.

Please see this as a reference #1348  A similar discussion had taken place.

**Comment by MeghaPrakash1992** [comment]
case "enabled":	Func_FindObj(ORvalname, ORvalue);
				boolval = elem.isEnabled();
				System.out.println(boolval);
				actval = boolval.toString();
				System.out.println(actval);
				break;
I am doing keyword driven automation testing using selenium open to test frame work. I am now to this whole thing. I am supposed to check if the link is enabled for a particular kind of user or not. I am using this method to check that. But 'boolval' always returns 'true' for any given link no matter it is enabled or disabled. Is there any other way to check if the link is enabled. If not in-built can we write our own method to check?

**Comment by MeghaPrakash1992** [comment]
Disabled is not there. And the only difference between the enabled and disabled element is the presence of 'href' in the anchor tag and the class.

**Comment by MeghaPrakash1992** [comment]
@stupidnetizen : I checked... Its not there in my framework so Disabled:disabled doesn't work. If you are saying that there is an inbuilt function to check if the link is disabled: No, it is not there.
