### ISSUE TITLE
[🚀 Feature]: Make selenium-manager optional, provided that you can manage it yourself

### ISSUE THREAD

**Issue by grepwood** [SeleniumHQ/selenium#13806]
### Feature and motivation

For the longest time since I started using Selenium back in 2017, I didn't need this kind of feature and now I find myself forced to use it in order to continue using up-to-date Selenium. I can't find any guides online to show me how I can go about using Selenium 4.18 without selenium-manager. I know what browser goes with what driver, thank you very much, I'm not silly enough to mix msedge with geckodriver. I know what paths do all the tools and dependencies have. I appreciate the guardrails, but I really have no need for this kind of assistance.

Also, I'm using Selenium in a workplace where we can't use programs written in Rust. I want everyone to understand that this isn't my decision and it's non-negotiable with people who make these kinds of decisions at my workplace.

### Usage example

I would use Selenium like I have so far. Just without the manager, because
1. I don't need it for my personal projects
2. Even if I can smuggle a 100% statically linked Rust binary into my workplace, then it's going to introduce an unsustainable build dependency and if security finds out it's over

**Comment by diemol** [comment]
Selenium Manager is optional already. If you create the driver service yourself, it won't be used. However, we are still deciding on the behavior for Selenium 5.

> I know what browser goes with what driver, thank you very much, I'm not silly enough to mix msedge with geckodriver.

That is great! However, many users do not want to spend time managing drivers and browsers. Selenium Manager was created because the community asked for a tool like this one.

The binary has been embedded in the language bindings since version 4.6.0, and we will keep it this way as it simplifies usage and distribution. If you want to talk more about this topic, join us in our [Slack](https://www.selenium.dev/support/#ChatRoom) and we will be happy to learn more from your use case.

**Comment by kool79** [comment]
IMHO we should have a simple way to disable Selenium Manager, without creation of custom driver services and playing with different combinations of properties. 
Even now, when SM is in beta - there are issues which can silently affect test execution because of bugs in SM.
Example is here: #13352. As a user I expect to have an error when something is wrong with path to browser binaries, but instead I just got some unknown browser version

@grepwood 
  If you are on Java, seems we can disable Selenium Manager without custom driver service.
  You need to System.setProperty(...) with a driver location (`webdriver.chrome.driver`, `webdriver.ie.driver`, `webdriver.gecko.driver`, `webdriver.edge.driver`, `webdriver.safari.driver`, `webdriver.tp.safari.driver`).

**Comment by grepwood** [comment]
@kool79 I'm on Python and I still have no clue how to deal with this. One year Selenium works, next year it stops. My code that starts up Selenium is here:
- https://github.com/grepwood/pytaku/blob/af546138e6ee2960f086c9576df17d56c0e452af/browser/engine.py#L34-L43 we rely on Linux having a package manager, it's other systems that have to adjust and provision a webdriver
- https://github.com/grepwood/pytaku/blob/af546138e6ee2960f086c9576df17d56c0e452af/browser/supplement_webdriver.py this class detects the supported browsers and if we are not running on Linux, it will assume that the user has no package manager to install webdriver with, so the class will try to find a compatible webdriver version and download it

I wrote this code in March 2022 up Dec 2022 and it worked flawless back then :/
