### ISSUE TITLE
High CPU usage with chromedriver 124.0.6367.78 and selenium-java 4.20.0[🐛 Bug]: 

### ISSUE THREAD

**Issue by dmidura** [SeleniumHQ/selenium#13872]
### What happened?

I am seeing very high CPU usage when running automation. The Chrome processes are not quitting after the automation directs the driver to quit. Instead, they collect in the background and just add to the CPU load. This just started when chrome upgraded to 124.0.6367.79. I was running selenium-java 4.19.1, but I've tried with 4.20.0 and haven't seen an improvement.

I am on chromedriver 124.0.6367.79
I am using selenium-java 4.20.0 
I am running in a Windows environment.

Can someone please tell me how to reduce the CPU load clocking for my automation?

### How can we reproduce the issue?

```shell
This is my driver initialization:
        
ChromeOptions chromeOpts = new ChromeOptions();
        chromeOpts.addArguments("--window-size=1920,1080");
        chromeOpts.addArguments("--disable-gpu");
        chromeOpts.addArguments("enable-automation");
        chromeOpts.addArguments("--no-sandbox");
        chromeOpts.addArguments("--disable-infobars");
        chromeOpts.addArguments("--disable-dev-shm-usage");
        chromeOpts.addArguments("--disable-browser-side-navigation");
        chromeOpts.addArguments("--disable-gpu");
        chromeOpts.addArguments("disable-features=NetworkService");
        chromeOpts.addArguments("--disable-extensions");
        chromeOpts.addArguments("--dns-prefetch-disable");
        chromeOpts.addArguments("--remote-allow-origins=*");
        chromeOpts.setExperimentalOption("prefs", setDownloadPath());
        chromeOpts.setPageLoadStrategy(PageLoadStrategy.NORMAL);

        LoggingPreferences logPrefs = new LoggingPreferences();
        logPrefs.enable(LogType.PERFORMANCE, Level.ALL);
        chromeOpts.setCapability("goog:loggingPrefs", logPrefs);

WebDriver driver = new ChromeDriver(chromeOpts);

// do automation with the driver

driver.quit();
```

### Relevant log output

```shell
I can only see this is happening by looking at the running processes in my windows task manager.
```

### Operating System

Windows 11 Enterprise

### Selenium version

4.19.1, 4.20.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 124.0.6367.79 

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 124.0.6367.78

### Are you using Selenium Grid?

no

**Comment by RodaxQA** [comment]
I've had the exact same problem since yesterday
Multiple running chrome processes and remaining "chromedriver.exe" after some test executions
My laptop was slower and slower and I noticed this
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4744

**Comment by diemol** [comment]
Yes, this has been [reported](https://bugs.chromium.org/p/chromedriver/issues/detail?id=4744). Unfortunately, we cannot fix this issue as it is in Chrome.

**Comment by DeepakSahu-Engineer** [comment]
I have been facing this issue since last week .. This is not only about Chrome 124 it is also Happening with firefox and edge browser .

**Comment by vinoth959** [comment]
Same issue i'm facing too.. first iteration starts fine and after the browser closes and restart then issue is back

**Comment by balivadas** [comment]
Added a comment in the chrome driver bugs link https://bugs.chromium.org/p/chromedriver/issues/detail?id=4744

"The issue still exists with chromedriver version 124.0.6367.155 and chrome browser version 124.0.6367.119.
After testcase is run, and completed (chrome driver is quit), the Google Chrome process still exists with 2 threads running consuming on an average 10% of CPU utilization.
If i run 10 testcases, it means 100% CPU utilization and this is making the system very slow.

As the original author recommended below 2 options
IMPORTANT TIPS:
  1) This is related to "--no-sandbox" browser argument. As soon as I remove this argument, I don't see "zombie processes".
  2) If I really want to use "--no-sandbox" argument, and I add "--remote-debugging-pipe", then the issue is not reproducible anymore - no "zombie" processes.

Nothing works for us.

Attached is the screenshot which shows when a simple testcase to open chrome launch [google.com](https://google.com/) and close it is run 10 times and the processes still exists even after testcases are completed and browsers are closed by chrome driver.

Note: during execution, if I manually close the browser, no more zombie processes left."
![2](https://github.com/SeleniumHQ/selenium/assets/144462165/e059492d-9c97-4800-a041-b2ea6b4d4ad9)

**Comment by RileyXX** [comment]
You need to call `driver.close()` before `driver.quit()` otherwise you get lingering chrome processes with high resource usage. This is an issue with recent chrome versions (124+).

**Comment by GerbenArkesteijn** [comment]
I was having the same problem.

As a possible work around you could comment out or remove chromeOpts.addArguments("--no-sandbox"); in your driver initialization. For me it reduced the CPU load.
