### ISSUE TITLE
NoSuchframeException in mozilla firefox

### ISSUE THREAD

**Issue by Shru123** [SeleniumHQ/selenium#1397]
<head>
   <frameset border="0" rows="100%,*">
      <frame src="/WmRoot/index.dsp">
         <html>
            <head>
              <frameset frameborder="0" spacing="0" framespacing="0" border="0" rows="55,*">
               <frame noresize="" scrolling="no" name="topmenu" border="0" marginheight="0"                 marginwidth="0" src="top.dsp">
            <frameset frameborder="0" spacing="0" framespacing="0" border="0" cols="190,*">
            <frame noresize="" scrolling="yes" name="menu" marginheight="0" marginwidth="0"          src="menu.dsp">
<html>
</frame>
<frame name="body" marginheight="0" marginwidth="0" src="stats-general.dsp">
</frameset>
</frameset>
<noframes> 

I have used driver.switchto.frame("menu") ...always i get nosuchframeexception in mozilla firefox.

I have used to find the number of frameset :driver.findelement(by.tagname("frameset")) .. when i use this i get only one frameset 

i have used driver.switchto.dafult content also to swtch to frames .. but nothing is working for me

Can any one please tell me how to find the frame("menu")  and inside that i have to click on link.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by Shru123** [comment]
Hi,

I got solved the above exception 'No such frame exception'.

I was not able to locate the frames by directly swicting to particular
frame , as i was having nested frames.

so i used getcurenturl() inbetween , than i was able to locate the frames
and the above exception got resolved.

Thanks.

regards,
Shruti P.
