### ISSUE TITLE
How to update the Firefox WebDriver? The WebDriver is disabled by latest firefox.

### ISSUE THREAD

**Issue by richardxiang** [SeleniumHQ/selenium#1410]
![screen shot 2015-12-21 at 12 05 35 pm](https://cloud.githubusercontent.com/assets/4313040/11959061/65f7f204-a899-11e5-8e83-85168fb96158.png)

My Firefox WebDriver suddenly stopped working after updating firefox to 43.0.1 (See attached screenshot). I tried to disable the xpinstall.signature.required in about:config but the WebDriver still been disabled in the new session when running my automation.

I had to manually install the old version 41.0 of firefox to continually use the WebDriver 2.47.01. Is there any way , steps to update my existing WebDriver to the latest?

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
