### ISSUE TITLE
[🚀 Feature]: WebDriver-BiDi - Browsing Context to support Csharp

### ISSUE THREAD

**Issue by sooraj171** [SeleniumHQ/selenium#14126]
### Feature and motivation

Please help by adding support for Chsap as well for the WebDriver-BiDi - Browsing Context 

### Usage example

Not able to use the WebDriver-BiDi - Browsing Context while using Csharp language.

**Comment by titusfortner** [comment]
I implemented this #14052 which includes some browser context pieces:
It uses https://www.nuget.org/packages/WebDriverBiDi

It's on hold because the WebDriverBiDi package might be re-implementing away from using Events, and I don't want to invest any more time without knowing what it will look like, but if you need something available now, you can use that package.

I'm closing this issue because we are not using GitHub issues to track each module in each language, but we're working it.
