### ISSUE TITLE
[🚀 Feature]: [java] BiDi Add an ability to add headers in BeforeRequestSent 

### ISSUE THREAD

**Issue by kasprzakdanielt** [SeleniumHQ/selenium#14137]
### Feature and motivation

Since we have the ability to intercept requests before they are sent. Would be useful to add/remove headers.

### Usage example

Inside onBeforeRequestSent I would like to be able to modify request headers.
```
          try (Network network = new Network(driver)) {
            CompletableFuture<BeforeRequestSent> future = new CompletableFuture<>();
            network.onBeforeRequestSent(future::complete);
            driver.get("https://www.selenium.dev/selenium/web/bidi/logEntryAdded.html");

            BeforeRequestSent requestSent = future.get(5, TimeUnit.SECONDS);
        }

```

**Comment by pujagani** [comment]
Hey! You can already do this in Java. Refer https://github.com/SeleniumHQ/selenium/blob/trunk/java/test/org/openqa/selenium/bidi/network/NetworkCommandsTest.java#L81 The continue request parameters has more parameters that you can set. Ensure it is supported by the browser under test though, since the BiDi is work in progress. Refer https://wpt.fyi/results/webdriver/tests/bidi/network/continue_request?label=experimental&label=master&aligned.
