### ISSUE TITLE
[🐛 Bug]: Use "GetScreenshot" method after expand combobox, it is collapsed. 

### ISSUE THREAD

**Issue by CodyDeng614** [SeleniumHQ/selenium#14136]
### What happened?

We want to perform these actions: expand a combobox by clicking it, then call "GetScreenshot". After that select a item. But it is collapsed. 

We cannot use "Class Select" provided by selenium. 
[UnitTest.zip](https://github.com/user-attachments/files/15833537/UnitTest.zip)

### How can we reproduce the issue?

```shell
Have attached a demo project, you can run it. After run line 56, the issue can be reproduced.
```

### Relevant log output

```shell
null
```

### Operating System

Windows 11

### Selenium version

C# 4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 125

### What are the browser driver(s) and version(s) where you see this issue?

125, see attachment 

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
We don't support old versions of Selenium. You will need to upgrade first and provide the code to reproduce the issue with the latest version.

**Comment by CodyDeng614** [comment]
[UnitTest.zip](https://github.com/user-attachments/files/15860747/UnitTest.zip)
Have attached project with newest version webdriver.

**Comment by titusfortner** [comment]
This action is guided by the drivers, and since neither Chrome nor Firefox support it, I believe it is working as intended, but you can raise an issue with them and see what they say.

Also, Net Framework 4.5 is no longer supported now that we target net standard 2.

Select class should still work to get the list of options since it is select/options classes
