### ISSUE TITLE
[🚀 Feature]: is it possible to add getnodeUrl() similar to getsessionId

### ISSUE THREAD

**Issue by krishtoautomate** [SeleniumHQ/selenium#14294]
### Feature and motivation

is it possible to add getnodeUrl() similar to getsessionId.

This helps to find the session and where and which node is it connected to using code/script.

### Usage example

similar to getSessionId printed in report, we can also print nodeUrl, using it, we can track node/machine and help to debug tests/defects that can be reproduced only on certain nodes.

**Comment by diemol** [comment]
This is very tricky and won't cover most cases in a usable way. 

Not everyone uses Grid. If they use something like Selenoid or a cloud provider, this method will not provide helpful information.

If you are using Selenium Grid, what happens if you are using Kubernetes and some autoscaling script? Even if you get the Node URL, you cannot debug it because the Node will be down at the end of the execution. Which URL should be reported if you have a standard Grid with a complex typology? 

I recommend you poll the `/status` endpoint, match the session with the Node, and save it. Or use the built in observability, and send the information to any given tool. This will allow you to debug your issues more thoroughly, without code changes.

https://www.selenium.dev/documentation/grid/advanced_features/observability/

**Comment by krishtoautomate** [comment]
I used graphql and filtered node by matching sessionId.
thanks
