### ISSUE TITLE
[🐛 Bug]:  Headless Mode Results in White Screen in Selenium [C#]

### ISSUE THREAD

**Issue by serizava01** [SeleniumHQ/selenium#14544]
### What happened?

I have encountered an issue while using Selenium with the headless argument. When running the browser in headless mode, the page renders as a blank (white) screen, even though the site works fine when running in non-headless mode. The page appears to load successfully (based on network logs and console messages), but no content is visible.

Steps to Reproduce:

Set up a Selenium WebDriver (Chrome) with the headless option enabled.
Navigate to a webpage that renders correctly in non-headless mode.
Observe that the content does not display, and the screen remains white in headless mode.
Expected Behavior: The page should render as it does in non-headless mode, displaying the full content.

Actual Behavior: The page appears as a blank white screen

Thank you!
![สกรีนช็อต 2024-09-27 164412](https://github.com/user-attachments/assets/1c4a9276-7117-41eb-ab79-d21f479d20f8)

### How can we reproduce the issue?

```shell
ChromeOptions options = new ChromeOptions();
            if (!checkBox1.Checked)
            {
                options.AddArgument("--headless");  
                options.AddArgument("window-size=1920x1080");
               
               
            }
            ChromeDriver driver = new ChromeDriver(options);
            driver.Navigate().GoToUrl("https://www.google.com/");
```

### Relevant log output

```shell
Starting ChromeDriver 129.0.6668.70 (df87d5cf12b1397be7495a04cab2db6239b227a8-refs/branch-heads/6668@{#1420}) on port 58239
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully on port 58239.

DevTools listening on ws://127.0.0.1:58242/devtools/browser/f686c0cd-e61e-46c1-8192-d5882dbf1477
```

### Operating System

11 Pro

### Selenium version

4.25.0

### What are the browser(s) and version(s) where you see this issue?

129.0.6668.70

### What are the browser driver(s) and version(s) where you see this issue?

Latest version comes with selenium

### Are you using Selenium Grid?

No

**Comment by Skryppy** [comment]
change 
`options.AddArgument("--headless")`
on
`options.AddArgument("--headless=old")`

**Comment by khxql** [comment]
Depending on the [new headless mode](https://developer.chrome.com/docs/chromium/headless), you can now use `--headless=old` or `headless=new`, in your case you should use the old method, but Selenium should make it more compatible so that it detect when to use `--headless`, `--headless=old`, or `--headless=new`. Because me myself I am not sure when to use these in a project I want to publish and it should be compatible.

**Comment by khxql** [comment]
Depending on the [new headless mode](https://developer.chrome.com/docs/chromium/headless), now you can use `--headless=old`, but Selenium should make it more compatible so that it detect when to use `--headless` or `--headless=old`. Because me myself I am not sure when to use these in a project I want to publish soon and it should be compatible.

I am confused of what versions of Selenium and Chrome the `--headless` or `--headless=old` should be used, also be sure that only the new headless mode will be used in upcoming updates of Chrome depending on that they say:
![image_2024-10-08_220726349](https://github.com/user-attachments/assets/0003d4e5-ab0b-498d-a686-79bdb0a1064e)

## *Purpose of this*
![image](https://github.com/user-attachments/assets/93a43838-a198-4b69-a927-f30441c254f2)

**Comment by serizava01** [comment]
Thanks everyone I fixed it <3

**Comment by rickeho** [comment]
Did you fix it by using "--headless=old" instead? @serizava01

**Comment by serizava01** [comment]
> Did you fix it by using "--headless=old" instead? @serizava01

Yes
