### ISSUE TITLE
Unable to scroll the page in an android application

### ISSUE THREAD

**Issue by sanatzzz** [SeleniumHQ/selenium#1474]
In the application in which I am testing I need to scroll the page to a particular element. So,we tried using the following 
D8.scrollTo("XXXX");
D8.findElement(By.name("XXXXXX")); 
but this works only when we use AndroidDriver. The problem is that in the app on which I'm performing my testing I need to switch from mobile to portal and portal to mobile in the same test case. So, for performing portal operations I should use RemoteWebDriver. So, please provide a solution to use scroll functionality in my testing without using AndroidDriver.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
