### ISSUE TITLE
When trying to output a window handle after a new window and alert, webdriver hangs and freezes.

### ISSUE THREAD

**Issue by indpyamamoto2403** [SeleniumHQ/selenium#14795]
### What happened?

1.Open a new window.
2.Outputs an alert.
3.Outputs the window handle.

Normally, this would return an error due to alert being active, but in this case it freezes and further operations become impossible.

Error handling is difficult, so we would appreciate it if you could address this issue.

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.common.alert import Alert
from selenium.webdriver.chrome.service import Service
import time
# Initialize the Chrome driver
driver = webdriver.Chrome()

# Open Google in the first window
driver.get("https://www.google.com")

# Open a new window and switch to it
driver.execute_script("window.open('');")

# driver.switch_to.window(driver.window_handles[1])

# Open Google in the new window
driver.get("https://www.google.com")

# Display an alert
alert = Alert(driver)
alert_text = "This is an alert"
driver.execute_script(f"alert('{alert_text}');")
print(1)
# Print the window handles
time.sleep(5)
print(driver.window_handles)
print(2)
# Close the driver after a short delay
time.sleep(5)
driver.quit()
```

### Relevant log output

```shell
1
```

### Operating System

Windows

### Selenium version

4.22

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver

**Comment by navin772** [comment]
Hi @indpyamamoto2403 I am getting the list of window handles even without `time.sleep()` statements:

```
Start of window handles
['7C3884E7FAA563CC45F8E55D4DFB77FD', 'FC87A70BD374A91F1BF25660EAAD95EC']
End of window handles
```

I am on macOS.

**Comment by indpyamamoto2403** [comment]
@navin772 Thank you for your comment!
Sorry, I pasted the wrong code earlier, so I’ve edited it.

Please try this corrected code ↓

```python
from selenium import webdriver
from selenium.webdriver.common.alert import Alert
from selenium.webdriver.chrome.service import Service
import time
# Initialize the Chrome driver
driver = webdriver.Chrome()

# Open Google in the first window
driver.get("https://www.google.com")

# Open a new window and switch to it
driver.execute_script("window.open('');")

# driver.switch_to.window(driver.window_handles[1])

# Open Google in the new window
driver.get("https://www.google.com")

# Display an alert
alert = Alert(driver)
alert_text = "This is an alert"
driver.execute_script(f"alert('{alert_text}');")
print(1)
# Print the window handles
time.sleep(5)
print(driver.window_handles)
print(2)
# Close the driver after a short delay
time.sleep(5)
driver.quit()
```

#console

```
1
```

but when accepting alert manually, program restarted ... 

```
1
['4A69201C7EF3E6DB2EEA2836F04248E8', 'CC9AA63A759B44E475EBB2CA1250B3E5']
2
```

**Comment by navin772** [comment]
@indpyamamoto2403 the issue is reproducible with the new code. This can be mitigated by shifting to the required `window_handle` or handling the alerts better, something like this:
```py
alert = driver.switch_to.alert
alert.accept()
```
and then printing the `window_handles`. Basically, this should be resolved at the user's end by handling the alerts better.


> Normally, this would return an error due to alert being active

This is applicable if we are triggering an alert and then trying to switch to another window (while the alert is still active). 
In the current script we are opening a new window and then triggering an alert (which is inside the 0th window since we didn't switched the `window_handle`, so it is expected.

Let me know if I am missing something here!

**Comment by indpyamamoto2403** [comment]
thank you for your comment!

As mentioned in the provided code, I believe it can be handled either by processing the alert or by switching the window handle. However, the fact that the process freezes in certain cases seems challenging from an error-handling perspective.

Is there any way to address this in the specifications, or is it something the user should be mindful of?

**Comment by navin772** [comment]
@indpyamamoto2403 As per - https://www.w3.org/TR/webdriver/#user-prompts, alerts need to handled on the user side and I don't think it will be possible to make changes to Selenium since it follows the W3C specifications.

You can use [WebDriverWaits](https://www.selenium.dev/documentation/webdriver/waits/) and proper Alert handling per window to mitigate this problem.

**Comment by indpyamamoto2403** [comment]
I understood that the alert should be handled on the user's side.
thank you for comment!
