### ISSUE TITLE
How to speed up voice in google translate with vba

### ISSUE THREAD

**Issue by Nelsonlam** [SeleniumHQ/selenium#1502]
Please, I'm trying to speed up the voice of the site https://translate.google.com in vba 2003. When I click the first time in the translation micorfone is 

at normal speed, and the second time is at on reduced speed, however we need to 
control the speed of speech to be able to put on my desired speed, which is faster. What I've done so far is:

Public Sub good()

Dim driver As New SeleniumWrapper.WebDriver
Dim Waiter As New Waiter
Dim keys As New SeleniumWrapper.keys

driver.Start "chrome", "https://translate.google.com"
driver.Open "/"

driver.Type "name=text", "good morning"
driver.Click "id=gt-res-listen"

End Sub

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
