### ISSUE TITLE
Not able to launch the Samsung mobile default browser

### ISSUE THREAD

**Issue by RavindraSHirandagi** [SeleniumHQ/selenium#1503]
Hi, 
i am able to launch and work with mobile chrome browser using CapabilityType.BROWSER_NAME,

but not able to launch default browser of samsung mobile,

please let me know where all and while files need to modify

**Comment by lukeis** [comment]
you likely won't be able to... You could try to use Selendroid, which presents an app with just an embedded webview or as you're already doing use chrome.

Otherwise you can try to see if the appium project has anything that could driver the default browser (but last I knew, you couldn't really do it well).

And if you haven't noticed with the names of the other projects I mentioned... this issue has nothing to do with this project (other than it's the provider of the WebDriver api).
