### ISSUE TITLE
[JAVA] Can't move in context menu through keyboard - Only in Chrome

### ISSUE THREAD

**Issue by Costantino-Grasso** [SeleniumHQ/selenium#1506]
I'm facing an issue in Chrome 47, using Selenium (WebDriver) 2.48.2, ChromeDriver 2.20.353145, and last version of Java as programming language. I couldn't find any solutions online. I need to open the "right click menu of browser" (or context click menu) from an input and I could do this using this code:

<code>new Actions(driverExample).contextClick(inputExample).build().perform();</code>

So the next step: select an option from it. I searched online and it seemed simple, but it's not. I didn't try on others browsers, but I always saw online that many people did this in Firefox and Internet Explorer using something like:

<code>
new Actions(driverExample).contextClick(inputExample).sendKeys(Keys.ARROW_UP).sendKeys(Keys.ARROW_UP).sendKeys(Keys.RETURN).build().perform();
</code>

In this situation I put two "arrow up" and one "enter", because I have to select the second option from the bottom. Anyway, this seems to work for people in Firefox and Internet Explorer, but not on Chrome and I also saw few discussions about this problem without solution. Thanks in advance.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
