### ISSUE TITLE
mouseover issue on firefox

### ISSUE THREAD

**Issue by zzhengjian** [SeleniumHQ/selenium#1540]
I have a scenario that need to loop for mouseovering on an webelement and click on other that appears with mouseover, but when it loops about several times(would be any times, but try loop more to reproduce this issue), the moveTo function doesn't work properly, I have to physically trigger a mouse move to make moveTo function work as expected again. Anyone knows how does this happen?

I was using java + selenium stand-alone 2.48.2, firefox version 38.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
