### ISSUE TITLE
WebDriverException: Session was terminated due to TIMEOUT. Grid v2.50.0

### ISSUE THREAD

**Issue by enivid** [SeleniumHQ/selenium#1557]
I upgraded my grid from v2.48.2 to v2.50.0 and now 50% of my tests will get the TIMEOUT error. This is happening on Linux with FF. I have not tried other browsers yet.

I also noticed that if you set the "timeout" option in your node.json file, it gets ignored. Also tried to pass it in through the command line and it was also ignored. This works perfectly fine in v2.48.2.

**Comment by lindavz28** [comment]
:+1:  We've just noticed encountered this as well. Bug from 2.49.0 possibly re-introduced?

**Comment by Dillenger69** [comment]
Same happens to me in both Firefox and Chrome. Had to revert to 2.47.1 and Firefox 41 to get my tests to run.

**Comment by nixsec** [comment]
We've also ran into this issue and had to revert to 2.48.x

**Comment by lukeis** [comment]
2.50.1 has been released

**Comment by lindavz28** [comment]
@lukeis :+1:  Thanks for that!

**Comment by lukeis** [comment]
going to mark this issue closed/fixed. Feel free to comment if that's not the case and you have steps to reproduce any continued error.

**Comment by bizmate** [comment]
i have this problem in both 2.52 and 2.53. Using the docker images at https://hub.docker.com/r/selenium/hub/tags/

Error example

[2016-09-07 23:20:01] app.CRITICAL: Crawler: WebDriverException  failed to fetch url due to message: Session [db903e26-4268-45d9-986c-0aced411ef6f] was terminated due to TIMEOUT  
[2016-09-07 23:20:01] app.CRITICAL: Crawler: WebDriverException  trace: #0 /var/www/sitecrawler/symfony3/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php(287): Facebook\WebDriver\Exception\WebDriverException::throwException(13, 'Session [db903e...', Array) #1 /var/www/sitecrawler/symfony3/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php(508): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand)) #2 /var/www/sitecrawler/symfony3/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php(187): Facebook\WebDriver\Remote\RemoteWebDriver->execute('get', Array) #3 /var/www/sitecrawler/symfony3/src/Bizmate/SiteCrawlerBundle/Service/Crawler/EmailCrawler.php(208): Facebook\WebDriver\Remote\RemoteWebDriver->get('http://andressa...') ...

I have the problem only when using Firefox apparently

$this->driver = RemoteWebDriver::create($host, DesiredCapabilities::firefox(), 3000, 25000);

Any clues? is this just a firefox problem?

**Comment by rbenitez** [comment]
We have the same problem with Firefox and Chrome. We are using selenium-java 3.0.0-beta3. 

Thanks.

**Comment by selenareneephillips** [comment]
I am having this with 2.53.1, 2.53.0, 2.52.0, 2.51.0.

**Comment by ameyms** [comment]
I am seeing this with 2.43.1, 2.52.0, 2.51.0 & 2.53.0.
Seems to be timing out on invoking `addCookie` and `deleteAllCookies`.

**Comment by Vitkyk** [comment]
I am having it in Grid Console v. 3.0.1.

**Comment by essamzaroura** [comment]
how i can Avoid this problem ?
org.openqa.selenium.WebDriverException: Session [1be27502-b50c-4ccf-9788-753e86300165] was terminated due to TIMEOUT
Command duration or timeout: 54 milliseconds

**Comment by selenareneephillips** [comment]
@essamzaroura 

I followed the suggestion in the accepted answer to this question. I never saw the problem again after I did it. I am using selenium 2.53.1:

https://stackoverflow.com/questions/39798340/selenium-grid-session-terminated-due-to-timeout-after-less-then-100-milliseco

**Comment by doomsbuster** [comment]
I am facing the same issue with Firefox 45 on Linux Rhel 7. At this point I have tried following versions of Selenium 2.47.1 and 2.53.0, on Docker Containers, and they both fail. I have tried several versions of browsers between Firefox 38 and 52. 
I set the `timeout` and `browserTimeout` in my `config.json` which i think was simply ignored.

Is there a solution for this?

```
Exception in thread "main" org.openqa.selenium.WebDriverException: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
Command duration or timeout: 30.01 seconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: '', ip: ', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_25'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=45.7.0, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webdriver.remote.sessionid=18ec103a-0ff5-4fdd-a97d-b243452db818, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 18ec103a-0ff5-4fdd-a97d-b243452db818
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

*config.json*

```
{
  "capabilities": [
      {
         "version":"45.7.0",
         "browserName": "firefox",
         "maxInstances": 1,
         "seleniumProtocol": "WebDriver"
      }
  ],
  "configuration": {
      "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
      "maxSession": 1,
      "port": 5555,
      "register": true,
      "registerCycle": 5000,
      "nodePolling": 5000,
      "unregisterIfStillDownAfter": 60000,
      "downPollingLimit": 2,
      "browserTimeout": 0,
      "timeout": 1800
  }
}
```

**Comment by jianhaohe** [comment]
You can try adding a parameter when starting the node container --shm-size=512m。
shm-size=512m：Docker's default shared memory, /dev/shm, is only 64m, sometimes causing chrome to crash. This parameter increases the shared memory size to 512m.*
