### ISSUE TITLE
Node die after n failed attempts to connect to hub

### ISSUE THREAD

**Issue by nnordrum** [SeleniumHQ/selenium#1573]
When running SeleniumGrid in something like Marathon on Mesos, it would be nice if the nodes would die when they are unhealthy (e.g. can't connect to the hub), so Marathon could spin up new ones.

Maybe two configuration options:
dieWhenUnhealthy
unhealthyAfterFailuresCount

or something like that.

**Comment by lukeis** [comment]
Can you elaborate the scenario more clearly?

If you have a hub and a node registers to it. If the node becomes unresponsive from the hub (the hub does a polling status check on the nodes), the hub will remove the node from it's list of available nodes.

Are you asking for the node to kill it's own process when if can't register to a hub initially? Or if a hub goes down, the node after N attempts to register? Currently it will go on forever hoping the hub comes back online:
https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/internal/utils/SelfRegisteringRemote.java#L161-L183

**Comment by nnordrum** [comment]
So image the following.
Hub (10.10.10.10:32345)
Node (10.10.10.11:32346)

Marathon needs to move Hub for whatever reason, so you then have this:
Hub (10.10.10.12:32347)
Node (10.10.10.11:32346)

Hub is empty, and Node is just orphaned there waiting forever for the Hub to come back (which it never will).

If Marathon could tell it was unhealthy, either through a failed TCP check, a provided status http status page, it would kill it and recreate another one, which would be able to lookup and find the new hub location. It would also detect the exited container and try and spin another one back up to fullfill the specified hub/node count.

Make sense?

**Comment by lukeis** [comment]
sounds like more of a bug for Marathon, to relaunch the node with the proper hub information. Otherwise how would the node know where to reconnect to?

I think that if Marathon decides to move the hub, you should keep a relationship to the nodes that were connected and destroy them too (or restart the selenium server process).

I could conceive of adding some kind of new node end point to update the hub it's pointing to. And possibly an extra configuration parameter for it to kill itself if after a configurable timeout has been reached when it can't connect back to the hub.  (Pull requests welcome :) )

**Comment by nnordrum** [comment]
> sounds like more of a bug for Marathon, to relaunch the node with the proper hub information. Otherwise how would the node know where to reconnect to?

The answer is in your question, but your missing disconnect: how does Marathon know the node _should_ reconnect? Yes, one could say, "I moved the hub, therefore, I should refresh all the nodes", but now you're pushing that intelligence back into Marathon, so what about the people running it in Aurora? Singularity? The common functionality between all these frameworks is that they will restart failed/unhealthy tasks/jobs. If you just mark the node unhealthy, or kill it, the framework will start another one, which will perform a service lookup, and connect to the new hub location.

What's the point in trying to keep container-based nodes around? They're stupid cheap to recreate, so who cares? just kill it and get a new one. I can spin up 128 nodes in <60 seconds with marathon on Mesos. If you want to keep them around, maybe include something like `com.spotify:dns` so the nodes can dynamically find the hub w/o a restart using DNS SRV records. Frankly, I think both options would be good to have.

> I think that if Marathon decides to move the hub, you should keep a relationship to the nodes that were connected and destroy them too (or restart the selenium server process).
> I could conceive of adding some kind of new node end point to update the hub it's pointing to. And possibly an extra configuration parameter for it to kill itself if after a configurable timeout has been reached when it can't connect back to the hub. (Pull requests welcome :) )

But the nodes connect to the hub, not the other way around. Is there a way to update the running nodes with a new hub location? e.g. POST /node/register?hub=123.45.67.89:12345

Here's a few examples of how Mesos frameworks deal with this issue:
[Marathon](https://mesosphere.github.io/marathon/docs/health-checks.html)
[Nomad](https://www.nomadproject.io/docs/jobspec/servicediscovery.html#check)
[Aurora](http://aurora.apache.org/documentation/latest/user-guide/#http-health-checking-and-graceful-shutdown)
[Singularity](https://github.com/HubSpot/Singularity/blob/master/Docs/reference/examples.md#basic-service-using-allocated-ports)

**Comment by lukeis** [comment]
> But the nodes connect to the hub, not the other way around.

This is not necessarily the case. You can (and I do) start up nodes agnostic of a hub. Then register the node to a hub (which one can do from a Java process running a hub or sending an http request to the hub register end point with relevant information). 

In this situation I think you should go with an approach like this, even though it's cheap to recreate nodes, why would you if it's "healthy"?

I don't personally use mesos or marathon, but I imagine that you have to have some way of knowing where the hub and nodes are? And when it changes you can execute scripts to help rectify your grid by re-registering nodes with a http request to the hub. 

Don't get me wrong, I think grid could use this enhancement :)

**Comment by nnordrum** [comment]
>  You can (and I do) start up nodes agnostic of a hub. Then register the node to a hub (which one can do from a Java process running a hub or sending an http request to the hub register end point with relevant information).

Is this documented anywhere? I've never seen this, but I also wasn't looking for it per se. It would be trivial to invert the lookup relationship to reregister nodes.

What you're describing would be called a Mesos Framework. It gets messages when things move/die/etc, so the Hub would be aware of the Nodes and send reconfiguration messages to them "automatically". That wouldn't be a bad thing to have as part of the project either, but is yet another way to set things up :)

**Comment by lukeis** [comment]
documented... hmm. The only place I know with an example of how to do the http request way is in selendroid:

http://selendroid.io/scale.html

Hopefully you can interpret that for your use case here.

**Comment by krmahadevan** [comment]
@nnordrum 

This was an interesting usecase.

Here's how you can go about solving this on your own, without requiring any changes from the Grid side by leveraging the flexibility that Grid provides to customize it.

* Build a new Servlet by extending ```org.openqa.grid.web.servlet.RegistryBasedServlet``` and within its init method, add a shutdown hook which would do the following when the JVM is exiting.
  * For each node object obtained via `getRegistry().getAllProxies()` (You can obtain its URL by invoking `org.openqa.grid.internal.RemoteProxy#getRemoteHost` ) do the following:
     * Invoke[1] and pass it the IP address of the new hub to which it is to register itself when it comes back again.
     * Invoke[2] and trigger a shutdown.


The following two servlets would need to be built (again by extending ```org.openqa.grid.web.servlet.RegistryBasedServlet```) and injected into the node level.
* [1] A servlet to which one can pass on the IP address of the new Hub, and this servlet would update the nodeConfig file with this information (The node should be brought up using a node configuration file)
* [2] A servlet which when invoked would trigger a call to `System.exit()`

In order to ensure that the node comes back on its own (assuming you don't want to employ any cron/task scheduler mechanim), you would need to build a watch dog kind of a mechanism which would be responsible for spawning the node as its child process. You can refer to this blog post of mine to learn more about this flavor of a "Self Healing Grid" https://rationaleemotions.wordpress.com/2013/01/28/building-a-self-maintaining-grid-environment/

**Comment by diemol** [comment]
Hi all,
We had a discussion if we should include this feature in Grid 4, but we concluded that a better approach is to provide a `/health` endpoint, which would be used by orchestrated environments (Mesos, Kubernetes, etc...) to verify if the container/pod should be torn down and a new one to be started.
I am closing this issue since we will provide another approach for it in Grid 4. For Grid 3.x, there is the approach that was mentioned in the previous comment.
