### ISSUE TITLE
dotnet-core Support? 

### ISSUE THREAD

**Issue by user4794170** [SeleniumHQ/selenium#1587]
Are there any plans to support Selenium for DNX/dotnet-core in the near future? 
Thanks!

**Comment by jimevans** [comment]
Define "near future." It's something we want to support, but there's been no work to enable the project's build system to produce assemblies for that platform yet.

**Comment by user4794170** [comment]
I'm working on migrating my test code to dotnet-core right now. The other two libraries that I use, xUnit and JSON.NET, are available as release candidates so I'm ready to move as soon as Selenium support becomes available.

**Comment by user4794170** [comment]
According to ApiPort CLI: 
- WebDriver 2.50.1 is 86.25% compatible with .NET Core 
- WebDriver.Support 2.50.1 is 89.84% compatible with .NET Core

ApiPort detects incompatible components and suggests alternatives when available.
- Porting: https://dotnet.github.io/porting/
- ApiPort CLI: https://github.com/Microsoft/dotnet-apiport/releases
- ApiPort Version: v1.2.1.alpha.00031
- Command Used: apiport analyze -f "<folder with both dlls>" -r html -t ".NET Core"

**Comment by jimevans** [comment]
The .NET bindings currently require too many parts of the .NET API that do not have equivalents in .NET Core. In particular, there is a dependency on `System.Drawing` which cannot be removed, because taking screenshots requires the image processing libraries available in that assembly. Additionally, since the .NET bindings must continue to support .NET 3.5, we cannot yet migrate to the portable versions of some of the API calls provided in 4.6. Until such time as we can drop support for versions of .NET below 4.6, we cannot make this migration happen in an elegant way. I'm closing this issue for now, but keep in mind that we will continue to work toward a goal of enabling the .NET bindings to work with .NET Core.

**Comment by MartinJohns** [comment]
@jimevans Since .NET Core is released now, is there any chance this could be tackled again? If there are a few features missing or if you're worried about backwards compatibility you could consider releasing two versions in the same NuGet package, one for .NET and one for .NET Core with a reduced feature set.

**Comment by MartinJohns** [comment]
@jimevans Any chance on this?

**Comment by gerryhernandez** [comment]
Even a RemoteWebDriver implementation would be a great first step.

**Comment by KevinHoward** [comment]
.NET Core System.Drawing alternative until Microsoft implements the library:
[https://www.nuget.org/packages/CoreCompat.System.Drawing](https://www.nuget.org/packages/CoreCompat.System.Drawing)

**Comment by bparvanov** [comment]
What about using SkiaSharp (https://github.com/mono/SkiaSharp) as a replacement of System.Drawing?

https://developer.xamarin.com/guides/cross-platform/drawing/

**Comment by sergey-litvinov** [comment]
Any updates in terms of .Net Core 2.0 that was released and has much bigger API coverage?

**Comment by sergey-litvinov** [comment]
Looks like work is in progress. I saw comments in other PR and 3.6 has some initial .Net Core 2.0 support
