### ISSUE TITLE
Windows >> Safari Browser >> 1.) implicit Wait stops the script to run, 2.) Script fail in the case of navigation

### ISSUE THREAD

**Issue by JaspalAujla** [SeleniumHQ/selenium#1597]
1.) If I implement implicit wait then my script get crashed. Please refer below code. The problem coming with third line of code:
DriverScript.driver=new SafariDriver();
DriverScript.driver.manage().window().maximize();
**DriverScript.driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);**

2.) Script fails when it has to handle navigation between the windows
Error coming:
**Yikes! Safari history navigation does not work. We can go forward or back, but once we do, we can no longer communicate with the page... (WARNING: The server did not provide any stacktrace information)**

I am using:
Operating System: Windows 10
Selenium version: 2.48.2
Safari Driver: 2.48.0

Thanks
Jaspal Singh Aujla
Email: jsaujla1@gmail.com
Linkedin: https://nz.linkedin.com/in/jaspalsinghaujla

**Comment by lukeis** [comment]
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.
