### ISSUE TITLE
WebdriverJS not able to find knockout binding element

### ISSUE THREAD

**Issue by RaghuTrivandrum** [SeleniumHQ/selenium#1603]
I have ojModule knockout binding in the login page.

I am trying to use driver.findElement(By.id('username')); to get the input text of login page which gets loaded by knockout binding

But it is throwing noSuchElement exception while running it.

Can someone help to test knockout bindings in WebdriverJs

**Comment by ddavison** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#bug-reports)
