### ISSUE TITLE
"spellcheck" should not be a binary attribute

### ISSUE THREAD

**Issue by kphorror** [SeleniumHQ/selenium#1605]
With the following HTML:
`<input type="text" id="myInput" spellcheck="false">`
Calling
`webDriver.findElement(By.id("myInput")).getAttribute("spellcheck")`
returns "true" instead of "false".

In fact, it returns "true" for any value of the "spellcheck" attribute, and only returns "null" when the attribute is not defined at all. This behavior is consistent with HTML5 binary attributes, but "spellcheck" is not a binary attribute. 

According to HTML5 specification: (https://www.w3.org/TR/html51/infrastructure.html#boolean-attributes)
> The spellcheck attribute is an enumerated attribute whose keywords are the empty string, true and false. The empty string and the true keyword map to the true state. The false keyword maps to the false state. In addition, there is a third state, the default state, which is the missing value default (and the invalid value default).

So, the "spellcheck" is actaully an enumerated attribute, and it does have a third state. Treating it as a binary attribute is not a good idea.

The example code comes from a real world scenario - Chrome needs 'spellcheck="false"' to disable spell-check on inputs (http://stackoverflow.com/questions/4524000/turn-off-chrome-safari-spell-checking-by-html-css)

**Comment by lukeis** [comment]
I agree there's an issue here... but the spec is a little odd here (even one section of the spellcheck is non-normative). Also the relevelant section referenced is here: https://www.w3.org/TR/html51/editing.html#spelling-and-grammar-checking

But it does say:
> The empty string and the true keyword map to the true state. The false keyword maps to the false state. In addition, there is a third state, the default state, which is the missing value default (and the invalid value default).

Which is to say, the spec doesn't directly attempt to define what default behavior is... sigh.

But we can say for certainty that spellcheck="false" should indeed return the False value here. Otherwise it seems True is appropriate for all other cases (unless a parent is set to false).

**Comment by lukeis** [comment]
just to get a feel of an understanding of the differences in response you'll see when the attribute is unset and is left to the browser default:

https://github.com/SeleniumHQ/selenium/blob/master/javascript/webdriver/test/atoms/element_test.html#L213-L219
