### ISSUE TITLE
Add list of supported web browsers or drivers in python

### ISSUE THREAD

**Issue by akki** [SeleniumHQ/selenium#1625]
As Selenium keeps on increasing the number of browsers it supports continuously (which is quite cool), it would be a really good idea to start maintaining a list of browsers that are being supported or the webdrivers that Selenium has.
This would allow apps using Selenium to always remain up-to-date with all the browsers and could save hard coding them in their own apps. For example, if they want to test an application on all browsers supported by Selenium or they want to take the browser name as a parameter from the user, it would be really helpful for them to know which browsers they can test on.
Right now, they have to get this list by trying hacks like getting all modules and removing 'common', 'remote' and 'support' from it.

Something like `SUPPORTED_BROWSERS = ['firefox', 'chrome', 'ie', 'safari']` in the \__init__ file should do the trick.
Or even better, return a list of all the browser webdriver classes like `selenium.webdriver.Firefox, selenium.webdriver.Chrome` bcoz that's what they will finally be using at the end. ;)

**Comment by lukeis** [comment]
sorry, but we won't be directly coding such a list. Mainly because this 'selenium' project does not maintain all of the drivers that exist and would rather not hold back any others. Also we technically don't 'support' some browsers that would be in that list (like chromedriver, that is done with the chromedriver team). Also there's many other drivers out there that are third party... EdgeDriver, PhantomJS, Appium, Selendroid, ios-driver (the ones I think of off the top of my head).

It's much more practical for users of the python library (or any other language) to maintain their own list of browsers they support with their automation. There are many factors involved in being able to run additional browsers that the selenium library may support that the selenium project should have no business in providing. As an example, if we were to add 'Edge' to the list, we don't automatically provision a machine running windows 10 and download the EdgeDriver executable.
