### ISSUE TITLE
Memory leak in org.openqa.selenium.io.TemporaryFilesystem

### ISSUE THREAD

**Issue by xmhubj** [SeleniumHQ/selenium#1679]
We have a long run environment to playback selenium scripts. The command to start the remote server is as the following.

java -Xdump:java:events=user -jar -Djava.util.logging.config.file=/opt/my/logging.properties /opt/my/selenium-server-standalone-reduced-2.47.1.jar -timeout 3600 -browserTimeout 3600

Find that the real memory consumption of this process keeps growing over time.

## Expected Behavior -
The real memory consumption of the selenium-server-standalone process should not grow overtime with steady load.

## Actual Behavior -
The heap dump of the selenium server process shows that the class "java.lang.ApplicationShutdownHooks", loaded by "<system class loader>", occupies 97,222,648 (93.28%) bytes.

And there are large number of org.openqa.selenium.io.TemporaryFilesystem$1 objects (159724 in my case) dominated by class "java.lang.ApplicationShutdownHooks" and keeps growing over time.

![dominator_tree](https://cloud.githubusercontent.com/assets/15373664/13215020/95602dde-d98d-11e5-9905-77eefeac5d60.jpg)

## Steps to reproduce -
No special steps. 

PS: for each test, we stop the BMP proxy and run driver.quit.

Cloud you advise how to find the root cause of this issue? Thanks.

**Comment by dr29bart** [comment]
Shutdown hooks are not deleted for some reason.

**Comment by xmhubj** [comment]
I simply took a look at the source code of class org.openqa.selenium.io.TemporaryFilesystem, only found that shutdownHooks are added and no removeShutdownHook is called.
line 62: Runtime.getRuntime().addShutdownHook(shutdownHook), 

And looks like shutdownHooks are only removed when stopping the Jetty server.
...
/**
   * Stops the Jetty server
   */
  public void stop() {
    int numTries = 0;
    Exception shutDownException = null;

    // this may be called by a shutdown hook, or it may be called at any time
    // in case it was called as an ordinary method, try to clean up the shutdown
    // hook
    try {
      if (shutDownHook != null) {
        Runtime.getRuntime().removeShutdownHook(shutDownHook);
      }
    } catch (IllegalStateException ignored) {
    } // thrown if we're shutting down; that's OK
...

Can anyone help me out. Thanks!

**Comment by krmahadevan** [comment]
@xmhubj 

This was interesting. :+1: 

Here's where I think the problem is.

The method https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/selenium/remote/server/DefaultSession.java#L87-L96 ends up calling the 1 arg static method 

```
    File tmpDir = new File(System.getProperty("java.io.tmpdir"), sessionId.toString());
    if (!tmpDir.mkdir()) {
      throw new WebDriverException("Cannot create temp directory: " + tmpDir);
    }
    TemporaryFilesystem tempFs = TemporaryFilesystem.getTmpFsBasedOn(tmpDir);
```

https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/io/TemporaryFilesystem.java#L54-L56

```
  public static TemporaryFilesystem getTmpFsBasedOn(File directory) {
    return new TemporaryFilesystem(directory);
  }
```

It may perhaps need to call https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/io/TemporaryFilesystem.java#L44-L46 

```
  public static TemporaryFilesystem getDefaultTmpFS() {
    return instance;
  }
```

But what I don't know is what would happen if there are 2 or more firefox executions happening. My guess is that its not going to be a problem because the implementation is such that the files related to a particular firefox execution are all bundled into a directory which is named after the session id and hence it shouldn't be a problem.

I think I can try raising a Pull Request which attempts at fixing the problem.

But in the meantime You might want to try the below approach to get past your issue immediately

Try building a servlet at the server end and add it up to the server (I know that this works in the grid setup but I dont know for sure if it works for the selenium server mode)

Try and implement what's documented in this link inside your servlet 
http://java.jiderhamn.se/2012/01/01/classloader-leaks-ii-find-and-work-around-unwanted-references/

Have your tests explicitly call out this servlet after it calls driver.quit

**Comment by xmhubj** [comment]
@krmahadevan Thank you so much! 

**"Try building a servlet at the server end and add it up to the server"** Did you mean adding it up to Jetty server. I'm not familiar with selenium server, do you have instruction or reference about that?

**Comment by krmahadevan** [comment]
@xmhubj 
I managed to create a demo project which not only shows you how to do this, but also can be consumed directly. Please take a look https://github.com/RationaleEmotions/grid-acolyte

Of-course I would expect it to have some glitches. If there are any, please do let me know.

**Comment by xmhubj** [comment]
@krmahadevan, Thanks for the fixing.
