### ISSUE TITLE
Unable to locate Dependency selenium-webdriver

### ISSUE THREAD

**Issue by 7654098** [SeleniumHQ/selenium#1690]
I've created ASP .Net console project in Visual Studio Code (OS X).

Then added the dependency in project.json:
`"dependencies": {
    "selenium-webdriver": "2.52.0"
},`

Run "dnu restore" and getting an error:

> Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16231
> 
> CACHE api.nuget.org/v3/index.json Restoring packages for /Users/user/Code/ConsoleApplication/project.json
> 
> GET api.nuget.org/v3-flatcontainer/selenium-webdriver/index.json
> 
> NotFound api.nuget.org/v3-flatcontainer/selenium-webdriver/index.json 2432ms
> 
> Unable to locate Dependency selenium-webdriver >= 2.52.0 Writing lock file /Users/user/Code/ConsoleApplication/project.lock.json Restore complete, 3027ms elapsed
> 
> Errors in /Users/user/Code/ConsoleApplication/project.json Unable to locate Dependency selenium-webdriver >= 2.52.0
> 
> Feeds used: https://api.nuget.org/v3-flatcontainer/

**Comment by jimevans** [comment]
The .NET bindings do not support .NET Core at this time. Moreover, it is unlikely they will be able to support that runtime in the near term, due to dependencies on .NET Framework classes that have no analogue in .NET Core. The dependency on these classes is required to continue to support .NET 3.5.

**Comment by 7654098** [comment]
Thank you for the answer!
