### ISSUE TITLE
Python binding does not handle potentially animated attributes correctly

### ISSUE THREAD

**Issue by vsajip** [SeleniumHQ/selenium#1693]
`selenium.webdriver.remote.WebElement.get_attribute` sometimes fails because the returned value from a lower level call is a dictionary. Here's the method:

```
    def get_attribute(self, name):
        """Gets the given attribute or property of the element."""
        resp = self._execute(Command.GET_ELEMENT_ATTRIBUTE, {'name': name})
        attributeValue = ''
        if resp['value'] is None:
            attributeValue = None
        else:
            attributeValue = resp['value']
            if name != 'value' and attributeValue.lower() in ('true', 'false'):
                attributeValue = attributeValue.lower()
        return attributeValue
```

When called with the `name` "href" on an `<a>` element, `resp['value']` is sometimes not a string but a dictionary, something like `{"baseVal": "foo", "animVal": "foo"}` (this is using Chrome). Calling `attributeValue.lower()` when `attributeValue` is a dictionary naturally raises `AttributeError`.

## Expected Behavior -

No `AttributeError` should be raised, and the `animVal` value should be returned as a string. Just returning the `resp['value']` would be preferable behaviour, leaving the caller to decide how to deal with unexpected return types.

## Actual Behavior -

Crashes with an `AttributeError`.

## Steps to reproduce -

Bring up any page which causes the Chrome remote driver to return a dictionary rather than a string for the `href` attribute of an `<a>` element.

**Comment by lukeis** [comment]
Can you please provide a sample page or a link to a page that has such an element

**Comment by vsajip** [comment]
Will try - not easy, as it's happening on a complex page (a dashboard) with some animation effects. The actual page can't be made public, but I'll see if I can extract a part of it that exhibits the problem.

**Comment by fpiesche** [comment]
I'm running into something that's evidently related, with string values coming out of the `self._execute` call as lists of the strings' individual characters - sadly I can't link to sample pages as the site I'm running into it on is not accessible to the public. I'm only encountering this in Chrome as well - phantomjs works fine.

To give you some extra info about the situation: I'm getting an `AttributeError` when calling `element.get_attribute('class')` - BUT:
 - only on two of the various elements on the page I'm getting the `classes` of
 - it happens *consistently* on these two elements

There's nothing odd or special about the elements as far as I can see - one of them is a `<button>`, the other an `<img>`, each with anywhere between 0 and four or five CSS `class`es assigned. Both are added to the DOM via JavaScript after the page loads (as are many of the other elements I look at in my tests).

With some pdb poking I've found that for some reason, when getting these elements' `class` attribute, `resp['value']` is a list of characters rather than a string, i.e. if the element's `class` is `myclass`, `resp['value']` is `[u'm', u'y', u'c', u'l', u'a', u's', u's']`. The `if attributeValue.lower() in ('true', 'false')` statement understandably fails with an `AttributeError` when this happens.

To further demonstrate the problem sits right out of the `self._execute` call, I've been able to fix this by monkey-patching the `get_attribute()` function with this in my test class:

```python
def get_attribute(self, name):
    """Override get_attribute function to monkeypatch webdriver with."""
    resp = self._execute(Command.GET_ELEMENT_ATTRIBUTE, {'name': name})
    attributeValue = ''
    if resp['value'] is None:
        attributeValue = None
    elif isinstance(resp['value'], list):
        attributeValue = ''.join(resp['value'])
    else:
        attributeValue = resp['value']
        if name != 'value' and attributeValue.lower() in ('true', 'false'):
            attributeValue = attributeValue.lower()
    return attributeValue

import selenium
selenium.webdriver.remote.webelement.WebElement.get_attribute = get_attribute
```

Finally I've also found a single `<input type="text">` element in the page I'm testing that returns a list of characters rather than a string when I call `element.get_attribute('value')`. Again there doesn't appear to be anything special about this element, and again it only happens on that single one and no others.

**Comment by vsajip** [comment]
Looks like something at a lower level is expecting a list when it gets a string, then iterating over that ... so it looks to me like a different issue, though in the same area of the API.

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
