### ISSUE TITLE
Safari Webdriver Hangs On Post URL When Alert Pops Up

### ISSUE THREAD

**Issue by smythey21** [SeleniumHQ/selenium#1721]
I have a selenium navigates to a specific url which causes an alert to popup. On safari, the Post URL command hangs because of the popup and does not return. 

## Expected Behavior 
After Post URL, I expect a popup to show and for the post URL command to return

## Actual Behavior 
The popup alert triggers, but the post URL command hangs so its impossible to close the popup

## Steps to reproduce  
Navigate to page with Safari Webdriver that throws an alert like ```alert("alert!")```

**Comment by titusfortner** [comment]
Safari Driver does not support alerts very well. I'm not sure what, if any, of the things discussed in [this thread](https://web.archive.org/web/20151006231111/http://code.google.com/p/selenium/issues/detail?id=3862) apply, but I believe it is as fixed as we can make it.

**Comment by lukeis** [comment]
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.

**Comment by tathanhphu** [comment]
Hi There,

I have the same issue with safari on alert box

Safari: 10
Mac: Sierra
