### ISSUE TITLE
Change User Agent and Proxy / using Python and PhantomJS

### ISSUE THREAD

**Issue by Gukki5** [SeleniumHQ/selenium#1747]
I'm trying to set my user agent... using Python and PhantomJS. Found online that this solution below used to work back around 2013, but it definitely doesn't work now..

Any ideas?

If I just ditch PhantomJS and use a different browser in a headless setup, is it possible to change the user-agent in a way similar to below?

Also I need to direct the traffic to a proxy... I assume I'd set that header similarly?

Thanks!

```
user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.57 Safari/537.36'
dcap = dict(DesiredCapabilities.PHANTOMJS)
dcap["phantomjs.page.settings.userAgent"] = user_agent
driver = webdriver.PhantomJS(desired_capabilities=dcap)
```

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
