### ISSUE TITLE
Unable to get an element via query on attribute(containing hyphens) value using an XPATH

### ISSUE THREAD

**Issue by hasanmehmood** [SeleniumHQ/selenium#1751]
Hello All,

Hope everybody is doing great. I'm facing very weird scenario in getting an element having an attribute using an XPATH. The problem is that if the attribute contains more than one Hyphens in it then Selenium is unable to find that element. I am using **Python**. And **Selenium 2.52.0**.

**Example that works fine.**

    <span data-one="containingOnlyOneHyphen"> </span>
    XPATH = '//*[@data-one="containingOnlyOneHyphen"]' (Works Completely Fine)

**Example that doesn't work.**

    <span data-one-two="containingTwoHyphen"> </span>
    XPATH = '//*[@data-one-two="containingTwoHyphen"]' (Does not work :/ )

So far my understanding with this issue is that Selenium is unable to find element based on attribute having more than 1 hyphens in it.

It would be great if you can guide me anything regarding this issue. I've almost tried everything but failed.

Thanks & kind Regards,

Hassan Mehmood

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
