### ISSUE TITLE
SeleniumServer: -browserTimeout does not take effect.

### ISSUE THREAD

**Issue by xmhubj** [SeleniumHQ/selenium#1770]
Base on the source code of org.openqa.selenium.server. From the usage below, It does provide a way to set the timeout in seconds a browser is allowed to hang.
https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/selenium/server/SeleniumServer.java#L876-L877

  public static void usage(String msg) {
    if (msg != null) {
      System.out.println(msg);
    }
    String INDENT = "  ";
    String INDENT2X = INDENT + INDENT;
    printWrappedLine("", "Usage: java -jar selenium-server.jar [-interactive] [options]\n");
    printWrappedLine(INDENT,
                     "-port <nnnn>: the port number the selenium server should use (default 4444)");
    printWrappedLine(INDENT,
                     "-timeout <nnnn>: an integer number of seconds we should allow a client to be idle");
    *printWrappedLine(INDENT,
                     "-browserTimeout <nnnn>: an integer number of seconds a browser is allowed to hang");*
    printWrappedLine(INDENT,
                     "-interactive: puts you into interactive mode.  See the tutorial for more details");
    printWrappedLine(
      INDENT,
    ...

But in the method parseLauncherOptions, it doesn't has a logic to parse -browserTiemout.
https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/selenium/server/SeleniumServer.java#L948-L1120

So when the -browserTimeout argument is parsed?

**Comment by lukeis** [comment]
this is going to be cleaned up  / reworked in selenium 3.0.

And right now i can't see any way for it to work, since as you noted it's not parsed in SeleniumServer. Although I can't imagine you really want browserTimeout, which is to say it's the timeout configuration to kill / quit a session while processing a command (example is calling driver.get(url) and the page load takes longer than the browserTimeout configured, it will then kill the session).

-timeout on the other hand is more useful (in my opinion) where it's the time between commands to the session where it will timeout and quit the session.

But as I said it'll be 'fixed' in 3.0 (see 7308f863657a9cc9225a856ac646f3974b1e8663 )

**Comment by xmhubj** [comment]
-timeout is the amounts of a session is allowed to be idle. It can't quit the active session. -browserTimeout works as a backup timeout for abnormal cases, especially when selenium run as a server with some traffic load, it can make sure there is no die browser window.

Thanks for the reply. Glad to hear that it will be reworked in 3.0.

**Comment by lukeis** [comment]
should be fixed now, please log new issues you encounter with 3.0
