### ISSUE TITLE
Feature request to provide a mechanism to enable/disable the compatibility view feature for IE11 

### ISSUE THREAD

**Issue by shelar** [SeleniumHQ/selenium#1809]
## Expected Behavior -
Need an API to change the compatibility view before opening an IE session. Is this feasible?

## Actual Behavior -
One manually configures the compatibility view on Internet Explorer on the nodes.

## Steps to reproduce -
Not applicable.

**Comment by jimevans** [comment]
One of the guiding principles of the IE driver is to make no changes to the system that could affect sessions other than the one expressly started by the driver. Since IE has no concept of user profiles, it's impossible to isolate changes like the one you're requesting to the current running session only. Thus, this type of feature would violate that principle, and will not be implemented.

**Comment by shelar** [comment]
@jimevans, Thank you very much for the clarification on this topic by sharing the IE driver principles and IE's technical consideration!
