### ISSUE TITLE
SafariDriver - sendKeys cant put negative value into number field 

### ISSUE THREAD

**Issue by smathistad** [SeleniumHQ/selenium#1816]
## Meta -
OS: OS X El Capitan
Selenium Version: 2.48
Browser: Safari
Browser Version: 9.0.1 

## Expected Behavior -
In safari browser, I am at a webpage that has an input field of type "number" with min and max values set. I am using sendKeys to attempt to put a negative number (which is greater than the minimum value) into the field.  I would expect the field to show the negative value.

## Actual Behavior -
The input field displays the number without the negative sign. In my example below, the field shows the value of 5.

## Steps to reproduce -
java code:
<code>String value = "-5";</code>
<code>String id = "myinputvalue";</code>
<code>WebElement inputElement = browser.findElement(By.id(id));</code>
<code>inputElement.clear();</code>
<code>inputElement.sendKeys(value);</code>

webpage source
<code>< input type="number" min="-10" max="10" id="myinputvalue" class="text" size="20" name="myinputvalue">
</code>

**Comment by mengbinhao** [comment]
Hi smathistad, Did you figure this problem out?

**Comment by smathistad** [comment]
Sorry for the late reply.  I ended up having to use JavaScript to inject the value directly into the field and bypass the Selenium driver.

**Comment by lukeis** [comment]
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.
