### ISSUE TITLE
How to read the WebElement object from a MapBox or Bing map

### ISSUE THREAD

**Issue by makmahesh** [SeleniumHQ/selenium#1821]
## Meta -
OS: Windows All versions
Selenium Version: 2.48.2
Browser: All Browsers
Browser Version: Latest version of Browser

## Expected Behavior -

When locating a point of a polygon in Bing map DOM should display the Matching node

## Actual Behavior -

Firebug reads the XPath but DOM is displaying 'No Matching Nodes'

## Steps to reproduce -

1. Navigate to https://www.mapbox.com/mapbox.js/example/v1.0.0/point-in-polygon/ in Firefox browser with Firebug addon

2. Locate a point in the map using Firebug, Or Inspect a element in the Map

3. Notice that XPath is displayed, but the DOM is displaying No Matching nodes.

As a result when this XPath is included in the script, Selenium is throwing No such element found exception.
![mapbox locator issue](https://cloud.githubusercontent.com/assets/10337451/13803570/a02e7dc0-eb6b-11e5-98d3-3b09c9e707d1.jpg)

**Comment by makmahesh** [comment]
Hey @jarib can you please help me out on this

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
