### ISSUE TITLE
Implement the interactions API for Safari

### ISSUE THREAD

**Issue by nalinip** [SeleniumHQ/selenium#1837]
OS: MAC 10.10
Selenium Version: 2.48.0 webdriver java
Browser: Safari
Browser Version: 8

## Expected Behavior -
Actions class drag and drop function should work in safari browser, other than safari it is working fine.

## Steps to reproduce -
I have used this script-it is working fine in FF,Chrome, IE9, IE10, IE11 but not working in safari browser

```java
WebElement hierarchyThreeElement = driver.findElement(By.xpath("//*[@id='RadPanelBar1_i0_RadTreeView2']//li[contains(.,'"+hierarchyOneText+"')]//span[text()='"+hierarchyThreeText+"']"));
SeleniumWrapper.switchToFrame(driver,rightPaneIFrame);
SeleniumWrapper.scrollToElement(driver, hierarchyThreeElement);
SeleniumWrapper.scrollToElement(driver, rowContainer);
SeleniumWrapper.waitUntilElementVisisble(driver,rowContainer,10);
actions.clickAndHold(hierarchyThreeElement).moveToElement(rowContainer).release().build().perform();
```
Thanks in Advance!

Nalini

**Comment by lmrafael** [comment]
Hey folks.

I am stuck with the **Unknown command: mouseMoveTo** error and [this archived issue](https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/4136) led me here.

I am running selenium through behat + mink, and am trying as hard as I can **not** to use JS instead of native browser interactions. I've tried to find a solution on my own but all I could fetch was that there is a need to implement the interactions API for Safari (is that right???).

Are there any other options besides using a JS workaround or not using Safari? Couldn't find any other.

If needed, I am eager to help.

Thanks in advance.

**Comment by uchuugaka** [comment]
There is one. You can synthesize a MouseEvent in JavaScript. It's not easy or obvious but I can share some code if you still need it. I found I needed this when any site used the jQuery plugin tool tipsy

**Comment by uchuugaka** [comment]
Here is some example code for a MouseEvent.
JavaScript
````
document.querySelector(yourCSSSelectorHere).dispatchEvent(
    new MouseEvent("mouseover", {
            bubbles: true, cancelable: true, view: window, 
        }
    )
);
````
In Selenium Python:
````
mouseoverJavaScriptString = """
document.querySelector(yourCSSSelectorHere).dispatchEvent(
    new MouseEvent("mouseover", {
            bubbles: true, cancelable: true, view: window, 
        }
    )
);"""
driver.execute_script(script=mouseoverJavaScriptString)
````
See MouseEvent at Mozilla Developer Network site:
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent

Arguably it's more clear than the the Actions API.
In general at this time, the synthetic MouseEvents JS API is the only way beyond basic DOM events that you will get mouse events in Safari.
KeyBoard Events will be similar. Documentation is sparse at best and Google won't find a lot easily.
In order to get more complex interactions properly and naturally, and to support interacting with JS alerts in Safari, it really requires leveraging a side app, possibly a Safari Extension Companion app (also sparsely documented and quite new). A side app would need to interact with the native AX (Accessibility) APIs to control the actual mouse and keyboard as well as with the CGEventTap API to properly capture and synthesize mouse and keyboard events at a native level. This would necessitate being added to the System Preferences > Security pane's list of apps allowed to control the system. It is a manual process to add that.

An alternative is to build a Cocoa app that uses a WebKit WebView or a WKWebView. A native app can control itself. A webview will use the same underpinnings as Safari, minus some of the Safari Cocoa UI layer. The separate pool of processes that do all of the rendering of web content are almost the exact same and can use the same set of shared cookies. The wealth of security and performance architectural separations in Safari make it quite a different challenge.

**Comment by lukeis** [comment]
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.
