### ISSUE TITLE
Add an error for Proxy Server is refusing connections

### ISSUE THREAD

**Issue by mushi1996** [SeleniumHQ/selenium#1849]
if you attempt to launch firefox using selenium with a proxy that refuses connections there is no error returned so I cant catch it.

A work around is to check the value of the id="errorTitleText" however I really wish there was a way to catch it.

I am using the latest version of firefox, selenium and python.

**Comment by lukeis** [comment]
much like how selenium doesn't error if it encounters a 500 or 404 page, we also can't error on a connection reset or 403 due to a proxy being down or misconfigured. If you know this is something common for your setup, then continuing with your workaround to check that the proxy is / isn't down is what would be recommended.

If you truly feel this feature needs more thought or vetting, then I suggest logging a bug against the W3C spec so that it can be implemented on all browsers -
https://w3c.github.io/webdriver/webdriver-spec.html
(bug link in the top corner)
