### ISSUE TITLE
Supported elements in org.openqa.selenium.support.ui

### ISSUE THREAD

**Issue by semonte** [SeleniumHQ/selenium#1858]
Why does package org.openqa.selenium.support.ui contain model for &lt;select> tag, but not for any other HTML element? It would make sense to have all HTML elements supported or none for consistency. 

The following elements could be modeled: button, checkbox, image, label, link, radio button, table, text fields (text and textarea).

If implementing Java classes for each HTML element sounds like a good idea, I would be happy to do it. However, I need some feedback on this.

**Comment by semonte** [comment]
Line breaks are not working for some reason, sorry about that.

**Comment by lukeis** [comment]
There's a special wrapper for Select tags because they need to be treated in a non-intuitive manner for most users. Many users assume one needs to click the Select first and then the Option, but that is not the case and they need to just click the Option directly.

All other elements do not have a confusing model to them and thus don't need a support class. Most "helpers" people want are not generic enough to fix for *every webpage in the world* and thus we feel they don't belong in this project and are most suited in other 'framework' type projects that could be used in tandem with selenium.

**Comment by semonte** [comment]
Thanks for replying, that sounds reasonable.
