### ISSUE TITLE
Browser-Safari: OpenGL elements are not present on screenshot taken by OpenQA.Selenium.Remote.RemoteWebDriver.GetScreenshot()

### ISSUE THREAD

**Issue by Hoverla** [SeleniumHQ/selenium#1866]
## Meta -
OS: OS X 10.10.5
Selenium Version: WebDriver.dll, v2.48.2.0, Safari WebDriver Extension 2.48.0 
Browser: Safari
Browser Version: 9.0.3

## Expected Behavior -
OpenGL objects are present on taken screenshot

## Actual Behavior -
OpenGL elements are not present on screenshot taken by OpenQA.Selenium.Remote.RemoteWebDriver.GetScreenshot()
## Steps to reproduce -
I’m taking screenshots of the application in Safari 9 by OpenQA.Selenium.Remote.RemoteWebDriver.GetScreenshot() (ITakesScreenshot.GetScreenshot()). But OpenGL elements are not present on taken screenshot. How this issue could be solved?

**Comment by lukeis** [comment]
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.
