### ISSUE TITLE
OSX 10.11.2 Safari 9.0.3 - Unable to install safari driver extension

### ISSUE THREAD

**Issue by churey** [SeleniumHQ/selenium#1871]
## Meta -
OS: 
Selenium Version: 
Browser: 
Browser Version: 

## Steps to reproduce -

I tried to install safari driver extension in this version safari, i downloaded the extension “SafariDriver.safariextz” and installed it. i click "Trust" button and Popup disappears leaving me with empty extensions dialog.  i tried a lot of methods to solve this issue and failed. I can access to the mac using VNC and without physical keyboard can be operated. https://github.com/seleniumhq/selenium/issues/1553

**Comment by lishiming9** [comment]
I am having the same issue here.
osx 10.10.5
Safari 9.1

**Comment by uchuugaka** [comment]
You likely need a new developer cert from Apple to sign a build and install. 
You also need to be logged in to an Aqua session. That means physical access. Not remote.

**Comment by daluu** [comment]
Take a look at  issue #1315 regarding installing the extension, maybe that might work for you.

And I would have thought VNC would be sufficient for working with Safari/SafariDriver. It used to be ok. Although for the extension install (in safe mode), most likely one will need local access.

**Comment by uchuugaka** [comment]
I would not recommend Safe Boot as a testing mode. 99 USD for a developer account should be within reach of anybody professionally testing. You **do** need an extension code signed with an active developer account.

VNC and other remote access tools will not work. This loop was closed. No security UI is actually usable outside of a standard local session. It might look usable, but will not do anything. Extensions are included in this.

**Comment by daluu** [comment]
@uchuugaka where can I find info about VNC / remote access loophole closed? Interesting to know about as a tester and user. I was not aware of such change to the Mac.

**Comment by lukeis** [comment]
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.

**Comment by daluu** [comment]
FYI, because Apple doesn't share reported bugs and their status updates to the public, only the reporter of the bug, it would be good for those who file bugs to also file a duplicate at

https://openradar.appspot.com/

and update the clone whenever there is an update to the filed bug, so that the rest of the community can check status and not need to file duplicate bugs.

It's unfortunate that Apple chose to have a closed bug reporting system. Confidential bugs may make sense, but many aren't.
