### ISSUE TITLE
Selenium Grid; RemoteWebDriver timeout

### ISSUE THREAD

**Issue by mr-raptor** [SeleniumHQ/selenium#1894]
Hi, I have installed grid with two nodes, one browser instance for each node
![](http://i.imgur.com/3eRmFLp.png)
But I have some error with it. Could you please explain me how grid should work correctly?

When I start several test fixtures, 
1. Started 2 tests in parallel.
2. In hub console always appears message about trying create new session. Is it regular behavior? I don't know.
![](http://i.imgur.com/7RdUWnR.png)
3. Exactly in 60 seconds after running in Visual Studio console appears next error message:
![](http://i.imgur.com/TxAccfm.png)
4. All tests, except first 2 ones, didn't run. I see only opened browser window.

I google this issue a lot. Tried different WebDriver versions. If I run less test fixtures, than there are capabilities on hub, this problem doesn't appear.

Please help.
Thanks.

**Comment by lukeis** [comment]
For questions please solicit help on the selenium users mailing list:
https://groups.google.com/forum/#!forum/selenium-users

As to what appears to be happening here, the nodes are currently busy with other sessions (but have free slots that don't match the browser type requested), it will keep looping through the list of nodes until it finds one with a browser available that does match. This will do so 'indefinitely' on the grid hub until it finds a match, which means however long it takes for one of the existing sessions to end.

You also seem to have a timeout on your WebDriver client that after 60 seconds of requesting a new session it aborts, I'm not sure if that's default in .NET or not, but I'm sure you can change it somehow. Since it seems at some point the shortest running test takes longer than 60 seconds and the new session request timed out. Also if you requested N sessions and you only have X browsers on nodes available, it would have to wait for N - X sessions to finish (which if each test takes 30 seconds, if you N is 3 more than X, you will assuredly run into this exception).
