### ISSUE TITLE
print element.get_attribute(innerHTML) works in ipython but not when run as a full script in the Linux terminal.

### ISSUE THREAD

**Issue by neatville** [SeleniumHQ/selenium#1901]
The same is true for Python3. I could not find another way to print the HTML of a given attribute. 

Part of the reason I want to do this is because I found some sites treat me differently when running a headless browser through pyvirtualdisplay, vs when it opens up a regular instance of a browser. I do set a browser size when I do that as well.  

```
  chromedriver = "/path/to/chromedriver64"
  os.environ["webdriver.chrome.driver"] = chromedriver
  display = Display(visible=0, size=(800,600))
  display.start() 
  options = webdriver.ChromeOptions() 
  options.add_argument("user-agent="+random.choice(linuxAgent)) #Path to your chrome profile
  driver = webdriver.Chrome(chromedriver, chrome_options=options)
```

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
