### ISSUE TITLE
actions.sendKeys(Keys.END) does not work in some pages

### ISSUE THREAD

**Issue by ericwtlin** [SeleniumHQ/selenium#1902]
## Meta -
OS: windows 10 x64
Selenium Version: 2.53.0
Browser:  Google Chrome
Browser Version: 49.0.2623.75 m (64-bit)

## Expected Behavior -
actions.sendKeys(Keys.END).perform(); should take me to the bottom of the page
(some pages work well, but some don't )
## Actual Behavior -
it doesn't work, nothing happens

## Steps to reproduce -
actions.sendKeys(Keys.END) does not work in the page bellow:  http://bbs.news.163.com/bbs/guoji/604136361.html

the chromedriver log and chromedriver.exe is attached. (both compressed in the zip file)
[chromedriver-log&exe.zip](https://github.com/SeleniumHQ/selenium/files/197764/chromedriver-log.exe.zip)

.

**Comment by p0deje** [comment]
This happens because when page is loaded, text area for commenting is focused, so `send_keys` are sent to it which makes no sense.

To workaround, you should send keys to body element. Here is how you can do that in Ruby, but Java example would be similar:

```ruby
body_element = driver.find_element(tag_name: 'body')
driver.action.send_keys(body_element, :end).perform
```

Also, this is not really a bug report but a support request so please use [selenium-users mailing list](https://groups.google.com/forum/#!forum/selenium-users) for such questions.
