### ISSUE TITLE
Python client :: PhantomJS cookies file

### ISSUE THREAD

**Issue by jamb0ss** [SeleniumHQ/selenium#1911]
In the last Python client's release (2.53.1) I see such change:
** create a temp file for cookies in phantomjs if not specified

What is the point? This file is never used. All cookies are stored in the memory.

## Meta -
OS: Linux
Selenium Version: 2.53.1
Browser: PjantomJS
Browser Version: 2.1.1

## Expected Behavior -

Cookies are stored in the automatically created file

## Actual Behavior -

Cookies are stored only in the memory

## Steps to reproduce -
```

from selenium.webdriver import PhantomJS

driver = PhantomJS()

cookies_file = filter(lambda _: _.startswith('--cookies-file='), driver.service.command_line_args())[0][15:]

driver.get('http://vk.com')

# cookies_file is empty

driver.get('http://google.com')

# cookies_file is still empty

driver.get('http://ya.ru')

# cookies_file is empty
```

**Comment by lukeis** [comment]
seems like an issue with phantomjs and webdriver, since the --cookies-file option appears to work when used without --webdriver, but doesn't work with it. Selenium's library isn't doing anything bad in particular, so i don't see a bug with the python code here.

Please log a bug (likely mostly in vein, since it's not really maintained anymore... but a pull request might get some traction) here:
https://github.com/detro/ghostdriver

**Comment by jamb0ss** [comment]
It's a bug, because this file (even if it'd work) must not be created automatically at all (please, check how PhantomJS works in this case)

**Comment by lukeis** [comment]
i don't understand what you mean.

you can specify --cookies-file with phantomjs and the file can already exist for it to work (without the --webdriver option, --cookies-file doesn't appear to work at all with the --webdriver option, thus needing to log a bug with phantomjs / ghostdriver and not with the selenium project here.)
