### ISSUE TITLE
Firefox 45.0.1 And webdriver 2.53 excessive CPU usage

### ISSUE THREAD

**Issue by randersen** [SeleniumHQ/selenium#1923]
Since upgrading to Firefox 45.0.1 and Webdriver 2.53 my tests take 3-4 times longer to run than previously.  After investigating the problem i found that 6 instances of firefox had my cpu pinned at 99% on an c4xlarge ec2 instance. 

Before the update it hovered around 50-80%. 

I lowered it to 4 instances and it still takes up over 90%. Seems like it might be a firefox issue though.

**Comment by lukeis** [comment]
can you reproduce the scenarios with the browsers manually (aka, without webdriver), if so, you might have a perf issue in firefox itself and thus would need to log a bug with mozilla.

Otherwise, there's very little for us to go on here and a reproducible test case for us to run would go a long way... until then there's nothing quite actionable for us, so i'm going to close.
