### ISSUE TITLE
Tests failed using IE driver

### ISSUE THREAD

**Issue by swathikvsr** [SeleniumHQ/selenium#1935]
## Meta -
OS: windows
Selenium Version: 2.53.0
Browser: IE
Browser Version:2.53.0.1

I used IEDriverServer.exe version 2.53.0.1 and my test case is opening an URL(not public URL local to my machine) and clicking on one of the link on the page.The page opens after the click on the link but I get the timeout exception and test fails, below is the code used to initialize the webdriver:

InternetExplorerOptions options = new InternetExplorerOptions();

options.PageLoadStrategy = InternetExplorerPageLoadStrategy.Eager;

webDriver = new InternetExplorerDriver(ConfigurationManager.AppSettings["IDEServerPath"].ToString(), options, TimeSpan.FromMinutes(2));

If any one can guide me on this that will be great as I am new to the selenium.This test case works fine using firefox driver.

**Comment by damianskiedrzynski** [comment]
Try to use 32-bit IE Driver. If doesn't help try to add Driver Capabilities.

Hope it helps.

**Comment by kesavaraojr** [comment]
If implicit and explicit waits mixed in your selenium test suite; try to use only explicit wait and check

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
