### ISSUE TITLE
Selenium Webdriver - Unable to select drop down in grid, it gets enabled and hide spontaneously

### ISSUE THREAD

**Issue by techiebuddhas** [SeleniumHQ/selenium#1943]
## Meta -
OS: 
Selenium Version: 
Browser: 
Browser Version: 

## Expected Behavior -
Dear all, please help me with this issues, in our web application most of the pages having dropdown’s in grid. While automating such process, it simply clicks the td (cell of the grid) and spontaneously the dropdown displayed and get hide. Because if its getting hide immediate we can’t perform next operation. How can we deal with such issues?  So that we can’t proceed further.
 I just tried with following functions in selenium webdriver.am using java(selenium version 2.52.0)
Click
Clickandhold
Tab keys
Double click 
Enter keys

Please advice? Thanks in advance.

## Actual Behavior -

drodpown in the grid enabled and hide spontaneously not able to perform action in the dropdown.
![after action](https://cloud.githubusercontent.com/assets/18043965/14373879/458924c0-fd6c-11e5-82d8-f04ffe351c5d.png)
![on action](https://cloud.githubusercontent.com/assets/18043965/14373880/458e5288-fd6c-11e5-8537-5a7db0f0f261.png)

**Comment by mstankovic86** [comment]
You can try with "select":

WebElement identifier = driver.findElement(By.id("id_of_drop_down"));
Select select = new Select(identifier);
select.selectByVisibleText("visible_text");

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
