### ISSUE TITLE
How to write xpath for element in different iframe

### ISSUE THREAD

**Issue by MeghaPrakash1992** [SeleniumHQ/selenium#1957]
As I am working on a portal that opens up only in IE, I have to write xpath. I am unable to click on element in an iframe. Help!

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
