### ISSUE TITLE
How to handle Data-Attributes (HTML5)  using Selenium WebDriver New Version.

### ISSUE THREAD

**Issue by banu2016** [SeleniumHQ/selenium#1968]
## Meta -
OS: 
Selenium Version: 
Browser: 
Browser Version:

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
