### ISSUE TITLE
Manual update of selenium server causes package import problems for apache commons lang3

### ISSUE THREAD

**Issue by tckelly38** [SeleniumHQ/selenium#1989]
I update the selenium-server-standalone from version 2.44.0 to 2.53.0 and selenium-java from 2.44.0 to 2.53.0. I am now getting an import error on "org.apache.commons.lang3.ArrayUtils" in one of my classes. Reverting back to 2.44.0 fixes this problem. 

What's going on?

**Comment by lukeis** [comment]
The standard selenium server no longer requires commons-lang3, it is only required for HtmlUnitDriver, which is now bundled in a separate project:
https://github.com/SeleniumHQ/htmlunit-driver

If your code requires commons-lang3, I would recommend adding the dependency rather than relying on a transitive third party dependency.
