### ISSUE TITLE
 I'm trying to find this field in firefinder

### ISSUE THREAD

**Issue by ciaran12** [SeleniumHQ/selenium#1997]
## Meta -
OS: 
Selenium Version: 
Browser: Firefox -->
Browser Version: 

## Expected Behavior -
 	
HTML IS: <a onclick="courseOfferingClose('sls355.rtp.raleigh.ibm.com:81/LMS1324/lms? Role=Trainingadmin&amp;Action=TACrsVwAdd&amp;CrsId=50D120524153208B8C25135700019‌​F1F&amp;Prices=&amp;Is OnlineOfferingAdded=true'); return false;" href="" onmouseover="this.style.color='#ff0000'" onmouseout="this.style.color=''" style="">Close</a>

I'm trying to find this field in firefinder using

[onclick*='courseOfferingClose']

a[contains(@onclick,'courseOfferingClose')]

[contains(@onclick,'courseOfferingClose')]

And none work... Any ideas please

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
