### ISSUE TITLE
PhantomJS requires different way to run for HTTPS site and is it or is it  not integrated?

### ISSUE THREAD

**Issue by rebatov** [SeleniumHQ/selenium#2000]
I have a scraper in which I am scraping https sites. The problem is phantomjs requires **phantomjs --ssl-protocol=tlsv1** to open headless browser for https but, how to integrate this with selenium-webdriver?

And the thing is using **firefox** as the browser works like a charm..

Please somebody :)

**Comment by sergeychipiga** [comment]
you can provide addition options to start phantomjs (and other browsers)

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
