### ISSUE TITLE
document.write/document.writeln hangs firefox driver

### ISSUE THREAD

**Issue by borski** [SeleniumHQ/selenium#2014]
## Meta -
OS: OS X
Selenium Version: 2.53.0
Browser: Firefox
Browser Version: 45.0.2

Originally reported [here](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/3460), and confirmed this is still occurring. Not sure if that archive is looked at at all, so I'm making the issue here as it's affecting us directly.

## Expected Behavior -
Write to the browser window and continue with the rest of the unit test.

## Actual Behavior -
FF Driver just hangs until I manually kill the browser.

## Steps to reproduce -
1. Create unit test with the following in it (With or without `driver.get("about:blank");`):

    ```JavascriptExecutor js = (JavascriptExecutor) driver;
    js.executeScript("document.write(\"Test\");document.close()");```

2. Execute the unit test.

**Comment by lukeis** [comment]
docuemnt.write is destructive of the current DOM and you are potentially removing references to existing JS objects that webdriver had already put on the window object when the call was first made... thus deleting those references and so it doesn't call a callback method to give a response (since you just deleted it).

I'm going to close this as won't-fix. Rather if you want to inject new elements on the DOM, use window.createElement and then document.body.appendChild.

**Comment by borski** [comment]
The problem is that we don't always have control over the content - this really is an issue worth fixing.

**Comment by lukeis** [comment]
"we don't always have control over the content"

That makes no sense here, you are in control of what you call to execute script, right?

You'll need to elaborate on your use case
