### ISSUE TITLE
We have problem in stimulating drag and drop functionality in html 5 site

### ISSUE THREAD

**Issue by sujithsuresh05** [SeleniumHQ/selenium#2032]

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
