### ISSUE TITLE
Click on Dynamic date link

### ISSUE THREAD

**Issue by karimahirani** [SeleniumHQ/selenium#2057]
## Meta -
OS:  Windows 7

Selenium Version:  
IDE
Browser:  
 Firefox 
Browser Version:  
46.0
## Expected Behavior -
Should click on first(topmost)date link in the table. date link is very dynamic.
## Actual Behavior -
not able to make it dynamic, hence clicks on static date link
## Steps to reproduce -
A table is displayed with the date links on it. every time you add a new record, it is saved under the date link of the day you added the record.
My question is how do i make it click on the most current link no matter what the date is?
Dynamic??

**Comment by ddavison** [comment]
Hey there!

Looks as though your issue is actually a user issue rather than an issue with Selenium itself.  For these issues, we ask you to please use the [selenium users group](https://groups.google.com/forum/#!forum/selenium-users) as we reserve GitHub issues for actual issues with the software.  Thanks!
