### ISSUE TITLE
Firefox 46.0.1

### ISSUE THREAD

**Issue by giacgbj** [SeleniumHQ/selenium#2067]
## Meta -
OS: Windows 10
Selenium Version:  2.53.0
Browser: Firefox
Browser Version: 46.0.1

## Expected Behavior -

WebDriver connects to the browser.

## Actual Behavior -

org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 42424 after 45000 ms. Firefox console output:
}","syncGUID":"ALxJgp7_YQ3u","location":"app-global","version":"46.0.1","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1462254391049,"updateDate":1462254391049,"applyBackgroundUpdates":1,"skinnable":true,"size":22012,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"46.0.1","maxVersion":"46.0.1"}],"targetPlatforms":[],"seen":true}
1462751801279	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1462751801280	DeferredSave.extensions.json	DEBUG	Save changes
1462751801280	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1462751801280	addons.xpi-utils	DEBUG	Updating add-on states
1462751801281	addons.xpi-utils	DEBUG	Writing add-ons list
1462751801284	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1462751801285	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1462751801285	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1462751801285	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0
1462751801286	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1462751801287	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.2.6
1462751801305	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1462751801305	addons.manager	DEBUG	Provider finished startup: XPIProvider
1462751801305	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1462751801305	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1462751801305	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1462751801306	addons.manager	DEBUG	Starting provider: GMPProvider
1462751801310	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1462751801310	addons.manager	DEBUG	Provider finished startup: GMPProvider
1462751801310	addons.manager	DEBUG	Starting provider: PluginProvider
1462751801311	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1462751801311	addons.manager	DEBUG	Provider finished startup: PluginProvider
1462751801311	addons.manager	DEBUG	Completed startup sequence
1462751801679	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1462751801679	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1462751801680	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1462751801680	DeferredSave.extensions.json	DEBUG	Starting write
1462751801862	addons.repository	DEBUG	No addons.json found.
1462751801863	DeferredSave.addons.json	DEBUG	Save changes
1462751801864	DeferredSave.addons.json	DEBUG	Starting timer
1462751801887	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1462751801887	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1462751801887	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1462751801890	DeferredSave.extensions.json	DEBUG	Write succeeded
1462751801890	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1462751801916	DeferredSave.addons.json	DEBUG	Starting write
1462751801959	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:123)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:117)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:124)
	at it.unimaticaspa.firmant.web.jsf.TestJsfTag.setUp(TestJsfTag.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

## Steps to reproduce -

Just use Firefox 46.0.1 with Selenium 2.53.0 for Java.

**Comment by DanielSundberg** [comment]
I use the Selenium nuget package of Selenium and execute tests from C# in Visual Studio and I have the same problem in Firefox 45.0.2. In my case it seems like Firefox is picking up an invalid version of the Selenium add-in after updating from 2.48 to 2.53:

![2016-04-07 10_21_09-clipboard](https://cloud.githubusercontent.com/assets/1454200/15104722/a765b516-15bb-11e6-820d-ce508db39387.png)

I've also tried to delete temp directories created by Selenium test run (C:\Users\my_username\AppData\Local\Temp\anonymous.*)

If I look at the file created under _C:\Users\my_username\AppData\Local\Temp\anonymous.23910f1f67d443819508836abee8b1a8.webdriver-profile\extensions\fxdriver@googlecode.com\install.rdf_ it looks like this:

````html
<?xml version="1.0"?>
<RDF xmlns="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:em="http://www.mozilla.org/2004/em-rdf#">

    <Description about="urn:mozilla:install-manifest">
        <em:id>fxdriver@googlecode.com</em:id>
        <em:version>2.48.0</em:version>
        <em:type>2</em:type>
        <em:name>Firefox WebDriver</em:name>
        <em:description>WebDriver implementation for Firefox</em:description>
        <em:creator>Simon Stewart</em:creator>
        <em:unpack>true</em:unpack>

        <!-- Firefox -->
        <em:targetApplication>
            <Description>
                <em:id>{ec8030f7-c20a-464f-9b0e-13a3a9e97384}</em:id>
                <em:minVersion>3.0</em:minVersion>
                <em:maxVersion>45.0</em:maxVersion>
            </Description>
        </em:targetApplication>

        <em:targetPlatform>Darwin</em:targetPlatform>
        <em:targetPlatform>SunOS</em:targetPlatform>
        <em:targetPlatform>FreeBSD</em:targetPlatform>
        <em:targetPlatform>OpenBSD</em:targetPlatform>
        <em:targetPlatform>WINNT_x86-msvc</em:targetPlatform>
        <em:targetPlatform>Linux</em:targetPlatform>

        <!-- We're probably missing lots of platforms here -->
    </Description>

</RDF>

````

Max version of Firefox handled is 45.0, clearly this won't work for me. How can I get the correct _install.rdf_ file to load?

Looking at Selenium code at label 2.53.0 this is not the code I should get:
https://github.com/SeleniumHQ/selenium/blob/selenium-2.53.0/javascript/firefox-driver/extension/install.rdf

**Comment by jimevans** [comment]
I've just confirmed that the correct version of the Firefox add-in is packaged inside the WebDriver assembly for version 2.53.0. Also, looking at the linked issue, the root cause appears to be a manually-extracted version of the `webdriver.xpi` extension added to the source tree. The .NET bindings can look for the extracted extension file in the output directory (the same as the `WebDriver.dll` assembly). This is a feature as opposed to a bug, as it allows the user to override the version of the extension, using a different one than that provided as an embedded resource in the `WebDriver.dll` assembly.

**Comment by nikkiparikh** [comment]
I am getting similar issue, i am not getting how this issue gets resolved

Meta -

OS: Windows 7
Selenium Version: 2.53.0
Browser: Firefox
Browser Version: 46.0.1

Expected Behavior -

WebDriver connects to the browser.

Actual Behavior -

org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
,"multiprocessCompatible":false,"signedState":0,"seen":true}
1465408689376 DeferredSave.extensions.json DEBUG Save changes
1465408689376 addons.xpi DEBUG Updating database with changes to installed add-ons
1465408689376 addons.xpi-utils DEBUG Updating add-on states
1465408689378 addons.xpi-utils DEBUG Writing add-ons list
1465408689380 addons.xpi DEBUG Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1465408689380 addons.xpi DEBUG Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1465408689380 addons.xpi DEBUG Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1465408689381 addons.xpi DEBUG Calling bootstrap method startup on firefox@getpocket.com version 1.0
1465408689381 addons.xpi DEBUG Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1465408689382 addons.xpi DEBUG Calling bootstrap method startup on loop@mozilla.org version 1.2.6
1465408689397 addons.manager DEBUG Registering shutdown blocker for XPIProvider
1465408689398 addons.manager DEBUG Provider finished startup: XPIProvider
1465408689398 addons.manager DEBUG Starting provider: LightweightThemeManager
1465408689398 addons.manager DEBUG Registering shutdown blocker for LightweightThemeManager
1465408689398 addons.manager DEBUG Provider finished startup: LightweightThemeManager
1465408689398 addons.manager DEBUG Starting provider: GMPProvider
1465408689402 addons.manager DEBUG Registering shutdown blocker for GMPProvider
1465408689402 addons.manager DEBUG Provider finished startup: GMPProvider
1465408689402 addons.manager DEBUG Starting provider: PluginProvider
1465408689402 addons.manager DEBUG Registering shutdown blocker for PluginProvider
1465408689402 addons.manager DEBUG Provider finished startup: PluginProvider
1465408689403 addons.manager DEBUG Completed startup sequence
1465408689650 addons.manager DEBUG Starting provider: <unnamed-provider>
1465408689650 addons.manager DEBUG Registering shutdown blocker for <unnamed-provider>
1465408689650 addons.manager DEBUG Provider finished startup: <unnamed-provider>
1465408689652 DeferredSave.extensions.json DEBUG Starting write
1465408689823 addons.repository DEBUG No addons.json found.
1465408689824 DeferredSave.addons.json DEBUG Save changes
1465408689827 DeferredSave.addons.json DEBUG Starting timer
1465408689849 addons.manager DEBUG Starting provider: PreviousExperimentProvider
1465408689849 addons.manager DEBUG Registering shutdown blocker for PreviousExperimentProvider
1465408689849 addons.manager DEBUG Provider finished startup: PreviousExperimentProvider
1465408689852 DeferredSave.extensions.json DEBUG Write succeeded
1465408689853 addons.xpi-utils DEBUG XPI Database saved, setting schema version preference to 17
1465408689878 DeferredSave.addons.json DEBUG Starting write
1465408689887 DeferredSave.addons.json DEBUG Write succeeded
1465408698285 addons.xpi DEBUG Calling bootstrap method shutdown on e10srollout@mozilla.org version 1.0
1465408698286 addons.xpi DEBUG Calling bootstrap method shutdown on firefox@getpocket.com version 1.0
1465408698286 addons.xpi DEBUG Calling bootstrap method shutdown on loop@mozilla.org version 1.2.6
1465408698446 addons.manager DEBUG shutdown
1465408698447 addons.manager DEBUG Calling shutdown blocker for XPIProvider
1465408698447 addons.xpi DEBUG shutdown
1465408698447 addons.xpi-utils DEBUG shutdown
1465408698447 addons.manager DEBUG Calling shutdown blocker for LightweightThemeManager
1465408698448 addons.manager DEBUG Calling shutdown blocker for GMPProvider
1465408698449 addons.manager DEBUG Calling shutdown blocker for PluginProvider
1465408698449 addons.manager DEBUG Calling shutdown blocker for <unnamed-provider>
1465408698449 addons.manager DEBUG Calling shutdown blocker for PreviousExperimentProvider
1465408698451 addons.xpi DEBUG Notifying XPI shutdown observers
1465408698453 addons.manager DEBUG Async provider shutdown done

Build info: version: '2.49.1', revision: '7203e46', time: '2016-01-21 17:35:35'
System info: host: 'AGERA-LT26', ip: '10.100.20.218', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_71'
Driver info: driver.version: FirefoxDriver

**Comment by nikkiparikh** [comment]
Good news.

I just get that resolved on its own. Still wondering.. What i did is i uninstalled Firefox and installed 46.0.0 once again and than i removed my selenium jar from my project. Refreshed my project. Showing Error so again added the same Jars and again did refresh and when i ran my script, i was surprised as it it worked and opened up firefox and processed further.
