### ISSUE TITLE
Where can I get list of selenium version which supports firefox when new firefox is released

### ISSUE THREAD

**Issue by karunakaran-pt** [SeleniumHQ/selenium#2105]
@davehunt  @shs96c 

I am using selenium and firefox for my testing. When I suddenly upgraded my firefox version. Then I have to search for which version of firefox supports selenium version. I am doing this search every time when I upgraded my firefox version. This makes me wait for answers from someone.

When you releasing a new version of selenium and provide me the list of firefox, chrome supported versions. It will be more helpful for everyone.

I have looked at the changelog . But Its doesn't help to list the supported versions of firefox and chrome. https://github.com/SeleniumHQ/selenium/blob/master/dotnet/CHANGELOG

Kindly help.

**Comment by bsauls** [comment]
This would help me also. My company pushed a Firefox update, WebDriver was obsolete, no more running protractor.

**Comment by davehunt** [comment]
This is not an issue, but a question, more appropriate for the [user group](https://groups.google.com/forum/#!searchin/selenium-users). At the time any given version of Selenium is released it should support the current release of Firefox and the latest extended support release of Firefox. When a new Firefox is released there is occasionally a need for a subsequent Selenium version to be released. In general you should keep Selenium up to date if you're updating Firefox. With the upcoming Firefox 47 there's likely to be some disruption due to the driver implementation needing to change from the current FirefoxDriver historically maintained by Selenium to GeckoDriver, which is maintained by Mozilla.

If you have further questions please raise them in the [user group](https://groups.google.com/forum/#!searchin/selenium-users) instead of the issue tracker.
