### ISSUE TITLE
ExpectedConditions.visibilityOfElementLocated is not working correctly

### ISSUE THREAD

**Issue by adambbn** [SeleniumHQ/selenium#2112]
## Meta -
OS:  Windows 7

Selenium Version:  2.53.0

Browser:  Firefox, Chrome

Browser Version:  ESR 38.7.1 (Firefox), 50.0.2661.102 m (Chrome)

## Expected Behavior -
Find visible element that is present in HTML using _ExpectedConditions.visibilityOfElementLocated_ method and print its id attribute.

## Actual Behavior -
Element is not found and _TimeoutException_ exception is thrown.

## Steps to reproduce -

Code: https://gist.github.com/adambbn/beee14d9a66ca91115fa9a306c51e274
Two element are present in HTML. First is not visible, second is visible.
Finding element using _ExpectedConditions.visibilityOfElementLocated_ method is not working.
If visible element is present before invisible element method works fine.

**Comment by Mobrockers** [comment]
You are misunderstanding the expected condition. The expected condition says wait until the element found by my locator is visible. Since you have an ambiguous locator, the **first** element is **always** selected. The first element is not visible so it will return false until you hit your timeout limit.

What you want is something like this expected condition in python: https://github.com/Mobrockers/selenium/blob/f878b53d9dd66ef25444b82e50218acd36f6bc4e/py/selenium/webdriver/support/expected_conditions.py#L105

It does not currently exist in the Java api.

**Comment by rac2030** [comment]
The question comes to my mind if it might not be better to do it in a more strict way as the first match strategy leads to strange bugs for beginners. Wouldn't it be better if it throws an exception in case it finds more than 1 match to the locator? Maybe some sort of flag to set a strategy choosing between firstmatch,  singlematch, ...
I know you can do it as restrictions inside some of the locators but this would might prevent some people from debugging many hours if they are not that experienced with locators.

**Comment by jleyba** [comment]
No, locators always return the first matched element based on a depth first
traversal of the DOM. Users need to understand that concept. Using a
locator with an ExpectdCondition is no different than using it with
WebDriver directly - you get the first match

**Comment by lukeis** [comment]
this is working as expected. Locator should be more specific. Or one can write their own 'visibility of any element located' method. (Pull requests accepted)
