### ISSUE TITLE
 RE:argument(0).click is not a fuction in javascriptexecutor

### ISSUE THREAD

**Issue by archanamuplams** [SeleniumHQ/selenium#2126]
I used javascript executor to click an element(used javascript executor because faced stale element referrence issue).When i tried to click an element using this javascript executor getting error as"argument(0).click is not a fuction".
>
> WebElement weekdate1 = driver.findElement(By.xpath(".//*[@id='dashboardleft']/div[2]/div/div[1]/a"));
>
> ((JavascriptExecutor) driver).executeScript("arguments[0].click();", weekdate1);
>
> Can you help us to overcome this issue.Thanks in advance

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
