### ISSUE TITLE
Selenium Grid-Hub and Node configuration- Error while registering NODE

### ISSUE THREAD

**Issue by ank15** [SeleniumHQ/selenium#2151]
I am getting some unexpected error message while trying to register node on WINDOWS machine[Image attached -Node instance screenshot]. Due to which, I am getting an error message [No node with the desired capabilities "browserName=internet explore,javascriptEnabled-true,version=,platform=WINDOWS" is found.] while trying to execute test cases on registered node.

Command to start hub: start java -jar C:\selenium-server-standalone-2.50.1.jar -port 4444 -role hub "browserName=internet explore,javascriptEnabled-true,version=,platform=WINDOWS"

Command to start Node: java -jar C:\Selenium\selenium-server-standalone-2.50.1.jar -port 5556 -role node -hub http://localhost:4444/grid/register "browserName=internet explore,javascriptEnabled-true,version=,platform=WINDOWS" 
![image](https://cloud.githubusercontent.com/assets/19182349/15479223/bede8790-213c-11e6-9943-50db47e560e9.png)
![image](https://cloud.githubusercontent.com/assets/19182349/15479251/ec1f0ef0-213c-11e6-8bc6-2e477c58e074.png)

NODE: Getting the same error with jar 2.53.0

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by lukeis** [comment]
You likely have more issues going on, but the browser name is "internet explorer"  <- missing the ending 'r'

**Comment by lukeis** [comment]
two more things that i see quickly... don't specify browserName with -hub, and on the command line for the -role node you need '-browser' before the string that contains "browserName=..."
