### ISSUE TITLE
Webdriver cannot continue execute JS script on firefox on 2.53 version

### ISSUE THREAD

**Issue by RalfWang** [SeleniumHQ/selenium#2163]
## Meta -
OS:  win7 64

Selenium Version: 2.53.0  

Browser:  firefox

Browser Version:   43.0.4 64 bit

## Expected Behavior -
When I run a JS script in selenium, the parameter is larger. The firefox pop up  an alert message box, warning me to continue,debug or ignore. I want to continue run the scripts to get the right response.
I set the webdriver as : 
capability = DesiredCapabilities.firefox();
 capability.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR,UnexpectedAlertBehaviour.ACCEPT);

But it is not work, the ACCEPT is to monitor the text in the browser. In selenium the relation text as follow:
  ACCEPT ("accept"),
  DISMISS ("dismiss"),
  IGNORE ("ignore")
  There is no "Continue" options.....

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
