### ISSUE TITLE
how to measure response time for both loading and search time for a website ? selenium

### ISSUE THREAD

**Issue by hana9090** [SeleniumHQ/selenium#2167]
I need to measure response time for website using Selenium and Selenide.

 1. Response time of a website: 
I mean the loading time, I see that there is method to take difference between time before and after open website.

> But this way, will measure the client loading time, will it depend on the used client? what is the best way for do that?

    long startTime = System.currentTimeMillis();
    
    driver.get("http://zyxware.com");
    
    new WebDriverWait(driver, 10).until(ExpectedConditions.
    
    presenceOfElementLocated(By.id("Calculate")));
    
    long endTime = System.currentTimeMillis();
    
    long totalTime = endTime - startTime;
    
    System.out.println("Total Page Load Time: " + totalTime + "
    
    milliseconds");
   

 

 2. if I have a search button for the same website, if I need to measure the search time, how to do it? is it as same as the above way?

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
