### ISSUE TITLE
[SafariDriver] KeyboardEvent.which property is not defined for event resulting from Selenium's sendKeys method. This then breaks jQuery's normalisation of the which value.

### ISSUE THREAD

**Issue by JoolsCaesar** [SeleniumHQ/selenium#2191]
## Meta -
OS:  
OSX: 10.9.5
Selenium Version:  
2.53.0
Browser:  
Safari
Browser Version:  
9.1.1

## Expected Behavior -
event.which should return the key code.
## Actual Behavior -
event. which is 0
## Steps to reproduce -
Create a page with a simple jquery event handler:
```
$(document).on("keydown",function(event){
   console.log("which:"+event.which+", keyCode:"+event.keyCode);
});

```

If you press the for example the left arrow key the output will be "which: 37.keyCode:37".

If you do the same with selenium, e.g. `documentElement.sendKeys(Keys.LEFT);`, the output will be "which: 0, keyCode:37"

The work around is simple enough- making handlers use `event.which||event.keyCode`, but the problem is [that `which` is the normalised value in jquery](https://api.jquery.com/keydown/) so most handlers use it and I don't have so much control over third party code.

**Comment by JoolsCaesar** [comment]
From a purely javascript point of view, the problem is that key events resulting from the SafariDriver's sendkeys method, do not define the `which `property. They only define `charCode` (as 0) and `keyCode` (as the expected value), where as for keydown fired by actual user action `which` is defined as the same as keyCode. 

So when jQuery normalises the which value...

> While browsers use differing properties to store this information, jQuery normalizes the .which property so you can reliably use it to retrieve the key code. This code corresponds to a key on the keyboard, including codes for special keys such as arrows.
- https://api.jquery.com/keydown/


```
// Add which for key events
if ( event.which == null ) {
   event.which = original.charCode != null ? original.charCode : original.keyCode;
}
```

...`event.which` will always come out as 0.

**Comment by sophiecdd** [comment]
@JoolsCaesar Does the clickMouseButton button property has the same issue as the keyboard event which property?

**Comment by Paul167** [comment]
@sophiecdd I experienced similar problems on Chrome and Firefox. In both cases it turned out that the MouseEvent.which property was not defined for the mouse events generated by the WebDriver. Although it is [marked as non-standard](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/which), the MouseEvent.which property is supported by the majority of browsers and widely used by web developers (including jQuery). The same situation is with the [KeyboardEvent.which](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which) property as described in the issue's topic. In my opinion both should be implemented by the WebDriver.

**Comment by lukeis** [comment]
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.
