### ISSUE TITLE
The HTTP request to the remote WebDriver server for URL http://localhost:60355/session timed out after 60 seconds.

### ISSUE THREAD

**Issue by kvk123456** [SeleniumHQ/selenium#2201]
## Meta -
OS:  Windows 7 Professional, 64 bit

Selenium Version:  2.52.0.0

Browser:  Google Chrome 

Browser Version:  51.0.2704.79

## Actual Behavior -

The below line of code throwing error "The HTTP request to the remote WebDriver server for URL http://localhost:60355/session timed out after 60 seconds."
ChromeDriver webDriver = new ChromeDriver()

## Steps to reproduce -

The below line of code throwing error "The HTTP request to the remote WebDriver server for URL http://localhost:60355/session timed out after 60 seconds."
ChromeDriver webDriver = new ChromeDriver()

**Comment by lukeis** [comment]
For chromedriver issues log them with the chromedriver project. But you need to provide a way for someone to reproduce the issue, which I cannot. 
You may want to email the selenium-users Google group first

**Comment by Thilaknath** [comment]
@lukeis can you comment if there was solution provided to issue id : 4319, "Unreachable browser". The thread appears closed.

**Comment by Sire** [comment]
@lukeis I found out a likely reason some people are still getting this problem. 

Chrome web installer (the one most people use) installs Chrome in `%HOMEPATH%\Local Settings\Application Data\Google\Chrome\Application\chrome.exe`

Chrome standalone installer installs Chrome in `%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe`

If you have both installed, and use the latter one, the first one will never update.
So when Selenium checks where Chrome is installed, it finds the first one and unsuccessfully tries to use an old version, resulting in this error.

I understand this is an edge case, but here are some proposed fixes:

1. Give a proper error message instead of a timeout? ("chrome.exe was found in <dir> but version<x.y> is incompatible with Selenium <x.y>")

2. Check both directories, and warn if chrome is found in both.

3. Or at least, consider updating [the wiki](https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver) with this information.

Let me know if I can help. I can enter a new issue if needed. Or does this belong in the chromedriver bug tracker?

Thanks!
