### ISSUE TITLE
Inconsistent behavior when running IEServerDriver.exe

### ISSUE THREAD

**Issue by v-krmo** [SeleniumHQ/selenium#2207]
## Meta -
OS:  Windows 10

Selenium Version:  2.53.0

Browser:  IE

Browser Version:  11.306.10586.0

## Expected Behavior -
when launching IEServer driver and navigating to url i'm able to find the element i'm looking for and click the button
## Actual Behavior -
when launching IEServerDriver.exe and navigating to a url i'm unable to find the element after repeating the test. setting enablenativeevents = true every other time enables the IEserverdriver to find the element.
## Steps to reproduce -

 private InternetExplorerOptions options = new InternetExplorerOptions
        {
            PageLoadStrategy = InternetExplorerPageLoadStrategy.Eager,
            EnableNativeEvents = false,
            IgnoreZoomLevel = true,
            RequireWindowFocus = false,
            EnsureCleanSession = true,
            EnablePersistentHover = false
            //InitialBrowserUrl = baseURL
        };
public void RunTests()
{
options.InitialBrowserUrl = "<sharepointsite>";
            driver = new InternetExplorerDriver(options);
         
                driver.FindElement(By.Id("QCB1_Button2")).Click();
}

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
