### ISSUE TITLE
Feature Request: Tell Chrome to Launch with Developer Tools Open

### ISSUE THREAD

**Issue by jasonfb** [SeleniumHQ/selenium#2228]
## Meta -
OS:  Mac OS X 10.11.5

Selenium Version:  selenium-webdriver (2.53.0)

Browser:    Chrome 

Browser Version:   50.0.2661.102 (64-bit)

I am using chrome via Capybara on a Mac. I am using Capybara 2.7.1 on a Rails 4.1.14.2 app

in my spec_helper, I have configured selenium like so:
```
Capybara.register_driver :chrome do |app|
  Capybara::Selenium::Driver.new(app, :browser => :chrome)
end

Capybara.javascript_driver = :chrome
```

## Expected Behavior -

I want to be configure the driver to open Developer Tools **when the test first starts to run**, i.e., when the chrome driver instance is launched. If I knew how to launch Chrome with dev tools open I think that https://github.com/SeleniumHQ/selenium/issues/2227 would be moot and also I could use this to drop into my debugger while running a Capybara test

## Actual Behavior -

not applicable

**Comment by jimevans** [comment]
Feature requests for chromedriver should be logged with the [Chromium team](https://bugs.chromium.org/p/chromedriver/issues/list). However, note that this behavior in particular is [normal and expected](https://sites.google.com/a/chromium.org/chromedriver/help/devtools-window-keeps-closing).

**Comment by jasonfb** [comment]
this is the feature request (other Issue was related to the behavior). Just to be clear, you know of no way chrome can be flagged to open with Dev tools open via the driver?  If so, then I agree this would need to go to the Chrome developers themselves

**Comment by jimevans** [comment]
No, I know of no way to accomplish this because the driver uses the Chrome Remote Debugging Protocol to perform (at least some of) its actions. The debugging protocol only supports one client at a time. The chromedriver executable is one; the Developer Tools window is another. You could _try_ using the `--auto-open-devtools-for-tabs` command-line switch when launching Chrome. In many language bindings, this can be accomplished by [using the `ChromeOptions` class](https://sites.google.com/a/chromium.org/chromedriver/capabilities) to set capabilities on the resulting instance of Chrome. I have no idea whether the Ruby language bindings support that construct, nor if it's exposed by Capybara.

**Comment by manelclos** [comment]
Thanks for pointers, working configuration for nightwatch:

```
...

    chrome: {
      desiredCapabilities: {
        browserName: 'chrome',
        javascriptEnabled: true,
        acceptSslCerts: true,
        chromeOptions: {
          'args': ['incognito', 'disable-extensions', 'auto-open-devtools-for-tabs']
        }
      }
    },
...
```

**Comment by choosen** [comment]
It works at chrome headfull. Not at headless mode
