### ISSUE TITLE
Why "test_google.py" contain "webhp" in URL?

### ISSUE THREAD

**Issue by coderLeprosy** [SeleniumHQ/selenium#2236]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:  

## Actual Behavior -
Why there is "webhp" in Google URL? I understand that webhp is some kind of "hijacker"
http://www.anvisoft.com/resources/homepage-changed-to-google-comwebhp-how-to-remove/

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
