### ISSUE TITLE
Feature request: API to work with browser tabs (Open new tab, switch to tab, etc)

### ISSUE THREAD

**Issue by thecoderok** [SeleniumHQ/selenium#2247]
Please add API to open new browser tab.
While most of the time there is no need to manipulate tabs directly, but there are scenarios where it is needed

People need it and look for solution: https://www.google.com/search?q=selenium+webdriver+open+new+tab

Existing options are hacks and are not reliable

**Comment by jleyba** [comment]
Tabs and windows are really the same thing as far as the webdriver spec is concerned (and javascript for that matter): distinct top-level browsing contexts. That said, we disable tabbed browsing because it simplifies internal code (depending on the browser, sometimes drastically so).

If you try to circumvent this behavior by sending `CTRL+T` with the sendKeys() command, you are actively trying to bypass WebDriver's window tracking and things will likely break.
