### ISSUE TITLE
field.clear() doesn't clear the field on React.JS

### ISSUE THREAD

**Issue by dialex** [SeleniumHQ/selenium#2316]
## Meta
OS:  OSX
Selenium Version:  2.53.0, IntelliJ 2016.1.3
Browser:  PhantomJS

Browser Version:  Chrome 51.0.2704.103 (64-bit)

## Steps to reproduce

My web app is written in React.JS. Here are 2 gifs.

This shows the test I was trying to run:
![selenium clear bug detail](https://cloud.githubusercontent.com/assets/2140450/16188737/f77e8b66-36ce-11e6-94d7-97023723b784.gif)

This one goes step by step:
![selenium clear bug](https://cloud.githubusercontent.com/assets/2140450/16188738/f77fdd0e-36ce-11e6-9d55-c7750961e7ae.gif)

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
