### ISSUE TITLE
Firefox driver is non-free (does not contain sources)

### ISSUE THREAD

**Issue by thomasgoirand** [SeleniumHQ/selenium#2318]
The driver for firefox in py/selenium/webdriver/firefox contains pre-built software without source code. Please include the source code so that it can be rebuilt in distributions. Note that because of this, python-selenium in Debian doesn't contain the firefox driver, which was pushed in the non-free repository.

**Comment by AutomatedTester** [comment]
Looking athttps://github.com/SeleniumHQ/selenium/tree/master/py/selenium/webdriver/firefoxI can't see anything that doesn't have all the source. Please be more explicit or I will be closing this bug.

**Comment by lukeis** [comment]
if you're talking about webdriver.xpi, that gets built/ generated, the source of that is here:

https://github.com/SeleniumHQ/selenium/tree/master/javascript/firefox-driver

Otherwise I can also see nothing else that qualifies as non-free in Firefox driver selenium code. Please comment on exactly what you are talking about, if it is an issue then we can reopen this.
