### ISSUE TITLE
Selenium Internet Explorer Issue

### ISSUE THREAD

**Issue by Rajsh123** [SeleniumHQ/selenium#2319]
I am trying to execute script on Internet Explorer but I am not able to run as showing error of NoSuchWindow Unable to get browser  pls help me in same. I am working in Geb Framework using groovy what changes need to be done on GebConfig.groovy please assist

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
