### ISSUE TITLE
Can anyone suggest, Selenium supports SAP application? if yes, How to work with through Selenium?

### ISSUE THREAD

**Issue by siva2bunny** [SeleniumHQ/selenium#2351]
## Meta -
OS:  Windows

Selenium Version:  

Browser:  IE and Firefox both

Browser Version:

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by siva2bunny** [comment]
ok. thank you
