### ISSUE TITLE
Selenium 3: Improvement Suggestion: If Element is not visible or Hidden by some Popup then Exception generated can be changed to Provide better info

### ISSUE THREAD

**Issue by abhinav1708** [SeleniumHQ/selenium#2378]
## Meta -
OS:  Win 7 64

Selenium Version:  3 beta

Browser:  Firefox 45

Browser Version:  

## Expected Behavior -
Exception can be improved to explicitly state that Element is not visible for interaction
## Actual Behavior -
When we pass a click action for an element and if it is not visible or hidden by some popup then Exception is
org.openqa.selenium.WebDriverException: Element is not clickable at point (839, 147). Other element would receive the click: &lt;input tabindex="4" name="refId1" id="refId1Add" style="width:230px;vertical-align: middle;" maxlength="250" class="textField" type="text" align="left">

**Comment by lukeis** [comment]
potentially as a user you already have that info, since it's the element you are using to execute the .click() on.

I believe the information provided is sufficient, it provides the point location and the other element that would be clicked. One should be able to surmise which element was used to click from their code.

closing as won't fix (not offended if other committers feel otherwise and can reopen the issue)
