### ISSUE TITLE
How  to add record handler to our custom commands?

### ISSUE THREAD

**Issue by Joylim** [SeleniumHQ/selenium#2393]
I use selenium to record the web app actions. But some commands are not recorded , how 
can I improve it ?  I read the recorder.js and recorder-handler.js but I still don't know how to do.
What's more, how can I add event handler for my own commands?

Thanks!

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
