### ISSUE TITLE
element.clear() fails with exception

### ISSUE THREAD

**Issue by charlesfradley** [SeleniumHQ/selenium#2408]
element.clear() fails with exception

org.openqa.selenium.InvalidElementStateException: invalid element state: Element is not currently interactable and may not be manipulated
  (Session info: chrome=51.0.2704.106)
  (Driver info: chromedriver=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b),platform=Windows NT 10.0.10586 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 32 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'charles-PC', ip: '10.150.100.39', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_92'
Driver info: org.openqa.selenium.chrome.ChromeDriver

**Comment by jleyba** [comment]
The exception is telling you exactly what the problem is. You are trying to manipulate an element that is not in a state where it can be manipulated. (e.g. `<input disabled>`)

If you expect the to become enabled "soon", add an explicit wait to your test looking for that condition. For more help, contact the selenium-users@ group

**Comment by charlesfradley** [comment]
This works fine in IE and Firefox, it is only the Chrome which is failing.
