### ISSUE TITLE
unrecognized chrome option: detach when connecting to embedded chromium

### ISSUE THREAD

**Issue by yatsan** [SeleniumHQ/selenium#2418]
**This is was issue submitted to chromedriver with the conclusion: Wontfix:**
https://bugs.chromium.org/p/chromedriver/issues/detail?id=925
If 'debuggerAddress' is passed, then 'detach' is not used. It doesn't seem right for ChromeDriver to kill a Chrome session that it didn't start itself, and wasn't asked to quit. The Ruby library should be changed so that it omits 'detach' if 'debuggerAddress' is passed.

**Original issue description:**
I get unrecognized chrome option error when trying to connect to embedded chromiun by debuggerAddress chromeOption.

What steps will reproduce the problem?
1. caps = Selenium::WebDriver::Remote::Capabilities.chrome("chromeOptions" => {"debuggerAddress" => "127.0.0.1:20480"})

2. browser = Watir::Browser.new browser_type, :desired_capabilities => caps, :switches => ['--disable-extensions', 'test-type'] #, :service_log_path => 'chromedriver.out'#  , :switches => %w[--incognito] #--user-data-dir=C:\\HOME\\GIT\\CUD --load-async]

Exception:
Selenium::WebDriver::Error::UnknownError: unknown error: cannot parse capability: chromeOptions
from unknown error: unrecognized chrome option: detach
  (Driver info: chromedriver=2.10.267521,platform=Windows NT 6.1 SP1 x86_64)

Selenium version:  gem 'selenium-webdriver', "~> 2.43.0"
OS: windows 7
Browser: embedded chromium 
Browser version: 25

I had to comment line 91 of C:/Ruby/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.43.0/lib/selenium/webdriver/chrome/bridge.rb:
chrome_options['detach']                   = detach.nil? || !!detach

after commenting it connects to embedded chromium.

This issue is related to Issue 5591: ruby selenium-webdriver doesn't support chromedriver2: https://code.google.com/p/selenium/issues/detail?id=5591

But I use the latest selenium and chromedriver and if I don't use chromeOptions" => {"debuggerAddress" => "127.0.0.1:20480"} in capabilities it also works fine.

**Comment by titusfortner** [comment]
The detach option keeps the browser open if the chromedriver process is killed. Sending the quit command always shuts everything down  regardless of this setting. Since Ruby doesn't provide a mechanism for quitting the chromedriver without also exiting the browser, I don't know why we were overriding the default chromedriver behavior here (and have been since the option was introduced in 2011).

I removed our overriding of this default here - 0a4b99

This is not backward compatible, but I think it is the correct behavior and I have less concern for it breaking someone's approach in 3.0.
