### ISSUE TITLE
Does ChromeDriver support React and Angular like PhantomJS?

### ISSUE THREAD

**Issue by h8rry** [SeleniumHQ/selenium#2420]

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
