### ISSUE TITLE
IEDriverServer 2.52 and newer fails if simple JavaScript is on the page

### ISSUE THREAD

**Issue by skaeff** [SeleniumHQ/selenium#2421]
## IEDriverServer 2.52 and newer fails on a very simple Javascript code
OS: Windows 7, 8, 10 
Selenium Version:  IEDriverServer.exe 2.52.0 and newer
Browser:  Internet Explorer 8 and up

Suppose we've got this simple html page
```html
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>
		Продажа контракта в офисе
	</title>
	
<script language="javascript" type="text/javascript">
	var Number="рпоп";
</script>
    
</head>
<body>
	
</body>
</html>
```
I use simple WebDriver script (C#):
```c#
var driver = new InternetExplorerDriver();
driver.Navigate().GoToUrl(<url to that page>);
var elements = driver.FindElementsByXPath("/*");
```
I expect to get some elements, at least HTML element, but getting zero collection instead.
If to enable IEDriverServer.exe logging, the problem comes to the sight:

```ps
T 2016-07-02 01:31:25:791 Browser.cpp(602) Entering Browser::GetDocumentFromWindow
T 2016-07-02 01:31:25:796 Script.cpp(44) Entering Script::Initialize
T 2016-07-02 01:31:25:797 Script.cpp(65) Entering Script::AddArgument(std::wstring)
T 2016-07-02 01:31:25:797 Script.cpp(100) Entering Script::AddArgument(VARIANT)
T 2016-07-02 01:31:25:797 Script.cpp(65) Entering Script::AddArgument(std::wstring)
T 2016-07-02 01:31:25:797 Script.cpp(100) Entering Script::AddArgument(VARIANT)
T 2016-07-02 01:31:25:797 Script.cpp(164) Entering Script::Execute
T 2016-07-02 01:31:25:797 Script.cpp(472) Entering Script::CreateAnonymousFunction
D 2016-07-02 01:31:25:821 Script.cpp(244) -2147352319 [Unknown error 0x80020101]: Failed to execute anonymous function, no exception information retrieved
W 2016-07-02 01:31:25:822 ElementFinder.cpp(157) A JavaScript error was encountered executing the findElements atom.
T 2016-07-02 01:31:26:073 response.cc(63) Entering Response::SetSuccessResponse
```

It seems that the only javascript line breaks the engine:
```javascript
var Number="рпоп";
```
and the point is Number with the capital letter.

I think the fault code is in Script.cpp line 244 and up
```c++
  int return_code = WD_SUCCESS;
  EXCEPINFO exception;
  memset(&exception, 0, sizeof exception);
  hr = temp_function.pdispVal->Invoke(call_member_id,
                                      IID_NULL,
                                      LOCALE_USER_DEFAULT,
                                      DISPATCH_METHOD,
                                      &call_parameters, 
                                      &result,
                                      &exception,
                                      0);
```
See also similar issue #1590 

## Workaround
use 2.48 version of IEDriverServer.exe

**Comment by skaeff** [comment]
it seems that all versions newer to 2.48 are affected.

**Comment by jimevans** [comment]
You've redefined `Number`, which is the name of a core JavaScript object. I wouldn't swear to it, but I strongly suspect that the [JavaScript XPath-over-HTML library](https://github.com/google/wicked-good-xpath) that the driver uses expects the `Number` object to be available and unmodified. The "workaround" (scare quotes deliberate) is to not redefine core language constructs in your code.

**Comment by skaeff** [comment]
Well, i'm not developing the web application being tested. The HTML pages come from web server "as is", so that javascript code is not "mine".

Anyway - the browser Javascript console doesn't give any errors and warnings when parsing that page - not IE, not Chrome, not Mozilla.

Since WebDriver is to automate user actions it must support such situations.

PS: firefox & chrome are gently do the job - why not to let it to IE???

**Comment by jimevans** [comment]
Because Firefox and Chrome both provide native XPath engines for the DOM. IE doesn't, so the driver must rely on a JavaScript XPath implementation. And strictly speaking, it's not an error that would show up in a browser's error console. It's perfectly legal to replace a built-in language construct with one of your own, even if it's inadvisable to do so. If you believe that behavior is incorrect, you can file a bug against the JavaScript language standards for allowing it, the browser's JavaScript engine for not flagging it as an error or warning, or against the developers of the site in question for doing something that can have unintended side effects.

Either way, there is nothing the IE driver can do to resolve the issue. IE is extremely opaque with respect to its JavaScript execution. It does not allow third parties like the IE driver to get extended error information when a JavaScript error is encountered. What course of action would you like the driver to take, given the techical limitations (no native XPath engine, no control over JavaScript execution, etc.)?

**Comment by skaeff** [comment]
I see at least three independent solutions:
1. fix in that Javascript XPath library - [wicked-good-xpath](https://github.com/google/wicked-good-xpath)
2. make an option for IEDriverServer, like **--xpath-engine="..."**
3. describe this behaviour of IEDriverServer, so everybody would know before he faces with it.

For now v 2.48 is very suitable for me, because has no problems on automating such pages - what XPath mechanism is on there?
It would be good if that behaviour be an option in future releases.

PS: i'm not sure, but it seems those "errorneous" pages are generated by some ASPX engine - maybe Devex or Telerik - i don't know. But i really know that these engines are widely used in corporate and wide-web sites. So, IMHO it would be the best if this issue is fixed or workarounded and at least documented (see #1590 e. g.)

**Comment by jimevans** [comment]
First, let's stop treating #1590 as if it's the same issue as this. That issue is timing-related, and the change made for that issue was to allow the `WebDriverWait case, where the `findElement` call is repeated, to work properly without encountering a transient JavaScript error. This issue is different. The page in question explicitly breaks JavaScript. Maybe not in a way that impedes normal operation, but it does break it nonetheless.

Second, as to your proposed solutions, I'm sure the developers of wicked-good-xpath would be willing to accept a pull request. Feel free to create an issue and pull request with them. Suggestions to change XPath engines in the IE driver are mostly a nonstarter, but if you'd like to submit a pull request here that integrates and implements a new one, I'd be willing to look at it. As for documentation, I'm not sure what you'd like it to say, other than, "JavaScript which redefines base object types may cause issues in IE." However, that seems a little obvious as something a JavaScript developer shouldn't do in the first place.

**Comment by skaeff** [comment]
and what about IEDriverServer v 2.48 - why it is working with that page?
Could you do the same behaviour in later versions?

**Comment by jimevans** [comment]
The previous behavior would cause users of `WebDriverWait` to be entirely broken on any page where the JavaScript engine was a little slow in initializing, as the JavaScript error would not return "element not found".

**Comment by skaeff** [comment]
Please, could you reference that changeset, so i could compile my own version of IEDriverServer?
Or just guide me where to look into the code to get that changes?

The thing is i never use `WebDriverWait `in my project :)
But the problem of invalid Javascript XPath is almost a showstopper. At least for newer versions of IEDriverServer.

Maybe later i'll prepare a pullrequest of some kind, because for now i'm too newbie in WebDriver internals.

Thanks!

**Comment by jimevans** [comment]
The behavior was changed in dd61210e for the single element case, then in 3c33fe97 for the multiple element case. The commit messages and subsequent entries in the [IEDriverServer CHANGELOG](https://github.com/SeleniumHQ/selenium/blob/master/cpp/iedriverserver/CHANGELOG) are instructive.
