### ISSUE TITLE
Unable to set Firefoxdriver logfile using Ruby binding

### ISSUE THREAD

**Issue by abotalov** [SeleniumHQ/selenium#2435]
Setting log_file leads to either log file not being created or "unable to obtain stable firefox connection" error.

```ruby
require 'selenium-webdriver'

profile = Selenium::WebDriver::Firefox::Profile.new
profile.log_file = File.expand_path('firefoxdriver.log')
capabilities = Selenium::WebDriver::Remote::Capabilities.firefox(:firefox_profile => profile)
driver = Selenium::WebDriver.for :firefox, :desired_capabilities => capabilities
driver.navigate.to 'http://google.com'
driver.quit
# Log file isn't created as the result of this script
```

```ruby
require 'selenium-webdriver'

profile = Selenium::WebDriver::Firefox::Profile.new
profile.log_file = File.expand_path('firefoxdriver.log')
driver = Selenium::WebDriver.for :firefox, :profile => profile
# "unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055) (Selenium::WebDriver::Error::WebDriverError)" error occurs
```

OS: Windows 7
Selenium version: 2.53.4
Ruby binding
Browser: Firefox 47.0.1

**Comment by p0deje** [comment]
Firefox 47 is not supported by old Selenium FirefoxDriver. You should start moving to GeckoDriver and see if it works there.

**Comment by jenseng** [comment]
It doesn't work on Firefox 46.0.1 either, which *should* be supported by 2.53.4.

It looks like there might be a legit bug, but I'll investigate some more. In 2.53.4, the generated firefox profile incorrectly escapes forward slashes in strings. e.g. this line is fine:

```
user_pref("browser.usedOnWindows10.introURL", "about:blank");
```
but this line is not:
```
user_pref("webdriver.log.file", "\/dev\/stdout");
```
There should be no backslashes, since I simply set `log_file` to `"/dev/stdout"`

This creates problems downstream for fxdriver, since it expects all paths to be absolute, but it gets one that starts with a literal backslash. So the extension fails to load with an error like:

```
JavaScript error: file:///var/folders/5w/p8lgk76s44s5ppwwvw3s5n20qks2dy/T/webdriver-profile20160907-39370-1gn7zi7/extensions/fxdriver@googlecode.com/components/driver-component.js, line 733: NS_ERROR_FILE_UNRECOGNIZED_PATH: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsILocalFile.initWithPath]
JavaScript error: chrome://fxdriver/content/server.js, line 61: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
```

So webdriver never loads, firefox just hangs out with a blank page, and in 60 seconds you get `unable to obtain stable firefox connection`

**Comment by jenseng** [comment]
Upon further investigation, in my case it appears to be an incompatibility due some combination of rails, multi_json, oj, and rails-patch-json-encode ... I'll see if I can track it down exactly in case anyone else encounters a similar issue. In vanilla Ruby, `"/".to_json` returns `"\"/\""`, but in this particular app it returns `"\"\\/\""`

**Comment by jenseng** [comment]
For posterity, if you are encountering this issue in your app, a quick test you can do in a rails console is to see what `"/".to_json` returns; if it has a backslash before the slash, you are probably using the `oj` gem and have set `{escape_mode: :xss_safe}`. That in itself is a good thing (cuz speed and security), but it's incompatible with setting the `log_file` and might mangle other profile preferences, due to selenium's reliance on `to_json`.

As a workaround, do:

```ruby
# switch to vanilla json, so profile preferences don't get mangled
Oj.default_options = {escape_mode: :json}

# set up webdriver as per usual
profile = Selenium::WebDriver::Firefox::Profile.new
profile.log_file = "/path/to/file"
driver =  Selenium::WebDriver.for(:firefox, profile: profile)

# set it back so you're testing your app correctly
Oj.default_options = {escape_mode: :xss_safe}
```

Note that If you are on rails 4.0, you might instead be setting `MultiJson.dump_options`, but the process is otherwise the same.
