### ISSUE TITLE
[Wiki] FirefoxDriver Internals Wiki broken

### ISSUE THREAD

**Issue by lucasqiu** [SeleniumHQ/selenium#2443]
The FirefoxDriver Internals Wiki in this repo seems to be broken. 

See section "Flow of Control: Starting Firefox":
https://github.com/SeleniumHQ/selenium/wiki/FirefoxDriver-Internals

**Comment by lukeis** [comment]
Well... Not broken. Whoever last edited it just didn't finish what they were doing? (I'm afraid the history of who did is hard to track down, since the page was renamed and moved to github from Google code)

Going to close this issue as the page is merely incomplete. Feel free to open another issue with suggested edits to the page.
