### ISSUE TITLE
IE Driver getWindowHandles(); returning 1 handle if there are multiple window opened with IEDriver.

### ISSUE THREAD

**Issue by sumitsharma15** [SeleniumHQ/selenium#2450]
OS:  
Windows 7
Selenium Version:  2.53.1
Browser:  Internet Explorer

Hi,

I have one issue with IEDriver. In my application when multiple window opened with IE driver and when i am trying to get all window handles, it is returning only 1 value in Set. I am using the latest version of IEDriver.exe file 64-bit. Latest Selenium Server and IE11 browser. Please help me in this as i am stuck to automate application.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by sumitsharma15** [comment]
Hi,

This is an issue as when i am doing Set<String> handles = driver.getWindowHandles(); it return only 1 value but expected result should be 2 when there are 2 window opened with IE driver instance. I have executed the same scenario on FF browser and driver.getWindowHandles(); return the expected output as 2.
This issue is related to the IE browser Only.
I am using IE11 browser.

PFB the code example i am using

driver.get(any url)
driver.click(element)--- here click on link which opens the different window.

String handle = driver.getWindowHandle();-- return 1 value as expected

Set<String> allhandles = driver.getWindowHandles();
Syso(allhandles.size())---- return only 1 but it should return 2 size.

**Comment by lukeis** [comment]
you need to provide a complete reproducible scenario, including the url and/or provide the html with css/javascript that reproduces your problem. We already have generic tests in the selenium project that cover window switching.

**Comment by stabarinde** [comment]
@lukeis this issue has been reported a number of times to SeleniumHQ and you keep closing them as non-issues, as if they're reported in isolation. 

The OP has provided enough methodology to work with. Most submitters will not be able to contribute their full stack of software, or the site against which they're testing (due to size or NDA), but it's very clear from the issues as submitted that this is *not* an issue with the site under test. It *is* an issue with the way Selenium handles IE 11 browser handles. 

If you have generic tests in selenium, maybe you could try applying them to IE 11, since *several* people have reported the issue.

**Comment by jimevans** [comment]
@stabarinde The statement "If you have generic tests in selenium, maybe you could try applying them to IE11" is patently offensive. The project does have a fairly extensive test suite, and one that includes tests that create multiple windows. They run without failure in IE11; I know because I've run them myself. The reason we keep closing the issues is because there's no action that can be taken on them. I'm a reasonably competent software developer, but maybe not competent enough, because I haven't been able to build the skill of fixing what I can't reproduce. It's comments like this one that have made me recently begin to question my continued involvement in contributing to open source software.

**Comment by stabarinde** [comment]
Apologies for my previous comment @jimevans  - it was poorly phrased and bang out of order. Duly removed.

**Comment by jimevans** [comment]
@stabarinde Thank you for the apology. I do appreciate it. That's rarely the outcome for conversations like this one.
