### ISSUE TITLE
Blur event freezes the process

### ISSUE THREAD

**Issue by dromero-7854** [SeleniumHQ/selenium#2460]
## Meta -
OS: Windows 7
Selenium Version: Internet Explorer Driver Server 2.53.1
Browser:  IExplorer 
Browser Version:  11.0.9600.18349CO

## Expected Behavior -
Continue with the process
## Actual Behavior -
The process freezes
## Steps to reproduce -
I have a validation in a field that throws an alert message when focus lost (I use blur event to simulate this, and I need test the validation message) if the field value is wrong. 

The blur event throws the validation alert message but the process freezes and never finish. The process waits for the confirmation message.

This is the code example:
new JavascriptLibrary().callEmbeddedSelenium(this.getWebDriver(), "doFireEvent", this.getDriver().findElement(By.xpath("//input[@name='codigoBeneficiario']")), "blur");

**Comment by lukeis** [comment]
can you attempt to run this script manually in the IE dev tools?

https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/com/thoughtworks/selenium/webdriven/injectableSelenium.js#L72-L74

that method is called with (<your dom element>, 'blur', false)  the rest of the parameters are undefined.

So try this in the IE dev tools console while on your page:

    document.querySelectorAll("input[name='codigoBeneficiario']")[0].fireEvent('onblur', document.createEventObject());


Otherwise there's not much someone else can do without your page in question and I'll need to close this issue since no one will be able to reproduce it

**Comment by dromero-7854** [comment]
I'll try that. Clarification : I am using java. I'll use executeScript() method on driver object.

**Comment by lukeis** [comment]
would be better to remove webdriver from the equation and isolate the issue

**Comment by dromero-7854** [comment]
Sorry, but I don't understand. I updated the issue for more information. I'm new in web driver. In the project we can't use another tool.

**Comment by lukeis** [comment]
i was recommending to run the script directly with IE, similar to how firefox / chrome have "Dev Tools" where you can run arbitrary javascript in a console. Not recommending using another tool.

**Comment by jimevans** [comment]
The reported behavior makes perfect sense. An alert stops JavaScript processing until dismissed. You're using a JavaScript function to fire an event that displays an alert, which, in turn, stops JavaScript processing until dismissed. Don't fire the blur event using JavaScript. Do it some other way.

**Comment by dromero-7854** [comment]
mmm Ok... But I'm creating JUnit Test with Java. And I can't use dev tools. 

If I try this code:
this.getDriver().executeScript("document.querySelectorAll(\"input[name='codigoBeneficiario']\")[0].onblur()");
I have the same result.

With Firefox and Chrome driver works fine. Throws the alert and continue with the rest codes lines. I cant get the validation message and close the alert. So I think is a IEDriver problem. 

The JUnit test throws the validation alert message but the process freezes and never finish. The process waits for the confirmation of the message. 

Please, I tried this in many ways (the sendKeys methos doesn't work in IE, I hate IE jaja)

I need to get the message, close the alert and continue with the test.

help!! :-P

**Comment by dromero-7854** [comment]
¿How can I shoot the event without run Javascript code in JAVA?

**Comment by lukeis** [comment]
I totally missed the Alert part of this... Alert is blocking in javascript, if you trigger one, the script will wait forever to get a response.

In order to avoid this you should not rely on the Selenium JavascriptLibrary to fire the event, rather do it yourself and wrap it in a setTimeout() to allow non-blocking of the webdriver command:

    driver.executeScript("var el=arguments[0];setTimeout(function(){el.onblur();}, 10);", yourWebElement);

**Comment by dromero-7854** [comment]
Thanks lukeis!! It works!! you made my day jaja 
Since yesterday I 'm working on this problem...

Thanks again...
