### ISSUE TITLE
Selenuim-webdriver: how to use the firefox profile in a remote machine to launch firefox in that machin

### ISSUE THREAD

**Issue by zqy2084** [SeleniumHQ/selenium#2467]
2 machines A, B
I want to use selenium web driver to launch machine B's firefox from machine A with one of the profiles P1 on machine B.
The way i know is I have to copy P1 from B to A, then create a firefox_profile instance with the copied P1 on A. Then call Remote to launch firefox on B with this profile instance from A.

I have tried to new a firefox Options instance and add argument '-p P1', then launch Remote ff with this Options instance. And I found the arguments do NOT work any way.

Is there a way I don't have to copy the remote firefox profile to launch a remote firefox?

A: debian 8.3
B: windows 8
selenium-server-standalone-2.53.1.jar in used.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
