### ISSUE TITLE
[Need Help] Marionnette firefox proxy

### ISSUE THREAD

**Issue by elhorla** [SeleniumHQ/selenium#2471]
OS:  Windows 8
Selenium Version: Last  , C#
Browser:  Firefox

Hi ,
I try to set up an http proxy but i don't know how i can proceed 

                startInfo.WindowStyle = System.Diagnostics.ProcessWindowStyle.Hidden;
                var driverService = FirefoxDriverService.CreateDefaultService();
                driverService.FirefoxBinaryPath = @"C:\Program Files (x86)\Mozilla Firefox\firefox.exe";
                driverService.HideCommandPromptWindow        = true;
                DesiredCapabilities cap = new DesiredCapabilities();
                cap.SetCapability("marionette", true);

                driver = new FirefoxDriver(driverService, new FirefoxOptions(), TimeSpan.FromSeconds(30));
                

                Proxy proxy = new Proxy();
                proxy.HttpProxy = "flfl";
                DesiredCapabilities des = new DesiredCapabilities();
                des.SetCapability(CapabilityType.Proxy, proxy);

                driver = new FirefoxDriver(des);
       `

Thx

**Comment by jimevans** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/m/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
