### ISSUE TITLE
How to use selenium sending keys to this hideNameInput?

### ISSUE THREAD

**Issue by FantasRu** [SeleniumHQ/selenium#2501]
OS X:  10.11.6 (15G31)

Selenium Version:  python selenium (2.53.2)

Browser:  Firefox

**here is the elements,i want input something into the nameNoteId.**

    <span class="table_n_abs" onclick="hideNameInput()" id="nameNoteId" style="top: 10px; font-size: 14px; font-family: 微软雅黑; display: block;">邮箱/手机号/帐号</span>

**here is the codes:**

    from selenium import webdriver
    from selenium.webdriver.common.keys import Keys
    
    import time
    url = 'http://passport2.chaoxing.com/login?fid=1479&refer=http://i.mooc.chaoxing.com'
    # driver = webdriver.PhantomJS()
    driver = webdriver.Firefox()
    driver.get(url)
    time.sleep(1)
    elem = driver.find_element_by_id('passwordId')
    elem.send_keys('CNM')
    not_work_elem = driver.find_element_by_id('nameNoteId')
    not_work_elem.click()
    not_work_elem.send_keys('test')
    
    time.sleep(10)
    driver.close()

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
