### ISSUE TITLE
C#: Firefox: Cannot disable addons.manager and addons.xpi DEBUG message. 

### ISSUE THREAD

**Issue by tonycjr** [SeleniumHQ/selenium#2508]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by tonycjr** [comment]
C#: Firefox: Cannot disable addons.manager and addons.xpi DEBUG message.

**Comment by tonycjr** [comment]
How do you turn off the addons.* DEBUG message via the Firefox browser?

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
