### ISSUE TITLE
Firefox issue with selenium 2.53.1

### ISSUE THREAD

**Issue by hardi1501** [SeleniumHQ/selenium#2512]
## Meta -
OS:  Windows 

Selenium Version:  2.53.1

Browser:  Firefox

Browser Version:  47

## Expected Behavior -
It should run with Firefox.  

## Actual Behavior -
Currently I am using selenium 2.52.0 and it works fine with my application.
To add support for latest browsers, We upgraded it to 2.53.1 and encountered lot of errors.

I can see there is total 9mb of diffrence in both .jar files. So can you give me list of dependencies you have removed form 2.53.1? 
If i add them as external dependancy,there is possibility that my errors may have gone.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
