### ISSUE TITLE
IE is unable to click on selector

### ISSUE THREAD

**Issue by timbru31** [SeleniumHQ/selenium#2516]
## Meta -

OS: Windows 7 Enterprise SP1 x86 (modern.ie virtual machine)
Selenium Version: 2.53.1
Browser:  Internet Explorer 10
Browser Version: 10.0.9200.17148
## Expected Behavior -

The browser is able to click on the selector `.table-category .separating-list-item:nth-child(1) .button.button--primary`
## Actual Behavior -

IE reports `Cannot click on element` and fails.
Chrome, Safari, Firefox are working fine.
## Steps to reproduce -

Visit the following page
https://www.volkswagen.es/app/configurador/vw-es/es/polo/30205/36210/bluemotion/6C12LN-GPJZPJZ-MSNRS3C-GWB1WB1-GZBEZBE/2017/0/F14%202B2B/F56%20%20%20%20%20RU/+?page=exterior

try to click on the selector `.table-category .separating-list-item:nth-child(1) .button.button--primary`
## Additional information

Here is a debug log of the InternetExplorerDriver  
https://pastebin.com/bVyLSXc9

**Comment by barancev** [comment]
Unfortunately it's impossible to use the provided sample to reproduce the issue, the target page does not contain an element by selector `.table-category .separating-list-item:nth-child(1) .button.button--primary`. If the issue is still actual please request reopening it with an updated code sample.
