### ISSUE TITLE
Where can I download a signed Selenium Assembly for DotNet?

### ISSUE THREAD

**Issue by AcousticGuitar** [SeleniumHQ/selenium#2519]
Are there  signed versions of OpenQA.Selenuim and Selenium support?
Are there signed versions of Chromedriver?

I need them to integrate with another secure assembly requiring it.

Thanks!

**Comment by jimevans** [comment]
As always, the official release point for the .NET bindings is http://selenium-release.storage.googleapis.com/index.html. You will find strong-named versions of the Selenium assemblies there. Releases are pushed to NuGet as a courtesy; not as an official release point, and there will be no strong-named package released via NuGet.

**Comment by AcousticGuitar** [comment]
Thanks Jim Evans!

**Comment by ae1king** [comment]
Hi Jim,

I understand that this issue is closed, but I would like to understand the reasoning behind this?
On our team we are required to produce a CLS Compliant Code base for all of out projects, and the preferred method of aquiring libaries is through Nuget, and is now the generally accepted way of gathering libaries.

So please would you be able to let me know why nuget libaries are not signed, or even why, if you have signed libaries that you release unsigned libararies?

Regards

Andy
