### ISSUE TITLE
webelement::get_attribute returns non-None (null) value for non-existing tags

### ISSUE THREAD

**Issue by mehmetg** [SeleniumHQ/selenium#2525]
## Meta -
OS:  
MacOs
Selenium Version:  
Client Python 2.53.6 , Server 2.53.1, ChromeDriver 2.22
Browser:  
Chrome, Firefox
-->

Browser Version:  
Fails on: FF 47.0.1, Chrome  51.0.2704.106 (64-bit)
Works on:  Edge 13
## Expected Behavior -
For non-existing tags the server should return None.
## Actual Behavior -
The server/client lib returns an empty unicode string ```u''``` 
## Steps to reproduce -
*Failure*:
Req body: ```{"sessionId": "4bd1ef02-3a08-4b0d-b700-2b6c2b892c0a", "name": "style", "id": "31"}```
Response body: ```{"state":"success","sessionId":"4bd1ef02-3a08-4b0d-b700-2b6c2b892c0a","hCode":1500749704,"value":"","class":"org.openqa.selenium.remote.Response","status":0}```
*Success*:
Req body: ```'{"sessionId": "2828bfad26d7437fa528b8105690f4ac", "name": "style", "id": "31"}'```
Response body: ```'{"status": 0, "sessionId": "2828bfad26d7437fa528b8105690f4ac", "value": null, "state": "success", "hCode": 23251683, "class": "org.openqa.selenium.remote.Response"}'```

**Comment by mehmetg** [comment]
Note that the Edge response matches the docs and the FF and Cr ones do not. 
The tag requested is `style` AFAIK there's nothing special about it.  Any guidance on workarounds or correct usage is appreciated. 

Thanks.

**Comment by lukeis** [comment]
this is being solved in the w3c spec by having separate end points for attribute and property-

https://w3c.github.io/webdriver/webdriver-spec.html#get-element-attribute
https://w3c.github.io/webdriver/webdriver-spec.html#get-element-property

Firefox and Chrome here still follow the JSONWP method, which is a munging of the two. It's behavior is as you saw, because after finding the attribute didn't exist, it would check the property of the element (thus getting an empty string, since style exists as a property on every dom element).

An API will be forthcoming with the separation in the Selenium library, but not guaranteed until version 4.0
