### ISSUE TITLE
WebDriver 2.53.1 - Java8, Firefox 47 - default user profile, browser crashes

### ISSUE THREAD

**Issue by acolomitchi** [SeleniumHQ/selenium#2527]
## Meta -
OS:  ubuntu 14.04, 64 bit
Selenium Version:  2.53.1
Browser:  Firefox 47

Java bindings (maven dependency to selenium-java, version 2.53.1):

`acolomitchi@travel:~$ uname -a`
`Linux travel 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
`acolomitchi@travel:~$ firefox -version`
`Mozilla Firefox 47.0`
`acolomitchi@travel:~$ java -version`
`java version "1.8.0_101"`
`Java(TM) SE Runtime Environment (build 1.8.0_101-b13)`
`Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)`

## Steps to reproduce -
` FirefoxDriver w=new FirefoxDriver();`
`  w.navigate().to("https://maps.google.com");`

## Expected behavior -
Browser should open and maps.google.com page is shown

## Actual behaviour -
browser opens, stays empty for a little while, then crashes. Application throws an exception telling the browser might have exited.

**Comment by lukeis** [comment]
47.0 is known to have issues. You need to use 47.0.1

**Comment by acolomitchi** [comment]
S**t! When Ubuntu decided to release it as an update.

**Comment by lukeis** [comment]
You shouldn't rely on third party packaging... download / install it yourself:

https://www.mozilla.org/en-US/firefox/all/?q=English%20(US)

going to close since 47.0.1 will have the fix, we can reopen if the issue persists with the latest version

**Comment by sabeelathermggh** [comment]
Dear Team,

This issue is reproduced in the below environment. Kindly reopen and provide fixes. 

Operating System: Linux Ubuntu Version16.04, Architecture 64 bit
Selenium Version: 3.0.0b
Browser: Mozilla Firefox 49.0.2
**Console Output:**

org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
untu-paket för Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["uk"],"name":"Ubuntu Modifications","description":"Убунтівські доповнення до Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["zh-CN"],"name":"Ubuntu Modifications","description":"Ubuntu 火狐扩展包.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["zh-TW"],"name":"Ubuntu Modifications","description":"Ubuntu Firefox 擴充包。","creator":"Canonical Ltd.","homepageURL":null}],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"9.0","maxVersion":"37.0a1"}],"targetPlatforms":[],"multiprocessCompatible":false,"seen":true}
1477980818526	DeferredSave.extensions.json	DEBUG	Save changes
1477980818526	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1477980818526	addons.xpi-utils	DEBUG	Updating add-on states
1477980818528	addons.xpi-utils	DEBUG	Writing add-ons list
1477980818530	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1477980818531	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1477980818532	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
1477980818532	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1477980818532	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi
1477980818533	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.3
1477980818533	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi
1477980818534	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-bn-IN@firefox.mozilla.org.xpi
1477980818535	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-bn-BD@firefox.mozilla.org.xpi
1477980818536	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi
1477980818539	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1477980818540	addons.manager	DEBUG	Provider finished startup: XPIProvider
1477980818540	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1477980818540	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1477980818540	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1477980818540	addons.manager	DEBUG	Starting provider: GMPProvider
1477980818547	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1477980818547	addons.manager	DEBUG	Provider finished startup: GMPProvider
1477980818547	addons.manager	DEBUG	Starting provider: PluginProvider
1477980818547	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1477980818548	addons.manager	DEBUG	Provider finished startup: PluginProvider
1477980818548	addons.manager	DEBUG	Completed startup sequence
1477980819953	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1477980819953	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1477980819953	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1477980819959	DeferredSave.extensions.json	DEBUG	Starting write
1477980820097	addons.repository	DEBUG	No addons.json found.
1477980820098	DeferredSave.addons.json	DEBUG	Save changes
1477980820102	DeferredSave.addons.json	DEBUG	Starting timer
1477980820121	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1477980820121	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1477980820122	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1477980820125	DeferredSave.extensions.json	DEBUG	Write succeeded
1477980820126	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1477980820156	DeferredSave.addons.json	DEBUG	Starting write
1477980820314	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:315)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:118)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:232)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:220)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:215)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:124)
	at package_week11.Day1Class_SmokeFirefoxLaunch.main(Day1Class_SmokeFirefoxLaunch.java:14)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows: 
untu-paket för Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["uk"],"name":"Ubuntu Modifications","description":"Убунтівські доповнення до Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["zh-CN"],"name":"Ubuntu Modifications","description":"Ubuntu 火狐扩展包.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["zh-TW"],"name":"Ubuntu Modifications","description":"Ubuntu Firefox 擴充包。","creator":"Canonical Ltd.","homepageURL":null}],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"9.0","maxVersion":"37.0a1"}],"targetPlatforms":[],"multiprocessCompatible":false,"seen":true}
1477980818526	DeferredSave.extensions.json	DEBUG	Save changes
1477980818526	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1477980818526	addons.xpi-utils	DEBUG	Updating add-on states
1477980818528	addons.xpi-utils	DEBUG	Writing add-ons list
1477980818530	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1477980818531	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1477980818532	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
1477980818532	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1477980818532	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi
1477980818533	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.3
1477980818533	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi
1477980818534	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-bn-IN@firefox.mozilla.org.xpi
1477980818535	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-bn-BD@firefox.mozilla.org.xpi
1477980818536	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi
1477980818539	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1477980818540	addons.manager	DEBUG	Provider finished startup: XPIProvider
1477980818540	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1477980818540	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1477980818540	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1477980818540	addons.manager	DEBUG	Starting provider: GMPProvider
1477980818547	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1477980818547	addons.manager	DEBUG	Provider finished startup: GMPProvider
1477980818547	addons.manager	DEBUG	Starting provider: PluginProvider
1477980818547	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1477980818548	addons.manager	DEBUG	Provider finished startup: PluginProvider
1477980818548	addons.manager	DEBUG	Completed startup sequence
1477980819953	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1477980819953	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1477980819953	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1477980819959	DeferredSave.extensions.json	DEBUG	Starting write
1477980820097	addons.repository	DEBUG	No addons.json found.
1477980820098	DeferredSave.addons.json	DEBUG	Save changes
1477980820102	DeferredSave.addons.json	DEBUG	Starting timer
1477980820121	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1477980820121	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1477980820122	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1477980820125	DeferredSave.extensions.json	DEBUG	Write succeeded
1477980820126	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1477980820156	DeferredSave.addons.json	DEBUG	Starting write
1477980820314	DeferredSave.addons.json	DEBUG	Write succeeded

Build info: version: 'unknown', revision: '2aa21c1', time: '2016-08-02 14:59:43 -0700'
System info: host: 'personal-laptop', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-45-generic', java.version: '1.8.0_91'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:125)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:315)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:118)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:232)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:220)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:215)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:124)
	at package_week11.Day1Class_SmokeFirefoxLaunch.main(Day1Class_SmokeFirefoxLaunch.java:14)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
untu-paket för Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["uk"],"name":"Ubuntu Modifications","description":"Убунтівські доповнення до Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["zh-CN"],"name":"Ubuntu Modifications","description":"Ubuntu 火狐扩展包.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["zh-TW"],"name":"Ubuntu Modifications","description":"Ubuntu Firefox 擴充包。","creator":"Canonical Ltd.","homepageURL":null}],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"9.0","maxVersion":"37.0a1"}],"targetPlatforms":[],"multiprocessCompatible":false,"seen":true}
1477980818526	DeferredSave.extensions.json	DEBUG	Save changes
1477980818526	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1477980818526	addons.xpi-utils	DEBUG	Updating add-on states
1477980818528	addons.xpi-utils	DEBUG	Writing add-ons list
1477980818530	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1477980818531	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1477980818532	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
1477980818532	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1477980818532	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi
1477980818533	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.3
1477980818533	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi
1477980818534	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-bn-IN@firefox.mozilla.org.xpi
1477980818535	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-bn-BD@firefox.mozilla.org.xpi
1477980818536	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi
1477980818539	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1477980818540	addons.manager	DEBUG	Provider finished startup: XPIProvider
1477980818540	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1477980818540	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1477980818540	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1477980818540	addons.manager	DEBUG	Starting provider: GMPProvider
1477980818547	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1477980818547	addons.manager	DEBUG	Provider finished startup: GMPProvider
1477980818547	addons.manager	DEBUG	Starting provider: PluginProvider
1477980818547	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1477980818548	addons.manager	DEBUG	Provider finished startup: PluginProvider
1477980818548	addons.manager	DEBUG	Completed startup sequence
1477980819953	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1477980819953	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1477980819953	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1477980819959	DeferredSave.extensions.json	DEBUG	Starting write
1477980820097	addons.repository	DEBUG	No addons.json found.
1477980820098	DeferredSave.addons.json	DEBUG	Save changes
1477980820102	DeferredSave.addons.json	DEBUG	Starting timer
1477980820121	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1477980820121	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1477980820122	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1477980820125	DeferredSave.extensions.json	DEBUG	Write succeeded
1477980820126	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1477980820156	DeferredSave.addons.json	DEBUG	Starting write
1477980820314	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
	... 8 more
![gh 2527_browser crashes _ url not entering](https://cloud.githubusercontent.com/assets/23184695/19881832/0c14be14-a02f-11e6-8739-f6b5160ee7c4.png)


**Evdience:**
![gh 2527_browser crashes _ url not entering](https://cloud.githubusercontent.com/assets/23184695/19881854/38bf1f90-a02f-11e6-9b81-803190f9f463.png)

#2528
