### ISSUE TITLE
How Selenium Grid chooses the node to execute the test case?

### ISSUE THREAD

**Issue by devanshagr** [SeleniumHQ/selenium#2535]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by devanshagr** [comment]
Hi, the link "selenium user group" seems not to be working. Can you pls provide me the correct link. Sorry  new user here. :-)

**Comment by devanshagr** [comment]
Oh crap! My organization was blocking the link. Will post the question from home.
