### ISSUE TITLE
Unable to interact with the chrome alerts version 52.*(latest version)

### ISSUE THREAD

**Issue by hemanthsridhar** [SeleniumHQ/selenium#2563]
**OS**:  Windows
**Selenium Version**:  2.53.1(Any version)
**Browser**: Chrome
**Browser Version** : 52.* (latest version)
The test suite simply gets stuck when the alert pops up and there is no way to communicate.
When reverted to version 51.* (or any other prior versions), I was able to interact with the alert.

**Comment by sujay88** [comment]
have you tried on ChromeDriver 2.22 ?

https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by lukeis** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net

**Comment by hemanthsridhar** [comment]
@lukeis  as you say brother.

**Comment by hemanthsridhar** [comment]
@sujay88  : not working bro :)

**Comment by DivitaN** [comment]
I am having the same issue with Chrome version 52, Unfortunately I cannot upgrade my browser since these settings are controlled by network admin. 

I get the following error message when I try to open google.com with elementor module of protractor-
17:24:33.983 WARN - Exception: unknown error: Chrome version must be >= 53.0.278
5.0

Did you downgrade the chrome driver version, if so, how?
