### ISSUE TITLE
How to pass Firefox profile within console as argument?

### ISSUE THREAD

**Issue by novacp** [SeleniumHQ/selenium#2573]
I am starting Selenium(3) jar file from within the command line using:
"java -jar selenium.jar"

How can I specify within the console, which firefox profile it should use?
When using webdriver for selenium 2.x, I could use the option "-firefoxProfileTemplate", which seems to not exist anymore for selenium 3.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by lukeis** [comment]
you should use DesiredCapabilities with creating your webdriver Firefox instance. If you're not using WebDriver, this option is no longer supported
