### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by mea95** [SeleniumHQ/selenium#2574]
1) I find some issues when using selectWindow command: it's not working even if I put 'WaitForPopUp' (failure) or 'WaitForPageToLoad' (doesn't wait at all)

2) When I use selectWindow and I put a breakpoint on it , and then I put a starting point on it and execute it , it works.  How can I solve this issue?

3) I can't save my breakpoints ... is there any way to save them? 

4) How do I get the window ID? 

5) Is there a way to select a window if it opens in a new tab? It's working with me when it opens in the same tab or in a PopUp window but it doesn't when it opens in a new tab page 

Thanks in advance

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
