### ISSUE TITLE
SafariDriver: should not yet be deprecated

### ISSUE THREAD

**Issue by mfulton26** [SeleniumHQ/selenium#2584]
I was surprised to learn that SafariDriver is deprecated. I understand that Safari 10 implements the WebDriver API but this doesn't mean that we don't still need support for Safari 9, 8, etc. Why discourage the use of the existing SafariDriver? There is nothing to supersede it for current and recent Safari versions and it isn't considered "unsafe". I think it would be better to un-deprecate it and mark it is "support-only" or something similar that explains that the only further development planned is for bugs but that the tool will not be updated for the latest Safari versions.

**Comment by jleyba** [comment]
Ok, I'm going to be blunt here. It has been over **FOUR YEARS** since [I announced](https://groups.google.com/d/msg/selenium-developers/46dyOipF9PE/BlrWYpoD5akJ) I would no longer be actively working on the SafariDriver. In that time, excluding a few minor patches, no one has stepped forward to maintain the driver—the driver has basically sat unchanged for several years now.

The driver is deprecated, will remain deprecated and will be removed when MacOS Sierra ships.

**Comment by mfulton26** [comment]
I did not realize that it had been over four years, etc. I personally appreciate your bluntness. Thank you.
