### ISSUE TITLE
trouble setting up NON - headless - in Ubuntu 14.04

### ISSUE THREAD

**Issue by spencer1573** [SeleniumHQ/selenium#2585]
## Meta -
OS:  
Ubuntu 14.04 or 16.04
Selenium Version:  
latest
Browser:  
chrome

I've been looking everywhere for how to install and set it up so that it works with nodejs. 

what is the easiest way to set up everything to run a simple test in ubuntu with node with chromewebdriver?

thanks!

**Comment by ddavison** [comment]
have you tried using X?  if you are running non-headless, you need to have a UI for selenium to run.  you can use x, or you can use the `ubuntu-desktop` package in aptitude.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
