### ISSUE TITLE
Selenium getText is normalizing white space

### ISSUE THREAD

**Issue by leolorenzoluis** [SeleniumHQ/selenium#2608]
## Meta -
OS:  Windows 7
Selenium Version:  2.46
Browser:  Internet Explorer

Browser Version:  
11.0.9600.18349

## Expected Behavior -
`getText` should not normalize spaces. For example, given a `WebElement` that has a text of "Hello  World", `getText` should return "Hello  World"
## Actual Behavior -
`getText` is not normalizing white spaces. The return value becomes "Hello World"

## Steps to reproduce -
1. Create an HTML Page with a span tag of simple text "Hello  World"
2. Using Selenium, access the `WebElement` and do `getText()`
3. Observe that the value is changed to "Hello World"

**Comment by lukeis** [comment]
https://w3c.github.io/webdriver/webdriver-spec.html#get-element-text
http://rocallahan.github.io/innerText-spec/index.html

So, selenium does normalize space, see spec references linked. Your issue also demonstrates exactly why we do... if you come to this page and view it every instance of "Hello  World" is rendered with only one space, browsers normalize space and it's what users see too. If you were highlight / copy / paste, the result also would only have one space.

We won't be changing this behavior unless browsers themselves change their behavior.

**Comment by leolorenzoluis** [comment]
@lukeis Thank you for refering the specs. Makes sense now. However, would it be possible then to have a separate method that doesn't normalize the text such as `getTextContent()`? For example. an instance can use `textContent` property to preserve the space.

**Comment by lukeis** [comment]
you can always call that directly?  `element.getAttribute("textContent")` or use executeScript

**Comment by sjethvani** [comment]
Thanks for getAttribute("textContent") workaround . 

_Explanation of issue (in case someone wants)_
I was fetching some webelements using findElements() and then iterating through each one and calling getText() on each webElement . I noticed that for some webElements getText() was returning value after ignoring some white spaces (for ex : Instead of 'VIP  - Archived' it was returning 'VIP - Archived ' , see that expected value has 2 spaces before hyphen '-') . getText() was ignoring an extra white space before hyphen , however getAttribute("textContent") returned exact value of element (which is 'VIP  - Archived' , with 2 spaces before hyphen) .
