### ISSUE TITLE
Have ceased запускться autotests from Jenkins after the browser chrome was updated to version 52.0.2743.116 m (64-bit) Tests worked at the previous version steadily. Tests are written on C# with use of Silenium and are started steadily only from Visual Studio. It is necessary for me that tests were started from Jenkins.

### ISSUE THREAD

**Issue by cont-inik** [SeleniumHQ/selenium#2618]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
