### ISSUE TITLE
Is it possible to download files to the test machine during a grid test?

### ISSUE THREAD

**Issue by abelfiore** [SeleniumHQ/selenium#2656]
I have a Selenium Grid with nodes set up for my automated testing (on windows machines). I have successfully used the LocalFileDetector approach when I have tests (.NET Selenium v2.53.1) that need to *upload* files (from my test/build machine to the node).

I was wondering if it was possible to *download* files from my Grid node to my test machine - similar to LocalFileDetector for uploads. I would really like my test logic/machine to verify the file that was downloaded.

What is the recommended approach for such scenarios?

Any advice would be greatly appreciated.

Thanks.

--Tony

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by abelfiore** [comment]
Sorry, Thanks.
