### ISSUE TITLE
Selblocks Selenium IDE ERROR

### ISSUE THREAD

**Issue by blancoleandro13** [SeleniumHQ/selenium#2696]
OS:  
Windows 7 64bit
Selenium Version:  
Selenium IDE 2.9.1
Browser:  
Firefox

Browser Version:  
48.0.2 Version Firefox

Greetings.

  I'm starting in the world of Selenium-IDE, install selblocks to use the "If-Else-endIf"

but it gives the following error before starting:

"There was an unexpected error. Msg: uncaught exception: undefined
Url: chrome://global/content/globalOverlay.js, line: 100, column: 7"

I have Selenium IDE Selblocks 2.1.1

I search the forums and I have no answer, someone could help me?

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by lukeis** [comment]
Also you should log this bug with the 'Selblocks' project https://github.com/refactoror/SelBlocks

**Comment by blancoleandro13** [comment]
I'll ask the question in https://github.com/refactoror/SelBlocks

Thank you
