### ISSUE TITLE
What to use in place of getInnerHtml and getOutterHtml?

### ISSUE THREAD

**Issue by JemiloII** [SeleniumHQ/selenium#2703]
So before 3.0 hits, I want to update my tests, however I can't find what I should be using in place of getInnerHtml and getOutterHtml, or even find the discussions to why it's being removed. Any help would be appreciated!

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by jleyba** [comment]
These were removed from the JS API for consistency with the other language bindings. You can use `executeScript` instead (which is all they were doing):

```js
let el = driver.findElement(By.id("foo"));

function getIInnerHtml(el) {
  return driver.executeScript("return arguments[0].innerHTML;", el);
}

function getOuterHtml(el) {
  return driver.executeScript("return arguments[0].outerHTML;", el);
}
```

These methods were initially deprecated in 2.53.0, and have been removed for 3.0.

API changes are always documented in [CHANGES.md](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md), which is also included with the published [API docs](http://seleniumhq.github.io/selenium/docs/api/javascript/Changes.html) and with the `selenium-webdriver` npm package.

**Comment by JemiloII** [comment]
thanks!
