### ISSUE TITLE
Calendar under canvas is not recognized 

### ISSUE THREAD

**Issue by arkadiyala** [SeleniumHQ/selenium#2705]
OS:  
Windows 7 Enterprise
Selenium Version:  
2.53.0
Browser:  
45.3.0

## Expected Behavior -
Calendar properties has to be recognized by firebug.
## Actual Behavior -
Canvas is recognized by firebug(However calendar under canvas is not recognized by firebug).

## Steps to reproduce -
I'm working on MarkitEDM vendor tool. 
I need to enter Maturity date(Calendar) , however this calendar is under canvas. I'm unable to recognize object properties inside canvas. 

Please help me asap.

**Comment by lukeis** [comment]
Sorry, Selenium has nothing to do with firebug. I'm unsure what your issue here is. You might have better luck some questions on our google group:
https://groups.google.com/forum/#!forum/selenium-users

If you can, include a link to the page in question and describe in more detail what you're attempting to do
