### ISSUE TITLE
Legacy Safari Driver Window call

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#2709]
I'm not sure if we care about this, but fwiw it works locally and is broken on remote server.

`POST session/f1fd34ab-faf3-4656-bfda-ff6584b42241/window`

returns:

`org.openqa.selenium.WebDriverException: undefined is not an object (evaluating 'this.source_.addEventListener')` 

Full debug: 
https://gist.github.com/titusfortner/bbd16bc4e8f45760b6bc6ab93e5401e1

**Comment by lukeis** [comment]
at this point, no, no we don't care about the legacy safari driver :)  Unless you can see something obvious about how the standalone server is forwarding the request to it?

**Comment by titusfortner** [comment]
Right, I don't care enough to dig through the code, I just wanted it documented somewhere that it was working on beta2 and not working on beta3. Fine by me to close it if that's the decision. :)

**Comment by uchuugaka** [comment]
My experience thus far is to use an older 2.x version if you need the Legacy Safari Driver. Given that the native one is new, and doesn't give you backward compatibility, it's probably best to do that.
Although there's a flag to choose to use legacy in 3.x, it's kind of a moot point if nobody cares about it.

**Comment by pbi-qfs** [comment]
Legacy mode is important for systems, where no Safari 10 can be installed, and those will be around for some while. But currently, the legacy mode switch has some bugs, so there is no way to enable it in 3.0 beta3 (I marked the bugs directly on the corresponding commit 2a4fb06).

**Comment by jleyba** [comment]
@pbi-qfs Then someone from the community needs to step up real quick and start contributing to the legacy SafariDriver. Since I stopped actively working on the driver, __4 years ago__, we have received less than 10 pull requests for the driver. As it stands, the legacy SafariDriver will be ripped from existence the moment macOS and Safari 10 released to the general public.

I'm sorry if this comes across a bit harsh, but I'm really sick of the Selenium community complaining about the SafariDriver yet no one offers to do anything abou tit.

**Comment by uchuugaka** [comment]
What would be required to NOT remove it.
I'm interested, at least in keeping it alive, not necessarily majorly enhancing, at least as long as JavaScript based extensions are available in Safari and can connect WebSockets.

If you have any useful notes from when you were actively working on the driver, I would love to take a look at them.
It's not a small bit of code, and it's inside a sprawling multi-platform codebase & build system, so anything helps.
There are even some areas I'd be interested in enhancing or fixing.

I run 2.47.1 because it's close to the last time I saw any major changes to the extension.
And in part, because I've seen errors in 3.0b due to changes in Selenium, not in the extension.

I'm not convinced to migrate to the native one yet, because it cannot click things. (at least from Python) And it also doesn't work on older installs.
There just hasn't been a hugely evident amount of testing on that to assume it works well enough yet. Legacy works quite well, with a few known issues that are as much architectural to Safari as anything.
I'm all for moving forward, but breaking backward, especially with something new and not vetted yet, seems a little rough.

**Comment by pbi-qfs** [comment]
@jleyba OK, I got the message. Here is the PR to revive the legacy mode in SafariDriver: #2733

It restores the pre-beta-3 status quo, so the test which ran before should now run again.

**Comment by titusfortner** [comment]
I can verify that this PR fixes the Window exceptions I was seeing.

**Comment by titusfortner** [comment]
We've decided to remove legacy safari driver from 3.0, so this is no longer an issue to be addressed.
