### ISSUE TITLE
Screenshot hangs up consuming excessive CPU for IE driver 2.53.1 64-bit

### ISSUE THREAD

**Issue by vipulnsward** [SeleniumHQ/selenium#2713]
## Meta -

OS:  
Windows Server 2012 on AWS (64 bit)

Selenium Version:  
2.53.1

Browser:  
Internet Explorer (64 bit)

Browser Version:  
11.0.9

IE Driver:  
2.53.1- 64 bit
## Expected Behavior -

Screenshot should work without any issues
## Actual Behavior -

Screenshot hangs up consuming excessive CPU.
## Steps to reproduce -
1. Set FEATURE key for browser as suggested 
2. dump of capabilities-

```
ie.enableFullPageScreenshot:false,webdriver.remote.quietExceptions:true,browserAttachTimeout:0,enablePersistentHover:true,ie.forceCreateProcessApi:true,pageLoadStrategy:normal,ie.usePerProcessProxy:false,ignoreZoomSetting:false,handlesAlerts:true,version:11,platform:WINDOWS,nativeEvents:false,ie.ensureCleanSession:true,requireWindowFocus:false,javascriptEnabled:true,ignoreProtectedModeSettings:false,enableElementCacheCleanup:true,cssSelectorsEnabled:true,unexpectedAlertBehaviour:dismiss
```
1. Set Zoom levels to 100%
2. Set zone to same levels
3. Take screenshot on page with some Ajax behaviour(page changes status)
4. IE driver maxes out CPU and hangs when trying to capture screenshot.

**Comment by jimevans** [comment]
I have two questions. First, can you provide log output from `IEDriverServer.exe`? Second, what happens when you use the 32-bit driver executable?

**Comment by etoperman** [comment]
@jimevans  Is this issue solved?

**Comment by diemol** [comment]
@etoperman, considering that the original poster never replied and that the versions that are mentioned in the original post are already several years old... I'd say that it was never an issue, otherwise the original poster would have replied with the requested information.

If you are facing something similar with the latest versions of the components, feel free to create a new issue filling out the complete template.

For now, I'll close this one since we didn't get any more useful replies.

**Comment by etoperman** [comment]
@diemol  I see, thank you
