### ISSUE TITLE
UrlChecker Thread in Selenium causes sun.misc.Unsafe.park on Tomcat context reload

### ISSUE THREAD

**Issue by coolfeature** [SeleniumHQ/selenium#2714]
WARNING: The web application [myapp] appears to have started a thread  named [UrlChecker-2] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
sun.misc.Unsafe.park(Native Method)

on tomcat context reload. 

http://stackoverflow.com/questions/39289762/urlchecker-thread-in-selenium-causes-sun-misc-unsafe-park-on-tomcat-context-relo

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
