### ISSUE TITLE
How to open new tab/window with same session with current ?

### ISSUE THREAD

**Issue by phunb3101** [SeleniumHQ/selenium#2715]
## Meta -
OS:  
Windows 7
Selenium Version:  
2.44.0
Browser:  
Internet Explorer 
Browser Version:  
11.0.9600.18282

## Expected Behavior -
Open link with current session
## Actual Behavior -
Open link with new session
## Steps to reproduce -
Hi Guys,

I have an issue with open new tab/window by selenium with current session,
currently, I opened new tab in IE by javascript windows.open('','_blank') but it only open new window with new session. May I know do we have anyway to open new window with same session with old window ?

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
