### ISSUE TITLE
UrlChecker Thread in Selenium causes sun.misc.Unsafe.park on Tomcat context reload

### ISSUE THREAD

**Issue by spc16670** [SeleniumHQ/selenium#2716]
## Meta -

OS:  
Windows 8.1

Selenium Version:  
2.53.1
Browser:  
Chrome

Browser Version:  
52.02
## Expected Behavior -

UrlChecker class provides a clean way to dispose the private THREAD_POOL.
## Actual Behavior -

sun.misc.Unsafe.park Exception on application shutdown
## Steps to reproduce -

1) create and start a ChromeDriver service in a tomcat application:

```
        chromeDriverService = new ChromeDriverService.Builder()
                .usingDriverExecutable(exe)
                .usingAnyFreePort()
                .build();
        chromeDriverService.start();
```

2) Trigger tomcat reload.

The issue is documented here:
http://stackoverflow.com/questions/39289762/urlchecker-thread-in-selenium-causes-sun-misc-unsafe-park-on-tomcat-context-relo

**Comment by lukeis** [comment]
I'm uncertain of why you're running selenium from within tomcat?  Also, I'm unclear what exception you're hitting? seems in your stackoverflow it's only a warning?

**Comment by coolfeature** [comment]
The exception stack is presented very clearly on SO. Tomcat logs this as a warning, in reality however this uncovers a problem this is potentially very serious if the application is run within any container, not neccessairly tomcat. In this particular example Tomcat will probably start leaking memory every time the app is reloaded.

The fix is relatively very simple. The thread needs to be gracefully stopped before the class is destroyed.

**Comment by lukeis** [comment]
> The fix is relatively very simple. The thread needs to be gracefully stopped before the class is destroyed.

Pull Requests appreciated.

UrlChecker appears to use a cached Thread pool that it passes into [SimpleTimeLimiter](https://github.com/google/guava/blob/master/guava/src/com/google/common/util/concurrent/SimpleTimeLimiter.java) (which is a google guava artifact). So your issue might be in guava

**Comment by diemol** [comment]
Closing as we never got more feedback from the OP
