### ISSUE TITLE
Delete the legacy SafariDriver

### ISSUE THREAD

**Issue by jleyba** [SeleniumHQ/selenium#2725]
This is a tracking bug for the deletion of the legacy SafariDriver.

Support should be removed in all language bindings when Safari 10 and Apple's safaridriver are released to the general public.

**Comment by pbi-qfs** [comment]
Since people out there will still use OS X systems which do not support Safari 10 for a while, we should delay this removal as long as supporting the legacy Safari Extension is possible with small coding effort, and as long as there are pull requests provided for those adaptations within reasonable time.

**Comment by jimevans** [comment]
Done in .NET with commit 9f5f45c

**Comment by lukeis** [comment]
@pbi-qfs OSX El Capitan has Safari 10 now. I certainly hope your IT department hasn't prevented you to update your system to that version of OSX. For those wishing to keep using the old safari driver, they can always use standalone server 2.53.1 on them.

**Comment by pbi-qfs** [comment]
@lukeis Safari 10 even installed fine on our Yosemite machines, except there is no webdriver option in the Dev menu, and no safaridriver in /usr/bin/. The deprecated extension however runs flawlessly on Safari 10 and as fast as never before...

Due to this, I would still really like to see PR #2733 merged, since it's no big deal to keep the legacy driver running as long as possible, since currently it doesn't produce maintenance work on your side or compromises in the rest of the selenium core.

**Comment by lukeis** [comment]
That's incorrect, this does produce maintenance work. As the Apple provided implementation becomes more W3C spec compliant we'll need to continue to diverge the two command codecs. Which looking at the PR, doesn't favor what simon's done with using inheritance to handle the differences in the command codecs.

We are planning on continuing to support 2.X nodes connecting to a 3.0 grid. So, if one chooses to continue to use older OSes / Browser versions. There's no reason they can't continue to do so with older versions of selenium. Same thing for using old versions of chrome or firefox. You have to use a corresponding old version of selenium to run with them.

**Comment by lukeis** [comment]
removed from java 11e5fa862664c63a3bfaf5a72726a81958db0ef4

**Comment by lukeis** [comment]
removed from python in 098063f9308179e98c968962cdcd9c1b98e2eceb
