### ISSUE TITLE
Selenium 3.0.0-beta3 node maxSession = 1 causes hub registration of default 5 instead of 1

### ISSUE THREAD

**Issue by james-crocker** [SeleniumHQ/selenium#2727]
## Meta -
OS:  Windows 10
Selenium Version:  
3.0.0-beta3 node (win10) and 3.0.0-beta3 hub (linux)
Browser:  
all
Browser Version:  
any

## Expected Behavior -
Setting node maxSession = 1 should restrict node's active sessions to one.

## Actual Behavior -
Setting node maxSession = 1 via command line argument or json causes registration at hub to be 5. Consequently the hub will spawn 5 concurrent sessions. Setting to maxSession = 2 or higher registers correctly on the hub.

## Steps to reproduce -
Set -maxSession 1 or in json configuration "maxSession": 1 causes registration at hub of maxSession: 5. Unregister node, set maxSession to 2 and registration correctly sets 2 and honors that value.

**Comment by james-crocker** [comment]
Related: setting hub maxSession = 1 results in maxSession being 1 (and for values >= 1).
However, the nodes registered maxSession is overridden by the hub maxSession if the hub's maxSession > node's maxSession.
So... (=> is the registered grid hub settings)
hubMaxSession=1, nodeMaxSession=2 (1 triggers default 5) => hubMaxSession:1, nodeMaxSession:2
hubMaxSession=2, nodeMaxSession=2 => hubMaxSession:2, nodeMaxSession:2
hubMaxSession=3, nodeMaxSession=2 => hubMaxSession:3, nodeMaxSession:3
etc..

**Comment by mach6** [comment]
Thanks @james-crocker. I've seen this and similar issues. Will look into it.

**Comment by mach6** [comment]
@lukeis The issue here is two-fold;

1. `maxSession` is updated on `merge()` iff the new value `!= 1`
2. `3.0.0-beta` changes the actual configuration precedence for remote proxies. In `2.x` remote configuration overrides hub/registry configuration for collisions. In `3.0.0-beta` hub/registry configuration overrides remote configuration for collisions. See `mergeConfig` in https://github.com/SeleniumHQ/selenium/blob/selenium-2.53.0/java/server/src/org/openqa/grid/internal/BaseRemoteProxy.java#L233-L250 for `2.x` and compare that to https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/internal/BaseRemoteProxy.java#L106-L110 in `3.0.0-beta`

I have a pending change set but need sync up with you at greater detail on the second part. I believe it is the root of this and other similar issues. Furthermore, I believe we should revert to 2.x behavior
