### ISSUE TITLE
Question : can i press two normal keys simultaneously in webdriver ?

### ISSUE THREAD

**Issue by venkat-gan** [SeleniumHQ/selenium#2738]
I want to press `w` and `a` simultaneously can i do that using selenium webdriver.

Attached
[htmlCode.zip](https://github.com/SeleniumHQ/selenium/files/461071/htmlCode.zip)

 the simple html code to log the pressed keys.

`keys = "w&&s".split("&&");
CharSequence[] allKeys = new CharSequence[keys.length];
element = driver.findElement(By.tagName("body"));
for (int i=0;i<keys.length;i++) {
	try {
	       allKeys[i]=Keys.valueOf(keys[i].trim());
        }
	catch(IllegalArgumentException e) {
	       allKeys[i]=keys[i].trim();
	}
}
String sendKeys = Keys.chord(allKeys);
element.sendKeys(sendKeys);
`

This is my Java code to press `w` and `s` simultaneously but it not pressing simultaneously. 
If press `SHIFT` and `W` it will work.

Please help me to solve this.

### WebDriver

**Comment by lukeis** [comment]
Have you tried using Actions?

    WebElement body = driver.findElement(By.tagName("body"));
    new Actions(driver).keyDown(body, "w").keyDown(body, "s").keyUp(body, "s").keyUp(body, "w").perform();

This isn't technically 'simultaneous' but close enough? I also don't believe the web allows one to handle 'multiple' key events, it only fires one at a time. So the code on your page has to be keeping track of the keys pressed in order to make something like two keys pressed at the same time work.

If you have further questions, please consider asking on the selenium-users google group:
https://groups.google.com/forum/#!forum/selenium-users
