### ISSUE TITLE
how to manage Faulty node from test code

### ISSUE THREAD

**Issue by jayantsarda** [SeleniumHQ/selenium#2752]
Hi , I have a situation where my android emulator nodes crashes occasionally. The reason for this could be long hrs of execution. In my emulator farm of 8 emulators ,if any one node crashes all the remaining test are executed on that node and fails for that device not found error. I tried to add a node recovery script for that node but by the time node comes back, all the tests are already failed.
My question: is there any way : 
1. I can block any more tests sent (from test code or grid config)  to this node till node is up and running again
2. I can quickly (with in 1 or 2 sec ) remove this node from grid (currently if we remove the node it take a min to unregister it from grid )

Or any other solution experts can suggest.

Thanks in advance.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
