### ISSUE TITLE
WebDriver is changing the context on click event of webelement in SPA

### ISSUE THREAD

**Issue by sshekhar89** [SeleniumHQ/selenium#2780]
## Meta -
OS:  
<!-- Mac 10.11.6 (15G1004) >
Selenium Version:  
<dependency>
	<groupId>org.seleniumhq.selenium</groupId>
	<artifactId>selenium-java</artifactId>
	<version>2.52.0</version>
</dependency>
Browser:  
Chrome

Browser Version:  
Version 52.0.2743.116 (64-bit)

Issue :
I am trying to do UI automaton of my product webpage. The product is in SPA architecture and we have used widget to load the content.

Page is divided into three part , top nav, left nav and widget container. On the click of left nav , content of widget is loaded in the container. 
The Webdriver has all the web element references. When i take the left nav web element and trigger the click event. The Webdriver only have  element reference  of left nav. it loses all other references (top nav,widget container). 

How do i get the reference back to the widget container web element ?

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
