### ISSUE TITLE
png

### ISSUE THREAD

**Issue by denis690** [SeleniumHQ/selenium#2781]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
