### ISSUE TITLE
Selenium not working on Ruby

### ISSUE THREAD

**Issue by fmauricios** [SeleniumHQ/selenium#2796]
When I execute ruby selenium-webdriver with a little example, selenium open my Firefox browser but not navigate to the URL. This only open the browser

Thanks for your help 👍

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
