### ISSUE TITLE
I have Eclipse Mars 2.0 (Release 4.5.2), Selenium-java 3.0.0 beta3 and Firefox 48.0.2. I am able to open the browser, but unable to perform any operations in it. It keeps telling that "source not found for firefox". I even tried to add the source path for firefox. Still didn't work. I am new to selenium. I am not sure if I should downgrade firefox.. or is it even possible to downgrade? .. Help required. Thanks in advance. - Dhivya

### ISSUE THREAD

**Issue by dhivya81** [SeleniumHQ/selenium#2802]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
