### ISSUE TITLE
Element is not clickable at point

### ISSUE THREAD

**Issue by edgonzalezj** [SeleniumHQ/selenium#2823]
## Meta -
OS:  
Windows 7
Selenium Version:  
2.52.0
Browser:  
Chrome

Hi!!!!

I'm testing my application with Selenium and i have problems when i try to select a RadioButton 
The error is 

Element is not clickable at point (45, 199). Other element would receive the click

I have the last version of Driver and Navegator.

I try to chage waits in driver, etc... but doesnt work.

Thank you.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by meet-sapu** [comment]
This issue was headache to me while writing a web scraping script in python , The solution for this came out to be simple , I simply scrolled down(or it could be up in your case) the webpage and then clicking the button worked for , as it turns out it the webdriver is firefox or internet explorer this is not n issue but it's an issue for chrome webdriver .
