### ISSUE TITLE
implicit wait and Waitfor page Load not working in selenium 3.0 beta with geckodriver. Does any body knows how to use implicit wait with selenium 3.0 beta version. As the following code is not working:

### ISSUE THREAD

**Issue by anukriti-chawla** [SeleniumHQ/selenium#2826]
driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

**Comment by lukeis** [comment]
works fine for me.

3.0.0-beta4
Firefox Nightly 52.0a1
geckodriver 0.10

    WebDriver driver = new FirefoxDriver();
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    driver.get("http://google.com");
    ((JavascriptExecutor)driver).executeScript("window.setTimeout(function(){var e = document.createElement('div'); e.id='testing'; document.body.appendChild(e);}, 5000);");
    assertEquals("div", driver.findElement(By.id("testing")).getTagName());

You will need to be more specific as to what is not work, what exception you are seeing, and a more complete code sample.

**Comment by phillipp** [comment]
In the current 3.x version, the ruby version says:
```
@driver.manage.timeouts.implicit_wait
```

This is exactly what the docs say you show use to set implicit wait (which does not seem to exist in 3.x any more, at least I needed to add wait and/or sleep's). The outdated docs (https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings#) said:

```
  driver = Selenium::WebDriver.for :firefox
  driver.manage.timeouts.implicit_wait = 3 # seconds
```

**Comment by titusfortner** [comment]
Yes, this has always been the case. In general I recommend against using implicit waits, which is why I haven't included an update with it.

http://elementalselenium.com/tips/47-waiting

**Comment by phillipp** [comment]
Wouldn't it be a good idea to add a depreciation notice, then (or a warning?)?Phillipp                                                                                                                                                                                                                                                                                                                                                     Von: TitusGesendet: Mittwoch, 19. Oktober 2016 20:02An: SeleniumHQ/seleniumAntwort an: SeleniumHQ/seleniumCc: phillipp; CommentBetreff: Re: [SeleniumHQ/selenium] implicit wait and Waitfor page Load not working in selenium 3.0 beta with geckodriver. Does any body knows how to use implicit wait with selenium 3.0 beta version. As the following code is not working: (#2826)Yes, this has always been the case. In general I recommend against using implicit waits, which is why I haven't included an update with it.

http://elementalselenium.com/tips/47-waiting

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SeleniumHQ/selenium","title":"SeleniumHQ/selenium","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SeleniumHQ/selenium"}},"updates":{"snippets":[{"icon":"PERSON","message":"@titusfortner in #2826: Yes, this has always been the case. In general I recommend against using implicit waits, which is why I haven't included an update with it.\r\n\r\nhttp://elementalselenium.com/tips/47-waiting"}],"action":{"name":"View Issue","url":"https://github.com/SeleniumHQ/selenium/issues/2826#issuecomment-254892390"}}}
