### ISSUE TITLE
Firefox not loading websites through Selenium proxy

### ISSUE THREAD

**Issue by CarloWakefield** [SeleniumHQ/selenium#2833]
## Meta -
OS:  Windows 7, 64 Bit
Selenium Version:  2.47.1, IntelliJ IDEA 2016.2.24
Browser:  Firefox
Browser Version:  41.0

## Expected Behavior -
Firefox is neither loading my application nor any other website through the Selenium proxy.
## Actual Behavior -
Firefox loading my application through the Selenium proxy.
## Steps to reproduce -
When I start a Selenium test a proxy is started successfully:
```
DefaultHttpProxyServer:448 - Starting proxy at address: 0.0.0.0/0.0.0.0:0
DefaultHttpProxyServer:477 - Proxy listening with TCP transport
DefaultHttpProxyServer:512 - Proxy started at address: /0:0:0:0:0:0:0:0:57982
```
Firefox is configured by Selenium to use this proxy. In the settings the proxy is set to my computer's name and to the port 57982.

Unfortunately no connection to a website can be established. Neither one to a page on my local server, nor one to google.com.

What could be the problem? How can I narrow down the problem?

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
