### ISSUE TITLE
Unable to make an input element visible to be able to upload an image

### ISSUE THREAD

**Issue by ruchikar** [SeleniumHQ/selenium#2853]
So as part of the test I click on an image placeholder to upload an image > it opens up the file explorer.

Now when am trying to automate the input filed looks like below:
<input id="photo0" class="hidden" type="file" name="images" multiple="">

And the associated css file has 
.hidden {
    display: none !important;
}

Tried lots of ways to make this input field visible using JSE, to be able to pass image path using:
String js = "arguments[0].style.display='block';";
((JavascriptExecutor) driver).executeScript(js, uploadPhoto);
uploadPhoto.sendKeys(filePath);

None of it is helping. Any idea wat can i do?

**Comment by twalpole** [comment]
Use JSE to remove the 'hidden' class from the element

**Comment by ddavison** [comment]
Hey there!

Looks as though your issue is actually a user issue rather than an issue with Selenium itself.  For these issues, we ask you to please use the [selenium users group](https://groups.google.com/forum/#!forum/selenium-users) as we reserve GitHub issues for actual issues with the software.  Thanks!

**Comment by ruchikar** [comment]
Found a workaround:

apply className as none:
        String js = "document.getElementById(\"photo0\").className = \"\"";
        ((JavascriptExecutor) driver).executeScript(js, uploadPhoto);
