### ISSUE TITLE
Not able to perform actions on lookup fields in MS CRM application using selenium(C#)

### ISSUE THREAD

**Issue by mahi515** [SeleniumHQ/selenium#2860]
## Meta -
OS:  
Windows 10.1
Selenium webDriver : 3.0  
Browser:  
Internet Explorer,  Firefox and chrome

Issue:
My application has dropdown lookup field to select an account name from the list. On hovering the mouse you can the dropdown control gets enabled with search icon image. I need to automation to click that search icon image and select a value from the dropdown list , using selenium webdrivers in C#.

Tried using Selenium IDE also, to record and play. Elements are recorded properly but while playing back, it throws error : unable to locate the elements.
Could you please help on this.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
