### ISSUE TITLE
Page Load timeout is NOT working in version 3.0 java

### ISSUE THREAD

**Issue by saikiran40cs** [SeleniumHQ/selenium#2946]
## Meta -
OS:  Windows 7

Selenium Version:  3.0.0 WebDriver

Browser:  Firefox v49 ,chrome v54,IE v11

Browser Version:  

## Expected Behavior -
The driver page load timeout should wait for the prescribed time to load the page.

## Actual Behavior -
The driver page load timeout is not now actually waiting for the prescribed time. Instead it gets closed immediately

## Steps to reproduce -
1. Open https://www.google.co.in/?gws_rd=ssl and start searching for Xpertfeed.
2. Click on the link http://xpertfeed.blogspot.com/
3. it takes more time to now load the page in the meantime the webdriver closes displaying error in console
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
lokakuuta 17, 2016 5:29:18 IP. org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
