### ISSUE TITLE
Selenium v3.0 SelectElement not working

### ISSUE THREAD

**Issue by nhhphuong** [SeleniumHQ/selenium#2986]
Hi,

I tried to use Selenium Webdriver v3.0 (C#) with SelectElement class, I'm using SelectByText/Value/Index to select item in dropdown, it does not select item but status return is passed.

Please guide me how to select in the new version of Selenium.

Thanks so much,
Phuong Nguyen

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
