### ISSUE TITLE
Force BrowserMobProxy and Selenium Chrome Driver to use QUIC 

### ISSUE THREAD

**Issue by vuyyala** [SeleniumHQ/selenium#3012]
Hi all, 
        I am working on downloading HAR from Chrome for YouTube through Selenium Python Script.
Code Snippet: 

                chrome_options = webdriver.ChromeOptions()
        	chrome_options.add_argument("--proxy-server={0}".format(url))
		chrome_options.add_argument("--enable-quic")

        	self.driver = webdriver.Chrome(chromedriver,chrome_options = chrome_options)

               self.proxy.new_har(args['url'], options={'captureHeaders': True})   // BrowserMobProxy
	       self.driver.get(args['url'])
               result = json.dumps(self.proxy.har, ensure_ascii=False)

I want QUIC to be used whenever I download HAR but when I look at the packets through Wireshark Selenium driver is using TCP only . Is there a way to force BrowserMobProxy and  Chrome Driver to use QUIC?

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
