### ISSUE TITLE
Chrome window is closed if test suite is failed

### ISSUE THREAD

**Issue by brbrr** [SeleniumHQ/selenium#3034]
## Meta -
OS:  OSX

Selenium Version: 3.0.0 ruby bindings  

Browser:  Chrome

Browser Version:  53.0.2785.143 (64-bit)

Browser window is closing if test was failed. it causing problems with debugging failed tests. 

## Expected Behavior -
Browser window remains open until `driver.close` is called.

## Actual Behavior -
Browser closed once test is failed.

## Steps to reproduce -
execute this test:
```
require 'selenium-webdriver'
require 'minitest/autorun'

describe 'Selenium' do
  it 'should not close browser window' do
    driver = Selenium::WebDriver.for :chrome
    driver.navigate.to "http://google.com"
    element = driver.find_element(:name, 'q')
    element.send_keys "Hello WebDriver!"
    element.submit

    puts driver.title
    driver.title.must_equal "OHAI!"
  end
end
```

**Comment by titusfortner** [comment]
You might be seeing this as a new issue as a result of the [change we made to chrome_options](https://github.com/SeleniumHQ/selenium/commit/0a4b995) due to [this bug](https://github.com/SeleniumHQ/selenium/issues/2418) for [detach feature](https://sites.google.com/a/chromium.org/chromedriver/capabilities).
The browser should close when the test is finished, whether it passes or fails.

If you want this to be different, try:
```
caps = Selenium::WebDriver::Remote::Capabilities.chrome(chrome_options: {'detach' => true})
driver = Selenium::WebDriver.for :chrome, desired_capabilities: caps
```

Let us know if this doesn't fix your issue.
