### ISSUE TITLE
Error: PhantomJS executable may have wrong permissions

### ISSUE THREAD

**Issue by MasterSwift** [SeleniumHQ/selenium#3065]
Running Selenium locally on flask. Im using the PhantomJS driver. 
`driver = webdriver.PhantomJS(executable_path='/Users/MyAcc/Documents/MY-WEBAPP/venv/lib/python3.5/site-packages/selenium/webdriver/phantomjs')`

Here's the error code I got when I run
`selenium.common.exceptions.WebDriverException: Message: 'phantomjs' executable may have wrong permissions. `

**Comment by mach6** [comment]
did you check the file permissions? what are they?

**Comment by MasterSwift** [comment]
How do you check and change file permissions?

**Comment by cgoldberg** [comment]
> 'phantomjs' executable may have wrong permissions.


@MasterSwift,

The file permission error you are getting is a red herring.  The actual issue is that the `executable_path` you are passing is not correct.   The `executable_path` is supposed to specify the location of the `phantomjs` driver executable.... you provided the location of the `phantomjs` Python module (part of the webdriver package).

You need to download phantomjs and then set its location via `executable_path` (or place the executable somewhere on your PATH).
