### ISSUE TITLE
how to disable mailto protocol with opening a native mac mail app?

### ISSUE THREAD

**Issue by litt1e-p** [SeleniumHQ/selenium#3072]
## Meta -
OS:  macOS

Selenium Version:  3.0.1

Browser:  Chrome

Browser Version:  54.0.2840.71

## Steps to reproduce -

just like firefox, it has an attibute: `network.protocol-handler.external.mailto`
```
profile = FirefoxProfile()
profile.set_preference('network.protocol-handler.external.mailto', False)
self.driver = webdriver.Firefox(self.profile)
```

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
