### ISSUE TITLE
kerberos / NTM

### ISSUE THREAD

**Issue by sebDK** [SeleniumHQ/selenium#3098]
Hi, 
My application uses kerberos to identify user.
How can I say to selenium driver that kerberos identification should be used?

Thanks for your help.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
