### ISSUE TITLE
There was an unexpected alert

### ISSUE THREAD

**Issue by ShrutiEswari** [SeleniumHQ/selenium#3105]
In web application testing using fire 
![selenium ide error](https://cloud.githubusercontent.com/assets/23181389/20292096/b5611dca-ab4f-11e6-8ce3-56af11f404df.png)
fox i got the below issue:

Action: User has to click a button which will reload to the new page.
I have given the xpath for the button click and added waitforPage to Load command too. 
Still selenium IDE says that "[error] There was an unexpected Alert! []" and testcase fails over there.

In my web page there is no alert at that point so i wonder what was the issue with that error?

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
