### ISSUE TITLE
Request about any example for iOS testing

### ISSUE THREAD

**Issue by albka1986** [SeleniumHQ/selenium#3108]
Can you give some examlpe on the github for testing an app file on iOS with Selenium?

My envinronment:

- mac os x el capitan;
- iphone 5 (iOS 10.0.2)
- Intellij IDEA

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
