### ISSUE TITLE
Can't run flask selenium app off apache server using WSGI. 

### ISSUE THREAD

**Issue by hdi200** [SeleniumHQ/selenium#3150]
## Meta -
OS:  
Rasbain (Linux 32 bit)
Selenium Version:  
Selenium 3.0.0.b2 (Python)
Browser:  
Firefox

Browser Version:  
50
I have a selenium script running of a flask site that automates a few tasks on my schools website. 
It runs fine on a flask server, but when I try to use it on apache on wsgi it throws an internal server error and this is what I get in the log
https://gist.github.com/anonymous/1c0420cdf1b141010044b92de8d169f1
Any Idea what could be causing this?

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
