### ISSUE TITLE
Selenium-html-runner 3.0.1 : Address already in use (Bind failed)

### ISSUE THREAD

**Issue by VincentRo** [SeleniumHQ/selenium#3156]
## Meta -
OS:  Red Hat
Selenium Version:  
selenium-html-runner-3.0.1.jar
Browser:  
Geckodriver

Hello,

I try to launch a simple test of selenium IDE with selenium-html-runner-3.0.1.jar in command line :

java -jar selenium-html-runner-3.0.1.jar -port 4445 -timeout 600 -userExtensions user-extensions.js -htmlSuite *firefox http://google.com searchtest.html firefox-results.html

I have download geckodriver and he is available. But every time I try to run this, I have this following error : 

java.io.IOException: java.lang.RuntimeException: java.net.BindException: Address already in use (Bind failed)

It's look like he try to use 2 times the same port.

Can you help me?

This guy has the same issue as me but he haven't any response : 
https://gist.github.com/bruceburge/b4b500d9672f88723f79ad2eb01ab350

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Duplicate of #2978.
Already fixed by not released yet.
