### ISSUE TITLE
JavaScript Application error 

### ISSUE THREAD

**Issue by UtkarshQA** [SeleniumHQ/selenium#3161]
Version:  Selenium IDE 2.9.1 
When i click on source tab at that moment get the JavaScript Application error.
Please resolve this issue fast. 

![screenshot_1](https://cloud.githubusercontent.com/assets/22098980/20596476/bf355066-b264-11e6-8c99-db2113c5110e.png)

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by UtkarshQA** [comment]
Hey man this is critical bug, i can't see the code of JAVA TestNg in source tab.

Steps:
1. Plugin Selenium IDE 2.9.1 in Firefox 50.0 
2. Go to tool option
3. Open Selenium IDE 
4. Change the format Java/ TestNG/ Remote control
5. Click on Source tab

**Comment by AutomatedTester** [comment]
To be quite honest, for a critical bug there is still lots of information missing. 

Did you record anything? was the recording currently on? Was this working in Firefox 49?

Since this is a volunteer project, giving half hearted bug reports makes it hard to replicate and there could be something missing from your bug report that is key.
