### ISSUE TITLE
Selenium support for Airwatch browser

### ISSUE THREAD

**Issue by sureshgorantla** [SeleniumHQ/selenium#3189]
Hi All,

I would like to know whether we will be able to run WebDriver scripts on AirWatch browser? I am trying to run few existing WebDriver scripts on Airwatch browser on iOS device. For that what is the browser name we need to provide in Desired Capabilities for Airwatch browser?

Can anyone please let me know.

Thanks,
Suresh G

**Comment by lukeis** [comment]
The selenium project does not directly support iOS, that is done through other projects like appium and WebDriverAgent. Please look into using them for automating with WebDriver on iOS. 
I'm not aware of being able to automate iOS apps without access to simulator builds or the source though, but I may be wrong.

**Comment by RoakyWood** [comment]
I realize that this is closed, but as the AirWatch VMware WorkspaceOne ecosystem browser becomes more pervasive, users will want to know what the "capabilities" are that have to passed to talk to the VMware device browser which is named 'Web'. This question involves both Selenium and Appium. So far I am getting crickets.

**Comment by RoakyWood** [comment]
The AirWatch, VMware, WorkspaceOne ecosystem browser is becoming more pervasive.

Users will want to know what the “capabilities” are that have to be passed to the device/browser in order to to talk to the VMware device browser which is named ‘VMware Workspace ONE Web’.

This question involves both Selenium and Appium.

Question: Has Appium, Selenium or VMware considered what the capabilities set will be in order to talk to VMware’s browser?

I have a request into VWware/AirWatch to motivate them to make sure that their browser can be automated via Appium/Selenium.

If anyone finds out anything before me, let me know. Can anyone from the Selenium Project reach out to VMware?

**Comment by RoakyWood** [comment]
David,

Your response is quite helpful.

I have started support discussions with VMware/Airwatch and my goal is to make sure they understand that they need to move on this, or lose a lot of people from the Appium Selenium world.

I’m going to look at the spec myself.

I will keep you informed on what they say.

Regards,
RW


On Nov 20, 2018, at 5:28 PM, David Burns <notifications@github.com<mailto:notifications@github.com>> wrote:


@RoakyWood<https://github.com/RoakyWood> The Selenium project does not have the bandwidth to support a new browser. We have however created a specification<https://w3c.github.io/webdriver/> that would allow VMWare to add support with an ever growing test suite<https://github.com/web-platform-tests/wpt/tree/master/webdriver/tests>.

I am happy to help with discussions but unfortunately that is the extent of what I, and Selenium, can offer at the moment.
