### ISSUE TITLE
Bug-java.lang.CharSequence cannot be resolved. How to solve this Problem?

### ISSUE THREAD

**Issue by Kati86** [SeleniumHQ/selenium#3198]
WebElement regUsername = driver.findElement(By.id("reg_username"));
regUsername.sendKeys(new String[] { "sample" });

**Comment by gopij** [comment]
Error appeared because of java. Use eclipse neon to overcome this issue

I have used eclipse Version: Neon.1 (4.6.1)

Solution: 
so using build path >> configure build path>> java compiler>> changed the compiler compliance level to 1.8

http://stackoverflow.com/questions/24694171/error-when-using-sendkeys-with-selenium-webdriver-java-lang-charsequence-canno

Attach relevant log and online example with test script, if you are still facing this issue

**Comment by Kati86** [comment]
Thank you very much. It's work :-)
