### ISSUE TITLE
Failed to open TCP connection to 127.0.0.1:7055 (Connection refused - connect(2) for "127.0.0.1" port 7055) (Errno::ECONNREFUSED)

### ISSUE THREAD

**Issue by ajaysonkusare** [SeleniumHQ/selenium#3218]
Hi, I am facing an issue while maximize browser instance.
Error is 
Failed to open TCP connection to 127.0.0.1:7055 (Connection refused - connect(2) for "127.0.0.1" port 7055) (Errno::ECONNREFUSED)
./features/support/hooks.rb:2:in `Before'

**hooks.rb**
1.Before do |scenario|
2.Capybara.reset_sessions!
3.  page.driver.browser.manage.window.maximize
 4. page.driver.browser.manage.delete_all_cookies
5.end

Parameters:
**OS**:  Linux
**Selenium** :  gem selenium-webdriver', '~> 2.53.4'
**Capybara**: gem 'capybara', '>= 2.10.0'
**Browser**:  Firefox version 45.5.0

Any proposition will be welcome
Thanks in advance for your time.

**Comment by lmtierney** [comment]
This is usually the tell tale sign that you're using Firefox 48+ with selenium < 3.0 Can you chck to make sure you don't possibly have another version of Firefox or selenium-webdriver installed?

**Comment by ajaysonkusare** [comment]
Thanks @lmtierney for your comment,

It's a Centos Machine(Linux) which have latest version of Firefox(45.5.0) and there is no another version of Firefox or selenium-webdriver installed.I ran cukes in parallel mode in 8 threads.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. Don't use any extensions (namely, Capybara), just bare Selenium.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by titusfortner** [comment]
Will reopen if reproducible test case provided

**Comment by CloCkWeRX** [comment]
For what it's worth, I went from a stable test suite to a failing one with similar versions (Centos, Mozilla Firefox 45.5.1; capybara (2.11.0), selenium-webdriver (2.53.4))

The only thing I changed was along the lines of:
```
yum update yum*
yum update tz* xorg*
yum update bash sudo 
yum update postfix perl*
yum update openssl* postgresql94*
yum update lib*
yum update nagios*
yum update ca-certificates
yum update openssh*
yum install -y java-1.8.0
```
Thus changing my default java version to:
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

I suspect it'll be either the java version bump or something in lib* that was updated inadvertedly, rather than specifically a selenium or firefox bug itself.
I needed the java version bump for newer versions of jenkins
