### ISSUE TITLE
Unable to run Selenium test cases with HTMLLauncher and Chrome

### ISSUE THREAD

**Issue by MomchilGorchev** [SeleniumHQ/selenium#3237]
## Meta -
OS:  
- MacOS 10.11.6

Selenium Version:  
- IDE: 2.9.1

Browser:  
- Chrome
- Firefox

Browser Version:  
- Chrome 55.0.2883.87 (64-bit)
- Firefox 50.0.2

## Expected Behavior -
- The command succeed and i see my test running
## Actual Behavior -
- Error is thrown

So, firstly I want to apologise if this is been discussed anywhere else or what I'm trying to achieve is not possible at all.
Im trying to run Firefox's Selenium IDE generated tests, exported as html files, from command line, using `chromedriver` and Chrome as a test browser.
This is the command im running:
`java -Dwebdriver.gecko.driver=/usr/local/bin/chromedriver -jar 'selenium-html-runner-3.0.1.jar' -htmlSuite '*chrome' 'http://localhost:3000/fluid' 'my-test-file.html' 'results.html'`

When i run that i can see Chrome is being open for ~1sec and then closed when i got the error looking like that:
```
Multi-window mode is longer used as an option and will be ignored.
Starting ChromeDriver 2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1) on port 14654
Only local connections are allowed.
Dec 12, 2016 11:45:51 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Dec 12, 2016 11:45:52 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
2016-12-12 11:45:52.988:INFO::main: Logging initialized @2358ms
2016-12-12 11:45:53.040:INFO:osjs.Server:main: jetty-9.2.z-SNAPSHOT
2016-12-12 11:45:53.055:INFO:osjsh.ContextHandler:main: Started o.s.j.s.h.ContextHandler@5c6648b0{/tests,null,AVAILABLE}
2016-12-12 11:45:53.074:INFO:osjs.ServerConnector:main: Started ServerConnector@3e694b3f{HTTP/1.1}{0.0.0.0:6067}
2016-12-12 11:45:53.074:INFO:osjs.Server:main: Started @2444ms
2016-12-12 11:45:53.545:INFO:osjs.ServerConnector:main: Stopped ServerConnector@3e694b3f{HTTP/1.1}{0.0.0.0:6067}
2016-12-12 11:45:53.546:INFO:osjsh.ContextHandler:main: Stopped o.s.j.s.h.ContextHandler@5c6648b0{/tests,null,UNAVAILABLE}
Dec 12, 2016 11:45:53 AM org.openqa.selenium.server.htmlrunner.HTMLLauncher mainInt
WARNING: Test of browser failed: *chrome
java.lang.RuntimeException: Unable to find suite table: <html xmlns="http://www.w3.org/1999/xhtml"><head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1" />
<title>Error 404 </title>
</head>
<body>
<h2>HTTP ERROR: 404</h2>
<p>Problem accessing /tests/. Reason:
</p><pre>    Not Found</pre><p></p>
<hr /><i><small>Powered by Jetty://</small></i>


</body></html>
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:118)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.mainInt(HTMLLauncher.java:245)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.main(HTMLLauncher.java:273)
```
Did some digging, i found its failing around [these lines](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/selenium/server/htmlrunner/HTMLLauncher.java#L120), but no idea why ... 

General questions:
- Am i missing some installation steps
- Are my Selenium and Chrome versions compatible
- If yes, what can i do to tackle this issue

**Comment by barancev** [comment]
Please attach the suite that causes the problem.

**Comment by MomchilGorchev** [comment]
HI @barancev, thank you for your answer, I should have attached the test file, my bad
That is what it looks like exported from Selenium IDE, I've just removed some steps in the test for simplicity.
In the source code of the HTMLLauncher its looking for a table with id of `suiteTable` if I'm understanding it correct. Is this meant to be populated from the IDE? Isn't this id hardcoded in the HTMLLauncher code? I've tried to put it as id on table in the test but i got the same error 
Does that means incompatibility in my Selenium and HTMLLauncher versions?
Looking forward for your answer, thanks in advance

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="http://localhost:3000/" />
<title>Widgets test</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">Widgets test</td></tr>
</thead><tbody>
<tr>
	<td>open</td>
	<td>/fluid</td>
	<td></td>
</tr>
<tr>
	<td>waitForElementPresent</td>
	<td>css=div.productContainer</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>css=div.productContainer</td>
	<td></td>
</tr>
<tr>
	<td>waitForElementPresent</td>
	<td>css=div.widget-instance</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>css=div.widget-instance</td>
	<td></td>
</tr>
</tbody></table>
</body>
</html>
```

**Comment by barancev** [comment]
It's not a suite, but a test case. Runner accepts suite files only.

**Comment by MomchilGorchev** [comment]
Hi, thanks for the clarification! I did export the test cases as a suite and now I have file looking as following:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta content="text/html; charset=UTF-8" http-equiv="content-type" />
  <title>Test Suite</title>
</head>
<body>
<table id="suiteTable" cellpadding="1" cellspacing="1" border="1" class="selenium"><tbody>
<tr><td><b>Test Suite</b></td></tr>
<tr><td><a href="testcase1.html">testcase1</a></td></tr>
<tr><td><a href="testcase2.html">testcase2</a></td></tr>
</tbody></table>
</body>
</html>
```
and running:
`java -Dwebdriver.gecko.driver=/usr/local/bin/chromedriver -jar "./e2e/jar_files/selenium-html-runner-3.0.1.jar" "-htmlSuite" "*chrome" "http://localhost:3000/fluid" "./e2e/tests/Suite1.html" "./e2e/results.html"`
... but its failing with the exact same error :|
Is it going to be easier if i update to Selenium 3.0+ (I've read somewhere that this will maybe fix problems like mine)
Any suggestions are greatly appreciated
Thanks

**Comment by ttaranov** [comment]
same here - html runner fails with "Unable to find suite table" when I pass suite html or a test html... My test suite (and test case) work fine via Selenium IDE though.

**Comment by ttaranov** [comment]
actually, fixed this by using absolute path for test suite using $(pwd):
java -Dwebdriver.gecko.driver=geckodriver -jar selenium-html-runner-3.0.1.jar -htmlSuite "*firefox" "https://mydomain/" $(pwd)/suite.html reports

**Comment by nammzzi** [comment]
did anyone solve this? exact same error

**Comment by juniormayhe** [comment]
## Test Suite HTML source code
My test suite is working fine. Maybe this is related to Selenium version. Here is a sample of test suite source code:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta content="text/html; charset=UTF-8" http-equiv="content-type" />
  <title>Test Suite</title>
</head>
<body>
<table id="suiteTable" cellpadding="1" cellspacing="1" border="1" class="selenium"><tbody>
<tr><td><b>Test Suite</b></td></tr>
<tr><td><a href="first-test-case.html">First test</a></td></tr>
<tr><td><a href="second-test-case.html">Second test</a></td></tr>
<tr><td><a href="third-test-case.html">Third test</a></td></tr>
</tbody></table>
</body>
</html>
```

## Running Selenium HTML Runner with Chrome in Windows

For those who are trying to run Selenium HTML runner, I managed to do it. I had to download chrome driver which is not maintained by Selenium team, actually it is taken care by Google. After downloading chromedriver.exe and selenium runner, and knowing where is your html containing "suite" case tests, you can type:

`java -Dwebdriver="C:\YourFolder\chromedriver.exe" -jar "C:\YourFolder\selenium-html-runner-3.4.0.jar -htmlSuite "*googlechrome" "http://127.0.0.1/" "C:\YourFolder\YourTestSuitePointingToTestCases.html" "C:\YourFolder\test-results-folder"`

Of course java must be seen globally in environment variables: `Path=C:\ProgramData\Oracle\Java\javapath;...your other paths...`

## Downloads

Java: http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html
Selenium Html Runner: https://selenium-release.storage.googleapis.com/3.4/selenium-html-runner-3.4.0.jar
Chrome Driver: https://chromedriver.storage.googleapis.com/2.31/chromedriver_win32.zip
Firefox and other drivers: http://www.seleniumhq.org/download/

## Issues
The annoying thing is that chromedriver.exe does not have an option to hide chrome user interface, so its window will pop up when running java. I haven't tried calling googledriver from C#, Node or Java code in order to figure out if hide chrome interface would work.

There is no documentation as far as I know and you have to dig into source code to find out all available browser "driver" options: https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/selenium/server/htmlrunner/HTMLLauncher.java

There is an issue related to click on input type text that is within a hidden div. In Selenium IDE it works just fine but with chromedriver I had to add an extra event (onmouseover) since the div shows up when mouse cursor is hovering this element. This is related only to the page I am testing and maybe this would not happen with you. Anyway it is always good to keep developers and testers aware of these issues. So, to give an example of this issue with hidden div, the original Selenium IDE code was:

```
<tr>
	<td>click</td>
	<td>id=txEmail</td>
	<td></td>
</tr>
```

To work in chromedriver, this part was changed to:

```
<tr>
	<td>mouseOver</td>
	<td>id=txEmail</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=txEmail</td>
	<td></td>
</tr>
```

Selenium IDE also generated some clicks which takes user to specific pages. That works if you run the test again in Selenium IDE though it DOES NOT work in chromedriver.exe. In this case you might have to remove those clicks (for redirecting user) and replace them with an `open `command:

```
<tr>
	<td>open</td>
	<td>https://domain.com/your-target-page</td>
	<td></td>
</tr>

```

**Comment by ldelaprade** [comment]
Get the exact same issue despite use of the latest version; i.e. selenium-html-runner-3.5.3.jar
Was preparing I nice test suite using Selenium IDE on Firefox 54 (with disabling auto-upgrade because IDE is not yet compatible with the new Firefox plugins paradigm). Test was running nicely from within Selenium IDE but could not be run using selenium-html-runner-3.5.3.jar.
I Just found the cause of that and managed with a workaround (a change in the test case HTML files generated by Selenium IDE)

**Comment by shs96c** [comment]
Does anyone have a sample test suite and test case that I can run without being on your corporate networks? I'm happy to try and fix this, but the test cases so far don't allow me to diagnose the problem.

**Comment by bingtw** [comment]
@shs96c Please refer to following samples. A simple test case for input "seleniumhq" on Google Search.

## Test Suite
```html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta content="text/html; charset=UTF-8" http-equiv="content-type" />
  <title>Test Suite</title>
</head>
<body>
<table id="suiteTable" cellpadding="1" cellspacing="1" border="1" class="selenium"><tbody>
<tr><td><b>Test Suite</b></td></tr>
<tr><td><a href="run_googler_search.html">First test</a></td></tr>
</tbody></table>
</body>
</html>
```

## Test Case
```html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="selenium.base" href="https://www.google.com" />
<title>run_google_search</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">run_google_search</td></tr>
</thead><tbody>
<tr>
	<td>open</td>
	<td>https://www.google.com</td>
	<td></td>
	<td>false</td>
</tr>
<tr>
	<td>clickAt</td>
	<td>id=lst-ib</td>
	<td>60,18</td>
	<td>false</td>
</tr>
<tr>
	<td>type</td>
	<td>id=lst-ib</td>
	<td>seleniumhq</td>
	<td>false</td>
</tr>
<tr>
	<td>pause</td>
	<td>2000</td>
	<td></td>
	<td>false</td>
	<td>pause</td>
</tr>
</tbody></table>
</body>
</html>
```
