### ISSUE TITLE
avoid using `element.innerText`?

### ISSUE THREAD

**Issue by sixinli** [SeleniumHQ/selenium#3242]
## Meta -
OS:  OSX
Selenium Version: 2.53.0
Browser:  chrome
Browser Version:  53.0

## Code 
```
// text = "Welcome!"
var headerText = $("h1").text();
```
## Expected Behavior -
`expect(headerText).toContain("Welcome!");`

## Actual Behavior -
`expect(headerText).toContain("WELCOME!");`

according to the docs, it seems like [WebElement#getText](https://github.com/SeleniumHQ/selenium/blob/ceaf3da79542024becdda5953059dfbb96fb3a90/java/client/src/org/openqa/selenium/WebElement.java#L143) uses [innerText] (https://developer.mozilla.org/en-US/docs/Web/API/Node/innerText) which is not a standard feature. I wonder if there's any reason for choosing `innerText` over [textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent)?

**Comment by lukeis** [comment]
It doesn't actually do that. Here's our atoms code, that may or may not be used in the driver implementations -

https://github.com/SeleniumHQ/selenium/blob/master/javascript/atoms/dom.js#L944-L1051

Since you mentioned Chrome, I would suggest logging a bug with chromedriver with reproducible html that corresponds to the behavior you are seeing.

https://bugs.chromium.org/p/chromedriver/issues/list

right now, because you aren't showing the html, I can't tell if it's expected behavior or not. Note that the getText API is meant to return the text as the user sees it. So if there's a text transform, it could be doing the right thing.

**Comment by sixinli** [comment]
ah ok, that makes sense, thanks @lukeis
