### ISSUE TITLE
Implement Context Manager protocol for Pythons selenium.webdriver.remote.webdriver.WebDriver

### ISSUE THREAD

**Issue by jachymb** [SeleniumHQ/selenium#3266]
It would be more Pythonic to do:
```
with webdriver.Chrome() as driver:
  foo(driver)
```
Then 
```
dirver = webdriver.Chrome()
foo(driver)
driver.close()
# Any additional cleanup to make sure the browser has really been shut down properly
```

EDIT: Or even:
```
dirver = webdriver.Chrome()
try:
  foo(driver)
finally:
  driver.close()
  # Any additional cleanup to make sure the browser has really been shut down properly
```

**Comment by cgoldberg** [comment]
I agree this is a nice feature, and context managers are very Pythonic.  The common pattern for cleaning up resources is to do it automatically using a context manager.

However, this has been requested several times over the years:
* https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/3228
* https://github.com/SeleniumHQ/selenium/issues/1906

Personally, I see no reason not to add `__enter__` and `__exit__` methods..  It would allow us to use drivers within a context manager (and still explicitly close browsers if we choose).
If the maintainers feel any different about including this in the Python bindings, I'd be happy to create a pull request.

----

one nitpick with the OP's example in this issue:

```
driver.close()
# Any additional cleanup to make sure the browser has really been shut down properly
```

You should use `driver.quit()` rather than `driver.close()` and everything will be cleaned up.

**Comment by davehunt** [comment]
I have no objections so long as there are suitable tests for the changes, though @AutomatedTester is the maintainer of the Python bindings and may have a reason why we would not want to introduce this.

**Comment by asottile** [comment]
Reaching for the same thing, at $COMPANY we maintain a wrapper around selenium which exposes a contextmanager, makes it much less likely to shoot oneself in the foot :)

**Comment by lmtierney** [comment]
There is a pending PR for this change, #4078
