### ISSUE TITLE
Reading data from multiple web tables, merging and exporting to excel

### ISSUE THREAD

**Issue by disdaining** [SeleniumHQ/selenium#3275]
Hi,

I want to read data from multiple web tables with different dimension, then i need to combine the second table with the first one. I am good by doing one job at a time but can' perform both at the same time.

[here](http://pastebin.com/UVZZPYAG) is the sample code.

Any help or idea?
Thank you

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
