### ISSUE TITLE
add extension raise AddonFormatError ,error message:can not find install.rdf exception

### ISSUE THREAD

**Issue by taoqsun** [SeleniumHQ/selenium#3291]
## Meta -
OS:  
windows 7 32bit
Selenium Version:  
3.0.1
Browser:  
firefox 
Browser Version:  
50.1.0(32bit)

Expected Behavior :
add_extension api can add extension without the file named "install.rdf"

Actual Behavior :
return a exception,it said can not find "c:\users\folder\temp\install.rdf"

Steps to reproduce :
1.create a FirefoxProfile() object.
2.call add_extension API to add local release extension file which from firefox store.

**Comment by barancev** [comment]
Can you please share an example of extenstion without 'install.rdf' file to debug on?

**Comment by taoqsun** [comment]
@barancev  sure,please use the attachment and you need unzip this file.thanks
[cisco_webex_extension-1.0.1-an+fx-windows.xpi.zip](https://github.com/SeleniumHQ/selenium/files/674845/cisco_webex_extension-1.0.1-an.fx-windows.xpi.zip)

**Comment by datatooldev** [comment]
I have the same problem with my web extension.
The Firefox web extension specification uses manifest.json file instead of install.rdf. 
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Your_first_WebExtension

**Comment by lricoy** [comment]
I could also reproduce it. The code clearly only works when a "install.rdf" is present.
 
See the readManifest method:

For .xpi files:
https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/firefox/extension.js#L152

**Comment by soulgalore** [comment]
I got the same with the NodeJS version. I think the extension handling is broken if you create a new extension and want to use it with Selenium, If you create a new extension following the new standard only using a manifest.json, everything works fine when I verify the extension on https://addons.mozilla.org/ but fails in Selenium because I miss the install.rdf file. 

If I add an install.rdf file and keep manifest.json, I get an error verifying the extension on amo. If I remove the manifest.json and only use a install.rdf, I get another error verifying the extension on amo, saying I'm missing the manifest.json. At least when I try there's no way to get a new extension to work with Selenium (if you install it with Selenium).

**Comment by tobli** [comment]
I have a PR coming for this.

**Comment by tobli** [comment]
Submitted https://github.com/SeleniumHQ/selenium/pull/3846.

**Comment by barancev** [comment]
Merging to more recent #4093
