### ISSUE TITLE
How to add extension to default profile permanently using Chromedriver

### ISSUE THREAD

**Issue by furqanmlk** [SeleniumHQ/selenium#3315]
## Meta -
OS:  Windows 10

Selenium Version:  2.52

Browser:  Chrome

Browser Version:  55.0.2

## Expected Behavior -
Extension should be able to remain installed in default profile after browser is closed
## Actual Behavior -
Extension is removed after browser is closed
## Steps to reproduce -
```
ChromeDriverService cd = ChromeDriverService.CreateDefaultService(<ChromeDriverPath>);
String userProfile= "C:\\Users\\user_name\\AppData\\Local\\Google\\Chrome\\User Data\\";
ChromeOptions options = new ChromeOptions();
options.addArguments("user-data-dir="+userProfile);
options.addArguments("--start-maximized");
WebDriver driver = new ChromeDriver(cd , options, TimeSpan.FromMinutes(3));

```

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
