### ISSUE TITLE
While executing parallel tests, report generation is too slow using serenity in Jenkins.

### ISSUE THREAD

**Issue by Rajktha** [SeleniumHQ/selenium#3328]
## Meta -
OS:  
Windows 7 Version 6.1
Selenium Version:  
 2.53.1 
Browser:  
Chrome 

Browser Version:  
55.0.2883.87

 I am facing issue with reports being generating very slow (While running a test with 1800 test scenarios) using serenity in Jenkins. Execution is completed as reasonable time with available nodes. But, serenity report generation is taking additional 1 hour 30 minutes from the time of execution completed.  I am using serenity version 1.1.42. Please suggest me for this.
![screenshot](https://cloud.githubusercontent.com/assets/17195094/21708561/1080f0bc-d400-11e6-87fc-bc821229a6a1.jpg)

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
