### ISSUE TITLE
Unable to send key press in Selenium

### ISSUE THREAD

**Issue by SivaKesava1** [SeleniumHQ/selenium#3363]
I have the following code snippet in Python:

driver = webdriver.Chrome(executable_path="/home/sivakesava/chromedriver",chrome_options = chrome_options)
ActionChains(driver).send_keys(Keys.F3).perform()
driver.get('http://google.com')

Even though I send the F3 key the Find dialog box does not open. Is there any alternative because I need to send the key before loading the URL and by "find_element_ ...  " method I could not send a key in general to the webpage. 
Any suggestion would be really helpful for my project.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
