### ISSUE TITLE
is it possible to resize an element(canvas, etc..) using selenium python?

### ISSUE THREAD

**Issue by cnyzgkn** [SeleniumHQ/selenium#3365]
## Meta -
OS:
Windows 7 x64 bit
Selenium Version:
3.0.2
Python:
3.6.0
Browser:
Chrome 55.0.2883.87 m (64-bit)

## Expected Behavior -
canvas element can be changed

## Actual Behavior -
canvas element can not be changed

## Steps to reproduce -

note that I have an element: "id=canvas" and its default size is 1024*768
now I want to change the size of it to 800*600 using selenium python

method 1:
canvas.size['width'] = 800;
canvas.size['height'] = 600;

method 2:
browser.execute_script('arguments[0].width = 800;', canvas)
browser.execute_script('arguments[0].height = 800;', canvas)

both failed.

Why?

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
