### ISSUE TITLE
Feature Improvement - user agent injection to IE11

### ISSUE THREAD

**Issue by RonenHoffer** [SeleniumHQ/selenium#3367]
## Meta -
OS:  
Windows 10

Selenium Version:  
3.0.0

Browser:  
Internet Explorer

Browser Version:  
11.576.14393.0

## Feature Improvement -
It seems that IE11 has a built in way to change its user agent, I've noticed it while hitting F12 and looking at emulation tab.
Can you add an ability to control the user agent through this interface?

**Comment by lukeis** [comment]
we don't intend on providing this feature. Recommended practice is to use a Proxy and then modify the user agent string as requests are made from the browser to the server.

Selenium is intended to be run from the effective browser you are attempting to emulate, so one should be able to launch and run that browser instead of attempting to change the configuration of a browser that nearly no end user using the website will do.
