### ISSUE TITLE
How to get the output of the browser's console?

### ISSUE THREAD

**Issue by binarykitchen** [SeleniumHQ/selenium#338]
Is there a command to retrieve the browser's console output? This for various log levels, preferable as an event?

This feature has been raised in the WebdriverIO repository at https://github.com/webdriverio/webdriverio/issues/464 but it seems that this is rather a Selenium thing.

Let me know if this is already implemented or on your todo list. Thanks

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
