### ISSUE TITLE
I need creat a custom servlet to Selenium Grid

### ISSUE THREAD

**Issue by yangle94** [SeleniumHQ/selenium#3383]
## Meta -
OS:  
OSX : 10.12.2 
Selenium Version:  
selenium-server-standalone-3.0.1.jar

In my selenium grid2, I would like to customize the two servlet for the various nodes in json form of information displayed, I consulted the official website on the contents of this, but the content is too simple, so I can not very Accurate understanding of how to do. I would like to ask who can give me a more detailed tutorial available, I am using selenium-server-standalone-3.0.1.jar very grateful.

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by yangle94** [comment]
@AutomatedTester  Thinks for your help,I have solved the problem。
