### ISSUE TITLE
How to  initialize page factory object outside the test

### ISSUE THREAD

**Issue by seema-realforce** [SeleniumHQ/selenium#3386]
Is there a way where i can initialize page factory object outside the test. 
Say i have tests
@Test()

		public void login(){
	  	
			 Login LoginPage = PageFactory.initElements(driver, Login.class);
			 Welcome WelcomePage = PageFactory.initElements(driver, Welcome.class);
			 }
@Test()

		public void createproperty(){
	  	
			 Login LoginPage = PageFactory.initElements(driver, Login.class);
			 Welcome WelcomePage = PageFactory.initElements(driver, Welcome.class);
                        Properties PropertiesPage = PageFactory.initElements(driver, Properties.class);
			 }
Instead of  initializing say Login LoginPage = PageFactory.initElements(driver, Login.class); in each of the tests, can i handle it outside the tests and use it accross all tests of the class?

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
