### ISSUE TITLE
Grid2. SelfRegisteringRemote. Incorrect processing of the "timeout" optional parameter

### ISSUE THREAD

**Issue by shimkiv** [SeleniumHQ/selenium#339]
[Selenium Grid2 Wiki](https://github.com/SeleniumHQ/selenium/wiki/Grid2#optional-parameters) page says:
> -timeout 30 (300 is default) The timeout in **seconds** ...

But in [SelfRegisteringRemote.java](https://github.com/SeleniumHQ/selenium/blob/2997a70d5872ff1f228a833f062ea32af05dca6b/java/server/src/org/openqa/grid/internal/utils/SelfRegisteringRemote.java#L97) source file, at line 97 we have divide by 1000 as if we're using the value of the "-timeout" parameter in milliseconds:
```java
    if (hubParameters.has(CLIENT_TIMEOUT)){
        int timeout = hubParameters.get(CLIENT_TIMEOUT).getAsInt() / 1000;
        remoteControlConfiguration.setTimeoutInSeconds(timeout);
    }
```

We should either to update source code or documentation.

**Comment by andreastt** [comment]
Changing this is risky because of potential breakage for users.  We need to check users of `CLIENT_TIMEOUT` internally as well as, ideally, in a bigger external code base.  As @nirvdrum pointed out on IRC, it sounds best to use milliseconds as the internal representation and seconds for the user-facing UI.  But this would mean (potentially) breaking code that is already relying on the status quo of `CLIENT_TIMEOUT` being in milliseconds.

**Comment by andreastt** [comment]
It looks like Mozilla, who's a big user of Selenium Grid, is relying on it being set in milliseconds: https://github.com/mozilla/moz-grid-config/blob/8115f4e85c2bb35449644046f3405f692b69bfa1/hub_configuration.json#L2 (@davehunt)

**Comment by andreastt** [comment]
Also the same seems to be true for `browserTimeout` if that wasn't obvious.

**Comment by shimkiv** [comment]
@andreastt thank you for your reply.
So maybe it will be enough just to update Wiki page ?

**Comment by nirvdrum** [comment]
@shimkiv How are you seeing this be a problem?  The code you've highlighted isn't what does the CLI parsing.  The CLI parsing does indeed read values as seconds and normalize internally to milliseconds (we have tests for this).  The code you've highlighted is taking the milliseconds values and converting back to seconds.  But since it's only dealing with normalized values, this shouldn't be a problem.

The problem scenario I suppose is we require milliseconds in the configuration JSON.  But the docs you've highlighted are for the CLI options, not the JSON config.  Am I missing something?

**Comment by shimkiv** [comment]
@nirvdrum Thanks for your reply. 
Hmm, it seems that I missed something but is there any possibility that "timeout" could be incorrectly overridden  somehow ?
Because, for example, when I'm using "-timeout **900**" option for node then I'm getting "Client requested session XYZ that was terminated due to TIMEOUT" exception, but when I'm using "-timeout **900000**" option then TIMEOUT exceptions are not thrown. 
So it looks for me like timeout value is setted in milliseconds though Wiki page is describes its value in seconds.

**Comment by nirvdrum** [comment]
@shimkiv Can you provide the entire command you're using please?  Also, which version of Sellenium?  With those two pieces of information, I can trace the code far more easily.

**Comment by shimkiv** [comment]
Selenium Server 2.45.0
HUB:
```
java -jar selenium-server-standalone-2.45.0.jar -logLongForm -role hub -timeout 900000
```
NODE:
```
java -cp .;lib\jul-to-slf4j-1.7.10.jar;lib\slf4j-api-1.7.10.jar;lib\logback-classic-1.1.2.jar;lib\logback-core-1.1.2.jar;selenium-server-standalone-2.45.0.jar -Djava.util.logging.config.file=logging.properties org.openqa.grid.selenium.GridLauncher -logLongForm -debug -timeout 900000 -browser "browserName=chrome, version=41.0, maxInstances=1, platform=WINDOWS" -Dwebdriver.chrome.driver=drivers\chromedriverwin.exe -port 5555 -role node -hub http://<hub_host>:<hub_port>/grid/register
```

**Comment by kierr** [comment]
The only error here is in the documentation, which states the value(s) should be in seconds rather than milliseconds as the code reflects.

**Comment by barancev** [comment]
There is no documentation error here.
-timeout command line option accepts the value in seconds.
JSON configuration file and internal representation are in milliseconds.
