### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by Kurimatzu** [SeleniumHQ/selenium#3484]
## Meta -
OS:  Windows 10

Selenium Version:  3.0.1

Browser:  Firefox

Browser Version:  51

## Steps to reproduce -

You can send POST to a website?

**Comment by ddavison** [comment]
Hey there!

Looks as though your issue is actually a user issue rather than an issue with Selenium itself.  For these issues, we ask you to please use the [selenium users group](https://groups.google.com/forum/#!forum/selenium-users) as we reserve GitHub issues for actual issues with the software.  Thanks!
