### ISSUE TITLE
Getting error for explicit wait -  wait.until(ExpectedConditions.presenceOfElementLocated(actualElement)) when using 3.1.0

### ISSUE THREAD

**Issue by sanojqa** [SeleniumHQ/selenium#3541]
Getting error for explicit wait -  wait.until(ExpectedConditions.presenceOfElementLocated(actualElement)) when using 3.1.0

**Comment by ddavison** [comment]
Hey there!

Looks as though your issue is actually a user issue rather than an issue with Selenium itself.  For these issues, we ask you to please use the [selenium users group](https://groups.google.com/forum/#!forum/selenium-users) as we reserve GitHub issues for actual issues with the software.  Thanks!

**Comment by testphreak** [comment]
@sanojqa  According to the [changelog](https://github.com/SeleniumHQ/selenium/blob/master/java/CHANGELOG) it appears that every project using the `selenium-java` dependency will also need to add `guava` dependency >= v21.

```xml
<dependency>
     <groupId>com.google.guava</groupId>
     <artifactId>guava</artifactId>
     <version>21.0</version>
</dependency>
```
Importing this dependency and rebuilding your project should resolve the error you are seeing.

**Comment by lmtierney** [comment]
Read the [CHANGELOG](https://github.com/SeleniumHQ/selenium/blob/master/java/CHANGELOG) it states that you need guava version 21 with `3.1.0`
