### ISSUE TITLE
failed to build the target iphone:atoms

### ISSUE THREAD

**Issue by jessyZu** [SeleniumHQ/selenium#3581]
./go //iphone:atoms 
ERROR:
Writing: build/iphone/atoms.h
go aborted!
same file: build/iphone/atoms.h and build/iphone/atoms.h

Has the issue with atoms.h been resolved?  I just get the latest version of selenium(3.2.0) and it fails to generate the header file atoms.h properly.  It looks like the file gets cut off:

/* AUTO GENERATED - DO NOT EDIT BY HAND */
#ifndef WEBDRIVER_ATOMS_H_
#define WEBDRIVER_ATOMS_H_

#include <string>    // For std::(w)string.

namespace webdriver {
namespace atoms {

--> end of atoms.h

**Comment by lukeis** [comment]
is there a reason you need this? the old iphone driver has been long since removed and this seems like a leftover target that should be deleted.

**Comment by jessyZu** [comment]
Yeah,I need this target .Our app use atoms based web driver to crawl webpage info ,which now helping millions and millions  people in China to manage bills of their credit cards. On Android platform ,we use android-atoms from seledroid，but in iOS platform, we also want the  iOS atoms.

I think you did a great job, the atoms is very valuable,may it be retained ？

**Comment by lukeis** [comment]
we have another atoms target that does work that was used by the ios-driver project:

    ./go ios_driver

will generate files in build/javascript/atoms/fragments/

since we don't know what you are using in particular it's very difficult for us to know if we will break you. We do try make sure this ios_driver target works (we run it in our travis ci build).

I'm going to remove the iphone/build.desc as it's outdated and no longer works :)  but you should be able to build individual atoms for particular targets. If you need something more than what ios_driver target is providing, let us know.

**Comment by jessyZu** [comment]
thank you ,I' ll give you some feedback
