### ISSUE TITLE
Tomcat安装成windows服务以后，在web程序中启动Chromedriver，浏览器不启动，但是所有的过程都没问题。

### ISSUE THREAD

**Issue by LinuxSuRen** [SeleniumHQ/selenium#3595]
## Meta -
OS:  

Selenium Version:  

Browser:  
 Chrome

Browser Version:  

## Expected Behavior -
浏览器能被打开
## Actual Behavior -
浏览器没有被打开，但是chromedriver.exe驱动的进程有。

**Comment by lmtierney** [comment]
Selenium is not supported to be run as a windows service

**Comment by LinuxSuRen** [comment]
能提供一些解决思路吗，谢谢！

**Comment by ruby186** [comment]
@LinuxSuRen 

option 1:
Under tomcat service, make sure it run as interactive mode. please google "interactive" for more help.

option 2:
run tomcat or jetty from (remote desktop) command line. never use as serivce.

for example, when we use webdriver under centos ci service, we are follow these steps:
1) start and login into a vnc session
2) start a console instance, or ssh from remote client
3) under console instance, type command and run jetty(tomat) and regular application
4) keep this console alive. now it can start all ui bases processes.

I still use legacy rc because of webriver has so many bugs and not stable.

**Comment by LinuxSuRen** [comment]
非常感谢，确实可以。
