### ISSUE TITLE
Feature request - Show browser versions installed on nodes in grid console

### ISSUE THREAD

**Issue by tomelliff** [SeleniumHQ/selenium#3613]
It would be useful to be able to see the browser versions installed on the nodes from the grid console.

We're tracking the latest Chrome releases and automatically installing them as they are released but sticking to ESR Firefox releases (due to not being ready to move to GeckoDriver just yet) and are regularly asked by developers about what versions of browsers we have installed on the nodes.

**Comment by evertones** [comment]
When Selenium Grid is started using [docker images](https://github.com/SeleniumHQ/docker-selenium), then it shows the browser version for each node.
The image attached shows 2 nodes started with docker and 2 nodes started using the JARs.

If you can use docker, it may solve your problem.

![grid](https://cloud.githubusercontent.com/assets/15055020/23728607/dcd0453c-04b1-11e7-98a6-16dfb9b258d3.jpg)

**Comment by lmtierney** [comment]
@evertones that is only because the docker images pass the value in. There's no guarantee that's actually the version. 

![](http://image.prntscr.com/image/a00024c6c9bd42b88ba100d5a43f1c4b.png)

**Comment by krmahadevan** [comment]
@tomelliff - The version of the browser being shown on the console is entirely controlled by the user who is configuring the node (It just shows whatever version is being put in the JSON configuration file).

The other way you can think of is, to expose a method in your framework etc., which when invoked would trigger a call to `driver.executeScript("return navigator.UserAgent;");` which can be parsed using a library such as [this](https://github.com/HaraldWalker/user-agent-utils). This is exactly NOT what you are after (because you want it via the console) and here we are forcing them to create a RemoteWEbDriver instance to find the version.. But hey.. something is better than nothing :)

**Comment by tomelliff** [comment]
Yeah apologies, somehow didn't spot the browser-version option in the capabilities on the nodes. That works for us we can grab the version of the browsers we're using and use that to drive the template of config.json.
