### ISSUE TITLE
Missing Methods in WindowUtils class in new Release of Selenium(3.2.0)

### ISSUE THREAD

**Issue by jimmyjavid** [SeleniumHQ/selenium#3629]
while in earlier Releases of Selenium I used to use methods like
 WindowsUtils.readIntRegistryValue(location); and 
WindowsUtils.writeIntRegistryValue(location, 0);
 to read and write to Window Registery. 
   As I transit from earlier releases to new Release 3.2; to my surprise these methods were missing in new release of selenium.
 Kindly mention the alternate that has replaced those methods or the strategy to perform tasks such as reading and writing to Window Registery in selenium 3.1 and Selenium 3.2.

**Comment by krmahadevan** [comment]
@jimmyjavid - They were removed as part of [this](https://github.com/SeleniumHQ/selenium/commit/717918fb1aba6f24d0ae9f7114a6228430b39c62) commit since they were classified as un-used windows specific methods. I dont think there are any alternatives. 

One thing you can do is (if you absolutely need this class ) to duplicate it inside your project and then use it internally.

**Comment by barancev** [comment]
Selenium is not a library to manage windows registry, so these methods were removed deliberately.
