### ISSUE TITLE
WebDriver class does not accept a session_id

### ISSUE THREAD

**Issue by Pyrodyne** [SeleniumHQ/selenium#364]
Allowing a session_id to be set on the WebDriver would allow reuse of an existing session.
Tested working.

selenium/webdriver/remote/webdriver.py - class WebDriver

doc says:
"     - session_id - The session ID to send with every command."

Added session_id=None to **init**
...
self.session_id = None changed to self.session_id = session_id
...
Changed to quash new session if a session id is specified
        if session_id is None: # Do not start a new session if there is already a session id
          self.start_session(desired_capabilities, browser_profile)

**Comment by lukeis** [comment]
I'm not in favor of adding this to the selenium project as it can be easily accomplished with a simple wrapper class.

https://gist.github.com/lukeis/67926542b5b252e1f3d8

**Comment by Pyrodyne** [comment]
That code mixes remote and local - not functional on a headless server.

Adapting the example to remote, it will open a new session - with all of the overhead involved in getting a new window going on a new session, then it will flip back to the other session afterwards.

My proposed changes in full:
line 50:
    def __init__(self, command_executor='http://127.0.0.1:4444/wd/hub',
        desired_capabilities=None, browser_profile=None, proxy=None, keep_alive=False, session_id=None):

line 70:
       self.session_id = session_id

line 74:
        if session_id is None: # Do not start a new session if there is already a session id
          self.start_session(desired_capabilities, browser_profile)

End result: you can attach to an existing session with little overhead, without starting an additional session beforehand - between the server and VM I am using this can be several seconds for each session.

With the proposed changes, connecting to an active session is as simple as:
sel = webdriver.Remote('http://127.0.0.1:4444/wd/hub', desired_capabilities=DesiredCapabilities.FIREFOX, session_id="13342673-3437-47a0-b3b2-75faf4482b0c")

In testing, this accomplishes connecting to the existing session with no perceivable overhead:
New session time: 0:00:02.444191
Reuse session time: 0:00:00.000575


Test code used with above changes to selenium:
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import datetime


start = datetime.datetime.now()
sel = webdriver.Remote('http://127.0.0.1:4444/wd/hub', desired_capabilities=DesiredCapabilities.FIREFOX)
print "New session time: %s" % str(datetime.datetime.now() - start)

start = datetime.datetime.now()
sel2 = webdriver.Remote('http://127.0.0.1:4444/wd/hub', desired_capabilities=DesiredCapabilities.FIREFOX, session_id=sel.session_id)
print "Reuse session time: %s" % str(datetime.datetime.now() - start)

**Comment by lukeis** [comment]
there's no reason the example code I provided couldn't be used with the drivers being Remote, it's not just for local instances.

**Comment by Pyrodyne** [comment]
Is there a good reason to avoid what I am doing by bypassing creating a new session? Your example code also creates a new session and browser window. 

I am looking to connect to an existing window and session without that step. The changes I wrote appear to work OK. Would there be any longer term issues that I am not aware of by doing so?

**Comment by lukeis** [comment]
Is there a good reason to do what you're doing? :)

My example code does create one driver "d" instance... but you have to create one somewhere first right? Doesn't matter where you create it, the important bit of my example was "d2" which did not start a new window / browser and just attached to the existing session that was "d".

**Comment by Pyrodyne** [comment]
As I posted above, new browser window will take up to 5 seconds (about 2.6 in the test), but skipping creating a new session and window and only loading the session id string takes hardly any time. I have verified that I can connect to the session and control it - even from a completely different script or interactive shell.

When "d" is created with Remote(), it creates a new browser window and session, and the 2.5-5 second lag is still present.

**Comment by lukeis** [comment]
Huh?  How are you connecting to a session that hasn't been started? Don't you have to a WebDriver session first in order to get the session id to connect to?

My code example was simply to show that you can connect... you don't have to create the "d" in that python process, if you magically read the session id from somewhere else it will also run in ~0 seconds for creating that "d2" instance.

Unless you're doing something I don't know, you have to take the hit at least once to start the browser session.

**Comment by Pyrodyne** [comment]
That the point of using the session ID to connect to them. The session is started/restarted/killed by a manager as needed, and other scripts can then pull from the manager to find a session that is not busy and immediately execute instructions.

Looking at the documentation, it appears that the session_id was meant to allow for this but wasn't completed - again, perhaps intentionally?

**Comment by lukeis** [comment]
your "manager" seems like a separate implementation of our Selenium Grid.

If your goal was to have the Grid 'manager' optimize itself by starting up sessions before they are requested, that could probably be done with a [plugin to the selenium grid](https://github.com/freynaud/grid-plugin-tutorial). The reason why Selenium by default does not try to do this optimization is because any new Session can potentially have a different set of Desired Capabilities and thus change the startup logic for a browser.

And yet... I still fail to see how the snippet provided isn't adequate. Basically I think you're in a highly customized environment and in such, you should not have an issue extending or wrapping the Selenium library to provide your functionality.

**Comment by Pyrodyne** [comment]
Just seemed like a good thing to have by default. 
If you already have a session started, why not be able to also simply connect to it?
The addition of one named argument to connect rather than create and connect seems like a reasonable request to me.

**Comment by lukeis** [comment]
Seems like a reasonable request to not include this sort of thing in the standard library and use the workaround?

Because without proper justification, I don't want to make it easier for users to do unrecommended things. Can you please elaborate your use case?

I haven't heard a sound argument for adding this (and honestly I'd use this, as I currently use similar workarounds as I've suggested in order to start a session in Java and then attach to it using the python repl).

Also, feel free to join our IRC chat room #selenium on irc.freenode.net to talk through things like this in real time. (Although it's nearing the end of the day)

**Comment by Pyrodyne** [comment]
While putting this together over the past two days, I actually saw many people asking for similar but different features - in particular being able to seize control of an existing window. 

Most of those requests were for a similar reason - the cookie jar is essentially in a vacuum, and same for things like the previous page visited. It doesn't work quite the same way as opening a new browser window and hit the ground running.

My short list would be:
1) Makes debugging simpler. The browser isn't broken even if the script is. Reconnect to the session and resume after fixing the problem. Don't have to rewind to the beginning.
2) Don't have to wait for sessions to boot. You can keep them idling, waiting for input.
3) Can use the same session across multiple scripts to keep other code cleaner.
4) Can manage the session with your own tools if desired.
5) Addition of session id to constructor doesn't break any other code made prior to it's introduction
6) Makes everything that is asynchronous easier.

Still not sure why this method of session connection is unrecommended. Beyond having a fight with the node's timeouts - seperate issue - it has been completely solid with no unpredictable behavior. At least, for the few hours it has been running.

Perhaps will see you on freenode.

**Comment by anupvg** [comment]
Hi Pyrodyne,
I followed all the steps you mentioned above, but ended up with an error:

urllib2.URLError: <urlopen error [Errno 111] Connection refused>

Please help!

**Comment by anupvg** [comment]
![remote_webdriver](https://cloud.githubusercontent.com/assets/14092966/9786602/f50172b6-57d8-11e5-9159-f49335100ba5.PNG)

**Comment by lmtierney** [comment]
Closing this as there is an open PR for this change
