### ISSUE TITLE
Screenshot : IE : VMs : Selenium Grid : 3.0.1 : when i take screenshots on VM. it appears black.

### ISSUE THREAD

**Issue by vaibhavkavi** [SeleniumHQ/selenium#3700]
## Meta -
OS:  Win 7

Selenium Version:  3.0.1

Browser:  IE 8,9 and 10

Browser Version:  

## Steps to reproduce -
- run the execution on selenium grid on different VMs with IE8,9 or 10. 
- VM machine must be locked and disconnected. 
- Capture the image
- it will appear as black.

**Comment by luke-hill** [comment]
Can I just add I've "just" started seeing this recently. Across IE mainly.

However whilst I'm sure this isn't a fully selenium related issue, I would be intrigued to know where the issue lies (We use `Capybara.current_session.save_screenshot` to capture).

We use Remote Win8_1 machines with Selenium `2.53.4` on IE11

**Comment by glacier6327** [comment]
I'm not sure if it's this simple, but on a VM the graphic drive will shut down if a VM goes into screensaver mode... turn off screen saver, or in my case run a non-intrusive keep alive if security wont let you modify the screen saver time out.

**Comment by fkberthold** [comment]
I'm seeing a similar behavior to this.

OS: Ubuntu 16.04.2 LTS
Selenium Version: Python 3.3.3
Browser: chromium 57.0.2987.98
Chrome Driver version: 2.29.461571

I noticed during normal automation test runs the screenshots were coming back as black. I started experimenting with capturing screenshots from the Python REPL.

Working across multiple workspace screens, I found that if the browser was on a different screen from the REPL, it consistently took black screens. If I put the browser on the same screen as the REPL and made sure it was visible, then it took screenshots, but the images written to file would lag behind what was there by 3-4 screenshots.

I've tried updating selenium, the browser and the driver all to the latest version, and tried installing the latest version of chrome instead of chromium. I get the same result in all cases.

**Comment by PavelStryhelski** [comment]
Hi,
I`m facing almost the same issue - we run tests on Amazon AWS Windows slaves through Jenkins CI (nunit 3.7.1 + nunit-console3.6.1 + C#). I have tried some variants to understand what is going wrong and where. The following couples were tested:
1) chromedriver 2.28.0-2 beta + chrome 57 - Screenshot is available
2) chromedriver 2.29 + chrome 57 - Screenshot is available
3) chromedriver 2.29 + chrome 58 - Screenshot is available
4) chromedriver 2.29 + chrome 59 - Screenshot is BLACK
5) chromedriver 2.30.0.1 + chrome 59 - Screenshot is BLACK
Results are 100% reproducible starting variant (4).

**Comment by cgoldberg** [comment]
@PavelStryhelski 

There is a known bug in Chrome 59 that is likely causing your screenshot problem.  
See Issue 1844:
* https://bugs.chromium.org/p/chromedriver/issues/detail?id=1844

Also, for some general tips on collecting screenshots from a remote desktop, read these threads:
* https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/2964
* https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/3536

hth

**Comment by diemol** [comment]
Closing as the related Chrome issue was linked above.
