### ISSUE TITLE
Clicking Invisible option elements should not succeed (from google code #8563)

### ISSUE THREAD

**Issue by lukeis** [SeleniumHQ/selenium#379]
example html:

```
<select>
<option value="option0">option0</option>
<option value="option1" disabled="disabled">Disabled option</option>
<option value="option2" style="visibility: hidden;">Option hidden</option>
<option value="option3" style="display: none;">Option display none</option>
</select>
```

options = driver.find_elements_by_tag_name("option")

options[0].click();  <- behaves as expected
options[1].click();  <- does a no-op (expected behavior IMO)
options[2].click(); chrome renders this option, firefox doesn't. Firefox doesn't allow the user to select this, but WebDriver will select this option with this call.
options[3].click(); <- no one renders this option and it isn't settable by a user... yet webdriver sets it (and thus updates the rendered UI)

Related W3C WebDriver spec bug - https://www.w3.org/Bugs/Public/show_bug.cgi?id=28143

**Comment by opensource21** [comment]
You can see a possible solution for the disable-problem at https://github.com/elisarver/selophane/commit/3d191b3192bc52db50d78a19c06183c238b77ee2.
I think it's not relevant if the click is possible or not, because you can obviously click on every element on a screen, perhaps to check if nothing happens. On the other side if I choose `select(option1)`  I expected that after that option1 is selected or I get an exception or at least a return value which shows me that nothing could be selected.

**Comment by barancev** [comment]
Current behavior matches W3C WebDriver standard [1] that describes a special case of click operation for 'option' elements. Selenium does not actually click it, it selects an option. So it allows to select an option if it is selectable but not clilckable. For example, Firefox allows to pick an option with style="display: none;" if you put focus to its 'select' parent and govern it with the keyboard.

But Firefox driver allows to select a disabled element, and it seems to be an issue, I've moved it to geckodriver tracker [2]

[1] https://w3c.github.io/webdriver/webdriver-spec.html#element-click
[2] https://github.com/mozilla/geckodriver/issues/1107
