### ISSUE TITLE
FindElementCompleted event from EventFiringWebDriver does not return element to Event Handler

### ISSUE THREAD

**Issue by Free1man** [SeleniumHQ/selenium#3829]
Hi Selenium Team,

OS:  Windows 10 
Selenium Version: 3.3.1 
Browser:  Chrome 57

Code sample here: https://dotnetfiddle.net/XJ5jDq

Problem: FindElementCompleted event from EventFiringWebDriver does not return element to Event Handler.Event occurs correctly but element is null. For events like ElementValueChanged and ElementClicking it works perfect.
![image](https://cloud.githubusercontent.com/assets/3762102/24985842/df3dd33e-204a-11e7-941a-59df3c6ddf16.png)

**Comment by IliaFraedom** [comment]
Good day Selenium Team, any chance that this could be resolved?

**Comment by totpero** [comment]
Hi, I found hack solution for this issue: 
`var element = e.Driver.FindElement(e.FindMethod);`
instead of:
`var element = e.Element;`

**Comment by Free1man** [comment]
Thanks, @totpero but it will be the infinite loop in this case, because 
`e.Driver.FindElement(e.FindMethod)` will trigger same event `_loggingDriver_FindElementCompleted`.
Small update:  This issue also happen for php-webdriver, so it is not C# specific.

**Comment by jimevans** [comment]
@Free1man The `FindElementEventArgs` object does not include the found element. The `Element` property of the event arguments refers to the parent element being used in the find, if there is one (i.e., using `element.FindElement` instead of `driver.FindElement`). When you call `FindElement` from an `IWebDriver` object, the property will always be `null`, and this is by design. Yes, a property named `ContextElement` or `ParentElement` would likely be more descriptive, but as it is, the caller already has access to the found element, as it's returned by the `FindElement` method. Note that if the element isn't present for the `FindElement` case, the `FindElementCompleted` event doesn't fire at all, since the `NoSuchElementException` is thrown.
