### ISSUE TITLE
RemoteWebDriver doesn't return platform version

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [SeleniumHQ/selenium#3874]
## Meta -
OS:  Win 7/Win10

Selenium Version:  3+

Browser:  Any

```
@BeforeTest(alwaysRun = true)
    public void setVariables() {
        env = new Properties();
        HasCapabilities remote = (HasCapabilities) getWebDriver();
        env.setProperty("Url", Configuration.baseUrl);
        env.setProperty("Browser", remote.getCapabilities().getBrowserName());
        env.setProperty("Browser Version", remote.getCapabilities().getVersion());
        env.setProperty("Platform", remote.getCapabilities().getPlatform().name());
        env.setProperty("Platform version", **remote.getCapabilities().getPlatform().getMajorVersion()** + "." +
                **remote.getCapabilities().getPlatform().getMinorVersion()** );
        LOGGER.setLevel(Level.CONFIG);
    }
```

Starting from version 3.1.0 of seleniumhq both remote.getCapabilities().getPlatform().getMajorVersion() and remote.getCapabilities().getPlatform().getMinorVersion() return "0" values. 
For version 3.0.1 and below it works like a charm.

Zip file with diff between versions 3.0.1 and 3.3.1 is attached.

[3.3.1-3.0.1.zip](https://github.com/SeleniumHQ/selenium/files/946659/3.3.1-3.0.1.zip)

**Comment by barancev** [comment]
Actually, Selenium was cheating ;)

The drivers (except for geckodriver) don't return platform version in capabilities (and never did). For example, these are capabillities returned by a remote chrome:

```
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29.461591 (62ebf098771772160f391d75e589dc567915b233), userDataDir=C:\Users\alexei\AppData\Local\Temp\scoped_dir2948_22719}, takesHeapSnapshot=true, pageLoadStrategy=normal, unhandledPromptBehavior=, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=59.0.3071.115, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, webdriver.remote.sessionid=926895fa-fbba-48c9-afde-b9f491851156, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
```

Instead of telling the platform version where the browser is running, Selenium told you the current platform version. That's not what one would expect from `remote.getCapabilities().getPlatform().getMajorVersion()`, right? And we've fixed this inconsistency.

If you want to get the current platform version you have to say this explicitly:
`Platform.getCurrent().getMajorVersion()`

At the moment we can't obtains platform version for a remote driver. So I'll keep this issue open as a "feature request".

**Comment by diemol** [comment]
If I am not wrong, drivers are not returning that information yet, because I think it is not part of the W3C WebDriver spec.

Also, in most of the cases, the user _should_ know what platform version they want to run the test on. 

In any case, this issue has been stale for over 3 years, which partly means that no other users in the community are interested in it. I will close this for now, but if there is a real use case needed by the community, we would be happy to see how we can work on this.
