### ISSUE TITLE
WebDriver.findelements().size() less than the reality value.

### ISSUE THREAD

**Issue by XinHuakai** [SeleniumHQ/selenium#3885]
Hi,

In my a test environment, there is a table with more than 50 lines on page. In order to count the lines, I used 'driver.findelements(By.tagName("tr"))', but the result is less than 50. Some time is 37 or 39. 
It blocks me for a long time.
Could someone help me? 
Thanks very much.

## Meta -
OS:  
Windows 7
Selenium Version:  

Browser:  
Internet Explorer
Browser Version:  
11.0.9600.17801

**Comment by yc2164708** [comment]
If possible，please provide the url of the page ....
usually，we can locate the element or element correctly by the CSS selector

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
