### ISSUE TITLE
Selenium finds and (tries) to click on hidden elements

### ISSUE THREAD

**Issue by dwt** [SeleniumHQ/selenium#3936]
## Meta -
OS:  MacOS 10.12.4 (16E195)
Selenium Version:  Gem selenium-webdriver (3.4.0)
Browser:  Firefox Firefox 53.0, Geckodriver 0.16.1

## Expected Behavior -
Hidden page elements should neither be found, nor be clicked on - especially if the element is behind other elements and the click therefore is on a completely different element.

## Actual Behavior -
A hidden element is found and selenium clicks on any random element that is where it thinks the hidden element might be.

## Steps to reproduce -
```ruby
require 'capybara'

Capybara.register_driver(:firefox) do |app|
  Capybara::Selenium::Driver.new(app, browser: :remote, 
    desired_capabilities: Selenium::WebDriver::Remote::Capabilities.firefox)
end

Capybara.default_driver = :firefox

page = Capybara::Session.new(:selenium)
page.visit('https://test.yeepa.de/auth/login/token?login_token=2%7C1%3A0%7C10%3A1493366171%7C20%3Alogin_token_for_user%7C4%3ANDI3%7Cbc94154597db08d5a093a55f0d392614ec89c78a7895a17acb643098d30a5d71')

page.click_link("Overview")
puts 'this actually clicked on "Measure" instead of raising "element not found" as the "measure" submenu is initially hidden'
sleep 2
```

**Comment by dwt** [comment]
I'd like to add, that this worked fine with selenium before gecko driver.

**Comment by AutomatedTester** [comment]
Selenium has always returned hidden elements, I am guessing that capybara must have some magic for removing hidden elements, if its not returning them I suggest you raise a bug with them.

**Comment by AutomatedTester** [comment]
Since we don't support capybara I recreated this in python and its doing the right thing. 

```bash
(sel) dburns in ~ λ python
Python 2.7.13 (default, Jan  3 2017, 16:36:18)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> f=webdriver.Firefox()
>>> f.get("https://test.yeepa.de/auth/login/token?login_token=2%7C1%3A0%7C10%3A1493366171%7C20%3Alogin_token_for_user%7C4%3ANDI3%7Cbc94154597db08d5a093a55f0d392614ec89c78a7895a17acb643098d30a5d71")
>>> f.find_element_by_link_text("Overview").click()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dburns/.virtualenvs/sel/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/dburns/.virtualenvs/sel/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "/Users/dburns/.virtualenvs/sel/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in execute
    self.error_handler.check_response(response)
  File "/Users/dburns/.virtualenvs/sel/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message:
```

**Comment by dwt** [comment]
Will do, thanks

**Comment by p0deje** [comment]
I think Capybara doesn't properly handle `ElementNotInteractableError` and this is why you don't see anything. I haven't got deep into Capybara source code, but I also see a correct behavior when using plain Ruby bindings:

```irb
irb(main):002:0> driver = Selenium::WebDriver.for(:firefox)
=> #<Selenium::WebDriver::Firefox::Marionette::Driver:0x1d4205e59794dfc2 browser=:firefox>
irb(main):003:0> driver.get 'https://test.yeepa.de/auth/login/token?login_token=2%7C1%3A0%7C10%3A1493366171%7C20%3Alogin_token_for_user%7C4%3ANDI3%7Cbc94154597db08d5a093a55f0d392614ec89c78a7895a17acb643098d30a5d71'
=> {}
irb(main):004:0> driver.find_element(link_text: 'Overview').click
Selenium::WebDriver::Error::ElementNotInteractableError:
```

**Comment by dwt** [comment]
Well, I'll let them know

**Comment by dwt** [comment]
Out of interest: In the past when trying to click on elements that where not visible / behind other elements, selenium raised an exception that I was trying to click on something hidden.

Is that not the case anymore or was this also a capybara feature?

**Comment by p0deje** [comment]
In W3C spec error is now call `ElementNotInteractableError`, while before Selenium was raising `UnknownError`.

**Comment by twalpole** [comment]
@AutomatedTester I believe this should be reopened since there is actually a problem.  In the example posted there are two 'Overview' links - one in the top menu and one in the side menu.  Capybara determines whether an element is visible or not by calling Selenium::WebDriver::Element#displayed? on  the element.  The top menu link is correctly identified as not visible, the side menu element, however, is identified as visible.  This is likely due to the CSS used to hide each element (top menu is in a display: none element, side menu is pushed off the page) and would be fine except for the fact that when one calls click on the side menu link, it clicks and returns no error.  This shouldn't happen since there is no way a user could click on the link.  I'm not sure whether the error is in selenium-webdriver or geckodriver.

irb(main):001:0> require 'selenium-webdriver'
=> true
irb(main):002:0> driver = Selenium::WebDriver.for(:firefox)
=> #<Selenium::WebDriver::Driver:0x5b1032e32eea5022 browser=:firefox>
irb(main):003:0> driver.get 'https://test.yeepa.de/auth/login/token?login_token=2%7C1%3A0%7C10%3A1493366171%7C20%3Alogin_token_for_user%7C4%3ANDI3%7Cbc94154597db08d5a093a55f0d392614ec89c78a7895a17acb643098d30a5d71'
=> {}
irb(main):004:0> els = driver.find_elements(link_text: 'Overview')
=> [#<Selenium::WebDriver::Element:0x..f851c1324ed09e7de id="e0043cab-b61d-0f42-8f6e-a6eb38217110">, #<Selenium::WebDriver::Element:0x..f8257ee04726d6a3c id="bec18413-1239-de40-8b56-412b879a5c45">]
irb(main):005:0> els[0].displayed?
=> false
irb(main):006:0> els[1].displayed?
=> true
irb(main):007:0> els[1].click
=> {}

**Comment by p0deje** [comment]
@twalpole Thank you for investigating!

I'm going to reopen this issue, but mark as "Awaiting answer" because I no longer can access the URL that is used in this issue - it keeps asking for authorization.

@dwt If you can make it available somehow, it would be great.

**Comment by dwt** [comment]
@p0deje: new url is: https://test.yeepa.de/auth/login/token?login_token=2%7C1%3A0%7C10%3A1493713498%7C20%3Alogin_token_for_user%7C4%3ANDI3%7C832d71fcbae13f7af2961f67e1cef0767a0813372d485b8d774784cc3b512155

**Comment by p0deje** [comment]
@dwt Thank you for new URL!

So, in the end it turned out to be a [Marionette issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1321516). Current geckodriver is not fully compliant to spec part that defines "clickability" of the element.

I'm closing this since that's Marionette issue and there is nothing Selenium can do about it.

**Comment by dwt** [comment]
@p0deje Could you share the link to the marionette issue here? Thanks!
