### ISSUE TITLE
Python fails to check loopback when it's not 127.0.0.1

### ISSUE THREAD

**Issue by TKCen** [SeleniumHQ/selenium#395]
selenium fails to recognize a started IEdriver while checking for it [here](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/common/utils.py#L43)  if run in a proxy environment.

Newer Windows versions resolve localhost as the IPv6 loopback :1 and 127.0.0.1 is not recognized as a localhost address anymore and will be routed through the proxy if not directly specified in the proxy exceptions.

Example:
- WIndows 7
- Proxy with 'Bypass proxy server for local addresses' checked
- Start an IE instance through the Python bindings
- Expected : IE starts

Currently using Python bindings version 2.45.0

**Comment by TKCen** [comment]
Currently using Python bindings version 2.45.0

**Comment by andreastt** [comment]
[utils.py:43](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/common/utils.py#L43) needs to change so that it can always find the loopback device since 127.0.0.1 isn't always available.  Perhaps changing it to _localhost_ will help?

**Comment by mhijazi1** [comment]
>126.0.0.1 is not recognized

Just to be sure, did you mean 127.0.0.1?

**Comment by TKCen** [comment]
Of course, typo... sorry.

**Comment by fijiaaron** [comment]
localhost doesn't always map to the loopback -- that's determined by your hosts file and could be defined differently.  While it might solve this particular problem, it would not be a correct solution.  127.0.0.1 is always (or should be) the loopback interface.

**Comment by andreastt** [comment]
> 127.0.0.1 is always (or should be) the loopback interface.

If this isn’t the case on Windows 7, we are in a bit of a pickle.

**Comment by titusfortner** [comment]
I'm not sure if it's the same thing, but I needed to do this in order to get the Microsoft Edge tests passing for Ruby in Windows 10  - 68b4efa
It would not accept 127.0.0.1

**Comment by GQAssurance** [comment]
According to my understanding, technically any address in 127.*.*.* range is specified to be a loopback.

It looks like the issue here is a failure to recognize IPv6s loopback address as such.

**Comment by andreastt** [comment]
> According to my understanding, technically any address in 127.*.*.* range is specified to be a loopback.

Yes, the localhost CIDR range for IPv4 is defined to be 127.0.0.0/8, and ::1 for IPv6.  See RFC4632 for more details.

But the fact that it is reserved does not necessarily mean that the system is configured to use it.  Which IP addresses in these ranges are available as identifiers for the loopback device would be defined in /etc/hosts or c:\Windows\System32\Divers\etc\hosts. This means the original issue is still valid, because we can't make the assumption that 127.0.0.1 is always available.

Another issue so far not mentioned in this thread is that using 127.0.0.1 limits the check to the IPv4 stack.  If the server is bound exclusively to an IPv6 address, it will not be reachable unless the Python client is made to check both IP layers.

**Comment by AutomatedTester** [comment]
Closing as using `localhost` has created issues in the past as people setup weird and wonderful localhosts.
