### ISSUE TITLE
Cannot send Print screen key with Actions.sendKeys and I really need to test the application behavior when PrtScr is pressed. Is there an alternative, please?

### ISSUE THREAD

**Issue by aleungu** [SeleniumHQ/selenium#3958]
## Meta -
OS:  

Browser:

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
