### ISSUE TITLE
FindElement fails to time out for a missing id

### ISSUE THREAD

**Issue by MichaelDeveloper2014** [SeleniumHQ/selenium#397]
When executing the below Webdriver code, Selenium hangs on the findElement line.  It never times out when it looks for an ID that doesn't exist on the page.

try
{
    ImplicitTimeOut(TimeSpan.FromSeconds(0.3));
    IWebElement elem = Targetdriver.FindElement(by);

}catch(Exception e) {return false}
return true

Expected output: 
=> Return true if element is found
=>Timeout after 0.3 of a second if element is not found and return false

Actual output:
=>Tests hangs for 60 secods if element with specified Id is not found

NOTE: This only happens if I findElement By ID, it works perfect as it should if I use for example xpath. I try to use as less xpath as I can in my tests if I can help it, so please help me, what is the work around of this. 

I have also tried the below method but same story.

 WebDriverWait wait = new WebDriverWait(Targetdriver, TimeSpan.FromSeconds(1));
  wait.Until(ExpectedConditions.ElementIsVisible(by));

Selenium version: 2.45.0
OS: Windows 7
Browser: Firefox 
Browser version: 31

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
For the record -- I can't reproduce it:

![01-04-2015 18-29-21](https://cloud.githubusercontent.com/assets/617090/6944608/45c9ce3e-d89d-11e4-9c95-9daee5821024.png)

**Comment by MichaelDeveloper2014** [comment]
Hi, thanks for your response, can I please ask which webdriver version you're using?

**Comment by barancev** [comment]
2.45

**Comment by MichaelDeveloper2014** [comment]
Okay thank you.
