### ISSUE TITLE
W3C IEDriver ignores "unhandledPromptBehavior" capability

### ISSUE THREAD

**Issue by juangj** [SeleniumHQ/selenium#3972]
## Meta -
OS: any Windows
Selenium Version: n/a
Browser: Internet Explorer
Browser Version: any

IEDriver 3.3.99.4 (cc @jimevans)

## Expected Behavior -
The `unhandledPromptBehavior` capability should be respected.

## Actual Behavior -
The capability is always set to `"dismiss"` in a newly-created session.

## Steps to reproduce -
`c:\bin\wget.exe http://localhost:4444/session --post-data="{\"capabilities\": {\"alwaysMatch\": {\"unhandledPromptBehavior\": \"accept\"}}}"`

The capabilities in the response contain `"unhandledPromptBehavior":"dismiss"`, and the driver does appear to dismiss unhandled prompts without raising an error.

If I set an illegal value (`"unhandledPromptBehavior": "cheese"`), then a `session not created` error is raised, as expected.

I think that, by default, the capability should be absent, because the "missing value default state" [is a distinct case](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-handle-any-user-prompts) from either of the defined states "accept" and "dismiss". Though perhaps this is a spec question of whether it should really be defined that way, or if there should be a third value, such as "error".

**Comment by jimevans** [comment]
There's a subtle, but important, difference in the way unexpected alerts are handled in the spec-compliant case vs the legacy driver case. In the legacy driver case, an unexpected alert will always throw `UnhandledAlertException`, because unexpected alerts are _always_ a bug in one's code (you didn't expect it, making it an exceptional condition). The legacy behavior capability only describes what to do with the resulting alert before the exception is thrown (accept it, dismiss it, or leave it up).

In the W3C case, setting an alert handler prevents the exception from being thrown at all. We're going to need to hash this out and figure out what Selenium's proper behavior will be here. I'm going to ping @shs96c and @AutomatedTester as editors of the spec to weigh in on their opinions of what the project ought to do. I already have an opinion, but I don't want to unilaterally impose it on the entirety of Selenium.

**Comment by jimevans** [comment]
This issue has been resolved by changes in the spec. Other discrepancies should be handled by a new issue.
