### ISSUE TITLE
Selenium not working in internet explorer

### ISSUE THREAD

**Issue by albinsunny** [SeleniumHQ/selenium#3977]
## Meta -
OS:  
Windows 7
Selenium Version:  
2.42.0 for JAVA
Browser:  
IE 11.0.9600

I have my selenium script written to regress a site. It was not maintained properly for a long time.
Recently I have executed it and find it failing to start for all the browsers.
I have updated the chromeDriver and I could run it on chrome, but it is still failing for IE and FF.
Browser is getting invoked, but the scripts are not getting executed. Not

I have the driver IEDriverServer_Win32_2.42.0 and the path is also set..

Browser Version:  
IE 11.0.9600

## Expected Behavior -
Browser should open and run the script
## Actual Behavior -
IE is getting opened, but the script is not working further. 
I am not able to see any errors in the logs also.
## Steps to reproduce -

public static InternetExplorerDriver objDriver;	
System.setProperty("webdriver.ie.driver","C:\\selPath\\IEDriverServer.exe");
    objDriver= new InternetExplorerDriver();
    objDriver.get("www.google.com");

**Comment by jimevans** [comment]
You're using a version of the IE driver that's quite old, and you haven't shown any error messages or exceptions thrown by your code. The IE driver is not globally broken for all users; many companies are using it to run millions of test cases every day. I'm afraid there's nothing we can do with this issue report as written. There's just not enough information to go on, since the symptoms you describe can't be reproduced.
