### ISSUE TITLE
Firefox Timeout not configurable. (Firefox v46)

### ISSUE THREAD

**Issue by koraded** [SeleniumHQ/selenium#3981]
Hi,
 I am currently using Selenium 2.5.3 to automate test cases. The code has implicit and explicit timeouts set to be configurable after the driver is loaded. When i am using firefox however, it is not taking any of these timeouts into picture. The only timeout it is taking is the timeout that we hard code in the constructor when we load the driver:
webDriver = new FirefoxDriver(new FirefoxBinary(), new FirefoxProfile(), new System.TimeSpan(0, 2, 0));
If we remove this hard coded value altogether so that the implicit and explicit timeout can be set later, it is not taking the other timeouts and is instead taking a default of 60 seconds as the timeout no matter what value we are setting later. Can someone please help me with this issue?

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users). 

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
