### ISSUE TITLE
Firefox doesn't return Browser Version

### ISSUE THREAD

**Issue by danwan** [SeleniumHQ/selenium#4024]
FF: 53.0.2
Gecko: 16.1
Selenium 3.0
Platform: C#

I'm using:
var capabilities = ((RemoteWebDriver) driver).Capabilities;
_returnValue = capabilities.Version;

To get the version of the running browser. With Chrome and phantomjs it works perfectly fine.
But with FF it returns an empty string.

Is there a different way to do this now with Gecko?

PS: I already checked with the Geckodriver Team and they say that the version is returned in the capabilities.

Thank you
Dan

**Comment by jimevans** [comment]
Geckodriver, adhering to the [W3C WebDriver Specification](https://w3c.github.io/webdriver/webdriver-spec.html), returns the browser version in a capability with a different name (`browserVersion`) than drivers using the open-source dialect of the wire protocol (`version`).  You can find the browser version for Firefox by looking for that capability explicitly, instead of relying on the `Version` property. 

In future releases, when other drivers have implemented the spec, one of two things will happen. Either the `Version` property will be updated to look for the spec-compliant capability, or the property will be marked as deprecated (via use of the `Obsolete` attribute) and subsequently removed.
