### ISSUE TITLE
Upload file on Internet Explorer doesn't work

### ISSUE THREAD

**Issue by RSant0s** [SeleniumHQ/selenium#4026]
OS:  Windows 7
Browser:  Internet Explorer

`config.driver.find_element_by_id(action_attributes['element']).send_keys(abs_file_path)`

This python code works on chrome and firefox but doesn't work on Internet Explorer.

On IE the upload dialog is opened but the file is not selected.

**Comment by jimevans** [comment]
No version information on `IEDriverServer.exe`, no version information on Internet Explorer. This is particularly important in this case because changes to the file upload dialog handling in [version 3.4.0](https://github.com/SeleniumHQ/selenium/blob/master/cpp/iedriverserver/CHANGELOG) to resolve exactly this issue, as described in the closed issue #3587. In order to reopen this issue, we'll need a lot more information.

**Comment by RSant0s** [comment]
Thanks, this is the problem, I had IEDriverServer.exe version 3.3 and it didn't work, I checked the version 3.4 and it already works fine.
