### ISSUE TITLE
In testSuite a failure as seen as success too!

### ISSUE THREAD

**Issue by Lpempoul28** [SeleniumHQ/selenium#4039]
## Meta -
OS:  
Windows7
Selenium Version:  
2.9.1
Browser:  
Firefox 52.1.1

When you execute a TestSuite containing several test cases, each test case seen as failure, is enumerated too as success. So enumeration of success is not real and to obtain correct number you have to substract number of test cases seen as failure. Normally a test case is seen as success OR as failure, not possible to have two status! In opposite if a test case is seen as succes it is not added as failure.

Systematic bug!
Do you have an idea to fix it?

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
