### ISSUE TITLE
Looking for Notes/Reference how properly integrate "geckodriver" with C# VS2017 / Selenium 3

### ISSUE THREAD

**Issue by tttower** [SeleniumHQ/selenium#4050]
## Meta -
OS:  Win7-64
Selenium Version:  3.4
Browser:  FF 53.0.3
Geckodriver: V16.0
I can see "geckodriver" starts as process, not an console application like other drivers.
And no control over Firefox browser.

**Comment by tttower** [comment]
Environment: Win7-64, VS2017, Selenum v3.4.0, geckodriver v16.0. 
I can see "geckodriver" starts as process, not an console application like other drivers.
And no control over Firefox browser.

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
