### ISSUE TITLE
Unable to init server: Could not connect: Connection refused

### ISSUE THREAD

**Issue by codekaizer** [SeleniumHQ/selenium#4067]
Hi Selenium community,

I have a problem using Selenium.

```
1495299180874   geckodriver::marionette INFO    Starting browser /usr/lib/firefox/firefox with args ["-marionette"]
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :99
```

I'm using the following versions:

- Firefox 53.0
- Linux Fedora 22
- Geckodriver 0.16.1
- Selenium 3.4.1

Refer to my [post](http://stackoverflow.com/questions/44088743/xvfb-connection-refused-when-running-test-script-via-browser-on-fedora) for more info.

I really appreciate your help!

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
