### ISSUE TITLE
Illegal Utf-16 Sequence issue

### ISSUE THREAD

**Issue by EuclidHeron** [SeleniumHQ/selenium#4072]
## Meta -
OS:  OSX
Selenium Version:  2.4.2
Browser:  PhantomJS

## Expected Behavior -
I get the page source, perhaps with non-uff 16 characters ignored
## Actual Behavior -
Error is thrown

## Steps to reproduce -
In Python 3 do
driver = webdriver.PhantomJS(service_args=['--ignore-ssl-errors=true', '--ssl-protocol=any'])
driver.get("http://www.showboxpresents.com/events/detail/335755")
the above throws an error with 'URIError - String contained an illegal UTF-16 sequence'

Is there a way to specify to selenium (or webdriver) to ignore illegal sequences?

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
