### ISSUE TITLE
We are using Java JDK 1.8 with xFramium (Java - XML framework)= 1.0.6 and Selenium 2.53.1 (standalone server jar). Browser we are executing our test run on is IE 11.0 (even tried in compatibility mode). WebDriver used is that for 32 bit on 64 bit Windows 7. The setting of text data in the input fields are very slow. If we use the WebDriver 64 bit then it is further slow. Anyone who has faced it?

### ISSUE THREAD

**Issue by v-vek** [SeleniumHQ/selenium#4074]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by lmtierney** [comment]
http://jimevansmusic.blogspot.com/2014/09/screenshots-sendkeys-and-sixty-four.html
