### ISSUE TITLE
How to deal with IE blocking popup?

### ISSUE THREAD

**Issue by FilipFilipov** [SeleniumHQ/selenium#4086]
When running tests with the Internet Explorer Driver sometimes I get this popup:
 
![](http://www.pcmag.com/media/images/340974-set-up-ie11.jpg)

It blocks the loading of the required page for the test. How do I detect when this happens and close the popup?

**Comment by LinuxSuRen** [comment]
貌似可以通过浏览器设置来做到吧

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
