### ISSUE TITLE
Selenium does work with Drag and drop block based on dragula.

### ISSUE THREAD

**Issue by mike123vn** [SeleniumHQ/selenium#4088]
I tried many ways but it seems to be that selenum and protractor as well do not work with dragula.
Demo page:  http://valor-software.com/ng2-dragula/      
 p_Login.openUrl("http://valor-software.com/ng2-dragula/");
            let ele1=element(by.xpath("//example-app//div[contains(text(),'You can move')]"));
            let ele2=element(by.xpath("//example-app//div[contains(text(),'This is the default use case')]/.."));
       browser.driver.executeScript(dragAndDropFn, ele1.getWebElement(), ele2.getWebElement());

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
