### ISSUE TITLE
I got an error while running the script for chrome browser please help me to solve this issue

### ISSUE THREAD

**Issue by Premkumaryadav** [SeleniumHQ/selenium#4112]
Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"6716.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=58.0.3029.110)
  (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 46 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03

**Comment by lmtierney** [comment]
You're using chromedriver 2.9, use [version 2.29](https://chromedriver.storage.googleapis.com/index.html?path=2.29/)

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by Premkumaryadav** [comment]
Thanks for your suggestion .... My error got Resolved
