### ISSUE TITLE
Click is not working for FF 31 and chrome 32

### ISSUE THREAD

**Issue by Snehashree** [SeleniumHQ/selenium#412]
My click is not working in ff  31 and chrome 32
Chrome is throwing this error 
Element is not clickable at point (1444, 175). Other element would receive the click: 
while in ff its not even throwing any error. 

I have ff v 24.0 where click is working . my code structure is like that 
"<..section >
<..span>
< ..a id="anchorTagToClick"> 
        <..span id="idToClick"> 
             link to click 
        </...span>
<../a>
 <../span>
 <../section> "

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
