### ISSUE TITLE
Click() Selenium doesn't work on Edge

### ISSUE THREAD

**Issue by tjnhdo** [SeleniumHQ/selenium#4169]
Microsoft Edge 38.14393.1066.0
Microsoft EdgeHTML 14.14393
Selenium 3.4.0

You can refer image below. The style the same with another browser. When I use element with click(), always error message displays "Additional information: Element not displayed"
![image](https://user-images.githubusercontent.com/14869318/27072188-ceaa806a-5049-11e7-908b-67ba12284b6e.png)

I can handle with javascriptClick
public void JavaScriptClick(IWebElement element)
{
IJavaScriptExecutor executor = (IJavaScriptExecutor)driver;
executor.ExecuteScript("arguments[0].click();", element);
}

But I think it's issue of Selenium ( not issue of Edge). Please help me check. 
Thanks

**Comment by lmtierney** [comment]
There's no way for us to help you check as we don't have a reproducible test case. If you cannot reproduce this with Chrome or Firefox then it's an issue with Edge.

Please log any Edge & MicrosoftWebdriver issues with Microsoft: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/?page=1&q=webdriver

Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. Once this is done the issue will be re-opened. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
