### ISSUE TITLE
C# Selenium How to use Safari Technology Preview

### ISSUE THREAD

**Issue by jibujmathew-rm** [SeleniumHQ/selenium#4179]
## Meta -
OS:  Mac

Selenium Version:  3.3

Browser:  Safari

Browser Version:  10

## Expected Behavior -
Can use Safari Technology Preview using C# WebDriver.
## Actual Behavior -
Unable to find a method which instruct to use Safari Technology Preview
## Steps to reproduce -
How we instruct Selenium to use Safari Technology Preview in C#?

In Java, we can set that using the method setUseTechnologyPreview, but unable to find similar method in C# class SafariOptions.

We have tried by using options.AddAdditionalCapability('useTechnologyPreview', true), but it did not work.

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
