### ISSUE TITLE
Not able to open Firefox through new FirefoxDriver(); in selenium 3.4

### ISSUE THREAD

**Issue by samnit** [SeleniumHQ/selenium#4197]
## Meta -
OS:  
Windows 10
Selenium Version:  
**3.4**
Browser:  
**Firefox 53**

**I am not able to run Firefox browser through FirefoxDriver();**

Here is the piece of code that I used : 
                WebDriver ldriver=null;
		System.setProperty("webdriver.gecko.driver","<Path to gecko driver>");
		ldriver = new FirefoxDriver();
**Then it is throwing error of browserName cannot be boolean**

When I use this peice of code : 
                WebDriver ldriver=null;
                DesiredCapabilites Cap=new DesiredCapabilites(ldriver);
                cap.setCapability("marionette",false);
		System.setProperty("webdriver.gecko.driver","<Path to gecko driver>");
		ldriver = new FirefoxDriver(cap);

**Then the browser is getting opened but not able to get URL in the browser after that and getting this** **error**  : -
1497848509960 addons.manager DEBUG Registering shutdown blocker for PreviousExperimentProvider
1497848509961 addons.manager DEBUG Provider finished startup: PreviousExperimentProvider
1497848509964 DeferredSave.extensions.json DEBUG Starting write
1497848509966 DeferredSave.addons.json DEBUG Starting write
1497848510244 DeferredSave.extensions.json DEBUG Write succeeded
1497848510254 DeferredSave.addons.json DEBUG Write succeeded
[ODEBUG] [Explorer Probe] [disableSPDY]#In disableSPDY()[ODEBUG] [Explorer Probe] [disableSPDY]#Trying to get profile path from command line if exists[ODEBUG] [Explorer Probe] [disableSPDY]#Didn't get any profile from command line, get all FireFox profiles from AppDataException in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'INNOSZPC00536', ip: '192.168.99.1', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_25'
Driver info: driver.version: FirefoxDriver
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:108)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:137)
at com.automatics.packages.library.test.main(test.java:24)
Caused by: java.lang.NullPointerException
at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:192)
at org.openqa.selenium.firefox.XpiDriverService.start(XpiDriverService.java:94)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:78)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
... 7 more

**Comment by p0deje** [comment]
You can't use legacy Firefox driver with Firefox 53 - you need to start using geckodriver.

**Comment by samnit** [comment]
@p0deje  I am giving gecko driver path to run the firefox but how to use gecko driver to start my firefox. That should be enabled through Firefox Driver. Right?

**Comment by p0deje** [comment]
You just have to set `webdriver.gecko.driver` property to point to geckodriver path and use `FirefoxDriver()` normally.

**Comment by samnit** [comment]
@p0deje I am doing that only. I haven't put my path of gecko driver in the above code but I am providing gecko driver path in my code before executing my file. Its still not running,

**Comment by p0deje** [comment]
Then please provide [concise reproducible test case](http://sscce.org/) and GeckoDriver + Firefox versions you use so that we could act on this issue. I cannot reproduce this.

**Comment by SudeeptMohan** [comment]
Title : The browser is getting opened but not able to get URL in the browser

OS:Windows 10

Execution Environment : JavaSE-1.8 (jre1.8.0_144)

JARs and class folders on build path:
client-combined-3.6.0-sources.jar
client-combined3.6.0.jar
selenium-server-standalone-3.6.0.jar

Browser:
FireFox 56.0

Code Snippet:
System.setProperty("webdriver.firefox.marionette","C:/Users/admin/Downloads/geckodriver-v0.11.1-win32/geckodriver.exe");
WebDriver driver = 	new FirefoxDriver ();
driver.get("https://www.facebook.com");

Error:
Exception in thread "main" org.openqa.selenium.WebDriverException: Timed out waiting 45 seconds for Firefox to start.
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:26.402Z'
System info: host: 'ADMIN-PC', ip: '192.168.1.6', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.XpiDriverService.waitUntilAvailable(XpiDriverService.java:112)
	at org.openqa.selenium.firefox.XpiDriverService.start(XpiDriverService.java:97)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:217)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:140)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:98)
	at FacebookFriends.main(FacebookFriends.java:18)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:45149/hub/status] to be available after 45005 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
	at org.openqa.selenium.firefox.XpiDriverService.waitUntilAvailable(XpiDriverService.java:110)
	... 8 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:147)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
	... 9 more

**Comment by 23kk** [comment]
SudeeptMohan i am also getting exctly same issue with same configurations. Have you got any solution?

**Comment by SudeeptMohan** [comment]
Try using the command 
System.setProperty("**webdriver.gecko.driver**","C:\\Marionette\\geckodriver_1.exe" ); instead of 
System.setProperty("webdriver.firefox.marionette","C:/Users/admin/Downloads/geckodriver-v0.11.1-win32/geckodriver.exe");

**Comment by rohantiwatne** [comment]
i write marionette but i does not work

package automation_Framework;

	import java.util.concurrent.TimeUnit;

	import org.openqa.selenium.By;
	import org.openqa.selenium.WebDriver;
	import org.openqa.selenium.firefox.FirefoxDriver;
	public class NewAm {
	    public static void main(String[] args) {
	    	System.setProperty("webdriver.firefox.marionette","F:\\New folder\\geckodriver-v0.20.1-win64 (2)\\geckodriver.exe");
	            WebDriver driver = new FirefoxDriver();
	            driver.manage().window().maximize();
	            String url ="https://accounts.google.com/signin";
	            driver.get(url);
	            driver.findElement(By.id("identifierId")).sendKeys("rohantiwatne9@gmail.com"); 
	            driver.findElement(By.xpath("//span[@class='RveJvd snByac']")).click();         
	            driver.manage().timeouts().implicitlyWait(40, TimeUnit.SECONDS);        
	            driver.findElement(By.xpath("//input[@class='whsOnd zHQkBf']")).sendKeys("9404857753");             
	            driver.findElement(By.xpath("//span[@class='RveJvd snByac']")).click(); 
	    }  
	}

**Comment by SudeeptMohan** [comment]
@rohantiwatne Try following code, it will work out

package automation_Framework;

	import java.util.concurrent.TimeUnit;

	import org.openqa.selenium.By;
	import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxDriverLogLevel;
import org.openqa.selenium.firefox.FirefoxOptions;
	public class NewAm {
	    public static void main(String[] args) {
	    	System.setProperty("webdriver.gecko.driver","F:\\New folder\\geckodriver-v0.20.1-win64 (2)\\geckodriver.exe");
	    	FirefoxOptions options = new FirefoxOptions();
			options.setLogLevel(FirefoxDriverLogLevel.DEBUG);
			WebDriver driver = new FirefoxDriver(options);
	            
				driver.manage().window().maximize();
	            String url ="https://accounts.google.com/signin";
	            driver.get(url);
	            driver.findElement(By.id("identifierId")).sendKeys("rohantiwatne9@gmail.com"); 
	            driver.findElement(By.xpath("//span[@class='RveJvd snByac']")).click();         
	            driver.manage().timeouts().implicitlyWait(40, TimeUnit.SECONDS);        
	            driver.findElement(By.id("recoveryIdentifierId")).sendKeys("9404857753");
	            	                         
	            driver.findElement(By.xpath("//span[@class='RveJvd snByac']")).click(); 
	    }  
	}

**Comment by Pari-Say** [comment]
I was getting the same issue but got resolved by replacing the following @sudeeptMohans piece of code snipplet: 

Try using the command
System.setProperty("webdriver.gecko.driver","C:\Marionette\geckodriver_1.exe" ); instead of
System.setProperty("webdriver.firefox.marionette","C:/Users/admin/Downloads/geckodriver-v0.11.1-win32/geckodriver.exe");

Now the code is being run properly with the required url being opened in the firefox. But still shows the error in the console along with the result. 

========================
Environment
========================
OS: Windows 10
JDK-10.0.1
Eclipse Oxygen
Selenium Java Drivers 3.12.0
gecodriver-v0.20.1

=========================
The code Im tryin to run:
=========================

package seleniumpackage1;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
//comment the above line and uncomment below line to use Chrome
//import org.openqa.selenium.chrome.ChromeDriver;
public class MyClass {
	
	
	public static void main(String[] args) {
	// declaration and instantiation of objects/variables
	System.setProperty("webdriver.gecko.driver","C:\\geckodriver.exe");
	WebDriver driver = new FirefoxDriver();
	//comment the above 2 lines and uncomment below 2 lines to use Chrome
	//System.setProperty("webdriver.chrome.driver","G:\\chromedriver.exe");
	//WebDriver driver = new ChromeDriver();
	
    String baseUrl = "http://demo.guru99.com/test/newtours/";
    String expectedTitle = "Welcome: Mercury Tours";
    String actualTitle = "";

    // launch Fire fox and direct it to the Base URL
    driver.get(baseUrl);

    // get the actual value of the title
    actualTitle = driver.getTitle();

    /*
     * compare the actual title of the page with the expected one and print
     * the result as "Passed" or "Failed"
     */
    if (actualTitle.contentEquals(expectedTitle)){
        System.out.println("Test Passed!");
    } else {
        System.out.println("Test Failed");
    }
   
    //close Fire fox
    driver.close();
	}
}

==============================
Console Display:
==============================
1527842162922	geckodriver	INFO	geckodriver 0.20.1
1527842162949	geckodriver	INFO	Listening on 127.0.0.1:41496
1527842164038	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "C:\\Users\\Dell\\AppData\\Local\\Temp\\rust_mozprofile.k56oF9gND158"
Unable to read VR Path Registry from C:\Users\Dell\AppData\Local\openvr\openvrpaths.vrpath
1527842165648	Marionette	INFO	Enabled via --marionette
Unable to read VR Path Registry from C:\Users\Dell\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\Dell\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\Dell\AppData\Local\openvr\openvrpaths.vrpath
1527842171506	Marionette	INFO	Listening on port 6659
1527842171996	Marionette	WARN	TLS certificate errors will be ignored for this session
Jun 01, 2018 2:06:12 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Unable to read VR Path Registry from C:\Users\Dell\AppData\Local\openvr\openvrpaths.vrpath
JavaScript warning: https://www.googletagmanager.com/gtag/js?id=UA-1248015-24, line 69: unreachable code after return statement
JavaScript warning: https://www.googletagmanager.com/gtag/js?id=UA-1248015-24, line 69: unreachable code after return statement
Test Passed!
[Parent 8076, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 15436, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 15436, Chrome_ChildThread] [Parent 8076, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping

###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv

**Comment by rohantiwatne** [comment]
Thank you
