### ISSUE TITLE
Using Firefox profile is not working with other device but not in my working device, in C#

### ISSUE THREAD

**Issue by 5ervant** [SeleniumHQ/selenium#4247]
## Meta -
OS: Windows 10 

Selenium Version: 3.4.0 

Browser: Firefox 

Browser Version: 54.0.1 (32-bit, it's working well in my working device!) 

## Expected Behavior -
Will just open a Firefox browser to manipulate.
## Actual Behavior -
It's working well with my working device but not with other.
## Steps to reproduce -

For more info, please visit: https://stackoverflow.com/q/44869739/4883372

Using Firefox profile is working as expected with my working device but not on the other device. It seems that the app is waiting for a timeout, then after that, the geckodriver will open and the thread will now be done.

What's the problem here? It's working well in my device... Could the downgrade of Firefox to v47 or by disabling its extensions will allow the other device to make it work?

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.

**Comment by 5ervant** [comment]
This is also an issue, I did the code right but not working on other devices.

**Comment by p0deje** [comment]
The fact that it works on 1 device and not on other probably means that this is not a Selenium issue (it doesn't take devices into account). It's also very hard to understand what you mean by "other devices". Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue. I'll re-open the issue once the test case that maintainers could run to see the issue is provided.
