### ISSUE TITLE
selenium.common.exceptions.ElementNotInteractableException: Message

### ISSUE THREAD

**Issue by grazielegs** [SeleniumHQ/selenium#4269]
**OS:**  Windows 7

**Selenium Version:**  3.4.3

**Browser:**  Firefox ISR and Google Chrome

Hi Guys, I've been reading some issues here and StackOverflow topics but nothing helps yet. So, I'm testing some simple codes for Firefox and Google Chrome and they are a little bit unstable. When I said ''simple codes'' I'm refering about stuff like logon, searchs and open menu with dropdown. Sometimes, when I execute this codes in Firefox I receive this message:
_"raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: "_
or
_"selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette"_

When I execute in Google Chrome I don't have any problem, but the problem is when I tried to execute again on Firefox, sometimes execute with errors and sometimes I have sucess. I've made some tests using the Selenium IDE, but seens they don't work well with the system what I'm testing here.
I know, this errors sound "generic" but I don't understand why are so unstable for simple comands like .send_keys().

**This is an example of my tests:**

`driver = self.driver
        driver.get(self.base_url + "mylink")
        driver.find_element_by_css_selector("#menu_search").click()
        driver.find_element_by_name("name").clear()
        driver.find_element_by_name("name").send_keys("grazigs")
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("***")
        driver.find_element_by_css_selector("profile_type").click()
        driver.find_element_by_css_selector("cyborg:profile_type").click()
        driver.find_element_by_xpath("//button[@type='login']").click()
        driver.find_element_by_link_text("consult_friends").click()
        driver.find_element_by_xpath("(//input[@type='search_box'])[1]").clear()
        driver.find_element_by_xpath("(//input[@type='search_box'])[1]").send_keys("my friend")
        driver.find_element_by_css_selector("btnSearch").click()
        driver.find_element_by_link_text("Best Friend Profile").click()`

Browser Version:  59.0.3071.115 (Google Chrome) and 52.2.1 (Firefox)

**Comment by p0deje** [comment]
You're probably facing a race condition, so sometimes the element you try to interact with is not ready for interaction and sometimes it is ready. There are subtle differences in how Chrome and Firefox drivers define elements being interactable, which is probably why it doesn't fail on Chrome. The other reason might be performance difference in Chrome/Firefox browsers/drivers.

In both cases I suggest to add some additional waitings to make sure that is a race condition. For example, you could add a simple sleep for a couple of seconds before the line that raises exception. If this solves the problem, than it's definitely a race condition.

If the problem still persists, please provide a test script that we could run locally to debug the issue and I'll re-open this issue.

**Comment by grazielegs** [comment]
Thanks for the answer! I noticed in some tests that when I add waitings they have different results. I think thats explain a lot for my problem, thanks again. 
_Best regards._

**Comment by JKAK47** [comment]
hi @p0deje , i met the same problem, and i add time.sleep, but this problem still exist, below are my scripts, could you please have a look? many thanks!

**Comment by JKAK47** [comment]
#!/usr/bin/env python3
# --*-- coding utf-8 --*--
#新建文件utf-8编码保存，Python3.5.2
# coding:utf-8
__author__='PengRong'

from selenium import webdriver
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait  # available since 2.4.0
import selenium.webdriver.common.by as bb
from selenium import webdriver
import time


driver=webdriver.Firefox()
driver.set_window_size(1080,900)
driver.implicitly_wait(15)
driver.get("https://kyfw.12306.cn")

driver.find_element_by_id("login_user").click()
#driver.find_element_by_id("username").send_keys("1198433749@qq.com")
#driver.find_element_by_id("password").send_keys("aceg123199122")

#input("请填写验证码图片，完成后继续")


driver.find_element_by_link_text("车票预订").click()

time.sleep(3)
#出发地
driver.find_element_by_id("fromStationText").click()
driver.find_element_by_css_selector("[title=杭州]").click()

time.sleep(3)
#目的地
driver.find_element_by_id("toStationText").click()
driver.find_element_by_css_selector("[title=南京]").click()

time.sleep(3)
#出发日期
driver.find_element_by_id("train_date").click()
driver.find_element_by_css_selector("body>div.cal-wrap>div:nth-child(1)>div.cal-cm>div:nth-child(22)>div").click()

time.sleep(3)
#只选择高铁类型车次
driver.find_element_by_css_selector("#_ul_station_train_code>li:first-child").click()
#  #_ul_station_train_code > li:nth-child(1)  from firefox

#点击查询按钮
driver.find_element_by_id("query_ticket")


#选择座位类型:二等座
seat=driver.find_element_by_id("ZE_56000G431400")
seat.click()
print(seat.text)

#反复刷新查询看是否有票
while True:
	try:
		driver.find_element_by_id("query_ticket").click()
		seat = driver.find_element_by_id( "ZE_56000G431400" )
		seat.click( )
		if seat.text in['无','--']:
			print('暂时无票，继续查询')
			time.sleep(2)
		else:
			print('有票')
			break
	except:
		pass
