### ISSUE TITLE
TypeKeys not working in IE or Chrome with latest version of webdrive

### ISSUE THREAD

**Issue by akila1** [SeleniumHQ/selenium#428]
My test with typekeys command works fine in Firefox. But when I run the same test in IE or Chrome it doesn't work.
Does anyone have any work around for this issue. Please Advice.
Thanks

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
