### ISSUE TITLE
location_once_scrolled_into_view change the element

### ISSUE THREAD

**Issue by raffam** [SeleniumHQ/selenium#4280]
## Meta -
OS:  Windows 10

Selenium Version:  3.4.3

Browser:  Firefox

Browser Version:  54.0.2

## Expected Behavior -
The correct link (the one to expand the experience section) should be clicked with or without calling location_once_scrolled_into_view on the button element before the clicking

## Actual Behavior -
If you call `btn.location_once_scrolled_into_view` before calling `btn.click()`, it does NOT work. The search text box on the navbar is clicked instead. This element was never selected in our code.
If you comment the `btn.location_once_scrolled_into_view` line, it works correctly. 
This line should not change the element , and thus should not change which element is clicked.
See also the comment on the attached SSCCE 

## Steps to reproduce -

You need a LinkedIn account, and substitute the `username` and `password` variable with the username and password of your LinkedIn account

```
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

url = "https://www.linkedin.com/in/orarbel/"
username = "YOUR_USERNAME"
password = "YOUR_PASSWORD"

def sessionKeyLogin(driver):
    login_email_element = driver.find_element_by_id("session_key-login")
    login_password_element = driver.find_element_by_id("session_password-login")
    login_email_element.clear()
    login_password_element.clear()
    login_email_element.send_keys(username)
    login_password_element.send_keys(password)
    login_password_element.submit()
    time.sleep(5)
        
driver = webdriver.Firefox()
driver.get(url)
time.sleep(5)

signin_link = driver.find_element_by_class_name("sign-in-link")
signin_link.click()
time.sleep(5)
sessionKeyLogin(driver)

driver.get(url)
time.sleep(5)

btn = driver.find_element_by_class_name("experience-section").find_element_by_css_selector(".pv-profile-section__see-more-inline.link")
#If you comment the following line, it works, and the link to expand the experience section is clicked
#If you un-comment the following lines, the search textbox on the navbar is clicked instead
btn.location_once_scrolled_into_view
time.sleep(5)
btn.click()
```

**Comment by p0deje** [comment]
Thank you for report and a test case that clearly shows the problem!

This is both an expected behavior and a bug, let me try to explain what happens here.

We locate "See more positions" element:

<img width="213" alt="screen shot 2017-07-09 at 08 43 15" src="https://user-images.githubusercontent.com/665846/27990743-b769292c-6482-11e7-895a-3a04ae19daa5.png">

If you don't call `.location_once_scrolled_into_view`, the element is not in a viewport. When you call `.click`, GeckoDriver will automatically scroll the page until the element is visible. [WebDriver spec tells](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-scrolled-into-view) to scroll to **to the very bottom of viewport**, so the button is not overlapped by other elements and click successfully happens.

If you call `.location_once_scrolled_into_view` it will scroll the element **to the very top of viewport**. Once it is on the top, a sticky header with search field overlaps this button, so an attempt to click on button (which is essentially an attempt to click at the coordinates of the center of the button) is intercepted by search field.

<img width="416" alt="screen shot 2017-07-09 at 08 47 12" src="https://user-images.githubusercontent.com/665846/27990759-375193fe-6483-11e7-8489-f2e85fefa6a9.png">

So, this is kind of expected behavior. The real problem here is that GeckoDriver should satisfy step 7 of [element click](https://w3c.github.io/webdriver/webdriver-spec.html#element-click):

> If element’s container is obscured by another element, return error with error code element click intercepted.

Instead of simply clicking on search field, you should instead get an element click intercepted exception. I have reported mozilla/geckodriver#813 for this.

**Comment by raffam** [comment]
Are you sure this is the intended behavior for `location_once_scrolled_into_view`? 
It is called "once scrolled **into view**". If the element is behind the navbar, it means it is not in view, right? Either the function should be renamed "once scrolled to the top of the page" (so it correctly gets behind the navbar) or the name should stay the same but the element should be placed below the navbar, so to be visible (and clickable). Is this function part of the W3C specification or only of Selenium?

Also the Selenium Python binding [documentation](https://seleniumhq.github.io/selenium/docs/api/py/webdriver_remote/selenium.webdriver.remote.webelement.html#module-selenium.webdriver.remote.webelement) (is this the correct / official link?) says "Use this to discover where on the screen an element is **so that we can click it**. This method should **cause the element to be scrolled into view**.". Again, if the element is behind a navbar, we can't click on it and it is not into view, right?

**Comment by p0deje** [comment]
> Are you sure this is the intended behavior for location_once_scrolled_into_view?
It is called "once scrolled into view". If the element is behind the navbar, it means it is not in view, right? 

Element can be in view, but still not visible and/or clickable. This might be confusing, but these are all different things:

* element in viewport means that element coordinates are within the coordinates range visible part of the page
* element is visible when it doesn't have CSS rules hiding it (e.g. `display: none`)
* element is clickable when you can retrieve it and not other element by using its coordinates (e.g. with `document.elementFromPoint()`

> Either the function should be renamed "once scrolled to the top of the page" (so it correctly gets behind the navbar) or the name should stay the same but the element should be placed below the navbar, so to be visible (and clickable).

The implementations are different. So, for example, ChromeDriver would scroll element to the bottom of the page while GeckoDriver scrolls it to the top. Checking visibility/clickability should not really be the responsibility of this method.

> Is this function part of the W3C specification or only of Selenium?

It's not a part of the spec. I'd recommend avoiding it. Usually, you don't need to scroll the element into view manually because Selenium already does that, but even if you need, consider executing JavaScript `element.scrollIntoView()`.

P.S. I guess you can remove the same comment from mozilla/geckodriver#813 - it's not really relevant for that issue.

**Comment by raffam** [comment]
> Element can be in view, but still not visible and/or clickable. This might be confusing, but these are all different things

Thanks you. I did not know that

> The implementations are different. So, for example, ChromeDriver would scroll element to the bottom of the page while GeckoDriver scrolls it to the top

Although this inconsistency can be a problem. I understand your bug report regards the fact that GeckoDriver should have thrown an error (not that he should click the link). Suppose you need the element to be _clickable_. In the situation of the example, if you call `location_once_scrolled_into_view` from GeckoDriver, than you need to scroll down a bit to make the link _clickable_. From ChromeDriver, instead, you don't have to do anything else (because the element is scrolled to the bottom of the page and if you scroll even more to the bottom the link lose _clickability_). So at this point it's better to call the javascript function instead of changing the code according to the backend

> P.S. I guess you can remove the same comment from mozilla/geckodriver#813 - it's not really relevant for that issue.

I did almost immediately after posting it. It was an error (had both tabs open)

> Usually, you don't need to scroll the element into view manually because Selenium already does that

You may hear me again about that, but I'm still not sure and trying to build an example :)

Thanks again

**Comment by p0deje** [comment]
Please keep in mind that W3C spec doesn't specify this command so at some point it might go into 2 directions:

1. Selenium will simply deprecate and remove this command
2. W3C spec will adopt the command and thus make it consistent across all the drivers

**Comment by raffam** [comment]
On a side note, I found the best way to click on an element to do it through Javascript

`driver.execute_script("arguments[0].click();", link)`

In this way the element does not need to be clickable (uniquely identified by its screen coordinates)

**Comment by jimevans** [comment]
@raffam That's a fine notion, but it also does not replicate what the user would do. If you are okay with that disconnect, and the potential for missed bugs because you're performing the action in a way the user is not, that's your prerogative.
