### ISSUE TITLE
get errors for mouseMove inside iframe

### ISSUE THREAD

**Issue by anahit42** [SeleniumHQ/selenium#4304]
## Meta -
OS:  
Ubuntu 17.04

Browser:  
Google Chrome

Hi,

I've come to a problem with mouse moving and clicking in iframes. Here is my code that can reproduce the error. 

`import Webdriver from 'selenium-webdriver';

let By = Webdriver.By;
let until = Webdriver.until;
let driver = new Webdriver.Builder()
    .forBrowser('chrome')
    .build();

driver.get('https://www.totogaming.am/Backgammon');

driver.switchTo().frame(driver.findElement(By.xpath('//*[@id="p2pFrame"]')));
driver.wait(until.elementLocated(By.xpath('//*[@id="pageNewGameBet"]')), 8000).then((elem) => {
    elem.sendKeys(41);
    driver.actions().mouseMove(elem).perform();

});

`

And this is the error that I get. 
https://gist.github.com/anahit42/27ca7b73f479fb56621fe3a39248a7bd

I wonder if this is chromedriver error or it is not possible to click inside iframe element using selenium-webdriver. 

Browser Version:  

chrome=59.0.3071.104

## Actual Behavior

**Comment by lmtierney** [comment]
Look at the error it's giving you, there appears to be a live chat element covering what you're intending to click

```
<div id="livechat-compact-container" style="position: fixed; bottom: 0px; right: 15px; width: 250px; height: 53px; overflow: hidden; visibility: visible; z-index: 2147483639; background: transparent; border: 0px; transition: transform 0.2s ease-in-out; backface-visibility: hidden; opacity: 1; transform: translateY(0%);">...</div>
```

Selenium/chromedriver will scroll the page just enough for the element you want to click to be in the viewport. Since the live chat element is floating, it's covering what you're trying to click. You will probably need to do some scrolling to get it out, or get rid of the livechat element

**Comment by anahit42** [comment]
Thank you very much, I was lost in errors and didn't notice that part.
