### ISSUE TITLE
Unable to launch mozila firefox using selenium

### ISSUE THREAD

**Issue by hashim22** [SeleniumHQ/selenium#4331]
## Meta -
OS:  
Win 8
Selenium Version:  
 Eclipse 4.5.2
Browser:  
firefox 54.0

As I am new to selenium ,when i tried to launch the mozila via web driver ,I am gettin  the following error.Please suggest some possible solutions
**Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V
	at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:136)
	at org.openqa.selenium.firefox.GeckoDriverService.access$000(GeckoDriverService.java:41)
	at org.openqa.selenium.firefox.GeckoDriverService$Builder.usingFirefoxBinary(GeckoDriverService.java:108)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:204)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:108)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:104)
	at test10.Test1.main(Test1.java:11)**

And here is the code which i used
package test10;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class Test1 {

	public static void main(String[] args) {
		System.setProperty("webdriver.firefox.bin","C:\\Users\\muhammed_pk\\AppData\\Local\\Mozilla Firefox\\firefox.exe");
		System.setProperty("webdriver.firefox.driver","D:\\New folder\\geckodriver.exe");
		WebDriver driver= new FirefoxDriver();
		driver.get("http://www.google.com");
		// TODO Auto-generated method stub

	}

}

**Comment by saideepika1** [comment]
Even I am getting the same error as the above , 
at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:136)
at org.openqa.selenium.firefox.GeckoDriverService.access$000(GeckoDriverService.java:41)
at org.openqa.selenium.firefox.GeckoDriverService$Builder.usingFirefoxBinary(GeckoDriverService.java:108)
at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:204)
at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:108)
at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:104)

Please help me out in rectifying it.

**Comment by barancev** [comment]
Check the classpath, you have an outdated guava dependency, update it to version 21.

**Comment by hashim22** [comment]
hi baran

I have checked the jar files and found that guava 21 is already there in the JAR file.
![guava](https://user-images.githubusercontent.com/30263347/28359634-8f47e576-6c90-11e7-8a22-86b3b4474929.jpg)

**Comment by barancev** [comment]
Yes, but guava 19 is here too. Fix your classpath to avoid conflicts.

**Comment by hashim22** [comment]
Thanks Baran......it got worked. :)

**Comment by saideepika1** [comment]
Hi Baran,
Still I am getting the below error:
1500474241866	addons.manager	DEBUG	Application has been upgraded
1500474242116	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1500474242120	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1500474242128	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1500474242131	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1500474242133	addons.manager	DEBUG	Starting provider: XPIProvider
1500474242133	addons.xpi	DEBUG	startup
1500474242134	addons.xpi	INFO	Mapping fxdriver@googlecode.com to C:\Users\IT\AppData\Local\Temp\anonymous6190436837776176908webdriver-profile\extensions\fxdriver@googlecode.com
1500474242135	addons.xpi	DEBUG	Ignoring file entry whose name is not a valid add-on ID: C:\Users\IT\AppData\Local\Temp\anonymous6190436837776176908webdriver-profile\extensions\webdriver-staging
1500474242135	addons.xpi	INFO	Removing all system add-on upgrades.
1500474242136	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1500474242138	addons.xpi	INFO	Mapping aushelper@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1500474242138	addons.xpi	INFO	Mapping e10srollout@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1500474242138	addons.xpi	INFO	Mapping firefox@getpocket.com to C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1500474242139	addons.xpi	INFO	Mapping screenshots@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\screenshots@mozilla.org.xpi
1500474242139	addons.xpi	INFO	Mapping webcompat@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1500474242142	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to C:\Program Files (x86)\Mozilla Firefox\browser\extensions\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1500474242143	addons.xpi	DEBUG	Skipping unavailable install location app-system-share
1500474242143	addons.xpi	DEBUG	Skipping unavailable install location app-system-local
1500474242144	addons.xpi	DEBUG	checkForChanges
1500474242144	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1500474242145	addons.xpi	DEBUG	Loaded add-on state from prefs: {}
1500474242146	addons.xpi	DEBUG	New add-on fxdriver@googlecode.com in app-profile
1500474242147	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
1500474242157	addons.xpi	DEBUG	New add-on aushelper@mozilla.org in app-system-defaults
1500474242158	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1500474242159	addons.xpi	DEBUG	New add-on e10srollout@mozilla.org in app-system-defaults
1500474242159	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1500474242160	addons.xpi	DEBUG	New add-on firefox@getpocket.com in app-system-defaults
1500474242160	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1500474242161	addons.xpi	DEBUG	New add-on screenshots@mozilla.org in app-system-defaults
1500474242161	addons.xpi	DEBUG	getModTime: Recursive scan of screenshots@mozilla.org
1500474242162	addons.xpi	DEBUG	New add-on webcompat@mozilla.org in app-system-defaults
1500474242162	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1500474242163	addons.xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1500474242163	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1500474242163	addons.xpi	DEBUG	getInstallState changed: true, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\IT\\AppData\\Local\\Temp\\anonymous6190436837776176908webdriver-profile\\extensions\\fxdriver@googlecode.com","st":1500474239165,"mt":1500474239154}},"app-system-defaults":{"aushelper@mozilla.org":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\aushelper@mozilla.org.xpi","st":1498666862000},"e10srollout@mozilla.org":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\e10srollout@mozilla.org.xpi","st":1498666862000},"firefox@getpocket.com":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\firefox@getpocket.com.xpi","st":1498666863000},"screenshots@mozilla.org":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\screenshots@mozilla.org.xpi","st":1498666863000},"webcompat@mozilla.org":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\webcompat@mozilla.org.xpi","st":1498666862000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","st":1498666862000}}}
1500474242174	addons.xpi-utils	DEBUG	Opening XPI database C:\Users\IT\AppData\Local\Temp\anonymous6190436837776176908webdriver-profile\extensions.json
1500474242176	addons.xpi-utils	DEBUG	New add-on fxdriver@googlecode.com installed in app-profile
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1500474242252	addons.xpi	WARN	Add-on fxdriver@googlecode.com is not correctly signed.
1500474242253	addons.xpi	WARN	Add-on fxdriver@googlecode.com is not correctly signed.
1500474242256	DeferredSave.extensions.json	DEBUG	Save changes
1500474242256	addons.xpi-utils	DEBUG	New add-on aushelper@mozilla.org installed in app-system-defaults
1500474242281	DeferredSave.extensions.json	DEBUG	Starting timer
1500474242284	DeferredSave.extensions.json	DEBUG	Save changes
1500474242284	addons.xpi-utils	DEBUG	New add-on e10srollout@mozilla.org installed in app-system-defaults
1500474242299	DeferredSave.extensions.json	DEBUG	Save changes
1500474242300	addons.xpi-utils	DEBUG	New add-on firefox@getpocket.com installed in app-system-defaults
1500474242317	DeferredSave.extensions.json	DEBUG	Save changes
1500474242317	addons.xpi-utils	DEBUG	New add-on screenshots@mozilla.org installed in app-system-defaults
1500474242348	DeferredSave.extensions.json	DEBUG	Starting write
1500474242373	DeferredSave.extensions.json	DEBUG	Save changes
1500474242373	DeferredSave.extensions.json	DEBUG	Data changed while write in progress
1500474242373	addons.xpi-utils	DEBUG	New add-on webcompat@mozilla.org installed in app-system-defaults
1500474242389	DeferredSave.extensions.json	DEBUG	Save changes
1500474242390	addons.xpi-utils	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
1500474242409	DeferredSave.extensions.json	DEBUG	Save changes
1500474242409	addons.manager	DEBUG	Registering startup change 'installed' for fxdriver@googlecode.com
1500474242410	addons.xpi-utils	DEBUG	Make addon app-profile:fxdriver@googlecode.com visible
1500474242410	DeferredSave.extensions.json	DEBUG	Save changes
1500474242410	addons.manager	DEBUG	Registering startup change 'installed' for aushelper@mozilla.org
1500474242428	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1500474242434	addons.xpi	DEBUG	Calling bootstrap method install on aushelper@mozilla.org version 2.0
1500474242434	addons.xpi-utils	DEBUG	Make addon app-system-defaults:aushelper@mozilla.org visible
1500474242434	DeferredSave.extensions.json	DEBUG	Save changes
1500474242435	addons.manager	DEBUG	Registering startup change 'installed' for e10srollout@mozilla.org
1500474242435	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1500474242439	addons.xpi	DEBUG	Calling bootstrap method install on e10srollout@mozilla.org version 1.50
1500474242441	addons.xpi-utils	DEBUG	Make addon app-system-defaults:e10srollout@mozilla.org visible
1500474242441	DeferredSave.extensions.json	DEBUG	Save changes
1500474242441	addons.manager	DEBUG	Registering startup change 'installed' for firefox@getpocket.com
1500474242442	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1500474242447	addons.xpi	DEBUG	Calling bootstrap method install on firefox@getpocket.com version 1.0.5
1500474242447	addons.xpi-utils	DEBUG	Make addon app-system-defaults:firefox@getpocket.com visible
1500474242447	DeferredSave.extensions.json	DEBUG	Save changes
1500474242448	addons.manager	DEBUG	Registering startup change 'installed' for screenshots@mozilla.org
1500474242448	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\screenshots@mozilla.org.xpi
1500474242451	addons.xpi	DEBUG	Calling bootstrap method install on screenshots@mozilla.org version 6.6.0
1500474242451	addons.xpi-utils	DEBUG	Make addon app-system-defaults:screenshots@mozilla.org visible
1500474242452	DeferredSave.extensions.json	DEBUG	Save changes
1500474242452	addons.manager	DEBUG	Registering startup change 'installed' for webcompat@mozilla.org
1500474242453	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1500474242456	addons.xpi	DEBUG	Calling bootstrap method install on webcompat@mozilla.org version 1.1
1500474242456	addons.xpi-utils	DEBUG	Make addon app-system-defaults:webcompat@mozilla.org visible
1500474242456	DeferredSave.extensions.json	DEBUG	Save changes
1500474242457	addons.xpi-utils	DEBUG	Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
1500474242457	DeferredSave.extensions.json	DEBUG	Save changes
1500474242457	addons.xpi	DEBUG	Updating XPIState for {"id":"fxdriver@googlecode.com","syncGUID":"{71c4c3a4-ff1c-4e21-8826-baebadde01a4}","location":"app-profile","version":"3.4.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox WebDriver","description":"WebDriver implementation for Firefox","creator":"Simon Stewart","homepageURL":null},"visible":true,"active":false,"userDisabled":false,"appDisabled":true,"descriptor":"C:\\Users\\IT\\AppData\\Local\\Temp\\anonymous6190436837776176908webdriver-profile\\extensions\\fxdriver@googlecode.com","installDate":1500474239165,"updateDate":1500474239165,"applyBackgroundUpdates":1,"bootstrap":false,"skinnable":false,"size":3303362,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"48.0"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":null},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1500474242458	addons.xpi	DEBUG	Updating XPIState for {"id":"aushelper@mozilla.org","syncGUID":"{552e5f27-ffcf-4582-9c46-5cd502962049}","location":"app-system-defaults","version":"2.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Application Update Service Helper","description":"Sets value(s) in the update url based on custom checks.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\aushelper@mozilla.org.xpi","installDate":1498666862000,"updateDate":1498666862000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":8488,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0.1","maxVersion":"54.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1500474242458	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1500474242458	addons.xpi	DEBUG	Updating XPIState for {"id":"e10srollout@mozilla.org","syncGUID":"{e1be517a-9b2a-4ac4-825c-201ccc148dea}","location":"app-system-defaults","version":"1.50","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Multi-process staged rollout","description":"Staged rollout of Firefox multi-process feature.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\e10srollout@mozilla.org.xpi","installDate":1498666862000,"updateDate":1498666862000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":12519,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0.1","maxVersion":"54.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1500474242458	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1500474242459	addons.xpi	DEBUG	Updating XPIState for {"id":"firefox@getpocket.com","syncGUID":"{c78775ad-1960-46ae-b1ea-756e020d6435}","location":"app-system-defaults","version":"1.0.5","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Pocket","description":"When you find something you want to view later, put it in Pocket.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\firefox@getpocket.com.xpi","installDate":1498666863000,"updateDate":1498666863000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":913906,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0.1","maxVersion":"54.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1500474242459	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1500474242460	addons.xpi	DEBUG	Updating XPIState for {"id":"screenshots@mozilla.org","syncGUID":"{d11cf331-e991-4c76-8608-438d4d02f85f}","location":"app-system-defaults","version":"6.6.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox Screenshots","description":null,"creator":null,"homepageURL":"https://pageshot.net/"},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\screenshots@mozilla.org.xpi","installDate":1498666863000,"updateDate":1498666863000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":716271,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"51.0a1","maxVersion":"*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1500474242460	addons.xpi	DEBUG	getModTime: Recursive scan of screenshots@mozilla.org
1500474242461	addons.xpi	DEBUG	Updating XPIState for {"id":"webcompat@mozilla.org","syncGUID":"{509f591b-fc3d-4fb9-a0ab-91f978e52bdc}","location":"app-system-defaults","version":"1.1","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Web Compat","description":"Urgent post-release fixes for web compatibility.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\webcompat@mozilla.org.xpi","installDate":1498666862000,"updateDate":1498666862000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":9006,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0.1","maxVersion":"54.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1500474242461	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1500474242461	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"{413e40e9-68b5-4d31-b4e0-8106509c20c5}","location":"app-global","version":"54.0.1","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":"chrome://browser/content/default-theme-icon.svg","icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1498666862000,"updateDate":1498666862000,"applyBackgroundUpdates":1,"skinnable":true,"size":8207,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0.1","maxVersion":"54.0.1"}],"targetPlatforms":[],"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"userPermissions":null}
1500474242462	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1500474242465	DeferredSave.extensions.json	DEBUG	Save changes
1500474242465	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1500474242465	addons.xpi-utils	DEBUG	Updating add-on states
1500474242467	addons.xpi-utils	DEBUG	Writing add-ons list
1500474242471	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1500474242471	addons.xpi	DEBUG	Calling bootstrap method startup on aushelper@mozilla.org version 2.0
1500474242473	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1500474242475	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.50
1500474242475	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1500474242476	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1500474242478	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\screenshots@mozilla.org.xpi
1500474242478	addons.xpi	DEBUG	Calling bootstrap method startup on screenshots@mozilla.org version 6.6.0
1500474242479	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1500474242480	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.1
1500474242485	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1500474242485	addons.manager	DEBUG	Provider finished startup: XPIProvider
1500474242485	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1500474242485	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1500474242486	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1500474242486	addons.manager	DEBUG	Starting provider: GMPProvider
1500474242492	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1500474242493	addons.manager	DEBUG	Provider finished startup: GMPProvider
1500474242493	addons.manager	DEBUG	Starting provider: PluginProvider
1500474242494	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1500474242494	addons.manager	DEBUG	Provider finished startup: PluginProvider
1500474242495	addons.manager	DEBUG	Completed startup sequence
1500474245463	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1500474245464	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1500474245464	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1500474245814	DeferredSave.extensions.json	DEBUG	Write succeeded
1500474245814	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19
1500474245815	DeferredSave.extensions.json	DEBUG	Starting timer
1500474246111	DeferredSave.extensions.json	DEBUG	Starting write
1500474246201	addons.repository	DEBUG	No addons.json found.
1500474246202	DeferredSave.addons.json	DEBUG	Save changes
1500474246208	DeferredSave.addons.json	DEBUG	Starting timer
1500474246604	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1500474246604	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1500474246605	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1500474246612	DeferredSave.addons.json	DEBUG	Starting write
1500474246626	DeferredSave.extensions.json	DEBUG	Write succeeded
1500474246662	DeferredSave.addons.json	DEBUG	Write succeeded
Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DEEPU', ip: '192.168.0.104', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:108)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:104)
	at PG.PG.main(PG.java:12)
Caused by: java.lang.NullPointerException
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:192)
	at org.openqa.selenium.firefox.XpiDriverService.start(XpiDriverService.java:94)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:78)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	... 7 more

Can you please help you out in rectifying it?
