### ISSUE TITLE
change log says latest version as 3.5.0 but repo has 3.4.0 

### ISSUE THREAD

**Issue by vikramvi** [SeleniumHQ/selenium#4358]
https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG

Per this latest version is 3.5.0 but the github repo has version as 3.4.0

Please clarify which one is correct ?

**Comment by lmtierney** [comment]
Changelogs are updated prior to releases, that doesn't mean the releases happen the same day. The changelog was updated for the upcoming release which will be coming soon (TBD).

As this is a question rather than an issue. Please send future questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

**Comment by vikramvi** [comment]
@lmtierney thanks for clarification. I thought it was a bug thus opened new issue here.

I feel similar to other s/w releases, change log should be there just before release is done ? That's what most of the companies follow as well.

Any specific reason why selenium has different approach ?
