### ISSUE TITLE
How to use 1 Driver(Appium) instead of 2 Different Drivers(Appium and Web) for Android and Windows Automation ??

### ISSUE THREAD

**Issue by samnit** [SeleniumHQ/selenium#4382]
## Meta -
OS:  Windows 10
Selenium Version:  Selenium 3.4
Browser:  Multiple

I am working on a framework based on selenium.
We are creating and executing script of 
**Web , Android Web and Hybrid App** using selenium Grid

For Web , we are using the **RemoteWebDriver** to initialise the **webDriver** for all the browsers(Firefox,Chrome,IE) For which the code is  : -

**WebDriver driver = new RemoteWebDriver(sURL, cap);**

For Android Web and Hybrid App we are using **AndroidDirver** to initialise the **AppiumDriver**

**AppiumDriver driver = new AndroidDriver(sURL, oCap);**

Now to perform different validations for Windows Web , we are using WebDriver and to perform validations on Andorid web and Hybrid , We are using Appium Driver.

Now ,typecasting Android Driver to WebDriver is working fine. But when trying to typecast RemoteWebDriver to AppiumDriver it is throwing error : 
**org.openqa.selenium.remote.RemoteWebDriver cannot be cast to io.appium.java_client.AppiumDriver**

I want to now use only **one Driver preferably Appium driver** to run the scripts on both Platforms(Windows and Android). 
**Is there a way of how I can Use only one driver for all type of my Testcases as AppumDriver will give more and better options for automating the hybrid apps on Android ???**

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
