### ISSUE TITLE
ActionBuilder: Click at offset does not work

### ISSUE THREAD

**Issue by luke-hill** [SeleniumHQ/selenium#4407]
OS:  
Windows 7
Selenium Version:  
2.53.4 / 3.0.7 / 3.4.4 (Assumed to be global since 2 series)
Browser:  
Any Chrome / IE (Tested 2 chrome and 3 IE) *Likely to be a global bug*

## Expected Behavior -
Command should run (Notice the commented out command which *will* run)
Test script passes and driver quits
## Actual Behavior -
Command doesn't run, test script throws an error

## Steps to reproduce -
```
require 'selenium-webdriver'
@driver = Selenium::WebDriver.for :internet_explorer
@driver.get('https://the-internet.herokuapp.com/horizontal_slider')

el = @driver.find_element(:css, 'input')

sleep 0.5
@driver.action.move_to(el, 10, 0).click.perform #won't work
#sleep 0.5 #Uncomment this line to make script pass
#@driver.action.move_to(el).move_by(10, 0).click.perform #will work #Uncomment this line to make script pass

ans = @driver.find_element(:css, '#range').text
raise ArgumentError, 'Should not occur' if ans == '0'
@driver.quit
```

**Comment by lmtierney** [comment]
This is working as intended. For IE or Chrome (since they are not W3C compliant), when you perform a `move_to` without an offset, it puts the cursor in the middle of the element. When you perform a `move_to` with an offset, it puts the cursor with the offset relative to the top left corner of the element.

This changed with W3C, as offsets are calculated based on the center point. At least in Ruby though, the API is not changed and you should be specifying the offset from the top-left corner (the selenium code accounts for this).

With 

```
@driver.action.move_to(el, 10, 0).click.perform
```

Since the offset of 10 is so small, the slider stays at 0 (since we're giving it an offset from the left side of the slider.

With 

```
@driver.action.move_to(el).move_by(10, 0).click.perform
```

We're telling it to go to the center of the slider, then click 10 pixels to the right, which causes a number to be selected.

If you were to issue the `move_to` with offsets after doing the combined `move_to` and `move_by`, it would then put the slider back at 0 indicating that it is indeed working.


See the following links for more information:

API OSS:
http://seleniumhq.github.io/selenium/docs/api/rb/Selenium/WebDriver/ActionBuilder.html#move_to-instance_method

API W3C:
http://seleniumhq.github.io/selenium/docs/api/rb/Selenium/WebDriver/PointerActions.html#move_to-instance_method

JSON Wire Protocol:
https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidmoveto

W3C Spec:
https://w3c.github.io/webdriver/webdriver-spec.html#pointer-actions
