### ISSUE TITLE
The import org.openqa.selenium.remote.CapabilityType cannot be resolved

### ISSUE THREAD

**Issue by rageai** [SeleniumHQ/selenium#4429]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.4.0

I can't import  org.openqa.selenium.remote.CapabilityType
or org.openqa.selenium.remote.DesiredCapabilities

my maven dependencies are as follows
<dependency>  
    <groupId>org.seleniumhq.selenium</groupId>  
    <artifactId>selenium-java</artifactId>  
    <version>3.4.0</version>  
</dependency>  
<dependency>  
    <groupId>org.seleniumhq.selenium</groupId>  
    <artifactId>selenium-server</artifactId>  
    <version>3.4.0</version>  
</dependency> 

what am i doing wrong?

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
