### ISSUE TITLE
Got issue while running multiple tests

### ISSUE THREAD

**Issue by uthiravel** [SeleniumHQ/selenium#4434]
Selenium::WebDriver::Error::UnknownError Session [c8442eb0-814f-4554-8b98-5e276f29cc8b] not available and is not among the last 1000 terminated sessions. Active sessions are[ext. key 58abeb9f-e9a3-428a-ab7e-06b245686039, ext. key e4db674e-089e-43e5-b983-6d154448fa19, ext. key de77b4d5-0d2e-4035-a207-b0a5e870e2de, ext. key 583b4232-a854-4306-b227-dfad2eae4184, ext. key b727b46e-4c65-479d-b61e-cdfc0ffc97ab, ext. key 8fbb3041-a94c-47cd-97e9-843e02a1728d, 503ce5ab-7e13-

I am using the following environment 
Ruby - 2.1
Rails - 4.1
Seleinum web driver Gem- 2.48.1

Thanks

**Comment by lmtierney** [comment]
`2.48.1` is very old and would require you to use an older browser version.

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
