### ISSUE TITLE
Change logs to be more informative for synchronization releases

### ISSUE THREAD

**Issue by sasank1985** [SeleniumHQ/selenium#4474]
## Meta -
OS:  
Windows 10 
Selenium Version:  
3.4.0 Standalone server
Browser:  

 Not Browser Specific. Its related to Change Log Details of Selenium Standalone Server release

Browser Version:  

## Steps to reproduce -

Not Applicable
![selenium standalone server- change log](https://user-images.githubusercontent.com/22906393/29356836-35bc3de0-8293-11e7-9883-edc08df81ab2.jpg)

**Comment by jimevans** [comment]
Please read the top section of the IEDriverServer CHANGELOG for information about how version information works for that component. Oftentimes, there are no functional changes from an internal-only release to the release that is synchronized to the full release of the Selenium project. Updates to the release notes are appropriate to indicate that there are no further changes since the prior documented release. This behavior for the IE driver CHANGELOG will not be changing.
