### ISSUE TITLE
<select> atoms test fails in Safari

### ISSUE THREAD

**Issue by juangj** [SeleniumHQ/selenium#461]
javascript/atoms/test/select_test.html fails in Safari 7 and Safari 8. All of the failing tests appear to be because the 'change' event is not fired.

These tests fail:
testClickCanSelectOptionWhenDefaultPrevented
testClickCanToggleOptionsInAMultiSelect
testClickTogglesByTheTimeChangeEventFires
testTapCanSelectOptionWhenDefaultPrevented
testTapCanToggleOptionsInAMultiSelect
testTapTogglesByTheTimeChangeEventFires

The tests listed above are a superset of the tests for which select_test is already disabled in Chrome (see https://code.google.com/p/chromedriver/issues/detail?id=1073). I'll send a PR later to disable these tests in Safari as well.

**Comment by jleyba** [comment]
See also #385

**Comment by lukeis** [comment]
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.
