### ISSUE TITLE
How can I get the available driver from grid hub?

### ISSUE THREAD

**Issue by firmlybelieve** [SeleniumHQ/selenium#4647]
I want get android or ios DeviceName from Grid，Do you have an interface about get available driver?
thanks

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
