### ISSUE TITLE
selenium-server-xxx.zip and selenium-java-xxx.zip have no version info in META-INF/MANIFEST.MF

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium#4667]
Detected in version 3.5.3
selenium-server-xxx.zip and selenium-java-xxx.zip have no version info in META-INF/MANIFEST.MF

**Comment by shs96c** [comment]
We should be loading this from the manifest, but I suspect we overwrite that when we construct the zips.

**Comment by shs96c** [comment]
I need some fixes in upstream Buck first. Rather than land them on our fork, I've put forward these PRs:

https://github.com/facebook/buck/pull/1523
https://github.com/facebook/buck/pull/1524
https://github.com/facebook/buck/pull/1528
https://github.com/facebook/buck/pull/1529

With those in place, we can do all the magic we need to do in a `genrule`

**Comment by shs96c** [comment]
All those PRs are now landed. I need to bump our buck version next.

**Comment by shs96c** [comment]
Closed with 500f3e11f65a3f8f9882eabde005140eaf6b2263
