### ISSUE TITLE
Gauge Tags from my gauge gradle task is not being passed to beforespec

### ISSUE THREAD

**Issue by thivyae** [SeleniumHQ/selenium#4695]
Hey All,
I have an issue where tags from my gauge gradle task is not being passed to beforespec whereas the the tags are passed to spec files
Any idea what is the issue?

I'm in Gauge version: 0.9.1
Plugins
html-report (3.1.0)
java (0.6.2)

**gradle gauge task :**
task runTestsInQA(type: GaugeTask) {
doFirst {
println 'Running tests for the V1 in QA environment...'
gauge {
specsDir = 'specs'
tags = 'V1'
env = 'qa'
additionalFlags = '--verbose'
}
}
}
_
  @BeforeSpec(tags = "V1")
    public void beforeSpec(ExecutionContext context)
    {
        System.out.println("Tags in scenario "+context.getAllTags());
    }

Here, print statement is throwing null array [ ]

**Comment by lmtierney** [comment]
Does this have anything to do with selenium?

Regardless, this is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by thivyae** [comment]
Hey,
This doesnt have to do with selenium i suppose.Because the selenium layer doesnt come into picture in this issue.If there are issue,it should be with gauge and gauge gradle task as only these two are involved in this scenario.
I'm pretty sure that problem shouldnt be with gauge gradle task as tags are recognized i specs but not in beforesuite/beforespec.
So I assume beforesuite/beforespec is not taking in tags.
