### ISSUE TITLE
3.5.3 not current via nuget

### ISSUE THREAD

**Issue by PioterB** [SeleniumHQ/selenium#4719]
## Meta -
OS:  
n/a
Selenium Version:  
3.5.3
Browser:  
n/a

latest release (3.5.3) is not available via nuget. still version 3.5.2 is shown as current.

Browser Version:  
n/a

## Expected Behavior -
3.5.3 as nugets current

## Actual Behavior -
nuget serves 3.5.2 as latest

## Steps to reproduce -
go to https://www.nuget.org/packages/Selenium.WebDriver/

**Comment by jimevans** [comment]
3.5.2 is the latest version of the .NET bindings available. Any version differences in the third field of the version number (`z` of `x.y.z`) are specific to a given language binding, and does not imply that other languages will have a corresponding release. In other words, just because Java has released a 3.5.3 does not mean that .NET or Ruby or Python will have a 3.5.3.

**Comment by PioterB** [comment]
thx!
that makes sens
