### ISSUE TITLE
Python seleneum remote driver

### ISSUE THREAD

**Issue by Hanyuusha** [SeleniumHQ/selenium#4821]
## Meta -
OS:  Linux (possibly any)

Selenium Version:  python selenium 3.6.0, selenium standalone > 3.4

Browser:  Any

Browser Version:  

## Expected Behavior -
WebDriverException: Message: Unable to find command matching POST to //session

Then i use selenium standalone > 3.4 and last (3.6.0) python selenium, on any command i has this error.
Possibly fix, in remote/remote_connection.py delete all leading / on commands.

**Comment by lmtierney** [comment]
Sounds like you have an extra slash `/` at the end of your `command_executor` URL.

Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. Once this is done the issue will be re-opened. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by lmtierney** [comment]
For example, it should be:

```
WebDriver(command_executor='http://127.0.0.1:4444/wd/hub')
```

Not

```
WebDriver(command_executor='http://127.0.0.1:4444/wd/hub/')
```
