### ISSUE TITLE
CEF3 Windows app not starting! Please help

### ISSUE THREAD

**Issue by ifritz7** [SeleniumHQ/selenium#4850]
Hello,

I have tried for the last 2 days to get this to work with our CEF app. It is not working.
I am following this: https://bitbucket.org/chromiumembedded/cef/wiki/UsingChromeDriver.md

I get this error:
org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: crashed

We set the debug port on our app. when I open http://localhost:xxxx (our debug port) it works.

 I can't for the life of me figure out why I can't get this to connect!!!

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
