### ISSUE TITLE
Expectation don't handle multiple fitting elements with different display state

### ISSUE THREAD

**Issue by HenningL** [SeleniumHQ/selenium#4867]
## Meta -
OS:  
all
Selenium Version:  
latest
Browser:  
all

Call:
ExpectedConditions.visibilityOfElementLocated(getSelector()))

## Expected Behavior -
Element which fits the expectation is found
## Actual Behavior -
Only the first selector-found element is considered to fulfill visibility while there is a list of selector-found elements where one of them fulfill.
## Steps to reproduce -

Having a site where two(or more) elements are present found by xpath while the first is hidden and the second is visible, the expectation of the visibility of the element found is never fulfilled.

elementIfVisible(findElement(locator, driver)); 
while findElement(locator, driver) only returns the first which doesn't fulfill visibility.

Expected is, that the element which fulfill all criteria is found/considered.

**Comment by barancev** [comment]
ExpectedConditions class was designed to be a set of examples, not the compete set of all possible conditions. We're not going to expand this class too much, especially because Java 8 introduced new cool features, like lambdas and streams, that made writing conditions really easy. The condition you need can be implemented as a single line of code:
```
wait.until(d -> d.findElements(locator).stream().filter(WebElement::isDisplayed).findFirst().orElse(null))
```
