### ISSUE TITLE
unknown error : cannot find Chrome binary

### ISSUE THREAD

**Issue by raghavendravejendla** [SeleniumHQ/selenium#5001]
Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error
: cannot find Chrome binary
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d902
3f),platform=Windows NT 6.3.9600 x86_64) (WARNING: The server did not provide an
y stacktrace information)
Command duration or timeout: 58 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'SDCPIAPP168', ip: '172.21.26.119', os.name: 'Windows Server
2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_144'
Driver info: driver.version: ChromeDriver
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

**Comment by raghavendravejendla** [comment]
I am getting this exception in some systems. can you please let me know how to resolve the issue.

**Comment by lmtierney** [comment]
Chromedriver cannot find your installation of chrome webdriver

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
