### ISSUE TITLE
I am unable to locate any elements on any page in IE11 Windows 10 with IEDriver 

### ISSUE THREAD

**Issue by Kumar-tsk** [SeleniumHQ/selenium#5011]
## Meta -
OS:  Windows10 64 bit

Selenium Version: Selenium Webdriver 3.6  

Browser:   IE11

Browser Version:  

## Actual Behavior -
exception in thread "main" org.openqa.selenium.NoSuchElementException: Unable to find element
## Steps to reproduce -
Go to URL web page> enter windows authentication credentials using AutoIT and main page opens after that driver not identifying any elements (text box, button click etc..)
( I verified IE protected mode settings set correctly)

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
