### ISSUE TITLE
Selenium 3.7.1-Java-IEDriverServer 3.7.0 : IEDriverServer opens a new Window instead of new TAB when JavascriptExecutor is used.

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#5108]
## Meta - Selenium 3.7.1-IEDriverServer 3.7.0 : **`IEDriverServer`** opens a new **`Window`** instead of new **`TAB`** when **`JavascriptExecutor`** is used.

OS:  Windows 8. Pro

Selenium Version:  3.7.1

Client:    Java

Browser:  Internet Explorer

Browser Version:  10.0

## Steps to reproduce -
Minimum Code Block : 

	    String URL="http://www.google.com";
	    System.setProperty("webdriver.ie.driver", "C:\\Utility\\BrowserDrivers\\IEDriverServer.exe");
	    WebDriver driver =  new InternetExplorerDriver();
	    driver.get(URL);
	    System.out.println("Page Title is : "+driver.getTitle());
	    ((JavascriptExecutor) driver).executeScript("window.open('http://facebook.com/');");

**Comment by jimevans** [comment]
This is by design that a new window is opened.

**Comment by Debanjan-B** [comment]
@jimevans Can you please point me to some design/specs/documentation to know a bit of details on this?

**Comment by jimevans** [comment]
@Debanjan-B The operative documentation is the W3C WebDriver Specification, which states the use of a “top level browsing context,” and remains normatively silent on “tabs vs. windows,” leaving the behavior implementation-specific. Given that, it means the design is up to the implementor, in this case, myself. So, it’s by design because I created the design to be so, and I have seen no compelling argument to change the design other than some peoples’ sense of aesthetics.
