### ISSUE TITLE
Ability to take full page screenshot

### ISSUE THREAD

**Issue by prahladyeri** [SeleniumHQ/selenium#5114]
## Meta -
OS:  
Ubuntu 16.04 LTS
Selenium Version:  
3.7.0 (Python)
Browser:  
Firefox

This is a follow-up to bug #1141. Since the ability to take full page screen-shot hasn't been implemented yet, this bug deserves to have a second look. As the [last comment](https://github.com/seleniumhq/selenium/issues/1141#issuecomment-282997959) on the thread says, even if the spec doesn't allow the screen-shot beyond a viewpoint, why can't we have another method like `save_full_screenshot()` for taking the full screen-shot?

Browser Version:  

## Expected Behavior -
`save_screenshot()` should capture a full page screen-shot. Or alternatively, if the spec doesn't allow that, then additional method such as `save_full_screenshot()` be introduced that can be used.

## Actual Behavior -
`save_screenshot()` doesn't capture a full page screen-shot.

## Steps to reproduce -

    browser = webdriver.Firefox()
    url = "https://www.google.com"
    browser.get(url)
    browser.save_screenshot(sfname ) #this is where it fails

**Comment by cgoldberg** [comment]
> save_screenshot() should capture a full page screen-shot.
> Or alternatively, if the spec doesn't allow that, 

@prahladyeri ,
The W3C WebDriver spec clearly states screenshots are of "top-level browsing context’s viewport".

> why can't we have another method like save_full_screenshot()
> for taking the full screen-shot?

Every browser would have to support full page screenshots (they don't).  Also, every browser driver would then need to expose an API for taking the full page screenshots.  Since this underlying support is not available to Selenium, I don't see how it is technically possible to implement without relying on scrolling/stitching (which is a hack and brings its own set of issues and corner cases).

**Comment by prahladyeri** [comment]
@cgoldberg You made a good point. "Scroll and stitch" is the hackish method that most devs use these days to fix the problem of taking full screen-shot. I understand that every browser cannot implement or agree on a new API easily, but even if selenium provides such a method and does the scrolling and stitching internally, it will save lots of efforts for devs. Since they are the experts in the DOM stuff (just after the upstream browsers), they can most easily and seamlessly do this. After all, browser automation is the goal of selenium, isn't it?

**Comment by p0deje** [comment]
As Jim already [explained](https://github.com/SeleniumHQ/selenium/issues/1141#issuecomment-147691328):

> Hacks such as scrolling-and-stitching images together seem, on the surface, to be a way forward, but there are too many corner cases where something like that approach fails for a general purpose library like Selenium. A common example is the case of absolutely positioned elements, such as those that remain at the top or bottom of the view port as the user scrolls the page. This is a clear case where scrolling-and-stitching individual screenshots would fail.

This leaves Selenium with not being able to implement a method to retrieve screenshot of the full page. However, you can create an issue in https://github.com/w3c/webdriver so that maybe in future W3C specification defines such a command (maybe in future versions of specifications). After that, browser vendors would need to implement and properly support getting screenshots of the full page.
