### ISSUE TITLE
SafariDriver on Mac OSx adding some extra json values while sending app data to application server

### ISSUE THREAD

**Issue by svaze** [SeleniumHQ/selenium#515]
In our application, when we try to save a record, data is sent to server in json format.
But while running selenium webdriver scripts on Mac Safari, the record is not getting saved even if manually the same record gets saved in Mac Safari.

i.e. while sending data to the server in json format, some extra characters or json value might be getting sent to the server causing the record to fail to save. 

Is there any workaround or solution to this issue?

Application platform: MVC, .Net, Html5, restful web API
Automation framework: Webdriver 2.45.0, C# , Mac Safari.

The above scenario works fine in other browsers on Windows.

Many thanks in advance.

**Comment by jleyba** [comment]
"Might be getting sent"?  The SafariDriver doesn't mess with network traffic. Have you looked at the network tab in devtools for what is actually getting sent to your server?

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by daluu** [comment]
I wonder if this issue has some relation to a past one: 

https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/5503

How is the JSON data constructed? Safari is rather picky on JSON and silently fails if it doesn't like the formatting.

On a related note, did this issue ever get resolved, OP? Don't know if the OP ever posted to the Selenium user group or not.
