### ISSUE TITLE
Getting error as No matching capability sets found for IE Driver 3.7 in remote machine

### ISSUE THREAD

**Issue by Elakkiyaab** [SeleniumHQ/selenium#5150]
## Meta -
OS:  Windows 

Selenium Version:  3.7.0

Browser:  IE

Browser Version:  11.0.48

## Actual Behavior -
Caused by: org.openqa.selenium.SessionNotCreatedException: No matching capability sets found.
Unable to match capability set 0: platformName must be 'windows', but was 'win8'
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
Driver info: driver.version: unknown
remote stacktrace: 
## Steps to reproduce -
I have given platform name in config file as below
browserType=internet explorer
browserVersion=11
platform=WIN8
remoteWebDriverUrl=Grid URL

I have given capabilities in node as below
{
          "browserName": "internet explorer",
          "version": "11",
          "platform": "WIN8",
          "maxInstances": 10
		 }

**Comment by p0deje** [comment]
I'm not a Grid expert, but why can't you just use "Windows"?

**Comment by Elakkiyaab** [comment]
I am getting this issue after updating the driver from 3.4 to 3.7.
I have configured multiple Windows platform(win7,vista,win8,win10) in grid.I want to run the test in specific windows platform.so that I have given the specific platform name in node and config file

**Comment by jimevans** [comment]
This is an IE driver “issue.” The word is deliberately in scare quotes because as of 3.5 or later, the driver now implements the [W3C WebDriver Specification](https://w3c.github.io/webdriver/webdriver-spec.html#processing-capabilities), which indicates that drivers should reject unknown capability names. The capability `platform` is such an unknown name. Moreover, it’s likely that the grid hub is attempting to migrate the capability to `platformName`, which _is_ valid, but the driver only matches on the value of `windows`, again, as completely allows by the spec. Since the platform passed to the grid hub can be any of a number of arbitrary strings indicating Windows, there is no way for the driver to match on that. While I haven’t looked at the grid code, the way forward here is to have an extension capability which the grid understands for routing purposes to specific nodes, but which does not blindly map to `platformName`. If you specify `platform` to be your specific platform type and also specify `platformName` to be `windows`, that ought to be a workaround, but I’ve no earthly idea whether it will actually work.

**Comment by barancev** [comment]
Fixing this issue is in the (preliminary) plan for release 3.9

**Comment by Elakkiyaab** [comment]
@jimevans I wil try to implement as per your comment and post the status.Thanks
@barancev Thanks for the updates.It will be very helpful if the issue is fixed in upcoming versions

**Comment by Elakkiyaab** [comment]
@jimevans I have implemented the code as per your suggestion.It is working now.Thanks for the help

**Comment by demirmustafa** [comment]
same issue on 3.11.0

**Comment by Satish396** [comment]
@jimevans as per your suggestion, this one make sense.. i hope it will helpful for other learners.

System.setProperty("webdriver.internetexplorer.driver", "IEDriver.exe");
         InternetExplorerOptions options=new InternetExplorerOptions();
         DesiredCapabilities capability = DesiredCapabilities.internetExplorer();
         capability.setBrowserName("internet explorer");
         capability.setCapability("platformName", "WINDOWS");
         capability.setPlatform(Platform.LINUX);
