### ISSUE TITLE
Selenium 2.45 is not compatible with Firefox 37

### ISSUE THREAD

**Issue by lokeshksymantec** [SeleniumHQ/selenium#517]
Profile error is appearing.

**Comment by ddavison** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by ddavison** [comment]
additionally, the new selenium version has issues with firefox.

[read here](https://github.com/SeleniumHQ/selenium/blob/master/py/CHANGES#L2)
