### ISSUE TITLE
Documentation for preferred way to get HTTP status code

### ISSUE THREAD

**Issue by Uninen** [SeleniumHQ/selenium#5194]
I'm a bit surprised that there is no way to get HTTP status code information from WebDriver. I found several tickets asking for this and a lengthy discussion, but no actual documentation on the issue. I believe this is a very common use case and if not implemented, at least there should be documentation on how to do this.

Is there currently a preferred way of extracting status code from WebDriver or any best practises how to do it for different languages? Can I help in writing this somehow?

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
