### ISSUE TITLE
New Safari profile not created with Selenium WebdriverSafari

### ISSUE THREAD

**Issue by nigeltest** [SeleniumHQ/selenium#520]
Hi I have setup the Safari driver with Selenium WebDriver using Java and testng and noticed that details from previous tests are displayed in the current test. For example, in test A I search for 'France' on a home page.  When test B starts 'France is already displayed in the homepage.

I currently have chrome and firefox drivers setup. In the example above, when test B starts it doesn't display 'France' in the homepage as it's a new instance of the firefox profile is created with each new test. I this that this better for test independence.

Some thoughts:
- Do you think Safari will be changed to work in similar way to Firefox / Chrome. 
- Or does it not create a new profile for security reasons.
- Or should their be addition automation code added to remove cookies, (which may mean that 'France' is not displayed in the example above)

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by jleyba** [comment]
This is working as intended.

There's no such thing as a "profile" with Safari. If you want a clean session, you need to set `cleanSession` in the `safari.options` dictionary of your desired capabilities.

https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities#webdriver-2
