### ISSUE TITLE
NPM bump latest releases to npm

### ISSUE THREAD

**Issue by Fetz** [SeleniumHQ/selenium#5205]
In [npm selenium page](https://www.npmjs.com/package/selenium-webdriver) the latest version showing there is the: **3.6.0** but the latest version is [selenium-3.8.1](https://github.com/SeleniumHQ/selenium/releases).

Thanks

**Comment by jleyba** [comment]
3.6.0 is the final 3.x release for the npm package.

The next release will be 4.0 (and it'll be a [big one](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md#v400-dev)). Not sure when I'm going to push it though - I'll probably have to do an alpha release* since Simon has said he wants to get to 3.14 before jumping to be 4.0

**Comment by johnjbarton** [comment]
I wonder if you might reconsider the strategy for the npm releases? 

The 4.0-dev requires WC3 compliant browser drivers eg for actions. Neither chrome nor edge supports this API:

Chromedriver:
https://chromium.googlesource.com/chromium/src/+/master/docs/chromedriver_status.md

Edge progress:
https://docs.microsoft.com/en-us/microsoft-edge/webdriver

That means the 4.0 release would not be adopted until those drivers catch up, allowing 3.6 to get old and stale. Then when the huge 4.0 release drops, the barrier for upgrade will be very challenging.

Having more increments in 3.x or even better breaking the 4.x into more digestible chunks would be better for users in my opinion.

**Comment by jleyba** [comment]
I'm still working on the new actions API - this is being tracked in #4564. In a nutshell, internally we'll translate new action sequences to legacy commands for non-compliant browsers.

**Comment by jleyba** [comment]
`4.0.0-alpha.1` has been published to npm
