### ISSUE TITLE
Strongnamed issues with Selenium libraries

### ISSUE THREAD

**Issue by sebionofrei** [SeleniumHQ/selenium#5227]
Hello guys,

Since version 7, the strongmaned version of the library has issues in means that, when used, it complains that we have to actually include in the project the not-strongnamed version of the webdriver, thus creating an issue as you can't have both the unsigned and signed versions of the same library in the app.

Previous to version 3.7 (when the zip archive was containing the lib files, not the nuget packages) this thing was ok.

Can you guys fix the build?

Many thanks, in name of all the community :)

**Comment by jimevans** [comment]
The build is as it is supposed to be. Migrating to the `dotnet` build tools provided by Visual Studio required the project to move to distributing .nupkg packages in the archive instead of just the assemblies. If you need the raw assemblies, extract them from the .nupkg packages that are within the strong-named zip file. Remember that a .nupkg is nothing more than a ZIP archive with a different extension in the file name.

**Comment by sebionofrei** [comment]
I know that but that is not my issue.
Try yourself to install via nuget (or manually importing the packages) the strongnamed libraries, all 3 of them, and you will see what I tell.

I believe webdriver.backed.selenium requires webdriver (unsigned version), while you obviously install the webdriver signed version.
