### ISSUE TITLE
Python --Unable to start headless ChromeDriver with extension

### ISSUE THREAD

**Issue by marslan390** [SeleniumHQ/selenium#5233]
OS:  
macOS
Selenium Version:  
3.8.0
Browser:  
Chrome

I am facing an issue while using ChromeDriver headless with proxy auth extension. I am getting the following message:

from unknown error: page could not be found: chrome-extension://ioajcajbkdgdnpbejmmmppmdjeaebing/_generated_background_page.html
  (Driver info: chromedriver=2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e),platform=Mac OS X 10.12.6 x86_64)

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.

**Comment by marslan390** [comment]
I think it is an issue rather than a question

**Comment by p0deje** [comment]
Headless Chrome is actively used in the community, so chances are high this is your environment problem. I'd recommend searching for help at Google Group first and, unless you solve it, providing a  [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
