### ISSUE TITLE
Firefox driver on .NET (2.45.0) doesn't get instantiate

### ISSUE THREAD

**Issue by CyborTronik** [SeleniumHQ/selenium#526]
Tried to init new FirefoxDriver and got next exception(tested with FF 30, 35,36):

System.Collections.Generic.KeyNotFoundException was unhandled by user code
  HResult=-2146232969
  Message=The given key was not present in the dictionary.
  Source=mscorlib
  StackTrace:
       at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
       at OpenQA.Selenium.Firefox.FirefoxProfile.ReadDefaultPreferences()
       at OpenQA.Selenium.Firefox.FirefoxProfile..ctor(String profileDirectory, Boolean deleteSourceOnClean)
       at OpenQA.Selenium.Firefox.FirefoxProfile..ctor(String profileDirectory)
       at MailerFlow.Driver.createProfile(Proxy proxy) in

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by CyborTronik** [comment]
WTF, just install it and try to use, clean app no code at all

**Comment by jimevans** [comment]
@CyborTronik The problem you're describing is not universal. I am successfully able to instantiate the FirefoxDriver using 2.45.0 of the .NET bindings and multiple versions of Firefox, including 38 (latest release). The issue is not as simple as you insist, and will require further info from you in order to reproduce and eventually fix it.
