### ISSUE TITLE
Not able to launch internet explorer without menu bar,toolbar

### ISSUE THREAD

**Issue by SuhaThevar90** [SeleniumHQ/selenium#528]
Hi i am not able to launch internet explorer through selenium driver without menu bar and tool bar

**Comment by ddavison** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
