### ISSUE TITLE
How to get html of tabs/windows in background?

### ISSUE THREAD

**Issue by eldep** [SeleniumHQ/selenium#5284]
Hello
I need to retrieve html from several opened tabs at the same time.
I know how to open new tabs/windows, also used to try SwitchTo function, and it works, but as known, html gets only from active tab, whereas I need to have active tab in my view,, without going to nearby to only get html from there(nearby tabs or windows).
Is there a way to modify that function, or maybe another way, to make that possible?

Thanks in advance

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
