### ISSUE TITLE
Start selenium grid hub with https://

### ISSUE THREAD

**Issue by ketanb007** [SeleniumHQ/selenium#5287]
Is there a way to start selenium grid hub with https:// instead of http://

Does any one did it? or is it possible to achieve it?

Thanks!!

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
