### ISSUE TITLE
The import org.openqa.selenium.WebDriver cannot be resolved

### ISSUE THREAD

**Issue by vsnsbhanupriya** [SeleniumHQ/selenium#5294]
When I try selenium webdriver 3.80 version in eclipse I'm getting error in class.
Please assist me

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
