### ISSUE TITLE
WebDriver driver= new PhantomJSDriver();

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#5295]
## Meta - What happened with "PhantomJSDriver" ?

With **`Selenium-Java v3.8.1`** `WebDriver driver= new PhantomJSDriver();` doesn't resolves any more on IDE.

JavaDocs have dropped the reference of `PhantomJSDriver` from [**`Interface WebDriver`**](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WebDriver.html) page.

`Selenium-Java v3.8.1` [**CHANGELOG**](https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG) haven't spoken about  **`PhantomJSDriver`** for a while.

OS:  Windows8
Selenium Version:  3.8.1
Browser:  PhantomJSDriver

Browser Version:  2.1.1

## Steps to reproduce -
Minimal Code Block : 

	      File path=new File("C:\\Utility\\phantomjs-2.1.1-windows\\bin\\phantomjs.exe");
	      System.setProperty("phantomjs.binary.path",path.getAbsolutePath());
	      WebDriver driver= new PhantomJSDriver();
	      driver.manage().window().maximize();
	      driver.navigate().to("https://www.google.co.in/");

**Comment by cgoldberg** [comment]
PhantomJS is no longer maintained.  Support for it has been removed from Selenium since Chrome and Firefox now support headless mode.

not sure why that didn't make it to the changelogs.

**Comment by Debanjan-B** [comment]
Thanks @cgoldberg for the update.

But I still wonder why to drop the support for **PhantomJS** all of a sudden? 
In-case of Web Scrapping I feel **PhantomJS** still exhibits a better performance then Chrome/Firefox in headless mode.

At the level best we could have deprecated **PhantomJS** so users could have adjusted their framework dependencies till the actual removal.

@AutomatedTester @shs96c @lmtierney @jimevans  your take please?

**Comment by jimevans** [comment]
Given that the PhantomJS driver in Java was a third-party jar that was packaged in the standalone server as a convenience, you should be able to include the same jar as a dependency in your own project and get that functionality back. Moreover, since the Java PhantomJS driver was not maintained by the Selenium project, I’m not entirely sure how it could’ve been marked as deprecated before removal. Finally, this would only apply to the Java bindings, since the phantomJS driver in the other language bindings is part of the Selenium project. 

Disclaimer: This isn’t an “official” project position. You asked for my take, so I’m giving it. Now I’m going back to my holiday.

**Comment by barancev** [comment]
Updated changelog.

Selenium discontinued PhantomJS support for two reasons:
1) PhantomJS developers claimed its EOL and recommended to use headless Firefox or Chrome. As soon as headless support was explicitly added to Selenium API we decided to drop PhantomJS.
2) But much more important is the fact that PhantomJS driver, aka ghostdriver, is effectively abandoned since 2014, for more than 3 years by now. There is no movement to make it conformant to W3C WebDriver standard. So it's getting incompatible with Selenium as we are moving to W3C driven future.

As Jim noted, we can't mark this class deprecated because in Java binding it's a third-party library. We just dropped dependency on it in selenium-java Maven artifact and stopped packing it into selenium-server-standalone. But you can explicitly add dependency on PhantomJS driver to the classpath and use it. Just be aware about potential compatibility issues.

**Comment by Debanjan-B** [comment]
Thanks @jimevans you have cleared all our hesitations. Happy Holidays :)

Thanks @barancev the change in the **CHANGELOG** will help the zillions of Selenium Users.
