### ISSUE TITLE
NullReferenceException when using FirefoxDriver.Keyboard.SendKeys(Keys.Space)

### ISSUE THREAD

**Issue by darxis** [SeleniumHQ/selenium#5310]
## Meta -
OS:  Windows 10
Selenium Version:  3.8.0 C#
Browser:  Firefox
Browser Version:  57.0.4 (64-bit)

## Expected Behavior -
SendKeys should execute

## Actual Behavior -
```
NullReferenceException
   at OpenQA.Selenium.Remote.HttpCommandExecutor.HttpRequestInfo..ctor(Uri serverUri, Command commandToExecute, CommandInfo commandInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteKeyboard.SendKeys(String keySequence)
```

## Steps to reproduce -
```c#
WebDriver.Keyboard.SendKeys(Keys.Space);
```

See issue https://github.com/mozilla/geckodriver/issues/939

**Comment by jimevans** [comment]
I’m on holiday at the moment, but I want to set the expectation that this may not get fixed. Use of the Keyboard and Mouse properties has never been the recommended path for the .NET bindings. With the move to W3C Specification compliance, this is even more true.

**Comment by darxis** [comment]
@jimevans Ok, so how can I focus an input element without knowing its XPath location and focusing it just by using SendKeys(Keys.Tab) when focusing other input elements?

**Comment by whimboo** [comment]
You could issue the SendKeys command against the body or document element of the page. This should move the focus to the next element in the tab order.

**Comment by darxis** [comment]
It works, thank you so much @whimboo 👍

**Comment by yesinsky** [comment]
This issue is still actual. Null reference exception is being thrown on any WebDriver.Keyboard.SendKeys(...); action. Please reopen.

**Comment by jimevans** [comment]
@yesinsky As I mentioned in my earlier comment, you shouldn’t be using the `Keyboard` property at all. It’s unlikely that the issue, even if reopened, would be fixed.

**Comment by yesinsky** [comment]
Unfortunately, I have one uncommon use case (related to javascript realization on a specific page) which cannot use element.SendKeys(...) on a selected item instead of driver.Keyboard.SendKeys(...) (an input element remains empty after keys were sent, another element grabs the focus). It worked with the latest chromedriver via Keyboard. Can I somehow send those keys in another way? Or maybe you can kindly advice me the firefoxdriver version when it worked the last time?

**Comment by jimevans** [comment]
@yesinsky I’ve not actually looked at the code as I’ve been on holiday for the last two-plus weeks, and I’m only back looking at technical things today. Having said that, I’m sure it’s an oversight in the transition from the open-source dialect of the JSON Wire Protocol to the W3C Specificatoon dialect of the protocol. That would explain why it works for Chrome, but not Firefox or IE. The API of `Keyboerd` and `Mouse` properties was ill-conceived, and those properties should have been `internal` instead of `public`. No, I don’t have an alternative to recommend at the moment, and it’s likely to be another week (or longer) before I can spare the bandwidth to look at it in any more depth than I’ve provided here.
