### ISSUE TITLE
When passing both 'desiredCapabilities' and 'capabilities' in POST /session, prefer WD3 caps

### ISSUE THREAD

**Issue by teodesian** [SeleniumHQ/selenium#5315]
Summary:
===========
If a request, POST /session is made to the selenium server, and both WD3 and legacy capabilities are passed as the JSON POST parameter (looking, say like so):
`{ desiredCapabilities:{...},capabilities:{...} }`
It would be preferable to attempt to create a new WD3-style session rather than making a legacy selenese connection (current behavior). 

The benefit of this change:
================
* Bindings don't have to make an expensive attempt to find out whether WD3 session creation is supported (by failing), and can instead pass harmless extra data which would be ignored both by WD3 and legacy selenium 2.x servers, but allows straightforward connections to be established on the first attempt.

Background:
============
Maintainer of perl bindings to selenium, Selenium-Remote-Driver here.  I'm implementing a compatibility layer so we can seamlessly use WD3 (mostly) the same as legacy selenium/WD.  It occurred to me that since there's no obvious way to tell whether a server supports WD3 methods other than trying to make a new WD3 session, it would be nice to not have to make a request that could possibly fail to find out.

Otherwise, once a session can be established it's simple enough to figure out whether we are WD3, given /session should return a capabilities object along with the status (legacy selenium only provided status); the binding can then chug along using whichever methods the server supports.

Not sure if this belongs here or downstream in the browser drivers; please advise if I should shop this to the browser vendors instead.

**Comment by p0deje** [comment]
I'm not a server expert, but as far as I remember, W3C capabilities are preferred over JWP, so it should already work correctly. What problem do you face?

**Comment by teodesian** [comment]
I'm no expert in the selenium server either, I'm just reporting what I've been seeing with selenium server 3.8.1, which is the old style caps (denoted by the desiredCapabilities parameter) being preferred to WC3 (the 'capabilities' parameter) when both are passed simultaneously as parameters to POST /session.

None of this is a bug -- this is a feature request.  Basically it would be less requests (read: faster) to call /session as my first interaction with a server (rather than /status then /session with the 'right' params, supposing /status gives me enough information to decide to use WC3 params, or /session possibly twice to figure out what *is* supported).

**Comment by teodesian** [comment]
What the ruby binding you reference above is exactly what I'm doing.

However I'm observing it choose desiredCapabilities over capabilities.  If it makes any difference, I'm using geckodriver.

And yes, I'm inferring we have a WC3 session or not based on the 'capabilities' parameter being present in the response to /session (it is only present with WC3 webdriver).

So, my problem here would be that instead of preferring WC3, as you assert, it appears the driver does the opposite.

**Comment by p0deje** [comment]
Can you demonstrate how server prefers desired capabilities over W3C? Maybe
an example of New session payload or something like that?

**Comment by teodesian** [comment]
Ha! Seems to be doing the right thing today.  Either this was a heisenbug or I'm working too hard.

Thanks for putting up with my BS

**Comment by shs96c** [comment]
You need to send both the w3c and the JSON Wire Protocol dialects at the same time. Consider the case where you just send the w3c payload (`{"capabilities": {"browserName": "chrome"}}`). In this case, a w3c server should attempt to start a chrome session. However, a server that obeys the JSON Wire Protocol will see an empty payload, in which case, it's free to do whatever it wants. Converserly, sending just the JSON Wire Protcol payload (`{"desiredCapabilities": {"browserName": "firefox"}}`) will have create a firefox session in a server that understands the JSON Wire Protocol, but will cause a "no session created" error in a w3c compliant server (since that expects _at least_ `{"capabilities": {}}` to be set.

So, we have the expected, legal behaviour of the server side layed out.

For historical reasons, most bindings only accept a "desired capabilities" hash as the argument when creating a new driver instance. Converting the old-style payloads to legal W3C ones is a non-trivial exercise (for example, `{"firefox_profile": "sdfgh"}` is now `{"moz:firefoxOptions": {"profile": "sdfgh"}}`, but what happens if both are set? Also "`platform`" has become "`platformName'", but do the values match? Probably only at the OS family level, according to the [note in the spec](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-matching-capabilities))

Most local end bindings get this mapping wrong, but the user doesn't care _why_ their session isn't as they'd expected it to be, they just know _it's not right_. What to do? What, my friends, do we do?

The answer is to be generous about what we receive from the user and attempt to do what they want. Knowing that most local end bindings have at least a few problems converting the old format to the new format, the selenium server creates an ordered list of capabilities, putting the OSS ones at the front of the list to ensure maximum compatability.

So, that's why you're seeing the behvaiour you are. The _correct_ thing to do is either do the munging of capabilities in the local end binding, or just speak one dialect or the other. If you have a choice, the w3c protocol is going to be the one that's supported into the future, so it's best to choose that, but the selenium server will always understand both.
