### ISSUE TITLE
selenium opens browser but does not navigate to the URL

### ISSUE THREAD

**Issue by khanh-nguyen** [SeleniumHQ/selenium#534]
Can someone please tell me what is wrong with my code?
```
'use strict';

var webdriver = require('selenium-webdriver'),
      driver = new webdriver.Builder()
        		            .forBrowser('chrome')   // same with firefox
 					        .build(),
      tape = require('tape'),
      cotape = require('co-tape');

tape('check element', function(t) {
  t.test('tape with cotape', cotape(function*(t) {
      t.plan(1);

      yield driver.get('https://www.google.com');

      t.pass('Selenium can open a page.');
  }));
});
```
The browser is opened but hangs there without going to the url. 
Thanks,

**Comment by ddavison** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
