### ISSUE TITLE
How do you write short-hand syntax of By.js?

### ISSUE THREAD

**Issue by NakajimaTakuya** [SeleniumHQ/selenium#5352]
Shorthand syntax is provided for locator in Node Selenium-webdriver.

like `By.partialLinkText('hogehoge')` to `{partialLinkText: 'hogehoge'}`

How do you write short-hand syntax of `By.js`?

```js
By.js(el => el.closest('.foo'), driver.findElement({id: 'bar'}))
```

to

```js
{js: ????}
```

Please tell me how to do it.

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by NakajimaTakuya** [comment]
ok.
thanks.

**Comment by jleyba** [comment]
This was phrased as a question, but it's a legit issue with API documentation.

**Comment by diemol** [comment]
If this was an issue with docs but no one has chimed in over 2-3 years, I assume it was either solved or it was not needed. Closing.
