### ISSUE TITLE
WebDriver does not support testing LocalStorage functionality for html5 app for different url's

### ISSUE THREAD

**Issue by santosh-sahoo** [SeleniumHQ/selenium#537]
Steps to Reproduce:
Step 1- Opens a url (www.abc.com/html/?storeId=01) does some config changes in the UI.
Step 2- Then open a url (www.abc.com/html/?storeId=20) does some other changes in this UI.
Step 3- Load the url mentioned in step 1 and check that UI is loaded with data from previously loaded LocalStorage  data for storeId 01.

Actual Result:
Everytime url is loaded with default config.

Expected Result:
Everytime url should load with default config.

Solutions tried-
1- Setting webStorageEnabled capability in desired capability.
2- Also tried using org.openqa.selenium.html5.LocalStorage, but getting class cast exception while casting webdriver to localstorage.

I am using latest WebDriver version.

Please suggest.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
