### ISSUE TITLE
Documentation a little confusing in ThenableWebDriver

### ISSUE THREAD

**Issue by mercmobily** [SeleniumHQ/selenium#5372]
[The documentation states](https://github.com/SeleniumHQ/selenium/commit/b390490dc93fc77284c484dc06d6e5fcc28d0468#diff-7639464dba3d23cc9e20002f627f55d3R98):

     A thenable wrapper around a {@linkplain webdriver.IWebDriver IWebDriver}
     instance that allows commands to be issued directly instead of having to
     repeatedly call `then`:
   
        let driver = new Builder().build();
        driver.then(d => d.get(url));  // You can do this...
        driver.get(url);               // ...or this

This confused me: I am late to the Selenium (and promises) party, but... wasn't this the "normal" way of doing it?

        let driver = new Builder().build();
        driver.get(url);               // ...or this

And this being the "new" way using the resulting proxying `then`:

        let driver = new Builder().build();
        driver.then(d => d.get(url));  // You can do this...

...?
The current documentation seems to imply that the proxy "allows commands to be issued directly instead of having to repeatedly call `then`" -- but I am confused: isn't the `then` the piece of news here?

It's most likely me. But...

**Comment by jleyba** [comment]
The builder can't return a fully constructed driver because starting the session is an async operation - so `Builder.build()` returns a promise for a new webdriver:

```js
let driver = new Builder().build();
console.log(typeof driver.then)  // function
driver.then(d => d.get(url));
```

Personally, I try to do everything in async functions these days, so I just do:

```js
let driver = await new Builder().build();
driver.get(url);
```

If you don't want to (or can't) use async functions, the promise returned by `Builder.build()` implements the [`IWebDriver`](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/webdriver_exports_IWebDriver.html) interface, so you can issue commands against the return value and the API will take care of chaining the promise for you.

```js
let driver = new Builder().build();
driver.get(url);
```

I'll try to update the API docs to make this more clear

**Comment by mercmobily** [comment]
thanks
