### ISSUE TITLE
Sendkeys not working with Firefox 58.0.1

### ISSUE THREAD

**Issue by rleaplaza** [SeleniumHQ/selenium#5413]
I have a problem uploading an input file embebed in a label button.
My code to attach is:
String idDocumento=driver.findElement(By.id("btadjuntar")).getAttribute("for");
        System.out.println("Id documento: "+idDocumento);
        JavascriptExecutor executor=(JavascriptExecutor)driver;
        executor.executeScript("document.getElementById('"+idDocumento+"').style.display='yes';");
        System.out.println("Subiendo el archivo de la ruta: "+path);
        WebElement elem = driver.findElement(By.id(idDocumento));
        elem.sendKeys(path);
        retardo(5);
The test gives an error like this
Exception in thread "main" org.openqa.selenium.ElementNotInteractableException: Element <input id="archivo_92_1517349655653" class="form-control" name="archivo" type="file"> is not reachable by keyboard
The error is pointing to elem.sendKeys(path)
The method sendkeys is not working

FF Version: 58.0.1
Geckodriver 0.18.0
Selenium jar version 3.5.3

**Comment by maeriens** [comment]
According to the docs, [ElementNotInteractableException](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/ElementNotInteractableException.html) is  `Thrown to indicate that although an element is present on the DOM, it is not in a state that can be interacted with.`

This means that the `elem` you are trying to send keys to does exist in the DOM but cannot receive the keystrokes. I suspect that it is because you are setting `style.display` to `yes`, which is [not a valid `display` value](https://www.w3schools.com/cssref/pr_class_display.asp), so it remains hidden.

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.

For issues, please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by rleaplaza** [comment]
I could find a solution, changing the style displaying yes to block, I could display the dynamic input file, attach the document and change the style display to none so the input file hides.

**Comment by DevelopmentTempVika** [comment]
I have a similar problem, but I just can not figure out how to solve it.
Here is the part of the code that displays the listbox, I need to select and click on "Show by 12". I can not help at all with the code.
Here is the listbox structure:
<select class = "select__control" autocomplete = "off" tabindex = "- 1" aria-hidden = "true"> <option class = "select__option" value = "12"> Show by 12 </ option> <option class = "select__option" value = "48" selected = "selected"> Show by 48 </ option> </ select>

Please, please understand.
