### ISSUE TITLE
Selenium WebDriver API .NET Bindings - OpenQA.Selenium.NoSuchElementException

### ISSUE THREAD

**Issue by Legends** [SeleniumHQ/selenium#5424]
**Question:**

Is this the default behaviour, that if an element is not found using:
`driver.FindElementByCssSelector("li.myClassName");`

that an `OpenQA.Selenium.NoSuchElementException` is thrown?
I would expect null, if no element is found.

> no such element: Unable to locate element: {"method":"css selector","selector":"li.myClassName"}
>   (Session info: headless chrome=64.0.3282.119)
>   (Driver info: chromedriver=2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73),platform=Windows NT 10.0.16299 x86_64)

>    at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
>    at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
>    at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
>    at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByCssSelector(String cssSelector)

**Comment by cgoldberg** [comment]
> Is this the default behaviour, that if an element is not found using:
> driver.FindElementByCssSelector("li.myClassName");
> that an OpenQA.Selenium.NoSuchElementException is thrown?

yes.

https://github.com/SeleniumHQ/selenium/blob/master/dotnet/test/common/ElementFindingTest.cs#L579

**Comment by lmtierney** [comment]
As @cgoldberg said, yes this is the intended behavior. See:
https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidelement
and
https://w3c.github.io/webdriver/webdriver-spec.html#find-element

As this is a question rather than an issue, in the future please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by Legends** [comment]
But does it make sense to throw an exception?
For example:
You want to scrape products and want to test if a certain feature (HtmlElement) is supported by this product, i.e. `<p class="isWaterProof">blabla</p>` .
In this case I would like to get `null` back, otherwise I need to handle everytime expensive exceptions...
