### ISSUE TITLE
Getting image from memory cache

### ISSUE THREAD

**Issue by Longbowman** [SeleniumHQ/selenium#5426]
Hello 

My task is to get some images which is dynamically loaded,  decrypted on client side using javascript and placed in memory cache. Unfortunately I didn't find any documentation that will help me to get those pictures either from memory cache or browser. 

![dev-tools](https://user-images.githubusercontent.com/4450907/35702218-f90effd2-07b1-11e8-8fbc-88483154aa64.png)

I am using chromedriver and c# but can use other webdriver. 

Thanks for help

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
