### ISSUE TITLE
An alternative node API

### ISSUE THREAD

**Issue by mercmobily** [SeleniumHQ/selenium#5432]
Hi there,

I used every spare minute I could find (and more) and came up with an alternative, much simplified [Node API for webdrivers](https://mercmobily.github.io/best-webdriver/). It's also very [documented](https://mercmobily.github.io/best-webdriver/index.html).

I haven't yet tested it on Safari and Edge (I don't have Windows or Mac). However, Chrome and Firefox seem to work fine.

I think this module's main advantage is that it was written from scratch, by somebody (me) who only ever saw the official W3C specs; I was also determined to always find the easiest possible solution to problems.

So...

* If there is anything from my code you might possibly want to use (I am thinking mayne the waitfor()` bit), feel free to help yourself. I will be happy to transfer copyright to you

* If you think this is good enough to have a chance to be a good API to cover JUST the W3C protocol, then please let me know. I would be happy to transfer it to you, and keep maintaining it

* Or, if you think you will stick with your existing module, but like this one too, maybe add a link to your site... which would be awesome.

@jleyba It would mean a lot to me if you had a look at the code and let me know what you think. If you don't have time, I will totally understand though!

Thank you,

Merc.

**Comment by jleyba** [comment]
The `waitFor()` construct is interesting, but there's an equivalent in `selenium-webdriver`:

```js
// best-webdriver
driver.waitFor(5000).findElementCss('[name=q]');

// selenium-webdriver
driver.wait(until.elementLocated(By.css('[name=q]')), 5000);
```

I'd like to know what it is you don't like about `selenium-webdriver` that led to writing your own API?  I know the [API documentation](http://seleniumhq.github.io/selenium/docs/api/javascript/) still needs TLC, especially with helping new users get started. I'm hoping to address this before the final `4.0.0` release.

As for an API that covers "just the W3C protocol", I'm not sure I understand what you want to accomplish. I'd hope users would never have to read the W3C spec and could just deal with the provided API. I've been working on the Selenium project for ~8 years and I still find parts of the spec hard to read (actions...) I don't think users should ever need to know/worry about the raw HTTP commands generated by the API

**Comment by mercmobily** [comment]
Hi,

> The waitFor() construct is interesting, but there's an equivalent in selenium-webdriver:

    // selenium-webdriver
    driver.wait(until.elementLocated(By.css('[name=q]')), 5000);

The main difference is that while with the selenium-webdriver you have specific calls, with my implementation of `waitFor()` I can poll *any* one of the existing API calls, without writing/using specific utility functions. 

> I'd like to know what it is you don't like about selenium-webdriver that led to writing your own API? I know the API documentation still needs TLC, especially with helping new users get started. I'm hoping to address this before the final 4.0.0 release.

I think the existing code is great in that it puts a rather thick layer around the webdriver standard. However, I feel that the design goes a little overboard: too many classes, no way to poll generic methods, the use of forward-proxies to make chaining work, etc.
My main point was: can I approach such a complex problem with the attitude "What's the simplest possible way to achieve this?"

> As for an API that covers "just the W3C protocol", I'm not sure I understand what you want to accomplish. I'd hope users would never have to read the W3C spec and could just deal with the provided API. 

I agree. However, at the same time, the thinner the API, the easier it is to debug things and -- generally speaking -- really understand what's going on.
I am not trying to say that people should make GET calls. But, I think that in implementing a protocol, an API should mirror the calls to the existing protocol whenever possible.
This is why in best-webdriver I have named _precisely_ after the W3C webdriver call.

> I've been working on the Selenium project for ~8 years and I still find parts of the spec hard to read (actions...) I don't think users should ever need to know/worry about the raw HTTP commands generated by the API

The way I dealt with actions is also something I simplified as much as possible, compared to the Selenium API.
This code shows you how I did it:

    var Keyboard = Actions.Keyboard
    var Pointer = Actions.Pointer
    var actions = new Actions(new Pointer('cucumber'), new Keyboard('hammer')
    actions
    .tick.hammerDown('r').cucumberDown()
    .tick.hammerUp('r').cucumberUp()


(Most of the time, people will just do `var actions = new Actions()` which will default to `keyboard` and `mouse`.)

Also, remember that:

    actions.tick.hammerDown('r').hammerDown()

Will result in an error, because `hammer` can only specify one action per tick.

As you can see, people are still shielded from the API. However, some API characteristics (one action per tick per device, for example) is fully portrait in the API itself.

Maybe I am the only one who feels that the current API is a little bit too complex, and it could be vastly simplified. It would have been impossible to submit PRs for the existing APIs, because -- as you can see -- the approach is totally different.

**Comment by jleyba** [comment]
> The main difference is that while with the selenium-webdriver you have specific calls, with my implementation of waitFor() I can poll any one of the existing API calls, without writing/using specific utility functions.

What does it mean to "poll" any of the existing API calls? How do you know which errors to ignore and try again and which should be surfaced to the user? `WebDriver.wait()` gives users that control (plus the ability to define a "wait" around a sequence of commands instead of a single API call). A set of common conditions are provided in the [`selenium-webdriver/lib/until`](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/until.html) module.

> I think the existing code is great in that it puts a rather thick layer around the webdriver standard. 

Thick layer around the standard? Your API is almost identical. There's only a handful of notable differences I see:

-  It's a bit flatter (`driver.back()` vs. `driver.navigate().back()`). `selenium-webdriver`'s core API was (intentionally) mirrored after Java, but I agree in these cases it should be a bit flatter.
-  Different approach to waits (see previous comments)
-  Explicitly enumerated find functions (`findElementCss()` vs. `findElement(By.css())`)
-  Different approach to configuring new sessions

> However, I feel that the design goes a little overboard: too many classes....

Most users should only need to interact with what's exported directly by [`selenium-webdriver`](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/index.html) (and some of that probably doesn't need to be exposed at the top level either).

> ...the use of forward-proxies to make chaining work

There's only a handful used and they simplified things a lot before async/await. The API works just fine if you always await function results.

> This code shows you how I did it:
>
> ```
> var Keyboard = Actions.Keyboard
> var Pointer = Actions.Pointer
> var actions = new Actions(new Pointer('cucumber'), new Keyboard('hammer')
> actions
> .tick.hammerDown('r').cucumberDown()
> .tick.hammerUp('r').cucumberUp()
> ```

Using the `tick` property for fine-grained control over the actions in a tick is an good idea. Not a fan of dynamically generating the API based on device IDs, though. 

> Maybe I am the only one who feels that the current API is a little bit too complex, and it could be vastly simplified. It would have been impossible to submit PRs for the existing APIs, because -- as you can see -- the approach is totally different.

I find your assertion that the API is too complex a bit of a stretch, given yours is _extremely_ similar (and you haven't actually provided any concrete examples of parts that are overly complicated. Of course, I say this with respect to `4.0.0-alpha.1`. The promise manager used in previous versions added a ton of complexity (and now that I've remembered it, perhaps this is what you were referring to with forward-proxies?)

**Comment by mercmobily** [comment]
Look, all good. I didn't mean this to be a thread that would waste your time. If you don't think it's a step forward, then it probably isn't.

If it ever works as inspiration to simplify your existing API, then great. In any case, my implementation will get some users who prefer it.

Thanks for listening!

**Comment by mercmobily** [comment]
Just my closing thoughts on this issue...
I think the current API has some problems:

* could do with ample flattening and simplifying (in pretty much every aspect: straight methods, actions, and polling);
* it doesn't follow the w3c specs when it could (e.g. passing `w3c: true` to Chrome, etc.) -- it still uses `desiredCapabilities` for example
* It has the forward-proxy elements (`WebElementPromise`) which add more complexity for the sake of chaining

I offered a greenfield implementation that addresses all of the issues that I see as problems. I documented it, tested it, linted everything.

I think the Selenium userbase would benefit from a cleaner, simpler API. I offered the API to the Selenium project, and offered to keep maintaining it giving up any rights etc.

**If you don't want it, all good.**. The offer stands.

Thanks again for listening!
