### ISSUE TITLE
Grid hub recommended OS

### ISSUE THREAD

**Issue by YogiBear52** [SeleniumHQ/selenium#5449]
OS:  
Windows Server 2016/Ubuntu 16.04

Selenium Version:  
3.8.1

Browser:  
Chrome

The grid hub is able to run on every platform which is supported by java. 
Is there a recommended OS for running the hub? What is the best practice?
I have two option, Windows Server 2016 or Ubuntu 16.04. Does it matter?

Thanks

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
