### ISSUE TITLE
How do you enable Selenium webdriver for wkwebview on MacOS?

### ISSUE THREAD

**Issue by atishay** [SeleniumHQ/selenium#5474]
## Meta -
OS:  OSX
Selenium Version:  General
Browser:  WkWebview

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
