### ISSUE TITLE
until.elementIsNotLocated

### ISSUE THREAD

**Issue by AlexLibs** [SeleniumHQ/selenium#5476]
In my automation I have to wait until.elementIsNotLocated. In my case I should wait while the loader spinner is presented. I would like to have this additional method. The implementation is really easy, quite similar to ```until.elementIsLocated``` (and it works just fine):

In selenium-webdriver/lib/until.js

```
/**
 * Creates a condition that will loop until an element is
 * {@link ./webdriver.WebDriver#findElement found} with the given locator.
 *
 * @param {!(By|Function)} locator The locator to use.
 */
exports.elementIsNotLocated = function elementIsNotLocated(locator) {
  locator = by.checkedLocator(locator);
  let locatorStr =
      typeof locator === 'function' ? 'by function()' : locator + '';
  return new Condition('for element not to be located ' + locatorStr,
      function(driver) {
        return driver.findElements(locator).then(function(elements) {
          return elements.length == 0;
        });
      });
};
```

**Comment by jleyba** [comment]
You can already do this with the existing API.

If the spinner will be removed from the DOM when done:

```js
let spinner = await driver.wait(until.elementLocated(locator));
await driver.wait(until.stalenessOf(spinner));
```

If the spinner will be hidden from view, but left in the DOM:

```js
await driver.wait(until.elementIsNotVisible(spinner));
```

You can also define your own condition if you really want to wait for `findElements()` to return an empty list:

```js
await driver.wait(async function(driver) {
  let found = await driver.findElements(locator);
  return found.length === 0;
});
```

**Comment by CodingToBeWithHer** [comment]
@jleyba
Unfortunately there is a problem when using your solution with stalenessOf
- I have tried this a couple of times and in my case there is DOM element with class 'loader' that I need to not be present on the page. 
The problem is that the line of code:

`let spinner = await driver.wait(until.elementLocated(locator));`

gets sometimes executed when the 'loader' element already disappeared and so this line leads to error.
I would say if we had potential method: 
`until.elementIsNotLocated`

the behaviour would be that if the element is not in the DOM carry on execution, if the element is in the dome try to wait XX seconds for it to disappear.

Could you comment if there is any way to have behaviour:
1. If element is not on the page, carry on
2.If the element is on the page wait XX seconds for it to disappear and then carry on
?

Because the given solution with stalenessOf fails in case 1
