### ISSUE TITLE
How to execute a script before page loaded?

### ISSUE THREAD

**Issue by NuclearGear** [SeleniumHQ/selenium#5509]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.9
Browser:  
Chrome

Hi ,
I want to execute scripts before page loaded by ChromeDriver. Could the selenium have any function like [the Page.onInitialized of PhantomJS](https://github.com/SeleniumHQ/selenium/pull/2331)? 
Thanks

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
