### ISSUE TITLE
Recommended way to use expected conditions on a chained locator

### ISSUE THREAD

**Issue by Drew-Ack** [SeleniumHQ/selenium#5515]
I like using a combination of WebDriverWaits and Expected Conditions to find elements on a page because of varying loading times. 

I have a problem using expected conditions when I need to use a series of By's and Locating strings to find an element.

`driver.find_element_by_link_text("link").find_element_by_tag_name("a")` is an example of the chaining. 

As i understand an Expected Condition take a tuple of (By, Locator), and does not handle a list or tuples in tuples. 

What is the recommended solution to use Expected Conditions with the above example? 
Should i create my own function for this?

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
