### ISSUE TITLE
Unable to create new service: ChromeDriverService - Driver info: driver.version: unknown (InsecureCertificate)

### ISSUE THREAD

**Issue by ayasha88** [SeleniumHQ/selenium#5547]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.9.1
Browser:  
Chrome

## Expected Behavior -
get IWebDriver of already opened Chrome browser

## Actual Behavior -
Exception

## Steps to reproduce -
hub: java -jar selenium-server-standalone-3.9.1.jar -role hub -port 4445
node: java -jar selenium-server-standalone-3.9.1.jar -role node -hub http://localhost:4445/grid/register

![image](https://user-images.githubusercontent.com/7511228/36772540-017f1982-1c56-11e8-872f-7b13977c9197.png)

![image](https://user-images.githubusercontent.com/7511228/36772604-285b27bc-1c56-11e8-8712-e74acfd97f7e.png)

In Visual Studio I have:

IWebDriver driver = new RemoteWebDriver(new System.Uri("http://localhost:4445/wd/hub"), new ChromeOptions());

but I get the following Exception:

Unable to create new service: ChromeDriverService
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:28.403Z'
System info: host: 'V121081', ip: '10.138.121.81', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_66'
Driver info: driver.version: unknown (InsecureCertificate)

I have also tried with FirefoxOptions, but same result:

Unable to create new service: GeckoDriverService
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:28.403Z'
System info: host: 'V121081', ip: '10.138.121.81', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_66'
Driver info: driver.version: unknown (InsecureCertificate)

what did I do wrong?

Thanks a lot.

**Comment by mcopjan** [comment]
@barancev We faced the same problem in our case it was caused by manipulating with our . csproj file where tags as Import Project and Target Name were removed

<Import Project="..\packages\Selenium.WebDriver.ChromeDriver.2.35.0\build\Selenium.WebDriver.ChromeDriver.targets" Condition="Exists('..\packages\Selenium.WebDriver.ChromeDriver.2.35.0\build\Selenium.WebDriver.ChromeDriver.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\Selenium.WebDriver.ChromeDriver.2.35.0\build\Selenium.WebDriver.ChromeDriver.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Selenium.WebDriver.ChromeDriver.2.35.0\build\Selenium.WebDriver.ChromeDriver.targets'))" />
  </Target>

Try to re-install chromedriver from nuget

**Comment by jimevans** [comment]
There are two things wrong with this issue report. First, the reporter states that the expected behavior is to “get IWebDriver of already opened Chrome browser.” This is unsupported by WebDriver in general.

Second is that the node does not have any indication where to find the chromedriver (or geckodriver for Firefox) executable. This needs to be set either by having the executables on the node’s PATH, or by explicitly setting system properties on the node’s command line.

**Comment by szarlatan** [comment]
@jimevans obviously you're right about the latest version, my mistake. Will check if 3.12 helps.
Also will double check if the problem is known on WebDriver.io GitHub.

Get well soon!

Cheers,
K.

**Comment by swapniljadhav111** [comment]
@szarlatan  I am facing same issue. Would you able guide me, how you resolved the issue.

Configuration:-
OS - WIN10
Chrome Browser Version:- v66
ChromeDriver- 32 bit
selenium standalone server - 3.12.0

Error:- Caused by: org.openqa.selenium.SessionNotCreatedException: Unable to create new service: ChromeDriverService

I tried degrading selenium server to 3.8.1 but still getting same error. 

`
System.setProperty("webdriver.chrome.driver", "D://SeleniumSoftwaresReq//chromedriver.exe");
			String hubURL ="http://localhost:4444/wd/hub";
			DesiredCapabilities capabilites = new DesiredCapabilities();
			capabilites.setBrowserName("chrome");
			capabilites.setPlatform(Platform.WIN10);
			ChromeOptions options = new ChromeOptions();
			options.setAcceptInsecureCerts(true);
			options.setUnhandledPromptBehaviour(UnexpectedAlertBehaviour.ACCEPT);
			options.merge(capabilites);			
			RemoteWebDriver driver = new RemoteWebDriver(new URL(hubURL), options);
driver.get("https://www.google.com")
`

**Comment by szarlatan** [comment]
@swapniljadhav111 
Might be that your system property is defined wrong - I believe it should be

```
System.setProperty('WebDriver.chrome.driver', 'D:\\SeleniumSoftwaresReq\\chromedriver.exe');
```

That should help. If not, you can always try to add chromedirver's location to system PATH, and then skip setting the property from the code (I did it that way).

**Comment by barancev** [comment]
Sorry for not triaging this issue in time, but this is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
