### ISSUE TITLE
unable to call driver value in Selenium web Driver 2.45 version 

### ISSUE THREAD

**Issue by Praveencnp** [SeleniumHQ/selenium#555]
Hi Team,
After implement all the web driver  jar file in project selenium web driver is function unable to call.

**Comment by tarlabs** [comment]
@Praveencnp , Please read the issue as a third person and see if you can make any sense out of that. Please first provide a concise way to reproduce the issue. Please provide information about the environment and bindings.

Also if you don't have a reproducible test case then post it on the Selenium Users google group

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
