### ISSUE TITLE
Testing Payment Request Api

### ISSUE THREAD

**Issue by petvas** [SeleniumHQ/selenium#5556]
Link:
https://paymentrequest.show/demo/

Is it possible to test user interaction with this api?

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by ruby186** [comment]
@petvas , maybe we cannot pay the order by native webdriver api.

creditcard management function is provide by browsers builtin function and may possible not to trigger it by webdriver apis. you can do it by 3rd way, for example, send TAB, Enter by native event, or sikuli operation by screen regions.

Adblock and other scenarios also cannot trigger by webdriver apis. The may outside of webdriver spec support. maybe this can help you, good luck, guys.

**Comment by ryancwalsh** [comment]
I still see no answers to this post: https://groups.google.com/forum/#!searchin/selenium-users/$20Payment$20Request$20API%7Csort:date/selenium-users/Cw7Yji-7HxM/OV7OjVkKBAAJ

Or to this post here: https://stackoverflow.com/questions/50070977/how-to-test-browser-functionality-of-popups-using-chromedriver-such-as-for-paym

**Testing is so important, and I'm really surprised that I've been unable to find an example of how to test usage of the Payment Request API.**

**Comment by cgoldberg** [comment]
@ryancwalsh this is the tracker for selenium issues, not general questions
