### ISSUE TITLE
java selenium getting all links of a content changing div

### ISSUE THREAD

**Issue by furk4no** [SeleniumHQ/selenium#5595]
Hello guys..

I have a problem with getting all links of a website.

There is a div, that contains divs, each of them are containing three links. (so one div is one row that is being loaded.)

The more you scroll the page the div content is changing (padding top and bottom).

So if you scroll a bit, a part of the links in the div container are getting changed. The max amount of links I can get out of the div is 54.

I couldn't find a way to show all links. I would like to get more than 54 links in my List. I'm struggling hard with this..

My question is: Is there a way to just jump to the next element that is being found with xpath? Or do I have to 'find' all elements and add to a List I will be doing actions with?

The simple xpath I'm using on this:

  By.xpath(".//a[starts-with(@href, '/p/')]");  

The inline css rule of the div:

element {
   padding-bottom: 3251px;
   padding-top: 2889px;
}

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
