### ISSUE TITLE
Unable to Turn off the pop up blocker By setting the Capabilities for IE 11

### ISSUE THREAD

**Issue by MuppuBala** [SeleniumHQ/selenium#5612]
Hi,

My requirement is to turn off the popup blocker in IE11 to open my application.

I have tried below options.But none of this working.
 DesiredCapabilities ieCapabilities =new DesiredCapabilities();            
                ieCapabilities.setCapability("disable-popup-blocking", true);
or
               ieCapabilities.setCapability("unexpectedAlertBehaviour","accept");
or 
               ieCapabilities.setCapability("browserstack.ie.enablePopups","accept");
Any help on this.

Thanks in Advance.

**Comment by jimevans** [comment]
Since the IE driver cannot isolate global settings (like the popup blocker being on or off) to a single session, it does not attempt to do so via capabilities. One of the driver's main tenets is that it does not make permanent changes to the browser settings. Firefox and Chrome have the ability to use a new user profile for every session; IE does not allow that. You will need to manually set the browser setting to the value you want on the target machine.
