### ISSUE TITLE
npm installing the latest version installs the alpha 4.x and not the stable 3.x

### ISSUE THREAD

**Issue by giltayar** [SeleniumHQ/selenium#5617]
Currently in this npm package, if a developer just does `npm install selenium-webdriver` they will get the 4.x.x-alpha version, which is somewhat unstable. They will get the 4 version because that version is tagged as "latest" in npm (try `npm view selenium-webdriver dist-tags` to see this). 

I believe that until 4 is out of beta, the latest 3.x.x should be tagged as "latest", while the 4.x.x should be tagged as "beta".

I've been bitten at least three times by this problem, and it takes a while to figure out the problem. Moreover, many of our customers have been having problems because of this issue, so this is not just a theoretical issue.

**Comment by jleyba** [comment]
We use semver b/c that's what npm uses, but it's not an accurate representation of the stability of each `selenium-webdriver` release. Every release pushed to npm is considered the latest stable supported release that users should consume.

Given that we're using semver for npm releases, there are some significant API changes that wouldn't be appropriate to push as a 3.x release. Since the rest of the Selenium project isn't ready for 4.0, I pushed it with the alpha tag.

**Comment by giltayar** [comment]
So, is 4 stable? If it is, why does it have an `alpha` tag?

I'm not sure what this has to do with semver. npm enables you to tag the "latest" version as something else than the last version published. This is exactly to enable beta versions that you don't want people to use until they stop being beta: so that `npm install _something_` should always bring the _stable_ version.

Currently, our customers are `npm install`-ing alpha versions of selenium webdriver (as I said, they are named as such: `4.0.0-alpha`!) by mistake due to their (and everybody else's assumption, including mine), that 

All you need to do is to npm-tag `3.6.0` as the `latest` version, until 4 is stable, at which point it's back to business as usual. This way, you can continue pushing versions of 4-alpha as much as you want, without impacting users that are installing `selenium-webdriver` for the first time.
