### ISSUE TITLE
c# querying Dom elements is very slow on dotnet core 2.

### ISSUE THREAD

**Issue by nikheelr** [SeleniumHQ/selenium#5676]
## Meta -
OS:  WIndows 10

Selenium Version:  3.11.0

Browser:  Chrome

Browser Version:  62.0.3202.94 

## Expected Behavior -
It should not take a long time to find Dom elements on the web page.
## Actual Behavior -
It takes about 3 seconds to find a Dom element on the web page. 

## Steps to reproduce -

```
var options = new ChromeOptions();
options.AddArguments("disable-infobars");

private ChromeDriver _webDriver;
_webDriver = new ChromeDriver(options);

var element = _webDriver.FindElementById("btnLogin"); 
```

**Comment by jimevans** [comment]
This is a [known issue](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/CHANGELOG#L142) with the .NET bindings on .NET Core. It’s due to a [bug in .NET Core’s networking stack](https://github.com/dotnet/corefx/issues/24104), and there’s not much the .NET bindings can do in their own without resorting to doing DNS resolution itself, which is likely to be error-prone, inefficient, and difficult to maintain.

**Comment by nikheelr** [comment]
@jimevans My apologies i should have mentioned this in the description. I am not using localHost i am using the ip ("http://127.0.0.1") and i also tried the IP Address of my PC and that also did not make a difference. I believe this is a different issue. I also tried this on mac and windows 10

**Comment by jimevans** [comment]
Can you then please supply an exact source code example that demonstrates the issue, while using the IP address (even the IPv4 loopback) directly? Your example in the issue report does not do so, and will use `localhost` for resolution.
