### ISSUE TITLE
PhantomJS Webdriver Race Condition in Port Selection

### ISSUE THREAD

**Issue by rvazarkar** [SeleniumHQ/selenium#569]
When using the phantomjs webdriver, it appears that there is a race condition when providing port=0. Selenium uses a socket bind on localhost to choose a free port, and then provides this port to ghostdriver. If a port is already in use when ghostdriver initializes, you receive the following error (uncaught excepting in Ghostdriver, so causes a zombie process):

```
[ERROR - 2015-05-23T15:07:26.410Z] GhostDriver - main.fail - {"line":85,"sourceURL":":/ghostdriver/main.js","stack":"\tat global code (:/ghostdriver/main.js:85:56)"}

  :262 in error
```

You can reproduce this fairly simply by initializing 2 phantomjs instances with the same port.

The issue occurs frequently when using multiprocessing. 

```
#!/usr/bin/env python

from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from multiprocessing import Manager
from multiprocessing import Pool
import time


def worker(url):
    service_args = []
    capabilities = DesiredCapabilities.PHANTOMJS
    capabilities['phantomjs.page.settings.resourceTimeout'] = 7000
    capabilities['phantomjs.page.settings.userName'] = 'none'
    capabilities['phantomjs.page.settings.password'] = 'none'
    service_args.append('--ignore-ssl-errors=true')
    service_args.append('--web-security=no')
    service_args.append('--ssl-protocol=any')

    driver = webdriver.PhantomJS(
            desired_capabilities=capabilities, service_args=service_args, executable_path='/root/phantom')
    driver.get(url)
    driver.quit()

if __name__ == '__main__':
    p = Pool(10)
    threads = []
    with open('topsites.txt') as f:
        lines = f.readlines()
    for url in lines:
        url = 'http://' + url.strip()
        threads.append(p.apply_async(worker,[url]))

    p.close()
    try:
        while not all([r.ready() for r in threads]):
            time.sleep(1)
    except KeyboardInterrupt:
        p.terminate()
        p.join()
```

The above code sample (using a fresh compiled version of phantomjs in my testing) will let you reproduce the issue, resulting in the same error thrown when a port is already in use. Modify the phantomjs binary path as necessary.

Every time this happens, the phantomjs process goes defunct, and essentially locks up that thread indefinitely. You can watch this happening using the code sample and

```
watch -C phantomjs u
```

You can grab topsites.txt from http://pastebin.com/raw.php?i=AFrezqpU

**Comment by lbach** [comment]
I'm working on a solution where communication with phantomjs takes place using a unix domain socket. The idea is that the selenium driver will generate a unique file path where it asks phantomjs to listen, then selenium connects to the domain socket. This will put an end to the race where selenium hopes the kernel will not hand out the port to some other process. 

For now I've made the following phantomjs branch: https://github.com/lbach/phantomjs/tree/webdriver_unix_domain_socket which enables phantomjs to listen on a domain socket file instead of a port. It is still a bit rough, but will serve as a proof of concept.

Next step is to make a selenium phantomjs webdriver which connects to the domain socket. This I haven't started yet.

**Comment by barancev** [comment]
PhantomJS support discontinued.
