### ISSUE TITLE
How to set homepage with chrome , my set not work

### ISSUE THREAD

**Issue by duoduoxi** [SeleniumHQ/selenium#5763]
## Meta -
OS:  
win7
Selenium Version:  
3.11.1
Browser:  
chrome 

Browser Version:  
65

Hi, i need to set homepage ,follow code not work, It stil open defalut homepage(google.com). 

i post on stackoverflow,but no one reply. 

` ChromeOptions option = new ChromeOptions();

 option.AddArgument("--custom-launcher-page=about:blank");

 option.AddArgument("--homepage=about:blank");

 iw = new ChromeDriver(option);`

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by duoduoxi** [comment]
ok，thanks.
