### ISSUE TITLE
How to simulate ctrl + s saving the page as txt in Firefox?

### ISSUE THREAD

**Issue by gyje** [SeleniumHQ/selenium#5788]
I use `doc = driver.find_element_by_tag_name('html').text` 
but doc content and ctrl + s saving the page as txt are different. i try send_keys(Keys.CONTROL,'s') , It doesn't work.

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
