### ISSUE TITLE
Getting [1524111659.663][SEVERE]: Timed out receiving message from renderer: 300.000 error while running multiple test and laptop is in ideal conditions

### ISSUE THREAD

**Issue by denishm-ezdi** [SeleniumHQ/selenium#5803]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.11.0
Browser:  
Chrome 

Browser Version:  
65.0.3325.181 (Official Build) 

## Expected Behavior - 
Working properly even thoughts laptop is in ideal conditions

## Actual Behavior - 
Some times selenium hang the browser and scripts stop working for 30 minutes to 2 hour.

## Steps to reproduce -
It happens some times. Not proper steps to reproduce.

**Comment by cgoldberg** [comment]
please submit a detailed description along with proper steps to reproduce, or nothing can be done here.

**Comment by skptricks** [comment]
It causes because page took long time to load , you need add additional line to your chromedriver option. Please refer the below link for more information : 
[Timed out receiving message from renderer in selenium](https://www.skptricks.com/2018/08/timed-out-receiving-message-from-renderer-selenium.html)
