### ISSUE TITLE
Drag-and-drop not working with jquery and ui-sortable

### ISSUE THREAD

**Issue by mskraddoc** [SeleniumHQ/selenium#581]
Hello!

Can you address this stackoverflow question?

http://stackoverflow.com/questions/30495708/testing-drag-and-drop-not-working-rspec-selenium-jquery

Best regards,

Perry

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
