### ISSUE TITLE
switchTo.window() method gets stuck while using with IEDriver.

### ISSUE THREAD

**Issue by Ankitssts** [SeleniumHQ/selenium#5818]
## Meta -
**OS:   Windows 7
Selenium Version:  3.4 and above
IEDriver Version: 3.8 and above
Browser:  Internet Explorer**

On "http://www.essentialbaby.com.au/" webpage, all elements are working using selenium and IEDriver, but when I click on "SUBSCRIBE TO OUR NEWSLETTER" button, it navigates to next page in a new tab.
After that when I try to work on elements on this new page using switchTo() method, it gets stuck at that point and program doesn't proceed further.

**Browser Version:  
IE 11**

## Expected Behavior -
Driver must switch to next window and work on its elements.

## Actual Behavior -
Driver gets stuck at "driver.switchTo().window(windowHandle);" and program doesn't proceed forward.

## Steps to reproduce -

Go to site: http://www.essentialbaby.com.au/ .
Click on "SUBSCRIBE TO OUR NEWSLETTER" button.
Click on "Sign up" link.

Use below code to reproduce this scenario.

System.setProperty("webdriver.ie.driver", "DriverLocation\\IEDriverServer.exe");
driver = new InternetExplorerDriver();
driver.get("http://www.essentialbaby.com.au/");
driver.findElement(By.xpath("//footer[@id='footer']/div[1]/ul/li[6]/a")).click();
driver.switchTo().window(newWindowHandle);
driver.findElement(By.xpath("//a[contains(text(),'Sign up')]")).click();

**Comment by jimevans** [comment]
@Ankissts Not to nitpick, but where does `newWindowHandle` get declared and set in your code sample?

**Comment by Ankitssts** [comment]
@jimevans Mentioned LOC was just to give an idea about how to reproduce it.
If you are not able to get it then let please allow me to expand my LOC a little bit more.

System.setProperty("webdriver.ie.driver", "\\DriverLocation\\IEDriverServer.exe");
driver = new InternetExplorerDriver();
driver.get("http://www.essentialbaby.com.au/");
String currentHandle = driver.getWindowHandle();
System.out.println("Current Window Handle::::::::::::::"+currentHandle);
driver.findElement(By.xpath("//footer[@id='footer']/div[1]/ul/li[6]/a")).click();
Set<String> handles = driver.getWindowHandles();
System.out.println("Window Count::::::::"+handles.size());	
for (String windowHandle : handles) {
	System.out.println("Found Handle:::::::"+windowHandle);
	if(!windowHandle.equals(currentHandle)) {
		System.out.println("Window Handle found::::"+windowHandle);			
		driver.switchTo().window(windowHandle);			
		System.out.println("Page Title:::::::"+driver.getTitle());
		driver.findElement(By.xpath("//a[contains(text(),'Sign up')]")).click();
	}
}
driver.quit();

Please let me know if you need anymore information regarding this.

**Comment by jimevans** [comment]
@Ankitssts There's no need to be rude ("If you are not able to get it..."). Thank you for the clarification. Since you've gone to the trouble to write all of that information out to the console, what is the output of an execution of that sample code? I am able to execute functionally the same code (ported to C#, see below) without any issue using IE.

    // `driver` is a valid instance of an InternetExplorerDriver
    driver.Url = "http://www.essentialbaby.com.au/";
    string parentHandle = driver.CurrentWindowHandle;

    // Changed this locator to be more reliable.
    // Using CSS selector would be more reliable still.
    driver.FindElement(By.XPath("//footer[@id='footer']//a[contains(@class, 'newsletter')]")).Click();
    foreach (string currentHandle in driver.WindowHandles)
    {
        if (currentHandle != parentHandle)
        {
            driver.SwitchTo().Window(currentHandle);
            break;
        }
    }

    driver.FindElement(By.XPath("//a[contains(text(),'Sign up')]")).Click();

**Comment by Ankitssts** [comment]
@jimevans Please accept my apology if you feel offended in any way. I had no such intentions.
Please find debug logs of this execution in attachment. And if you can help in any way, it will be highly appreciated.
[DebugLog.txt](https://github.com/SeleniumHQ/selenium/files/1950013/DebugLog.txt)

**Comment by jimevans** [comment]
A quick perusal of the log shows that the page is never completely loaded. In particular, the browser’s “ReadyState” property never transistions from “interactive” to “complete”. This could be because a domain from which a resource (graphics, script files, analytics data, etc.) are being referenced can’t be reached from your system, or a browser plug-in, or it could be caused by a number of other things.

This doesn’t happen in my environment for the same site. You can easily change the page load strategy in the initial capabilities from the default, unset value to “none”, or “eager”, which might allow the WebDriver code to continue.

In any case, if the browser isn’t reporting that the page is finished loading (the ReadyState property never reaches “complete”), the driver won’t be able to continue. It’s not a bug in the driver.
