### ISSUE TITLE
can i change the proxy while running the code?

### ISSUE THREAD

**Issue by Dashu-Xu** [SeleniumHQ/selenium#5866]
## Meta -
OS:  

Selenium Version:  win 10

Browser:  Firefox

Browser Version:

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
