### ISSUE TITLE
Cannot access website requiring Basic Auth with account and password in URL using IE on Windows 10

### ISSUE THREAD

**Issue by DamienLyles** [SeleniumHQ/selenium#5870]
## Meta -
OS:  
Windows 10
Selenium Version:  
Ruby selenium-webdriver gem 3.11.0, IEDriverServer.exe 3.11.1.0 (32-bit)

Browser:  
Internet Explorer

Browser Version:  
11.1540.10586.0

## Expected Behavior -
My organization has several websites that require basic authentication.  I used to be able to access them with IE 11 by using URLs like what I have below.  

http://my_domain%5my_account:my_password@my_server.gov

## Actual Behavior -
Passing account information still works on Windows 7, but not on Windows 10.  On Windows 10, I get the following error message:

Failed to navigate to http://my_domain%5cmy_account:mypassword6@my_server.gov. This usually means that a call to the COM method IWebBrowser2::Navigate2() failed.

## Steps to reproduce -
Create the "explorer.exe" AND "iexplore.exe" DWORD values of 0 in the Windows registry under
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer\MAIN\FeatureControl\FEATURE_HTTP_USERNAME_PASSWORD_DISABLE

Attempt to navigate to a website that uses basic auth by including the account and password in the URL.

**Comment by jimevans** [comment]
There is no provision for this in the IE driver, and user names and passwords in URLs has been disabled by default for IE for years. If it was working in Windows 7, it was doing so only because someone had configured IE on that machine to allow it. If memory serves, it used to be configurable via a registry setting (which may have been removed in Windows 10). Finding the registry key and setting it appropriately is left as an exercise to the reader.
