### ISSUE TITLE
Can't compile Java9 module with selenium-java as dependency

### ISSUE THREAD

**Issue by mhomnag** [SeleniumHQ/selenium#5896]
Selenium Version:  
3.11.0

I'm trying to build a Java9 module which has selenium-java as maven dependency.

My module-info.java looks something like this:
```java
module my.module {

    exports my.package;

    requires httpcore;
    requires json;
    requires selenium.api;
    requires selenium.chrome.driver;
    requires selenium.edge.driver;
    requires selenium.firefox.driver;
    requires selenium.ie.driver;
    requires selenium.remote.driver;
    requires selenium.support;
}
```

However, when compiling my module with maven I get the following error message:
module my.module reads package org.openqa.selenium.logging from both selenium.api and selenium.remote.driver

This seems to happen, because both selenium-api and selenium-remote-driver contain a package called "org.openqa.selenium.logging". Java 9 (and all later versions) forbid this. This problem is called "split packages".

Is there any chance, we can get this problem fixed in the next releases? Or is there some other dependecy I should use instead of selenium-java (for example a single JAR that contains everything)?

**Comment by mhomnag** [comment]
Here is a reproducer with Java 10 and Selenium 3.12.0: https://github.com/mhomnag/selenium-java10-reproducer

You just need to run "mvn compile" and that's it.

**Comment by lmtierney** [comment]
Last I knew selenium wasn't yet fully compatible with Java 9. @barancev ?

**Comment by mhomnag** [comment]
Any update on this issue?

**Comment by barancev** [comment]
Pull requests are welcome ;)

**Comment by mhomnag** [comment]
Hehe, that's what I thought :)
I'll try to take some time for this.

**Comment by mhomnag** [comment]
OK, so to solve this particular issue, it seems to be enough to move all classes in the logging package to the selenium-api JAR. However, I can't find the BUCK file which packages the additional classes to the selenium-remote-driver JAR.

Could you point me to the right file?

**Comment by mhomnag** [comment]
Hrmpf... I seriously have no idea, how to solve this.
I think that logging:api and logging:logging need to be merged, but I've run into various problems. The worst seems to be a circular dependency with json:json (because "HttpProfilerLogEntry.java" needs that). This would be easily solvable, if that class could use GSON. But when reading the latest Java client CHANGELOGS, this seems to be deprecated.

Any ideas?

**Comment by joerg1985** [comment]
Hi,

i had a look at the package "org.openqa.selenium.logging". It contains a lot of mixed code, perhaps it is possible to cleanup and split the classes to different packages. 
This might be a breaking change, but in my mind it is important to support the java module system.

I would suggest to move LogType to the API jar, because LoggingPreferences relies on the string values defined there and LoggingPreferences is inside the API jar. The LoggingHandler and LogCombiner should also be moved to the API jar, because they are not related to the remote driver, but are related to the classes defined inside the API jar and are desigened for public use.

All classes inside the package "org.openqa.selenium.logging" containing "SessionLog" could be moved to a package "org.openqa.selenium.logging.session" inside the remote jar. 
All classes inside the package "org.openqa.selenium.logging" containing "LocalLog" could be moved to a package "org.openqa.selenium.logging.local" inside the remote jar.


This should solve the split packages issue, because the packages are now unique per jar file.
What do you think about this suggestion?

Kind regards

**Comment by mhomnag** [comment]
I think, this sounds pretty good. I'll try to have a look at this in the next few days! Thanks a lot for the suggestions!

**Comment by seombre** [comment]
@joerg1985 I've just submitted the pull request for this.

**Comment by MarionaDSR** [comment]
@seombre , was your pull request accepted?
@mhomnag , is this issue solved?

If yes, can you close it? Thank you!

**Comment by seombre** [comment]
Actually both accounts belong to me, so speaking for both ;)

No, the pull request was not accepted. It was, however, done in another way by @shs96c 
And as mentioned in the comments of my pull request, there were still some issues.

**Comment by shs96c** [comment]
There are definitely issues. Adding this to the backlog for Selenium 4

**Comment by shs96c** [comment]
I think we resolved the split package problem a while ago, but only by accident as we tidied up our build files :)

I've spent the past few days working on the Java module support, and I think it's now a lot better. We infer the module names from the Maven coordinates (so `org.seleniumhq.selenium:selenium-api` becomes the module `org.seleniumhq.selenium.api` and `org.seleniumhq.selenium:selenium-firefox-driver` becomes the module `org.seleniumhq.selenium.firefox_driver`) so those should always be in sync. I think we've correctly opened the modules to each other as necessary (please let me know if we haven't!) and we _should_ have also exposed the services correctly.

Some of our transitive dependencies are automatic modules, so unfortunately you can't yet use `jlink` to generate a standalone application. We're working to resolve that problem too.

Your example repo was particularly useful for resolving this issue, so please accept my thanks for setting that up!

I'm going to mark this issue as closed, but please LMK if there's still an issue once the beta ships.
