### ISSUE TITLE
Support POST	/session/{session id}/window/rect in javascript (nodejs) client.

### ISSUE THREAD

**Issue by johnjbarton** [SeleniumHQ/selenium#5926]
The W3C command for window position and size is 
POST	/session/{session id}/window/rect
https://www.w3.org/TR/webdriver/#set-window-rect 

The javascript/webdriver code:
https://github.com/SeleniumHQ/selenium/blob/master/javascript/webdriver/command.js#L139
only supports non-W3C position and size.

We discovered this omission when we switched to the W3C IE11 driver.

There does not seem to be any W3C code in javascript/webdriver/command.js whereas the py code
https://github.com/SeleniumHQ/selenium/blob/a92a0496c5f75cc0afa2e3585143493bfe7aa088/py/selenium/webdriver/remote/command.py
has several W3C-specific commands: there may be other W3C features missing from the JS code.

**Comment by johnjbarton** [comment]
The 4.x release does not support control-flow and its anyway alpha not something we can insist users adopt.  I think another 3.x release would help a lot.

**Comment by johnjbarton** [comment]
From the 4.0.0 alpha release notes: 

>Changes to lib/webdriver.WebElement:
>  Replaced getSize & getLocation with getRect

So if I understand correctly: 
  For Javascript and non-W3C drivers (eg chrome) you have to use 3.x
  For Javascript and W3C drivers (eg firefox) you have to use 4.x
The python and Java drivers support both with flag.

Is this correct?

**Comment by jleyba** [comment]
[`getRect`](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/webdriver.js#L1421) will automatically fall back to the legacy protocol if the remote end returns an unknown command error (likewise for `setRect`). Just update your code to use the new API and let the library do the rest.

As for 4.0 vs 3.x: the js bindings use trunk-based development (well, the Selenium project as a whole does) and anything pushed to npm is considered fully supported. I pushed the release as `4.0.0-alpha.1` instead of as another `3.x` release because of the scope of the changes (removing the control flow, many changes to the public API). I wanted to wait for Selenium as a whole before going to `4.0.0`, so I pushed as "alpha". In hindsight, this was probably a mistake.

The only changes I currently have planned before the "real" 4.0 release (assuming I ever find time) are some improvements to the interactions API. Otherwise, everything is stable and supported like any other published release.
