### ISSUE TITLE
HTTP PRoxy for anonymous browsing

### ISSUE THREAD

**Issue by Prutheus** [SeleniumHQ/selenium#5946]
Hello. I am using selenium-webdriver with the chrome driver on my ruby project. I want to use http proxies to make my browsing anonymous. I use that setting for it:

    Selenium::WebDriver::Proxy.new(http: "#{ip}:#{port}")
      driver = Selenium::WebDriver.for :chrome

 but for some reason, the driver does not have the ip of the proxy, instead it has the server ip ... why?

Why is my http proxy not used/working?

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
