### ISSUE TITLE
How to get the HTTP Headers using Selenium Webdriver

### ISSUE THREAD

**Issue by komalaameneni** [SeleniumHQ/selenium#602]
Hi,
I see there are many posts on HTTP headers not supported in Selenium. 
Can someone please point me to the workaround we use in order to get the HTTP headers using Selenium WEBDRIVER. I would be very glad if the exact code snippet is shared on how to retrieve the http headers.

Thanks,
Komala A

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
