### ISSUE TITLE
Question: does the driver for Safari work for webview in a Mac OS application?

### ISSUE THREAD

**Issue by hy9be** [SeleniumHQ/selenium#603]
It seems the chrome driver could work with CEF webview: https://bitbucket.org/chromiumembedded/cef/wiki/UsingChromeDriver

But I did not find a way to set binary when using the Safari driver. Does it mean the current Safari driver cannot work with webview?

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by hy9be** [comment]
Thanks!
