### ISSUE TITLE
ChromeDriver.exe is not closing from Task Manager

### ISSUE THREAD

**Issue by Girishrakhe** [SeleniumHQ/selenium#6040]
## Meta -
OS:  

Selenium Version:  3.11

Browser:  Chrome 67.0.3396.87

Browser Version:  67.0.3396.87

**Comment by Girishrakhe** [comment]
catch (Exception exc)
            {
                driver.Quit();
}

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
