### ISSUE TITLE
Internet Explorer and Chrome respond to isDisplayed() differently

### ISSUE THREAD

**Issue by ben-yocum** [SeleniumHQ/selenium#6059]
## Meta -
OS: Windows 10
Selenium Version: 3.11.0
Browser: IE11, Chrome
Browser Version:
IE: 11.1.029.15063.0 (64-bit)
Chrome: Version 67.0.3396.87 (Official Build) (64-bit)

## Expected Behavior
Chromedriver and IEServerDriver should always give the same result when `isDisplayed()` is run agains the same element.

## Actual Behavior
In Chrome we get `false`. In IE we get `true`. (The expected behavior is `false`. What a shocker, Internet Explorer is causing problems.)

## Steps to reproduce
See [this repository](https://github.com/GitSage/selenium-is-displayed-ie-bug) for an SSCCE. In short, given this html:

```
<html>
<body>
<div style="height: 0; overflow: hidden;">
	<div style="display: flex;">
		<button style="position: relative;" id="should-not-be-displayed">
			<span style="position: absolute; left: 0; top: 0; bottom: 0; right: 0;"></span>
		</button>
	</div>
</div>
</body>
</html>
```

Test whether the button is displayed in both IE and Chrome:

```
const {Builder, By} = require('selenium-webdriver');

(async () => {
	let locator = By.id('should-not-be-displayed');

	let ieDriver = await new Builder()
		.forBrowser('internet explorer')
		.build();

	await ieDriver.get('http://127.0.0.1:8080/selenium_bug.html');
	await ieDriver.navigate().refresh(); // ie likes to cache the page even between sessions
	let isDisplayedIE = await ieDriver.findElement(locator).isDisplayed();

	console.log(`IE isDisplayed    : ${isDisplayedIE}`);

	let chromeDriver = await new Builder()
		.forBrowser('chrome')
		.build();

	await chromeDriver.get('http://127.0.0.1:8080/selenium_bug.html');
	let isDisplayedChrome = await chromeDriver.findElement(locator).isDisplayed();

	console.log(`Chrome isDisplayed: ${isDisplayedChrome}`);

	await ieDriver.quit();
	await chromeDriver.quit();
})();
```

This outputs:

```
IE isDisplayed    : true
Chrome isDisplayed: false
```

Every part of this html must be as it is for the bug to occur. Specifically, the html must follow these rules:

* A grandparent div hides the button with the styles `height: 0; overflow: hidden;`
* A parent div is `display: flex;`
* The button is `position: relative;`
* The button contains a span with `style="position: absolute; left: 0; top: 0; bottom: 0; right: 0;"` (see [this related bug](https://github.com/SeleniumHQ/selenium/issues/6058))

**Comment by GitSage** [comment]
I forgot to mention. This issue is relevant because [angular material's](https://material.angular.io/components/button/overview) `mat-button` is built this way. If you drop that button into a div with `display: flex`, then try to hide that div with `height: 0; overflow: hidden;`, Internet Explorer will report that the div is still visible.

**Comment by AutomatedTester** [comment]
I think this is a similar "problem" to #6058.

Since IE doesnt support flexbox the bounding rect might be returning a different value to Chrome and/or chrome's `isDisplayed` atom might be out of date

**Comment by GitSage** [comment]
My understanding is that [IE11 does support flexbox](https://caniuse.com/#feat=flexbox) but [has some bugs](https://github.com/philipwalton/flexbugs). I read over the buglist and I can't see any that apply to this bug. My app uses Flexbox live on IE11 right now.

If it is an IE11 bug then should we find a workaround, or just blame Microsoft and close it? I'm willing to try to help out with this but I need to know where to start. Where is Chrome's `isDisplayed` atom? What do I compare it against to see if it's out of date?

What is the correct behavior here anyways? Nothing is being drawn due to `height:0; overflow:hidden;` so it should be `not displayed`, right?

**Comment by danieladougan** [comment]
My Selenium tests run successfully in Firefox and Chrome, but when I launch IE 11, I get an error that it can't find an element even though it is displayed on the screen and appears in the DOM by the same name.

Expected behavior: isDisplayed = true
Actual behavior: isDisplayed = false

It doesn't matter even if I add a long explicit wait. IE never detects the element.
