### ISSUE TITLE
How do we get EXACT XPath of an existing/known element?

### ISSUE THREAD

**Issue by sanguuday** [SeleniumHQ/selenium#6118]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by sanguuday** [comment]
IWebElement _element = Driver.FindElement(By.XPath("//a[contains(text(), 'Uday Kumar Sangu')]"));
srting elementXpath = _element.getAttribute("Xpath");

elementXPath should contain exact XPath of the element...like //table[contains(@id, "group")]/thead/tr[1]/th[8]/a

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
