### ISSUE TITLE
Selenium - FF 37 - Jenkins - server not found browser error

### ISSUE THREAD

**Issue by balamv** [SeleniumHQ/selenium#615]
Hi Team,
When I executes the Jenkins job, it calls maven build that executes the selenium scripts. Am facing a weird Issue, my browser shows server not found error and it is not able to proceed with the tests. But at the same time, if I execute the maven build manually, it can connect to the application and works fine. This issue we noticed after Firefox got upgraded to 37. We are not able to conclude that issue is due to Firefox upgrade as if you open the browser and access the application manually, it works. The issue just when we execute the job through Jenkins. Anybody faces this issue? Kindly help on this.

Thanks,
BV

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
