### ISSUE TITLE
Request failed certificate checks while running protractor test with selenium 3.3.1, geckodriver- 18.1 and firefox 52 on windows 7

### ISSUE THREAD

**Issue by suryavir** [SeleniumHQ/selenium#6153]
## Meta -
OS:  
Windows 7

Selenium Version:  
Selenium 3.3.1

Browser:  
Firefox 52 
I am getting this error when I run selenium server + then run my protractor tests in firefox 52. The firefox browser opens up but then in the selenium log this error shows up-

1469541521068 addons.productaddons ERROR Request failed certificate checks: [Exception... "Certificate checks failed. See previous errors for details." nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)" location: "JS frame :: resource://gre/modules/CertUtils.jsm :: validateCert :: line 113" data: no]

Any help would be appreciated!

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
