### ISSUE TITLE
The latest version of Selenium-WebDriver is not published to NPM

### ISSUE THREAD

**Issue by deflagg** [SeleniumHQ/selenium#616]
I'm 1 month new to github and npm.  I'm installing the selenium-webdriver via npm.  There is an update to this code 13 days ago and I need the code because I'm affected by the bug.  I tried to re-install via npm, but I'm still getting an older version from what is in github.  Do you have to publish the update to npm?  Is there a set delay?  If there is, how can I use npm to install the webdriver from github?  I tried npm install [selenium webdriver url] , but it did not work.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
