### ISSUE TITLE
Browser Session Cookie Expired

### ISSUE THREAD

**Issue by Manikandan018** [SeleniumHQ/selenium#6258]
## Meta -
OS:  
    Windows 10, Linux, Mac 
Selenium Version:  
    3.8.1 
Browser:  
   Google Chrome
Browser Version:  
   67.0 64-bit series
Chrome Driver Version:
   2.38

## Expected Behavior -
Getting cookie from first logged in browser session and stored in redis. after this reuse the above session cookie for all the browsers(20 browsers run in parallel) logged in successfully.

## Actual Behavior -
Sometimes getting logged out during the test using the above stored session cookie.

Let me know, Is  this causes by account problem or selenium chrome driver problem ?

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
