### ISSUE TITLE
Win10 IE version 11 protection mode issue -- need your support

### ISSUE THREAD

**Issue by ManojR16** [SeleniumHQ/selenium#6259]
## Meta -
OS:  
Windows 10 
Selenium Version:  
13 
Browser:  
Internet Explorer version 11

Hi,

This is regarding an issue which we are currently facing in my team related to IE browser protection mode. 

In Windows10, IE version 11 is not working with Selenium. I checked this in your wiki @ https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver website, and it suggested to enable the protection mode in IE internet option (Security tab) for all security zones.

However, I am not able to perform this operation under these zones: Local Intranet/Trusted sites/Restricted sites. Only it is enabled in Internet zone, perhaps it is due to company policies.

Hence, could you please suggest me some alternative option through which I can test/execute IE through selenium. I also checked the option : INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS through Java, which also did not work.

I am receiving "Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones" error message

Please support me in this.

Thanks & Regards,
Manoj

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
