### ISSUE TITLE
[QUESTION] Status of "selenium-webdriver" package?

### ISSUE THREAD

**Issue by SamuraiJack** [SeleniumHQ/selenium#6340]
Hello,

What is the status of "selenium-webdriver" package on npm? Its "4.0.0-alpha1" released 7 months ago. Is it still maintained? Which java binaries release it supports?

Thanks, Nickolay

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by SamuraiJack** [comment]
Ok, sorry for the noise. Posted to the user group: https://groups.google.com/forum/#!topic/selenium-users/NZ9Qsp5as9w
