### ISSUE TITLE
Chromedriver doesnt start on Windows startup

### ISSUE THREAD

**Issue by StepIg** [SeleniumHQ/selenium#6348]
## Meta -
OS:  windows 7, 10
Selenium Version:  
3.x
Browser:  
Chrome

Issue Description:
I'm using Selenium chromeDriver on Vb.net. Using Windows 7 and 10 i have a strange problem. If i set the app for start with Windows start, i got a crash app in this line:

.AddExtensions

But if i start the app manually once Windows has started all is running fine.
The code is:

Dim options As New OpenQA.Selenium.Chrome.ChromeOptions
Dim service As ChromeDriverService = ChromeDriverService.CreateDefaultService()
service.HideCommandPromptWindow = True
options.AddExtensions("ExtensionFoo.crx")

## Expected Behavior -
Must start correctly when i start the app automaticly on windows startup.

## Actual Behavior -
When app start with windows automaticly, app crashes.

## Steps to reproduce -
With this code as VB.net project

Dim options As New OpenQA.Selenium.Chrome.ChromeOptions
Dim service As ChromeDriverService = ChromeDriverService.CreateDefaultService()
service.HideCommandPromptWindow = True
---> options.AddExtensions("ExtensionFoo.crx") <----

When arrive to options.AddExtensions("ExtensionFoo.crx") line, app crashes.

**Comment by p0deje** [comment]
Please post ChromeDriver specific issues to [its own bug tracker](https://sites.google.com/a/chromium.org/chromedriver/help).

**Comment by StepIg** [comment]
Why issues for Firefox and other browsers are allowed here and for ChomeDriver no?

**Comment by p0deje** [comment]
Only issues with legacy FirefoxDriver are allowed here, because the driver is written and support by Selenium. The newer Firefox driver (aka GeckoDriver) its issues are also redirected to GeckoDriver's bug tracker. The reason we do that for GeckoDriver and/or ChromeDriver is because we cannot fix issues in driver - they are not developed by Selenium community (ChromeDriver is mainly developed by Google, GeckoDriver - by Mozilla). It's not a matter of space, it's just because we don't have any control over ChromeDriver and its developers don't look through Selenium bug tracker.

**Comment by barancev** [comment]
`options.AddExtensions("ExtensionFoo.crx")` does not interact immediately with chromedriver, it just modifies `options` object in memory. It may be a client-side issue.

Also we need to know the exact WebDriver library version and the extension you're loading.

**Comment by barancev** [comment]
Closing the issue as there is no response from the author.
