### ISSUE TITLE
Click that must open "menu" do not actually open this "menu"

### ISSUE THREAD

**Issue by igorSss** [SeleniumHQ/selenium#637]
I have element like this: 
<div class="data-cell-menu menu-field">

When i clicked for this element some menu must be opened - but in fact only in FF and only with selenium 2.46 (in 2.43 bugs are absent) menu are not opened. In Chrome and IE -  ok - menu is opened

driver.findElement(By.xpath("//div[@class='data-cell-menu menu-field']")).click();

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
