### ISSUE TITLE
Need help in enable and disable proxy setting in IE for Serenity BDD Framework through code

### ISSUE THREAD

**Issue by ShubhamSerenity** [SeleniumHQ/selenium#6376]
## Meta -
OS:  
<!-- Windows 10
Selenium Version:  
<!-- 2.52.0, IDE
Browser:  
<!-- Internet Explorer
Hi,
Need help in enable the proxy setting "10.204.2.169:1999" in IE browser and disable after running few lines of code.
Can you please help to resolve this issue.
Can anyone help in providing the java code for enable/disable the proxy setting in Internet Explorer.

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by IlyaDhtvzGhbltn** [comment]
excuse me, but your group is too slow, I was send my question yesterday morning. for now, question even not been published! I get questions from other users on my email, but you can send at least explanation - why MY question not published until now? I just want to launch FF under current profile. All solution, I found are not working.

**Comment by lmtierney** [comment]
@IlyaDhtvzGhbltn please do not bring comments from other issues to share your grievances. Since it is your first post to the user-group, an admin needs to approve it. Please be patient as we are all volunteers on this project, and not everyone who is a committer here has admin privileges to the users group. You can always ask questions in the IRC channel where there are usually more active people. https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#communication
