### ISSUE TITLE
Selenium:WebElement Not Found by Selenium even though its visible on WebPage

### ISSUE THREAD

**Issue by SudeeptMohan** [SeleniumHQ/selenium#6383]
Selenium - 3.13
Windows - 10
TestNG - 6.14

Following code opens a website, which in turn opens another website.On this opened website the web element is not found by selenium.Kindly intervene.

```
package onlinePractice;

import java.util.ArrayList;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.Test;

public class testCasesphpTravelsTest {

    String baseUrl = "http://phptravels.com/demo/";
    String driverPath = "C:/Marionette/geckodriver.exe";
    WebDriver driver;

    @Test
  public void login() {
  System.setProperty("webdriver.gecko.driver", driverPath);
  driver = new FirefoxDriver();
  driver.get(baseUrl);

  WebElement login = driver.findElement(By.linkText("LOGIN"));

  if (login.isDisplayed()) 
  login.click();

  WebElement email = driver.findElement(By.xpath("//input[@id='inputEmail']"));

}
}
```

**Comment by lmtierney** [comment]
It opens the new webpage in a new window. You need to switch to that window.

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
