### ISSUE TITLE
Selenium automatic Screenshotting for failed TestNg tests

### ISSUE THREAD

**Issue by yev** [SeleniumHQ/selenium#643]
I developed a little plugin which facilitates the automatic "screenshotting" for each failed test in TestNG suites. 
I'm interested in the possibility to share it with the community.
The code is here - https://github.com/yev/seleniumMvnScreenshot

Where can I integrate this part? Do you interested in it or should I contact the guys from TestNg?

Tnx

**Comment by lukeis** [comment]
you can try to reach out to the testng community or elsewhere. There's also many people who have blogged about this type of code. And in my opinion it usually needs to be copied into to the tests since you can't necessarily depend on where the WebDriver instance lives, but I see you made a good effort to attempt to :)
