### ISSUE TITLE
at a element, single click not woking but clicking two times works

### ISSUE THREAD

**Issue by sdhsmm** [SeleniumHQ/selenium#6442]
## Meta -
OS:  All

Selenium Version:  3.14

Browser:  All

Browser Version:  all

## Expected Behavior -

click should work at first click

## Actual Behavior -
single click shows hover, two time clicks, clicks the element

## Steps to reproduce -
:- go to home page of starbuks.com and landsend.com
:- at starbucks.com, click at coffehouse and at landsend.com, click at New, Women,Kids

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by sdhsmm** [comment]
hello alex, thnks for replying

**Comment by sdhsmm** [comment]
Actually at starbucks.com, single clicking at coffeehouse tab in nav bar is giving fakepass but clicking again works exactly

**Comment by p0deje** [comment]
```ruby
require 'selenium-webdriver'

driver = Selenium::WebDriver.for(:firefox)
driver.get 'http://www.starbucks.com'
driver.find_element(css: '#nav_coffee a').click
raise unless driver.current_url.include?('coffee')
```

**Comment by p0deje** [comment]
Wild guess is that Starbucks has some strange event handlers resulting in this behavior. This needs investigation.

**Comment by sdhsmm** [comment]
thanks alex, it helps a lot.

**Comment by twalpole** [comment]
This is because of the way the site is designed.   The page doesn't process the click as a page transition unless the dropdown menu is shown.  Normally the menu will dropdown due to a `mouseover` on the link, however when you tell selenium to click the element there is no `mouseover` event (or there is one but it's so quickly followed by the click that it's ignored) produced so you get behavior like on a tablet - the first click/touch drops the menu, the second click/touch transitions to a new page.

**Comment by p0deje** [comment]
@twalpole Thanks for the explanation! How did you figure that out?

ChromeDriver for example doesn't emit `mouseOver` specifically https://github.com/bayandin/chromedriver/blob/e67c7a2005dd07beda01fa87d4e5ac05c792a707/element_commands.cc#L166-L176, but I agree that it's probably because the period between those events and click is too small and the site doesn't have time to process it.

As a workaround, you can move mouse first and then click:


```ruby
driver.action.move_to(driver.find_element(css: '#nav_coffee a')).perform
driver.action.click.perform
```

Also, WebDriver specification doesn't define which particular events should be emitted, so it's up to driver to decide (https://w3c.github.io/webdriver/#dfn-perform-a-pointer-move).

Looks like there is not much we can do about it on Selenium side.

**Comment by twalpole** [comment]
@p0deje I've seen similar behavior previously, and it was the only thing that made sense from a quick look at the page.  It's the result of developers attempting to make a menu work on desktop and touch devices using the same code.
