### ISSUE TITLE
how to disable javascript after the a chrome widow is opend

### ISSUE THREAD

**Issue by WongYueKeung** [SeleniumHQ/selenium#6455]
any platform

we can disable javascript before creating a chrome widow
but how to disable it after the chrome window is created?

for an example, the login page required javascript to work, and then I want to disable the javascript the get plain HTML source code from the server without any javascript is executed.
Because javascript will modify the HTML DOM and stuff like that.
thank you very much

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by WongYueKeung** [comment]
no, it is a issue

because when we r getting the page source code:
$driver->getPageSource();

there is no such an option to disable javascript, it is a very common issue, sometimes we need to let javascript run for a while, and when it comes to next pages, we want to disable javascript to figure out what data did server responded to the browser.
And this is an important issue bro.

Thank you!

**Comment by WongYueKeung** [comment]
this issue occurs on any platform and any pages, cant provide with a sample or something

**Comment by lmtierney** [comment]
Again, selenium does not handle this, the driver vendor does.
