### ISSUE TITLE
Not able to click submenu which is dynamicly visible in Selenium WebDriver 2.45 and Firefox 31.0

### ISSUE THREAD

**Issue by Bagirathe** [SeleniumHQ/selenium#648]
In my scenario, I need to click the submenu that's only visible when its parent menu is in 'mouse over' status:
   MainMenu (Dropdown list)(ul)
   SubMenu of MainMenu (a)
   SubMenu of SubMenu of MainMenu (li)
   
I need to click the 6th submenu, but it can only be visible when 1st dropdown menu is clicked on and mouse over the 2nd. I've tried with the ActionChains (Java) api (move_to_element, click, perform , even click_and_hold) in Selenium WebDriver, but had no luck. Can anyone please help me with this. Great Thanks!
  Here is the HTML tags

<li class="dropdown-submenu pull-left">
<a class="ng-scope" translate="" href="" tabindex="-1">Reports</a>
<ul class="dropdown-menu">
<li class="disabled">
<li>
<li class="disabled">
<li class="disabled">
<li class="disabled">
<li>
<a class="ng-scope" translate="" href="" ng-click="rawReport();" tabindex="-1">Raw Data Report</a>
</li>
<li class="disabled">
</ul>
</li>
</ul>

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
