### ISSUE TITLE
can selenium be detected with some features by javascript?

### ISSUE THREAD

**Issue by pyhacx0f** [SeleniumHQ/selenium#6553]
## Meta -
OS:  win7&10
Browser:  firefox、chrome、ie

Is there a way to detect if the browser is being manipulated by selenium and webdriver via JavaScript? I just want to know if there are some unique features in selenium that can be used by javascript to detect whether it is a real browser or an automation framework. just in order to against the bot.

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by pyhacx0f** [comment]
> ## Meta -
> OS: win7&10
> Browser: firefox、chrome、ie
> 
> Is there a way to detect if the browser is being manipulated by selenium and webdriver via JavaScript? I just want to know if there are some unique features in selenium that can be used by javascript to detect whether it is a real browser or an automation framework. just in order to against the bot.

.
