### ISSUE TITLE
timeout configuration in grid2 hub.json

### ISSUE THREAD

**Issue by wck821829906** [SeleniumHQ/selenium#6570]
I want to know about the "timeout" configuration in grid2 hub.json, if the grid2 will kill the chrome.exe and chromedriver.exe process when the time exceed.
![image](https://user-images.githubusercontent.com/17002975/47344504-3af33780-d6db-11e8-9dd5-130a13f82176.png)

**Comment by diemol** [comment]
Hi @wck821829906,
 
Timeout corresponds to the max time in milliseconds that a session can be inactive, after this, the session is terminated and the resources should be released.

Moreover, this is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
