### ISSUE TITLE
OpenQA.Selenium.Remote.RemoteWebElement.GetAttribute method not always returning the correct value

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#6578]
## Meta -
OS:  
Windows 10 and Windows 7
Selenium Version:  
```
  <package id="Selenium.WebDriver" version="3.14.0" targetFramework="net45" />
```
Browser:  
Google Chrome

Browser Version:  
Version 70.0.3538.77 (Official Build) (64-bit)

## Expected Behavior -
Value of class attribute on the element is returned

## Actual Behavior -
Returns "System.Object[]"

## Steps to reproduce -
Run the attached .NET C# UnitTest Project which contains 2 Test Methods, one that works and one that fails.  The only difference between the 2 tests is the url they use to get the web page elements.

[UnitTestSeleniumGetAttributeMethod.zip](https://github.com/SeleniumHQ/selenium/files/2515454/UnitTestSeleniumGetAttributeMethod.zip)

## Extract taken from the UnitTest1.cs test class file in the .NET C# UnitTest Project 
```
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace UnitTestSeleniumGetAttributeMethod
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void Successful()
        {
            using (var driver = new OpenQA.Selenium.Chrome.ChromeDriver())
            {
                driver.Navigate().GoToUrl("https://staticdemosite.z21.web.core.windows.net/page1.html");

                var element = driver.FindElementById("chair_56");
                var classValues = element?.GetAttribute("class");

                Assert.IsFalse(classValues == "System.Object[]");
            }
        }

        [TestMethod]
        public void Fail()
        {
            using (var driver = new OpenQA.Selenium.Chrome.ChromeDriver())
            {
                driver.Navigate().GoToUrl("https://www.seagullstickets.com/en-GB/events/albion%20v%20arsenal/2018-12-26_17.15/american%20express%20community%20stadium?area=c5eae2e3-b424-4010-94cb-11c22d0a54e3&type=");

                var element = driver.FindElementById("chair_56");
                var classValues = element?.GetAttribute("class");

                Assert.IsFalse(classValues == "System.Object[]");
            }
        }
    }
}
```

**Comment by jimevans** [comment]
When running the failing scenario, the `chromedriver.exe` sends the following response body:

    {
      "sessionId":"7bfd8dc7e46d898340d19cfd9718af82",
      "status":0,
      "value":["s","e","a","t"," ","o"," ","i","-","a"," ","l","v","l","_","9","f","9","7","8","e","1","8","-","5","9","e","7","-","4","6","0","c","-","a","9","d","d","-","0","2","5","d","7","9","2","c","9","0","c","1"]
    }

This is incorrect for both the OSS and W3C dialects of the wire protocol. The `value` property should be a string, not an array of strings. I suspect this might be a bug somehow in the automation atom that underlies the `getAttribute` command for both Chrome and IE. Accordingly, it would also appear in other language bindings as well.

Looking at [the atom](https://github.com/SeleniumHQ/selenium/blob/master/javascript/webdriver/atoms/attribute.js#L108), I can't see any reason why it should be returning an array instead of a string. I'm hopeful that @shs96c or @barancev can look at this for Java, and let us know if the behavior is the same as C#.

**Comment by barancev** [comment]
Tried Selenium Java binding 3.141.59, ChromeDriver 2.46, Chrome 73.0.3683.103.
The response is:
```
{"sessionId":"c21523f20e44756e6e6627295d67c7f5","status":0,"value":"seat o i-a lvl_60d706a2-d65f-4265-8a30-a9935dd796fd s-i"}
```
