### ISSUE TITLE
DirectCast(e, ILocatable).Coordinates.LocationOnScreen

### ISSUE THREAD

**Issue by brickhe** [SeleniumHQ/selenium#660]
call DirectCast(e, ILocatable).Coordinates.LocationOnScreen
' e is type of IWebElement
raise a exception: 
An exception of type 'System.NotImplementedException' occurred in WebDriver.dll but was not handled in user code

and, have a function to get the browser's handle in type of IntPtr ? can get the first opened  browser's handle on create new driver?

**Comment by jimevans** [comment]
Getting the location on the screen is not implemented, so this is the proper behavior. The driver is throwing the correct exception. 

As for getting the browser's OS-specific window identifier (called a "handle" on Windows), that is not going to happen for the WebDriver API. I've argued for such a method, as it makes some use cases for companion projects easier, but the designer of the API (@shs96c) has consistently argued otherwise.

**Comment by pvtpeter** [comment]
Hi jimevans,

Is there any public or non-public, specific or non-specific code snippet which can indentify the absolute position of a WebElement on screen?
If not, will it be implemented in the near future?
I think, it would be a useful feature.

Thank you in advance for your answer.
