### ISSUE TITLE
Selenium:Python Client- minimize_window(self) function need to be W3C compliant.

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#6656]
## Meta - Selenium:Python Client- [`minimize_window(self)`](https://seleniumhq.github.io/selenium/docs/api/py/_modules/selenium/webdriver/remote/webdriver.html#WebDriver.minimize_window) function need to be W3C compliant.
OS:  All
Selenium Version:  3.14.0

Browser:  NA

Browser Version:  NA

## Expected Behavior - The function definition for [`maximizing`](https://seleniumhq.github.io/selenium/docs/api/py/_modules/selenium/webdriver/remote/webdriver.html#WebDriver.maximize_window) the window was adjusted as per the _W3C Recommended Specification_ as follows:

    def maximize_window(self):
        """
        Maximizes the current window that webdriver is using
        """
        params = None
        command = Command.W3C_MAXIMIZE_WINDOW
        if not self.w3c:
            command = Command.MAXIMIZE_WINDOW
            params = {'windowHandle': 'current'}
        self.execute(command, params)
        
So, the function definition for [`minimizing`](https://seleniumhq.github.io/selenium/docs/api/py/_modules/selenium/webdriver/remote/webdriver.html#WebDriver.minimize_window) the window should have updated as per the _W3C Recommended Specification_

## Actual Behavior - The function defination for[ `minimizing`](https://seleniumhq.github.io/selenium/docs/api/py/_modules/selenium/webdriver/remote/webdriver.html#WebDriver.minimize_window) the window is still pending to be W3C compliant within the Python Client as is still defined as:

    def minimize_window(self):
        """
        Invokes the window manager-specific 'minimize' operation
        """
        self.execute(Command.MINIMIZE_WINDOW)

**Comment by lmtierney** [comment]
This is compliant, unless I'm missing something? It is not `W3C_MINIMIZE_WINDOW` because there was no minimize functionality before. 

https://github.com/SeleniumHQ/selenium/blob/f028f08e9af4abb743569743e077a5b7f3eaa8cc/py/selenium/webdriver/remote/command.py#L108

refers to 

https://github.com/SeleniumHQ/selenium/blob/f028f08e9af4abb743569743e077a5b7f3eaa8cc/py/selenium/webdriver/remote/remote_connection.py#L351-L352

which is the endpoint from the spec https://www.w3.org/TR/webdriver1/#minimize-window
