### ISSUE TITLE
Introduce API for Distributed Tracing

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#6663]
At least on the server side. This should support both OpenCensus and OpenTracing

**Comment by shs96c** [comment]
This is now done thanks to 15f31bd47a9a0924d006914d93ee6577d2947d3f and c18f2f31248c1cdd651e9fbd9f45db00e369e712. There's still work to do, but the basics are in place now, and we can start using them.

**Comment by KroArtem** [comment]
Sorry for posting in the closed issue but I think it's worth mentioning: [OpenCensus and OpenTracing are merging](https://medium.com/opentracing/merging-opentracing-and-opencensus-f0fe9c7ca6f0)

That's why it might be a good idea not to spread resources on providing APIs to two projects.

 Btw, whilst on it, are there any examples how to use tracing regarding selenium? Like, "we can use this API to get data about sessions and do what with this information"?
