### ISSUE TITLE
Issue with Reading data from Excel Sheet when Excel functions are used to modify the required data

### ISSUE THREAD

**Issue by vickeekulkarni** [SeleniumHQ/selenium#6687]
## 🐛 Bug Report

From Excel want to read the Date as data for my application. The date as condition that one date should be Today's (current) date and another 30 days advance to the current date. So I'm using Cell Function to make data live. But I observed when data is read from webdriver its reading the function value as input data.

Hope needs some fix for the code to read teh cell content instead of Function.

Detailed steps to reproduce the behavior:

It should read the date generated using Excel Function.
Used Function is Excel:  =(TODAY)

## Test script or set of commands reproducing this issue

1. Create an Excel file and format Cell Type as Custom.
2. Set Date format as mmm dd, yyyy (Eg. Nov 26, 2018).
3. For the cell use Excel Function to created current date (=(TODAY)).
4.  Create a Selenium script to read the data formatted above cells.

Note: Using 'String' variable type to read the cell data (Eg. String strStartdate)

Issue:
The data read as =(TODAY) instead of reading the actual date.

## Environment

OS:  10
Browser:  Chrome
Browser version:  Version 70
Browser Driver version: 
Language Bindings version:  JAVA jdk 1.8, 
Selenium Grid version (if applicable):   NA

![selenium_issue](https://user-images.githubusercontent.com/7704253/49003139-5c868980-f187-11e8-8c40-6de11a8b5838.jpg)

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
