### ISSUE TITLE
RegistrationRequest's fromJson ignores customized GridNodeConfiguration

### ISSUE THREAD

**Issue by matthewdoerksen** [SeleniumHQ/selenium#6691]
## 🐛 Bug Report

When converting a test object to/from JSON the GridNodeConfiguration (which is exported as "configuration") fails to be read back in and added to the re-built node. 

## To Reproduce

Simply export a customized RegistrationRequest (e.g. using a custom proxy class) as JSON and use RegistrationRequest.fromJson(Map<String, Object> raw) to attempt to deserialize a GridNodeConfiguration that has been customized - it will not be present in the new RegistrationRequest.

## Fix

Two possible options based on an instanceof check:
1)
If "configuration" is an instanceof GridNodeConfiguration, cast and pass it to the constructor of RegistrationRequest.
2) Assign request.configuration the value (cast to GridNodeConfiguration).

## Environment

OS: N/A
Browser: N/A
Browser version: N/A
Browser Driver version: N/A
Language Bindings version: Java 3.141.59
Selenium Grid version (if applicable): N/A

**Comment by diemol** [comment]
Hi @matthewdoerksen,

Could you please provide a code snippet or a GitHub project link to reproduce this issue? I normally work with customised proxies and I have not seen this behaviour. 
Perhaps I don't understand completely what the issue is, therefore with some code example it will be easier to do something about it.

**Comment by diemol** [comment]
I missed somehow the [test](https://github.com/SeleniumHQ/selenium/pull/6692#issuecomment-444043299) you provided in #6692. I am able to reproduce the issue with it.  

I think we can merge #6692 to have correctness in the code, since it solves the issue. Nevertheless, it is very unlikely that we will release a new version Selenium 3.x with that fix, we targeted 3.141.59 as the last one of the 3.x series, and this isn't a critical bug affecting lots of users.

Thanks for taking the time to report this @matthewdoerksen

**Comment by matthewdoerksen** [comment]
Thank you @diemol, I appreciate it.
