### ISSUE TITLE
Unable to write to Sharepoint people picker 

### ISSUE THREAD

**Issue by rashmighub** [SeleniumHQ/selenium#6695]
Hi, 
I am unable to write to/select people selector's objects/controls for Info-path form called in SharePoint
Online. Here is the html code for this field "<spanid="Approver_cbd8f8ed-e6b5-4e65-b534-9ce38c8ceec4_$ClientPeoplePicker_InitialHelpText" class="sp-peoplepicker-initialHelpText ms-helperText" style="display: inline;">Enter a name or email address...</span>". 

People Picker - The People Picker control is a central component of SharePoint Server 2013. The control is connected to a repository so that you can find and select users, groups, and claims to assign permissions in a site.

**Comment by rashmighub** [comment]
<span id="FirstApprover_cbd8f8ed-e6b5-4e65-b534-9ce38c8ceec4_$ClientPeoplePicker_InitialHelpText" class="sp-peoplepicker-initialHelpText ms-helperText" style="display: inline;">Enter a name or email address...</span>

**Comment by lmtierney** [comment]
Please do not remove the new issue templates as they are there for a reason.

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
