### ISSUE TITLE
Selenium ie driver - open browser in private mode

### ISSUE THREAD

**Issue by omer11121** [SeleniumHQ/selenium#6713]
Today's solutions to open the IE browser in private mode all includes changing the registry "TabProcGrowth".
For security reasons, not all the users can make this change.
You can see here: https://support.microsoft.com/en-us/help/3136268/can-t-print-from-the-web-if-you-run-internet-explorer-11-as-another-us
In the "More information" section Microsoft are saying it will reduce security.

From what i know there is a simple way to open the browser in private mode, just open the process with the argument of private mode.

Thanks,
Omer

**Comment by jimevans** [comment]
The introduction of so-called “Loosely Coupled IE” introduced by Microsoft in IE 7 means that when you use the Windows `CreateProcess` API function to launch Internet Explorer, the process that gets started may not be the process that actually hosts the browser content. IE can detect that another process is running and transfer control over to it, with no notification of which process is actually used. The registry change is required so that when the process is created by the driver, it is _forced_ to be the same process used by the browser itself. It is regrettable, though understandable, that many corporate IT departments restrict users from modifying the registry in this way; however, there is no other way to force IE to behave the way the driver needs when launched via `CreateProcess` without the modification. So, no, there is not “a simple way to open the browser in private mode” without it.
