### ISSUE TITLE
Selenium IE driver - Working with local DLL (IEDriver.dll)

### ISSUE THREAD

**Issue by omer11121** [SeleniumHQ/selenium#6714]
Today the selenium IE driver is working with tmp files that he is creating and then loading them from the local temp folder.
For security reasons in some computers the option to run unknown DLLs(including tmp files) is blocked.

My suggestion is to add a parameter to give the option to work with the DLL (IEDriver.dll).
In my project i had to change the source code and re-compile.
The changes I made:

hard coded in the LoadLibrary() function the "fileName" parameter to be "IEDriver.dll".
Removed the section where the tmp files are deleted after use.
You can see the changes in the attached files:
![iedriver1](https://user-images.githubusercontent.com/44057000/49339174-a3b4c480-f636-11e8-8590-d265840b2972.png)
![iedriver2](https://user-images.githubusercontent.com/44057000/49339175-a3b4c480-f636-11e8-8566-c80f2e20e693.png)

**Comment by jimevans** [comment]
Help me understand how the prevention of loading the dll through `LoadLibrary` is accomplished. Is it because the driver is attempting to load the library through the TEMP directory? Is it because the library has a random name when extracted from the executable resources? Is it a combination? Is it some other mechanism? 

If it’s because of the TEMP directory location, you can mitigate that by using the `/extract-path` command line switch. The IE driver has had this functionality for years, and a full description of its use can be seen by typing `IEDriverServer.exe /?`.

If it’s because the name is random, please note that the driver extracts first to `IEDriver.tmp`, and only uses the random name if that file already exists. If the system is preventing loading based on a whitelist of file names, adding `IEDriver.tmp` to the whitelist should resolve the issue.

**Comment by jimevans** [comment]
No response from reporter. Closing.

**Comment by omer11121** [comment]
Hi,
Sorry for not responding.
Let me explain the issue:
We are running the selenium in hardened environment and because of that the exe "rundll32" is blocked from security reasons.
When I am loading dynamically DLL's the exe "rundll32" is getting called(which is blocked in the app locker).
So thats my problem to load temp files dynamically, I know it might be edge event but it could be really helpful to add support for that case.

Thanks,
Omer

**Comment by jimevans** [comment]
As you’ve seen from the source code, the executable doesn’t call `rundll32.exe` to load the driver library, it calls the Windows `LoadLibrary` API, which does still work in your environment, as shown by your own modifications. So once again, I’ll ask for clarification once again.

Is it the that the dll is extracted to the temp directory the item that causes the issue? If so, there’s a solution for that (use the `/extract-path` switch on the command line to `IEDriverServer.exe` to specify a directory other than the temp directory).

Is it that the file is named a random name? There’s a solution for that (current versions extract the embedded dll to the name `IEDriver.dll` first if it doesn’t exist in the target directory before resorting to a randomized name).

Other than changing the code, you’ve not indicated a willingness to try the other solutions already available to you. Can you do that and report back with your findings please?

**Comment by omer11121** [comment]
No the problem occurs when loading the temp files.
We have investigated the issue with procmon and we saw that windows is using rundll32.exe when it is loading the DLL's dynamically.
So the first solution is not related to the problem, about the second solution I doubt it will work because the DLL still will be loaded dynamically. 
But i will test the second option and get back to you.
Thanks

**Comment by jimevans** [comment]
If it is using rundll32.exe to load the library when executed from the temp directory, then it will use rundll32 every time LoadLibrary is called, even with your modified code, so I am skeptical that solution will work either.
