### ISSUE TITLE
Add ability to control the mouse wheel with ActionChains class

### ISSUE THREAD

**Issue by ouam** [SeleniumHQ/selenium#6729]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

## Motivation

Please outline the motivation for the proposal.

## Example

Please provide an example for how this feature would be used.

**Comment by ouam** [comment]
Hello,

I couldn't find a way of controlling the mouse wheel event with the ActionChains class hence the feature proposal.
I don't know if there is a fundamental reason why the wheel scroll event is not part of the class but it would be great to be able to control the wheel scroll with the keyword 'scroll'.
I have used other python library which control the mouse wheel but my issue is that I need the scroll event to work in headless mode and so far all the ones I have tried use screen positioning (which is not available in  headless mode).
Could the button '4' be used to control the mouse wheel?

Regards,
Sylvain

**Comment by p0deje** [comment]
Mouse wheel controls are not available in Selenium because they are not the part of [WebDriver specification](https://w3c.github.io/webdriver). I believe it has been discussed in the working group, but I can recommend proposing to add such an API to the next version of specifcation. Once it gets there, it will be implemented by Selenium and browser drivers too.

You can propose it using https://github.com/w3c/webdriver/issues.
