### ISSUE TITLE
Cannot set cookies before navigating to page.

### ISSUE THREAD

**Issue by briz88** [SeleniumHQ/selenium#6775]
## 🐛 Bug Report

Cookie cannot be set before navigating to a page.
org.openqa.selenium.InvalidCookieDomainException: Document is cookie-averse  is thrown.

navigating to the page before setting the cookie defeats the purpose of trying to set cookies.
also navigating, set the cookie and then re-navigating is only extending the execution time.
<

## To Reproduce
1.have valid cookie
2.create a new driver
3.try to set the cookie

## Expected behavior

cookie is set

## Test script or set of commands reproducing this issue

Cookie ck = read cookie from file

@BeforeClass
public void setUp() {
    driver = new FirefoxDriver();
    driver.driver.manage().addCookie(ck);
}

## Environment
These are irrelevant as this most likely does depend on any of the below, but here you go anyway 
OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by lmtierney** [comment]
This is by design according to the [W3C WebDriver Specification](https://www.w3.org/TR/webdriver1/#add-cookie). Cookies can only be set on the current domain. Since you aren't at a domain, you cannot add a cookie.

See also [the html standard spec for cookie-adverse Document](https://html.spec.whatwg.org/#cookie-averse-document-object)
