### ISSUE TITLE
IE11 does not support new tab in selenium webdriver 

### ISSUE THREAD

**Issue by ShanthiAthi** [SeleniumHQ/selenium#679]
Hi,

  I want to open url in new tab in IE11.
This is the scenario

1. open the one application url [Google page] in new window and open another url [facebook] in new tab. But load facebook in first tab i.e on google page

WebDriver driver = new InternetExplorerDriver(ieCapabilities);
driver.manage().window().maximize();
driver.get("https://google.com/");

driver.findElement(By.cssSelector("Body")).sendKeys(Keys.CONTROL + "t");//opens new tab

driver.get("https://facebook.com/"); 

Pls help me. How to shift control to new tab so that the facebook link opens in that new tab.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
