### ISSUE TITLE
make IHasCapabilitiesDictionary as public interface

### ISSUE THREAD

**Issue by sroei** [SeleniumHQ/selenium#6804]
### IHasCapabilitiesDictionary interface is an internal interface. this cause a null reference exception when implementing ICapabilities interface

the following code (line 1108, RemoteWebDriver)
`IHasCapabilitiesDictionary capabilitiesObject = legacyCapabilities as IHasCapabilitiesDictionary;`

tries to cast ICapabilities as IHasCapabilitiesDictionary which cannot be done because this interface is internal.

please, either make it public or enforce the capabilities dictionary under ICapabilities interface and remove the IHasCapabilitiesDictionary casting

note: this can be done by override `GetLegacyCapabilitiesDictionary` & `GetCapabilitiesDictionary`, but I still consider this as an issue

**Comment by jimevans** [comment]
@sroei Help me understand why you feel you need this interface and why you’re implementing `IHasCapabilities`. The intention is for `IHasCapabilitiesDictionary` to be a transitional interface, and is one reason it was not made public to begin with. We can, of course, fix the NullReferenceException, but that would not resolve the root cause of the issue.

If it’s to get around the deprecation of `DesiredCapabilities` in any way, then no, that won’t be happening. There is already little reason in the .NET bindings to attempt to manipulate the payload in the Options classes provided for individual browsers (`InternetExplorerOptions`, `FirefoxOptions`, `ChromeOptions`, etc.). In the main, the structures already exist to duplicate nearly any use case that manipulating raw capabilities would require. Downstream projects and cloud providers that wish to support .NET clients going forward will need to step up their efforts to be compliant with the W3C WebDriver Specification.

**Comment by sroei** [comment]
Hi, thank you for your reply.

First, yes it is to bypass the deprecation, but not to manipulate the payload in the existing options classes - as you said, they already provide the functionallity to manipulate raw capabilities

Second, I didn't understand it is a transitional interface, could not find a mention for it as it is mentioned on the virtual methods.

My use case is as follow:
1. I have implemented windows driver based on w3c (for windows applications and apps)
2. I am implementing a new client based on Selenium interfaces and RemoteWebDriver to keep unified standard with our web automation and to use it with our grid

When implementing a new options class (WinAppOptions) baesd on the new approach and implementing ICapabilities to avoid deprecation, the remote web driver still looking for that internal interface and throwing null reference, unless override capabilities methods as mentioned before (which is also transitional...)

It just feel like hacking rather than standard development. I was expecting that implement ICapabilities will be enough when you want to implement a new client.

**Comment by jimevans** [comment]
If you’re implementing a new options class derived from `DriverOptions`, then current sources allow you to call the `GenerateDesiredCapabilities` from your `ToCapabilities` implementation. This will return an `IWritableCapabilities` object that you can then modify and return. To mimic existing implementations, you should return the result of the `AsReadOnly` method. The actual implementation should look something like this:

    public override ICapabilities ToCapabilities()
    {
        IWritableCapabilities caps = this.GenerateDesiredCapabilities(true);

        // Modify the capabilities as required here
        // caps.SetCapability(name, value);

        return caps.AsReadOnly();
    }

In the future, I may provide a slightly cleaner implementation where `ToCapabilities` is not fully abstract, but has a base implementation that does the bulk of this for you, but the current overrides won’t be invalid in that case. When that happens, appropriate protected methods will be marked deprecated for at least a few releases before being removed.

**Comment by sroei** [comment]
Great :)
Thank you.
What you sent me looks much cleaner and I will keep it up with future changes
