### ISSUE TITLE
ServicedSession cause OutofMemory

### ISSUE THREAD

**Issue by xiaospider** [SeleniumHQ/selenium#6808]
## 🐛 Bug Report
Use selenium standalone server to create remote webdriver, open and close website, close the webdriver continuously. After about 6 days, the standalone server  OutOfMemory and coredump.

There are about 520000 ServicedSession object referenced by JMXBean, that caused the OOM.
![oom](https://user-images.githubusercontent.com/4019176/50631642-0f64b700-0f80-11e9-8885-70e05e2fc934.png)

I created webdriver with following java code.
```
RemoteWebDriver driver = null;
	    URL seleniumHub = new URL("http://" + hub + ":4444/wd/hub");
	    tlog.logp(Level.INFO, CLASS, METHOD, "Hub URL: " + hub);
	    
	    while(driver == null) {
	        count++;
	        try {
	            driver = new RemoteWebDriver(seleniumHub, capabilities);
	        } catch(Exception ex) {
	          
	                throw ex;
	         }
	    }
```

From the sourcecode of org.openqa.selenium.grid.session.remote.ServicedSession , I can see that it's registered in to JMX server in the constructor.

```
 public ServicedSession(
      DriverService service,
      Dialect downstream,
      Dialect upstream,
      SessionCodec codec,
      SessionId id,
      Map<String, Object> capabilities) {
    super(downstream, upstream, codec, id, capabilities);

    this.service = service;

    new JMXHelper().register(this);
}
```

But it's not unregistered in the stop function.
```
public void stop() {
    // Try and kill the running session. Both W3C and OSS use the same quit endpoint
    try {
      HttpRequest request = new HttpRequest(HttpMethod.DELETE, "/session/" + getId());
      HttpResponse ignored = new HttpResponse();
      execute(request, ignored);
    } catch (IOException e) {
      // This is fine.
    }

    service.stop();
}
```

## Environment

OS: Ubuntu 16.0.4
Browser:  Firefox 
Browser version: 60.4.0ESR
Browser Driver version: GeckoDriver 0.23 
Language Bindings version: Java 3.141.59
Selenium Grid version (if applicable): 3.141.59 standalone server

**Comment by cgoldberg** [comment]
in your example code, you create webdrivers but never quit them...  so eventually you run out of memory.  That seems like the correct expected behavior.

**Comment by xiaospider** [comment]
I already quit webdriver every time with following code.
```
SessionId sessionId = null;
		try {
			sessionId = driver.getSessionId();
			driver.quit();
		}catch (WebDriverException t) {
			// in case of hung Firefox killed, the driver session in Selenium server has to be cleaned with rest API
			HttpURLConnection conn = null;
			try {				
				if (sessionId != null) {
					String url = "http://" + this.hub + ":4444/wd/hub/session/" + sessionId.toString();
					final URL httpURL = new URL(url);
					conn = (HttpURLConnection) httpURL.openConnection();
					conn.setRequestMethod("DELETE");
					conn.connect();
					int responseCode = conn.getResponseCode();
					if (responseCode == 200) {
						tlog.logp(Level.INFO, CLASS, METHOD, 
						        logMsgPrefix + "Firefox Driver Session: " + sessionId + " is deleted successfully");
					} else {
						tlog.logp(Level.WARNING, CLASS, METHOD, 
						        logMsgPrefix + "Deleting Firefox DriverSession: " + sessionId + " failed, Selenium server returns error code: " + responseCode);
					}
				}
			} catch (Exception e) {
				tlog.logp(Level.SEVERE, CLASS, METHOD, 
				        logMsgPrefix + "Unexpected exception in deleting Firefox driver session: " + sessionId + ", error: " + e.getMessage());
			} finally {
				if (conn != null) {
					conn.disconnect();
				}
			}
		}
```

**Comment by diemol** [comment]
@xiaospider could you please share with us your use case? From the shared code one can just conclude what @cgoldberg says, it just looks like you start RemoteWebDriver instances until the machine will run out of memory. 

In addition to that, please share the complete code and just not segments of it, so we can give you hints on how to avoid the behaviour.

And just one more thing; since this **does not look like a common use case** and the Selenium Grid 3.x won't be released anymore - due to the fact that it is being reimplemented from scratch for Selenium 4.0 -, it is unlikely that there will be any actions taken in the code for the Standalone server.

**Comment by cgoldberg** [comment]
@xiaospider your issue report describes the use case as "create remote webdriver, open and close website, close the webdriver continuously" ... However, your example code does not do that.  We have requested valid reproduction code multiple times.  Since you can't provide the code or clearly describe the issue, there is nothing we can fix or help you with... sorry.

**Comment by xiaospider** [comment]
@cgoldberg 
The code is one iteration of "create remote webdriver, open and close website, close the webdriver".
I have a task scheduler to run this logic continuously, I didn't put this part code here. But you can just add a while loop and sleep 5 seconds every  iteration.
