### ISSUE TITLE
selenium don't running at spark cluster mode - Failed to open connection to "session" message bus: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11 site:stackoverflow.com

### ISSUE THREAD

**Issue by saseo90** [SeleniumHQ/selenium#6822]
selenium don't running at spark cluster mode 
Version: centos 7
Platform: LINUX
Firefox: 60.2.2
Selenium: 3.14.1
geckodriver 0.21.0

I don't no understand
selenium do good running at Yarn Cluster Mode.
but selenium don't running at spark cluster mode.

![stop2](https://user-images.githubusercontent.com/21356484/50772016-a5297a80-12cf-11e9-9820-de2ba80864e5.png)
![stop](https://user-images.githubusercontent.com/21356484/50772017-a5297a80-12cf-11e9-94cf-5e23f4d17a0b.png)

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
