### ISSUE TITLE
manage().deleteAllCookies() does not work for on IE

### ISSUE THREAD

**Issue by khanh-nguyen** [SeleniumHQ/selenium#683]
I have some tests written in NodeJS that require to clean cookie to reproduce login scenario. They work well with chrome and firefox but fail on IE (Windows 7, IE 10). 

```
yield driver.manage().deleteAllCookies();
yield driver.get(httpsUrl);
// login here
```
I saw a related discussion [here](https://code.google.com/p/selenium/issues/detail?id=5101). Is it still a known bug with IE driver?

Thanks,

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
