### ISSUE TITLE
Selenium Python test failed with this error: WebDriverException

### ISSUE THREAD

**Issue by contorax** [SeleniumHQ/selenium#6844]
I run my code on MacOS 10.14.1

the test is for Safari browser, it opens Safari and navigates to the url but then immediately closes and I got error. This is my code:
```
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest
import time
import re
from friends import Friends


class TestAddGroup(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Safari()
        self.driver.implicitly_wait(30)
        self.base_url = "https://www.team-united.com/"
        self.verificationErrors = []
        self.accept_next_alert = True
```
and I'm getting this error:

```
selenium.common.exceptions.WebDriverException: Message:

../../../.local/share/virtualenvs/python_my_address_book-7a6KC1M-/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py:242: WebDriverException
```

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
