### ISSUE TITLE
Performance degradation in frame switch method

### ISSUE THREAD

**Issue by dimand58** [SeleniumHQ/selenium#685]
Hi,

We are detect some performance degradation for often calls of driver.switchTo().frame("someFrameIdOrName") on same page. Each switch is slower then previous. This problem is actual for 2.46 version, after https://github.com/SeleniumHQ/selenium/commit/98161bc5c743918318e81be04f62cf37e49cd971 I guess.

IEDriverServer 2.46 x32
Internet Explorer 8
JDK 7 x64

P.S. For 2.45 or driver.switchTo().frame(someFrameAsWebElement) is OK

**Comment by ddavison** [comment]
for the code: 
```java
@Test
    public void test685() {
        driver.get("https://rawgit.com/SeleniumHQ/selenium/master/common/src/web/frame_switching_tests/deletingFrame.html");

        howLong();
        howLong();
        howLong();
        howLong();
        howLong();
        howLong();
    }

    private void howLong() {
        long start = System.currentTimeMillis();
        driver.switchTo().frame(driver.findElement(By.id("iframe1")));
        driver.switchTo().defaultContent();
        long end = System.currentTimeMillis();
        System.out.println("Switching took: " + (end-start) + "ms");
    }
```

Couldn't reproduce in Chrome, Firefox, or Safari.

Could somebody check IE with the above code?  I get consistent times.

```
Switching took: 13ms
Switching took: 13ms
Switching took: 13ms
Switching took: 17ms
...
```

**Comment by lukeis** [comment]
I don't believe we will do anything about this, as switching to frame by id or name is essentially deprecated because remote end servers are not required to implement it according to the spec. 

Meaning the commit referenced is required since there is no direct API call to new drivers for performing this switch. (New drivers being Marionette for Firefox and the future Edge one provided by Microsoft)

I would recommend using only switch to frame by webelement or index in your code.
