### ISSUE TITLE
I can't change browser.link.open_newwindow pref if I need use profile

### ISSUE THREAD

**Issue by azapevalov** [SeleniumHQ/selenium#6865]
## 💥 Regression Report

Hi.

**Meta -**

OS: MacOS X, Linux, Windows

Selenium Version: 3.141.59

Browser: Firefox (geckodriver)

Browser Version: 64,63,62,61,60 (64 bits)

**Expected Behavior**

**_browser.link.open_newwindow_** preference always set to 3

**Actual Behavior**
Exception in thread "main" java.lang.IllegalArgumentException: Preference browser.link.open_newwindow may not be overridden: frozen value=2, requested value=3

**Scenario:**
`FirefoxProfile profile = new FirefoxProfile();
FirefoxOptions options = new FirefoxOptions().setProfile(profile);
options.addPreference("browser.link.open_newwindow", 3)
 //or options.addPreference("browser.link.open_newwindow", 1)
desiredCapabilities.merge(options);
WebDriver driver1 = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), desiredCapabilities);`

but if I send custom profile with "browser.link.open_newwindow" = 3 in pref.js, so I don't get exception. I get browser with "browser.link.open_newwindow" = 2
Why???

**Comment by barancev** [comment]
Don't create a profile at all, set preferences in options directly:
```
FirefoxOptions options = new FirefoxOptions().addPreference("browser.link.open_newwindow", 3);
WebDriver driver1 = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), options);
```
Does it work?

**Comment by azapevalov** [comment]
Yes, it is
But I need profile, for send extensions(Firefox) without a profile it is impossible to do

**Comment by barancev** [comment]
The issue will hardly be fixed, we're working on the new selenium server version that should allow installation of Firefox extensions on the fly, and I believe FirefoxProfile will be deprecated eventually.

But I'll tell you a secret workaround :)

1) Create a file, say, `prefs.json`, copy content of https://github.com/SeleniumHQ/selenium/blob/master/third_party/js/selenium/webdriver.json to this file and move required preferences from the `frozen` section to the `mutable` one.
2) Override a secret method in `FirefoxProfile` (substitute your actual class instead of `MyTest`):
```
    FirefoxProfile profile = new FirefoxProfile() {
      protected Reader onlyOverrideThisIfYouKnowWhatYouAreDoing() {
        URL resource = Resources.getResource(MyTest.class, "prefs.json");
        try {
          return new InputStreamReader(resource.openStream());
        } catch (IOException e) {
          throw new WebDriverException(e);
        }
      }
    };
```
... and you're done, the preference is not frozen anymore.
