### ISSUE TITLE
Update our HttpClient to support streaming

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#6868]
This will allow us to avoid having to hold the entire request in memory when acting as a proxy.

**Comment by shs96c** [comment]
Ultimately, we want to better support the Java 11 HttpClient, so some sort of interface that takes a `Supplier<InputStream>` for the body is the way to go. Probably.

**Comment by virenv** [comment]
@shs96c : Simon: Could you add more details or point to some document to get more details here?

**Comment by shs96c** [comment]
Apologies for the slow reply. Details? Of course! 

Our HttpClient implementation is fine in most cases, but it's not great when what we want to do is to stream from one request into another (for example, when acting as a reverse-proxy). Ideally, this would be implemented as something like:

```java
public HttpResponse forward(HttpRequest request) {
  HttpRequest toUpstream = new HttpRequest(request.getMethod(), "/rewritten");
  toUpstream.setContent(() -> request.consumeContent());

  // or perhaps
  toUpsteam.body(() -> request.getBody());

  // And then execute the request with an HttpClient
}
```

That is, it would be useful if we could use a `Supplier<InputStream>` to write the body of the request. This would bring us a lot closer to what the [Java 11 HttpClient](https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpClient.html) does.

Ultimately, it would be nice to be able to drop the requirement to use OkHttp, and instead use the JRE's own http client implementation, so the steps we make in this direction are advantageous.

**Comment by virenv** [comment]
@shs96c : Thank you for the update. I want to contribute this piece of work. At this moment, I am just a beginner in Open source contributions. Let me take a look at it and add my notes here for your validation.

**Comment by virenv** [comment]
@shs96c : I took a look around in the code.  I have following questions

1. It seems that we want to update HttpRequest and HttpResponse classes to support streaming as opposed to enable HttpClient to support streaming. Please correct me if I am wrong. The reason I am asking this is because, at the end we have to convert the HttpRequest and HttpResponse objects to the OkHttp corresponding data structure (HttpUrl.Builder) to execute. Ref code file: [here](https://github.com/SeleniumHQ/selenium/blob/dce76b5aa86184f4f0a629139b6406a9752cce74/java/client/src/org/openqa/selenium/remote/internal/OkHttpClient.java#L51)

2. As the task description suggests, we want to avoid having a copy of request/response when we just want to act as pass through (proxy). In the code you suggested above, we will anyway be making a copy. Could you please share more details around the memory consumption here? 

3. Further taking the example of code here in the [ReverseProxyHandler class](https://github.com/SeleniumHQ/selenium/blob/9d8278e1742372a63cdfe3a2ec2953f47d577a30/java/server/src/org/openqa/selenium/grid/web/ReverseProxyHandler.java#L54), here we do extra processing to a request to remove headers which fall in the ignored list of headers (Line 63). We also want to add additional headers like "Connection" header line 73. In a nutshell we may want to modify requests/response as we forward them in proxy handlers. This would not enable us to have direct streaming of request/response contents. Will stream support be still that much valid?

**Comment by shs96c** [comment]
This is the kind of thing I was driving towards: 1b253f985168c22f6df6f03a4f6e45d92ec02b88 Right now, we're using OkHttp, and the underlying abstractions don't support streaming this way, but the JRE HttpServer, HttpURLConnection, the JEE HttpServletRequest and Response, and Netty all do.

We landed this fix, but if you can think of anyway of making it more efficient, please let me know. In particular, I really don't like having to memoize the content: I do wonder whether it's possible to change our code to only read a body once.
