### ISSUE TITLE
Cannot gracefully exit a page that raises a beforeunload alert.

### ISSUE THREAD

**Issue by brianchin** [SeleniumHQ/selenium#690]
I'm working with the python WebDriver implementation. Our webapp raises a dialog in a beforeunload event listener by assigning to event.returnValue, as is part of the spec. However, it does not appear that there is any way of gracefully quitting/closing the webdriver after that point. Is there any way to tell get()/close()/quit() to expect a dialog, and be able to actually dismiss it at the appropriate time?

My browser platform is Chrome.

**Comment by ddavison** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
