### ISSUE TITLE
execute_async_script timeout but execut_script works?

### ISSUE THREAD

**Issue by anthonypan08** [SeleniumHQ/selenium#6905]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

The following code works exactly as I intended. The web driver will scroll to the bottom of the page

```
while new_height != last_height:
            new_height = last_height
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            last_height = driver.execute_script("return document.body.scrollHeight")
            time.sleep(1)
```

In an attempt to get rid of the sleeping time, I thought it would be a good idea to use execute_async_script and just block until the script finishes running. However, the code below timeout and said something about never receiving a result for async script

```
while new_height != last_height:
            new_height = last_height
            driver.execute_async_script("window.scrollTo(0, document.body.scrollHeight);")
            last_height = driver.execute_async_script("return document.body.scrollHeight")
```
Below is the image of the error
![image](https://user-images.githubusercontent.com/20074651/52101149-4bebf880-25a8-11e9-96e9-aad5f2c432dd.png)

**Comment by p0deje** [comment]
The script you execute has to execute the callback to let Selenium know it finished execution. Since you don't call it, it times out. Please see the difference between `execute_script` and `execute_async_script`. A thorough explanation can be found in [javadoc](http://static.javadoc.io/org.seleniumhq.selenium/selenium-api/2.50.1/org/openqa/selenium/JavascriptExecutor.html#executeAsyncScript-java.lang.String-java.lang.Object...-) and [stackoverflow](https://stackoverflow.com/a/28057738/479558).
