### ISSUE TITLE
Instantiating a ChromeDriver doesn't work on .NET Core on Mac

### ISSUE THREAD

**Issue by nadvolod** [SeleniumHQ/selenium#6928]
## 🐛 Bug Report
I am attempting to use Visual Studio for Mac and I can't instantiate a ChromeDriver, or any driver for that matter. I get this exception even though the driver is clearly in the directory:

_Test method Tests.UnitTest1.TestMethod1 threw exception: 
OpenQA.Selenium.DriverServiceNotFoundException: The file /Users/nikolay/Downloads/demo-csharp-master/SauceExamples/Web.Tests/Tests/bin/Debug/netcoreapp2.1/chromedriver does not exist. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html_ 

## To Reproduce

Detailed steps to reproduce the behavior:
1. Download [this solution](https://github.com/nadvolod/dotnet-core) that has a simple test that tries to instantiate a ChromeDriver()
2. Try to run TestMethod1() on Mac, it doesn't work and we get error
_Test method Tests.UnitTest1.TestMethod1 threw exception: 
OpenQA.Selenium.DriverServiceNotFoundException_

## Expected behavior

I tried the same code on Windows in Visual Studio and it worked just fine. I expect that this will start a Chrome browser and open the url.
chromedriver.exe is here in my folder: http://prntscr.com/mjtnlu

## Test script or set of commands reproducing this issue

https://github.com/nadvolod/dotnet-core

## Environment

OS: MacOS Mojave
Browser: Chrome
Browser version: latest
Browser Driver version: ChromeDriver 2.45.0
Language Bindings version: C# 3.141.0 
Image of all versions: http://prntscr.com/mjtoeu

**Comment by jimevans** [comment]
From where, exactly, did you download the ChromeDriver executable? It looks like you’re attempting to use the Windows-specific chromedriver.exe, rather than the MacOS native executable.

Note carefully that if you’re attempting to use the chromedriver executable by including a reference to a NuGet package, there is no guarantee that the proper platform-specific executable is included in the package. As far as I know, there are no NuGet packages for any of the browser driver executables (IEDriverServer.exe, geckodriver.exe, chromedriver.exe) that are provides or maintained by the teams that produce those executables. If you are attempting to use the chromedriver executable from such a package, please download the correct executable for your platform directly from http://chromedriver.storage.googleapis.com/index.html and see if that resolves the issue.

**Comment by nadvolod** [comment]
BINGO! That was exactly the problem. I was using Nuget ChromeDriver. Thanks for your help Jim. Truly appreciate your time man.
This issue may be closed.

**Comment by shishirshettygit** [comment]
@nadvolod Did you have ChromeDriver.exe and ChromeDriver(mac executable) both in the same directory?
