### ISSUE TITLE
Deploy location 'cause few issues continue to issue #681

### ISSUE THREAD

**Issue by Shnitzelil** [SeleniumHQ/selenium#694]
Hey,

I'm not trying to deploy Selenium, somehow the during building my project (not Selenium project) selenium dependency caused the error showed on issue #681.

Thanks

**Comment by ddavison** [comment]
I'm quoting @lukeis here -

> Going to close until you describe completely what you are doing (and include your Pom file)

he closed your issue because you didn't provide enough details, and in this issue you are not providing enough either.  "during building"  how are you building?  eclipse? Maven resolve? compiling Selenium? compiling java code that uses selenium? 

These are things you should bring up with the [selenium users group](https://groups.google.com/forum/#!forum/selenium-users).  The issues here on GitHub should be reserved for issues with vetted material showing that Selenium has a bug.

Please bring your issue up with the [selenium users group](https://groups.google.com/forum/#!forum/selenium-users) :+1:

**Comment by Shnitzelil** [comment]
Seriously, you're keep closing my issue? did any of you thought to write me what specifically he needs to understand the issue?
Before you close any other issues, I suggest you to ask what you need to know.

TIA

**Comment by ddavison** [comment]
As I said....

>  "during building" how are you building? eclipse? Maven resolve? compiling Selenium? compiling java code that uses selenium?

And as lukeis said:

> ... include your pom file.
