### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by ulist** [SeleniumHQ/selenium#6959]
I tried selenium on android for forgetting reason whatever it was create backup files or something in /tmp and my device storage losted why?
``
https://youtu.be/SClyNqZRhgs
``

**Comment by diemol** [comment]
This is a question rather than an issue, and not even sure that this is related to Selenium. 

If you consider that it is still related to Selenium, please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.

**Comment by ulist** [comment]
I do my best 🕵
