### ISSUE TITLE
support Console command :screenshot

### ISSUE THREAD

**Issue by SS024** [SeleniumHQ/selenium#6969]
## 🚀 Feature Proposal

propose to support webconsole :screenshot command. this command can run within FF browser, but when tried the same in selenium, it reports "elenium.common.exceptions.JavascriptException: Message: SyntaxError: expected expression, got ':'" with command below:
 driver.execute_script(":screenshot --selector '.css1' --filename 'test.png'")

## Motivation

very useful for automation, for lazy load web content(image, text...) and save it(with selector) as picture instead of saving whole page. 

## Example

Please provide an example for how this feature would be used.

**Comment by jimevans** [comment]
@SS024 Help me understand the use case here, as I don’t understand what the command is doing above the built-in Selenium screenshot commands. If the advantage you’re seeking is taking a screenshot of a single element instead of a whole page, Selenium already supports that (cast `WebElement` to `TakesScreenshot` and that should work for drivers that support it like Firefox and IE).

**Comment by diemol** [comment]
Closing as we didn't get a reply from the OP and also the feature already exists.
