### ISSUE TITLE
How to select a SSL certificate  using Selenium web Driver?

### ISSUE THREAD

**Issue by cesaregerbino** [SeleniumHQ/selenium#698]
I’m using Selenium Web Driver on Windows 7 using Java.

I need to test a web application and I’ve to use a SSL certificate to enter.

I don’t know how to select the right certificate to use my application.

I’m in this situation now
![sslcertificates-1](https://cloud.githubusercontent.com/assets/4707083/8281998/8de33af8-18ed-11e5-93ca-2f5246ccb6c1.PNG)

(NOTE: I’ve put also the AutoIt window to add some info …..but it doesn't work ...)

I've tried several roads ..... using AutoIT, deifining and using a Firefox profile with only a single SSL cdertificate, ecc ... but the problem is still the same. The certificates dialog, that is a modal one, come up and wait for a human interaction for the certificate selection. I've tried to search on the web but nothing to help me .... 

Any suggestions / help / samples / tutorials on this stuff?

Thank you very much in advance!!
 
Cesare

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
