### ISSUE TITLE
Invoke IE11 without alerts add-on- Webdriver 

### ISSUE THREAD

**Issue by sashidharkochi** [SeleniumHQ/selenium#6986]
## 💬 Questions and Help
Please suggest if we can open IE driver by excluding some of the IE Add-ons. With my current IE settings, application is opened in tool bar when I have IE add-on enabled(Alerts add-on). Applications are opening properly when I disable the add-on, Kindly help if we can open IE by excluding some of the add-ons.

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by jimevans** [comment]
Because IE does not have the concept of user profiles like other browsers do, the correct way to resolve this is to manually configure the browser as you need it before running Selenium code against it. The main reason is that there is no guarantee that the system could be reset to its initial state if something goes wrong, leaving the user’s machine in an unstable state.
