### ISSUE TITLE
IE sendKeys file selection not found sometimes

### ISSUE THREAD

**Issue by reinsch82** [SeleniumHQ/selenium#6991]
Unfortunately the repro involves a lot of retries with our testing framework

SendKeys triggers the opening of the file selection dialog. I assume when the system is a bit slower it doesn't find the "Alternate Modal Top Most" window (the seems the 2 threads involved here have a race condition).

"Alternate Modal Top Most" windows is only tried to find once, which means when the windows isn't there in the beginning it won't find it even with the retries on the UIA.

I'll follow up with a fix

OS: Windows 10 1809
Browser: IE
Browser Driver version: IEDriver 3.141.10
Language Bindings version: Java 3.141.159

**Comment by diemol** [comment]
@reinsch82 I am not a commiter of the IE bindings, but my first impression from this issue and the PR is to not accept it because there is not enough information to understand the issue, also there is no scenario to reproduce it and the PR does not have any tests to check if the issue is solved.

Could you please enrich the issue information (e.g. fill the template completely and don't delete it), so when the maintainer has time to check this, can actually provide good feedback?

**Comment by jimevans** [comment]
@diemol, I’ve been working with @reinsch82 offline on these issues. We’ve already done one PR in this area, and we’re working toward that on this one too
