### ISSUE TITLE
ExpectedConditions.elementToBeClicable() for Java not working as expected

### ISSUE THREAD

**Issue by IvanMarkovicIske** [SeleniumHQ/selenium#7003]
## 🐛 Bug Report

When using WebDriverWait(driver, timeout) to wait until expected condition ExpectedConditions.elementToBeClickable(...) is met, it looks like timeout is not applied. Method until() just executes without waiting for element to became clickable.

elementToBeClickable() documentation:
An expectation for checking an element is visible and **enabled** such that you can click it.

## To Reproduce

Please use below test script to reproduce.

## Expected behavior

Timeout should be applied and wait.until(...) would wait for 5 seconds, as declared in WebDriverWait constructor.

I have put one print at end of test to show actual duration of wait.

## Test script or set of commands reproducing this issue

    private static final String DRIVER_PROPERTY = "webdriver.chrome.driver";
    private static final String DRIVER_PATH = "/home/username/drivers/chromedriver";

    private static final String TEST_URL = "https://demos.telerik.com/kendo-ui/button/index";
    private static final String DISABLED_BUTTON = "//a[@id='primaryDisabledButton'][@aria-disabled='true'][contains(text(), 'Disabled Primary Button')]";

    @Test
    public void waitUntillOnDisabledButton() throws InterruptedException {

	System.setProperty(DRIVER_PROPERTY, DRIVER_PATH);

	WebDriver driver = new ChromeDriver();
	driver.get(TEST_URL);
	driver.manage().window().maximize();
	TimeUnit.SECONDS.sleep(3);

	WebElement disabledButton = driver.findElement(By.xpath(DISABLED_BUTTON));
	WebDriverWait wait = new WebDriverWait(driver, 5000l);

	long start = System.currentTimeMillis();
	wait.until(ExpectedConditions.elementToBeClickable(disabledButton));

	System.out.println(String.format("Waited %s miliseconds for element to be clickable (enabled)!",
		System.currentTimeMillis() - start));

	disabledButton.click();
    }

## Environment

OS: Linux Ubuntu 16.04
Browser: Chrome
Browser version: 72.0.3626.109 (64-bit)
Browser Driver version: ChromeDriver 2.46
Language Bindings version: 3.141.59

**Comment by virenv** [comment]
@IvanMarkovicIske : I tried your code and I got following response
**Waited 15 miliseconds for element to be clickable (enabled)!**

Which is correct response. The wait had to wait till the time the evaluated condition turns out to be true. Are you expecting that you should get 5 seconds as the wait time? 
All the wait in Selenium system are basically loops that continuously evaluate a condition after every few milliseconds (Polling time). The wait will wait at max till 5 seconds or will quit before 5 seconds if condition is met. I tried to explain this in one of my articles [here:](https://www.toolsqa.com/selenium-webdriver/advance-webdriver-waits/)

**Comment by IvanMarkovicIske** [comment]
As I understand my expected condition is that button becomes clickable. Per documentation and code, clickable means that button is not null and it's enabled... This button never becomes clickable (enabled) so I was expecting that after 5 seconds of waiting for it to becomes enabled, exception is thrown because it's still not clickable. 

Is my understanding wrong?

**Comment by virenv** [comment]
@IvanMarkovicIske : Sorry I had to remove my earlier comment. It was basically a misunderstanding of the issue from my side. I will try to break it down.

1. ExpectedConditions.elementToBeClickable just checks if element is visible and enabled. Webdriver spec: [https://www.w3.org/TR/webdriver/#is-element-enabled](url)
2. It may  turn out the above condition is met by an element but when we actually go to click the link, the action does not happen. In this case click is not happening because there is another element at the point where WebDriver is trying to click. 

That is why even after checking the elementToBeClickable condition we got the exception. I am not sure if this can be handled at the binding level but there seems to be an issue with the layout of the page. This is as per best of my understanding. I think let the experts comment on  this issue, that will bring more clarity.

**Comment by IvanMarkovicIske** [comment]
@virenv 

We should always get exception, because this button never becomes clickable. But I was expecting to get that exception after 5 seconds because that is the timeout provided. Web page in test script may not be the best example, but this is reproducible on other pages with disabled buttons.

**Comment by virenv** [comment]
@IvanMarkovicIske : The problem is that this control is not actually disabled in the terms of standard element properties. I think showing it as disabled is a CSS trick. As a result when we query the standard properties of the button we get that the element is visible and is enabled. That is the check that we do to determine that element is clickable. You can see it in the below code.

In these cases you will have to write custom wait code which can query attributes like class = k-primary k-button k-state-disabled or disabled="disabled". That is when you can determine the actual state of the button. This will be applicable to all custom styled controls that dont use standard properties.

The exception that you are getting is because para element is overlapping the button. Click event is being received by the para control. I think it is above button in Z order. I have added some code to you original code which will display the displayed, enabled state and bounding boxes that can help us visualize the issue.

`		System.setProperty("webdriver.chrome.driver", "D:\\JavaTools\\WebDriver\\ChromeDriver\\chromedriver.exe");

        WebDriver driver = new FirefoxDriver();
        driver.get(TEST_URL);
        driver.manage().window().maximize();
        TimeUnit.SECONDS.sleep(3);

        WebElement disabledButton = driver.findElement(By.xpath(DISABLED_BUTTON));
        WebDriverWait wait = new WebDriverWait(driver, 5000l);

        long start = System.currentTimeMillis();
        wait.until(ExpectedConditions.elementToBeClickable(disabledButton));

        System.out.println(String.format("Waited %s miliseconds for element to be clickable (enabled)!",
        	System.currentTimeMillis() - start));
        
        
        System.out.println("Is Button displayed " + disabledButton.isDisplayed());
        System.out.println("Is button enabled " + disabledButton.isEnabled());
        
        JavascriptExecutor executor = (JavascriptExecutor)driver;
        Object boundingBox = executor.executeScript("return arguments[0].getBoundingClientRect();", disabledButton);
        System.out.println("Bounding box of disabled button: " + boundingBox.toString());
        
        WebElement paraWebElement = driver.findElement(By.xpath("/html/body/div[2]/div[2]/div[2]/div/div/div[2]/p"));
        Object paraBoundingBox = executor.executeScript("return arguments[0].getBoundingClientRect();", paraWebElement);
        System.out.println("Bounding box of para control: " + paraBoundingBox.toString());
        
        disabledButton.click();`

**Comment by virenv** [comment]
@barancev @diemol : Can you please look into this issue. At present Selenium does not check **_isEnabled_** via a js atom. Is there a possibility to check for **_isEnabled_** via atom so that we can have complex logic to check for this property?

**Comment by barancev** [comment]
@virenv How will use of the atom help to resolve the issue?

**Comment by virenv** [comment]
@barancev : With atom we can implement more complex, most importantly custom, logic to check for multiple attributes. This can be different from what browser has implemented based on WebDriver standard. Please correct me if I have wrong understanding of atoms.

**Comment by barancev** [comment]
Yes, you're wrong. The atom implements the logic defined in W3C specification, as well as the executable drivers that often use atoms internally. If you want to change this behaviour please raise an issue on the specification https://github.com/w3c/webdriver/
