### ISSUE TITLE
Getting different behhaviour with @FindBy and by using driver.findElements

### ISSUE THREAD

**Issue by spawar20** [SeleniumHQ/selenium#7016]
I am getting size of list as 3,even if I remove a element from the list when I am using @FindBy annotation.

When I execute my code without @FindBy annotation I am getting correct list size as 2.

List has following elements:[Instructor,course,price]

package com.practise.testSuite;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.apache.commons.collections.collection.UnmodifiableCollection;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;

import com.google.common.collect.ImmutableCollection;

public class TestClass {

	static WebDriver driver;

	@FindBy(xpath = "//th")
	public List<WebElement> columns;

	List<WebElement> columnNames = new ArrayList<>();

	public void initMethod() {
		PageFactory.initElements(driver, this);
	}

	public List<WebElement> getColumns() {
		if(columns.getClass().getName().contains("UnmodifiableList")){
			System.out.println("true");
		}
		// output of below line = Initial columns list size 3
		System.out.println("Initial columns list size " + columns.size());

		for (int i = 0; i < columns.size(); i++) {
			System.out.println(columns.get(i).getText());
			if (columns.get(i).getText().equals("Instructor"))
				columns.remove(i);
		}
		// output of below line = After modification column list size 3
		System.out.println("After modification column list size " + columns.size());
		return columns;
	}

	public static void main(String[] args) {
		System.setProperty("webdriver.chrome.driver", "F://chromedriver.exe");
		driver = new ChromeDriver();
		driver.get("http://www.qaclickacademy.com/practice.php");
		TestClass test = new TestClass();
		test.initMethod();
		test.getColumns();
	}

}

**Comment by diemol** [comment]
@spawar20 
After reading the code and checking the page, I don't really understand what the issue is... You get 3 elements and then you execute some logic to remove one element from the list... But this is not related to Selenium or the @FindBy functionality at all, this is entirely a piece of code that has no Selenium call in it. 

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
