### ISSUE TITLE
Windows Auth Box - GoTo URL Never Completes 

### ISSUE THREAD

**Issue by xDazedx** [SeleniumHQ/selenium#7026]
This is an odd one I need some help with. We have an automation project for an internal application that has a windows auth box when you hit the site. originally they were passing in the user/pass intp the url string but we started to notice some tests failing that seemed to be tied to permissions.  I wanted to setup AutoIT and see if this fixed the issue we were seeing but I ran into a new problem. The url we go to is an internal ip:port. When I goto the url, ex. 12.34.56.78:1111 the browser (chrome) opens but then fails with:

    OpenQA.Selenium.WebDriverException: 'The HTTP request to the remote WebDriver server for URL http://localhost:7233/session/be85ee0483da9772b136488bed19c43b/url timed out after 180 seconds.'

It appears that webdriver is waiting for something to complete and I can't get to the next step.  The web page is fully loaded with the auth box staring at me. 

I have tried the below but each one loads the page and then throws the error.
    
    _webDriver.Navigate().GoToUrl(url);
    _webDriver.Url = url;

I also tried using a URI.

I am running latest Selenium and ChromeDriver v72. I also tried using 2.46. Could this be a selenium bug or maybe some internal security settings interfering?

**Comment by rapidroamer** [comment]
I understand that you are switching from basic auth to windows auth. 

It is very difficult to debug the issue without having access to your environment.

But can you please try the below and use it while initialising chrome :

var options = new ChromeOptions();
options.AddArgument("no-sandbox");

**Comment by diemol** [comment]
Hi @xDazedx,

As @rapidroamer mentions, it is really hard to help without having more information. We have spent some time improving the issue templates in order to allow users to provide enough information when an issue is reported, which will end up helping the maintainers and collaborators to provide a better answer when an issue is created. Why did you delete the template? 

The only the I could say is that perhaps you can interact with the browser and check the DevTools, the network tab and see what is happening. Aside from that, please check if this is really a Selenium issue, and if so, feel free to reopen and provide all the information required in the template.

If this is just a question, send it to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.

**Comment by xDazedx** [comment]
Thanks all. 

1. It is an internal application and not public facing so there is no way to provide access. 

2. I have a post in stackoverflow as well located here - https://stackoverflow.com/questions/55123388/selenium-windows-auth-box-issue#comment97087427_55123388.

3. I have tried this using var options = new ChromeOptions();
options.AddArgument("no-sandbox"); with no luck. 

So at this point, if there are no other posts with people having a similar issue, I would tend to think that this has something to do with internal security settings vs. a selenium issue. 

Appreciate the help.
