### ISSUE TITLE
Selenium source code is still using JsonWireProtocolResponse.java. Deprecated?

### ISSUE THREAD

**Issue by miggs125** [SeleniumHQ/selenium#7027]
Hello,

I was going through the java selenium client source and noticed that when validating the response from the server, the function successHandler() under the JsonWireProtocolResponse.java file is called as opposed to the function by the same name under the W3CHandshakeResponse.java file. I was under the impression that the Jsonwire protocol had been deprecated and replaced by the W3C standard. The issue that I am having is that I have formatted the response for a webdriver I am working on according to the W3C standard but the current client code checks for properties dictated by the jsonwire protocol but not W3C. Mainly "value", "status" and "sessionId" as opposed to "sessionId" and "capabilities" when the /session endpoint is called. Is this something that will be fixed in the near future or should I write the driver code such that it is functional with the old standard?

**Comment by diemol** [comment]
Hi @miggs125,

 
We have spent some time improving the issue templates in order to allow users to provide enough information when an issue is reported, which will end up helping the maintainers and collaborators to provide a better answer when an issue is created. Why did you delete the template? When possible, please provide the information requested in the original template. Until then, we cannot continue.
