### ISSUE TITLE
SPNEGO support in Selenium hub/webdriver

### ISSUE THREAD

**Issue by actionbronson** [SeleniumHQ/selenium#7030]
## 🚀 Feature Proposal

A hub that supports SPNEGO and CA Siteminder.  The work is already done as a patch to Selenium where I work, I'm gauging if there's any interest in pushing this out to the community.

## Motivation

username/password authentication is out of the question for us so we support SPNEGO/Kerberos authentication and proper logging on the hub/webdriver side so we can print out each action done by a user.  This is to counter data leakage.

**Comment by actionbronson** [comment]
Any interest in this?

**Comment by diemol** [comment]
Hi @actionbronson,

This is actually interesting since I believe many companies have that challenge when testing internal apps that rely on those authentication methods.

One thing to note is that the current Selenium Grid 3.x is being deprecated and the version 4.0 is under work. So it is probable that your contribution won't be merged. Another thing to add is that authentication as a topic is not yet part of the W3C WebDriver standard, related [issue](https://github.com/w3c/webdriver/issues/385), which also makes it complicated to add it.

Nevertheless, I would be interested on the implementation and willing to have a look to it, perhaps at the point where the W3C WebDriver standard adds support for it, we could take a look at your code and port it over to Grid 4.0. Why don't to open source that customisation to your GitHub account so other members of the community can benefit from it?

**Comment by actionbronson** [comment]
Cool.  Let me work out the paperwork over here and see how quickly I can push this through.

**Comment by diemol** [comment]
Looking forward to it!
Should we keep this open? You can just comment and then I'd be happy to have a look.

**Comment by actionbronson** [comment]
Sorry, yes please keep it open if you don't mind.

**Comment by royswastik** [comment]
Hi, I wanted to check if there is any update on this. My application relies on SPNEGO authentication, and I am running automation using HtmlUnitDriver. I could not find a way to get SPNEGO auth work with this. It would be great if it is supported.

**Comment by kmsrv** [comment]
Eagerly waiting for this update. Using Selenium Webdriver and currently blocked because of SPNEGO authentication failure. Please provide an update.

**Comment by diemol** [comment]
I'll close this since the OP didn't come back and the code for Grid 3.x does not exist in the tree anymore.
