### ISSUE TITLE
Disable SSO as an Option in ChromeDriver to automate SSO Applications

### ISSUE THREAD

**Issue by parwalrahul** [SeleniumHQ/selenium#7032]
## 🚀 Feature Proposal

Need a way to enable ChromeDriver to handle different User IDs via selenium so that we can automate applications with SSO.

## Motivation

We are required to do automation of applications which run in Chrome but uses SSO, so while testing we are not able to simulate different users.

## Example

Need a method where SSO User Id/ Password can be passed by Driver only.

**Comment by diemol** [comment]
@parwalrahul 
I am assuming that you mean Single Sign On by SSO, where normally there is a 3rd entity authenticating you instead of the app you are testing. 

Therefore, usually the user is redirected to a page where s/he needs to be authenticated, and after that, sent back to the original website. This type of flow can be already automated with the methods that WebDriver offers. Nothing would need to be baked into ChromeDriver or Selenium to support that, it is an interaction with a few websites.

The question lays down more into how to plan the infrastructure for these type of tests, if you can use a production server for authentication or if you are provided with a testing/staging server to authenticate the users  needed in the tests.

Now, if the authentication requieres handling some sort of popup to enter user/password details, this is something that is not yet supported, but there is already an [issue created](https://github.com/w3c/webdriver/issues/385) in the W3C WebDriver. When/if that lands into the specification, then we could see browser drivers implementing it. 

Closing this as this feature proposal already exists in the W3C WebDriver repo.
