### ISSUE TITLE
Chrome download path set issue

### ISSUE THREAD

**Issue by omkarnathsingh** [SeleniumHQ/selenium#7052]
Please refer to this: 
https://bugs.chromium.org/p/chromedriver/issues/detail?id=2810#c2

Selenium version 6.3.0 is working, but not 6.141.59.

I am unable to set chrome download path using latest 6.141.59. 
Please suggest. Thanks,

**Comment by DanVill29** [comment]
Any updates on this?

**Comment by diemol** [comment]
@omkarnathsingh @DanVill29 
This is extremely confusing because we cannot tell anything from the information you are providing. We have added an issue template that should give a guide on what information to provide so the maintainers can give a proper answer. Why did you delete it?

Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

Without complete information, it is impossible to help.
