### ISSUE TITLE
grid hub is not responding to remote node

### ISSUE THREAD

**Issue by kvbhaskar79** [SeleniumHQ/selenium#7056]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

HI, i am using version 3.141.59 of stand alone jar file.  I did run the jar file on machine-A with role as hub. I could see that hub is started.  on Machine A (windows 10) ran the hub with this command:  "java -jar selenium-server-standalone-<version>.jar -role hub". 
Verified  whether hub is stared or not by accessing grid console web page.  "http://192.168.0.21:4444/grid/console". 

Now when i try accessing the "http://192.168.0.21:4444/grid/console" from machine-B (ubuntu 16.04), hub is not responding.  On the machine A i could see two TCP connection request packets from machine B. But no response is generated.

Now question do i need to add any options when starting hub on machine A? . why hub not responding to TCP connection request ?

**Comment by diemol** [comment]
Hi @kvbhaskar79,

As mentioned in the template, this issue tracker is not a help form and this issue will be closed.

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.

**Comment by kvbhaskar79** [comment]
Thank you Diemol.
