### ISSUE TITLE
Chromedriver is not working when executed from Jenkins

### ISSUE THREAD

**Issue by archanarathnam** [SeleniumHQ/selenium#7077]
Chromedriver - 2.37
Chrome version - 73.0.3683.86 (Official Build) (64-bit)

When I run the tests with the same chromedriver, it works fine in my local laptop but when I run it in jenkins remote server , it says the below but timeouts after 500seconds.

Starting ChromeDriver 2.37.543627 (63642262d9fb93fb4ab52398be4286d844092a5e) on port 35312
Only local connections are allowed.

**Comment by diemol** [comment]
Hi @archanarathnam,

We have spent some time improving the issue templates in order to allow users to provide enough information when an issue is reported, which will end up helping the maintainers and collaborators to provide a better answer when an issue is created. Why did you delete the template? When possible, please provide the information requested in the original template. 

Feel free to reopen when a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site) is provided.
