### ISSUE TITLE
promise.ControlFlow is not a constructor

### ISSUE THREAD

**Issue by chauhansaurabhb** [SeleniumHQ/selenium#7099]
I am trying to understand the behavior of following code:

selenium/javascript/node/selenium-webdriver/example/parallel_flows.js

But I am getting error that `promise.ControlFlow is not a constructor`.

Am I missing something? Can anyone please guide me?

Thanking you

**Comment by lmtierney** [comment]
This example was remove long ago https://github.com/SeleniumHQ/selenium/commit/5650b96185df72ee074f3c660ef5efd227b2739a#diff-10a12aab81944f17d0a16ada2c43656e

This is a question rather than an issue. In the future, please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
