### ISSUE TITLE
driver.find_elements_by_xpath() get list of data how display all in python

### ISSUE THREAD

**Issue by jasartp** [SeleniumHQ/selenium#7108]
my_url = 'https://techolution.app.param.ai/jobs/'

uclient = ureq(my_url)
page_html = uclient.read()
uclient.close()

page_soup = soup(page_html,"html.parser")
driver = webdriver.Firefox()
driver.get(my_url)
results = driver.find_elements_by_xpath('//*[@id="joblist"]')

for result in results:
print(result.text)

hear i got all the information in a list like the below

Engineering
Big Data Intern
Internship · Hyderabad · 0 - 2 Years
7 days ago
Consulting
Senior Cloud Specialist
Full-time · Singapore · 5 - 10 Years
11 days ago
Information Technology
Cloud Native Developer
Full-time · Hyderabad · 2 - 5 Years
12 days ago

how i store the data according to the date of posting(Most old first) as a DataFrame in CSV.

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
