### ISSUE TITLE
Last version of IEDriverServer & Selenium compatible with Windows XP + IE 8?

### ISSUE THREAD

**Issue by mingjin** [SeleniumHQ/selenium#7116]
Hi there,

I'm trying to run IEDriverServer & selenium on Windows XP + IE 8 (what an ancient version!:( ), but the recommended version(3.14.0) of IEDriverServer doesn't work with Windows XP.

Would you please help point out the appropriate version of IEDriverServer & selenium against windows XP + IE 8, and where can I download them?

Thanks in advance.

**Comment by lmtierney** [comment]
Please see https://github.com/SeleniumHQ/selenium/blob/master/cpp/iedriverserver/CHANGELOG#L1117-L1119 and check versions appropriately.

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)'

**Comment by mingjin** [comment]
thanks @lmtierney 

Just a note, after some investigation, I found the last working version of IEDriverServer & selenium against windows XP + IE 8 is 3.9.0, which can be downloaded from [here](https://selenium-release.storage.googleapis.com/index.html).
