### ISSUE TITLE
driver.findElements(by) method couldn't locate element which present in DOM

### ISSUE THREAD

**Issue by slymanAktas** [SeleniumHQ/selenium#7118]
![1](https://user-images.githubusercontent.com/30462178/56371890-a4757e00-6206-11e9-93cf-500c10dd9f0c.png)
## 🐛 Bug Report

driver.findElements(by); method couldn't locate element which present in DOM

## To Reproduce

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS:  OSX
Browser: Chrome
Browser version: Version 73.0.3683.103
Browser Driver version:  ChromeDriver  2.46
Language Bindings version:  jdk1.8.0_161
Selenium Grid version (if applicable):

**Comment by lmtierney** [comment]
It's in an iFrame, you need to switch context to the frame first.

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by slymanAktas** [comment]
Thanks
