### ISSUE TITLE
No documentation on how to set host headers

### ISSUE THREAD

**Issue by duane** [SeleniumHQ/selenium#7131]
EXPECTED: seeing a headers/host override on the `get` method on the selenium driver: https://www.seleniumhq.org/docs/03_webdriver.jsp#fetching-a-page

ACTUAL: documentation provides no reference for accepted parameters.

How do I set/override the Host (or any) header for the `get` request? Setting the Host header separately from resolving the DNS is incredibly important for verifying health before allowing it to accept traffic from the expected Host.

I am happy to pull updates to documentation if you point me towards where this mechanism is exposed.

If this mechanism is not exposed, is there a reason?

**Comment by cgoldberg** [comment]
> How do I set/override the Host (or any) header for the get request

which headers are you referring to?

**Comment by jimevans** [comment]
@duane If you mean headers between the browsers and the web server hosting the page navigated to when calling `get()`, the answer is no, there is no support for setting those headers. WebDriver doesn’t allow it as part of the W3C specification, and never has. There is no consistent, cross-browser way to support such an operation, and not every browser supports the ability for the user to do so. A cross-browser mechanism to accomplish this does exist, in the form of an HTTP proxy, which all WebDriver implementations support.

While one may claim that some browsers do allow this programmatically (like, say, Chrome, using the Chrome Debugging Protocol), these approaches are not universal.

**Comment by duane** [comment]
I take it you have no intention of allowing control of this behavior?

**Comment by diemol** [comment]
@duane Selenium controls browsers as a end user would do, this is modelled by the WebDriver W3C spec. Setting/overriding headers through WebDriver would not fit into that. If you want to do that, a proxy like https://github.com/lightbody/browsermob-proxy is the best option.

Closing as this is not in the scope of WebDriver.

**Comment by duane** [comment]
So to be clear, there are no intentions to support this functionality moving forward?

**Comment by jimevans** [comment]
@duane One of the things we've publicly talked about for Selenium 4 is integration with the Chrome Debugging Protocol (CDP) in some form. If that protocol allows one to set headers in HTTP requests, then that would allow Selenium users to set them in browsers that support CDP. I would suspect that integration in a finished form, with a reasonably polished API would be some way off, as those design discussions have just started.

However, as I mentioned in my earlier comment, the good news is that you can get this functionality today, right now, without having to wait, by using a proxy. There are several good options available. @diemol already mentioned [BrowserMobProxy](https://github.com/lightbody/browsermob-proxy), which is written in Java, but can be used by virtually any programming language due to its HTTP API. For my own work in C#, I've started using a version of [FryProxy](https://github.com/eger-geger/FryProxy), which provides a programmable API that users can control, and examples of its use can be found within the Selenium project's .NET test suite.

"Intentions" are a slippery thing in open source software. We're all volunteers here; we scratch the itch that the individual contributor decides to scratch There is no "Selenium Corporation" sponsoring the creation and maintenance of the project, and driving the creation of new features. I'm not trying to be coy by not directly answering your question with a yes or no. Saying "there are no intentions" would be accurate in one sense (no, there isn't a feature roadmap with "allow manipulation of the outgoing HTTP request" explicitly on it), but inaccurate in another (we hope to be adding CDP integration, which, if memory serves, would allow the user to do exactly what you're asking).

**Comment by drk-mtr** [comment]
I understand the rationale but this is such a shame, massively limits the potential for Selenium testing to be a pain free experience.
