### ISSUE TITLE
I'm getting "Chrome version must be between 70 and 73 "

### ISSUE THREAD

**Issue by oystersauce8** [SeleniumHQ/selenium#7132]
What should I do?

/home/travis/.rvm/gems/ruby-2.6.2/gems/selenium-webdriver-3.141.5926/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok': session not created: Chrome version must be between 70 and 73 (Selenium::WebDriver::Error::SessionNotCreatedError)

**Comment by diemol** [comment]
You need to use an appropriate ChromeDriver version for the Chrome version you are using, see http://chromedriver.chromium.org/downloads.

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.

**Comment by OHollister** [comment]
https://github.com/SeleniumHQ/selenium/issues/7132#issue-436502815
I fixed it by following the next steps:
1. Check your current Chrome Version - you can check it by going to https://www.whatismybrowser.com/detect/what-version-of-chrome-do-i-have
2. Download the WebDriver for Chrome that matches your current Chrome Version from http://chromedriver.chromium.org/downloads
3. Manually remove old chromedriver version from your bin folder and place there a new one. My dir was `/usr/local/bin/chromedriver`
Hope it help!

**Comment by krishnachaitanya9** [comment]
I had a similar issue, but I had a small misconception. I used the snippet 
`driver = webdriver.Chrome('chromedriver', options=options)`
And I placed the downloaded chrome driver in my project path. I was getting the same error even after updating the chromedriver to latest. I was wondering why the @OHollister fix wasn't working. I found out the hard way that it was referencing `'/usr/local/bin/chromedriver'` not my chromedriver in my project path. So anyone in the future who get this error, pass the full path where your intended chromedriver is present rather than assuming it will reference it from your project path automatically. And thanks @OHollister, after reading your answer I found the right way.

**Comment by cgoldberg** [comment]
> So anyone in the future who get this error, pass the full path where your intended chromedriver is present rather than assuming it will reference it from your project path automatically.

It *will* automatically find chromedriver if it resides in a directory specified on your system `PATH`, (not just an arbitrary project directory)

**Comment by Saledddar** [comment]
> I had a similar issue, but I had a small misconception. I used the snippet
> `driver = webdriver.Chrome('chromedriver', options=options)`
> And I placed the downloaded chrome driver in my project path. I was getting the same error even after updating the chromedriver to latest. I was wondering why the @OHollister fix wasn't working. I found out the hard way that it was referencing `'/usr/local/bin/chromedriver'` not my chromedriver in my project path. So anyone in the future who get this error, pass the full path where your intended chromedriver is present rather than assuming it will reference it from your project path automatically. And thanks @OHollister, after reading your answer I found the right way.

you saved my life.

**Comment by krishnachaitanya9** [comment]
@cgoldberg is correct. But everytime adding project path to PATH variable wasn't feasible for me. But I know how to use chromedriver better after learning from your comment. Thank You.

@Saledddar Happy to help amigo!
