### ISSUE TITLE
Selenium doesn't work well with a URL but browser could

### ISSUE THREAD

**Issue by greatvia** [SeleniumHQ/selenium#7133]
## 💬 Questions and Help
I want to do a automation with Selenium to handle the URL 'http://www.cde.org.cn/', but it doesn't work with Selenium + Python and Java, I tried Chrome and Edge. 
There are resource doens't exist error and the AJEX Request syntact error.  And also the "Bad Request" worning message alert.

But in the standalone browser, the URL could be opened correctly.

I am wondering if I need to add any special Chrome options or profile parameters.

Anyone can help?

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
