### ISSUE TITLE
Selenium operations malfunction with Outlook on Chrome

### ISSUE THREAD

**Issue by v-shakur** [SeleniumHQ/selenium#7148]
## 🐛 Bug Report

Using Selenium with Outlook on Chrome results in prolonged response times (approximately five minutes) for each element search.

To reproduce the behavior any set of simple actions would suffice (our repo is to complex to include here), e.g. waiting for an element to be displayed, click an element, etc.

## Environment

OS: Windows 10 
Browser: Chrome
Browser version:  73.0.3683.103
Browser Driver version: ChromeDriver 2.46.628402
Language Bindings version: Python 2.7.13
Selenium Grid version: 3.141.0

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
