### ISSUE TITLE
Error Starting IEDriver on Windows Server 2016

### ISSUE THREAD

**Issue by BrownCowOnSteroid** [SeleniumHQ/selenium#7167]
OS:
Windows Server 2016
Selenium Version:
selenium-java-3.4.0 for java (using maven)
Browser:
IE 11.2670.14393.0
driver:
IEDriverServer 3.4.0 64bit

All the browsers run fine on Windows 7, however for IE, the driver does not start up on Windows Server 2016, i have tried disabling the Protection Mode as well. 
Any idea if there is anything additional i need to do to get it working for Windows Server 2016

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
