### ISSUE TITLE
StaleElementReference exception even after waiting for sufficient amount of time

### ISSUE THREAD

**Issue by 9LPittu** [SeleniumHQ/selenium#7184]
OS: Windows 10
Browser: Chrome
Browser version: 74

Though element is present and even after waiting for 60 secs , element is not able to found and throwing staleelement reference exception.

The weird part is the same script is working well with java +selenium solution , the element is able to found successfully and click , but the same element could not be found and click

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
