### ISSUE TITLE
Here's GoToUri question

### ISSUE THREAD

**Issue by luowenjia1996** [SeleniumHQ/selenium#7189]
Hi,
I come from china,here are some questions for you,I am a .net developer, I use driver.Navigate().GoToUrl to navigate the page,but sometimes it triggers timeout exception,the page is actually fully displayed,but the browser keeps going round and round, and i try catch the TimeoutExption and then I use  FindElement to check the page whether completed but it didn't work,I thought  the reason was the driver was synchronous , It that right? how can I deal with this proplem?I want to check that the page is completed with some judgment of my own,how can I do?

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.

**Comment by luowenjia1996** [comment]
thanks a lot




------------------ 原始邮件 ------------------
发件人: "Diego Molina"<notifications@github.com>;
发送时间: 2019年5月9日(星期四) 下午3:56
收件人: "SeleniumHQ/selenium"<selenium@noreply.github.com>;
抄送: "……"<601438931@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [SeleniumHQ/selenium] Here's GoToUri question (#7189)




Closed #7189.
