### ISSUE TITLE
Element click is not functioning properly in IE 11

### ISSUE THREAD

**Issue by hbindut** [SeleniumHQ/selenium#7190]
## 💬 Questions and Help
The issue on IE 11.0 with Selenium 2.53.0

We could successfully execute a selenium test on Chrome, but with IE we had a weird observation.

It clicks on any random element than the target element.

Is this a known issue with IE 11? Can you please help us with any workaround/solution?.

Seeking help at the earliest.

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
