### ISSUE TITLE
What Capabilities of chrome driver is used to show latency in the network or set offline mode? 

### ISSUE THREAD

**Issue by Nehakatqa** [SeleniumHQ/selenium#7220]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by adiohana** [comment]
both Performance and set offline mode will be available in CDP - https://github.com/SeleniumHQ/selenium/pull/7212

For now, you can use performance logs. Check out this SO post:
https://stackoverflow.com/questions/55957240/how-to-calculate-total-time-for-one-request-from-chrome-driver-performance-logs/55957586#55957586

**Comment by diemol** [comment]
Thanks for replying @adiohana!

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
