### ISSUE TITLE
selenium web-driver, scroll the element into view not working

### ISSUE THREAD

**Issue by jlnbalaji** [SeleniumHQ/selenium#7227]
We are using ruby + watir-webdriver for our UI automation. 
Ruby Version - ruby 2.0.0p648 (2015-12-16) [i386-mingw32] 
Selenium webdriver - 3.4.0 
watir-scroll - 1.2.0 
watir-webdriver - 0.9.0
Selenium web-driver - 3.4.0 gem installed 
Firefox - 60ESR

Previous behaviour:
Previously it worked fine with firefox 52ESR and selenium webdriver 3.3.0

Browser Capabilities: 
profile = Selenium::WebDriver::Firefox::Profile.new
    profile.secure_ssl = true
    capabilities = Selenium::WebDriver::Remote::Capabilities.firefox(acceptInsecureCerts: true)
@browser = Watir::Browser.new @browserType, :profile => profile, :desired_capabilities => capabilities

Problematic code:
 @browser.div(:text=>child_element).wd.location_once_scrolled_into_view
wd.location_once_scrolled_into_view - piece of code not working 

Error: 
Selenium::WebDriver::Error::WebDriverError:
  Element <div id="dojoUnique4" class="dojoDndItem childNode"> is not reachable by keyboard

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
