### ISSUE TITLE
Can I convert a tag in the string type into webelement?

### ISSUE THREAD

**Issue by Ganofins** [SeleniumHQ/selenium#7232]

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
