### ISSUE TITLE
Selenium::WebDriver::Error::InvalidArgumentError file not found 

### ISSUE THREAD

**Issue by prativapokhrel** [SeleniumHQ/selenium#7255]
I am using selenium(3) headless chrome with Capybara(2.18.0)
I am trying to run a file upload spec(js: true) inside a Docker container, but I am getting 
`Selenium::WebDriver::Error::InvalidArgumentError:  invalid argument: File not found : /home/app/webapp/spec/support/files/dummy.pdf

![Screenshot from 2019-06-02 14-51-13](https://user-images.githubusercontent.com/20887144/58759243-8e1d4a80-8546-11e9-91b3-28e43fdb5a3c.png)

`

**Comment by twalpole** [comment]
You're running with a remote driver which means you either need to make sure the files you want to attach exist at the same location on the local and remote systems, or you need to specify a `file_detector` so the files gets uploaded (and location converted) from the local system to the remote system.  You'll also want to update your Capybara at some point since newer versions work around a lot of the issues with things like multiple file uploading.
