### ISSUE TITLE
Selinum WEbdriver test runner

### ISSUE THREAD

**Issue by shibinmadassery** [SeleniumHQ/selenium#7256]
Hi folks,
I was new to selenium and I wrote all tests, now I want to run the test run and schedule the test run.
How can I do this?

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
