### ISSUE TITLE
Issues installing the IDE ?

### ISSUE THREAD

**Issue by mmotahar-ia** [SeleniumHQ/selenium#7268]
## 💬 Questions and Help

I tried to install this and I am getting wrong java I/O version. 

Can someone assist ?

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
