### ISSUE TITLE
Selenium test exported as JUnit test *.jar file acts differently on Mozilla Firefox

### ISSUE THREAD

**Issue by ojake13** [SeleniumHQ/selenium#7283]
This question is pretty straightforward... When I created my test in Selenium IDE, I was able to automate the web browser to the point where I click on a link and the zip file automatically downloads. Mozilla Firefox is also set to download zip files automatically. 

However, when I export the selenium IDE to java (JUnit) and create a *.jar file from that exported test and run from the command line, everything works as expected until the file is clicked. The browser then asks where I would like to save or what application I would like to open with. How is this possible when the default is set to auto download zip files? Has anybody ever seen a similar problem?

Thanks!

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
