### ISSUE TITLE
'ValueError: source code string cannot contain null bytes' while importing webdriver

### ISSUE THREAD

**Issue by thisisanurag** [SeleniumHQ/selenium#7286]
## Note: You didn't choose a template in the previous step, therefore this will be treated as a "Questions / Help" one.
![Screenshot (15)](https://user-images.githubusercontent.com/43112185/59402939-3391b300-8dbe-11e9-971c-fd6c1f116147.png)

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
