### ISSUE TITLE
Access is denied: 'OpenQA.Selenium.Remote.DesiredCapabilities'. -> AppiumOptions.ctor()

### ISSUE THREAD

**Issue by jackwangchs** [SeleniumHQ/selenium#7288]
To solve the port leaking issue https://github.com/SeleniumHQ/selenium/issues/4162, I upgrade the selenium to v4.0.0a1 and use AppiumOptions. However, it always reports 'Access is denied' error.

The driver setup is like this:
```
var options = new AppiumOptions();
options.AddAdditionalOption("platformName", "iOS");
options.AddAdditionalOption("deviceName", "iPhone X");
```
Any solution on that?

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
