### ISSUE TITLE
Is there any selenium method exist to replace bar code scanner simulation

### ISSUE THREAD

**Issue by RG108** [SeleniumHQ/selenium#7298]
Hi
My application authorizes users with a tag which is nothing but the barcode so we authorize it with scanner machine. On analysis, I found that it simulates device control along with the actual data which on a textbox on the web application.
Is there any selenium library exist to simulate the barcode functionality ?? I could use the zxing library here but my task is to pass the actual data (which I know ) along with the nonprintable characters ( which are the ASCII values ). I passed the data in the given format with sendkeys() method but it is not working as expected.

Has anybody worked on it before ? or can we surpass the scanner authentication with Java ??
Any help is much appreciated!!!!

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by RG108** [comment]
@lmtierney
Please note that I am raising it as an issue here. I can understand what is meant to be questioned and what is an issue btw.

**Comment by lmtierney** [comment]
>I can understand what is meant to be questioned and what is an issue btw.

You asked multiple questions and did not point out any issues in the selenium library.
