### ISSUE TITLE
Choose Certificate hangs Selenium on Chrome

### ISSUE THREAD

**Issue by Hexploit85** [SeleniumHQ/selenium#7317]
## 🐛 Bug Report

Selenium stops executing code after choose certificate pop-up. Even if i try to handle this window with other tools(Appuium,AutoIT) i simply can't, as no code will be executed pass moment when i click on link that triggers cert pop-up. When i set-up Chrome to auto accept certificate, pop-up won't show but code will still hangs in exact same moment.

## To Reproduce
public class TestChrome{
public static void main (string[] args){
System.setProperty("webdriver.chrome.driver", "c:\\whatever\\chromedriver.exe");
WebDriver driver = new ChromeDriver();
driver.get("http://www.webpage.com");
driver.findElementByName("link to button that triggers cert pop-up").click();
System.out.println("This code won't execute or any other");}}

## Expected behavior

Code should execute further.

## Environment

OS: Windows 7 
Browser:  Chrome  
Browser version:  75.0.3770.100
Browser Driver version: 75.0.3770.90 
Language Bindings version:  Java 3.141.0 
Selenium Grid version (if applicable): 3.141.59

**Comment by diemol** [comment]
Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by JizaiGinji** [comment]
We have exactly the same problem. In our solution, we trigger an external ui automation tool to handle the dialog after executing browser.get("a angular page") in protractor. We get the following error message after the handling of the dialog:

 Failed: Session [XXXXX] not available and is not among the last 1000 terminated sessions.
    Active sessions are[]

The remote browser shows the target website after handling for a few moments and then stops the browser with the mentioned error message. It seems like after dialog handling we lose the current driver session and somehow a new one is generated. Sadly, I cannot provide the exact code and the page we want to access is an internal one.

**The expected behavior would be:**
- access page with driver.get (certificate selection dialog shows)
- handle dialog somehow
- go on with tests, with the new session id after handling

**Environment:**
OS: Windows 10
Browser: Chrome/Firefox
Browser version: 75.0.3770.100/67.03
Browser Driver version: 75/24

**Comment by diemol** [comment]
@Hexploit85 @JizaiGinji I will close this issue since no reproduction scenario has been provided, in addition the description is incomplete. Feel free to create a new issue and fill out the whole template when more information is available on your side.
