### ISSUE TITLE
Cookies duplication

### ISSUE THREAD

**Issue by ArnoldCell** [SeleniumHQ/selenium#7368]
I'm using Chrome Driver on a .NET application,

I create a new instance of ChromeDriver and adding a set of cookies to it.

During the session I get many "Set-Cookie" headers responses from the server. 
When the server responds with a "Set-Cookie" most of the cookies just update their value as expected, but there are few cookies (always the same) that being duplicated with new values instead of updating the old value.
How can I handle this situation?

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
