### ISSUE TITLE
varacode scan  throws vulnerable for selenium JARs

### ISSUE THREAD

**Issue by ramakrishnakandipati** [SeleniumHQ/selenium#7382]
Hi

my selenium scripts scanned through varacode and it generated vulnerable in below selenium JAR files specially regarding Directory Traversal

selenium-chrome-driver-2.53.1.jar
selenium-ie-driver-2.53.1.jar
selenium-firefox-driver-2.53.1.jar

Description : Allowing user inout to control paths used in filesystem operations may enable attacker to access.

below are few lines it throws 
selenium-firefox-driver-2.53.1.jar ------  org/.../internal/ProfilesIni.java (line 104,137, 140, 145)
selenium-ie-driver-2.53.1.jar -----------   .../InternetExplorerDriverService.java (line 201, 177)
selenium-chrome-driver-2.53.1.jar ------ .../ChromeDriverService.java (line 147)

As i ma working in financial institution my scripts has to go through varacode,  let me know how to fix these issues.

Regards
Ramakrishna

**Comment by diemol** [comment]
@ramakrishnakandipati Selenium 2.x is not supported anymore, please upgrade to the latest Selenium version.
Moreover, this is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
