### ISSUE TITLE
java v3.141.59:TemporaryFilesystem.setTemporaryDirectory() invalid

### ISSUE THREAD

**Issue by LiqiNew** [SeleniumHQ/selenium#7389]

**Comment by LiqiNew** [comment]
Why are you closing my question? My question has not been answered yet? @barancev

**Comment by barancev** [comment]
Because you've completely ignored the bug report template:

## 🐛 Bug Report

A clear and concise description of what the bug is.

## To Reproduce



Detailed steps to reproduce the behavior:

## Expected behavior

A clear and concise description of what you expected to happen.

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):
