### ISSUE TITLE
selenium webdriver click event not working sometimes 

### ISSUE THREAD

**Issue by KRajadurai** [SeleniumHQ/selenium#743]
Selenium click event not working( sometime ) with firefox( 36.0.4).
when i trigger the click event one more time, its working. Why?

click event not always working with single click.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
