### ISSUE TITLE
Node.js: Error reading broker pipe: The pipe has been ended

### ISSUE THREAD

**Issue by jonathanrsmjtk** [SeleniumHQ/selenium#7431]
I'm writing a program to read what people types in Google Search, but error occured:
`const {Builder, By, Key, until} = require('selenium-webdriver');`
 
`(async function example() {`
 ` let driver = await new Builder().forBrowser('chrome').build();`
  `try {
    await driver.get('http://www.google.co.id/');
    await driver.getTitle();
	await driver.wait(driver.getTitle().then(function(title){console.log(title)}));
    // await driver.findElement(By.name('q')).sendKeys('webdriver', Key.RETURN);
    // await driver.wait(until.titleIs('webdriver - Google Search'), 10000);
  } 
  catch(err){
  	// 
  	console.log(err);
  }
  finally {
    await driver.quit();
  }
})();`

and this error occured when i set timeout on wait() equal to or above 10000:
![image](https://user-images.githubusercontent.com/49324622/61853675-ad9d7780-aee6-11e9-8da9-2e5515b8970e.png)
chrome can be opened, but it closes before typing on search box and results that error on my console. Any suggestions?

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
