### ISSUE TITLE
Do we still need the xml2js dependency in selenium-webdriver?

### ISSUE THREAD

**Issue by charlesh21** [SeleniumHQ/selenium#7432]
## 💬 Questions and Help
After used npm install the selenium-webdriver, I grep the 'xml2js' with whole folder.
It didn't use by any function. I checkout with old tag and grep. It used to read the manifest for Firefox add-on. But in this [commit](https://github.com/SeleniumHQ/selenium/commit/e8efc001bdf09bc668a7715f939d5f09039d1fae#diff-581b0552068e3455f032d5c9a87d58a5) firefox/extension.js already be removed.
Currently, the firefox.js read the manifest file with json not xml too.

So, just wondering the xml2js still need as the dependency or not?

selenium-webdriver version: 4.0.0-alpha.4

Thanks,
Charles

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
