### ISSUE TITLE
System proxy does not support method setNoProxy

### ISSUE THREAD

**Issue by leoforever** [SeleniumHQ/selenium#7449]
When I using system proxy and set no proxy, it throws exception.
proxy.setProxyType(ProxyType.SYSTEM);
proxy.setNoProxy(noProxiesOn);

 And I check the source code, find that setNoProxy  is for MANUAL proxy only. Is there any reason and can we add set no proxy for other type of proxy(system proxy and pac proxy)

public Proxy setNoProxy(String noProxy) {
verifyProxyTypeCompatibility(ProxyType.MANUAL);
this.proxyType = ProxyType.MANUAL;
this.noProxy = noProxy;
return this;
}

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
