### ISSUE TITLE
JAVA excludeSwitches Convertion DOTNET

### ISSUE THREAD

**Issue by ImQdf** [SeleniumHQ/selenium#7451]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
Start the Google drive, the browser enter 'window.navigator.webdriver'
JAVA:
Option = ChromeOptions ()
Option. Add_experimental_option (' excludeSwitches' [' enable - automation '])
Driver = Chrome(options = option)
So how should C# be added?I need some help. Thanks

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
