### ISSUE TITLE
Not able to execute test cases after updating chrome to v76.

### ISSUE THREAD

**Issue by viveksingh1992** [SeleniumHQ/selenium#7491]
Please take a look at [this](https://stackoverflow.com/questions/57457310/i-got-error-like-script-returns-unexpected-result-while-running-selenium-test-ca?noredirect=1#comment101399557_57457310) and help me with it.

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
