### ISSUE TITLE
Selenium Standalone Server: deviceName capability is not considering when create appium node

### ISSUE THREAD

**Issue by beregeyko** [SeleniumHQ/selenium#7499]
OS: Mac OS 10.13.6
Selenium Server version: 3.141.59

**Description:**
1. Selenium Server is UP
2. Appium started for a few devices as nodes(--nodeconfig provided) Each .json has different 'deviceName' capability(e.g. "phone1", 'phone2' ....Nodes are connected to selenium server
3. Create WebDriver instance( url - selenium server URL, deviceName - one of existed node deviceName

**Actual result:**
Selenium Server send request to one of connected devices not considered provided deviceName capability

Expected result:
Selenium Server send request to node with provided deviceName capability

**Comment by diemol** [comment]
@beregeyko this is something out of the scope of Grid 3 because `deviceName` is not a capability used to decide on which node the test will run. This has never been supported, and the implementation of this requires implementing your own capability matcher or own proxy to handle this. 

I believe there should be a collaboration between Appium and Selenium for this. Could you please create a feature proposal on both repos?
