### ISSUE TITLE
不知道WebDriverWait是否有起作用

### ISSUE THREAD

**Issue by Lee-Jin-Yi** [SeleniumHQ/selenium#7501]
💬 Questions and Help

C# selenium 新手
不知道這樣寫的WebDriverWait運行時有沒有起作用，判斷在60秒內若有找到CssSelector(".col-md-5")這個元素，才往下繼續執行;若超過60秒沒找到則TimeOut

For questions or help please see:

`namespace SFA.Shared` 
`{
    class IWebElement
    {
        public static WebDriverWait wait = new WebDriverWait(webDriver, TimeSpan.FromSeconds(60));
    }
`
`classTOverseaCustomerForm
{
   public TOverseaCustomerForm()
     {
      Shared.IWebElement.wait.Until(driver => driver.FindElement(By.CssSelector(".col-md-5")));
     }
}
`

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
