### ISSUE TITLE
Fatal error: invalid session id

### ISSUE THREAD

**Issue by mohitgith** [SeleniumHQ/selenium#7508]
I am facing this issue while running the UI regression test. I have used Typescript for automation in selenium and I have around 80 test cases. So when executing all at once, it executes some of the test cases smoothly but after sometimes some test cases fail and this error is popped up. I am using only one thread for running these tests.
`"noOfThreads": "1",`
There is no issue with the individual test cases as they work fine when running individually.

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
