### ISSUE TITLE
Provide an option to disable images loading in Internet Explorer

### ISSUE THREAD

**Issue by NallaSandeep** [SeleniumHQ/selenium#7512]
## 🚀 Feature Proposal

There is an option to disable images loading in Firefox & Chrome. 
(Ref: https://stackoverflow.com/questions/48306556/selenium-webdriver-firefoxchrome-java-how-to-disable-image-loading).
I don't find the option to do the same in Internet Explorer. 
So, opened a thread at StackOverflow. But, no luck.
https://stackoverflow.com/questions/57553624/selenium-internet-explorer-java-how-to-disable-images-loading/57557858?noredirect=1#comment101635509_57557858

## Motivation

Disabling images loading improves the automation test performance.

**Comment by jimevans** [comment]
This isn’t possible without changing the browser configuration/profile, and IE does not support profiles outside the currently logged in Windows user account. The driver will not be modified to change the configuration, since there is no guaranteed way to revert the configuration change after the session ends. You can either manually set the browser configuration in the options dialog (if such a setting exists), manipulate the setting programmatically using the Windows registry (assuming such a setting exists for IE), or use a web proxy to block retrieval of images. This is not a feature the driver will be implementing.
