### ISSUE TITLE
selenium python issues-> Traceback (most recent call last):   File "C:/Users/mdarpana/PycharmProjects/python/example.py", line 5, in <module>     driver = webdriver.Chrome(executable_path='\Program Files\Python37\Lib\site-packages\selenium\webdriver\chromedriver.exe')   File "C:\Users\mdarpana\PycharmProjects\python\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__     self.service.start()   File "C:\Users\mdarpana\PycharmProjects\python\venv\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start     os.path.basename(self.path), self.start_error_message) selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

### ISSUE THREAD

**Issue by Darpana10** [SeleniumHQ/selenium#7523]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
