### ISSUE TITLE
Can't click an AJAX element using Selenium WebDriver !

### ISSUE THREAD

**Issue by msayem63** [SeleniumHQ/selenium#7549]
Hi there,
I have tried a lot to click an AJAX element but any of the methods not working; 

1. Thread.sleep(2000);
		By cotainer = By.xpath("//input[@value='View Details']");
		WebDriverWait wait = new WebDriverWait(driver, 15);
		wait.until(ExpectedConditions.presenceOfElementLocated(cotainer)).click();
2. WebElement myElement = new WebDriverWait(driver, 30).until(ExpectedConditions.elementToBeClickable(
												By.xpath("//input[@value='View Details']")));

3. WebDriverWait wait = new WebDriverWait(driver, 10);
		WebElement myEl = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//input[@value='View Details']")));
		myEl.click();
[page.txt](https://github.com/SeleniumHQ/selenium/files/3592113/page.txt)

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
