### ISSUE TITLE
SafariDriver does not support pageLoadTimeout

### ISSUE THREAD

**Issue by anthonygreen** [SeleniumHQ/selenium#7578]
My previously working Browserstack tests have started failing. The Browserstack team report the cause is this unresolved issue: 
https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/6015

Any update?

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.

**Comment by AutomatedTester** [comment]
According to https://wpt.fyi/results/webdriver/tests/set_timeouts/set.py?label=experimental&label=master&aligned Safari driver supports this. If it is not working then I suggest raising a bug with Apple

**Comment by anthonygreen** [comment]
This is Safari 9 on El Capitan

**Comment by barancev** [comment]
I'm more than sure that nobody will fix this issue in Safari 9.
Please consider upgrade to a newer version.
