### ISSUE TITLE
Error Value cannot be null. parameter name : Source

### ISSUE THREAD

**Issue by VineethTV** [SeleniumHQ/selenium#7582]
## 🐛 Bug Report

I am getting an error 'Value cannot be null. parameter name :source' after filling password filed and submitting the page through selenium script. But am not getting this error by doing manually.
Following code is used for setting the password

-----------------------------------------
var passwordtxt=driver.FindElement(By.Id("txtpassword"));
var JSexecutor= (IJavaScriptExecutor)driver;
JSexecutor.ExecuteScript("arguments[0].setAttribute('value',arguments[1])",passwordtxt,"mypassword");
-----------------------------------------

## Environment

OS: <!-- Windows 10
Browser: Internet Explorer
Browser version: 11.1331.16299.0
Project : Asp.Net
Language : C#
Selenium Version= 3.141.0.0

Anyone Please help me on this, Thanks

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
