### ISSUE TITLE
Make a new release (Python, pypi)

### ISSUE THREAD

**Issue by PetterS** [SeleniumHQ/selenium#7590]
I am using the selenium Python library from pypi. Due to #5296 I am forced to pin the version to 3.8.0, which is almost two years old.

That bug has however been fixed, so a new Python release to pypi would presumably work for us and others.

Is there a timeline for a new release?

**Comment by AutomatedTester** [comment]
There have been numerous releases since 3.8. Looking at the bug it devolved down to me too without any meaningful help in trying to solve it. There has not been any changes in selenium that would be the cause.

I suggest trying to help figure out the cause and help break that down or maybe raise a bug with 
[chromedriver](https://sites.google.com/a/chromium.org/chromedriver/help)

**Comment by AutomatedTester** [comment]
Please raise a bug with more details on the actual issue if you can debug it

**Comment by PetterS** [comment]
@AutomatedTester 

Ah, I think you misunderstood me. The bug *has* been fixed. But it was fixed this year, and the last release on PyPi was 3.141.0 on November 1, 2018. There has been more than a thousand commits to master since then.

**Comment by PetterS** [comment]
It was fixed in #6480

**Comment by PetterS** [comment]
I see, the 4.0.0-alpha-2 release from July 1 still has to make its way to PyPi, though.
