### ISSUE TITLE
Changing the path of testcases in a test suite

### ISSUE THREAD

**Issue by nithinbang** [SeleniumHQ/selenium#760]
If the path for the test case is changed and then if we want to access a test suite with the test cases whose paths are changed. we get an error. But we cant edit the path of the changed test case path. How to resolve this issue?

**Comment by ddavison** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
