### ISSUE TITLE
How to capture websocket messages from Selenium using some interval update?

### ISSUE THREAD

**Issue by ProgrammingLife** [SeleniumHQ/selenium#7600]
How to capture websocket messages from Selenium using some interval update? Can you provide me with some example (Python/ Node.js) on how to do it?

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
