### ISSUE TITLE
Obtain the content of "https://free-ss.site" with selenium + python + firefox + geckodriver

### ISSUE THREAD

**Issue by hongyi-zhao** [SeleniumHQ/selenium#7601]
Hi,

I want to obtain the content of "https://free-ss.site" with selenium + python + firefox + geckodriver.   I write the following code with python:

```
import os

def get_path(path):
    return os.path.abspath(os.path.expanduser(path))

firefox_binary=get_path("~/software/mozilla.org/firefox_relative/firefox-68.0esr/firefox/firefox")
executable_path=get_path("~/software/mozilla.org/geckodriver-v0.25.0-linux64/geckodriver")

from selenium import webdriver
browser = webdriver.Firefox(firefox_binary=firefox_binary, executable_path=executable_path)
browser.get("https://free-ss.site")
```

But failed the get all of the contents on that website.    
Any hints?

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
