### ISSUE TITLE
Allow overloading capabilities to "driver.find_element_by_*(...)" methods (Python API)

### ISSUE THREAD

**Issue by garciparedes** [SeleniumHQ/selenium#7636]
## 🚀 Feature Proposal

This feature would make more flexible the way to reimplement the behavior on `driver.find_element_by_*(...)` on Python. To do that I propose to add the `*args`, `**kwargs` arguments to these methods.

## Motivation

The main motivation is to only need to reimplement the `driver.find_element(...)` method to change the global behavior of element finding, and allow to provide new arguments that extends the default functionality.

## Example

Suppose I want to build a custom `driver` that has a retry policy on element finding. To do that, I would override `driver.find_element()` adding a new argument such us the max number of allowed retries as optional. That's possible right now, whereas the problem is that if I want to set this when I use `driver.find_element_by_xpath(...)`, then I would need to reimplement that method to allow something like `*args, **kwargs` arguments. 

I would like to this kind of things can be possible without the need of reimplementing every `driver.find_element_by_*(...)` method.

P.D: If the propose is approved, I can work on the changes and then submit a pull request. :wink:

**Comment by Dude-X** [comment]
I am a -1 on this idea and here are my reasons:
1) by adding `*args, **kw` to every method on the driver, it will pollute the function signature with arguments that do nothing by default.
2) Using  `*args, **kw` to allow flexible input does not help document what are the acceptable arguments to use. I really dislike big inheritance chains where every parent object along the way has their own use for args, and kwargs. Sadly, I have this in my own test framework and it's really a pain to go through all the code to see how one variable can affect another class.
3) I prefer the idea that a function tries to do one thing well. Now that Selenium is pretty popular changing the signature to allow easier inheritance is something that may break other's people code if they have their own subclasses.
4) It is preferable to write your own wrapper class that calls the underlying selenium code.

One thing I do encourage though is making the all the `find_element` calls a class of its own so that all the driver objects inherit it, a la Java. Java calls it a `SearchContext` and it's written as an interface. This would actually help reduce redundancy in the Python code, and allow you to easily create a subclasses in a more concise way.

**Comment by AutomatedTester** [comment]
I have deprecated the use of `find_element(s)_by_*` commands so we won't be working on this issue
