### ISSUE TITLE
RemoteWebDriver SendKeys using TouchActions

### ISSUE THREAD

**Issue by apalabrados** [SeleniumHQ/selenium#7642]
Hi,

I'm trying to send a string to an input tag, letter by letter, and all seems to work fine but there's a slight issue with the text entered.

Each time a letter in entered, it repeats the previous letters. Yes it's something really extrange.

```
element = _remoteWebDriverMobile.FindElementById("input");
touchActions = new TouchActions(_remoteWebDriverMobile);
point = new Point(_random.Next(0, element.Size.Width), _random.Next(0, element.Size.Height));
touchActions.MoveToElement(element, point.X, point.Y)
                                                    .Click()
                                                    .Build()
                                                    .Perform();

for (int idx = 0; idx < text_to_write.Length; idx++)
{
   String s = new StringBuilder().Append(text_to_write[idx]).ToString();
   touchActions.SendKeys(s).Perform();
   waitDriver = new WebDriverWait(_remoteWebDriverMobile, 
   TimeSpan.FromMilliseconds(RandomGaussiano.NextGaussian(_random, 150, 50)));
   Console.WriteLine("Text: " + s);
}
```
I just send each letter individually by a certain period of time.

So, if send this string "tag protector", the resulting text entered in the input is: "tag protecttag protectotag protector" and each time the result is different.

![Captura](https://user-images.githubusercontent.com/39434545/66126888-c31bd580-e5ea-11e9-88c7-41594cd4cccd.JPG)

Using latest ChromeDriver.
Using .NET c#.

**Comment by jimevans** [comment]
This behavior is by design for the `TouchActions` class.

An Action does not reset after a call to `Perform`, so by reusing the same `TouchActions` instance, you’re stacking calls together at each call to any action. This is to allow users to design reusable action sequences that can be repeated by subsequent calls to `Perform`. Current sources have a `Reset` method, though I don’t remember when it was added. You can either call the `Reset` method between calls to `SendKeys().Perform()`, or instantiate a new `TouchActions` instance. The latter approach is not expensive, as `Actions` and its subclasses were explicitly designed to be lightweight.

**Comment by apalabrados** [comment]
I do not any Reset() method.

The second way you mention works like a charm and i just have a question. On every instance of TouchAction, i have to use MoveToElement method for placing the focus in the input field. Is that equivalent as if a user tap the input on every typing?
