### ISSUE TITLE
java: org.openqa.selenium.remote.RemoteWebDriver cannot be cast to org.openqa.selenium.interactions.HasTouchScreen

### ISSUE THREAD

**Issue by gitjayzhen** [SeleniumHQ/selenium#7675]
### docker-selenium-chrome: 3.141.0

`WebDriver driver = new RemoteWebDriver(webURL, cap)`
`TouchActions action = new TouchActions(driver);`
`action.build();`
`action.scroll(autoDriverAtion.getWebElement(), xOffSet,0).perform();`

### ERROR

org.openqa.selenium.remote.RemoteWebDriver cannot be cast to org.openqa.selenium.interactions.HasTouchScreen

## An error occurred while I was executing the script. Can you tell me how to solve it? Thanks

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.

**Comment by gitjayzhen** [comment]
@diemol OK, I will, thanks for your advice.
