### ISSUE TITLE
Selenium not detect 

### ISSUE THREAD

**Issue by oh2thirteen** [SeleniumHQ/selenium#7680]
Hey i use selenium with python on win 7 64 bit i have script to login me only automated on my using webpages.But the browser detect and the websites knows i use selenium and they dont let me login without re captcha. I read in other issues users replace something in chromedriver but my changing of cdc part with vim doesnt help.
what do I have to change so that selenium is not recognized By webpages and chromedriver ?

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
