### ISSUE TITLE
WebElement#getCssValue does not return rgba value in case of hexa color

### ISSUE THREAD

**Issue by surli** [SeleniumHQ/selenium#7697]
## 🐛 Bug Report

When using `WebElement#getCssValue` the returned value is not necessarily a rgba value when the requested color is in fact an hexadecimal value, contrarily to what's explained in the WebElement javadoc:
https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/WebElement.java#L246-L265

Now I've not been able to track down in the W3C WebDriver specification if the color values should be systematically rgba or not, so maybe it's just a javadoc issue.

## To Reproduce

Detailed steps to reproduce the behavior:
Request the CSS color value of an element containing an hexadecimal color.

## Expected behavior

The color is returned as an RGBA value.

## Test script or set of commands reproducing this issue

```
WebDriver driver = new FirefoxDriver();
driver.get("http://www.google.com");
// The "connection" button, cf the following gif
WebElement element = driver.findElement(By.id("gb_70"));
// expected to be RGBA according to the javadoc
String color = element.getCssValue("border-top-color");
System.out.println("Color CSS value: " + color);
driver.quit();
```

![google-button-border-color](https://user-images.githubusercontent.com/1478232/67192046-1b2c4780-f3f3-11e9-833a-ccd4b410f56a.gif)

## Environment

OS: Linux
Browser: Firefox
Browser version: 69.0.3
Browser Driver version: GeckoDriver 0.25.0
Language Bindings version: Java 3.141.59

**Comment by smallcreep** [comment]
@surli I checked it, this result returns gecko driver.

**Comment by smallcreep** [comment]
@surli @barancev In documentation WebDriver part [Get Element CSS Value](https://w3c.github.io/webdriver/#get-element-css-value):

```
Let computed value be the result of the first matching condition:

current browsing context’s document type is not "xml"
computed value of parameter property name from element’s style declarations. property name is obtained from url variables.
Otherwise
"" (empty string)
```

And `computed value` defined as [Computed value](https://w3c.github.io/webdriver/#dfn-computed-value):

```
The following terms are defined in the CSS Object Model: [CSSOM]:
```

In the `CSSOM` part [5.7.2. Serializing CSS Values](https://www.w3.org/TR/cssom-1/#serializing-css-values):
```
<color>
  If <color> is a component of a resolved or computed value, then return the color using the rgb() or rgba() functional notation as follows:
* If the alpha component of the color is equal to one, then return the serialization of the rgb() functional equivalent of the opaque color.
* If the alpha component of the color is not equal to one, then return the serialization of the rgba() functional equivalent of the non-opaque color.
```

It means  that need change javadoc and fix chrome driver, because gecko driver return correct result.

**Comment by pujagani** [comment]
Thank you for providing the details of the bug and the follow up on the same. I was seeing `NoSuchElement` exception with the example shared so I tweaked the example to check the value returned.
I attempted to see if the issue is still valid. 

Example 1 

```
  WebDriver driver = new FirefoxDriver();
    driver.get("http://www.yahoo.com");
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(40));
    WebElement element = wait.until(presenceOfElementLocated(By.tagName("a")));
    String color = element.getCssValue("background-color");
    System.out.println("Color CSS value: " + color);
    driver.quit();
```

![image](https://user-images.githubusercontent.com/10705590/112629168-f5ae3380-8e59-11eb-9663-bd07f3dbb313.png)


Result: Color CSS value: rgba(0, 0, 0, 0)

Example 2

```
   WebDriver driver = new FirefoxDriver();
    driver.get("http://www.google.com");
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(40));
    WebElement element = wait.until(presenceOfElementLocated(By.className("gNO89b")));
    String color = element.getCssValue("background-color");
    System.out.println("Color CSS value: " + color);
    driver.quit();
```

![image](https://user-images.githubusercontent.com/10705590/112629353-3c9c2900-8e5a-11eb-957c-4c82e63764b8.png)

Result: Color CSS value: rgb(248, 249, 250)

 **Setup**
OS: MacOS 
Browser: Firefox
Browser version: 86.0.1
Browser Driver version: GeckoDriver 0.29.0

Browser: Chrome 
Browser version: 89.0.4389.90
Chrome Driver version: ChromeDriver 89.0.4389.23

Language Bindings version: Java Beta 2 

 In both cases, I was unable to see the issue. The result is as per the Javadoc https://github.com/SeleniumHQ/selenium/blob/selenium-4.0.0-beta-2/java/client/src/org/openqa/selenium/WebElement.java#L326

I would recommend an update to the latest release of Selenium Beta-2. 

Please let me know if I am missing something here.

**Comment by surli** [comment]
> In both cases, I was unable to see the issue.

So apparently my issue description was not clear enough, but you show exactly the issue I had: I was expecting this method to always return RGBA and not RGBA or RGB. You can check the associated commit on our project, I had to change some test expectation from rgba value to rgb because of it: https://github.com/xwiki/xwiki-platform/commit/f6366253740a905147f21a7e43d901e7bce36f61

Now IMO the fix is just to clarify the javadoc to express that the value can be either rgba or rgb, since right now it says:
> Color values should be returned as rgba strings

[EDIT: note that I created it as a bug since apparently this commit was related with an upgrade of selenium, so I wasn't sure if it was a regression or not]

**Comment by pujagani** [comment]
Thank you for providing the details again. Apologies from my end. I misunderstood the issue here. Appreciate the clarification comment. It seems the values returned are dependent on the browser interpretation and implementation. I have updated the Javadoc appropriately.
