### ISSUE TITLE
Use proxy with username and password

### ISSUE THREAD

**Issue by GodStar88** [SeleniumHQ/selenium#7700]
Hello, I have a problem when use proxy with username and password.

ChromeOptions options = new ChromeOptions();
proxy = new Proxy();
proxy.Kind = ProxyKind.Manual;
proxy.IsAutoDetect = false;
proxy.HttpProxy =
proxy.SslProxy = "127.0.0.1:3330";
options.Proxy = proxy;
options.AddArgument("ignore-certificate-errors");
var chromedriver = new ChromeDriver(options);

that can use without username and password.
but doesn't work with username and password.
someone said use SocksUserName and SocksPassword. it doesn't work.
Please help me, thanks

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
