### ISSUE TITLE
How to use RelativeLocator in Page facory

### ISSUE THREAD

**Issue by sachinguptait** [SeleniumHQ/selenium#7727]
How can i use RelativeLocator in page factory (@FindBy), please help me here

```
driver.findElement(RelativeLocator.withTagName("input").above(By.name("password")).
				below(By.xpath("//td//b[text()='sign-in here']")));
```

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
