### ISSUE TITLE
connect to local browser but can't set agent

### ISSUE THREAD

**Issue by Heartfilia** [SeleniumHQ/selenium#7757]
**i started a local brower and used this**  `options.add_experimental_option("debuggerAddress", "127.0.0.1:62486")`, **but it can't set agent by** `options.add_argument(f'--proxy-server=xxx.xx.xx.xx:8800')`.

 **Thanks guys, i need help.**

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
