### ISSUE TITLE
Selenium-side-runner problem

### ISSUE THREAD

**Issue by pcace** [SeleniumHQ/selenium#7759]
Hi,

can anyone help me with this problem:

```
selenium-side-runner -c "goog:chromeOptions.args=[--headless,--nogpu] browserName=chrome" Wohnungsemail.side 
info:    Running Wohnungsemail.side
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In /home/hannes/flathunter/selenium/side-suite-Wohnungsemail
  3 files checked.
  testMatch: {**/***/*.test.js,**/***.test.js} - 0 matches
  testPathIgnorePatterns: /node_modules/ - 3 matches
  testRegex:  - 0 matches
Pattern:  - 0 matches

```

I am running the selenium file from chrome Browser pwerfectly, but from Selenium-side-runner i only get this...

any idea?

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
