### ISSUE TITLE
Chromedriver Ruby code does not close browser window

### ISSUE THREAD

**Issue by kurmasz** [SeleniumHQ/selenium#781]
The Ruby code for the chormedriver does not appear to close the browser window.

When I run the following Ruby code, the chomedriver process quits, but the browser window is left open.

    require 'selenium-webdriver'
    driver = Selenium::WebDriver.for(:chrome, detach: false)

I'm using selenium-webdriver 2.46.2 with ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13] on Mac OS X 10.9.5.  I also see the same behavior on CentOS Linux.

(This issue isn't causing me any problems; I just happened to notice the behavior while investigating a different bug.)

**Comment by lukeis** [comment]
I can't reproduce this... everything works fine for me (and the process remains running)... OSX 10.10.4, ruby 2.2.2p95, chrome 43.0.2357.132,  chromedriver 2.15

**Comment by kurmasz** [comment]
Which process remains running? I thought the chromedriver process was supposed to terminate when the ruby process that created the chromedriver process terminates.

My understanding based on this discussion (https://github.com/SeleniumHQ/selenium/issues/742) is that  the chromedriver process should always be terminated (even if the user neglects to call `#quit`).  Setting the `detach` parameter to `false` should cause both chromedriver and the browser to quit, correct?

**Comment by p0deje** [comment]
The actual test case to reproduce would be something like this:

```ruby
require 'selenium-webdriver'

Selenium::WebDriver.for(:chrome, detach: false)
exit
```

In this case, ChromeDriver process exits with [at_exit](https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/chrome/service.rb#L64) hook. However, Chrome window is still shown (regardless of `detach` option).

I'm not sure if this is an expected behavior, but, if it's not, I guess it should be reported against ChromeDriver.

**Comment by lukeis** [comment]
seems like the ruby client is doing even more than the other client languages. Expected behavior (at least in java and python) if you don't call quit on chrome, it will leave both chromedriver and chrome running.

As Alex mentioned, this sounds more like a chromedriver bug if you expect them to kill the running browser with the process is killed.

chromedriver's issue tracker: https://code.google.com/p/chromedriver/issues/list
