### ISSUE TITLE
Relative Locator "near" doesn't work in some case 

### ISSUE THREAD

**Issue by takeya0x86** [SeleniumHQ/selenium#7851]
## 🐛 Bug Report

Relative Locator "near" doesn't work in some case.
I tried to find element near by "second" cell on this HTML (same of relative_locator_test.html).

```html
<table>
  <tr>
    <td id="first">1</td>
    <td id="second" style="width: 100px">2</td>
    <td id="third">3</td>
  </tr>
  <tr>
    <td id="fourth">4</td>
    <td id="center">5</td>
    <td id="sixth">6</td>
  </tr>
  <tr>
    <td id="seventh">7</td>
    <td id="eighth">8</td>
    <td id="ninth">9</td>
  </tr>
</table>
```

```java
driver.findElements(withTagName("td").near(By.id("second")))
```

I expected to find eight elements but actually found six elements. The "center" and "eighth" cell is missing. See below image, red is found cell.

<img width="167" alt="near_2" src="https://user-images.githubusercontent.com/13767532/70376459-b5693000-194c-11ea-8f30-d00865606286.png">

## To Reproduce

Add below test method to https://github.com/SeleniumHQ/selenium/blob/selenium-4.0.0-alpha-3/javascript/atoms/test/relative_locator_test.html .

And run FAILED.

```javascript
function testShouldBeAbleToFindAnElementNearSecond() {
  var found = bot.locators.findElements({relative: {root: {tagName: 'td'}, filters: [{kind: "near", args: [{id: "second"}]}]}});

  assertEquals(8, found.length);
  assertEquals("first", found[0].getAttribute("id"));
  // Note: an element is not near itself.
  assertEquals("third", found[1].getAttribute("id"));
  assertEquals("fourth", found[2].getAttribute("id"));
  assertEquals("center", found[3].getAttribute("id"));
  assertEquals("sixth", found[4].getAttribute("id"));
  assertEquals("seventh", found[5].getAttribute("id"));
  assertEquals("eighth", found[6].getAttribute("id"));
  assertEquals("ninth", found[7].getAttribute("id"));
}
```

## Expected behavior

Find ALL of near elements.

## Test script or set of commands reproducing this issue

See above.

## Environment

OS: macOS
Browser: Chrome
Browser version: 78.0.3904.108
Browser Driver version: ChromeDriver 78.0.3904.105
Language Bindings version: 4.0.0-alpha-3
Selenium Grid version (if applicable):

**Comment by pujagani** [comment]
Thank you for providing the details. The relative locators find the nearby element in the following manner as mentioned in the test comments:
" Elements are sorted by proximity and then DOM insertion order.
  Proximity is determined using distance from center points, so we expect the order to be:
   1. Directly above (short vertical distance, first in DOM)
   2. Directly below (short vertical distance, later in DOM)
   3. Directly left (slight longer distance horizontally, first in DOM)
   4. Directly right (slight longer distance horizontally, later in DOM)
   5-8. Diagonally close (pythagorus sorting, with top row first  because of DOM insertion order) "

In the attempt to re-create the issue with the Selenium Beta-2, I have noted the following results.
With the following script : 
 ```
 <table>
 <tr>
    <td id="first">1</td>
    <td id="second" style="width: 100px">2</td>
    <td id="third">3</td>
  </tr>
  <tr>
    <td id="fourth">4</td>
    <td id="center">5</td>
    <td id="sixth">6</td>
  </tr>
  <tr>
    <td id="seventh">7</td>
    <td id="eighth">8</td>
    <td id="ninth">9</td>
  </tr>
</table>
```
The result is 
["center", "eighth", "first", "third", "fourth", "sixth", "seventh", "ninth"]

If the width is removed from the second element, then the result is  : 
` ["first", "third", "center", "fourth", "sixth", "eighth", "seventh", "ninth"]`

It returns all the elements in the expected order. 

Please let me know if I am missing something in this context.

**Comment by diemol** [comment]
Closing this as we did not get more information or feedback after the previous comment.
