### ISSUE TITLE
geckodriver executable needs to be in path

### ISSUE THREAD

**Issue by ikp4success** [SeleniumHQ/selenium#7853]
## 🐛 Bug Report
https://stackoverflow.com/questions/40048940/geckodriver-executable-needs-to-be-in-path/40448974
Firefox - 70
gecko_driver - 0.26
python 3.7

```Message: 'geckodriver' executable needs to be in PATH.```
There doesn't seem to be an issue when you downgrade to pip install selenium==2.53.6, but then i hate to miss on new features, for example headless does not work on 2.53, also you get errors like

```selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmpjtz2dzvw If you specified a log_file in the FirefoxBinary constructor, check it for details.```

**Comment by barancev** [comment]
This is a question rather than an issue. For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) go
