### ISSUE TITLE
Selenium separate actions objects work differently than single actions object with procedures

### ISSUE THREAD

**Issue by KardoseR** [SeleniumHQ/selenium#7854]
## 🐛 Bug Report

If you instantiate an **Actions** object and build your Actions chain normally like 
**new Actions(driver).ClickAndHold().MoveByOffset(10,10).Perform();**

This will work differently than 
 **new Actions(driver).ClickAndHold().Perform();**
 **new Actions(driver).MoveByOffset(10,10).Perform();**

The ClickAndHold() Action will be cancelled on MoveByOffset()

Is this normal?

## To Reproduce

Detailed steps to reproduce the behavior:

## Expected behavior

Both scenarios should work the same (i guess?)

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by barancev** [comment]
This is a question rather than an issue. For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) go

**Comment by KardoseR** [comment]
No.

**Comment by KardoseR** [comment]
I dont see how this is not an issue as two identical set of instructions(mostly) perform differently.

**Comment by barancev** [comment]
As soon as you skipped most of the bug report template, it's rather question than an issue.

Please fill the template properly if you want it to be reopened.
