### ISSUE TITLE
SPM-Branch-Issue with continue scanning

### ISSUE THREAD

**Issue by akskulkarni** [SeleniumHQ/selenium#7881]
Hello Liang ,

    We have issue with automation of continue scanning with TAF .Could you please create template.
Could you please look into the issues.

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
