### ISSUE TITLE
[18960:6772:1226/104434.641:ERROR:CONSOLE(108)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/shell.js (108)

### ISSUE THREAD

**Issue by 12371601** [SeleniumHQ/selenium#7891]
## 🐛 Bug Report
[18960:6772:1226/104434.641:ERROR:CONSOLE(108)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/shell.js (108)

## Environment

OS: Windows 10
Browser: Chrome
Browser version:  70.0.3538.110 
Browser Driver version:  ChromeDriver 2.45
Language Bindings version: C#

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
