### ISSUE TITLE
Selenium WebDriver some url is not working

### ISSUE THREAD

**Issue by saileshkush95** [SeleniumHQ/selenium#7958]
## To Reproduce

Detailed steps to reproduce the behavior:
```
driver.get(
                'https://www.ccp.my-hosting-panel.com/Default.aspx?pid=Login&ReturnUrl=%2fDefault.aspx%3fpid%3dSpaceMailAccounts%26mid%3d102%26ctl%3dedit_item%26ItemID%3d1927293%26SpaceID%3d89439')
```
For more info please follow below link
https://stackoverflow.com/questions/33945853/selenium-webdriver-some-url-is-not-working
## Expected behavior

It only display error page

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS:  OSX
Browser:  :
Browser version: 
Browser Driver version: https://pypi.org/project/webdriver-manager/
Language Bindings version:  Python
Selenium Grid version (if applicable):

**Comment by barancev** [comment]
This is a question rather than an issue.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
