### ISSUE TITLE
InternetExplorerDriver sporadically captures wrong screenshots

### ISSUE THREAD

**Issue by itaibh** [SeleniumHQ/selenium#7967]
## 🐛 Bug Report

When trying to capture a specific webpage on IE 11, even though I see an element (SVG image) it sometimes doesn't show in the captured image.

## To Reproduce

1. Create a project from this gist: https://gist.github.com/itaibh/2caccf7206a622aaf2ee79479beabc9e
(it has a `pom.xml` file and a `.java` file)
2. Run the test.

## Expected behavior

All screenshots match the website. Currently the website looks like this:
![image](https://user-images.githubusercontent.com/140983/73245967-28a55a80-41b6-11ea-8f1f-91cd0aa484d4.png)

## Actual behavior

Sometimes these are the screenshots we get (only on IE):

![image](https://user-images.githubusercontent.com/140983/73246072-6609e800-41b6-11ea-90af-6cb2ff37a1e7.png)

or

![image](https://user-images.githubusercontent.com/140983/73246109-7b7f1200-41b6-11ea-9578-4be64d468322.png)

And sometimes none of the SVG images. Only the text is present.

I did notice the more commands we perform on the browser using the IEDriver, the more likely it is to reproduce the problem.

## Environment

OS:  Windows 10
Browser: Internet Explorer
Browser version: 11
Browser Driver version: IEDriverServer 3.150.1.0
Language Bindings version: Java 3.141.59

**Comment by diemol** [comment]
Hi @itaibh,

I went through the project and the website to reproduce the issue, I strongly believe this is not an IE nor Selenium issue.
The website has animated content based on scrolling and perhaps other inputs, and that's why the screenshots vary between executions. In general, the approach needs to be in a way where you can control and understand when the website is ready to take the screenshot and continue further with the validations you need to do.

If you want to get more ideas on how to tackle this challenge, feel free to post it to[StackOverflow](https://stackoverflow.com/questions/tagged/selenium) or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com/) where the community can help you as well.

**Comment by itaibh** [comment]
Thank you for taking a look at this. From the tests I ran I strongly
believe it IS an IEDriver issue, perhaps I didn't explain it correctly.
I also showed it to my co-worker Dave Haeffner who told me to file this
issue. He said he'll take a look at it but he didn't get to it.
Perhaps you can re-open this issue until he'll get to it?
Thanks.
Itai.

**Comment by jimevans** [comment]
The screenshot code in the IE driver is remarkably simple. It calls the Windows API `PrintWindow` function and not much else. If that API call isn’t capturing those images every time, it’s likely a browser or OS issue, and there’s precious little the driver can do about it.

**Comment by mmirold** [comment]
We have the same problem with IEDriver 3.141.59 on Windows 10 1903 (IE version is 11.175.18362.0). The problem is also present with IEDriver 3.12, so we would rule out a regression. We don't have the problem on Windows 7, so the OS or IE version appear to be the culprit. It seems that there is some internal buffer used for PrintWindow that is not refreshed after JavaScript scrolling (in the browser window itself, everything looks fine). All SVGs are cropped (or at least distorted in some way) by the amount of vertical space that has been scrolled (see the attached screenshot, which shows a web page after scrolling by 20px).

Adding delays after scrolling / before taking the screenshot did not help (so it does not seem to be a race condition). However, we have found that forcing a repaint of the entire page makes the problem disappear:
 
```javascript
            driver.executeScript("document.body.style.display = 'none'");
            driver.executeScript("document.body.style.display = 'block'");
```
This is quite invasive, so use with care.
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/432429/73561888-35e27380-445a-11ea-8f44-513bbe089997.png">

**Comment by mmirold** [comment]
The issue seems not to be fixed in Win 10 1909 and I did not find a simple workaround that could be triggered from JavaScript. @jimevans I have briefly looked into the `ScreenshotCommandHandler` code and I agree that there is not so much that can be done. Do you think there is any hope that a simple hack such as calling `PrintWindow` without `PW_CLIENTONLY` before the actual PrintWindow call could help? Or maybe using SendMessage directly (I am no Windows developer / user, so please apologize if that doesn't make sense). If you consider this a possibility, I will gladly install Visual Studio and try myself :-)

**Comment by mmirold** [comment]
Ok. I give up. It seems that IE11 on Win10 has some problem with the combination of PrintWindow, scrolling, and SVGs. In IEDriver, I have tried some variations on `PrintWindow`, `RedrawWindow`, and `UpdateWindow`, to no avail. In JavaScript, I have tried to redraw the SVGs by resetting the `src` parameter, changing dimensions of the SVG node. I have even tried to add cache breaker query parameters to the SVG src to force reloading of SVGs before taking a screenshot. But nothing has helped. Here is a small video that illustrates the problem. It shows a sequence of screenshots taken with IEDriver after scrolling 2px in every frame.
