### ISSUE TITLE
Active Element and Window Handle

### ISSUE THREAD

**Issue by danielricci** [SeleniumHQ/selenium#7975]
Im using WebDriver and Chrome

Let's say that I have 3 chrome windows opened.

How do I go about finding out the WindowHandle associated to the current active element of the web driver. I am looking at the window handles and they look like gibberish to me.

**Comment by danielricci** [comment]
Pathetic.

**Comment by AutomatedTester** [comment]
This is a great question for the google group. When you ask for the active element it will return the one for the active window. You can get that by asking for the ‘current_window_handle’

**Comment by danielricci** [comment]
> This is a great question for the google group. When you ask for the active element it will return the one for the active window. You can get that by asking for the ‘current_window_handle’
> […](#)
> On Jan 28, 2020, 2:06 PM +0000, Daniel Ricci ***@***.***>, wrote: Pathetic. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

The problem is that the active window is really not the `real` active window, its what Selenium `thinks` is active. And the window handle identifiers are using some nonsensical naming schema that has nothing to do with the actual window handle. At the very least the CDwindow-<identifier> should have an identifier that actual corresponds to the native window handle of the window, which can be easily found when spying on the window itself.

**Comment by AutomatedTester** [comment]
That is by design so you can run selenium AND still use your machine.

The active window in selenium is the one receiving the commands and it tells you it’s window handle if you ask for the current_window_handle.

We can’t get the OS level window handle from the browser which is what we’re controlling. It is not available.

Also relying on the OS level window handle doesn’t work well when you move to mobile as the concept is fundamentally different.

I am happy to discuss the design on slack/irc this week. Just ping me, my nick is @automatedtester

**Comment by danielricci** [comment]
Let's say I have three Chrome browser windows open, doesn't matter which one has focus.

When I ask the web driver which window handles it has, there are three unique identifiers corresponding to each window handle (this we already know). 

When I tell it to `WebDriver.SwitchTo().Window(someIdentifer)`, it is capable of doing the switch, therefore there is SOMETHING somewhere in the code that is able to know that the identifier "CDwindow-some-guid" that I a specifying means to focus on THIS PARTICULAR window, and there is code that actually can switch to THAT window. There has to be because if not then it would not be able to focus on ANY PARTICULAR window, which is not the case because then you wouldn't have a product.

Therefore, there is a way to specify that I want to focus on a particular window, however the unique identifier that I have actually have to work with on the web driver layer are unique identifier which just to serve to help the underlying system. I would not be surprised if this association is known rather on the chrome driver side of things (within the chromedriver.exe)

However, by design it would seem that that information is not available to the developer on the selenium side, all that is available is a unique identifier which doesn't correspond to anything but to help the internal system say that THIS WINDOW is represented by this particular unique identifier that the application has generated for itself.

We can call it a `by design thing` thats not a problem, but to a developer trying to push the boundaries with automation with this framework, its a limitation. Also considering that there are many threads on the internet asking to do this and the only viable way is to cycle through all the windows and compare something like the window title, it seems like this is a good enhancement request, if it reaches the right ears.

When I use the C# UI Automation framework by Microsoft I can get an AutomationElement and search for the window handle associated to that AutomationElement, and because my application has UIA support out of the box, I can actually get this info. What sucks is that Selenium/WebDriver has unique identifier that can't be used to represent an actual window handle, and window handles are unique so they should just have been used instead. I don't see how it would have changed anything in the system, at the end of the day a unique identifier is a unique identifier, just prepend CDwindow to it and we could just regex the identifier and get the actual window handle.

**Comment by AutomatedTester** [comment]
A lot of what you have here has a lot of incorrect assumptions about how the browser and OS interact with each other while Selenium is in control of the browser. A lot of what Selenium does is to hide the differences between OSes and Browsers in a way that should never matter to the end user. 

> Let's say I have three Chrome browser windows open, doesn't matter which one has focus.
> 
> When I ask the web driver which window handles it has, there are three unique identifiers corresponding to each window handle (this we already know).
> 
> When I tell it to `WebDriver.SwitchTo().Window(someIdentifer)`, it is capable of doing the switch, therefore there is SOMETHING somewhere in the code that is able to know that the identifier "CDwindow-some-guid" that I am specifying means to focus on THIS PARTICULAR window, and there is code that actually can switch to THAT window. There has to be because if not then it would not be able to focus on ANY PARTICULAR window, which is not the case because then you wouldn't have a product.
> 

Here we are doing a switch but this is not an OS level switch to a window in the sense that this is a .NET application. This is actually doing a switch to a different browser context. If you have a browser that has multiple tabs open then we call `drive.window_handles` it will return all the browser contexts that are available to move to. This could be a tab or brand new process in the mobile case. There is a high level note in the spec prose for [`Switch to Window`](https://w3c.github.io/webdriver/#switch-to-window). You can also see the [implementation in Firefox](https://searchfox.org/mozilla-central/source/testing/marionette/driver.js#1608-1651)

Once we know what context we are running in we will inject  commands into it to manipulate the window. This works in all OSes, including mobile, as well as working in headless when there is no real window that is taking focus. Focus here is a somewhat mythical construct that means events that we make sure that browser fires the [focusing steps](https://html.spec.whatwg.org/multipage/interaction.html#focusing-steps) when we are doing keyboard or mouse interactions.

> Therefore, there is a way to specify that I want to focus on a particular window, however the unique identifier that I have to work with on the web driver layer are unique identifier which just to serve to help the underlying system. I would not be surprised if this association is known rather on the chrome driver side of things (within the chromedriver.exe)
> 
> However, by design it would seem that that information is not available to the developer on the selenium side, all that is available is a unique identifier which doesn't correspond to anything but to help the internal system say that THIS WINDOW is represented by this particular unique identifier that the application has generated for itself.
> 
> We can call it a `by design thing` thats not a problem, but to a developer trying to push the boundaries with automation with this framework, its a limitation. Also considering that there are many threads on the internet asking to do this and the only viable way is to cycle through all the windows and compare something like the window title, it seems like this is a good enhancement request, if it reaches the right ears.

I am not against seeing about putting this into WebDriver but how would this work on **all OSes**  and **all browsers**. Selenium, by design, only offers features that we can guarantee the same level of support across everything. If there is a feature that will only work in one browser or one OS we ignore that feature. This is one the key items when designing and implementing any feature in Selenium.

> When I use the C# UI Automation framework by Microsoft I can get an AutomationElement and search for the window handle associated to that AutomationElement, and because my application has UIA support out of the box, I can actually get this info. What sucks is that Selenium/WebDriver has unique identifier that can't be used to represent an actual window handle, and window handles are unique so they should just have been used instead. I don't see how it would have changed anything in the system, at the end of the day a unique identifier is a unique identifier, just prepend CDwindow to it and we could just regex the identifier and get the actual window handle.

If it works in Microsoft, amazing, but can we access the same in Linux and OSX? How would this work on mobile devices?

**Comment by danielricci** [comment]
If Selenium/SomeDriverImplementation is capable of having UUID's that represent valid window/tab switches, then it might be capable of mapping those UUIDs to something more abstracted and presented to a developer that can be better used in cases where UUIDs aren't known because of runtime constraints, such as when the user is driving a browser. This abstraction can use some unique property of all web pages/tabs/etc, maybe it could even be a script that is injected when it detects some context.

Without looking at the code I cannot say how hard this will be, however what I am suggesting should not be a difficult thing to do conceptually, unless the underlying system doesn't permit this.

I do not know how this would be implemented within the framework, and I do not have an answer to how this would work everywhere, and that is not the point of this request. If it is not possible then so be it, but its still a valid request on my end.

**Comment by titusfortner** [comment]
UUIDs are only known when you ask the driver for the list of open handles. If you're dealing with more than two, you have to switch to each and make a query to determine desired context. For example, this is how Watir wraps the Ruby bindings to search by title/url:
https://github.com/watir/watir/blob/master/lib/watir/window.rb#L230

Also, I just found out that Appium implements a `fullContextList` for iOS, which I assume something similar might be an option for the browser vendors to support that could be proposed to add to the spec? (https://appiumpro.com/editions/61)
