### ISSUE TITLE
Add support for identifying a window handle with an active element

### ISSUE THREAD

**Issue by danielricci** [SeleniumHQ/selenium#7976]
## 🚀 Feature Proposal

Im using WebDriver and Chrome

Let's say that I have 3 chrome windows opened.

How do I go about finding out the WindowHandle associated to the current active element of the web driver. I am looking at the window handles and they look like gibberish to me.

## Motivation

N/A

## Example

N/A

**Comment by diemol** [comment]
💬 It looks like this is a question rather than an issue, this is not a support forum.
  💡 A better way to address this is:
  * 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
  * 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
  * 🗣 Join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com/) where the community can help you as well

**Comment by diemol** [comment]
@danielricci I saw you created a few issues and you just want to ask a question, join us in Slack where many people are there and some of them can give you a hand and answer your queries.
