### ISSUE TITLE
When using java ChromeDriver on www.amextestsystem.com pageSource returns null

### ISSUE THREAD

**Issue by mstrelex** [SeleniumHQ/selenium#8072]
## 🐛 Bug Report

When using java ChromeDriver on www.amextestsystem.com pageSource returns null
The issue is **not** with ChromeDriver - see details here https://bugs.chromium.org/p/chromedriver/issues/detail?id=3371#c1

_The java bindings are issuing a specific javascript call instead of allowing ChromeDriver to make the correct call_

## To Reproduce

```
String driverPath = "C:\\chromedriver.exe";
System.setProperty("selenium.chrome.driver", driverPath);
ChromeDriver driver = new ChromeDriver();
driver.navigate().to("http://amextestsystem.com");
System.out.println(driver.getPageSource());
```

driver.getPageSource() returns null.

## Environment

OS: macOs and Windows
Browser: Chrome
Browser version: 80
Browser Driver version: 80
Language Bindings version: Java

**Comment by mstrelex** [comment]
Anyone?

**Comment by s-glatshtein** [comment]
Any information regarding this issue? I am experiencing the same issue.
Any information i can provide to expedite solving this issue?

**Comment by barancev** [comment]
The target site is down, so I can't reproduce the issue.

Is there any other site that suffers of the same issue?

**Comment by prasannaakhil** [comment]
http://amextestsystem.com is currently not working, so you are experiencing null error.
i think so..

**Comment by s-glatshtein** [comment]
Hi,
I've had this problem before the website went down. if i called `driver.getPageSource` it would return null, but if at the same point of code i would query the /source endpoint in selenium using postman, i'd get the actual source

**Comment by barancev** [comment]
I believe that it's an actual issue, but I can't reproduce it on any other site I treid.

**Comment by s-glatshtein** [comment]
Hello,
I've gone across old logs from my computer and found the log i took when calling `driver.getPageSource()`. I'm aware the website isn't up, but maybe this can help you identify the problem
[pageSourceNull.txt](https://github.com/SeleniumHQ/selenium/files/4317056/pageSourceNull.txt)

**Comment by barancev** [comment]
Unfortunately it does not help. Yes, we can see from the log that `ExecuteScript` command returns `null`. And this means that the issue is even more devastating, it's not tied to `pageSource` command only. But it's impossible to move it further without ability to reproduce and debug it.

**Comment by mstrelex** [comment]
Website is currently not accessible and perhaps won't be. Closing the issue.

**Comment by mstrelex** [comment]
here's the page source if this might help, but I couldn't reproduce the problem when hosting this source on another domain other than http://www.amextestsystem.com
[pageSource.html.zip](https://github.com/SeleniumHQ/selenium/files/4330660/pageSource.html.zip)

**Comment by TriciaCrichton** [comment]
We reproduced this when the user reported it for ChromeDriver: https://crbug.com/chromedriver/3371

The issue is that the java bindings don't use the w3c endpoint for Get Page Source. Instead, the java bindings issue a custom javascript call to retrieve page source. The python bindings do call the proper endpoint, and were able to retrieve the target websites source. The java bindings should call the proper endpoint: 	/session/{session id}/source

please see Java: https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/codec/w3c/W3CHttpCommandCodec.java
python: https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/remote_connection.py
https://w3c.github.io/webdriver/#get-page-source

A second user reported the same issue & included a repro: see https://crbug.com/chromedriver/3403.
This repros using the java bindings, but not using the python bindings.

ExecuteScript is a problem on these websites, but if page source did not attempt an execute script call, it would work. I didn't see any comment in the code explaining why the specific end point wasn't used.

**Comment by barancev** [comment]
@TriciaCrichton Yes, Java binding can use this endpoint for `pageSource` command. But the issue is still actual if `executeScript` does not work as expected.

**Comment by TriciaCrichton** [comment]
@barancev Agreed, executeScript is a problem, but a different one.

We've had a dozen or so users with similar issues. In the cases we've been able to fix, the websites were redefining basic javascript objects which interfered with ChromeDriver or Selenium javascript atoms.
