### ISSUE TITLE
Run test case on all nodes.

### ISSUE THREAD

**Issue by Kanti1702** [SeleniumHQ/selenium#8080]
## 🚀 Feature Proposal

I have requirement of running same set of test cases on all nodes which will create some dynamic data.

## Motivation

It is required to configure prerequisite data in web application, which should be there for all nodes. And each nodes is running it's own web application instance.

## Example

Let's say there is some current date specific data should be there to perform some operation. Now for this type of dynamic data, it is not possible to enter as master data so we are inserting as prerequisite data before actual test execution starts.

**Comment by diemol** [comment]
💬 It looks like this is a question rather than an issue, and seems to be not related to Selenium at all.
  💡 A better way to address this is:
  * 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
  * 🗣 Join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com/) where the community can help you as well
