### ISSUE TITLE
open a normal window, then open a incognito window, then driver.quit()

### ISSUE THREAD

**Issue by gMan1990** [SeleniumHQ/selenium#8107]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

## Motivation

Please outline the motivation for the proposal.
1. start chrome normal
2. open a incognito window, login user a, get cookie, close window
3. open a incognito window, login user b, get cookie, close window
4. driver quit
5. got 2 useable cookie with start chrome just one times

## Example

Please provide an example for how this feature would be used.

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
