### ISSUE TITLE
Chromedriver.exe has stopped working" message needs to be more communicative

### ISSUE THREAD

**Issue by AndersBillLinden** [SeleniumHQ/selenium#8121]
## 🐛 Bug Report

Some days, my selenium tests makes a popup come up saying that chromedriver.exe has stopped working.

Is it possible to get a more descriptive error message? Developers are used to better error messages than this.

## To Reproduce

Not possible to produce on demand since the dialog comes up on unexpected events.

## Expected behavior

I expect some other messages than "has stopped working"

## Test script or set of commands reproducing this issue

I am filling out this section just to not have the questionnable selenium assistant bot automatically closing this issue.

## Environment

OS: Windows 10
Browser: Chrome

**Comment by jimevans** [comment]
@AndersBillLinden Is this on Windows? Is the popup a system dialog that looks similar to this?

![BB7E8D84-0B22-42BB-A144-A662C8132EA8](https://user-images.githubusercontent.com/352840/77043021-1a441580-6993-11ea-86a8-220af8f9acc0.png)

If so, there is nothing Selenium can do about the dialog. It’s caused by chromedriver “crashing” (scare quotes intentional), and is a system dialog that appears whenever any Windows application behaves similarly. Likewise, there’s nothing the Selenium team can do to change the internal behavior of chromedriver.exe to prevent this dialog, as that code is built and maintained by the Chromium team. They can’t change the content of that dialog either, but to fix the issue to prevent the crash would require an issue be filed in their issue tracker.

**Comment by AndersBillLinden** [comment]
Oh, I can close this.
