### ISSUE TITLE
[4.0.0-alpha5]Default to 'standalone' flag if nothing is passed as CliCommand

### ISSUE THREAD

**Issue by Dharin-shah** [SeleniumHQ/selenium#8251]
## 🚀 Feature Proposal

In Selenium-4.0.0-alpha-5 we need to pass a standalone flag if the jar needs to run in standalone mode. It makes sense that selenium starts in standalone mode by default when run
`java -jar selenium-server-4.0.0-alpha-5.jar`
instead of 
`java -jar selenium-server-4.0.0-alpha-5.jar standalone`

## Motivation

This was a behaviour in the previous versions. If someone is running standalone jar automatically, it may break and need to have handling.

## Example

Please provide an example for how this feature would be used.
`java -jar selenium-server-4.0.0-alpha-5.jar`

**Comment by diemol** [comment]
Hi @Dharin-shah,
We discussed this proposal and we decided to not implement it, it is true that some scripts out there will break since the parameter `standalone` is needed.

But the complexity to change those scripts is low since the only change needed will be to actually add the `standalone` parameter.  In any case, no other parameters (like port or host) can be added without specifying a role first.

The motivation to leave it like that is to show the users all the options available before making a decision for them on which mode to use the Grid.
