### ISSUE TITLE
Cross-Site Scripting (XSS) in hub's web interface

### ISSUE THREAD

**Issue by mleblebici** [SeleniumHQ/selenium#8259]
## 🐛 Bug Report

A cross-site scripting (XSS) vulnerability exists in Selenium Grid hub's web interface. The vulnerability is located in /grid/console page where unvalidated user input from node's configuration is displayed back to the users. 

## To Reproduce
A node can register to a hub using the following configuration file, where an XSS payload is given in the hub parameter. Since the payload is written as a URL GET parameter value, the node is still be able to register to the hub.
![selenium_xss3](https://user-images.githubusercontent.com/19292195/80546145-99c6fa80-89bd-11ea-9da9-fa33f13aaae7.png)
Once the hub's web interface is opened, injected JavaScript code is executed on the user's browser, as shown below.
![selenium_xss1](https://user-images.githubusercontent.com/19292195/80546316-fde9be80-89bd-11ea-96dd-3507be8f72ea.png)
Also, injected JavaScript code can be seen by inspecting the page source.
![selenium_xss2](https://user-images.githubusercontent.com/19292195/80546344-0b9f4400-89be-11ea-9fab-906903a7766d.png)

## Expected behavior

The contents of configuration file should be encoded before being displayed to users.

## Environment

The vulnerability exists regardless of the environment. 
The test is done using Selenium Grid v3.141.59.

**Comment by diemol** [comment]
Thank you for reporting this @mleblebici, nevertheless, we need to close this because:
- Grid 3.x is not under development anymore, the code is not even present in the tree.
- Grid 4 will have a different UI and we will double-check this issue is not happening.
- Whenever someone deploys a Grid, it should be done in its own environment under restricted network permissions.
