### ISSUE TITLE
[NodeJS] ie.ensureCleanSession not working

### ISSUE THREAD

**Issue by Tae69** [SeleniumHQ/selenium#8271]
## 🐛 Bug Report

Adding capability `ie.ensureCleanSession` for IE is not working.

Don't know if it's related, but I've tried:
- Run command prompt in Administrator Mode
- Uncheck 'Enable Protected Mode' in all tab/section

## To Reproduce
Detailed steps to reproduce the behavior:

- Run the script below, it will output driver capability.

## Expected behavior

`ie.ensureCleanSession` should be `true`

## Test script or set of commands reproducing this issue

```javascript

const webdriver = require('selenium-webdriver');

(async function () {
    let driver = await new webdriver.Builder()
        .withCapabilities({
            'ie.ensureCleanSession': true,
        })
        .forBrowser('internet explorer', '11')
        .build();

    console.log(await driver.getCapabilities());
})();
```

## Environment

OS: Windows 10 v1903 build 18362.778 64-bit
Browser: Internet Explorer
Browser version: IE 11.778.18362.0
Browser Driver version: IEDriverServer.exe 3.150.1.0 (32-bit)
Language Bindings version: NodeJS v12.16.3
Selenium Grid version (if applicable): -

**Comment by Harsha509** [comment]
Hi @Tae69 ,

I've noticed the issue and fixed in commit [f0234ab](https://github.com/SeleniumHQ/selenium/pull/8152/commits/f0234ab2622c04c51aa488355d1ad4ffe345de04)

The fixes will be available in next alpha release!

Also, We need to set capabilities using IEOptions. Here is the document link on how to do it (click on JS to see the code)

https://www.selenium.dev/documentation/en/driver_idiosyncrasies/driver_specific_capabilities/#ensurecleansession

Hope this helps!

Regards,
Harsha
