### ISSUE TITLE
Testing autofill of username/password: is there a way to setup the browser so it already stores a pair <username,password>

### ISSUE THREAD

**Issue by bitliner** [SeleniumHQ/selenium#828]
I need to test the browser auto-fill for a login form (included browsers like IE9).

This means when the browser opens it should already have a specific pair <username, password> stored in it.

Does Selenium offer an API to store in the browser this information?

Or is the only way to do it  manually (logging 2 times to let the first time store the pair <username, password>).

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
