### ISSUE TITLE
IEDriver 3.150.+ sendKeys() slow as hell

### ISSUE THREAD

**Issue by black-snow** [SeleniumHQ/selenium#8384]
## 🐛 Bug Report

I upgraded from IEDriver `3.14.0` to `3.150.1` (hoping to fix some weird bug) but now `sendKeys()` is slow af - it takes ~30 sec to enter a single character. Thus filling out a form takes like 10 minutes.

## To Reproduce

* Have IEDriver `3.150.1` set up with a hub and a single node (all on the same machine).
* Load any page with a form.

```java
final DesiredCapabilities dc = DesiredCapabilities.internetExplorer();
dc.setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, true);
dc.setCapability("browser_version", "11.0");
dc.setCapability("requireWindowFocus", true);
dc.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
driver = new RemoteWebDriver(new URL(remoteMachineUrl), dc);
```

Get some input field and send some input:
```java
driver.findElement(By.cssSelector("input[id^=\"someId\"]")).sendKeys("some input");
```

## Expected behavior

Input entered in human-like speed.

## Test script or set of commands reproducing this issue

s.a.

## Environment

OS: Windows 7 SP1 64 bit
Browser: IE 11
Browser version: 11.0.9600.19230
Browser Driver version: 3.150.1 64 bit
Language Bindings version: Java 3.141.59
Selenium Grid version (if applicable): Selenum server 3.141.59 rev e82be7d358

**Comment by black-snow** [comment]
Reverted to `3.14.0` and it's still slow - issue seems to be somewhere else, need to investigate.

**Comment by jimevans** [comment]
@black-snow It’s almost guaranteed that the issue is a mismatch between the “bit-ness” of the driver and the instance of IE you're driving. You more than likely need the 32-bit version of the driver, even though you’re on 64-bit Windows. There are historical and [technical](http://jimevansmusic.blogspot.com/2014/09/screenshots-sendkeys-and-sixty-four.html) reasons for this, but try the 32-bit driver and see if things change.

**Comment by black-snow** [comment]
@jimevans thanks, that's actually what I just did and it solves the issue.
