### ISSUE TITLE
Use of "takesElementScreenshot" to check if W3C Compliant browser might break compatibility with third-party drivers

### ISSUE THREAD

**Issue by NickAb** [SeleniumHQ/selenium#843]
`"takesElementScreenshot"` is used to check if driver is w3c complaint and css selectors should be used for findElement and findElements commands. This might break comparability with third-party drivers, e.g. mobile drivers.
`"takesElementScreenshot"` is not related to ability of a driver to find anything by css selector in general. Maybe [this](https://github.com/SeleniumHQ/selenium/blob/06fd3f334462af579674e1015136232f23fdb615/py/selenium/webdriver/remote/webdriver.py#L141-L142) check can be replaced with a more specific one?

```py
# Quick check to see if we have a W3C Compliant browser
self.w3c = "takesElementScreenshot" in self.capabilities
```

There is a  `cssSelector` capability in [WebDriver spec](https://w3c.github.io/webdriver/webdriver-spec.html#element-location-strategies) which seems to be more suitable:
> If the browser can support locating elements by CSS Selector, it must set the "cssSelector" capability to boolean true when responding to the newSession().

**Comment by AutomatedTester** [comment]
Unfortunately, as of this time, there are no capabilities that say W3C other than ones that are related to new features.  You have spotted a bug in the spec. When we [discussed](http://www.w3.org/2014/02/25-testing-minutes.html) (search for 24225 for the discussion) [bug 24225](https://www.w3.org/Bugs/Public/show_bug.cgi?id=24225) cssSelector was going to be dropped and since everything can be described as CSS selectors it was decided to move to that.

**Comment by nwlunatic** [comment]
@AutomatedTester So Webdriver API should not be used to any kind of test automation except browser one? And selenium team does not seek to make a desktop and/or mobile compatible API?
