### ISSUE TITLE
Drag and drop is not working in selenium automation with SVG tag : ElementNotInteractableException

### ISSUE THREAD

**Issue by RamjiRamachandran** [SeleniumHQ/selenium#8528]
## 🐛 Bug Report

Drag and drop is not working in selenium automation with SVG tag : ElementNotInteractableException

## To Reproduce

"div class="entry csf-icon hive-source" draggable="true" data-action="create.dfle-HiveSource" title="Create HiveSource"

Trying to drag above div element inside below SVG element in automation. But we are getting error "ElementNotInteractableException: Message: element not interactable"

"svg width="100%" height="100%" style="touch-action: none; user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);" data-element-id="DataFlow" class=""  g class="viewport" transform="matrix(1,0,0,1,87.00000256299973,-273.5000081807375)" /g /svg"

## Expected behavior
On drag on drop , it should populate the new "g" rectangle inside "g class="viewport" "

## Environment

Browser: Chrome

**Comment by diemol** [comment]
@RamjiRamachandran you can do a drop only on elements that can be interacted with. Please double check your locators. In addition, this issue is ignoring most of the required fields from the template. Complementing that, looks like this is a question rather than an issue.
  💡 A better way to address this is:
  * 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
  * 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
  * 🗣 Join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well
