### ISSUE TITLE
Problem with some special key and sending key with firefox driver

### ISSUE THREAD

**Issue by rdpdo** [SeleniumHQ/selenium#8548]
## 🐛 Bug Report

I was trying making zoom for a long time and just saw that some special key do not work. For example in python :

driver.get("http://www.google.fr")
elm = driver.find_element_by_name("body")

ActionChains(driver).key_down(Keys.CONTROL).send_keys(Keys.NUMPAD2).perform() <= Work OK (scroll down)
ActionChains(driver).key_down(Keys.CONTROL).send_keys(Keys.ADD).perform()           <= Do not work (no zoom-in...)

So CTRL+page down work but CTRL++ no... 

If someone know how to make zoom ? Thanks !

OS: Windows 10
Browser : Firefox
Browser version: 78.02 64bits
Browser Driver version: Geckodriver

**Comment by diemol** [comment]
💬 It looks like this is a question rather than an issue.
  💡 A better way to address this is:
  * 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
  * 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
  * 🗣 Join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well
