### ISSUE TITLE
Send registration-secret via header for web calls

### ISSUE THREAD

**Issue by AutomatedTester** [SeleniumHQ/selenium#8559]

**Comment by AutomatedTester** [comment]
@adamgoucher could you fill in details what is expected here and how people may approach this problem. If you can't do it then I can see about maybe assigning

**Comment by adamgoucher** [comment]
The idea here is that with the registration-secret, we can now determine that a worker node is 'authorized' to connect to a hub and start to receive commands. But once its registered, we don't do any further checks that something has happened after that. The worker node should send the secret as an http header (X-REGISTRATION-SECRET or similar) as part of every message sent to the node (either originating from its self or as a response to something from the hub) which is then checked before processing the payload.

**Comment by raju249** [comment]
Thanks @adamgoucher 

I will look into this issue.

**Comment by raju249** [comment]
Hey @adamgoucher 
I am trying to map the changes for this issue.

So if I understand correctly, what we intend to do here is use the registration secret defined [here](https://github.com/SeleniumHQ/selenium/blob/trunk/java/server/src/org/openqa/selenium/grid/node/local/LocalNode.java#L101) and send it as header to responses defined in [NodeServer](https://github.com/SeleniumHQ/selenium/blob/trunk/java/server/src/org/openqa/selenium/grid/node/httpd/NodeServer.java)
and then validate the same before processing the payload at appropriate places.

Is that correct?

**Comment by adamgoucher** [comment]
@raju249 mostly correct, I believe. 

1) Start a hub

java -jar selenium.jar \
       hub \
       --https-private-key /path/to/key.pkcs8 \
       --https-certificate /path/to/cert.pem \
       --registration-secret cheese

2) Start a node

  java -jar selenium.jar \
       node \
       --https-private-key /path/to/key.pkcs8 \
       --https-certificate /path/to/cert.pem \
       --detect-drivers \
       --registration-secret cheese

Now, what we have done is assure that the node is authorized to talk to the hub by passing the shared password over the wire (via https)

Now, in theory, a back actor could replace the node instance with their own without knowing the secret because the grid has authorized that IP to communicate with the hub and receive commands. What we need to do is continue to send, with each request and acknowledgement of command, health check, etc., the secret as well. 

The communication can only ever be node -> hub. The node has to trust the hub.

**Comment by shs96c** [comment]
There's still some work to be done here :)

**Comment by raju249** [comment]
@diemol - AFAIK, I think you added code to fix this right? 🤔

**Comment by diemol** [comment]
I believe this was completed. We can always revisit in case something was left.
