### ISSUE TITLE
Chrome starting with version 44 fails to accept keystrokes via WebDriver after sendKeys("") to several elements on the page

### ISSUE THREAD

**Issue by ZathrasOne** [SeleniumHQ/selenium#856]
Basically, what I am doing is getting by xPath a list of potential focus elements, using sendKeys("") to go to each element, getting the current element, then checking to see if the correct element has focus (to generate a list of focusable elements). Then I go to the first focusable element on the page and tab through the page using sendKeys(keys.TAB). Up until Chrome Version 44 that worked great, but now when I go to sendKeys(keys.TAB) through the page after the initial scan the focus does not move. Is this a problem with Chrome, or did something in the Chrome API change requiring a change in the Chrome driver?

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by lukeis** [comment]
also log chromedriver related issues on the chromedriver project:

https://code.google.com/p/chromedriver/issues/list
