### ISSUE TITLE
What is the equivalent of "refreshed" expected condition in Python?

### ISSUE THREAD

**Issue by norbertpy** [SeleniumHQ/selenium#857]
Is there any alternative to Java's [refreshed][1] expected condition in Python? I have a problem which I think `refreshed` would solve it. If it's not, is it easy to implement? Any pointer?

Thanks.
[1]: http://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/support/ui/ExpectedConditions.html#refreshed-org.openqa.selenium.support.ui.ExpectedCondition-

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
