### ISSUE TITLE
ImportError: sys.meta_path is None, Python is likely shutting down when calling self.driver.quit() within __del__(self)

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#8571]
## 🐛 Bug Report

ImportError: sys.meta_path is None, Python is likely shutting down error is observed when calling `self.driver.quit()` within `__del__(self)`

## To Reproduce

Detailed steps to reproduce the behavior:

If we pass `self.driver.quit()` within `def __del__(self):` the following error is observed:

```
Exception ignored in: <bound method PythonBot.__del__ of <__main__.PythonBot object at 0x028172F0>>
Traceback (most recent call last):
  File "C:\Users\Soma Bhattacharjee\Desktop\Debanjan\PyPrograms\init_del_in_python_class.py", line 17, in __del__
  File "C:\Python\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 158, in quit
  File "C:\Python\lib\site-packages\selenium\webdriver\common\service.py", line 151, in stop
  File "C:\Python\lib\site-packages\selenium\webdriver\common\service.py", line 122, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down
```

Where as if we do `self.driver.close()` no errors are observed.

Seems, earlier similar issue was reported in #3330 and the #3263 merge addressed the issue. However, the same issue seems to prevail when using python classes.

## Test script or set of commands reproducing this issue

Sample Python Code:

```
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC

class PythonBot:
    def __init__(self,my_string):
        self.my_string = my_string
        self.driver = webdriver.Chrome(executable_path=r'C:\WebDrivers\chromedriver.exe')

    def send_text(self):
        driver = self.driver
        driver.get('https://www.google.com/')
        WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.NAME, "q"))).send_keys(self.my_string)

    def __del__(self):
        self.driver.quit()

run = PythonBot('Selenium')
run.send_text()
```

## Environment

OS: Windows 10
Browser: Chrome
Browser version:  v84.0.4147.89
Browser Driver version: ChromeDriver 84.0.4147.30
Language Bindings version: Python 3.6.3
Selenium version (if applicable): selenium==3.141.0

**Comment by isaulv** [comment]
Using `__del__` in Python is a bad idea 99% of the time because the rules for when it runs is inconsistent, and it may not even run properly. In the current library implementation, `RemoteWebDriver` has a few object cycles, which can interfere with `__del__` making it troublesome.  Python is not C++ in this regard.

Here are some sensible solutions even if it may not be aesthetically pleasing:
1) using driver as a context manager. The latest version supports the context manager protocol so you can write:
```
driver = Chrome()
with driver:
  driver.get('http://google.com')
  driver.page_source
# driver will close after the with block.
```

2) In your class, add an explicit `quit()` method and explicitly call it. You may consider using a `try: finally` block to ensure it gets called when things fail.

3) register at an `atexit` function to kill the driver so when the program is done, it will kill the driver, before the system tears down everything.

**Comment by SalmonMode** [comment]
For some more context, `__del__` will always run when all references to that object have been eliminated. Python tracks this by having a counter attached to each object, where the number is the number of references that point to it. As each reference is eliminated, the counter is decremented by 1. When the counter reaches 0, it means no more references to it exist, and then Python runs its `__del__` method. However, it's possible for this counter to _never_ reach 0 in certain circumstances.

As @Dude-X  said, `__del__` is not guaranteed to run, and as such, is not a good place for cleanup code that needs to run (it's more for "nice to haves"). I second the suggestion for using a context manager, a `finally` block, or something similar.

Also, to clarify, the reason this issue wasn't seen when `driver.close()` was used, is because `close` just closes the window. It doesn't quit the session, meaning the session would still be active when `driver.close()` is used.

This was opened 22 days ago, with a solution provided 7 days ago, so I'll be closing this issue. If you're still having an issue, please comment here or make a new issue 🙂 .
