### ISSUE TITLE
StaleElementReferenceException in FindElements(By.TagName(“a”)))

### ISSUE THREAD

**Issue by parvizblack** [SeleniumHQ/selenium#8573]
## 🐛 Bug Report
I save site links with the following code, but in some sites, I encounter the following error:

OpenQA.Selenium.StaleElementReferenceException: "stale element reference: element is not attached to the page document (Session info: chrome=xx.x.xxx.xx)"

problem with (this site): https://namnak.com
`private string followlinks(string url)
{
    IWebDriver driver = new ChromeDriver(@"C:\");

    driver.Navigate().GoToUrl(url);

    //...
    //...
    //...

    foreach (var item in driver.FindElements(By.TagName("a")))
    {          
        var url2 = item.GetAttribute("href");
        //...
    }
}`

How can I solve this problem?

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Web Driver:

**Comment by SalmonMode** [comment]
When you "locate" an element with Selenium, you're really just getting a unique reference to that element's node in the DOM at that moment. This reference is then used for all subsequent requests relating to that element, which is how the browser knows what element you're talking about. A stale element exception occurs when that reference is no longer valid (because the DOM changed somehow). In order to get around it, you just need to get a fresh reference to the element by locating it again.
