### ISSUE TITLE
Dose webdirver support HTML5

### ISSUE THREAD

**Issue by lvyinshaoxia** [SeleniumHQ/selenium#860]
Recently, i use appium test web app using html in android application，but now out app has upgraded to html5, i want to know whether appium also can support html5?

At the same time, for firefox driver,chrome driver,Opera Driver,ios driver and android driver in selenium2, whether they can support html5?

I will thank you very much for your answer!

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
