### ISSUE TITLE
Send Selenium emoji with C # project

### ISSUE THREAD

**Issue by MillesC** [SeleniumHQ/selenium#8639]
I'm trying to send emojis through Selenium, but I can't.

My Project is C #, Selenium webdriver, Chromedriver.

My code:

 string Message = "😀👍";
 driver.FindElement(By.XPath("//*[@id='_glo']/div")).SendKeys(Message);

**Comment by ghost** [comment]
👋 Hi there! Thank you for creating this issue.

I am the Selenium Assistant Bot 🤖, I triage issues in this repository. If I can't do it, I label it to help maintainers identify issues that need triaging.

I am an Open Source project 🙌, post bugs or ideas [here](https://github.com/SeleniumHQ/selenium-assistant)!

**Comment by ghost** [comment]
❗️ It seems this issue is not using any of the supported templates

💡 Supported issue types are (they start with):

* 🐛 Bug Report (bugs found in a recent release)
* 🚀 Feature Proposal (a useful feature you would like to propose)
* 💥 Regression Report (a supported feature is not working anymore)

Issue templates help this project to stay in shape, please use them and fill them out completely. By doing that you are helping the project because the community and maintainers can provide prompt feedback, and potentially solve the issue.

If you are asking a question, a better way to address this is:

* 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
* 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
* 🗣 Join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com/) where the community can help you as well

If you think this is incorrect, please feel free to open a new issue.

Thank you for your contributions.
