### ISSUE TITLE
selenium-server-3.141.0 has CVE-2017-18640 vulnerability 

### ISSUE THREAD

**Issue by aleksandrOranskiy** [SeleniumHQ/selenium#8678]
## 🐛 Bug Report

Selenium server 3.141.0 has CVE-2017-18640 vulnerability - org.yaml_snakeyaml package, which fixed in 1.26 version of org.yaml_snakeyaml.

**Comment by diemol** [comment]
Hi @aleksandrOranskiy, thank you for reporting this.
However, Grid 3 is not under development anymore, and we do not patch old versions.
Grid 4 is being developed from scratch, and there are alpha releases already. we invite you to download it and check it
selenium.dev/downloads/

Closing since there is no action to take from us.
