### ISSUE TITLE
Select from dropdown in selenium-webdriver javascript

### ISSUE THREAD

**Issue by mathewkuruvila** [SeleniumHQ/selenium#8721]
How to select a value from drop down using selenium-webdriver JavaScript bindings. I do see that Select is available in Java. I have seen similar option in C# also. Couldn't find anything in JavaCcript to handle select option

**Comment by luukvhoudt** [comment]
Looking at [the documentation about working with select](https://www.selenium.dev/documentation/en/support_packages/working_with_select_elements), once there click on the JavaScript tab of any of the code examples. The code block will display:

> This feature is not implemented - Help us by sending a pr to implement this feature

To summarize this issue is not implemented into the NodeJS client yet.

---

Seems like a crucial feature, why is this not implemented yet? Any one here who would be able to give some guidance, so that contributors can start submitting PR's. I would love to do it but I'm kinda new to Selenium.
