### ISSUE TITLE
[Java] Cannot build multimodule maven project as selenium.api doesn't export org.openqa.selenium.internal

### ISSUE THREAD

**Issue by Auties00** [SeleniumHQ/selenium#8788]
Hello,
I'm using Selenium 4 alpha 6 and Java 11 in a multi-module maven 3.6.3 project. One of my modules requires in its module-info,java the following selenium modules:

    requires org.seleniumhq.selenium.api;
    requires org.seleniumhq.selenium.chrome_driver;
    requires org.seleniumhq.selenium.support;
Everything compiles fine if I remove all the code that needs the support module and the requires statement, but adding it back produces a compile time error:

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project     shared: Compilation failure: Compilation failure:
    [ERROR] C:/Users/alaut/IdeaProjects/AliexpressBot/shared/src/main/java/com.fabifont.aliexpress/account/AccountWorker.java:    [76,29] cannot access org.openqa.selenium.internal.FindsById

It looks like the support module needs some classes located in org.openqa.selenium.internal, this package though is only available in the api module. The support module requires the api module as visible from its maven-info.java, though the api module doesn't export org.openqa.selenium.internal as visible from its maven-info.java:
        
        requires transitive java.logging;
        exports org.openqa.selenium;
        exports org.openqa.selenium.html5;
        exports org.openqa.selenium.interactions;
        exports org.openqa.selenium.interactions.touch;
        exports org.openqa.selenium.logging;
        exports org.openqa.selenium.logging.profiler;
        exports org.openqa.selenium.mobile;
        exports org.openqa.selenium.net;
        exports org.openqa.selenium.virtualauthenticator;
which leads to an error.

**Comment by ghost** [comment]
❗️ It seems this issue is not using any of the supported templates

💡 Supported issue types are (they start with):

* 🐛 Bug Report (bugs found in a recent release)
* 🚀 Feature Proposal (a useful feature you would like to propose)
* 💥 Regression Report (a supported feature is not working anymore)

Issue templates help this project to stay in shape, please use them and fill them out completely. By doing that you are helping the project because the community and maintainers can provide prompt feedback, and potentially solve the issue.

If you are asking a question, a better way to address this is:

* 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
* 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
* 🗣 Join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com/) where the community can help you as well

If you think this is incorrect, please feel free to open a new issue.

Thank you for your contributions.
