### ISSUE TITLE
grid/api/ not working in Selenium alpha 6

### ISSUE THREAD

**Issue by hnestorova** [SeleniumHQ/selenium#8805]
## 🐛 Bug Report

In previous Selenium versions, after I start selenium web driver, I programatically got the IP of the node on which the tests is currently executed

## Expected behavior
return the IP of the node on which the test is being executed

## Test script or set of commands reproducing this issue

HttpHost host = new HttpHost(hostName, port);
  CloseableHttpClient client = HttpClientBuilder.create().build();
 URI testSessionURI = URI.create(String.format("http://%s:%s/grid/api/testsession?session=%s", hostName, port, ((RemoteWebDriver) driver).getSessionId()));
  HttpGet r = new HttpGet(testSessionURI);
String responseString=  EntityUtils.toString(client.execute(host,r).getEntity());

Or refer to:
https://rationaleemotions.wordpress.com/2016/01/15/where-did-my-test-run/

## Environment

OS: Windows 7
Browser: <Internet Exporer -->
Browser version: 
Browser Driver version: 3.150.1
Language Bindings version: IE 11.0.9600.19356
Selenium Grid version : Grid 4 [(4.0.0-alpha-6)](url)

**Comment by hnestorova** [comment]
![proxy_id_pb_1](https://user-images.githubusercontent.com/30794708/96364003-bd832600-1140-11eb-8d8e-e8a4c2697e9d.png)
![proxy_id_pb_2](https://user-images.githubusercontent.com/30794708/96364005-beb45300-1140-11eb-96c5-51b4d2985a20.png)

**Comment by hnestorova** [comment]
![proxy_id_pb_1](https://user-images.githubusercontent.com/30794708/96364042-f28f7880-1140-11eb-8bb3-5fb3be627aab.png)
![proxy_id_pb_2](https://user-images.githubusercontent.com/30794708/96364043-f3280f00-1140-11eb-906f-3e33e3c86a7a.png)

**Comment by shs96c** [comment]
Thank you for highlighting this!

It's not well documented yet, but the graphql endpoint is designed as a replacement for the old Grid APIs. I've raised #8816 to cover this use case.

**Comment by mcopjan** [comment]
Hi @shs96c, as far as I understand graphql endpoint will give you session information but what about overall grid information such as number of free and total slots? I am referring to slotCounts section from the http://hubIP:4444/grid/api/hub from selenium 3

`{
  "browserTimeout": 0,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "cleanUpCycle": 5000,
  "custom": {
  },
  "debug": false,
  "host": "xxxxxxxxx",
  "jettyMaxThreads": -1,
  "newSessionRequestCount": 0,
  "newSessionWaitTimeout": -1,
  "port": 4444,
  "registry": "org.openqa.grid.internal.DefaultGridRegistry",
  "role": "hub",
  "servlets": [
  ],
  "slotCounts": {
    "free": 49,
    "total": 50
  },
  "success": true,
  "throwOnCapabilityNotPresent": true,
  "timeout": 1800,
  "withoutServlets": [
  ]
}`

I am asking because we have a monitoring system in place (Prometheus on docker swarm) using https://github.com/wakeful/selenium_grid_exporter which relies  on the current selenium 3 grid api response structure

**Comment by dylanlive** [comment]
@mcopjan There's an example for querying free and total slots in the documentation:
https://www.selenium.dev/documentation/en/grid/grid_4/graphql_support/#querying-the-number-of-totalslots-and-usedslots-in-the-grid-

**Comment by mcopjan** [comment]
thanks @dylanlive I will give it a go
