### ISSUE TITLE
Firefoxdriver does not open Firefox with system default locale

### ISSUE THREAD

**Issue by binodpanta** [SeleniumHQ/selenium#885]
Basically, if I don't use any overrides and use new FirefoxDriver(), I see that Firefox still opens up as English Firefox on a Japanese machine. Chromedriver+chrome however appears to open up as Japanese. This actually affects some tests we have where tests make assumptions that the browser locale is already the default system locale (that only used to run with chrome, and now trying Firefox)

I checked about:config, and noticed a difference between the Selenium+Firefox (case1) and the default install of Firefox on the system (case2)

case1: intl.accept_languages=en
case2: intl.accept_languages=ja,en-us,en

So there it is. I could try to add these accept_languages setting to Firefoxprofile but I would have to track down the system locale myself and find the correct locale string to use. It seems like an onerous thing to do.

Also, the same firefox I am using with Selenium, if I launch directly  as firefox.exe, it does open up with the default system locale (japanese in this case)

Why does Firefox not open up with the default system locale when launched with FirefoxDriver?

**Comment by binodpanta** [comment]
For now I am forcing japanese case to work by always setting intl.accept_languages to 

ja,en-US,en

to mimic what I saw on default Firefox on Japanese. But my approach breaks down on other locales of course

**Comment by lukeis** [comment]
sounds like a potential firefox issue... but Selenium (when not specifying otherwise) uses a clean profile with no preferences set. It sounds like Firefox on first launch is defaulting to what version of the browser you downloaded (Mozilla provides separate downloads for each locale, which would default to the other). I assume you are actually running with the "English" firefox binary and thus why it keeps defaulting to that.

Selenium provides the mechanism to override the language preference via the profile preference, it may be ["difficult"](http://stackoverflow.com/questions/2469435/how-to-detect-operating-system-language-locale-from-java-code) to figure out what the system setting is, but that is outside the scope of the selenium project to do that.

**Comment by binodpanta** [comment]
Ok thanks for that clarification. So I understand this is more about a clean profile than using Firefoxdriver? I posted to Mozilla forums to see if they can help me. This would mean that I need to download and manage a Firefox package for each locale, which makes it harder for my browser package management system. But let's see what they say.
