### ISSUE TITLE
OpenQA.Selenium.DevTools.DevToolsSession.Network removed with version 4.0.0-alpha07

### ISSUE THREAD

**Issue by JMan7777** [SeleniumHQ/selenium#8862]
## 💥 Regression Report

OpenQA.Selenium.DevTools.DevToolsSession.Network was removed with version 4.0.0-alpha07.

## Last working Selenium version

Worked up to version: 4.0.0-alpha05

Stopped working in version: 4.0.0-alpha07

## Example code which is not longer working because of this:

```
OpenQA.Selenium.DevTools.DevToolsSession devTools = ((ChromeDriver)driver).CreateDevToolsSession();
await devTools.Network.Enable(new OpenQA.Selenium.DevTools.Network.EnableCommandSettings(), millisecondsTimeout: 10000).ConfigureAwait(false);
await devTools.SendCommand(new OpenQA.Selenium.DevTools.Network.SetCacheDisabledCommandSettings()
{
	CacheDisabled = true
}, millisecondsTimeout: 5000, throwExceptionIfResponseNotReceived: false).ConfigureAwait(false);
await devTools.Network.ClearBrowserCache(millisecondsTimeout: 5000, throwExceptionIfResponseNotReceived: false).ConfigureAwait(false);
```

OS: Windows 10
Browser: Chrome
Language Bindings version: .net core 3.1

**Comment by jimevans** [comment]
The .NET bindings now offer a version-independent API for the Chrome DevTools Protocol (CDP), which does not conform directly to the domains of CDP. This is to prevent the case where the Selenium project has to release a new version every six weeks, and that version would be tied to a specific version of Chromium-based browsers to guarantee interoperability with the protocol, which can be changed at the whim of a single browser vendor.

This version-independent API is still being shaped, and feedback would be welcome, but the intention is to allow a large portion (using the Pareto Principle) of users to enable their CDP-based use cases without interacting directly with the protocol domains themselves. It also sets the Selenium project up to better support the W3C’s currently-being-developed bidirectional WebDriver protocol.

However, if one feels that tying oneself to a specific browser and protocol version is desirable, there is an escape hatch that allows one to accomplish this. The code would look something like this:

    var devtoolsDriver = driver as IDevTools;
    var session = devtoolsDriver.CreateDevToolsSession();
    var domains = session.GetVersionSpecificDomains<V87.DevToolsSessionDomains>();

Some things to note: First, yes, this does tie your code to a specific version of Chrome. Yes, when Chrome updates, you may have exceptions being thrown. That, unfortunately, is the reality of relying on a browser’s version-specific protocol.

Second, yes, the above code snippet references version 87 of Chrome, when the most recent stable channel is version 86. There is a bug in the alpha 7 version matching code, which is already fixed by commit 8a20973, and will ship in beta 1.

**Comment by JMan7777** [comment]
Thx a lot for the explanation.

I understand your intentions but this will mean that source code has to be touched every time the chrome  driver changes.
In my case I use a web app in an azure docker container and not wanted to touch my code every time the chrome driver of the docker container Linux image changes. 
I will then most likely need to pin the chrome driver version in the docker build process to be able to use the newer version of Selenium.

Wouldn't it be possible that Selenium is checking the chrome driver version and if specific calls are possible?
So if the chrome driver version don't support the requested functionality it will throw an error and otherwise proceeds like in  4.0.0-alpha05.

Thx again.

**Comment by jimevans** [comment]
Unfortunately, CDP does not have any concept of “feature testing” that would allow a consumer to test for the availability of a given command. You were always at risk of the DevTools protocol changing out from underneath you; this now just makes that risk explicit.

I will consider adding an overload to the `CreateDevToolsSession` method that would “pin” your implementation to a specific CDP version, but this will be a hack that will be strongly encouraged. The way forward would be to help the Selenium project team shape the version-independent API so that It has the functionality you need.

**Comment by JMan7777** [comment]
Don't worry. I can live with the current workaround for me ;). I'm looking forward for the Selenium project team to shape the version-independent API that it can also have additional functionality covered. Thx & Stay safe.
