### ISSUE TITLE
Enforcing xpath lookup for drivers to lookup elements.

### ISSUE THREAD

**Issue by HenningL** [SeleniumHQ/selenium#8918]
The api for easy use of selectors is contra productive. All what a selenium api has to provide, is the xpath. It is the most open. You can redirect all others to xpath resolution. eg. By.id(theId) is the same as By-xpath(//*[@id = theId]). But implementors of the driver api might focus on implementing stuff for id, instead of focusing to implement xpath lookup.  Enforcing xpath lookup will drive the focus for future implementors of WebDriver-Api.

**Comment by twalpole** [comment]
@HenningL XPath can’t do everything CSS can (`input:checked` against actual page state for instance) and vice versa.

**Comment by HenningL** [comment]
Im developing testautomation for 5y now and i never needed css-selectors. your example , i think, is doable with xpath. The only issue i had to use cssselector was the shadow-dom access. hope that will be implemented like iframes, since iframe is obsolete and shadow-dom the new one. so..., i disagree. XPath is the only tech one should focus on.

 thx for your input :)! glad to exchange thoughts in the future.

**Comment by barancev** [comment]
To be honest, most `By` classes are internally converted to CSS selectors (not XPath, sorry). There are two reasons:

1) Converting to CSS selectors is more straightforward. If we take your example `By.id("theId")`, it corresponds to a rather long XPath query "//*[@id='theid']" and a much shorter and easier to read CSS selector `#id`. If we take a more complex example of searching by class the difference willl be even more obvious: `By.className("myclass")` would be converted to either CSS selector `.myclass` or an XPath query `//*[contains(concat(' ', normalize-space(@class), ' '), 'myclass')]`. Don't blame us for choosing a simpler implementation.

2) Browser vendors don't like XPath and we don't expect extening XPath support in near future (see for example this thread: https://github.com/whatwg/dom/issues/903). At the same time they implement all the recent CSS-related standards. It does not seem illogical to rely on the technology that has better support.

As for the API -- yes, we could remove all these `By.id`, `By.className` etc because they can be easily replaced by equivalent CSS selectors. But we don't think that the API for easy use of locators is contra productive from the customer point of view.

On the other side, we don't insist that all client binding libraries implement all the variety of `By` classes available in Java or C# clients, it's up to the binding author.
