### ISSUE TITLE
Security Vulnerability in Jquery 3.1.1 min version under Selenium 3.141.59

### ISSUE THREAD

**Issue by Afrina-Alam** [SeleniumHQ/selenium#8945]
## 🚀 Feature Proposal

We have recently run our organization vulnerability scan on the machine where Selenium is running ,and it is throwing security breach for Jquery 3.1.1.min.js version . And the Jquery has already worked on the security breach in there 3.5.0 version.  Can selenium also upgrades the Jquery Version within so that the selenium could run through without any breach . Thanks

## Motivation

Security Vulnerability avoidance from Selenium 

## Example

Please provide an example for how this feature would be used.

**Comment by AutomatedTester** [comment]
I can't seem to find this file in the selenium tree. 

You seem to have deleted from the template where it asks what version of selenium you're using. Could you let us know which version because currently feel like this is fixed. The selenium tree only has 3.5.1 in it and we don't seem to ship this to end users, or I can't find where we might

**Comment by Afrina-Alam** [comment]
Appreciate your quick response !
We are using Selenium 3.141.59 version 
Could You Please let us know after which release Jquery3.5.1 has been upgraded 
Thanks !

**Comment by AutomatedTester** [comment]
The fix is in the Selenium 4 alpha releases. You can use these as drop in replacements for Selenium 3 already.

**Comment by chibicitiberiu** [comment]
You are asking people to use a piece of software that's in "alpha" state (appears to be beta now), instead of the stable (but vulnerable) version 3 which I don't think this is very reasonable. We don't know what's broken, and because of our requirements, we cannot ship an "alpha" version to our customers.

I think this would be a reasonable request, to release updates for the stable version with updated (and not vulnerable) dependencies, at least until the stable release of 4.

**Comment by diemol** [comment]
You have a good point, however the code for Grid 3 is not present in the `trunk` branch anymore. We hoped to be faster in the Selenium 4 release but in open source, sometimes this things takes longer. We are taking this type of things into account for future releases.

If you feel like, you can take the `3.141.59` tag, update the dependency and build a new server from the instructions. 

Apologies for the incovenience, but we do not have the bandwidth to maintain two separate versions of the server.
