### ISSUE TITLE
Unable to access menu and submenu in a polymer UI screen in firefox browser

### ISSUE THREAD

**Issue by vnandhan** [SeleniumHQ/selenium#895]
I am not able to access the core-menu and sub-menu in polymer screen in Firefox browser.

Environment : 

Browser : Firefox 30
Selenium Web Driver : version 2.47
polymer : 1.0 
Url : https://www.polymer-project.org/0.5/components/core-menu/demo.html
Element tried to access : Topic1 ( at the bottom of above url).

Refer : screenshot attached.
 
![coremenu_polymer_issue](https://cloud.githubusercontent.com/assets/13692059/9132601/54ddbff0-3d12-11e5-9ab7-4da940f789db.png)

**Comment by ddavison** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#bug-reports)

**Comment by vnandhan** [comment]
Hi - sorry for the incorrect wordings. Though i am identifying element correctly, Selenium was not able to click menu and submenu in the polymer screen in Firefox browser.

**Comment by lukeis** [comment]
this is a 'fun' interesting one... it's not straight forward since that web page uses something called "shadow dom"

I'm not sure the best way to interact with this in firefox will be. Might want to ask on the users list as pointed out previously ^
