### ISSUE TITLE
webElement.isObscured()

### ISSUE THREAD

**Issue by samuelfac** [SeleniumHQ/selenium#8962]
## 🚀 Feature Proposal

As isDisplayed() create isObscured(), which returns true if there is any other element that obscures my element

## Motivation

be possible to check for this type of error not to occur:
`"Element <button class="api-form-save-button btn btn-primary" type="submit"> is not clickable at point (1128,877) because another element <div class="Footer__inner-1-75"> obscures it"`

## Example

```
if(!webElement.isObscured()) {
	((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", webElement);
}
```

**Comment by AutomatedTester** [comment]
thank you for this issue.

For this to be actioned we really need to move this to the [W3C repository](https://github.com/w3c/webdriver) and get it in the [specification](https://w3c.github.io/webdriver). However, I don't think that it will be accepted there for the following reasons.

*[ isDisplayed](https://w3c.github.io/webdriver/#element-displayedness) was never agreed on and was relegated to an addendum using the Selenium atom
* From ^ `There be dragons` and I will attempt to go through some of the issues

The web is inherently hostile to browsers and regularly sends utter junk to them.

In the case of Selenium returning an `ElementNotInteractable` error, it does it by checking which element will receive the hit from a [hit test](https://w3c.github.io/pointerevents/#dfn-hit-test). 

Now the "issue" comes when items are partially obscured by 2 elements with a z-index that places them above the element we are caring about. Do we need to calculate the region that is not obscured or do we do what `Element Click` does and only aim for the centre of the element that's in the view port?

Then we have the case where an element is visible but won't receive the click. In the example below the link will be clicked despite it being "obscured" if we told Selenium to click there due to the hit test.

```html
<div style='pointer-events: none;background: rgba(0, 0, 0, 0.5);`><a href=#>someLink</a></div>
```

We could approximate the hit test by injecting JavaScript, which is what I am going to suggest you do for the time being until you can flesh out the edge cases (And there are going to be loads unfortunately but might be a fun exercise if you have the time). 

```javascript
// This is untested code but should give you ideas
function isObscured(element) {
  let box = element.getBoundingClientRect()
  let x, y = box.x + (box.width/2), box.y + (box.height/2)
  const elements = document.elementsFromPoint(x, y);

  if elements[0] !== element {
    return true;
  } else {
     // do further checks on if it's opaque etc.
  }
}
```

Feel free to join our [slack or irc](https://www.selenium.dev/support/) to discuss further
