### ISSUE TITLE
Unable to change the setting for 'always_open_pdf_externally' on edge using Selenium?

### ISSUE THREAD

**Issue by heyitsmesuraj** [SeleniumHQ/selenium#8985]
## 🐛 Bug Report

Unable to change the setting for 'always_open_pdf_externally' on edge using Selenium?

## To Reproduce

For chrome, we can alter the setting for always_open_pdf_externally by following code:

var options = new ChromeOptions();
options.AddUserProfilePreference("plugins.always_open_pdf_externally", true);

Is there any way in Edge chromium to change the "always_open_pdf_externally" value?

I tried using it the same way but not worked. I have also tried it by using AddAdditionalOption but not worked.

Code :

var options = new EdgeOptions();
options.AddUserProfilePreference("plugins.always_open_pdf_externally", true);

var options = new EdgeOptions();
options.AddAdditionalOption("plugins.always_open_pdf_externally", true);

Detailed steps to reproduce the behavior:

## Expected behavior

Should change the setting value to true for 'always_open_pdf_externally'.

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Windows 10
Browser: Edge Chromium
Browser version: Version 87.0.664.60 (Official build) (64-bit)
Browser Driver version:  87.0.664.60
Language Bindings version: C#.net
Selenium Grid version (if applicable): 3.14 and 4

**Comment by diemol** [comment]
💬 It looks like this is a question rather than an issue.
  💡 A better way to address this is:
  * 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
  * 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
  * 🗣 Join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well
