### ISSUE TITLE
Chromium-based Edge in Selenium 3

### ISSUE THREAD

**Issue by joeyparrish** [SeleniumHQ/selenium#8993]
## 🚀 Feature Proposal

I propose to send a PR to add Chromium-based Edge support to Selenium 3.

## Motivation

Selenium 4 isn't ready yet, and it's not clear when it will be ready for use.  Meanwhile, legacy Edge is no longer supported by Microsoft.  Everyone testing on Edge should be testing the new Chromium-based Edge.

We have a Selenium 3 grid that is part of critical testing infrastructure for our project, and Edge is a critical platform.  We are currently unable to test in the new Chromium-based Edge.  Microsoft has WebDriver servers available, so it's unclear why there should be any problem using these in Selenium 3.

If anyone can outline the differences between what Selenium 3 does today and what Selenium 4 does differently to communicate with the new drivers, I can start working on a PR to address this critical gap in Selenium 3.

**Comment by joeyparrish** [comment]
Also, I meant to mention this in the original post, but I've seen https://github.com/SeleniumHQ/selenium/issues/8237#issuecomment-629851734, where @barancev said:

> Sorry, but we're not going to backport Edgium support to Selenium v.3, please wait for a stable version of Selenium 4 or try the current alpha.

I would completely understand you not wanting to devote resources to updating Selenium 3 while you focus on Selenium 4, but Selenium 3 is the only stable Selenium grid available to us as users, and Microsoft Edge is important.  If you don't want to devote your own resources to it, could you please provide some minimal guidance and allow contributors from the community work on this issue?

**Comment by diemol** [comment]
@joeyparrish, there is no need for a PR (well, since the code for Grid 3 is gone from the tree already). 

The good news is that you can use the new Edge Chromium with Grid 3, I know it is not working out of the box (which is what we meant by not backporting), but a slight change in the configuration allows you to use the new Edge in your current setup. I replied to this a while ago in a different issue, the details can be seen [here](https://github.com/SeleniumHQ/selenium/issues/8712#issuecomment-695793782).

If you'd like to try Alpha 7 of Selenium Grid 4, and you are bumping into issue, please create an issue or drop by our Slack/IRC channel, we'd be happy to help there. Link to the channel can be seen here -> https://www.selenium.dev/support/
