### ISSUE TITLE
Remove Edge HTML

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#9166]
Since Microsoft is forcing users to upgrade from Legacy Edge to the Chromium backed Edge, we've decided to remove support for it from the Selenium bindings for 4.0

Bindings maintainers can remove the label when completed in their code.

**Comment by titusfortner** [comment]
thank you selenium-assistant

**Comment by diemol** [comment]
Java done here https://github.com/SeleniumHQ/selenium/commit/610b34ab992390da41ef4a170ee21eefc42ef3a7

**Comment by bwalderman** [comment]
Hi @titusfortner. Support for Microsoft Edge Legacy (the browser) is indeed ending in the near future, but EdgeHTML will remain installed on the system and EdgeHTML-based universal Windows applications will continue to be supported.

Would you be open to keeping EdgeHTML support in Selenium 4? We could update the language bindings which have a `UseChromium` flag to `true` by default since Edge Chromium testing will be the most common scenario going forward.

**Comment by titusfortner** [comment]
@bwalderman  Can't you extend everything you need to work with EdgeHTML in your `edge-selenium-tools` project? What would you need in Selenium library to ensure it still functions correctly?

**Comment by bwalderman** [comment]
No new changes are needed in Selenium to ensure both EdgeHTML and Chromium function correctly. The EdgeHTML support should just not be removed.

The EdgeDriver class in dotnet, python, and javascript has a `UseChromium` boolean property that determines whether the driver uses EdgeHTML or Chromium. At the moment, `UseChromium` is false by default for backward compat. I'm proposing instead of removing EdgeHTML support from all languages, we simply flip the property to true by default. This makes Edge Chromium automation easy but leaves EdgeHTML support available for those who need it. I'd be happy to submit a PR.

Regarding `edge-selenium-tools`, This is a polyfill for bringing Edge Chromium support to Selenium 3 because 3 is still the latest stable release. We don't intend to use `edge-selenium-tools` to ship new features and would prefer to contribute directly to Selenium instead. `edge-selenium-tools` was created as a separate project because there was no longer any vehicle for updating the official Selenium 3 with Edge Chromium support.

**Comment by titusfortner** [comment]
Yes, all of the bindings had toggles for whether to use EdgeHTML or Edgium, and we decided in our most recent Technical Leadership Committee meeting to remove the toggles and only support the Chromium implementation going forward. EdgeHTML has always had problems because it was never completely W3C compliant, and maintaining the differences going forward will be increasingly challenging.

I suspect that projects interested in automating a universal Windows application are unlikely to also be automating the latest browsers with the same code. Setting the Selenium version to the latest 3.x version in such projects would be a better solution.

**Comment by bwalderman** [comment]
That makes sense. After discussing with the Edge developer tools team we agree this is the cleanest solution. We'll direct anyone who needs EdgeHTML support for their legacy apps to continue using 3.x. I suspect this is a relatively small group anyway.

**Comment by titusfortner** [comment]
@bwalderman thanks for raising the concern about this.

**Comment by AutomatedTester** [comment]
I have set Chromium Edge as the default in https://github.com/SeleniumHQ/selenium/commit/2b6b05b05d22c5719c72ef808ca9611b03d8be0d

**Comment by jimevans** [comment]
I've set Chromium Edge as the default in b2a7f08

**Comment by slnksachin** [comment]
Hey, is there any tentative date, when 4.0 will be released ?
Thank you !!
