### ISSUE TITLE
get the image data via python

### ISSUE THREAD

**Issue by novoxudonoser** [SeleniumHQ/selenium#920]
If link dont generates dynamically i can get image with .get(src) , byt if the link regenerates I am not able to doo that, the only way is too take a screenshot of all page and then crap it from theare (its not a good solution) , so it will be very nice to get the image data from the image element.

**Comment by lukeis** [comment]
if you're asking for what I think you're asking for... it's coming, in the future:
https://w3c.github.io/webdriver/webdriver-spec.html#take-element-screenshot
was added to the python bindings:
https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webelement.py#L388-L397

but it is only implemented in Marionette (driver for Gecko / future for firefox) and Edge.

Closing this issue and I would like to direct you to the user's mailing list for help with figuring out how to do things with selenium:
https://groups.google.com/forum/#!forum/selenium-users

Issues should describe succinctly what the issue is, how to reproduce it, what is happening and what is expected.

**Comment by novoxudonoser** [comment]
Ups, didnt know that, sorry for taking your time
