### ISSUE TITLE
Just call `HttpClient.Factory.createDefault();` im neccesary

### ISSUE THREAD

**Issue by stbischof** [SeleniumHQ/selenium#9232]
Because it is a static field  `HttpClient.Factory.createDefault();` in called on instantiating the HttpCommandExecutor.
If you are using on of the Constructors with `HttpClient.Factory httpClientFactory)` as parameter it is no neccesary to have the `HttpClient.Factory.createDefault();` And you will stock on exceptions inside this `HttpClient.Factory.createDefault();`

https://github.com/SeleniumHQ/selenium/blob/26c65c7a5c1be4558311e91802ce35942cfacee8/java/client/src/org/openqa/selenium/remote/HttpCommandExecutor.java#L48

**Comment by pujagani** [comment]
To address the issue, I have revisited the `HttpCommandExecutor` class code. By the looks of it, the reason the default HTTP client factory is kept static is to avoid creating multiple client factories each time the constructor is called. Regarding, the exception bit mentioned in the issue, can you please provide more details? Have you faced errors/exceptions due to global instance? 
Apologies in the case I might have looked over any potential problems that the issue is trying to point to. 
All contributions are welcome!

**Comment by diemol** [comment]
@barancev, what needs to be done here?

**Comment by diemol** [comment]
From Slack:
>Alexei Barantsev  6:31 PM
@diemol we should instantiate it on demand (using singleton pattern with double locking)

**Comment by barancev** [comment]
This factory is a tiny object, its impact on performance is next to zero so the issue severity is minor. But it's worth fixing for the sake of clean code :)

**Comment by stbischof** [comment]
Or if you try to handle all this without the service loader. This will throw an exception and you can't go around this.

In frameworks like osgi this code is really not nice.

I fixed my Problem an other way.  It is up tu you.

**Comment by diemol** [comment]
@stbischof, would you like to contribute and propose a solution?

**Comment by stbischof** [comment]
I solved my Problem. The goal was to create osgi compatible bundles and Register every driver as service. This now work's finde for me.
