### ISSUE TITLE
WebDriver commands differ between language bindings

### ISSUE THREAD

**Issue by vr2262** [SeleniumHQ/selenium#926]
I tried `driver.execute('setBrowserOnline', {'state': False})` in the Python Selenium client but encountered a `KeyError`.

That command is missing in
https://github.com/SeleniumHQ/selenium/blob/55a252442ad57cd63731959b44b12a1e6977b64f/py/selenium/webdriver/remote/command.py
but present in
https://github.com/SeleniumHQ/selenium/blob/55a252442ad57cd63731959b44b12a1e6977b64f/javascript/webdriver/command.js#L182
and
https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/DriverCommand.java#L108

**Comment by lukeis** [comment]
BrowserOnline is no longer supported and isn't in the upcoming W3C WebDriver spec. Also drivers don't implement the endpoint, so it doesn't really matter if the client has it or not (i think an exception may be chrome).

What it was originally intended for can be easily fetched with execute_script("return navigator.onLine;").

Setting this value is another thing altogether, since it's a read only property. You may want to raise a bug with the W3C spec to ensure its implementation -
https://w3c.github.io/webdriver/webdriver-spec.html
(link to log bugs in the top right corner of that page)
