### ISSUE TITLE
isDisplayed throws NullPointerException

### ISSUE THREAD

**Issue by atastrumf** [SeleniumHQ/selenium#9266]
## 🐛 Bug Report

Running with java binding and Firefox, the framework occasionally throws NullPointerException on the isDisplayed call.

**Please see https://github.com/mozilla/geckodriver/issues/1825 for more information.** As stated from geckodriver team, the issue is apparently related to the custom JS that is executed with this method. The ticket also contains trace logs. 

## To Reproduce

Hard to provide steps, as it happens "randomly".

## Expected behavior

Should not throw exception..

## Environment

OS: Windows 10
Browser: Firefox
Browser version: 84.0.1
Browser Driver version: geckodriver 0.28.0 (c00d2b6acd3f 2020-11-03 16:29 +0200)
Language Bindings version: java 3.141.59

**Comment by PiotrZgadzaj** [comment]
I have the same problem on 
OS: Linux (4.15.0-88-generic)
Browser: Firefox
Browser version: 85.0
Browser Driver version: geckodriver  0.29.0
Language Bindings version: java 3.11.0

As i'm able to reproduce it from time to time, I can provide additional logs if needed

**Comment by diemol** [comment]
I understand that it might be hard to provide steps to reproduce it, but without them it is impossible for us to investigate the issue. We would appreciatte if you can provide them.

**Comment by PiotrZgadzaj** [comment]
Steps are described in related geckodriver issue. As i said, if you tell me on which classes we i should enable trace logs, i can also provide them.

I don't have a running example which i **can** share with you, but if there is no other way, then i can try to design one

**Comment by diemol** [comment]
That would be much better because narrative descriptions lead to many assumptions. In short, we need a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by PiotrZgadzaj** [comment]
You know that i can only provide a test page which will  produce the problem in 1 out a 100 or even 1000 attempts? This will really help You? Without proper logs You will anyway do nothing with that, but fine, i will make such a page

**Comment by diemol** [comment]
Looking forward to it, thank you!

**Comment by PiotrZgadzaj** [comment]
Pls check the attachment below

I was able to prepare a reproducible example. Archive contains the test logic + test page

[test.zip](https://github.com/SeleniumHQ/selenium/files/6152369/test.zip)

My setup is:
OS: Linux (4.15.0-88-generic)
Browser: Firefox
Browser version: 85.0
Browser Driver version: geckodriver 0.29.0
Language Bindings version: java 3.11.0

I have pretty fast machine with:
- I7 8700
- Samsung 970 PRO
- 32GB of RAM

I mentioned that as i observed that how fast issue is reproducible, depends on the machine, slower the machine, faster you should be able to reproduce that. On my side it needed just a few iteration of the loop to hit the null pointer:

java.lang.NullPointerException: null
	at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:323)
	at Test.waitForSpanToDisappearOrUntilTimeout(Test.java:30)
	at Test.test(Test.java:19)

If you cannot reproduce it on your side, pls manipulate the time periods defined in:
Test.java:19
test.html:530

The aim of them is when isDisplayed is triggered, page is being reloaded by the setTimeout defined in html

**Comment by pujagani** [comment]
Thank you for providing the detailed steps. I was able to reproduce the issue. Based on the observation it turns out the issue does not occur with the latest version of ChromeDriver and EdgeDriver but it occurs with GeckoDriver. The isDisplayed() function in all Selenium bindings runs a script https://github.com/SeleniumHQ/selenium/blob/trunk/rb/lib/selenium/webdriver/atoms/isDisplayed.js on the driver end. The GeckoDriver sometimes returns null and the Java client binding simply passes the value back to the user calling the function. 

To safeguard against this, a null check has been added as part of #9299. 
This could be potentially similar to https://github.com/SeleniumHQ/selenium/issues/4555.

**Comment by TurboCoder13** [comment]
Since this is the latest thread on the `isDisplayed()` methond / function (which was worked on in the past 2-3 months), has `isDisplayed()` been removed from the library of available methods?

I am using Maven and wanted to update the version for Selenium, but unfortunately I cannot find the `isDisplayed()` method.

Here I have `Selenium Java V3.141.59` with the `WebElement class` like this:

_NOTE: Comments from the class removed for readability on the thread_

```
package org.openqa.selenium;

import java.util.List;

public interface WebElement extends SearchContext, TakesScreenshot {
 
  void click();

  void submit();

  void sendKeys(CharSequence... keysToSend);

  void clear();

  String getTagName();

  String getAttribute(String name);

  boolean isSelected();

  boolean isEnabled();

  String getText();

  List<WebElement> findElements(By by);

  WebElement findElement(By by);

  boolean isDisplayed();

  Point getLocation();

  Dimension getSize();

  Rectangle getRect();

  String getCssValue(String propertyName);
}
```
And then with the latest **beta version 4.0.0-beta-3**, the class has some missing stuff and looks like this:

```

package org.openqa.selenium;

import java.util.List;

public interface WebElement extends SearchContext {
 
  void click();

  void submit();

  String getValue();

  void sendKeys(CharSequence... keysToSend);

  void clear();

  String getTagName();

  String getAttribute(String name);

  boolean toggle();

  boolean isSelected();

  void setSelected();

  boolean isEnabled();

  String getText();

  List<WebElement> findElements(By by);

  WebElement findElement(By by);

}
```
The `boolean isEnabled();` is missing and this is causing the code to fail, obviously.

I cannot find anything regarding this method that it's been removed or moved to another place or something since the `V3.141.59`.

I checked every version since the `V3.141.59` (**all the Alpha and Beta versions**) and none of them have this method in them.
