### ISSUE TITLE
Question: Javascript selenium-webdriver

### ISSUE THREAD

**Issue by cristian-smocot** [SeleniumHQ/selenium#929]
Is it possible to use selenium-webdriver with classic Mocha tests, without using the testing module integrated in selenium-webdriver?

In other words, is it possible to
```javascript
describe('Test', function(){

	var browser;

	before(function(){
		browser = new selenium.Builder().usingServer(serverURL).withCapabilities(capabilities).build();
	});

	it('Go to google.com', function(done) {

		browser
			.get('http://www.google.com')
			.then(done);

	});
});
```

**Comment by ddavison** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#bug-reports) before filing issues

**Comment by jleyba** [comment]
To answer your question though, yes it is possible.  The testing module is just provided as a convenience.
