### ISSUE TITLE
[dotnet] RelativeBy methods are inaccessible

### ISSUE THREAD

**Issue by jordan-mace** [SeleniumHQ/selenium#9320]
## 🐛 Bug Report

Currently, the RelativeBy methods (Near, LeftOf, etc) are non-static whereas the By methods (ClassName, LinkText) are. 
The RelativeBy constructor is also protected, meaning the methods are inaccessible since you can't do `new RelativeBy().LeftOf()`.

## To Reproduce

Detailed steps to reproduce the behavior:
1. Write a line of code to get a WebElement with a RelativeBy
2. Notice the object ref error

## Expected behavior

The RelativeBy should be accessible in the same way that By is.

## Test script or set of commands reproducing this issue

https://github.com/jordan-mace/relativeby-bug

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Windows 10
Browser: N/A
Browser version: N/A
Browser Driver version: N/A
Language Bindings version: dotnet 4.0.0-beta2
Selenium Grid version (if applicable):

**Comment by pujagani** [comment]
Thank you for providing the details and a potential fix. However, as far I understand, the way RelativeBy methods are exposed is correct. 
Please refer to https://www.selenium.dev/documentation/en/webdriver/browser_manipulation/#navigate-to for correct usage of the same using the latest version of Selenium Beta 2.

**Comment by jordan-mace** [comment]
Hey @pujagani you have linked the NavigateTo documentation, I believe you meant the [RelativeSelector](https://www.selenium.dev/documentation/en/webdriver/locating_elements/#relative-locators) documentation?

Is there a reason why the RelativeBy selectors are not exposed as the By selectors are?

**Comment by pujagani** [comment]
Yes, sorry about that,  I was intending to point to https://www.selenium.dev/documentation/en/webdriver/locating_elements/#relative-locators. Regarding the reason for the way they are exposed, I think it could be due to ease of readability and usage. It emulates "find the elements with tag name above this element".  This is my understanding from my usage of it based implementation in all language bindings.
For understanding details, @jimevans  or @shs96c  might have a better explanation. :)
