### ISSUE TITLE
 Proxy auth is not working with chrome and nodejs 

### ISSUE THREAD

**Issue by alicanso** [SeleniumHQ/selenium#9326]
## 🐛 Bug Report

I tried everything but cant success. How to use proxy authentication with Selenium? I tried these ways:

options.addArguments("--proxy-server=http://username:pass@proxy_url");

and

options.setProxy(proxy.manual({http: username:pass@proxy_url}));

These are not working.

## Environment

OS: OSX
Browser: Chrome
Browser version: Latest
Browser Driver version: Latest ChromeDriver
Language Bindings version: Latest Nodejs

**Comment by diemol** [comment]
This is a question rather than an issue.
  💡 A better way to address this is:
  * 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
  * 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
  * 🗣 Join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well
