### ISSUE TITLE
Python Selenium Firefox on Ubuntu: New Tabs Not Working

### ISSUE THREAD

**Issue by legel** [SeleniumHQ/selenium#935]
New tabs in Firefox are not opening up for this configuration:
 - Ubuntu 14.04.2
 - Python 2.7.6
 - Selenium 2.47.1
 - PyVirtualDisplay 0.1.3

Example:

    from selenium import webdriver
    from selenium.webdriver.common.keys import Keys
    from selenium.webdriver.common.action_chains import ActionChains
    from pyvirtualdisplay import Display

    # launch our headless display 
    display = Display(visible=0, size=(800, 600))
    display.start()

    # launch our web driver and get a page
    browser = webdriver.Firefox()
    browser.get("http://www.google.com/")
    
    # try to open a new tab
    ActionChains(browser).key_down(Keys.CONTROL).send_keys("t").key_up(Keys.CONTROL).perform()
    
    # this should print 2, but it prints 1, because new tab not opened
    print len(browser.window_handles)

    # clean up everything
    browser.quit()
    display.stop()

Also reported on StackOverflow:
http://stackoverflow.com/questions/32040316/python-selenium-firefox-on-ubuntu-new-tabs-not-working

**Comment by lukeis** [comment]
Firefox using Selenium's FirefoxDriver is no longer able to execute "native" events. Meaning sending a "Control t" to the browser is actually sending synthetic javascript events to the DOM and not to the Browser Chrome. Your best bet to get this working is to attempt to use [Marionette](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver)

An alternative is to merely open a new window (there is not fundamental difference between a tab and new window, other than people prefer to visually see them).  driver.execute_script("window.open()");

Closing this issue because no one is able or willing to work on native events. Pull requests will be accepted if someone attempts to make it work, but their work is better vested into Marionette.
