### ISSUE TITLE
Java 4.0.0-beta-3 Relative locators - withTagName is missing

### ISSUE THREAD

**Issue by kasprzakdanielt** [SeleniumHQ/selenium#9429]
## 💥 Regression Report

After updating to beta3, all of my relative locators are showing import errors on 
import static org.openqa.selenium.support.locators.RelativeLocator.withTagName;

![obraz](https://user-images.githubusercontent.com/9053610/116515416-9023eb80-a8cc-11eb-8b26-cb9262a33867.png)

On beta2 it works just fine.

Worked up to version: 4.0.0-beta-2

Stopped working in version: 4.0.0-beta-3

## To Reproduce

1. Add "import static org.openqa.selenium.support.locators.RelativeLocator.withTagName;"
2. Update to beta3
3. "withTagName" shows and error "Cannot resolve symbol 'withTagName'"

## Expected behavior

Successful import.

## Environment

OS: Windows 10
Browser: any
Browser version: any
Browser Driver version: any
Language Bindings version: java:4.0.0-beta-3

**Comment by harsha509** [comment]
HI @kasprzakdanielt ,

This behaviour is changed in Selenium4 beta 3 with this PR https://github.com/SeleniumHQ/selenium/pull/9273.

Now Java bindings supports `with(By)` instead of `withTagName` allowing the users to pick locators of their choice like

`with(By.tagName())`
`with(By.Id())`
`with(By.cssSelector())` 

Hope this helps!

Thanks,
Harsha

**Comment by diemol** [comment]
Thanks for pointing that out, @JS31096!
