### ISSUE TITLE
> What is the actual bug? Can we have a script to reproduce the behaviour? Narrative descriptions leave lots of room for assumptions.

### ISSUE THREAD

**Issue by ThomasSun001** [SeleniumHQ/selenium#9469]
> What is the actual bug? Can we have a script to reproduce the behaviour? Narrative descriptions leave lots of room for assumptions.
Well, thx for your reply, If I know that the bug is, then I will be looking for some solutions, the thing is I have no idea what happened for this error!
by the way:
the script to reproduce:
`Selenium::WebDriver::Firefox::Service.driver_path = "/geckodriver"
    Selenium::WebDriver.logger.level = :info
    Selenium::WebDriver.logger.output = 'selenium.log'
    options = Selenium::WebDriver::Firefox::Options.new(args: ['-headless'],log_level: :info)
    driver = Selenium::WebDriver.for(:firefox,options:options)
`
The log will output nothing,
I update my firefox to Mozilla Firefox 78.10.0esr, it works smoothly, but my another computer which is also centos7, the firefox version Mozilla Firefox 68.12.0esr, it also works, So I'm deeply confused!

_Originally posted by @ThomasSun001 in https://github.com/SeleniumHQ/selenium/issues/9467#issuecomment-839434366_

**Comment by ghost** [comment]
❗️ It seems this issue is not using any of the supported templates

💡 Supported issue types are (they start with):

* 🐛 Bug Report (bugs found in a recent release)
* 🚀 Feature Proposal (a useful feature you would like to propose)
* 💥 Regression Report (a supported feature is not working anymore)

Issue templates help this project to stay in shape, please use them and fill them out completely. By doing that you are helping the project because the community and maintainers can provide prompt feedback, and potentially solve the issue.

If you are asking a question, a better way to address this is:

* 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
* 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
* 🗣 Join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com/) where the community can help you as well

If you think this is incorrect, please feel free to open a new issue.

Thank you for your contributions.
