### ISSUE TITLE
C# WebDriver ChromeOptions LeaveBrowserRunning property not working

### ISSUE THREAD

**Issue by luzemin** [SeleniumHQ/selenium#9492]
## 🐛 Bug Report
C# WebDriver ChromeOptions LeaveBrowserRunning property not working

## To Reproduce
```
public class Program
{
        static void Main(string[] args)
        {
            ChromeOptions option = new ChromeOptions();
            option.LeaveBrowserRunning = true;
            using (IWebDriver driver = new ChromeDriver("C:\Selenium", option))
            {
                driver.Navigate().GoToUrl("https://www.google.com");
            }
       }
}
```

## Expected behavior
The Chrome should be left running after the ChromeDriver instance is exited

## Test script or set of commands reproducing this issue
See *To Reproduce*

## Environment
OS: Windows 10
Browser: Chrome
Browser version: 90.0.4430.212(64bit)
Browser Driver version: ChromeDriver 90.0.4430.24
Language Bindings version: C# 3.141.0

**Comment by jimevans** [comment]
@Luzemin What is your expectation of that property? From [the documentation of the capability](https://chromedriver.chromium.org/capabilities):

> If false, Chrome will be quit when ChromeDriver is killed, regardless of whether the session is quit. If true, Chrome will only be quit if the session is quit (or closed). Note, if true, and the session is not quit, ChromeDriver cannot clean up the temporary user data directory that the running Chrome instance is using. 

This means to me that if you call `driver.Quit()` (or `Dispose()` as your `using` clause does), the browser will be terminated when those methods are called, even if the capability is set to `true`. That being the case, it's a chromedriver issue, and by design for them.
