### ISSUE TITLE
Selection failing on some select boxes

### ISSUE THREAD

**Issue by nmondal** [SeleniumHQ/selenium#951]
Hi Guys, 
This is really a question. The select perfectly works, most of the time.
However, there is this one page - where in selection  - it generates Javascript error ( events fails ).
There, the select is not working.
I tried reproing it - by creating a small local file - and injecting javascript error on selection change event - but it is still able to select.

Now, I need to know that is it possible that due to some javascript error - can selection be cancelled?
What really happens is this : 

*  The select ( combo box ) gets clicked
*  Instead of the item getting selected - we see the whole popup of the combo box 
* Now the item gets selected - but the popup does not disappear ( the item does not get selected actually ) 
* The popup stays there, and the code breaks.

Need to know cause of such a behaviour.
Please help!
Thanks, 
-- Noga

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
