### ISSUE TITLE
headless

### ISSUE THREAD

**Issue by ing670** [SeleniumHQ/selenium#9529]
## To Reproduce

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by diemol** [comment]
❗️ It seems this issue is not using any of the supported templates

💡 Supported issue types are (they start with):

* 🐛 Bug Report (bugs found in a recent release)
* 🚀 Feature Proposal (a useful feature you would like to propose)
* 💥 Regression Report (a supported feature is not working anymore)

Issue templates help this project to stay in shape, please use them and fill them out completely. By doing that you are helping the project because the community and maintainers can provide prompt feedback, and potentially solve the issue.

If you think this is incorrect, please feel free to open a new issue.
