### ISSUE TITLE
Traverse all tabs without disturbing the manually browsing activity, i.e., without change the window focusing.

### ISSUE THREAD

**Issue by noisnemid** [SeleniumHQ/selenium#9607]
## 🚀 Feature Proposal

Traverse all tabs without disturbing the manually browsing activity, i.e., without change the window focusing.

## Motivation

Set selenium's managing tab/window  in background without switch_to.window(some_window_handle).

when I'm trying to traverse all tabs of an opened browser(chromium) and manually open some tabs and do some browsing, selenium changes the focus of the window and disturbs the browsing activity.

So, the motivation is: manually browsing could be done when selenium could monitor all tabs background.

## Example

```
class Foo():
    def traverseTabs(self):
        while True:
            for wh in self.browser.window_handles:
                self.getCurrentTabSource(wh)

    def getCurrentTabSource(self, wh):
        self.browser.switch_to.window(wh)
        url = self.browser.current_url
        time.sleep(1)
        h = {
            'url': url,
            'time': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            'src': self.browser.page_source,
            'text': self.browser.find_element_by_tag_name('body').text
        }
        if h['url'] not in self.history:
            self.history[url] = [h]
        else:
            for hs in self.history[url]:
                if h['text'] == hs['text']:
                    return
            self.history[url].append(h)
```

**Comment by diemol** [comment]
Browsers opened by WebDriver through the browser drivers have a clean state since they use a completely new profile created for the session.

Manipulating the browser manually breaks that concept of "clean state" since those manual actions can interfere with the automation session, which is why it is expected to leave the browser just running the automated session. 

From the browser automation point of view, manual actions disturb the automation activity (unless they are related to debugging while creating automated scripts). 

For manual browsing activity, please open a separate browser instance.
