### ISSUE TITLE
IE driver - Does not get cookies from IE 10 or IE11

### ISSUE THREAD

**Issue by Prabhs13** [SeleniumHQ/selenium#962]
STR:
1. Try to get cookies using IE driver with driver.manage().getCookies() or driver.manage().getCookieNamed(COOKIE) on Internet explorer browser . 
The IE browser window then hangs and can be closed only by using kill process.
2. The above said methods were used with Chrome and Firefox and were working fine.

**Comment by jimevans** [comment]
You neglected to mention the versions of `IEDriverServer` that you're using. My psychic debugging powers tell me that you're using 2.47 of `IEDriverServer.exe`, and furthermore, you're running the 64-bit executable, probably because you're on 64-bit Windows. Don't do that. Use the 32-bit version of `IEDriverServer`.

Cookie handling was entirely rewritten in 2.47 for IE, but doing so did introduce this incompatibility. A further change (79ea708) was added after 2.47 to quickly throw an exception in this case, rather than just "hang." All of these changes are listed in the [change log](https://github.com/SeleniumHQ/selenium/blob/master/cpp/iedriverserver/CHANGELOG) for the IE driver.

**Comment by Prabhs13** [comment]
Hey Jim,

I really appreciate your quick response. I was using 2.47 version (64 bit) of IEDriverServer.exe. Now, as I have implemented the proposed changes in the script, so will let you know if this works on Windows 7, 8 and 10 as well.

Thanks

**Comment by Prabhs13** [comment]
Hi @jimevans ,

Your proposed solution didn't worked for me. I was using IEDriverServer.exe version 2.47.1 (32 bit) but still IE screen freezes during getCookies request. I have tested it on Windows 7 (IE version 10)and Windows 10 and 11.

I have disabled the protected mode on IE, lowered the security parameters, and have enabled script debugging too.

Kindly let me know if I am still missing something to make it work.

Thanks

Prabhdeep

**Comment by jimevans** [comment]
Please download version 2.47.0.2 of `IEDriverServer.exe` from [this location](https://github.com/SeleniumHQ/selenium/blob/master/cpp/prebuilt/Win32/Release/IEDriverServer.exe). Set the driver in your language binding to generate a log file for `IEDriverServer.exe` of `DEBUG` or `TRACE` level, and post the log.

**Comment by kriegaex** [comment]
I am seeing a similar issue with Selenium IE 2.53 when reading all or a single cookie via Selenium Hub from TestChameleon cloud service. It takes reproduceably 45.1 seconds to retrieve the cookies.

**Comment by praveenraj123** [comment]
I'm using above the code it's working good chrome browser but not working on ie 11 browser .... So kindly give any other solution

**Comment by praveenraj123** [comment]
I'm using above the code it's working good chrome browser but not working on ie 11 browser .... So kindly give any other solution
