### ISSUE TITLE
Selenium hangs for long time for click operation on modals.

### ISSUE THREAD

**Issue by kittudk** [SeleniumHQ/selenium#967]
selenium hangs for very long time without throwing any error or exception when i perform any operation on modals ( where switch to () is not required since it's a modal pop-up  
![webdriverhang](https://cloud.githubusercontent.com/assets/13978025/9488952/19cd8074-4bfb-11e5-94df-020a74dc1899.png)
).

 Following are my environments : 

FF : ver 34
WebDriver : 2,44

In these modals we don't have to use switch to () since it's just a pop-up and not a window.

**Comment by ddavison** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#bug-reports)
