### ISSUE TITLE
Selenium Python how to write elements to pandas

### ISSUE THREAD

**Issue by epiphronSG** [SeleniumHQ/selenium#9687]
Newbie here. Need help on Selenium Python, Find Elements, Pandas:
Codes as follows:
array=[]
array=driver.find_elements_by_xpath("//fl-list-item")
for e in array:
    print(e.text)

I can see the print(e.text) as follows: (there are 20 elements and here is the 1st one) 
Convert a PDF in Word
$250 – 750 USD
Posted 6 minutes ago
We would like to have a (scanned) PDF file convert to a Word file
Data Entry
Excel
PDF
Word
Copy Typing
Fixed Price
28 Bids
0.0

Question: how do I get these as one row with headers using Pandas? 

Went to numerous videos and kind of know bits and pieces but couldn't get the data into Pandas.

Appreciate help to newbie here.

**Comment by ghost** [comment]
❗️ It seems this issue is not using any of the supported templates

💡 Supported issue types are (they start with):

* 🐛 Bug Report (bugs found in a recent release)
* 🚀 Feature Proposal (a useful feature you would like to propose)
* 💥 Regression Report (a supported feature is not working anymore)

Issue templates help this project to stay in shape, please use them and fill them out completely. By doing that you are helping the project because the community and maintainers can provide prompt feedback, and potentially solve the issue.

If you are asking a question, a better way to address this is:

* 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
* 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
* 🗣 Join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well

If you think this is incorrect, please feel free to open a new issue.
