### ISSUE TITLE
Make Node.js browser creation non-blocking

### ISSUE THREAD

**Issue by pauldraper** [SeleniumHQ/selenium#9706]
## 🚀 Feature Proposal

Make `Builder.prototype.build` asynchronous.

## Motivation

Currently, creating browsers limits concurrency, which is a performance problem.

Exacerbating the problem is the lack of timeout when creating browsers. Creating a browser can literally hang the entire process forever.

## Example

```ts
const builder = new Builder()
const driver = await builder.build();
```

**Comment by diemol** [comment]
This should be addressed at the specification level.

There was actually a [PR](https://github.com/w3c/webdriver/pull/1561) adding the specification for it, but it was [reverted](https://github.com/w3c/webdriver/pull/1576) because complexity was overseen. More work needs to be done there. What is missing is actually an issue in that repo to track that work, could you help us to create that issue, @pauldraper?
