### ISSUE TITLE
Getting java.lang.NoSuchMethodError: org.openqa.selenium.WebElement.getDomAttribute(Ljava/lang/String;)Ljava/lang/String;in select class for Selenium 4.0.0-beta-4

### ISSUE THREAD

**Issue by vijaysri22** [SeleniumHQ/selenium#9709]
Hi , I am using selenium 4.0.0-beta-4 with chrome 89 . While selecting value from drop down using select class  I am getting exception java.lang.NoSuchMethodError: org.openqa.selenium.WebElement.getDomAttribute(Ljava/lang/String;)Ljava/lang/String;

**Comment by diemol** [comment]
❗️ It seems this issue is not using any of the supported templates

💡 Supported issue types are (they start with):

* 🐛 Bug Report (bugs found in a recent release)
* 🚀 Feature Proposal (a useful feature you would like to propose)
* 💥 Regression Report (a supported feature is not working anymore)

Issue templates help this project to stay in shape, please use them and fill them out completely. By doing that you are helping the project because the community and maintainers can provide prompt feedback, and potentially solve the issue.

If you think this is incorrect, please feel free to open a new issue.

If you are asking a question...
  💡 A better way to address this is:
  * 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
  * 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
  * 🗣 Join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well
