### ISSUE TITLE
Cannot Load PAC file in to Firefox.

### ISSUE THREAD

**Issue by RathanakSreang** [SeleniumHQ/selenium#972]
Hi,
I am new to selenium, and now I have one problem.
Which I don't know how load PAC file into selenium to test my rails project. I do search a lot but I cannot find any solution on google.
Can you tell me how to load it into Firefox? Thx

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
