### ISSUE TITLE
Gallio MbUnit  - Assert.Count() not working after updating C# webdriver dlls to 2.47.0

### ISSUE THREAD

**Issue by pmadhuyadav** [SeleniumHQ/selenium#973]
I Have declared web element in page class as
 [FindsBy(How = How.XPath, Using = "//tr[not(contains(@class, 'rowHidden'))]//span[@id='LinkToDetail']")]
        public IList<IWebElement> ResumeTitleLinks { get; protected set; }

am asserting the links count using 
Assert.Count()

Note:above assertion was working fine in previous C# webdriver dll's  releases

Getting below exception
==================
An exception occurred while verifying an assertion. 

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetException: Object does not match target type.
HResult: -2146232829
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at OpenQA.Selenium.Support.PageObjects.WebDriverObjectProxy.InvokeMethod(IMethodCallMessage msg, Object representedValue)
   at OpenQA.Selenium.Support.PageObjects.WebElementListProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.Runtime.InteropServices.WindowsRuntime.IVector`1.get_Size()
   at System.Runtime.InteropServices.WindowsRuntime.VectorToCollectionAdapter.Count[T]()
   --- End of inner exception stack trace ---
HResult: -2146232828
   at Gallio.Common.Collections.EnumerableCounter.<>c__DisplayClass18.b__16() in c:\Server\Projects\MbUnit v3.3\Work\src\Gallio\Gallio\Common\Collections\EnumerableCounter.cs:line 100
   at Gallio.Common.Lazy`1.get_Value() in c:\Server\Projects\MbUnit v3.3\Work\src\Gallio\Gallio\Common\Lazy.cs:line 55
   at Gallio.Common.Collections.CountingStrategy.get_Count() in c:\Server\Projects\MbUnit v3.3\Work\src\Gallio\Gallio\Common\Collections\EnumerableCounter.cs:line 200

**Comment by jimevans** [comment]
The `PageFactory` implementation was refactored in 2.46 to use standard .NET Framework proxy objects instead of hand-rolled proxy objects. As such, the requirement that fields and properties for element lists must be of type `IList<IWebElement>` is now more strictly enforced. Note that limitation has been around for some time now in the .NET `PageFactory` implementation, but it is now a strict limitation. What happens if you change your member data type to the appropriate type of `IList<IWebElement>`?

**Comment by pmadhuyadav** [comment]
Below is the correct declaration of webelement 

 [FindsBy(How = How.XPath, Using = "//tr[not(contains(@class, 'rowHidden'))]//span[@id='LinkToDetail']")]
        public IList<IWebElement> ResumeTitleLinks { get; protected set; }

**Comment by jimevans** [comment]
Your property declaration is still incorrect. You're still using `IList` and not `IList<IWebElement>`. What happens if you change the property to be of type `IList<IWebElement>`?

**Comment by jimevans** [comment]
Never mind. I just re-read your comment. Do you have a page where this can be tested against? This is not globally broken for all users of all pages.

**Comment by pmadhuyadav** [comment]
URl = http://jobsearch.monster.com/browse/?sf=20&pcn=3&re=nv_gh_gnl1147_%2F

 [FindsBy(How = How.CssSelector, Using = "a[id*='wacCenterStage_NewFilters_FiltersFacets_repeaterFacets_'][id$='_lnkFilter']")]
        public IList<IWebElement> JobsFilterAllItems { get; protected set; }

**Comment by koreyba** [comment]
Hi! Maybe I have similar problem. When I initialize attributes using page factory then when I made a break point in my code I can not view properties of my web element. 

I have the next code:
[FindsBy(How = How.CssSelector, Using = "input#raffle_submit")]
private IWebElement _buyNowButton;

and:

PageFactory.InitElements(Driver, this);

public CartObj ClickBuyNowButton()
{
     _buyNowButton.Click(); //here is my break point
}

Only property I see is: - Non-Public members : http://prntscr.com/8k90r4

**Comment by jimevans** [comment]
@pmadhuyadav This behavior is due to a [bug in the .NET Framework](https://connect.microsoft.com/VisualStudio/feedback/details/1853289/can-no-longer-use-reflection-on-count-property-for-instances-of-realproxy-of-icollection-t-objects), which is caused by the way Galleo/MbUnit has implemented its `Assert.Count` method. There is nothing Selenium can do to resolve this issue.

@koreyba Your issue is entirely unrelated. It's due to the fact that the .NET `PageFactory` implementation now uses instances of `System.Runtime.Remoting.Proxies.RealProxy` to intercept method calls and populate your fields and properties marked with the appropriate attributes. Using the .NET Framework's proxy solution provides flexibility for other third-party projects to use the .NET `PageFactory` implementation, and thus will not be changing. It should be possible to create your own proxy solution that provides you with the debug properties in Visual Studio, but it would require a custom solution.
