### ISSUE TITLE
WebDriver Bidi APIs Java example does not work with FirefoxDriver

### ISSUE THREAD

**Issue by abhi-singhs** [SeleniumHQ/selenium#9731]
## 🐛 Bug Report

The Java Bidi APIs example doesn't work because it is implemented with Firefox and FirefoxDriver doesn't implement the HasLogEvents interface.
Happy to submit a PR for this issue.

## To Reproduce

Running the Java Example code mentioned in https://www.selenium.dev/documentation/webdriver/bidi_apis/

## Expected behavior

The WebDriver Bidi API for DOM Mutation should work with FirefoxDriver.

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: OSX
Browser: Firefox
Browser version: 88.0.1
Browser Driver version: GeckoDriver 0.29.1
Language Bindings version:  Java 4.0.0-beta-3
Selenium Grid version (if applicable):

**Comment by diemol** [comment]
What happens when you upgrade to `beta-4`?

**Comment by abhi-singhs** [comment]
> What happens when you upgrade to `beta-4`?

The issue still persists.

I can see that HasLogEvents has been implemented for [ChromiumDriver](https://github.com/SeleniumHQ/selenium/blob/f40638f241c490c47446f17c707cfb92d541dc0f/java/src/org/openqa/selenium/chromium/ChromiumDriver.java#L72) but not for [FirefoxDriver](https://github.com/SeleniumHQ/selenium/blob/f40638f241c490c47446f17c707cfb92d541dc0f/java/src/org/openqa/selenium/firefox/FirefoxDriver.java#L80).

**Comment by abhi-singhs** [comment]
`class org.openqa.selenium.firefox.FirefoxDriver cannot be cast to class org.openqa.selenium.logging.HasLogEvents`
@diemol This is the error I am seeing.

**Comment by pujagani** [comment]
@abhi2810 Thank you for providing the details. Once the HasLogEvents interface is implemented by FirefoxDriver, the class cast exception is fixed as you said ( I have tried it locally). 
However, the DOM mutation listener works by calling the [Runtime.addbinding CPD command] (https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-addBinding) along with the dom mutation javascript script. When the listener is [initialized](https://github.com/SeleniumHQ/selenium/blob/d6bb232e525571b334325ed0859e2168e10f6edb/java/src/org/openqa/selenium/devtools/events/CdpEventTypes.java#L97) the `Runtime.addbinding` command is called. 
It works fine for the ChromeDriver. 
But with FirefoxDriver throws an error : 
```
1631687941612	CDP	ERROR	UnknownMethodError: Runtime.addBinding:
	RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5
	UnknownMethodError@chrome://remote/content/cdp/Error.jsm:112:7
	execute@chrome://remote/content/cdp/domains/DomainCache.jsm:98:13
	receiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.jsm:84:45 
```

This is due to missing functionality in the geckodriver implementation which is tracked via https://bugzilla.mozilla.org/show_bug.cgi?id=1549487.

**Comment by diemol** [comment]
Thanks @pujagani for providing the context and the reason.
We have also fixed the example, it is using Chrome now.
