### ISSUE TITLE
Issue with WebDriverWait - Timeout not considered

### ISSUE THREAD

**Issue by dampfnudel** [SeleniumHQ/selenium#974]
I have a problem with the Timeout which is passed to the constructor WebDriverWait. I would expect that always the passed timeout would be considered

<img width="570" alt="capturfiles_1" src="https://cloud.githubusercontent.com/assets/11321242/9514816/6e5a366c-4c9d-11e5-9ef0-d07483188e90.png">
.

Please find below the outcome of the console.

If implicitlyWait is set to 0 then the WebDriverWait Timeout is considered.
Exception0
0.019
Exception1
5.14 

If implicitlyWait is set to 5 then the WebDriverWait Timeout is considered.
Exception0
5.108
Exception1
5.134

**Comment by AutomatedTester** [comment]
implicit waits take precedent so this is behaving as expected. WebDriverWait just does polling from the local end.

It has been recommended for a long time that you should not mix implicit and explicit waits. Ideally you should only be using explicit waits for what you want so that you get the expected behaviour.

**Comment by dampfnudel** [comment]
Thanks for the quick reply. Will consider this.
