### ISSUE TITLE
How we use selenium at client side

### ISSUE THREAD

**Issue by kartikdanidhariya** [SeleniumHQ/selenium#976]
hi,

i am using selenium 2.47.1 with python

no i want to make auto login script in python using selenium
i open browser using        mydriver = webdriver.Firefox()
but after when script run it open browser in server not in client side
i want to open browser at client side 
how can i open browser at client side in selenium with python
please help,
thanks in advanced!!!

**Comment by ddavison** [comment]
there is not enough information to go on here.  Selenium doesn't communicate with a back-end.  Selenium communicates with a front-end web application.

```python
mydriver.get('http://example.com')
```
should be sufficient for you.

I will be closing this issue ,however, since you aren't detailing enough information to prove that this is a concrete issue with the Selenium software itself.  If you need help, go ahead and create a topic in the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group
