### ISSUE TITLE
Selenium Remote Web Driver not starting with given Firefox Profile 

### ISSUE THREAD

**Issue by alexfernandezv** [SeleniumHQ/selenium#9761]
### Test Case
I want to install a custom extension in a Firefox remote web driver. To achieve that I have created a FirefoxProfile and added the custom extension via setExtension. The problem is that the profile I have just created is not added to the Driver instance. Here is the piece of code I have used:
```
          File firefoxExtension = new File("src\\main\\resources\\browser-extensions\\firefox-extension.xpi");
          FirefoxProfile profile = new FirefoxProfile();
          profile.addExtension(firefoxExtension);
          FirefoxOptions options = new FirefoxOptions();
          options.setProfile(profile);
          capabilities.setCapability(FirefoxOptions.FIREFOX_OPTIONS,options);

        try {
            return new RemoteWebDriver(new URL("https://" + username + ":" + accessKey + "@"
                    + environmentVariables.getProperty("browserstack.server") + "/wd/hub"), capabilities);
        } catch (Exception e) {
            System.out.println(e);
            return null;
        }
```
### System
Remote Platform: Windows 10
Firefox version: 68
Selenium: 3.141.59
Selenium Hub: Browser Stack

### Expected result

1. Browser opened
2. Profile loaded with the extension
3. Browser can be interacted using RemoteWebDriver

**Comment by ghost** [comment]
👋 Hi there! Thank you for creating this issue.

I am the Selenium Assistant Bot 🤖, I triage issues in this repository. If I can't do it, I label it to help maintainers identify issues that need triaging.

I am an Open Source project 🙌, post bugs or ideas [here](https://github.com/SeleniumHQ/selenium-assistant)!

**Comment by ghost** [comment]
❗️ It seems this issue is not using any of the supported templates

💡 Supported issue types are (they start with):

* 🐛 Bug Report (bugs found in a recent release)
* 🚀 Feature Proposal (a useful feature you would like to propose)
* 💥 Regression Report (a supported feature is not working anymore)

Issue templates help this project to stay in shape, please use them and fill them out completely. By doing that you are helping the project because the community and maintainers can provide prompt feedback, and potentially solve the issue.

If you are asking a question, a better way to address this is:

* 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
* 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
* 🗣 Join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well

If you think this is incorrect, please feel free to open a new issue.
