### ISSUE TITLE
geolocation permisson on linux

### ISSUE THREAD

**Issue by luobm01** [SeleniumHQ/selenium#9769]
Recently I am using selenium to write a program that run on Linux(ubuntu 20.04).A visit to a web page, it prompts me it needs geolocation permissions.In the code, I've given it geolocation permissions：
```
chrome_options = Options()
chrome_options.add_argument('disable-infobars')
chrome_options.add_argument('--headless')
chrome_options.add_experimental_option("prefs",{"profile.default_content_setting_values.geolocation": 1})
```
and I've set my location:
```
Map_coordinates = dict({
        "latitude": latitude,
        "longitude": longitude,
        "accuracy": 98
    })

self.execute_cdp_cmd("Emulation.setGeolocationOverride", Map_coordinates)
```
but apparently didn't work.
Why?What should I do?(The code is can be used on Windows, no longer warrant permissions)

**Comment by ghost** [comment]
👋 Hi there! Thank you for creating this issue.

I am the Selenium Assistant Bot 🤖, I triage issues in this repository. If I can't do it, I label it to help maintainers identify issues that need triaging.

I am an Open Source project 🙌, post bugs or ideas [here](https://github.com/SeleniumHQ/selenium-assistant)!

**Comment by ghost** [comment]
❗️ It seems this issue is not using any of the supported templates

💡 Supported issue types are (they start with):

* 🐛 Bug Report (bugs found in a recent release)
* 🚀 Feature Proposal (a useful feature you would like to propose)
* 💥 Regression Report (a supported feature is not working anymore)

Issue templates help this project to stay in shape, please use them and fill them out completely. By doing that you are helping the project because the community and maintainers can provide prompt feedback, and potentially solve the issue.

If you are asking a question, a better way to address this is:

* 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
* 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
* 🗣 Join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well

If you think this is incorrect, please feel free to open a new issue.
