### ISSUE TITLE
 Add support for "webSocketUrl" capability to opt-in to WebDriver BiDi support

### ISSUE THREAD

**Issue by whimboo** [SeleniumHQ/selenium#9817]
## 🚀 Feature Proposal

Browser vendors are going to add [WebDriver BiDi](https://w3c.github.io/webdriver-bidi/) support, and as such it is required to support the [webSocketUrl](https://w3c.github.io/webdriver-bidi/#establishing) capability. 

## Motivation

Even Selenium not supporting any commands and events yet, it would be great to support this capability at least. Could this maybe done for the Selenium 4 release?

Right now at least the Python implementation completely ignores this capability, and doesn't send it to the remote end. I assume that other bindings might behave the same.

## Example

This would be up to the individual binding.

CC'ing @AutomatedTester and @shs96c. Already filed as issue #9816 but that got closed immediately by the bot.

**Comment by diemol** [comment]
I have not followed the BiDi spec development so much, but I wonder why this capability is not turned on by the browser driver by default?

**Comment by jgraham** [comment]
Because starting a BiDi connection creates several additional issues:
* There is a performance cost to starting the additional server
* The BiDi server is an additional point of failure. For example it might fail to bind to a port.
* It's an additional attack surface to worry about.

So the conservative default should only be to start the BiDi server in cases where the user has explictly opted in and expects to actually use the BiDi functionality. It may be that Selenium 4 users always want to opt-in where possible. That's fine, but it's not a sufficient reason to change the default for all users.

**Comment by shs96c** [comment]
Selenium will likely always start the bidi connection. The problem that we have is that users are often unaware which features of Selenium are based on bidi and which aren't (indeed, for a while, some might be provided by a mixture of CDP and Bidi until we can switch completely to the standard), and by the time they're aware there's no mechanism to enable Bidi mid-test.

Ideally, we'll reformulate the original WebDriver spec in terms of Bidi, and at that point, there will only be one network connection needed (to bidi) in order to automate browsers.

**Comment by jgraham** [comment]
Sure, that all seems fine. If Selenium 4 is always going to use the BiDi connection it makes sense for it to always set that capability. I don't think the possibility of reformulating WebDriver on top of BiDi (or any other BiDi-only scenario) really changes much here; in that case you're making a direct websocket connection to the browser, and when you do that the webSocketUrl capability isn't used.

**Comment by jimevans** [comment]
This is implemented in .NET in fe91134

**Comment by diemol** [comment]
This was implemented across all bindings.

**Comment by whimboo** [comment]
Amazing! Thanks a lot!
