### ISSUE TITLE
Firefox loggingPrefs ignored

### ISSUE THREAD

**Issue by sjelin** [SeleniumHQ/selenium#983]
In [this small example](https://github.com/sjelin/webdriver-bugs/blob/master/firefox-log.js) I set the log level to `'WARNING` bug still see info level logs like:

```
03:13:44.002 INFO - Executing: [get: http://www.google.com])
03:13:46.188 INFO - Done: [get: http://www.google.com]
03:13:46.197 INFO - Executing: [execute script: window.HELLO_WORLD = "I am in your log :(", []])
03:13:46.254 INFO - Done: [execute script: window.HELLO_WORLD = "I am in your log :(", []]
```

What's up with that?  Google-ing around it seems like maybe this option is just ignored?  Why's it even there then?

**Comment by lukeis** [comment]
because it seems you are using the standalone server. The capabilities log levels you are trying to set are in the Firefox Driver itself, which would get logged to the browser console (different than your OS terminal console)

to suppress the logging on the standalone server you need to do it like this:

    java -Djava.util.logging.config.file="logging.properties" -jar selenium-standalone-server-2.47.1.jar

where logging.properties is a file that contains:

    .level = WARNING

note that almost all messages are 'INFO' level... so when you run your server like this you'll basically see no output at all.
