### ISSUE TITLE
class org.openqa.selenium.remote.RemoteWebDriver cannot be cast to class org.openqa.selenium.html5.WebStorage

### ISSUE THREAD

**Issue by agingorange** [SeleniumHQ/selenium#9844]
## 🐛 Bug Report

From your test LocalStorageTest.java:

`LocalStorage local = ((WebStorage) driver).getLocalStorage();`

This works when using a local webdriver. When using a remote webdriver the following error is presented:

java.lang.ClassCastException: class org.openqa.selenium.remote.RemoteWebDriver cannot be cast to class org.openqa.selenium.html5.WebStorage (org.openqa.selenium.remote.RemoteWebDriver and org.openqa.selenium.html5.WebStorage are in unnamed module of loader 'app')

What does work is the 'hack' posted on [StackOverflow][1]:

    RemoteExecuteMethod executeMethod = new RemoteExecuteMethod((RemoteWebDriver) driver);
    RemoteWebStorage webStorage = new RemoteWebStorage(executeMethod);
    LocalStorage storage = webStorage.getLocalStorage();
    storage.setItem("test", "test");

[1]: https://stackoverflow.com/questions/57593369/webstorage-with-remotewebdriver/57603243#57603243

**Comment by shs96c** [comment]
Not all drivers support webstorage, so the default `RemoteWebDriver` doesn't support it.

In rc2, we've extended the `Augmenter` to handle those browsers that claim to support it via the `webStorageEnabled` capability. If after the update your remote web driver doesn't implement the interface, it's likely because it's not returning this capability name.

To use the Augmenter:

```
driver = new Augmenter().augment(driver);
```
