### ISSUE TITLE
Unable to launch the driver after upgrading to version 4.0.0-alpha-7

### ISSUE THREAD

**Issue by geethub17** [SeleniumHQ/selenium#9888]
##  Unable to launch the driver with version 4.0.0-alpha-7

Trying to launch the driver with Selenium 4.0.0-alpha-7 version but getting unexpected error.

## To Reproduce

**Earlier maven dependency**:
```
<dependency>
   <groupId>org.seleniumhq.selenium</groupId>
   <artifactId>selenium-java</artifactId>
   <version>3.141.59</version>
</dependency>
```

**Updated maven dependency**:

```
<dependency>
   <groupId>org.seleniumhq.selenium</groupId>
   <artifactId>selenium-java</artifactId>
   <version>4.0.0-alpha-7</version>
</dependency>
```

**Code**:

```
System.setProperty("webdriver.chrome.driver", "path to chromeDriver");
WebDriver driver = new ChromeDriver();
driver.get("https://www.google.com");
```

**Error**:
```
Exception in thread "main" java.lang.AbstractMethodError: org.openqa.selenium.remote.service.DriverService$Builder.createArgs()Lcom/google/common/collect/ImmutableList;
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:358)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:119)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:105)
```
## Expected behavior

Chrome driver should be launched and should navigated to google.

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 92.0.4515.107
Browser Driver version: ChromeDriver 92.0.4515.107
Language Bindings version: Java 1.8 
Selenium Grid version (if applicable): No
IDE: Eclipse

**Note**: 

- I created a sample project from scratch by with version `4.0.0-alpha-7` and that is working fine (able to launch driver successfully) but issue occurs when upgrading from ` 3.14` to `4.0.0-alpha-7`
- I did force update for the Maven project
- Cleaned and rebuilt the project

**Comment by ghost** [comment]
❗️ It seems this issue is not using any of the supported templates. This is a volunteer-run project that receives a lot of issues that do not provide sufficient information needed to provide proper help.
💡 Please select which of these best represents your concern, and make sure you provide all of the requested information:
* 🐛 [Bug Report](https://github.com/SeleniumHQ/selenium/issues/new?template=bug.md) (bugs found in a recent release)
* 🚀 [Feature Proposal](https://github.com/SeleniumHQ/selenium/issues/new?template=feature.md) (a useful feature you would like to propose)
* 💥 [Regression Report](https://github.com/SeleniumHQ/selenium/issues/new?template=regression.md) (a supported feature is not working anymore)

If you are asking a question, a better way to address this is:

* 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
* 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
* 🗣 Join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well
