### ISSUE TITLE
A recommendation on the document

### ISSUE THREAD

**Issue by jingedawang** [SeleniumHQ/selenium#9900]
Strongly recommend that tell users not use Power shell to run this command!!
![image](https://user-images.githubusercontent.com/7996256/136889597-09b06ec8-c6f6-4a84-9c21-57d5f7ebaa68.png)

I use Power shell to run this command and all my PATH env lost.

**Comment by ghost** [comment]
👋 Hi there! Thank you for creating this issue.

I am the Selenium Assistant Bot 🤖, I triage issues in this repository. If I can't do it, I label it to help maintainers identify issues that need triaging.

I am an Open Source project 🙌, post bugs or ideas [here](https://github.com/SeleniumHQ/selenium-assistant)!

**Comment by ghost** [comment]
❗️ It seems this issue is not using any of the supported templates. This is a volunteer-run project that receives a lot of issues that do not provide sufficient information needed to provide proper help.
💡 Please select which of these best represents your concern, and make sure you provide all of the requested information:
* 🐛 [Bug Report](https://github.com/SeleniumHQ/selenium/issues/new?template=bug.md) (bugs found in a recent release)
* 🚀 [Feature Proposal](https://github.com/SeleniumHQ/selenium/issues/new?template=feature.md) (a useful feature you would like to propose)
* 💥 [Regression Report](https://github.com/SeleniumHQ/selenium/issues/new?template=regression.md) (a supported feature is not working anymore)

If you are asking a question, a better way to address this is:

* 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
* 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
* 🗣 Join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well
