### ISSUE TITLE
Error Building dotnet project in Windows

### ISSUE THREAD

**Issue by sarvaje** [SeleniumHQ/selenium#9914]
Hello,

I'm trying to build the dotnet project in windows but I'm having issues.
I have tried to build it using two different ways:

1. Using Visual Studio 2019. After installing the dependencies, I'm able to build the `Webdriver` project, but when I try to build the project `Webdriver.Common.Tests` then I get some issues similar to the this one: 
```txt
C:/users/<user>/_bazel_<user>/io65vnbs/external/maven/BUILD:1737:8: Executing genrule @maven//:io_netty_netty_transport_native_epoll_4_1_67_Final_extension failed: (Exit 127): bash.exe failed: error executing command
```
2. Using the command line. Running the command `bazel build dotnet/...`
```txt
ERROR: C:/github/selenium/dotnet/src/webdriverbackedselenium/BUILD.bazel:227:11: in src attribute of nuget_push rule //dotnet/src/webdriverbackedselenium:publish: '//dotnet/src/webdriverbackedselenium:package' must produce a single file
ERROR: C:/github/selenium/dotnet/src/webdriverbackedselenium/BUILD.bazel:227:11: Analysis of target '//dotnet/src/webdriverbackedselenium:publish' failed
ERROR: file 'dotnet/test/common/bazelout/netcoreapp2.1/Newtonsoft.Json.dll' is generated by these conflicting actions:
Label: //dotnet/test/common:edge, //dotnet/test/common:firefox
RuleClass: nunit_test rule
Configuration: aa07a07519e82af810774c182569ca55c645d883994ca9f38206e0a45c93967d
Mnemonic: CopyFile
Action key: 8e55144576d1ad53f03a8496f5eef0c6956cea29389c534297527ed5abb5881c, 1170696927e279935540456bb63d6023998c9e71393f04e77a136632e239f270
Progress message: Copying files
PrimaryInput: File:[C:/users/<user>/_bazel_<user>/io65vnbs/external/json.net[source]]lib/netstandard2.0/Newtonsoft.Json.dll
PrimaryOutput: File:[[<execution_root>]bazel-out/x64_windows-fastbuild/bin]dotnet/test/common/bazelout/netcoreapp2.1/Newtonsoft.Json.dll
Owner information: ConfiguredTargetKey{label=//dotnet/test/common:edge, config=BuildConfigurationValue.Key[aa07a07519e82af810774c182569ca55c645d883994ca9f38206e0a45c93967d]}, ConfiguredTargetKey{label=//dotnet/test/common:firefox, config=BuildConfigurationValue.Key[aa07a07519e82af810774c182569ca55c645d883994ca9f38206e0a45c93967d]}
MandatoryInputs: Attempted action contains artifacts not in previous action (first 5):
        dotnet/test/common/edge-copy-files.bat
Previous action contains artifacts not in attempted action (first 5):
        dotnet/test/common/firefox-copy-files.bat
Outputs: are equal
ERROR: com.google.devtools.build.lib.skyframe.ArtifactConflictFinder$ConflictException: com.google.devtools.build.lib.actions.MutableActionGraph$ActionConflictException: for dotnet/test/common/bazelout/netcoreapp2.1/Newtonsoft.Json.dll, previous action: action 'Copying files', attempted action: action 'Copying files'
INFO: Elapsed time: 57.083s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (360 packages loaded, 12877 targets configured)
```

Any idea what can be the issue?

Thanks.

**Comment by ghost** [comment]
👋 Hi there! Thank you for creating this issue.

I am the Selenium Assistant Bot 🤖, I triage issues in this repository. If I can't do it, I label it to help maintainers identify issues that need triaging.

I am an Open Source project 🙌, post bugs or ideas [here](https://github.com/SeleniumHQ/selenium-assistant)!

**Comment by ghost** [comment]
❗️ It seems this issue is not using any of the supported templates. This is a volunteer-run project that receives a lot of issues that do not provide sufficient information needed to provide proper help.
💡 Please select which of these best represents your concern, and make sure you provide all of the requested information:
* 🐛 [Bug Report](https://github.com/SeleniumHQ/selenium/issues/new?template=bug.md) (bugs found in a recent release)
* 🚀 [Feature Proposal](https://github.com/SeleniumHQ/selenium/issues/new?template=feature.md) (a useful feature you would like to propose)
* 💥 [Regression Report](https://github.com/SeleniumHQ/selenium/issues/new?template=regression.md) (a supported feature is not working anymore)

If you are asking a question, a better way to address this is:

* 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
* 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
* 🗣 Join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well
