### ISSUE TITLE
Unable to send value to input text in firefox 38, selenium 2.47.1

### ISSUE THREAD

**Issue by nofard** [SeleniumHQ/selenium#993]
Selenium 2.47.1, firefox 38 - When trying to fill in a form, elem.sendKeys("String") isn't working, the input remains empty 50% of the time.
Works in debug, but when running it doesn't work. Also I've tried to put some sleeps and wait for elements but still it didn't work.

In the previous version of selenium it didn't work 90% of the time.

Is it a familiar issue?

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
