### ISSUE TITLE
[🚀 Feature]: OpenTelementry tracing: be able to link the default tracing with a custom tracing

### ISSUE THREAD

**Issue by llatinov** [SeleniumHQ/selenium#9943]
### Feature and motivation

Be able to link custom OpenTelemetry tracing with the default Selenium grid tracing. See for e.g. https://github.com/llatinov/selenium-observability-java/blob/324b500316be34f5f1426720353d0c4e2e8b5a89/selenium-tests/src/main/java/com/automationrhapsody/observability/TracingWebDriver.java#L81 
It will be useful if I am able to pass my Span as a parent span of Selenium's RemoteWebDriver tracing, so I can trace my actions with corresponding grid actions.

### Usage example

Implement a custom tracing that monitors the tests. It will be of great help to be able to make the default server/grid tracing a child of the custom tracking. In this case, users can monitor how a click of a button in their tests links to grid performance.

**Comment by pujagani** [comment]
Thank you for providing the details and helping us understand the feature required. We do have a way to trace a request from the client to the server. As far as I understand, connecting a trace should not be a problem as long as the correct trace headers are present. Please refer to https://www.selenium.dev/documentation/webdriver/remote_webdriver/#beta-2-onwards. Any chance you have tried this out and it did not suffice or function? 
If so, we can then ideate on how to get this up and running.

**Comment by llatinov** [comment]
Hello, I have tried this, and it is working correctly. As you said, it is tracing the request from the client to the server. What I want is a different use case. I am instrumenting my tests, and I have linked them with the application under test, so I can trace the whole setup. Both traces - my custom one and Selenium default one are not connected in any way. What I suggest here is to link both traces, so while tracing the tests and application, users can get additional information on how the grid had performed meanwhile.

**Comment by pujagani** [comment]
👋  I understand the requirement better after pulling in the project you shared and trying to hook it up with Selenium's observability. Thank you for sharing the repo information and providing the detailed requirement and motivation. 
After a few attempts yesterday, the change needed does not seem straightforward. Essentially context propagation is the issue here. Passing a Span and using it to create a child span in the RemoteWebDriver does not seem to be a straightforward option, because we have an internal wrapper around OpenTelemetry to ensure compatibility and ease of changes with the upgrade. 
Hence, the only way I see is passing the context will fix it. I have tried to pass the context from the repo to the RemoteWebDriver instance, but even that has not done the trick. It is probably due to how the creation of a span updates it each time and then linking to that updated context becomes tricky. Let me know if you have some insights on the same! I would appreciate any thoughts or suggestions. Thank you!

**Comment by llatinov** [comment]
I checked the wrapper you have. I also believe passing the context down to the Selenium wrapper might be a good approach. WIll do some experiments and will update the issue.

**Comment by llatinov** [comment]
@pujagani I have attached an experimental branch. I set my context into OpenTelemetryTracer and then Selenium uses it from there. In my code I set the context with: OpenTelemetryTracer.getInstance().setOpenTelemetryContext(Context.current().with(span));

This achieves what I need. Please, take a look and let me know if this can fit into the Selenium architecture concepts. If so, I will add tests and create a PR.

![full_traces](https://user-images.githubusercontent.com/10547692/140615868-609f7c10-470e-472d-bf50-2fecce9ffa74.png)

**Comment by pujagani** [comment]
Thank you for sharing the details and the code. I achieved something similar, but locally I was using the OpenTelemetry APIs rather than the wrapper APIs we have. The next step was for me was to create methods to set the context and get the same context and use it as needed to stitch it all together. 

![Screenshot 2021-11-08 at 11 02 03 AM](https://user-images.githubusercontent.com/10705590/140689459-ffada495-fb96-48b7-b092-f0b9f99abea8.png)

I think your changes achieve what I was intending with my local changes. Appreciate your time and effort on this. Please create a PR. Thank you for your contribution :)

**Comment by llatinov** [comment]
@pujagani thanks for merging the PR, I am expecting the next release to try it out. When the next version is released, I believe is good to update the documentation: https://www.selenium.dev/documentation/webdriver/remote_webdriver/ ?

**Comment by pujagani** [comment]
Thank you for your contribution. Yes, after the next release, it is a good idea to update the documentation regarding the support of integration with custom tracing.
