### ISSUE TITLE
[🐛 Bug]: Session still active after driver.quit() is called

### ISSUE THREAD

**Issue by attiladobos** [SeleniumHQ/selenium#9959]
### What happened?

I deployed Selenium 4.0.0 GRID (commit hash: 50fecc4c098b3f80b64b9cb3129ace6bbf07065e) into a Kubernetes cluster by applying k8s-deployment-full-grid.yaml.

I created a test in a NodeJS/Typescript/Cucumber environment. It navigates to a site, performs a login procedure and gets forwarded to an another page.

The driver is built as follows:

`    this.driver = new Builder()
      .usingServer(env.SELENIUM_REMOTE_URL)
      .forBrowser('chrome')
      .setChromeOptions(new Options().headless().windowSize({ width: 1920, height: 1080}).addArguments('--no-sandbox'))
      .build();
`

The test executes perfectly, all elements are found, the sequence completes.
At the end of the test suite the session is closed by:
`
    await this.driver.close();
    await this.driver.quit();``
`
The test ends, but when I query the /status endpoint on the Selenium Router I see the chrome's session slot still being used with the same session ID I just terminated.

This session remains there
 indefinitely until / I redeploy the services.

I have attached wireshark logs from the chrome and the router nodes, also application logs:
[hanging_session_wireshark.zip](https://github.com/SeleniumHQ/selenium/files/7382491/hanging_session_wireshark.zip
[hanging_session_app_log.zip](https://github.com/SeleniumHQ/selenium/files/7382515/hanging_session_app_log.zip)
)

### How can we reproduce the issue?

```shell
1) Use the aforementioned k8s deployment yaml to deploy the solution into a k8s cluster.
2) Create a chrome session by building a driver described in the previous section
3) You do not have to perform any browser action
4) Quit the session either with close()/quit() or simply quit().
5) Check the router/session page to see the session being stuck.
```

### Relevant log output

```shell
Relevant logs are attached in the first block (app logs / wireshark logs)
```

### Operating System

Linux

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

chrome / firefox

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 94.0.4606.61

### Are you using Selenium Grid?

4.0.0

**Comment by pujagani** [comment]
Hello!
Thank you for sharing the details and the detailed logs. I have attempted to run a local fully distributed Grid setup on my machine and created a session multiple times. Every time `driver.quit() ` is called, the session is deleted. I do not suspect any problem with how session deletion is handled in the codebase. 

All the components of the Grid talk to each other either use HTTP requests or send messages via the event-bus. Based on the logs of Grid components, I have noticed that most of them (except Router) have this error : 
```
15:26:49.253 WARN [UnboundZmqEventBus$PollingRunnable.run] - Caught exception while polling for event bus messages: Unable to parse: =0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1
Accept-Encoding: gzip
Authorization: Bearer eyJhbGciOiJSUzI1
org.openqa.selenium.json.JsonException: Unable to parse: =0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1
Accept-Encoding: gzip
Authorization: Bearer eyJhbGciOiJSUzI1
	at org.openqa.selenium.json.Json.toType(Json.java:57)
	at org.openqa.selenium.json.Json.toType(Json.java:50)
	at org.openqa.selenium.events.zeromq.UnboundZmqEventBus$PollingRunnable.run(UnboundZmqEventBus.java:229)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.openqa.selenium.json.JsonException: Unable to determine type from: =. Last 1 characters read: =
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'selenium-chrome-node-deployment-588d9c5748-f4r6t', ip: '10.150.59.70', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.198-152.320.amzn2.x86_64', java.version: '11.0.11'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:126)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:141)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
	at org.openqa.selenium.json.Json.toType(Json.java:71)
	at org.openqa.selenium.json.Json.toType(Json.java:55)
	... 7 more

```

This error is happening since invalid JSON is being sent to the EventBus. Is it possible for you to check how and why that could be happening? Are there any other components on your end sending messages to the EventBus and they should not be doing so? Will appreciate if you could have a look. Since locally I do not see the Grid components sending any bad payload to each other. So I am wondering what is causing that error. 

My hunch is that after the error, the components are no longer able to process any events in the future (this calls for better error handling on our end and I am trying to recreate similar situation). Hence the SessionMap is unable to get the event to delete the session and the session just sticks around until everything is restarted.

**Comment by attiladobos** [comment]
Hello!
Thank You for looking into the issue so quickly!
I have been analyzing those error logs and found out they are generated by requests coming from the Prometheus service. It is making calls to the /metrics endpoint of the pods to gather performance/health related information.
I have requested the exclusion of the selenium related pods for now, but currently waiting for the action to be carried out.
Regarding the repro of the issue, You may find the request causing the exceptions in the wireshark logs. If any other logs are required or if I can assist any other way let me know.
Thank You again for your help!

**Comment by pujagani** [comment]
Thank you for the details. I now understand the situation better. I did see the /metrics request giving `404 not found` error in the wireshark logs but not sure how is that reaching the EventBus. 
I am trying to see if an JSON error faced by the EventBus causes it to hang, since that is not ideal. Thank you for the quick response! Please let me know excluding the pods or preventing the /metrics request from reaching the EventBus helps.

**Comment by pujagani** [comment]
Hey! The issue where a JSON parsing error prevents further messages from being processed is handled as part of https://github.com/SeleniumHQ/selenium/commit/6bbafcdde8ac904b9bf9f88e8c9e9423c0d5d99d. The changes will be available in the next release.

**Comment by diemol** [comment]
This issue is usually caused by requests sent to the EventBus, requests that do not have the usual message structure. So the parsing was breaking and then listening to messages was stopped. The fixes from above fix this.
