### ISSUE TITLE
[🐛 Bug]: selenium-webdriver gem warns about deprecation but does not match docs

### ISSUE THREAD

**Issue by DreadPirateShawn** [SeleniumHQ/selenium#9971]
### What happened?

Using the latest Ruby selenium-webdriver gem (4.0.3), the `Selenium::WebDriver.for` method is documented to take `desired_capabilities:` -- see the third example in https://www.selenium.dev/selenium/docs/api/rb/Selenium/WebDriver.html#for-class_method

However, attempting to use this triggers a deprecation warning.

### How can we reproduce the issue?

```shell
require "selenium-webdriver"
Selenium::WebDriver.for :remote,  desired_capabilities: {}
```

### Relevant log output

```shell
2021-10-22 02:42:57 WARN Selenium [DEPRECATION] [:desired_capabilities] :desired_capabilities as a parameter for driver initialization is deprecated. Use :capabilities with an Array value of capabilities/options if necessary instead.
```

### Operating System

Ubuntu 20.04.2 LTS

### Selenium version

4.0.3

### What are the browser(s) and version(s) where you see this issue?

remote

### What are the browser driver(s) and version(s) where you see this issue?

remote

**Comment by DreadPirateShawn** [comment]
Note, same problem exists with https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings with examples that include the `desired_capabilities:` parameter -- as well as similar usage of the `options:` parameter. Using example `options:` code directly from that page results in:
```
2021-10-22 03:05:32 WARN Selenium [DEPRECATION] [:browser_options] :options as a parameter for driver initialization is deprecated. Use :capabilities with an Array of value capabilities/options if necessary instead.
```

**Comment by justinko** [comment]
@DreadPirateShawn thank you for reporting -- am experiencing this as well

**Comment by titusfortner** [comment]
Good catch, we can update the docs to show the recommended code.

Selenium 3 `Options` was only for Browser Options, and you needed `Capabilities` to do any top level options and it allows a complete Hash / String keys conversion to capabilities. Options tries to be more controlled with Symbols only and specific parameters, and it now supports top level as well. To distinguish "new way" from the "old way" we decided to use `capabilities` keyword instead of changing what `options` keyword did, but it is unfortunately more confusing than would be nice because it is different from the other bindings. We'll probably need to make more adjustments in future releases to keep things in better sync with other bindings..

**Comment by titusfortner** [comment]
Example has been updated (aceb6e2561fc070ee4e830413b2c1bb30c6c2492) and the wiki has been marked as unofficial. The correct content will be added to the [official documentation](https://www.selenium.dev/documentation/)
