### ISSUE TITLE
Pass command-line arguments to Firefox

### ISSUE THREAD

**Issue by smarts** [SeleniumHQ/selenium#998]
WebDriver should provide a way to pass [command-line arguments](https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options#How_to_use_command_options) when launching Firefox

**Comment by lukeis** [comment]
we do... in Java,  you would create a FirefoxBinary object and then call addCommandLineOptions, you then pass that binary to FirefoxDriver.

**Comment by jleyba** [comment]
Since you referenced this from protractor, you would use the [`selenium-webdriver/firefox.Binary`](http://seleniumhq.github.io/selenium/docs/api/javascript/module_selenium-webdriver_firefox_binary_class_Binary.html) class. More usage information is included in the docs for the [`selenium-webdriver/firefox`](http://seleniumhq.github.io/selenium/docs/api/javascript/module_selenium-webdriver_firefox.html) module.

**Comment by jrharshath** [comment]
The links in the previous comment seem to have moved to a new location

**Comment by enikolov** [comment]
Found them here:
https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/firefox/index.html
